<form action="" method="post">
    <div class="photos">
        <div class="photo" style="text-align:right;">
            <input id="file_upload" name="file_upload" type="file" />
        </div><!-- closes photo -->
        <?php foreach($this->pictures as $pic): ?>
        <div class="photo">
            <?= $this->thumbnail(array('width'=>133,'height'=>92), $pic->url, '','133:92') ?>
            <strong>Add a description</strong>
            <input type="text" name="pic[<?= $pic->id ?>][location]" value="<?= $pic->location ?>" />
            <a href="#img_delete_<?= $pic->id ?>" class="lb link-7">Delete Photo</a>
        </div><!-- closes photo -->
        <?php endforeach ?>
    </div><!-- closes photos -->
    <div class="foot">
        <input type="submit" class="btn-1" value="Save Changes" />
        <a href="/provider/listings/desactivate/<?= $this->listing->id ?>">Deactivate Listing</a>
    </div><!-- closes foot -->
	<input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token.'edit_picture') ?>" />
    <input type="hidden" name="_task" value="<?= md5('edit_picture') ?>" />
</form>
