<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->trip->title ?>, Package Checkout | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/cart/checkout.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
  	<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="main wrapper">
            <div class="checkout-wrapper">
                <div class="left">
                    <div class="header_checkout">
                        <h2><?= $this->trip->title ?></h2>
                        <p><strong><?= $this->country->title ?></strong></p>
                        <span class="label"><?= ($this->trip->days > 1) ? $this->trip->days.' Days' : '1 Day' ?> Trip<em></em></span> 
                        <?= $this->thumbnail(array('width'=>650,'height'=>138), $this->trip->image, '', '650:138') ?>
                    </div><!--HEADER_CHECKOUT-->
                    <div class="warnings">
                    	<h3>The following information is missing or wrong</h3>
                    	<ul>
                    		<li>- The Credit Card Number required</li>
                    		<li>- The Cardholder Name is wrong</li>
                    		<li>- The Expiration Date is wrong</li>
                    		<li>- The Security Code is wrong</li>
                    		<li>- Please accept the terms and conditions</li>
                    	</ul>
                    </div><!--WARNINGS-->
                    <form id="checkout" action="/en-US/cart/charge" method="post">
                        <div class="checkout-item first">
                            <div class="ttl"><span>1</span><strong>How it works</strong></div>
                            <p class="process">Please provide your billing details now. <strong>You will not be charged unless 
                            the partners accept your requests (within 24 hours)</strong>. If some of the partners declines or does 
                            not respond, no charge is made and you can try booking again or with someone else. </p>
                        </div><!-- div checkout-item -->
                        <div class="checkout-item">
                            <div class="ttl"><span>2</span><strong>Payment</strong></div>
                            <div class="payment-item">
                                <?php if(count($this->accounts) > 0): ?>
	                            <?php foreach($this->accounts as $i => $a): ?>
                                <div class="saved-card">
                                    <label for="card-1">
                                    	<?php $checked = ($i == 0) ? 'checked="checked"' : '' ?>
                                        <input <?= $checked ?> type="radio" name="account" value="<?= $a->id ?>" />
                                        <span class="card-name"><img src="<?= $this->creditcards[$a->type] ?>" width="30" height="20" alt="" />
                                        <?= $a->type ?></span> <span class="card-number">************<?= $a->last4 ?></span> </label>
                                </div><!--SAVED-CARD-->
                                <?php endforeach ?>
                                <?php endif ?>
                                <div class="new-card">
                                	<?php $checked = (count($this->accounts) == 0) ? 'checked="checked"' : '' ?>
                                    <input name="account" type="radio" value="new" <?= $checked ?> />
                                    <div class="cont">
                                        <div class="ttl-select">
                                            <label for="new-card">Enter a New Credit Card</label>
                                            <ul class="cards">
                                            </ul>
                                        </div><!--TTL-->
                                        <div class="item">
                                        	<div>
                                                <p><strong>Cardholder Name</strong> No dashes or spaces</p>
                                                <input type="text" value="" class="cname" autocomplete="off" />
                                            </div>
                                        </div><!--ITEM-->
                                        <div class="item">
                                        	<div>
                                                <p><strong>Credit Card Number</strong> As it appears on the credit card</p>
                                                <input type="text" value="" id="credit-card" class="cnum" autocomplete="off" />
                                            </div>
                                        </div><!--ITEM-->
                                        <div class="item">
                                        	<div>
                                                <p><strong>Expiration Date</strong> Only month and year required</p>
                                                <select class="cmonth">
                                                    <option value="">--</option>
                                                    <option value="01">Jan (01)</option>
                                                    <option value="02">Feb (02)</option>
                                                    <option value="03">Mar (03)</option>
                                                    <option value="04">Avr (04)</option>
                                                    <option value="05">May (05)</option>
                                                    <option value="06">Jun (06)</option>
                                                    <option value="07">Jul (07)</option>
                                                    <option value="08">Aug (08)</option>
                                                    <option value="09">Sep (09)</option>
                                                    <option value="10">Oct (10)</option>
                                                    <option value="11">Nov (11)</option>
                                                    <option value="12">Dec (12)</option>
                                                </select>
                                                <select class="cyear">
                                                    <option value="">----</option>
                                                    <option value="2011">2011</option>
                                                    <option value="2012">2012</option>
                                                    <option value="2013">2013</option>
                                                    <option value="2014">2014</option>
                                                    <option value="2015">2015</option>
                                                    <option value="2016">2016</option>
                                                    <option value="2017">2017</option>
                                                    <option value="2018">2018</option>
                                                    <option value="2019">2019</option>
                                                    <option value="2020">2020</option>
                                                    <option value="2021">2021</option>
                                                </select>
                                            </div>
                                        </div><!--ITEM-->                                        
                                        <div class="item last">
                                        	<div>
                                                <p><strong>Security Code</strong><a href="#" class="helptip">What is this?</a></p>
                                                <p class="tip hidden"><span></span>The 3 or 4 digit value printed on the card or signature strip</p>
                                                <input maxlength="4" type="text" class="ccode sscode" />
                                                <div class="clear"></div>
                                            </div>
                                        </div><!--ITEM--> 
                                    </div><!--CONT--> 
                                </div><!--NEW-CARD--> 
                            </div><!-- closes payment-item -->                             
                        </div><!-- closes checkout-item -->
                        
                        <div class="checkout-item">
                            <div class="ttl"><span>3</span><strong>Policies &amp; Restriccions</strong></div>
                            <div class="card-item longer"> <strong>Cancellation</strong> <a class="high-r lb" href="#cancel_policy">High Restrictions &rarr;</a> </div>
                            <div class="card-item last">
                                <input type="checkbox" name="terms" id="terms" value="1" />
                                <label for="terms">I agree to the cancellation policy, activity restrictions and <a href="">terms of use</a>.</label>
                            </div><!-- closes card-item -->
                        
                            <div class="restricction_tip hidden">
                                <strong>50% refund up until 1 week prior to arrival, except fees</strong>
                                <ul>
                                    <li>• Cleaning fees are always refunded if the guest did not check in.</li>
                                    <li>• The Tripfab service fee is non-refundable.</li>
                                    <li>• If there is a complaint from either party, notice must be given to Tripfab 
                                    Resolution Center within 24 hours of check-in.</li>
                                    <li>• Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                    <li>• A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                    e-mail from Tripfab Resolution Center.</li>
                                </ul>
                                <span></span>
                            </div><!--RESTRICCTION_TIP-->    
                            <div class="hidden">
                            	<div id="cancel_policy" class="cancel_policy lb">
                                	<div class="top">High Restrictions Cancellation Policy</div>
                                    <div class="mid">
                                        <h3>50% refund up until 1 week prior to arrival, except fees</h3>
                                        <ul>
                                            <li>Cleaning fees are always refunded if the guest did not check in.</li>
                                            <li>The Tripfab service fee is non-refundable.</li>
                                            <li>If there is a complaint from either party, notice must be given to Tripfab 
                                            Resolution Center within 24 hours of check-in.</li>
                                            <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                            <li>A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                            e-mail from Tripfab Resolution Center.</li>
                                        </ul>
                                        <div class="inner">
                                            <img src="https://developer.tripfab.com/images2/img-67-hotel.png" width="    " height="" alt="" />
                                            <div class="specs">
                                                <div class="column">
                                                    <p>Must be made seven full days prior to listing's local check in time (or 2:00 PM 
                                                    if not specified) on the day of check in, otherwise no refund. For example, 
                                                    if check-in is on Friday, cancel by Friday of the previous</p>
                                                </div><!--COLUMN-->
                                                <div class="column">
                                                    <p>If the guest cancels less than 7 days in advance, the nights not spent are not refunded.</p>
                                                </div><!--COLUMN-->
                                                <div class="column last">
                                                    <p>If the guest arrives and decides to leave early, the nights not spent are not refunded.</p>
                                                </div><!--COLUMN-->
                                                <div class="clear"></div>
                                            </div><!--SPECS-->
                                        </div><!--INNER-->
                                    </div><!--MID-->
                           		</div><!--CANCEL_POLICY-->
                            </div> 
                            <div class="clear"></div>
                        </div><!-- closes checkout-item -->
                        
                        <div class="bottom"> <span>Grand Total<strong>$<?= $this->formatnumber($this->cartitem->total) ?></strong></span>
                            <input type="submit" class="btn-1 noclean" value="Book Trip" />
                        </div><!-- closes bottom -->
                        <input type="hidden" name="userids" value="<?= $this->user->id ?>" />
                        <input type="hidden" name="userstoken" value="<?= $this->user->token ?>" />
                        <input type="hidden" name="cartitemid" value="<?= $this->cartitem->id ?>" />
                        <input type="hidden" name="cartitemtoken" value="<?= $this->cartitem->token ?>" />
                        <input type="hidden" name="formids" value="<?= md5($this->user->token.'checkout') ?>" />
                        <input type="hidden" name="_task" value="<?= md5('purchase') ?>" />
                        <input type="hidden" name="ammount" value="<?= $this->cartitem->total ?>" />
                    </form>
                </div><!-- closes left -->
                
                <div class="right">
                    <div class="widget summary">
                        <div class="ttl">Trip Summary</div>
                        <ul>
                            <li class="checkin"><strong>Trip Starts</strong> <?= date('D, F jS, Y', strtotime($this->cartitem->checkin)) ?></li>
                            <li class="checkout"><strong>Trips Ends</strong><?= date('D, F jS, Y', strtotime($this->cartitem->checkout)) ?></li>
                            <li class="time"><strong>Trip Duration</strong> <?= $this->trip->days ?> Days</li>
                            <li class="occupation"><strong>Travelers</strong>
                                <dl>
                                    <dt>Adults</dt>
                                    <dd><?= $this->cartitem->adults ?></dd>
                                    <?php if($this->cartitem->kids > 0): ?>
                                    <dt><?= $this->cartitem->kids ?></dt>
                                    <dd>3</dd>
                                    <?php endif ?>
                                </dl>
                            </li>
                        </ul>
                        <div class="total"> <a href="#" class="booknow btn-1">Book Now</a>
                            <p>Grand Total <strong>$<?= $this->formatnumber($this->cartitem->total) ?></strong></p>
                        </div><!-- closes total --> 
                    </div><!-- closes widget --> 
                </div><!-- closes right --> 
            </div><!-- closes checkout wrapper --> 
        </div><!-- closes main --> 
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript">PUBLIC_KEY = "<?= $this->pkey ?>"; </script>
<script type="text/javascript" src="https://js.stripe.com/v1/"></script>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/cardcheck.min.js"></script>
<script type="text/javascript" src="/js2/cart/checkout.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('a.helptip').click(function() {
			$('.tip').toggleClass('hidden');
			return false;
		});
		
		$('.booknow').click(function(){
			$('#checkout').submit();
			return false;
		});
		
		$('a.lb').fancybox({
			padding: 0,
			overlayColor: '#FFF',
			overlayOpacity: '0.7',
			showCloseButton:false
		});
	});
</script>
</body>
</html>