<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?>, Reservation Checkout | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/cart/checkout.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <script type="text/javascript" src="https://js.stripe.com/v1/"></script>
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js2/jquery.input.value.js"></script>
    <script type="text/javascript" src="/js2/jquery.elastic.js"></script>
    <script type="text/javascript" src="/js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/js2/cart/checkout.js"></script>
    <script type="text/javascript" src="/js2/common.js"></script>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', 
	array('user'=>$this->user,'full'=>true)); ?>    
    <div class="w2">
        <div class="main wrapper">
            <div class="checkout-wrapper">
                <div class="left">
                    <form id="checkout" action="/en-US/cart/charge" method="post">
                        <div class="checkout-item">
                            <div class="left">
                                <span>1</span>
                                <strong>How it works</strong>
                            </div><!-- closes left -->
                            <div class="right">
                                <p>Please provide your billing details now. You will not be charged unless the host accepts your request (within 24 hours). If the host declines or does not respond, no charge is made and you can try booking with someone else. </p>
                            </div><!-- closes right -->
                        </div><!-- div checkout-item -->
                        <div class="checkout-item">
                            <div class="left">
                                <span>2</span>
                                <strong>Payment</strong>
                            </div><!-- closes left -->
                            <div class="right">
                                <div class="payment-tabs">
                                    <div class="tab">
                                        <div class="payment-item">
											<div class="card-details">
                                            	<div class="card-item longer">
                                                    <strong>Credit Card</strong>
                                                </div><!-- closes card-item -->
                                                <div class="card-item longer">
                                                    <input type="text" autocomplete="off" class="cnum" />
                                                    <strong>Credit Card Number</strong>
                                                    <span>No dashes or spaces</span>
                                                </div><!-- closes card-item -->
                                                <div class="card-item longer">
                                                    <input type="text" autocomplete="off" class="cname" />
                                                    <strong>Card Holder Name</strong>
                                                    <span>As it appears on the credit card</span>
                                                </div><!-- closes card-item -->
                                                <div class="card-item longer">
                                                    <select class="cmonth">
                                                        <option value="">--</option>
                                                        <option value="01">Jan (01)</option>
                                                        <option value="02">Feb (02)</option>
                                                        <option value="03">Mar (03)</option>
                                                        <option value="04">Avr (04)</option>
                                                        <option value="05">May (05)</option>
                                                        <option value="06">Jun (06)</option>
                                                        <option value="07">Jul (07)</option>
                                                        <option value="08">Aug (08)</option>
                                                        <option value="09">Sep (09)</option>
                                                        <option value="10">Oct (10)</option>
                                                        <option value="11">Nov (11)</option>
                                                        <option value="12">Dec (12)</option>
                                                    </select>
                                                    <select class="cyear">
                                                        <option value="">----</option>
                                                        <option value="2011">2011</option>
                                                        <option value="2012">2012</option>
                                                        <option value="2013">2013</option>
                                                        <option value="2014">2014</option>
                                                        <option value="2015">2015</option>
                                                        <option value="2016">2016</option>
                                                        <option value="2017">2017</option>
                                                        <option value="2018">2018</option>
                                                        <option value="2019">2019</option>
                                                        <option value="2020">2020</option>
                                                        <option value="2021">2021</option>
                                                    </select>
                                                    <strong>Expiration Date</strong>
                                                    <span>Only month and year required</span>
                                                </div><!-- closes card-item -->
                                                <div class="card-item longer">
                                                    <input maxlength="4" type="text" class="ccode" />
                                                    <strong>Security Code</strong>
                                                    <span><a href="">What is this?</a></span>
                                                </div><!-- closes card-item -->
                                            </div>
                                        </div><!-- closes payment-item -->
                                    </div><!-- closes tab -->
                                </div><!-- closes payment-tabs -->
                            </div><!-- closes right -->
                        </div><!-- closes checkout-item -->
                        <div class="checkout-item">
                            <div class="left">
                                <span>4</span>
                                <strong>Policies</strong>
                            </div><!-- closes left -->
                            <div class="right">
                                <div class="card-item longer">
                                    <strong>Cancellation</strong>
                                    <a href="">Moderate &rarr;</a>
                                </div><!-- closes card-item -->
                                <div class="card-item longer">
                                    <strong>Activity Requirements</strong>
                                    <a href="">Read Requirements &rarr;</a>
                                </div><!-- closes card-item -->
                                <div class="card-item longer">
                                    <input type="checkbox" name="terms" value="1" />
                                    <label>I agree to the cancellation policy and <a href="">terms of use</a>.</label>
                                </div><!-- closes card-item -->
                            </div><!-- closes right -->
                            <div class="clear"></div>
                            <div class="bottom">
                                <span>Grand Total<strong>$<?= $this->cartitem->total ?></strong></span>
                                <input type="submit" class="btn-2 noclean" value="Book Hotel" />
                            </div><!-- closes bottom -->
                        </div><!-- closes checkout-item -->
                        <input type="hidden" name="userids" value="<?= $this->user->id ?>" />
                        <input type="hidden" name="userstoken" value="<?= $this->user->token ?>" />
                        <input type="hidden" name="cartitemid" value="<?= $this->cartitem->id ?>" />
                        <input type="hidden" name="cartitemtoken" value="<?= $this->cartitem->token ?>" />
                        <input type="hidden" name="formids" value="<?= md5($this->user->token.'checkout') ?>" />
                        <input type="hidden" name="_task" value="<?= md5('purchase') ?>" />
                        <input type="hidden" name="ammount" value="<?= $this->cartitem->total ?>" />
                    </form>
                </div><!-- closes left -->
                
                <div class="right">
                    <div class="widget summary">
                        <div class="ttl">Trip Summary</div><!-- closes ttl -->
                        <ul>
                            <li>Check in <span><?= date('D, F jS Y', strtotime($this->cartitem->checkin)) ?></span></li>
                            <?php if($this->cartitem->checkout): ?>
                            <li>Check out<span><?= date('D, F jS Y', strtotime($this->cartitem->checkout)) ?></span></li>
                            <?php endif ?>
                            <?php if($this->cartitem->nights > 0): ?>
                            <li><?= $this->cartitem->nights ?> Nights</li>
                            <?php endif ?>
                            <li><?= $this->cartitem->adults ?> Adults</li>
                            <?php if($this->cartitem->kids > 0): ?>
                            <li><?= $this->cartitem->kids ?> Kids</li>
                            <?php endif ?>
                            <?php if($this->cartitem->rooms > 1): ?>
                            <li><?= $this->cartitem->rooms ?> Rooms</li>
                            <?php endif ?>
                            <?php if($this->cartitem->rooms > 1): ?>
                            <li>Maximun people per room: <?= $this->cartitem->max ?></li>
                            <?php endif ?>
                            <li>Charges
                                <table cellpadding="0" cellspacing="0" border="0">
                                    <tr>
                                    	<td><?= $this->cartitem->rate_description ?></td>
	                                    <td>$<?= $this->cartitem->rate ?></td></tr>
                                    <?php if($this->cartitem->additional): ?>
                                    <tr>
                                    	<td><?= $this->cartitem->additional_description ?></td>
                                    	<td>$<?= $this->cartitem->additional ?></td></tr>
                                    <?php endif ?>
                                    <tr>
                                    	<td>Subtotal</td>
                                    	<td>$<?= $this->cartitem->subtotal ?></td></tr>
                                    <tr>
                                    	<td>Taxes &amp; Fees</td>
                                    	<td>$<?= $this->cartitem->taxes ?></td></tr>
                                </table>
                            </li>
                        </ul>
                        <div class="total">
                            <strong>$<?= $this->cartitem->total ?></strong>
                            Grand Total
                        </div><!-- closes total -->
                    </div><!-- closes widget -->
                </div><!-- closes right -->
            </div><!-- closes checkout wrapper -->
        </div><!-- closes main -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->	
</body>
</html>