<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?>, Reservation Invoice | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
    
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>    
    <div class="w2">
        <div class="main wrapper">
            <div id="confirmation"> <img src="https://static.tripfab.com/images2/confirmation-img.png" width="" height="" alt="" />
                <div class="wrap"> <span class="stamp"></span>
                    <h2>Thank You <?= $this->user->name ?></h2>
                    <?php if($this->listing->main_type == 5): ?>
                    <h3>We wish you the best stay ever!</h3>
                    <?php else: ?>
                    <h3>We wish you the best day of your life!</h3>
                    <?php endif ?>
                    <a href="/user/reservations/print/<?= $this->reservation->id ?>" class="btn-10">Print your Reservation</a>
                    <div class="warning">
                        <p><strong>We'll confirm your reservation in the next 24 hours</strong> You will only be charged if the partner accepts your request. If our partner declines or does not respond, no charge is made.</p>
                    </div><!--WARNING-->
                    <div class="overview"> 
                        <span class="name"><?= $this->listing->title ?></span> 
                        <span class="code">Reservation Code: <?= $this->reservation->code ?></span> 
                    </div>
                    <div class="details">
                        <h4>Payment</h4>
                        <ul>
                            <li><strong>Credit Card</strong><?= $this->transaction->method ?></li>
                        </ul>
                    </div><!--DETAILS-->                    
                    <div class="details">
                    	<?php if($this->listing->main_type == 6): ?>
                        <h4>Reservation Dettails</h4>
                        <ul>
                            <li><strong>Activity Date </strong><?= date('F jS, Y', strtotime($this->reservation->checkin)) ?></li>
                            <li><strong>Travelers </strong><?= $this->reservation->adults ?> Adults
                            <?php if($this->reservation->kids > 0): ?>
                            , 1 Child<?php endif ?></li>
                        </ul>
                        <?php else: ?>
						<h4>Reservation Dettails</h4>
						<ul>
							<li><strong>Check In</strong> <?= date('F jS, Y', strtotime($this->reservation->checkin)) ?></li>
							<li><strong>Check Out</strong> <?= date('F jS, Y', strtotime($this->reservation->checkout)) ?></li>
							<li><strong>Rooms</strong> <?= $this->reservation->rooms ?> Rooms, 
                            <?= $this->reservation->nights ?> Nights</li>
							<li><strong>Ocupation</strong> <?= $this->reservation->adults ?> Adults
                            <?php if($this->kids > 0): ?>, 2 Children<?php endif ?></li>
						</ul>
                        <?php endif ?>
                    </div><!--DETAILS-->                    
                    <div class="details">
                        <h4>Total Paid</h4>
                        <dl>
                            <dt class="total">Total</dt>
                            <dd class="total">$<?= $this->formatnumber($this->transaction->ammount) ?></dd>
                        </dl>
                    </div><!--DETAILS-->
                    <div class="bottom">
                        <p><strong>Questions?</strong> Contact service@tripfab.com </p>
                        <a href="/user/reservations/view/<?= $this->reservation->id ?>">Reservation Details</a> 
                        <a href="/user/reservations/print/<?= $this->reservation->id ?>">Print Reservation</a>
                    </div><!--BOTTOM-->
                </div><!--WRAP--> 
            </div><!--CONFIRMATION-->             
        </div><!-- closes main --> 
    </div><!-- closes w2 -->
	<?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
</body>
</html>