<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Adventure Inn, Reservation Checkout | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/cart/checkout.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <script type="text/javascript" src="/js2/jquery.js"></script>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>    
    <div class="w2">
        <div class="main wrapper">
            <div id="confirmation"> <img src="/images2/confirmation-img.png" width="" height="" alt="" />
                <div class="wrap"> <span class="stamp"></span>
                    <h2>Thank You <?= $this->user->name ?>!</h2>
                    <h3>We wish you the best trip ever!</h3>
                    <a href="#" class="btn-10">Print your Reservation</a>
                    <div class="warning">
                        <p><strong>We'll contact you in the next 24 hours</strong><br />To help you with all of the details</p>
                    </div><!--WARNING-->
                    <div class="overview"> 
                    	<span class="name"><?= $this->listing->title ?></span> 
                        <span class="code">Reservation Code: <?= $this->reservation->code ?></span> 
                    </div><!--OVERVIEW-->
                    
                    <div class="details">
                        <h4>Payment</h4>
                        <ul>
                            <li><strong>Credit Card</strong><?= $this->transaction->method ?></li>
                        </ul>
                    </div><!--DETAILS-->
                    
                    <div class="details">
                        <h4>Reservation Dettails</h4>
                        <ul>
                            <li><strong>Trip Starts </strong> </li>
                            <li><strong>Trips Ends Sat,</strong> <?= date('F jS Y', strtotime($this->reservation->checkin)) ?></li>
                            <li><strong>Trip Duration</strong> <?= $this->listing->days ?> Days</li>
                            <li><strong>Travelers</strong> <?= $this->reservation->adults ?> Adults
                            <?php if($this->reservation->kids > 0) ?>
                            , <?= $this->reservation->kids ?> Children</li>
                        </ul>
                    </div><!--DETAILS-->
                    
                    <div class="details">
                        <h4>Total Paid</h4>
                        <dl>
                            <dt class="total">Total</dt>
                            <dd class="total">$<?= $this->transaction->ammount ?></dd>
                        </dl>
                    </div><!--DETAILS-->
                    
                    <div class="bottom">
                        <p><strong>Questions?</strong> Contact service@tripfab.com </p>
                        <a href="#">Reservation Details</a> <a href="#">Print Reservation</a> 
                    </div><!--BOTTOM--> 
                </div><!--WRAP--> 
            </div><!--CONFIRMATION--> 
        </div><!-- closes main --> 
    </div><!-- closes w2 -->
    <div class="footer">
	<?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
</body>
</html>