<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Oops, Page Not Found | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
    <script type="text/javascript">
	$(function(){
		$.ajax({
			url:'/ajax/getsearchtags',
			success:function(tags){
				$( "#tags" ).autocomplete({
					source:tags,
					select:function(e, ui){
						window.location = ui.item.url
					},
					appendTo:'#citiesAutocompleteContainerError'
				}).data( "autocomplete" )._renderItem = function( ul, item ) {
					return $( "<li></li>" )
					.data( "item.autocomplete", item )
					.append( '<a href="'+item.url+'">' + item.label + "</a>" )
					.appendTo( ul );
				};
			}
		});	
    });	
	</script>
    <style type="text/css">
	#citiesAutocompleteContainerError .ui-autocomplete {
		border-radius:2px;
		overflow-x:hidden;
		overflow-y:auto;
		width:462px;
		background:#fff;
		box-shadow: 0 0 10px #000000; 
		max-height: 240px;
		left:440px !important;
		top:-265px !important;
	}
	
	#citiesAutocompleteContainerError .ui-autocomplete li a {
		line-height:24px;
		color:#464646;
		padding-left:10px;
		font-weight:bold;
		display:block;
		font-size: 14px;
	}
	#citiesAutocompleteContainerError .ui-autocomplete li a:hover,  
	#citiesAutocompleteContainerError .ui-autocomplete li a.ui-state-hover {
		background: url(https://static.tripfab.com/images2/arrow-25.png) no-repeat 98% 50% #60b6e8;
		color: #FFFFFF;
		text-decoration:none;
	}
	</style>
</head>
<body>
<div class="w1" id="errorpage">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>
    <div class="w2">
        <div class="top">
            <div> </div>
        </div><!--TOP-->
        <div class="bottom">
            <div class="island"><img src="https://static.tripfab.com/images2/404-island.png"  alt="" /></div>
            <h2>You found a desert Island!</h2>
            <h3>Unfortunately Tripfab can't take you here.</h3>
            <div class="search">
                <form action="">
                    <fieldset>
                        <input type="text" id="tags" value="Where do you want to go?"  />
                        <input type="submit" class="btn-1 noclean" value="Go!" />
                    </fieldset>
                </form>
            </div><!--SEARCH--> 
            <span class="previous-page"><a href="javascript:history.go(-1)">Go back</a> to the previous page</span> 
        </div><!--BOTTOM--> 
    </div><!-- closes w2 -->
	<?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<!--
<h1>An error occurred</h1>
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)): ?>

<h3>Exception information:</h3>
<p>
<b>Message:</b> <?php echo $this->exception->getMessage() ?>
</p>

<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3>Request Parameters:</h3>
<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
</pre>

<?php endif ?>
-->
<div id="citiesAutocompleteContainerError">
</div>
</body>
</html>