<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> - Change Password | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-backend">
        	<?= $this->partial('partials/vendormainmenu.phtml', 
			array('notifications'=> $this->pendingSettings,'active'=>'Password','parentActive'=>'Account')); ?>
            <div class="listings-main">
            	<div class="sub-ttl">
	                Account - Reset Password
            	</div><!-- closes sub-ttl -->
            </div>
            <div class="vendor-profile">
                <form id="user_account" method="post" action="">
                    <?php if($this->errormessage): ?>
                    <script type="text/javascript">
					showError("<?= $this->errormessage ?>");
					</script>
                    <?php endif ?>
                    <?php if($this->successmessage): ?>
                    <script type="text/javascript">
					showAlert("Your changes have been saved");
					</script>
                    <?php endif ?>
                    <div class="profile-items">
                        <div class="item-wrppr">
                            <div class="item-ttl">
                                Password
                            </div><!-- closes item ttl -->
                            <div class="item first">
                                 <input type="password" name="opassword" />
                                <h4>Current Password</h4>
                                <span>Write your current password</span>
                            </div><!-- closes item -->
                            <div class="item">
                                <input type="password" name="npassword" />
                                <h4>New Password</h4>
                                <span>6 characters minimum</span>
                            </div><!-- closes item -->
                            <div class="item last">
                                <input type="password" name="rpassword" />
                                <h4>Re-type New Password</h4>
                                <span>Make sure you didn't have any typos in it</span>
                            </div><!-- closes item -->
                            <div class="clear"></div>									
                        </div><!-- closes item-wrppr -->
                    </div>
                    <!-- closes profile-items -->
                    <div class="foot">
                        <input type="submit" class="btn-1 noclean" value="Change Password" />
                    </div>
                    <!-- closes foot -->
                    <input type="hidden" name="userids" value="<?= $this->user->id ?>" />
                    <input type="hidden" name="usertokens" value="<?= $this->user->token ?>" />
                    <input type="hidden" name="formid" value="<?= md5($this->user->token.'change_password') ?>" />
                    <input type="hidden" name="_task" value="<?= md5('change_password') ?>" />
                </form>
            </div>
            <!-- closes vendor-profile -->
        </div>
        <!-- closes user-backend -->
    </div>
    <!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div>
<!-- closes w1 -->
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<style type="text/css">
.profile-items .item input[type="password"] {
	border: 1px solid #D8D8D8;
	border-radius: 2px 2px 2px 2px;
	color: #303030;
	float: right;
	font-size: 12px;
	height: 27px;
	padding: 0 5px;
	width: 203px;
}
.profile-items .item input[type="password"]:focus {
	border-color: #ADDEFF;
	box-shadow: 0 0 5px #ADDEFF;
}
</style>
</body>
</html>