<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Cancellation Policies | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->

</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper cw">
            <h2>Cancellation Policies for Activities</h2>
            <div class="cancellation">						
                <div class="intro">
                    <p>Tripfab allows hosts to choose among three standardized cancellation policies (Level 1, Level 2 and Level 3) that we will enforce to protect both guest and host alike. T Each listing and reservation on our site will clearly state the cancellation policy. Guests may cancel and review any penalties by viewing their travel plans and then clicking 'Cancel' on the appropriate reservation.</p>
                </div><!-- closes intro -->
                <div class="tabs">
                    <ul>
                        <li><a href="#tabs-1">Low Restictions</a></li>
                        <li><a href="#tabs-2">Medium Restrictions</a></li>
                        <li><a href="#tabs-3">High Restrictions</a></li>
                    </ul>
                    <div id="tabs-1" class="tab">
                        <h3>Full refund 1 day prior to arrival, except fees</h3>
                        <ul>
                            <li>The Tripfab service fee is refundable.</li>
                            <li>If there is a complaint from either party, notice must be given to Tripfab 
                            Resolution Center within 24 hours of the tour activity.</li>
                            <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                            <li>A reservation is not officially canceled until the guest receives a cancellation 
                            confirmation e-mail from Tripfab Resolution Center.</li>
                        </ul>
                        <div class="inner">
                            <div class="top">
                                <img src="/images2/img-65.png" alt="" />
                            </div><!-- closes top -->
                            <div class="bottom">
                                <div>
                                    Must be made 24 hours prior to listing's local arriving time on the day when the tour begins, otherwise no refund. For example, if the tour starts on Friday at 9:00 AM, the cancellation must be requested before 9:00 AM of the Thursday before.
                                </div>
                                <div>
                                    If the guest cancels less than 24 hours before the tour starts, the tour cost is not refunded.
                                </div>
                                <div>
                                    If the visitor arrives and decides to leave early, or not take the tour, the cost of the tour is 100% refunded.
                                </div>
                            </div><!-- closes bottom -->
                        </div><!-- closes inner -->
                    </div><!-- closes tab -->
                    <div id="tabs-2" class="tab">
                        <h3>Full refund 3 days prior to arrival, except fees</h3>
                        <ul>
                            <li>The Tripfab service fee is refundable.</li>
                            <li>If there is a complaint from either party, notice must be given to 
                            Tripfab Resolution Center within 24 hours of the tour activity.</li>
                            <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                            <li>A reservation is not officially canceled until the guest receives a cancellation confirmation e-mail 
                            from Tripfab Resolution Center.</li>
                        </ul>
                        <div class="inner">
                            <div class="top">
                                <img src="/images2/img-66.png" alt="" />
                            </div><!-- closes top -->
                            <div class="bottom">
                                <div>
                                   Must be made three full days prior to listing's local arriving time on the day when the tour begins, otherwise no refund. For example, if the tour starts on Friday at 9:00 AM, the cancellation must be requested before 9:00 AM of the previous Tuesday.
                                </div>
                                <div>
                                    If the visitor cancels less than 3 days in advance, 50% of the tour cost will be refunded.
                                </div>
                                <div>
                                	If the visitor arrives and decides to leave early, or not take the tour, the cost of the tour is 50% refunded.			
                                </div>
                            </div><!-- closes bottom -->
                        </div><!-- closes inner -->
                    </div><!-- closes tab -->
                    <div id="tabs-3" class="tab">
                        <h3>50% refund up until 1 week prior to arrival, except fees</h3>
                        <ul>
                        	<li>Cleaning fees are always refunded if the guest did not arrive to the meeting point.</li>
                            <li>The Tripfab service fee is non-refundable.</li>
                            <li>If there is a complaint from either party, notice must be given to Tripfab Resolution Center 
                            within 24 hours of the tour activity.</li>
                            <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                            <li>A reservation is not officially canceled until the guest receives a cancellation confirmation 
                            e-mail from Tripfab Resolution Center.</li>
                        </ul>
                        <div class="inner">
                            <div class="top">
                                <img src="/images2/img-67.png" alt="" />
                            </div><!-- closes top -->
                            <div class="bottom">
                                <div>
                                    Must be made seven full days prior to listing's local arriving time on the day when the tour begins, otherwise no refund. For example, if the tour starts on Friday at 9:00 AM, the cancellation must be requested before 9:00 AM of the previous Friday.
                                </div>
                                <div>
                                	If the visitor cancels less than 7 days in advance, the cost of the tour is not refunded.
                                </div>
                                <div>
                                    If the visitor arrives and decides to leave early, or not take the tour, the cost of the tour is not refunded.
                                </div>
                            </div><!-- closes bottom -->
                        </div><!-- closes inner -->
                    </div><!-- closes tab -->
                </div><!-- closes tabs -->
            </div><!-- closes cancellation -->
        </div><!-- closes wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#header .header-login a.user').click(function(){
            $(this).next().toggleClass('show');
            return false;
        });
        $('.tabs').tabs();
    });
</script>
</body>
</html>