<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> : Location | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
</head>
<body>
<div class="w1">
     <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="listing-wrapper wrapper">
            <?= $this->partial('partials/vendormainmenu.phtml', array('notifications'=> $this->pendingSettings,'active'=>'All Listings','parentActive'=>'Listings')); ?>
            <?= $this->partial('partials/vendorlistingstop.phtml', array('listing'=>$this->listing)); ?>
            <div class="listing-content">
                <div class="left">
                    <?= $this->partial('partials/vendorlistingsmenu.phtml', array('active'=>'How To Get there', 'id' => $this->listing->id, 
									   'type'=>$this->listing->main_type)) ?>
                </div><!-- closes left -->
                <div class="right">
                    <?= $this->partial('listing/common/getthere.phtml', array(
							'listing' => $this->listing,
							'location' => $this->location,
							'countries' => $this->countries,
							'cities'	=> $this->cities,
							'errors'	=> $this->errors,
							'help' => $this->help,
					)) ?>
                </div><!-- closes right -->
                <div class="clear"></div>
                <!-- closes listing-content -->
        </div><!-- closes listing-wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div class="hidden">
	<div id="new_direction" class="lb">
		<form action="" method="post">
            <div class="top"><h2>Add a New Direction</h2></div><!--TOP-->
            <div class="content">
                <select name="location">
                    <?php if(empty($this->location->plane)): ?>
                    <option value="train">By Plane</option>
                    <?php endif; if(empty($this->location->car)): ?>
                    <option value="car">By Car</option>
                    <?php endif; if(empty($this->location->train)): ?>
                    <option value="train">By Train</option>
                    <?php endif; if(empty($this->location->boat)): ?>
                    <option value="boat">By Boat</option>
                    <?php endif; if(empty($this->location->bus)): ?>
                    <option value="bus">By Bus</option>
                    <?php endif ?>
                </select>
            </div><!--CONTENT-->
            <div class="bottom">
            	<a href="" class="btn-1">Add Direction</a>
                <a href="" onclick="$.fancybox.close(); return false;" class="btn-10">Cancel</a>
            </div><!--BOTTOM-->
            <input type="hidden" name="_task" value="<?= md5('add_location') ?>" />
            <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
            <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
            <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'add-location') ?>" />
      </form>
	</div><!--NEW-DIRECTION-->
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/provider/location.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('textarea').elastic();
		$('a.add_direc').fancybox({
			padding:0,
			overlayColor:'#FFF',
			overlayOpacity: 0.7,
			showCloseButton:false,
			centerOnScroll:1,
		});
		$('#new_direction a.btn-1').click(function(){
			$(this).parents('form').submit();
			return false;
		});
		$('.cont .delete').click(function(){
			$top = $(this).parents('.top');
			$text = $top.next('textarea');
			$text.fadeOut('fast');
			$text.val('');
			$top.fadeOut('fast');
			return false;
		});
	});
</script>
</body>
</html>