<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Profile | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
	<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
	<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="listing-wrapper wrapper">
            <?= $this->partial('partials/vendorlistingstop.phtml', array('listing'=>$this->listing)); ?>
            <div class="listing-content show">
                <div class="left">
                    <?= $this->partial('partials/vendorlistingsmenu.phtml', array('active'=>'Calendar', 'id' => $this->listing->id)) ?>
                </div><!-- closes left -->
                <div class="right">
                    <div class="lstng-details">
                        <div class="lstng-detail">
                            <strong>Tips</strong>
                            <span>Write a some tips travelers need to know</span>
                        </div>
                        <!-- closes lstng-detail -->
                        <div class="lstng-detail">
                            <img width="736" alt="" src="images/img-33.png" />
                        </div>
                        <!-- closes lstng-detail -->
                    </div>
                    <!-- closes lstng-details -->
                    <div class="foot">
                        <input type="submit" class="btn-1" value="Save Changes" />
                        <a href="">Deactivate Listing</a>
                    </div>
                    <!-- closes foot -->
                </div>
                <!-- closes right -->
            </div>
            <!-- closes listing-content -->
        </div>
        <!-- closes listing-wrapper -->
    </div>
    <!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div>
<!-- closes w1 -->
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js2/jquery.input.value.js"></script>
<script type="text/javascript" src="/js/jquery.jqtransform.js"></script>
<script type="text/javascript" src="/js2/jquery.elastic.js"></script>
<script type="text/javascript" src="/js2/common.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('textarea').elastic();	
        $('input').ToggleInputValue();
        $('select').jqTransSelect();
    });
</script>
</body>
</html>