<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Create New Listing - Set Pricing | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
	
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?> 
    <div class="w2">
        <div class="wrapper">
            <div class="vendor-steps">
                <?= $this->partial('partials/vendorsteps.phtml',array('type'=>$this->listing->main_type,'step'=>6)) ?>
            </div><!-- closes vendor-steps -->
            <div class="sign-box vendor first">
                <div class="ttl-2">
                    <div class="text-right different3">
                        <p><strong>Set the pricing for your activity.</strong></p>
                        <p>Select a basic pricing and a rate for additional travelers. 
                        You can add pricing for each schedule you have. You'll be able to add  flexible pricing later in your listing page.</p>
                    </div>
                    <!-- closes text-right -->
                    <h2>Set the pricing</h2>
                    <p>Choose a basic pricing</p>
                </div><!-- closes ttl-2 -->
                <form action="" method="post" id="form_pricing">
                    <div class="content prcng">
                    	<?php if(count($this->errors) > 1): ?>
                        <div class="error">
                        	<?php foreach($this->errors as $err): ?>
                            <p><?= $err ?></p>
                            <?php endforeach ?>
                        </div>
                        <?php endif ?>
                        <?php $persons = array('1','2','3','4','5','6','7','8','9','10','15','20','30','40','50'); ?>
						<?php if($this->listing->main_type == 5): ?>
                        <?php foreach($this->schedules as $sch): ?>
                        <?php if($_POST): ?>
                        <div class="prcng-item hl">
                            <div class="left-ttl">
                                <span>1</span>
                                <strong>Set the pricing for <br /><?= $sch->name ?></strong>
                            </div><!-- closes left-ttl -->
                            <div class="right">
                                <ul>
                                    <li>
                                        <div>
                                            <h4>Basic Pricing</h4>
                                            <span>Rate per night</span>
                                        </div>
                                        <input name="sch[0][<?= $sch->id ?>][price]" value="<?= $_POST['sch'][0][$sch->id]['price'] ?>" 
                                        type="text" class="short" />
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Additional Pricing</h4>
                                            <span>Additional Person</span>
                                        </div>
                                        <input name="sch[0][<?= $sch->id ?>][additional]" value="<?= $_POST['sch'][0][$sch->id]['additional'] ?>" 
                                        type="text" class="short" />                                        
                                        <select name="sch[0][<?= $sch->id ?>][additional_after]">
										<?php foreach($persons as $p): ?>
											<?php if($_POST['sch'][0][$sch->id]['additional_after'] == $p): ?>
                                            <option selected="selected" value="<?= $p ?>"><?= $p ?></option>                                            
                                            <?php else: ?>
                                            <option value="<?= $p ?>"><?= $p ?></option>
                                            <?php endif ?>
                                        <?php endforeach ?>
                                        </select>
                                        <label>Rate for each person after</label>
                                        <div class="clear"></div>
                                    </li>
                                </ul>
                            </div><!-- closes right -->
                        </div><!-- closes prcng-item -->
                        <?php else: ?>
                        <div class="prcng-item hl">
                            <div class="left-ttl">
                                <span>1</span>
                                <strong>Set the pricing for <br /><?= $sch->name ?></strong>
                            </div><!-- closes left-ttl -->
                            <div class="right">
                                <ul>
                                    <li>
                                        <div>
                                            <h4>Basic Pricing</h4>
                                            <span>Rate per night</span>
                                        </div>
                                        <input name="sch[0][<?= $sch->id ?>][price]" value="0.00" type="text" class="short" />
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Additional Pricing</h4>
                                            <span>Additional Person</span>
                                        </div>
                                        <input name="sch[0][<?= $sch->id ?>][additional]" value="0.00" type="text" class="short" />                                        
                                        <select name="sch[0][<?= $sch->id ?>][additional_after]">
										<?php foreach($persons as $p): ?>
                                            <option value="<?= $p ?>"><?= $p ?></option>
                                        <?php endforeach ?>
                                        </select>
                                        <label>Rate for each person after</label>
                                        <div class="clear"></div>
                                    </li>
                                </ul>
                            </div><!-- closes right -->
                        </div><!-- closes prcng-item -->
                        <?php endif ?>
                        <?php endforeach ?>
						<?php else: ?>
                        <div class="prcng-item">
                            <div class="left-ttl">
                                <div>
                                    <strong>Basic pricing</strong>
                                </div>
                            </div><!-- closes left-ttl -->
                            <div class="right">
                                <ul>
                                    <li>
                                        <div>
                                            <h4>Basic Pricing</h4>
                                            <span>Rate per person</span>
                                        </div>
                                        <input name="price" value="0.00" type="text" class="short" />
                                        <label>Min</label>                                        
                                        <select name="min" class="min">
                                        <?php foreach($persons as $p): ?>
                                            <option value="<?= $p ?>"><?= $p ?></option>
                                        <?php endforeach ?>
                                        </select>
                                        <label>Max</label>
                                        <select name="max" class="max"> 
										<?php foreach($persons as $p): ?>
                                        <?php if($p == 50): ?>
                                            <option selected="selected" value="<?= $p ?>"><?= $p ?></option>
                                        <?php else: ?>
                                            <option value="<?= $p ?>"><?= $p ?></option>
                                        <?php endif ?>
                                        <?php endforeach ?>
                                        </select>
                                    </li>
                                </ul>
                            </div><!-- closes right -->
                        </div><!-- closes prcng-item -->
                        <?php endif ?>
                    </div><!-- closes content -->
                    <div class="foot">							
                        <input type="submit" class="btn-1 noclean" value="Finish" />
                        <a class="link-4" href="/provider/listings/new/<?= $this->listing->id ?>/step5">Back</a>
                    </div><!-- closes foot -->
                    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
                    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
                    <input type="hidden" name="form_id" value="<?= md5($this->listing->token.'form_pricing') ?>" />
                    <input type="hidden" name="_task" value="<?= md5('update_pricing') ?>" />
                </form>
            </div><!-- closes sign-box -->
        </div><!-- closes wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div class="hidden">
	<div id="congrats">
    	<div class="lb-congrats">
			<h2>Congratulations!</h2>
			<strong>You've created your first listing</strong>
			<p>Now, you need to complete some details <br /> before you listing become active</p>
			<div class="bottom">
				<a href="/provider/listings/" class="btn-1">Manage Listings</a>
			</div><!-- closes bottom -->
		</div><!-- closes lb-congrats -->
    </div>
</div>
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
    $(document).ready(function() {
		
		<?php if($this->congrats): ?>
		$.fancybox({
			href:'#congrats',
			padding:0,
			overlayColor:'#fff',
			centerOnScroll:1,
			overlayOpacity:0.7,
			showCloseButton:0,
			modal:1
		});
		<?php endif ?>
		
    });
</script>
<style type="text/css">
.sign-box.vendor.first .profile-items.prcng select {
	float:right;
	border:1px solid #ccc;
	padding:5px;
	margin-top:2px;
	margin-left:5px;}
.sign-box.vendor.first .profile-items.prcng input.short {
	width:40px;}
.error {
	border:1px solid #F00;
	padding:5px;
	margin-bottom:30px;}
	.error p {
		text-align:left;
		line-height:18px;
		font-style:italic;
		font-size:12px;
		font-weight:normal;
		color:#F00 !important;}
.hidden { display:none;}
.lb-congrats { background:#F3F3F3;}
.sign-box.vendor .content.prcng .prcng-item .right ul li input[type="text"] {
	background: url("/images2/ico-95.png") no-repeat scroll 5px 50% transparent;
	padding: 0 5px 0 16px;}
</style>
</body>
</html>