<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Create a New Listing : Select Type | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
	<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
	<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?> 
    <div class="w2">
        <div class="wrapper">
            <div class="vendor-steps">
                <ul>
                    <li class="first active"><strong>Step 1</strong><span>Listing Type</span></li>
                </ul>
            </div><!-- closes vendor-steps -->
            <div class="sign-box vendor first">
                <div class="ttl-2">
                    <div class="text-right different">
                        <p><strong>We have 5 different types of listings, choose one to start yours.</strong></p>
                        <p>You can choose between Activity, Hotel, Restaurant, Entertainment or Tourist Sight. Just select the type of listing you want, you can add more listings later, in your listings page.</p>
                    </div><!-- closes text-right -->
                    <h2><?= $this->title ?></h2>
                    <p>Select the type of listing you want to create.</p>
                </div>
                <div class="content">
                <form method="post">
                    <a href="" class="box box-1">
                        <img src="/images2/cleardot.gif" alt="" />
                        <strong>Activity</strong>
                        Fun activities that can be: sight seeing, boat tours, guided visits, etc.
                    </a>
                    <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
                    <input type="hidden" name="vendortoken" value="<?= $this->vendor->token ?>" />
                    <input type="hidden" name="type" value="6" />
                </form>
                <form method="post">
                    <a href="" class="box box-2">
                        <img src="/images2/cleardot.gif" alt="" />
                        <strong>Hotel</strong>
                        Types of rooms and accommodations available, amenities included, etc.
                    </a>
                    <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
                    <input type="hidden" name="vendortoken" value="<?= $this->vendor->token ?>" />
                    <input type="hidden" name="type" value="5" />
                </form>
                <form method="post">
                    <a href="" class="box box-3">
                        <img src="/images2/cleardot.gif" alt="" />
                        <strong>Restaurant</strong>
                        Types of cuisine, specials and dining options available.
                    </a>
                    <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
                    <input type="hidden" name="vendortoken" value="<?= $this->vendor->token ?>" />
                    <input type="hidden" name="type" value="2" />
                </form>
                <form method="post">
                    <a href="" class="box box-4">
                        <img src="/images2/cleardot.gif" alt="" />
                        <strong>Entertainment</strong>
                        Shows, concerts, events and activities that visitors can experience.
                    </a>
                    <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
                    <input type="hidden" name="vendortoken" value="<?= $this->vendor->token ?>" />
                    <input type="hidden" name="type" value="7" />
                </form>
                <form method="post">
                    <a href="" class="box box-5 last">
                        <img src="/images2/cleardot.gif" alt="" />
                        <strong>Tourist Sight</strong>
                        Impressive locations, sceneries and places that visitors will enjoy.
                    </a>
                    <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
                    <input type="hidden" name="vendortoken" value="<?= $this->vendor->token ?>" />
                    <input type="hidden" name="type" value="4" />
                </form>
                </div><!-- closes content -->
            </div><!-- closes sign-box -->
        </div><!-- closes wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->	
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript">
$(document).ready(function() {		
    $('a.box').click(function(){
            $(this).parents('form').submit();
            return false;
    });
});
</script>
</body>
</html