<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Listings | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/lightboxes.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages">
			<?= $this->partial('partials/vendormainmenu.phtml', array('notifications'=> $this->pendingSettings,'active'=>'All Listings','parentActive'=>'Listings')); ?>
            <?php if(count($this->listings) > 0): ?>
            <div class="listings-main">
            	<div class="sub-ttl">
            		<a href="#new_listing" class="lb btn-1">Create A New Listing</a>
            		<?= $this->title ?>
            	</div><!-- closes sub-ttl -->
            	<?php $statuses = array('inactive', 'active'); ?>
            	<?php foreach($this->listings as $listing): ?>
                <div class="lstng <?= $statuses[$listing->status] ?>">
                    <div class="left">
                        <?= $this->thumbnail(97, $listing->image, '','1:1'); ?>
                        <h2><img class="listing<?= $listing->main_type ?>" src="/images2/cleardot.gif" alt="" /><?= $listing->title ?></h2>
                        <span>Created on <?= date('F j, Y', strtotime($listing->created)) ?></span>
                        <p><?= stripslashes($listing->description) ?></p>
                    </div><!-- closes left -->
                    <div class="right">
                        <a href="#listing_delete_<?= $listing->id ?>" class="lb btn-4">Delete</a>
                        <?php if(!empty($listing->identifier) and $listing->country_id != 0 and $listing->city_id != 0): ?>
                        <a href="/provider/listings/preview/<?= $listing->id ?>" class="btn-4">Preview</a>
                        <?php endif ?>
                        <a href="/provider/listings/edit/<?= $listing->id ?>" class="btn-4">Edit</a>
                    </div><!-- closes right -->
                    <div class="timespan">
                        <span><?= strtoupper($statuses[$listing->status]) ?></span>
                    </div><!-- closes timespan -->
                </div><!-- closes lstng -->
                <?php endforeach ?>
            </div><!-- closes listings-main -->
			<?php else: ?>
            <div class="listings-main">
            	<div class="sub-ttl">
            		<a href="#new_listing" class="lb btn-1">Create A New Listing</a>
            		<?= $this->title ?>
            	</div><!-- closes sub-ttl -->
            </div>
            <div class="empty-container">
                <img src="/images/empty-1.png" alt="" /><br />
                There are no listings in this section :(
            </div><!-- closes empty -->
            <?php endif ?>
        </div><!-- closes user-messages -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div class="hidden">
	<?php foreach($this->listings as $list): ?>
    <div id="listing_delete_<?= $list->id ?>" class="listing_delete">
    	<form action="" method="post" id="form_listing_delete_<?= $list->id ?>">
            <div class="delete_name">
                <h2>Are you sure you want to delete the listing "<?= $list->title ?>"?</h2>
                <p>You will loose all the information for this listing</p>
            </div><!--DELETE_NAME-->
            <ul>
                <li><a class="btn-1" onclick="$(this).parents('form').submit(); return false;" href="">Delete</a></li>
                <li><a class="btn-13" onclick="$.fancybox.close(); return false;" href="">Cancel</a></li>
            </ul>      
            <input type="hidden" name="ids" value="<?= $list->id ?>" />
            <input type="hidden" name="listing_token" value="<?= $list->token ?>" />
            <input type="hidden" name="form_id" value="<?= md5($list->token .'form_listing_delete_'.$list->id) ?>" />
            <input type="hidden" name="_task" value="<?= md5('delete_listing') ?>" />
	    </form>
    </div><!--LISTING-DELETE-->
    <?php endforeach ?>
    <div id="new_listing">
    	<div class="lightbox_listing">
            <h1>What kind of listing do you want to create?</h1>
            <ul class="listing">
                <li class="select">
                	<form method="post" action="/en-US/provider/listings/new">
                        <a href="" onclick="$(this).parents('form').submit(); return false;">
                            <span><img src="/images2/ico-105.png" width="35" height="87" alt="" /></span>
                            <h2>Activity</h2>
                            <p>Fun activities that can done: sight seeing, boat tours, guided visits, etc.</p>
                        </a>
                        <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
                        <input type="hidden" name="vendortoken" value="<?= $this->vendor->token ?>" />
                        <input type="hidden" name="type" value="6" />
                    </form>
                </li>
                <li>
                	<form method="post" action="/en-US/provider/listings/new">
                        <a href="" onclick="$(this).parents('form').submit(); return false;">
                            <span><img src="/images2/ico-106.png" width="35" height="87" alt="" /></span>
                            <h2>Hotel</h2>
                            <p>Types of rooms and accomodations available, amenities included, etc.</p>
                        </a>
                        <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
                        <input type="hidden" name="vendortoken" value="<?= $this->vendor->token ?>" />
                        <input type="hidden" name="type" value="5" />
                    </form>
                </li>
                <li>
                	<form method="post" action="/en-US/provider/listings/new">
                        <a href="" onclick="$(this).parents('form').submit(); return false;">
                            <span><img src="/images2/ico-107.png" width="35" height="87" alt="" /></span>
                            <h2>Restaurant</h2>
                            <p>Types of cuisine, specials and dining options available.</p>
                        </a>
                        <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
                        <input type="hidden" name="vendortoken" value="<?= $this->vendor->token ?>" />
                        <input type="hidden" name="type" value="2" />
                    </form>
                </li>
                <li>
                	<form method="post" action="/en-US/provider/listings/new">
                        <a href="" onclick="$(this).parents('form').submit(); return false;">
                            <span><img src="/images2/ico-108.png" width="35" height="87" alt="" /></span>
                            <h2>Entertainment</h2>
                            <p>Shows, concerts, events and activities that visitors can experience.</p>
                        </a>
                        <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
                        <input type="hidden" name="vendortoken" value="<?= $this->vendor->token ?>" />
                        <input type="hidden" name="type" value="7" />
                    </form>
                </li>
                <li>
                	<form method="post" action="/en-US/provider/listings/new">
                        <a href="" onclick="$(this).parents('form').submit(); return false;">
                            <span><img src="/images2/ico-109.png" width="35" height="87" alt="" /></span>
                            <h2>Tourist Sight</h2>
                            <p>Impressive locations, sceneries and places that visitors will enjoy.</p>
                        </a>
                        <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
                        <input type="hidden" name="vendortoken" value="<?= $this->vendor->token ?>" />
                        <input type="hidden" name="type" value="4" />
                    </form>
                </li>
            </ul><!--LISTING-->
        </div><!--LIGHTBOX_LISTING-->
    </div>
</div>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('textarea').elastic();				
		$('input, textarea').ToggleInputValue();
		$('form select').jqTransSelect();
		$('a.lb').fancybox({
			padding:0,
			overlayColor:'#fff',
			centerOnScroll:1,
			overlayOpacity:0.7,
			showCloseButton:0,
		});
		$('.lbox .btn-2, .lbox .btn-11').click(function(){
			$(this).parents('form').submit();
		});
	});
</script>
</body>
</html>