<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Create a New Listing - Upload photos | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link href="/uploadify/uploadify.css?v=<?= $this->cssVC ?>" type="text/css" rel="stylesheet" />	
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
	<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
	<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?> 
    <div class="w2">
        <div class="wrapper">
            <div class="vendor-steps">
                <?= $this->partial('partials/vendorsteps.phtml',array('type'=>$this->listing->main_type,'step'=>5)) ?>
            </div><!-- closes vendor-steps -->
            <div class="sign-box vendor first">
                <div class="ttl-2">
                	<div class="text-right different">
                		<p><strong>Upload the most beautiful pictures you have</strong></p>
                		<p>Select some cool pictures for your activity. The upload limit is 10 photos per listing, so you may choose the best ones. You can manage your pictures later in your listing page.</p>
                	</div>
                	<!-- closes text-right -->
                    <h2>Upload Photos</h2>
                    <p>Upload Pictures for your activity.</p>
                </div><!-- closes ttl-2 -->
                <div class="content">
                    <div class="photos-wrapper">
                        <h3>Picture Requirements</h3>
                        <table cellpadding="0" cellspacing="0" border="0">
                            <tbody>
                                <tr>
                                    <td>Upload limit</td>
                                    <td>10 photos per listing</td>
                                </tr>
                                <tr>
                                    <td>Photo Dimension</td>
                                    <td>640x425 pixels</td>
                                </tr>
                                <tr>
                                    <td>File Size</td>
                                    <td>2MB or less</td>
                                </tr>
                            </tbody>
                        </table>
                        <input type="file" id="file-input" />
                        <a href="javascript:$('#file-input').uploadifyUpload();" class="btn-8">Upload Files</a>
                    </div><!-- closes photos-wrapper -->
                </div><!-- closes content -->
                <div class="foot">
                	<form id="uploadphotos" method="post">
	                    <input id="uploadphotos" type="submit" class="btn-1 noclean" value="Continue" />
                    </form>
                    <?php if($this->listing->main_type == 5 || $this->listing->main_type == 6): ?>
                    <a class="skip" href="/provider/listings/new/<?= $this->listing->id ?>/step6">Skip Step</a>                    
                    <?php else: ?>
                    <a class="skip" href="/provider/listings/">Skip Step</a>                    
                    <?php endif ?>
					<?php if($this->listing->main_type == 4 or $this->listing->main_type == 7): ?>
                    <a class="link-4" href="/provider/listings/new/<?= $this->listing->id ?>/step2">Back</a>
                    <?php else: ?>
                    <a class="link-4" href="/provider/listings/new/<?= $this->listing->id ?>/step4">Back</a>
                    <?php endif ?>
                </div><!-- closes foot -->
            </div><!-- closes sign-box -->
        </div><!-- closes wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div class="hidden">
	<div id="congrats">
    	<div class="lb-congrats">
			<h2>Congratulations!</h2>
			<strong>You've created your first listing</strong>
			<p>Now, you need to complete some details <br /> before you listing become active</p>
			<div class="bottom">
				<a href="/provider/listings/" class="btn-1">Manage Listings</a>
			</div><!-- closes bottom -->
		</div><!-- closes lb-congrats -->
    </div>
</div>
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
    $(document).ready(function() {
		$('#file-input').uploadify({
			'uploader'		  : '/uploadify/uploadify.swf',
			'script'   		  : '/phpscripts/uploadListingPhotos.php',
			'cancelImg'		  : '/uploadify/cancel.png',
			'folder'  		  : '/uploads',
			'buttonImg' 	  : '/images2/file-2.png',
			'height' 		  : 37,
			'width' 		  : 128,
			//'auto'      	  : true,
			'multi' 		  : true,
			'removeCompleted' : false,
			'onError':function(e,a,c,d){
			},
			'onComplete':function(a,b,c,image){
				
			},
			'scriptData':{
				'userids':<?= $this->user->id ?>,
				'vendorid':<?= $this->vendor->id ?>,
				'listings':<?= $this->listing->id ?>,
				'listtoken':'<?= $this->listing->token ?>',
				'formtoken':'<?= $this->user->token ?>',
				'usertoken':'<?= md5($this->user->token.'upload_listing_pictures') ?>'
			},
			'sizeLimit': 2097152,
		    'fileExt'  : '*.jpg;*.gif;*.png',
		    'fileDesc' : 'Image Files'
		});
		<?php if($this->congrats): ?>
		$.fancybox({
			href:'#congrats',
			padding:0,
			overlayColor:'#fff',
			centerOnScroll:1,
			overlayOpacity:0.7,
			showCloseButton:0,
			modal:1
		});
		<?php endif ?>
    });
	
</script>
<style type="text/css">
.sign-box.vendor.first .photos-wrapper .uploadifyQueue {
	border-top: 1px solid #E8E8E8;
	clear: both;
	padding-top: 6px;}
.hidden { display:none;}
.lb-congrats { background:#F3F3F3;}
</style>
</body>
</html>