<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <?php if($this->listing->main_type == 5): ?>
    <title>Create a New Listing : Set Room Types | Tripfab.com</title>
    <?php else: ?>
    <title>Create a New Listing : Set Schedules | Tripfab.com</title>
    <?php endif ?>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
	<script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
			var i=1;
			$('#newHour').click(function(){			
				<?php if($this->listing->main_type == 5): ?>
				var $item = $('<div class="item"><input tabindex="'+(i+1)+'" name="sch['+i+'][name]" value="Standard, Familiar...." type="text" /><h4><a href="" class="remove">Remove</a>Room Name</h4><span>Write a name for this room</span><div class="clear"></div></div>');
				$('.item-wrppr .item:last').before($item);
				$('input').ToggleInputValue();
				i++;
				<?php else: ?>
				var $item = $('.prcng-item.hidden.ltt').html();
				$item = $('<div class="prcng-item item">'+$item+'</div>');
				$('input[name=name]', $item).attr('name','sch['+i+'][name]');
				$('select[name=start_time]', $item).attr('name','sch['+i+'][start][time]');
				$('select[name=start_hour]', $item).attr('name','sch['+i+'][start][hour]');
				$('select[name=end_time]', $item).attr('name','sch['+i+'][end][time]');
				$('select[name=end_hour]', $item).attr('name','sch['+i+'][end][hour]');
				$('input[name=duration_lb]', $item).attr('name','sch['+i+'][duration_lb]');
				$('select[name=duration]', $item).attr('name','sch['+i+'][duration]');
				$('input[name=same]', $item).attr('name','sch['+i+'][same]');
				$('input.sameday', $item).attr('id','sameday'+i);
				$('label[for=sameday1]', $item).attr('for','sameday'+i);
				$('.left-ttl span', $item).text(i+1);
				$('.prcng-item.hidden:first').before($item);
				i++;
				<?php endif ?>
				return false;
			});
			
			$('a.remove').live('click', function(){
				$item = $(this).parents('.item');
				$item.fadeOut('fast', function(){
					$item.remove();
				});
				i--;
				return false;
			});
			
			$('input.sameday').live('change', function(){
				$li = $(this).parents('li');
				if($(this).attr('checked') == 'checked') {
					$('select, input:not(.sameday)', $li).attr('disabled', 'disabled');
				} else {
					$('select, input:not(.sameday)', $li).removeAttr('disabled');
				}
			});
        });
    </script>
    <style type="text/css">
	.hidden { display:none; }
	.sign-box.vendor.first .item-wrppr {
		background: none repeat scroll 0 0 transparent;
		border: 0 none;
	}
	.sign-box.vendor.first .item-wrppr .item input[type="text"]  { 
		width:350px;
		vertical-align:middle;}
	.sign-box.vendor.first .item-wrppr .item select {
		border: 1px solid #CCCCCC;
		float: right;
		margin-left: 5px;
		margin-top: 3px;
		padding: 5px;}
	.errors {
		border:1px solid #F00;
		padding:5px;
		margin:30px;}
		.errors p {
			text-align:left;
			line-height:18px;
			font-style:italic;
			font-size:12px;
			font-weight:normal;
			color:#F00 !important;}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?> 
    <div class="w2">
        <div class="wrapper">
            <div class="vendor-steps">
                <?= $this->partial('partials/vendorsteps.phtml',array('type'=>$this->listing->main_type,'step'=>4)) ?>
            </div><!-- closes vendor-steps -->
            <div class="sign-box vendor first">
                <div class="ttl-2">
                	<?php switch($this->listing->main_type): case '5': ?>
                	<div class="text-right different2">
                	    <p><strong>Add all the schedules available for your activity.</strong></p>
                	    <p>Select the starting time, the ending time and the duration for your activity. 
                	    You can add multiple schedules for each activity and set their prices individually later.</p>
                	</div><!-- closes text-right -->
                    <h2>Room Types</h2>
                    <p>Enter the name of the hotel room types</p>
                    <?php break; case '6': ?>
                    <div class="text-right different2">
                        <p><strong>Add all the schedules available for your activity.</strong></p>
                        <p>Select the starting time, the ending time and the duration for your activity. 
                        You can add multiple schedules for each activity and set their prices individually later.</p>
                    </div><!-- closes text-right -->
                    <h2>Activity Hours</h2>
                    <p>Set the schedule for your activity.</p>
                    <?php break; case '2': ?>
                    <div class="text-right different2">
                        <p><strong>Add all the schedules available for your activity.</strong></p>
                        <p>Select the starting time, the ending time and the duration for your activity. 
                        You can add multiple schedules for each activity and set their prices individually later.</p>
                    </div><!-- closes text-right -->
                    <h2>Restaurant Hours</h2>
                    <p>When your restaurant is open</p>
                    <?php break; endswitch ?>
                </div><!-- closes ttl-2 -->
                <form action="" method="post" id="form_sch_new">
                	<?php if($this->listing->main_type == 5): ?>
                    <div class="content ">
                        <div class="profile-items rooms">
                        	<?php if($this->errors): ?>
                            <div class="errors">
                            	<?php foreach($this->errors as $err): ?>
                                <p><?= $err ?></p>
                                <?php endforeach ?>
                            </div>
                            <?php endif ?>
                            <div class="text-left">
                                <h3>Write the names for your room types</h3>
                                <p>Sed laoreet tempor pellentesque. Integer ultricies pellentesque rutrum. 
                                Vestibulum quis orci non lacus dignissim cursus.</p>
                            </div>
                            <div class="item-wrppr">
                            	<?php $tab = 1 ?>
                            	<?php if(count($this->schedules)>0): ?>
                                <?php foreach($this->schedules as $sch): ?>
                                <div class="item">
                                    <input tabindex="<?= $tab ?>" name="schs[<?= $sch->id ?>][name]" value="<?= $sch->name ?>" type="text" />
                                    <h4><a href="" class="remove">Remove</a>Room Name</h4>
                                    <span>Write a name for this room</span>
                                    <div class="clear"></div>	
                                </div><!-- closes item -->
                                <?php $tab++ ?>
                                <?php endforeach ?>
                                <?php endif ?>
                                <?php if($this->sch): ?>
                                <?php foreach($this->sch as $i => $sch): ?>
                                <div class="item">
                                    <input tabindex="<?= $tab ?>" class="noclean" name="sch[<?= $i ?>][name]" value="<?= $sch['name'] ?>" type="text" />
                                    <h4><a href="" class="remove">Remove</a>Room Name</h4>
                                    <span>Write a name for this room</span>
                                    <div class="clear"></div>	
                                </div><!-- closes item -->
                                <?php $tab++ ?>
                                <?php endforeach ?>
                                <?php elseif(count($this->schedules) == 0): ?>
                                <div class="item">
                                    <input tabindex="<?= $tab ?>" name="sch[0][name]" value="Standard, Familiar...." type="text" />
                                    <h4>Room Name</h4>
                                    <span>Write a name for this room</span>
                                    <div class="clear"></div>	
                                </div><!-- closes item -->
                                <?php endif ?>
                                <div class="item last">
                                    <a id="newHour" href="" class="link-5">Add a New Room</a>
                                    <div class="clear"></div>	
                                </div><!-- closes item -->
                            </div><!-- closes item-wrppr -->
                        </div><!-- closes profile-items -->
                    </div><!-- closes content -->
                    <?php elseif($this->listing->main_type == 2): ?>
                    <?php $hours = array('1:00','1:30','2:00','2:30','3:00','3:30','4:00','4:30','5:00','5:30','6:00','6:30','7:00','7:30','8:00','8:30',
										 '9:00','9:30','10:00','10:30','11:00','11:30','12:00','12:30'); ?>
                    <div class="content prcng hours days">
	                    <?php if($this->errors): ?>
                        <div class="errors">
                            <?php foreach($this->errors as $err): ?>
                            <p><?= $err ?></p>
                            <?php endforeach ?>
                        </div>
                        <?php endif ?>
                        <?php if(count($this->schedules) > 0): ?>
                        <?php foreach($this->schedules as $sch): ?>
                        <?php if($_POST): ?>
                        <div class="prcng-item">
                            <div class="left-ttl">
                                <strong><?= $sch->name ?>'s Schedule</strong>
                                Set a schedule for <?= $sch->name ?>
                            </div><!-- closes left-ttl -->
                            <div class="right">
                                <ul>
                                    <li>
                                        <div>
                                            <h4>Open Time</h4>
                                            <span>Set the open hour</span>
                                        </div>
                                        <select name="schs[<?= $sch->id ?>][start][time]">
                                        	<?php $selected = ($_POST['schs'][$sch->id]['start']['time'] == 'AM') ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="AM">AM</option>
                                            <?php $selected = ($_POST['schs'][$sch->id]['start']['time'] == 'PM') ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="PM">PM</option>
                                        </select>
                                        <select name="schs[<?= $sch->id ?>][start][hour]">
                                            <option value="">--:--</option>
                                            <?php foreach($hours as $h): ?>
                                            <?php $selected = ($_POST['schs'][$sch->id]['start']['hour'] == $h) ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="<?= $h ?>"><?= $h ?></option>
                                            <?php endforeach ?>
                                        </select>										
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Close Time</h4>
                                            <span>Set the closed hour</span>
                                        </div>
                                        <select name="schs[<?= $sch->id ?>][end][time]">
                                            <?php $selected = ($_POST['schs'][$sch->id]['end']['time'] == 'AM') ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="AM">AM</option>
                                            <?php $selected = ($_POST['schs'][$sch->id]['end']['time'] == 'PM') ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="PM">PM</option>
                                        </select>
                                        <select name="schs[<?= $sch->id ?>][end][hour]">
                                            <option value="">--:--</option>
                                            <?php foreach($hours as $h): ?>
                                            <?php $selected = ($_POST['schs'][$sch->id]['end']['hour'] == $h) ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="<?= $h ?>"><?= $h ?></option>
                                            <?php endforeach ?>
                                        </select>
                                        <input type="hidden" name="schs[<?= $sch->id ?>][name]" value="<?= $sch->name ?>" />
                                        <div class="clear"></div>
                                    </li>
                                </ul>
                            </div><!-- closes right -->
                        </div><!-- closes prcng-item -->
                        <?php else: ?>
                        <div class="prcng-item">
                            <div class="left-ttl">
                                <strong><?= $sch->name ?>'s Schedule</strong>
                                Set a schedule for <?= $sch->name ?>
                            </div><!-- closes left-ttl -->
                            <div class="right">
                                <ul>
                                    <li>
                                        <div>
                                            <h4>Open Time</h4>
                                            <span>Set the open hour</span>
                                        </div>
                                        <select name="schs[<?= $sch->id ?>][start][time]">
                                            <?php $selected = (date('A', strtotime($sch->starting)) == 'AM') ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="AM">AM</option>
                                            <?php $selected = (date('A', strtotime($sch->starting)) == 'PM') ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="PM">PM</option>
                                        </select>
                                        <select name="schs[<?= $sch->id ?>][start][hour]">
                                            <option value="">--:--</option>
                                            <?php foreach($hours as $h): ?>
                                            <?php $selected = (date('g:i', strtotime($sch->starting)) == $h) ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="<?= $h ?>"><?= $h ?></option>
                                            <?php endforeach ?>
                                        </select>										
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Close Time</h4>
                                            <span>Set the closed hour</span>
                                        </div>
                                        <select name="schs[<?= $sch->id ?>][end][time]">
                                            <?php $selected = (date('A', strtotime($sch->ending)) == 'AM') ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="AM">AM</option>
                                            <?php $selected = (date('A', strtotime($sch->ending)) == 'PM') ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="PM">PM</option>
                                        </select>
                                        <select name="schs[<?= $sch->id ?>][end][hour]">
                                            <option value="">--:--</option>
                                            <?php foreach($hours as $h): ?>
                                            <?php $selected = (date('g:i', strtotime($sch->ending)) == $h) ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="<?= $h ?>"><?= $h ?></option>
                                            <?php endforeach ?>
                                        </select>
                                        <input type="hidden" name="schs[<?= $sch->id ?>][name]" value="<?= $day ?>" />
                                        <div class="clear"></div>
                                    </li>
                                </ul>
                            </div><!-- closes right -->
                        </div><!-- closes prcng-item -->
                        <?php endif ?>
                        <?php endforeach ?>
                        <?php else: ?>
                    	<?php $res_days = array('Monday', 'Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday') ?>
                        <?php foreach($res_days as $i=>$day): ?>
                        <?php if($_POST): ?>
                        <div class="prcng-item">
                            <div class="left-ttl">
                                <strong><?= $day ?>'s Schedule</strong>
                                Set a schedule for <?= $day ?>
                            </div><!-- closes left-ttl -->
                            <div class="right">
                                <ul>
                                    <li>
                                        <div>
                                            <h4>Open Time</h4>
                                            <span>Set the open hour</span>
                                        </div>
                                        <select name="sch[<?= $i ?>][start][time]">
                                        	<?php $selected = ($_POST['sch'][$i]['start']['time'] == 'AM') ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="AM">AM</option>
                                            <?php $selected = ($_POST['sch'][$i]['start']['time'] == 'PM') ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="PM">PM</option>
                                        </select>
                                        <select name="sch[<?= $i ?>][start][hour]">
                                            <option value="">--:--</option>
                                            <?php foreach($hours as $h): ?>
                                            <?php $selected = ($_POST['sch'][$i]['start']['hour'] == $h) ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="<?= $h ?>"><?= $h ?></option>
                                            <?php endforeach ?>
                                        </select>										
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Close Time</h4>
                                            <span>Set the closed hour</span>
                                        </div>
                                        <select name="sch[<?= $i ?>][end][time]">
                                            <?php $selected = ($_POST['sch'][$i]['end']['time'] == 'AM') ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="AM">AM</option>
                                            <?php $selected = ($_POST['sch'][$i]['end']['time'] == 'PM') ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="PM">PM</option>
                                        </select>
                                        <select name="sch[<?= $i ?>][end][hour]">
                                            <option value="">--:--</option>
                                            <?php foreach($hours as $h): ?>
                                            <?php $selected = ($_POST['sch'][$i]['end']['hour'] == $h) ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="<?= $h ?>"><?= $h ?></option>
                                            <?php endforeach ?>
                                        </select>
                                        <input type="hidden" name="sch[<?= $i ?>][name]" value="<?= $day ?>" />
                                        <div class="clear"></div>
                                    </li>
                                </ul>
                            </div><!-- closes right -->
                        </div><!-- closes prcng-item -->
                        <?php else: ?>
                        <div class="prcng-item">
                            <div class="left-ttl">
                                <strong><?= $day ?>'s Schedule</strong>
                                Set a schedule for <?= $day ?>
                            </div><!-- closes left-ttl -->
                            <div class="right">
                                <ul>
                                    <li>
                                        <div>
                                            <h4>Open Time</h4>
                                            <span>Set the open hour</span>
                                        </div>
                                        <select name="sch[<?= $i ?>][start][time]">
                                            <option value="AM">AM</option>
                                            <option value="PM">PM</option>
                                        </select>
                                        <select name="sch[<?= $i ?>][start][hour]">
                                            <option value="">--:--</option>
                                            <?php foreach($hours as $h): ?>
                                            <option value="<?= $h ?>"><?= $h ?></option>
                                            <?php endforeach ?>
                                        </select>										
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Close Time</h4>
                                            <span>Set the closed hour</span>
                                        </div>
                                        <select name="sch[<?= $i ?>][end][time]">
                                            <option value="AM">AM</option>
                                            <option value="PM">PM</option>
                                        </select>
                                        <select name="sch[<?= $i ?>][end][hour]">
                                            <option value="">--:--</option>
                                            <?php foreach($hours as $h): ?>
                                            <option value="<?= $h ?>"><?= $h ?></option>
                                            <?php endforeach ?>
                                        </select>
                                        <input type="hidden" name="sch[<?= $i ?>][name]" value="<?= $day ?>" />
                                        <div class="clear"></div>
                                    </li>
                                </ul>
                            </div><!-- closes right -->
                        </div><!-- closes prcng-item -->
                        <?php endif ?>
                        <?php endforeach ?>
                        <?php endif ?>
                    </div><!-- closes content -->
                    <?php else: ?>
                    <?php $hours = array('1:00','1:30','2:00','2:30','3:00','3:30','4:00','4:30','5:00','5:30','6:00','6:30','7:00','7:30','8:00','8:30',
										 '9:00','9:30','10:00','10:30','11:00','11:30','12:00','12:30'); 
						  $days  = array(2,3,4,5,6,7,8,9,10,15,30,45); ?>
                    <div class="content prcng hours">
                    	<?php if($this->errors): ?>
                        <div class="errors">
                            <?php foreach($this->errors as $err): ?>
                            <p><?= $err ?></p>
                            <?php endforeach ?>
                        </div>
                        <?php endif ?>
                        <?php if(count($this->schedules) > 0): ?>
						<?php foreach($this->schedules as $i => $sch): ?>
                        <div class="prcng-item item">
                            <div class="left-ttl">
                                <span><?= $i + 1 ?></span>
                                <strong><?= $sch->name ?></strong>
                                Choose a name, the starting time, the ending time and the duration for your first schedule
                            </div><!-- closes left-ttl -->
                            <div class="right">
                                <ul>
                                    <li>
                                        <div>
                                            <h4>Schedule Name</h4>
                                            <span>Set a name for this schedule</span>
                                        </div>
                                        <input class="noclean" name="schs[<?= $sch->id ?>][name]" value="<?= $sch->name ?>" type="text" />
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Starting Time</h4>
                                            <span>At what time does this activity start?</span>
                                        </div>
                                        <select name="schs[<?= $sch->id ?>][start][time]">
                                        	<?= $selected = (date('A', strtotime($sch->starting)) == 'AM') ? 'selected="selected"' : ''; ?>
                                            <option <?= $selected ?> value="AM">AM</option>
                                            <?= $selected = (date('A', strtotime($sch->starting)) == 'PM') ? 'selected="selected"' : ''; ?>
                                        	<option <?= $selected ?> value="PM">PM</option>
                                        </select>
                                        <select name="schs[<?= $sch->id ?>][start][hour]">
                                            <option value="">--:--</option>
                                            <?php foreach($hours as $h): ?>
                                            <?= $selected = (date('g:i', strtotime($sch->starting)) == $h) ? 'selected="selected"' : ''; ?>
                                            <option <?= $selected ?> value="<?= $h ?>"><?= $h ?></option>                                            
                                            <?php endforeach ?>
                                        </select>
                                        <div class="clear"></div>											
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Ending Time</h4>
                                            <span>At what time does this activity end?</span>
                                        </div>
                                        <select name="schs[<?= $sch->id ?>][end][time]">
                                        	<?= $selected = (date('A', strtotime($sch->ending)) == 'AM') ? 'selected="selected"' : ''; ?>
                                            <option <?= $selected ?> value="AM">AM</option>
                                            <?= $selected = (date('A', strtotime($sch->ending)) == 'PM') ? 'selected="selected"' : ''; ?>
                                        	<option <?= $selected ?> value="PM">PM</option>
                                        </select>
                                        <select name="schs[<?= $sch->id ?>][end][hour]">
                                            <option value="">--:--</option>
                                            <?php foreach($hours as $h): ?>
                                            <?= $selected = (date('g:i', strtotime($sch->ending)) == $h) ? 'selected="selected"' : ''; ?>
                                            <option <?= $selected ?> value="<?= $h ?>"><?= $h ?></option>                                            
                                            <?php endforeach ?>
                                        </select>
                                        <div class="clear"></div>										
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Activity Duration</h4>
                                            <span>How long is it?</span>
                                        </div>
                                        <?php $disabled = ($sch->duration == 1) ? 'disabled="disabled"' : ''; ?>
                                        <input <?= $disabled ?> type="hidden" name="schs[<?= $sch->id ?>][duration_lb]" value="days" />
                                        <select <?= $disabled ?> name="schs[<?= $sch->id ?>][duration]">
                                            <option value="1">1 day</option>
                                        	<?php foreach($days as $d): ?>
                                            <?php $selected = ($d == $sch->duration) ? 'selected="selected"' : '' ?>
                                            <option <?= $selected ?> value="<?= $d ?>"><?= $d ?> days</option>                                            
                                            <?php endforeach ?>
                                        </select>                                        	
                                        <label for="sameday<?= $sch->id ?>">Ends the same day</label>
                                        <?php $checked = (!empty($disabled)) ? 'checked="checked"' : '' ?>
                                        <input <?= $checked ?> name="schs[<?= $sch->id ?>][same]" id="sameday<?= $sch->id ?>" class="sameday" type="checkbox" />
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                    	<a href="" class="remove">Remove</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
						<?php endforeach ?>
						<?php else: ?>
                        <div class="prcng-item">
                            <div class="left-ttl">
                                <span>1</span>
                                <strong>First Schedule Settings</strong>
                                Choose a name, the starting time, the ending time and the duration for your first schedule
                            </div><!-- closes left-ttl -->
                            <div class="right">
                                <ul>
                                    <li>
                                        <div>
                                            <h4>Schedule Name</h4>
                                            <span>Set a name for this schedule</span>
                                        </div>
                                        <input name="sch[0][name]" value="Morning, Afternoon...." type="text" />
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Starting Time</h4>
                                            <span>At what time does this activity start?</span>
                                        </div>
                                        <select name="sch[0][start][time]">
                                            <option value="AM">AM</option>
                                        	<option value="PM">PM</option>
                                        </select>
                                        <select name="sch[0][start][hour]">
                                            <option value="">--:--</option>
                                            <option value="1:00">1:00</option>
                                            <option value="1:30">1:30</option>
                                            <option value="2:00">2:00</option>
                                            <option value="2:30">2:30</option>
                                            <option value="3:00">3:00</option>
                                            <option value="3:30">3:30</option>
                                            <option value="4:00">4:00</option>
                                            <option value="4:30">4:30</option>
                                            <option value="5:00">5:00</option>
                                            <option value="5:30">5:30</option>
                                            <option value="6:00">6:00</option>
                                            <option value="6:30">6:30</option>
                                            <option value="7:00">7:00</option>
                                            <option value="7:30">7:30</option>
                                            <option value="8:00">8:00</option>
                                            <option value="8:30">8:30</option>
                                            <option value="9:00">9:00</option>
                                            <option value="9:30">9:30</option>
                                            <option value="10:00">10:00</option>
                                            <option value="10:30">10:30</option>
                                            <option value="11:00">11:00</option>
                                            <option value="11:30">11:30</option>
                                            <option value="12:00">12:00</option>
                                            <option value="12:30">12:30</option>
                                        </select>
                                        <div class="clear"></div>											
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Ending Time</h4>
                                            <span>At what time does this activity end?</span>
                                        </div>
                                        <select name="sch[0][end][time]">
                                            <option value="AM">AM</option>
                                        	<option value="PM">PM</option>
                                        </select>
                                        <select name="sch[0][end][hour]">
                                            <option value="">--:--</option>
                                            <option value="1:00">1:00</option>
                                            <option value="1:30">1:30</option>
                                            <option value="2:00">2:00</option>
                                            <option value="2:30">2:30</option>
                                            <option value="3:00">3:00</option>
                                            <option value="3:30">3:30</option>
                                            <option value="4:00">4:00</option>
                                            <option value="4:30">4:30</option>
                                            <option value="5:00">5:00</option>
                                            <option value="5:30">5:30</option>
                                            <option value="6:00">6:00</option>
                                            <option value="6:30">6:30</option>
                                            <option value="7:00">7:00</option>
                                            <option value="7:30">7:30</option>
                                            <option value="8:00">8:00</option>
                                            <option value="8:30">8:30</option>
                                            <option value="9:00">9:00</option>
                                            <option value="9:30">9:30</option>
                                            <option value="10:00">10:00</option>
                                            <option value="10:30">10:30</option>
                                            <option value="11:00">11:00</option>
                                            <option value="11:30">11:30</option>
                                            <option value="12:00">12:00</option>
                                            <option value="12:30">12:30</option>
                                        </select>	
                                        <div class="clear"></div>										
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Activity Duration</h4>
                                            <span>How long is it?</span>
                                        </div>
                                        <input disabled="disabled" type="hidden" name="sch[0][duration_lb]" value="days" />
                                        <select disabled="disabled" name="sch[0][duration]">
                                            <option value="1">1 day</option>
                                            <option value="2">2 days</option>
                                            <option value="3">3 days</option>
                                            <option value="4">4 days</option>
                                            <option value="5">5 days</option>
                                            <option value="6">6 days</option>
                                            <option value="7">7 days</option>
                                            <option value="8">8 days</option>
                                            <option value="9">9 days</option>
                                            <option value="10">10 days</option>
                                            <option value="15">15 days</option>
                                            <option value="30">30 days</option>
                                            <option value="45">45 days</option>
                                        </select>                                        	
                                        <label for="sameday0">Ends the same day</label>
                                        <input checked="checked" name="sch[0][same]" id="sameday0" class="sameday" type="checkbox" />
                                        <div class="clear"></div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <?php endif ?>
                        <div class="prcng-item hidden"></div>
                        <div class="prcng-item hidden ltt">
                            <div class="left-ttl">
                                <span></span>
                                <strong>New Schedule Settings</strong>
                                Choose a name, the starting time, the ending time and the duration for your new schedule
                            </div><!-- closes left-ttl -->
                            <div class="right">
                                <ul>
                                    <li>
                                        <div>
                                            <h4>Schedule Name</h4>
                                            <span>Set a name for this schedule</span>
                                        </div>
                                        <input name="name" value="Morning, Afternoon...." type="text" />
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Starting Time</h4>
                                            <span>At what time does this activity start?</span>
                                        </div>
                                        <select name="start_time">
                                            <option value="AM">AM</option>
                                        	<option value="PM">PM</option>
                                        </select>
                                        <select name="start_hour">
                                            <option value="">--:--</option>
                                            <option value="1:00">1:00</option>
                                            <option value="1:30">1:30</option>
                                            <option value="2:00">2:00</option>
                                            <option value="2:30">2:30</option>
                                            <option value="3:00">3:00</option>
                                            <option value="3:30">3:30</option>
                                            <option value="4:00">4:00</option>
                                            <option value="4:30">4:30</option>
                                            <option value="5:00">5:00</option>
                                            <option value="5:30">5:30</option>
                                            <option value="6:00">6:00</option>
                                            <option value="6:30">6:30</option>
                                            <option value="7:00">7:00</option>
                                            <option value="7:30">7:30</option>
                                            <option value="8:00">8:00</option>
                                            <option value="8:30">8:30</option>
                                            <option value="9:00">9:00</option>
                                            <option value="9:30">9:30</option>
                                            <option value="10:00">10:00</option>
                                            <option value="10:30">10:30</option>
                                            <option value="11:00">11:00</option>
                                            <option value="11:30">11:30</option>
                                            <option value="12:00">12:00</option>
                                            <option value="12:30">12:30</option>
                                        </select>	
                                        <div class="clear"></div>										
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Ending Time</h4>
                                            <span>At what time does this activity end?</span>
                                        </div>
                                        <select name="end_time">
                                            <option value="AM">AM</option>
                                        	<option value="PM">PM</option>
                                        </select>
                                        <select name="end_hour]">
                                            <option value="">--:--</option>
                                            <option value="1:00">1:00</option>
                                            <option value="1:30">1:30</option>
                                            <option value="2:00">2:00</option>
                                            <option value="2:30">2:30</option>
                                            <option value="3:00">3:00</option>
                                            <option value="3:30">3:30</option>
                                            <option value="4:00">4:00</option>
                                            <option value="4:30">4:30</option>
                                            <option value="5:00">5:00</option>
                                            <option value="5:30">5:30</option>
                                            <option value="6:00">6:00</option>
                                            <option value="6:30">6:30</option>
                                            <option value="7:00">7:00</option>
                                            <option value="7:30">7:30</option>
                                            <option value="8:00">8:00</option>
                                            <option value="8:30">8:30</option>
                                            <option value="9:00">9:00</option>
                                            <option value="9:30">9:30</option>
                                            <option value="10:00">10:00</option>
                                            <option value="10:30">10:30</option>
                                            <option value="11:00">11:00</option>
                                            <option value="11:30">11:30</option>
                                            <option value="12:00">12:00</option>
                                            <option value="12:30">12:30</option>
                                        </select>											
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                        <div>
                                            <h4>Activity Duration</h4>
                                            <span>How long is it?</span>
                                        </div>
                                        <input disabled="disabled" type="hidden" name="duration_lb" value="days" />
                                        <select disabled="disabled" name="duration">
                                            <option value="1">1 day</option>
                                            <option value="2">2 days</option>
                                            <option value="3">3 days</option>
                                            <option value="4">4 days</option>
                                            <option value="5">5 days</option>
                                            <option value="6">6 days</option>
                                            <option value="7">7 days</option>
                                            <option value="8">8 days</option>
                                            <option value="9">9 days</option>
                                            <option value="10">10 days</option>
                                            <option value="15">15 days</option>
                                            <option value="30">30 days</option>
                                            <option value="45">45 days</option>
                                        </select>
                                        <label for="sameday1">Ends the same day</label>
                                        <input checked="checked" name="same" id="sameday1" class="sameday" type="checkbox" />
                                        <div class="clear"></div>
                                    </li>
                                    <li>
                                    	<a href="" class="remove">Remove</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="prcng-item">
                            <a href="" id="newHour" class="link-5">Add a New Schedule</a>
                        </div>
                    </div><!-- closes content -->
                    <?php endif ?>
                    <div class="foot">
                        <input type="submit" class="btn-1" value="Continue" />
                        <a class="link-4" href="/provider/listings/new/<?= $this->listing->id ?>/step2">Back</a>
                        <?php if($this->listing->main_type == 6): ?>
	                    <a class="skip" href="/provider/listings/new/<?= $this->listing->id ?>/step5">Skip Step</a>   
                        <?php endif ?>
                    </div><!-- closes foot -->
                    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
                    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
                    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'form_sch_new') ?>" />
                    <input type="hidden" name="_task" value="<?= md5('add_sch') ?>" />
                </form>
            </div><!-- closes sign-box -->
        </div><!-- closes wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->	
</body>
</html>