<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Create a New Listing - General Information | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/lightboxes.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
   	<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
   	<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?> 
    <div class="w2">
        <div class="wrapper">
            <div class="vendor-steps">
            	<?= $this->partial('partials/vendorsteps.phtml',array('type'=>$this->listing->main_type,'step'=>2)) ?>
            </div><!-- closes vendor-steps -->
            <div class="sign-box vendor first">
                <div class="ttl-2">
                	<?php switch($this->listing->main_type): case '5': ?>
                    <div class="text-right">
                        <p><strong>We need some required details of your listing</strong></p>
                        <p>Write a name, select a location and a category for your hotel. 
                        You'll be able to add more information about this hotel later in your listing page.</p>
                    </div><!-- closes text-right -->
                    <h2>Hotel Description</h2>
                    <p>A short description about the hotel.</p>
                    <?php break; case '6': ?>
                    <div class="text-right">
                        <p><strong>We require you to fill in some detailed information about your listing</strong></p>
                        <p>Write a name, select a location and a category for your activity. You will be able to add more information about this activity later in your listing page.</p>
                    </div><!-- closes text-right -->
                    <h2>Activity Description</h2>
                    <p>A short description about the activity.</p>
                    <?php break; case '2': ?>
                    <div class="text-right">
                        <p><strong>We need some required details of your restaurant</strong></p>
                        <p>Write a name, select a location and a category for your restaurant. 
                        You'll be able to add more information about this restaurant later in your listing page.</p>
                    </div><!-- closes text-right -->
                    <h2>Restaurant Description</h2>
                    <p>Tell us some info about your restaurant.</p>
                    <?php break; case '4': ?>
                    <div class="text-right">
                        <p><strong>We need some required details of this tourist sight</strong></p>
                        <p>Write a name, select a location and a category for this tourist sight. 
                        You'll be able to add more information about this tourist sight later in your listing page.</p>
                    </div><!-- closes text-right -->
                    <h2>Tourist Sight Description</h2>
                    <p>Tell us some info about this tourist sight.</p>
                    <?php break; case '7': ?>
                    <div class="text-right">
                        <p><strong>We need some required details of your listing</strong></p>
                        <p>Write a name, select a location and a category for your listing. 
                        You'll be able to add more information about this listing later in your listing page.</p>
                    </div><!-- closes text-right -->
                    <h2>Listing Description</h2>
                    <p>Tell us some info about your entertainment listing.</p>
                    <?php break; endswitch ?>
                </div><!-- closes ttl-2 -->
                <form action="" method="post">
                    <div class="content">
                        <div class="profile-items">
                            <div class="item-wrppr">
                            	<?php if(count($this->errors) > 0): ?>
                                <div class="item errors">
                                	<?php foreach($this->errors as $err): ?>
                                	<h4><?= $err ?></h4>
                                    <?php endforeach ?>
                                </div>
                                <?php endif ?>
                                <?php if($_POST): ?>
                                <div class="item">
                                    <input type="text" class="noclean" value="<?= $_POST['title'] ?>" name="title" />
                                    <h4>Listing Title</h4>
                                    <span>Write the full name of the activity</span>
                                    <div class="clear"></div>	
                                </div><!-- closes item -->
                                <div class="item">
                                	<select name="city_id" id="cities2">
                                        <?php if(count($this->cities) > 0): ?>
                                        <option value="">Select the city</option>
                                        <?php foreach($this->cities as $c): ?>
                                        <?php $selected = ($c->id == $_POST['city_id']) ? 'selected="selected"' : ''; ?>
                                        <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                                        <?php endforeach ?>                                    
                                        <?php else: ?>
                                        <option>Country first</option>
                                        <?php endif ?>
                                    </select>
                                    <select name="country_id" id="country2">
                                        <option value="">Select the country</option>
                                        <?php foreach($this->countries as $c): ?>
                                        <?php $selected = ($c->id == $_POST['country_id']) ? 'selected="selected"' : ''; ?>
                                        <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                                        <?php endforeach ?>
                                    </select>                                    
                                    <h4>Location</h4>
                                    <span>Select the location where this activity takes place</span>
                                    <div class="clear"></div>	
                                </div><!-- closes item -->
                                <div class="item">
                                    <input type="submit" class="btn-4 noclean" id="setLocation" value="Set Location" />
                                    <input type="text" class="noclean shorter" name="address" value="<?= $_POST['address'] ?>" />
                                    <div id="maplocations" class="w-m">
                                        <h5>Location Results</h5>
                                        <ul id="">
                                        </ul>
                                    </div>
                                    <!-- closes w-m -->
                                    <div class="map-wrapper">
                                        <div id="mapcanvas"></div>
                                    </div><!-- closes map-wrapper -->
                                    <input type="hidden" name="lat" value="<?= $_POST['lat'] ?>" />
                                    <input type="hidden" name="lng" value="<?= $_POST['lng'] ?>" />										
                                    <h4>Map</h4>
                                    <span>Set a location and then drag the mark to the <br /> specific location</span>
                                    <div class="clear"></div>	
                                </div><!-- closes item -->
                                <div class="item last">
                                    <div class="map-wrapper">
                                        <table cellpadding="0" cellspacing="0" border="0">
                                            <?php for($i=0; $i<count($this->categories); $i=$i+2): ?>
                                            <tr>
                                                <?php for($j=$i; ($j<count($this->categories)) && ($j<($i+2)); $j++): ?>
                                                <td>
                                                <?php if(is_array($_POST['types'])): ?>
                                                <?php $checked = (in_array($this->categories[$j]->id, $_POST['types'])) ? 'checked="checked"' : ''; ?>
                                                <?php endif ?>
                                                <input <?= $checked ?> name="types[<?= $this->categories[$j]->id ?>]" 
                                                value="<?= $this->categories[$j]->id ?>" type="checkbox"/>
                                                <?= $this->categories[$j]->name ?>
                                                </td>
                                                <?php endfor ?>
                                            </tr>
                                            <?php endfor ?>
                                        </table>
                                    </div><!-- closes map-wrapper -->
                                    <h4>Categories</h4>
                                    <span>Select all that apply</span>
                                    <div class="clear"></div>	
                                </div><!-- closes item -->
                                <?php else: ?>
                                <div class="item">
                                	<?php $title = ($this->listing->title == 'Untitled Listing') ? '' : $this->listing->title ?>
                                    <input type="text" class="noclean" name="title" value="<?= $title ?>" />
                                    <h4>Listing Title</h4>
                                    <span>Write the full name of the activity</span>
                                    <div class="clear"></div>	
                                </div><!-- closes item -->
                                <div class="item">
                                	<select name="city_id" id="cities2">
                                        <?php if(count($this->cities) > 0): ?>
                                        <option value="">Select the city</option>
                                        <?php foreach($this->cities as $c): ?>
                                        <?php $selected = ($c->id == $this->listing->city_id) ? 'selected="selected"' : ''; ?>
                                        <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                                        <?php endforeach ?>                                    
                                        <?php else: ?>
                                        <option>Country first</option>
                                        <?php endif ?>
                                    </select>
                                    <select name="country_id" id="country2">
                                        <option value="">Select the country</option>
                                        <?php foreach($this->countries as $c): ?>
                                        <?php $selected = ($c->id == $this->listing->country_id) ? 'selected="selected"' : ''; ?>
                                        <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                                        <?php endforeach ?>
                                    </select>                                    
                                    <h4>Location</h4>
                                    <span>Select the location where this activity takes place</span>
                                    <div class="clear"></div>	
                                </div><!-- closes item -->
                                <div class="item">
                                    <input type="submit" class="btn-4 noclean" id="setLocation" value="Set Location" />
                                    <input type="text" class="noclean shorter" name="address" value="<?= $this->listing->address ?>" />
                                    <div id="maplocations" class="w-m">
                                        <h5>Location Results</h5>
                                        <ul id="">
                                        </ul>
                                    </div>
                                    <!-- closes w-m -->
                                    <div class="map-wrapper">
                                        <div id="mapcanvas"></div>
                                    </div><!-- closes map-wrapper -->
                                    <input type="hidden" name="lat" value="<?= $this->listing->lat ?>" />
                                    <input type="hidden" name="lng" value="<?= $this->listing->lng ?>" />										
                                    <h4>Map</h4>
                                    <span>Set a location and then drag the mark to the <br /> specific location</span>
                                    <div class="clear"></div>	
                                </div><!-- closes item -->
                                <div class="item last">
                                    <div class="map-wrapper">
                                        <table cellpadding="0" cellspacing="0" border="0">
                                            <?php for($i=0; $i<count($this->categories); $i=$i+2): ?>
                                            <tr>
                                                <?php for($j=$i; ($j<count($this->categories)) && ($j<($i+2)); $j++): ?>
                                                <td>
                                                <?php $checked = (in_array($this->categories[$j]->id, $this->listing_types)) ? 'checked="checked"' : ''; ?>
                                                <input <?= $checked ?> name="types[<?= $this->categories[$j]->id ?>]" 
                                                value="<?= $this->categories[$j]->id ?>" type="checkbox"/>
                                                <?= $this->categories[$j]->name ?>
                                                </td>
                                                <?php endfor ?>
                                            </tr>
                                            <?php endfor ?>
                                        </table>
                                    </div><!-- closes map-wrapper -->
                                    <h4>Categories</h4>
                                    <span>Select all that apply</span>
                                    <div class="clear"></div>	
                                </div><!-- closes item -->
                                <?php endif ?>
                            </div><!-- closes item-wrppr -->
                        </div><!-- closes profile-items -->
                    </div><!-- closes content -->
                    <div class="foot">
                        <input type="submit" class="btn-1 noclean" value="Continue" />
                    </div><!-- closes foot -->
                    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
                    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
                    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'edit-listing') ?>" />
                    <input type="hidden" name="_task" value="<?= md5('edit_listing') ?>" />
           		</form>
            </div><!-- closes sign-box -->
        </div><!-- closes wrapper -->
    </div><!-- closes w2 -->
   <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript"> var neww = true; </script>
<script type="text/javascript" src="/js2/provider/listing-edit2.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
    $(document).ready(function() {
		$('a.lb').fancybox({
			padding:0,
			overlayColor:'#000',
			centerOnScroll:1,
			overlayOpacity:0.3
		});
		$('.lbox .btn-2, .lbox .btn-11').click(function(){
			$(this).parents('form').submit();
		});
    });
</script>
<style type="text/css">
#mapcanvas {
	width:435px;
	height:250px;
	background:#09C;
	clear:both;
	margin-top:15px;}
.listing-content .profile-items .item .inner-container > a {
	display:none;}
.listing-content .profile-items .item:hover .inner-container > a {
	display:block;}
.item .inner-form {
	clear:both;
	overflow:hidden;
	padding-top:5px;}
	.item .inner-form input.text {
		float:left;
		width:200px !important;
		vertical-align:middle;}
	.item .inner-form input.btn {
		float:left;
		vertical-align:middle;}
	.item .inner-form .selects {
		display:block;
		clear:both;}
	.hidden { display:none; }
	.jqTransformSelectWrapper { width:150px !important }
	.errors {
		border:1px solid #F00 !important;
		padding:5px !important;
		margin-bottom:30px;}
		.errors h4 {
			text-align:left;
			line-height:18px;
			font-style:italic;
			font-size:12px;
			font-weight:normal !important;
			color:#F00 !important;}
	.w-m {
		float:right;
		width:404px;
		display:none;}
	
</style>
</body>
</html>