<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> : General Info | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/lightboxes.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <!--
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js2/jquery.input.value.js"></script>
    <script type="text/javascript" src="/js2/jquery.elastic.js"></script>
    <script type="text/javascript" src="/js/jquery.jqtransform.js"></script>
    <script type="text/javascript" src="/js2/common.js"></script>
    <script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
	<script type="text/javascript" src="/uploadify/swfobject.js"></script>
    <script type="text/javascript" src="/uploadify/jquery.uploadify.v2.1.4.min.js"></script>
    -->
    <style type="text/css">
	#maplocations ul {
		list-style:none;
		margin-top:10px;
		background:#FFC;}
		#maplocations ul li {
			margin-bottom:5px;}
	#mapcanvas {
		width:356px;
		height:207px;
		background:#09C;
		clear:both;
		margin-top:35px;}
	.listing-content .profile-items .item .inner-container > a {
		display:none;}
	.listing-content .profile-items .item:hover .inner-container > a {
		display:block;}
	.item .inner-form {
		clear:both;
		overflow:hidden;
		padding-top:5px;}
		.item .inner-form input.text {
			float:left;
			width:200px !important;
			vertical-align:middle;}
		.item .inner-form input.btn {
			float:left;
			vertical-align:middle;}
		.item .inner-form .selects {
			display:block;
			clear:both;}
		.hidden { display:none; }
		.errors {
			border:1px solid #F00;
			margin:20px 0 0;
			padding:5px;}
			.errors p {
				color:#F00;
				font-weight:normal;
				font-style:italic;}
				
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="listing-wrapper wrapper">
			<?= $this->partial('partials/vendormainmenu.phtml', array('notifications'=> $this->pendingSettings,'active'=>'All Listings','parentActive'=>'Listings')); ?>
            <?= $this->partial('partials/vendorlistingstop.phtml', array('listing'=>$this->listing)); ?>
            <div class="listing-content show">
                <div class="left">
                    <?= $this->partial('partials/vendorlistingsmenu.phtml', array('active'=>'General Information', 'id' => $this->listing->id, 
									   'type'=>$this->listing->main_type)) ?>
                </div><!-- closes left -->
                <div class="right">
                <?php 	switch($this->listing->main_type):
							case 2:
								echo $this->partial('listing/restaurant/info.phtml', array(
										'errors' 	 => $this->errors,
										'listing'	 => $this->listing,
										'countries'	 => $this->countries,
										'cities'	 => $this->cities,
										'schedules'	 => $this->schedules,
										'attributes' => $this->attributes,
										'categories' => $this->categories,
										'tags'		 => $this->tags,
										'listing_types' => $this->listing_types,
										'listing_tags'	=> $this->listing_tags,
										'cities2'		=> $this->cities2,
										'cities3'		=> $this->cities3,
										'help' => $this->help,
										'vendor' => $this->vendor,
										'landscapes' => $this->landscapes,
										'l_lands'	=> $this->l_lands,
								));
								break;
							case 4:
								echo $this->partial('listing/sight/info.phtml', array(
										'errors' 	 => $this->errors,
										'listing'	 => $this->listing,
										'countries'	 => $this->countries,
										'cities'	 => $this->cities,
										'schedules'	 => $this->schedules,
										'attributes' => $this->attributes,
										'categories' => $this->categories,
										'tags'		 => $this->tags,
										'listing_types' => $this->listing_types,
										'listing_tags'	=> $this->listing_tags,
										'cities2'		=> $this->cities2,
										'cities3'		=> $this->cities3,
										'help' => $this->help,
										'vendor' => $this->vendor,
										'landscapes' => $this->landscapes,
										'l_lands'	=> $this->l_lands,
								));
								break;
							case 5:
								echo $this->partial('listing/hotel/info.phtml', array(
										'errors' 	 => $this->errors,
										'listing'	 => $this->listing,
										'countries'	 => $this->countries,
										'cities'	 => $this->cities,
										'schedules'	 => $this->schedules,
										'attributes' => $this->attributes,
										'categories' => $this->categories,
										'tags'		 => $this->tags,
										'listing_types' => $this->listing_types,
										'listing_tags'	=> $this->listing_tags,
										'cities2'		=> $this->cities2,
										'cities3'		=> $this->cities3,
										'help' => $this->help,
										'vendor' => $this->vendor,
										'landscapes' => $this->landscapes,
										'l_lands'	=> $this->l_lands,
								));
								break;
							case 6:
								echo $this->partial('listing/activity/info.phtml', array(
										'errors' 	 => $this->errors,
										'listing'	 => $this->listing,
										'countries'	 => $this->countries,
										'cities'	 => $this->cities,
										'schedules'	 => $this->schedules,
										'attributes' => $this->attributes,
										'categories' => $this->categories,
										'tags'		 => $this->tags,
										'listing_types' => $this->listing_types,
										'listing_tags'	=> $this->listing_tags,
										'cities2'		=> $this->cities2,
										'cities3'		=> $this->cities3,
										'help' => $this->help,
										'vendor' => $this->vendor,
										'landscapes' => $this->landscapes,
										'l_lands'	=> $this->l_lands,
								));
								break;
							case 7:
								echo $this->partial('listing/entertaiment/info.phtml', array(
										'errors' 	 => $this->errors,
										'listing'	 => $this->listing,
										'countries'	 => $this->countries,
										'cities'	 => $this->cities,
										'schedules'	 => $this->schedules,
										'attributes' => $this->attributes,
										'categories' => $this->categories,
										'tags'		 => $this->tags,
										'listing_types' => $this->listing_types,
										'listing_tags'	=> $this->listing_tags,
										'cities2'		=> $this->cities2,
										'cities3'		=> $this->cities3,
										'help' => $this->help,
										'vendor' => $this->vendor,
										'landscapes' => $this->landscapes,
										'l_lands'	=> $this->l_lands,
								));
								break;
						endswitch ?>
                </div><!-- closes right -->
                <div class="clear"></div>
            </div><!-- closes listing-content -->
        </div><!-- closes listing-wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->

<div class="hidden">
	<?php $hours = array('01','02','03','04','05','06','07','08','09','10','11','12'); ?>
	<?php $mins	 = array('00','15','30','45'); ?>
    <?php $times = array('AM','PM'); ?>
	<?php foreach($this->attributes as $attr): ?>
    <div class="attr" id="attr_<?= $attr->id ?>">
        <form action="" method="post" id="form_attr_<?= $attr->id ?>">
            <div class="lbox lb-size-1">
                <div class="lb-wrapper">
                    <div class="lb-ttl">
                        Edit <?= $attr->name ?>
                    </div><!-- closes lb-ttl -->
                    <div class="lb-content">
                        <div class="entry entry-2">
                            <p><input name="name" class="noclean" type="text" value="<?= stripslashes($attr->name) ?>" /></p>
                        </div><!-- closes entry -->
                        <div class="entry entry-2">
                            <p><input name="value" class="noclean" type="text" value="<?= stripslashes($attr->value) ?>" /></p>
                        </div><!-- closes entry -->
                        <div class="btns">
                            <span class="btn-8" onclick="$.fancybox.close()">Cancel</span>
                            <span class="btn-2">Save</span>
                        </div><!-- closes btns -->
                    </div><!-- closes content -->
                </div><!-- closes lb-wrapper -->
            </div><!-- closes lb-small -->
            <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
            <input type="hidden" name="attr_id" value="<?= $attr->id ?>" />
            <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
            <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'form_attr_'.$attr->id) ?>" />
            <input type="hidden" name="_task" value="<?= md5('edit_attr') ?>" />
        </form>
    </div>
    <?php endforeach ?>
    <?php foreach($this->attributes as $attr): ?>
    <div id="attr_delete_<?= $attr->id ?>" class="attr">
        <form action="" method="post" id="form_attr_delete_<?= $attr->id ?>">
            <div class="lbox lb-size-1">
                <div class="lb-wrapper">
                    <div class="inner-wrapper">
                        <div class="lb-ttl">
                            Are you sure you want to remove "<?= $attr->name ?>" ?
                        </div><!-- closes lb-ttl -->
                        <div class="lb-content">
                            <div class="btns">
                                <span class="btn-8" onclick="$.fancybox.close()">Cancel</span>
                                <span class="btn-11">Delete</span>
                            </div><!-- closes btns -->
                        </div><!-- closes content -->
                    </div><!-- closes inner-wrapper -->
                </div><!-- closes lb-wrapper -->
            </div><!-- closes lb-size-1 -->
            <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
            <input type="hidden" name="attr_id" value="<?= $attr->id ?>" />
            <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
            <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'form_attr_delete_'.$attr->id) ?>" />
            <input type="hidden" name="_task" value="<?= md5('delete_attr') ?>" />
        </form>
    </div>
    <?php endforeach ?>
    <div class="attr" id="attr_new">
        <form action="" method="post" id="form_attr_new">
            <div class="lbox lb-size-1">
                <div class="lb-wrapper">
                    <div class="lb-ttl">
                        Add a new quick fact
                    </div><!-- closes lb-ttl -->
                    <div class="lb-content">
                        <div class="entry entry-2">
                            Quick Fact Name
                            <p><input  class="noclean" name="name" type="text" /></p>
                        </div><!-- closes entry -->
                        <div class="entry entry-2">
                            Quick Fact Value
                            <p><input  class="noclean" name="value" type="text" /></p>
                        </div><!-- closes entry -->
                        <div class="btns">
                            <span class="btn-8" onclick="$.fancybox.close()">Cancel</span>
                            <span class="btn-2">Add</span>
                        </div><!-- closes btns -->
                    </div><!-- closes content -->
                </div><!-- closes lb-wrapper -->
            </div><!-- closes lb-small -->
            <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
            <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
            <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'form_attr_new') ?>" />
            <input type="hidden" name="_task" value="<?= md5('add_attr') ?>" />
        </form>
    </div>
    <?php foreach($this->schedules as $sch): ?>
	<?php if($this->listing->main_type == 5): ?>
    <div id="sch_<?= $sch->id ?>" class="sch">
        <form action="" method="post" id="form_sch_<?= $sch->id ?>">
            <div class="lbox lb-size-1 schedule-lb">
                <div class="lb-wrapper">                    
                    <div class="lb-ttl">Edit <?= $sch->name ?> Room type</div><!-- closes lb-ttl -->
                    <div class="lb-content">
                        <div class="entry entry-2 season-entry">
                            <p><input type="text" class="noclean" name="name" value="<?= $sch->name ?>" /></p>
                        </div><!-- closes entry -->
                        <div class="btns">
                            <span class="btn-8" onclick="$.fancybox.close()">Cancel</span>
                            <span class="btn-2">Save</span>
                        </div><!-- closes btns -->
                    </div><!-- closes content -->
                </div><!-- closes lb-wrapper -->
            </div><!-- closes lb-small -->
            <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
            <input type="hidden" name="sch_id" value="<?= $sch->id ?>" />
            <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
            <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'form_sch_'.$sch->id) ?>" />
            <input type="hidden" name="_task" value="<?= md5('edit_sch') ?>" />
        </form>
    </div>
    <?php else: ?>
    <div id="sch_<?= $sch->id ?>" class="sch">
        <form action="" method="post" id="form_sch_<?= $sch->id ?>">
            <div class="lbox lb-size-1 schedule-lb">
                <div class="lb-wrapper">                    
                    <div class="lb-ttl">Edit <?= $sch->name ?> Schedule</div><!-- closes lb-ttl -->
                    <div class="lb-content">
                        <div class="entry entry-2 season-entry">
                            <p><input type="text" class="noclean" name="name" value="<?= $sch->name ?>" /></p>
                        </div><!-- closes entry -->
                        <div class="entry entry-2">
                            <span>Starting at</span>
                            <?php $time = date('h:i:A', strtotime($sch->starting)) ?>
                            <?php $time = explode(':',$time); ?>
                            <select class="noselect" name="start_hour">
                                <?php foreach($hours as $h): ?>
                                <?php if($h == $time[0]): ?>
                                <option selected="selected" value="<?= $h ?>"><?= $h ?></option>
                                <?php else: ?>
                                <option value="<?= $h ?>"><?= $h ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                            <select class="noselect" name="start_min">
                                <?php foreach($mins as $h): ?>
                                <?php if($h == $time[1]): ?>
                                <option selected="selected" value="<?= $h ?>"><?= $h ?></option>
                                <?php else: ?>
                                <option value="<?= $h ?>"><?= $h ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                            <select class="noselect" name="start_time">
                                <?php foreach($times as $h): ?>
                                <?php if($h == $time[2]): ?>
                                <option selected="selected" value="<?= $h ?>"><?= $h ?></option>
                                <?php else: ?>
                                <option value="<?= $h ?>"><?= $h ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                        </div><!-- closes entry -->
                        <div class="entry entry-2">
                            <span>Ending at</span>
                            <?php $time = date('h:i:A', strtotime($sch->ending)) ?>
                            <?php $time = explode(':',$time); ?>
                            <select class="noselect" name="end_hour">
                                <?php foreach($hours as $h): ?>
                                <?php if($h == $time[0]): ?>
                                <option selected="selected" value="<?= $h ?>"><?= $h ?></option>
                                <?php else: ?>
                                <option value="<?= $h ?>"><?= $h ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                            <select class="noselect" name="end_min">
                                <?php foreach($mins as $h): ?>
                                <?php if($h == $time[1]): ?>
                                <option selected="selected" value="<?= $h ?>"><?= $h ?></option>
                                <?php else: ?>
                                <option value="<?= $h ?>"><?= $h ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                            <select class="noselect" name="end_time">
                                <?php foreach($times as $h): ?>
                                <?php if($h == $time[2]): ?>
                                <option selected="selected" value="<?= $h ?>"><?= $h ?></option>
                                <?php else: ?>
                                <option value="<?= $h ?>"><?= $h ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                        </div><!-- closes entry -->
                        <div class="btns">
                            <span class="btn-8" onclick="$.fancybox.close()">Cancel</span>
                            <span class="btn-2">Save</span>
                        </div><!-- closes btns -->
                    </div><!-- closes content -->
                </div><!-- closes lb-wrapper -->
            </div><!-- closes lb-small -->
            <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
            <input type="hidden" name="sch_id" value="<?= $sch->id ?>" />
            <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
            <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'form_sch_'.$sch->id) ?>" />
            <input type="hidden" name="_task" value="<?= md5('edit_sch') ?>" />
        </form>
    </div>
    <?php endif ?>
    <?php endforeach ?>
    <?php foreach($this->schedules as $sch): ?>
    <div id="sch_delete_<?= $sch->id ?>" class="sch">
        <form action="" method="post" id="form_sch_delete_<?= $sch->id ?>">
            <div class="lbox lb-size-1">
                <div class="lb-wrapper">
                    <div class="inner-wrapper">
                        <div class="lb-ttl">
                            Are you sure you want to remove "<?= $sch->name ?>" ?
                        </div><!-- closes lb-ttl -->
                        <div class="lb-content">
                            <div class="btns">
                                <span class="btn-8" onclick="$.fancybox.close()">Cancel</span>
                                <span class="btn-11">Delete</span>
                            </div><!-- closes btns -->
                        </div><!-- closes content -->
                    </div><!-- closes inner-wrapper -->
                </div><!-- closes lb-wrapper -->
            </div><!-- closes lb-size-1 -->
            <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
            <input type="hidden" name="sch_id" value="<?= $sch->id ?>" />
            <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
            <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'form_sch_delete_'.$sch->id) ?>" />
            <input type="hidden" name="_task" value="<?= md5('delete_sch') ?>" />
        </form>
    </div>
    <?php endforeach ?>
    <?php if($this->listing->main_type == 5) :?>
    <div id="sch_new" class="sch">
        <form action="" method="post" id="form_sch_new">
            <div class="lbox lb-size-1 schedule-lb">
                <div class="lb-wrapper">                    
                    <div class="lb-ttl">Add New Room Type</div><!-- closes lb-ttl -->
                    <div class="lb-content">
                        <div class="entry entry-2 season-entry">
                            <p><input type="text" name="name"  class="noclean" /></p>
                        </div><!-- closes entry -->
                        <div class="btns">
                            <span class="btn-8" onclick="$.fancybox.close()">Cancel</span>
                            <span class="btn-2">Add</span>
                        </div><!-- closes btns -->
                    </div><!-- closes content -->
                </div><!-- closes lb-wrapper -->
            </div><!-- closes lb-small -->
            <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
            <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
            <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'form_sch_new') ?>" />
            <input type="hidden" name="_task" value="<?= md5('add_sch') ?>" />
        </form>
    </div>
    <?php else: ?>
    <div id="sch_new" class="sch">
        <form action="" method="post" id="form_sch_new">
            <div class="lbox lb-size-1 schedule-lb">
                <div class="lb-wrapper">                    
                    <div class="lb-ttl">Add New Schedule</div><!-- closes lb-ttl -->
                    <div class="lb-content">
                        <div class="entry entry-2 season-entry">
                            <p><input type="text" name="name" class="clean" /></p>
                        </div><!-- closes entry -->
                        <div class="entry entry-2">
                            <span>Starting at</span>
                            <?php $time = explode(':',$sch->starting); ?>
                            <select class="noselect" name="start_hour">
                                <?php foreach($hours as $h): ?>
                                <option value="<?= $h ?>"><?= $h ?></option>
                                <?php endforeach ?>
                            </select>
                            <select class="noselect" name="start_min">
                                <?php foreach($mins as $h): ?>
                                <option value="<?= $h ?>"><?= $h ?></option>
                                <?php endforeach ?>
                            </select>
                            <select class="noselect" name="start_time">
                                <?php foreach($times as $h): ?>
                                <option value="<?= $h ?>"><?= $h ?></option>
                                <?php endforeach ?>
                            </select>
                        </div><!-- closes entry -->
                        <div class="entry entry-2">
                            <span>Ending at</span>
                            <?php $time = explode(':',$sch->ending); ?>
                            <select class="noselect" name="end_hour">
                                <?php foreach($hours as $h): ?>
                                <option value="<?= $h ?>"><?= $h ?></option>
                                <?php endforeach ?>
                            </select>
                            <select class="noselect" name="end_min">
                                <?php foreach($mins as $h): ?>
                                <option value="<?= $h ?>"><?= $h ?></option>
                                <?php endforeach ?>
                            </select>
                            <select class="noselect" name="end_time">
                                <?php foreach($times as $h): ?>
                                <option value="<?= $h ?>"><?= $h ?></option>
                                <?php endforeach ?>
                            </select>
                        </div><!-- closes entry -->
                        <div class="btns">
                            <span class="btn-8" onclick="$.fancybox.close()">Cancel</span>
                            <span class="btn-2">Add</span>
                        </div><!-- closes btns -->
                    </div><!-- closes content -->
                </div><!-- closes lb-wrapper -->
            </div><!-- closes lb-small -->
            <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
            <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
            <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'form_sch_new') ?>" />
            <input type="hidden" name="_task" value="<?= md5('add_sch') ?>" />
        </form>
    </div>
    <?php endif ?>
</div>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/provider/listing-edit.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('textarea').elastic();	
		//$('select:not(.noselect)').jqTransSelect();			
		$('a.lb').fancybox({
			padding:0,
			overlayColor:'#000',
			centerOnScroll:1,
			overlayOpacity:0.3
		});
		$('.lbox .btn-2, .lbox .btn-11').click(function(){
			$(this).parents('form').submit();
		});
		$('#file_upload').uploadify({
			'uploader'		  : '/uploadify/uploadify.swf',
			'script'   		  : '/phpscripts/uploadListingPhotos.php',
			'cancelImg'		  : '/uploadify/cancel.png',
			'folder'  		  : '/uploads',
			'buttonImg' 	  : '/images2/file-1.png',
			'buttonText' 	  : 'Add Photos',
			'auto'      	  : true,
			'removeCompleted' : false,
			'onError':function(e,a,c,d){
				console.log(e);
				console.log(a);
				console.log(c);
				console.log(d);
			},
			'onComplete':function(a,b,c,image){
				var $img = $('.picture img:eq(0)');
				$img.attr('src',image);
				$img.attr('width',58);
				$img.attr('height',58);
				console.log(image);
			},
			'scriptData':{
				'userids':<?= $this->user->id ?>,
				'vendorid':<?= $this->vendor->id ?>,
				'listings':<?= $this->listing->id ?>,
				'listtoken':'<?= $this->listing->token ?>',
				'formtoken':'<?= $this->user->token ?>',
				'usertoken':'<?= md5($this->user->token.'upload_listing_pictures') ?>',
				'main':'1',
			}
		});
		$('input[name=capacity]').change(function(){
			$cont = $(this).parents('.item-wrppr').find('.single-schedule');
			if($(this).val() == 'single'){
				$cont.fadeIn('slow', function(){
					$('select', $cont).removeAttr('disabled');
				});
			} else {
				$('select', $cont).attr('disabled', 'disabled');
				$('input', $cont).removeAttr('checked');
				$('input', $cont).change();
				$cont.fadeOut('slow');
			}
		});
		$('input[name=kids]').change(function(){
			if($(this).attr('checked') == undefined){
				$('.accept-kids').addClass('hidden');
				$('.accept-kids select').attr('disabled','disabled');
			} else {
				$('.accept-kids').removeClass('hidden');
				$('.accept-kids select').removeAttr('disabled');
			}
		});
	});
</script>
</body>
</html>