<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Offers | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
	<script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
	$(function(){
		$('.vendor-offers table tr td').hover(function(){
			$(this).addClass('hover');
		}, function(){
			$(this).removeClass('hover');
		}).click(function(){
			$input = $(this).parent('tr').find('input[type=checkbox]');
			if($input.attr('checked') == undefined)
				$input.attr('checked','checked');
			else
				$input.removeAttr('checked');
		});
		$checked = false;
		$('.vendor-offers table th input[type=checkbox]').change(function(e){
			e.preventDefault();
			if($checked)
				$('.vendor-offers input[type=checkbox]').removeAttr('checked');
			else
				$('.vendor-offers input[type=checkbox]').attr('checked','checked');
			$checked = !$checked;
		});
		$('.vendor-offers table td input[type=checkbox]').change(function(e){
			e.preventDefault();
			if($(this).attr('checked') == undefined)
				$(this).attr('checked','checked');
			else
				$(this).removeAttr('checked');
		});
		
		$('.lb-itinerary .days').cycle({
			timeout:0,
			prev:'.prevday',
			next:'.nextday'
		});
		$('.lb-itinerary .days .tabs').tabs();
		$('td.explore a').fancybox({
			padding:0,
			autoScale:0,
			centerOnScroll:1,
			overlayColor:'#fff',
			showCloseButton:0,
			overlayOpacity:0.5
		});
		$('.description-offer a.btn-1, .vendor-offers a.btn-1').fancybox({
			padding:0,
			centerOnScroll:1,
			overlayColor:'#fff',
			showCloseButton:0,
		});
		<?php if(isset($_GET['success'])): ?>
		showAlert('The offer has been successfuly placed');
		<?php endif ?>
	});
	</script>
    <style type="text/css">
	.vendor-offers tr.hover {
		background: none repeat scroll 0 0 #EDF7FF;}
	.hidden {
		display:none;}
	.lb-itinerary {
		width:533px;
		height:463px;
		background:#fff;
		border-radius:5px;}
	.lb-itinerary .lb-title {
		background:url(/images2/lb-itinerary-title.gif) repeat-x;
		height:44px;
		line-height:44px;
		padding-left:10px;
		color:#fff;
		font-weight:bold;
		font-size:13px;}
		.lb-itinerary .lb-title span {
			float:right;
			padding:0px 22px;
			background:url(/images2/lb-itinerary-title-days.gif) top left no-repeat #181818;
			height:26px;
			line-height:26px;
			margin-top:9px;
			font-size:12px;}
	.lb-itinerary .itinerary {
		position:relative;}
		.lb-itinerary .itinerary a.prev,
		.lb-itinerary .itinerary a.next {
			position:absolute;
			font-size:12px;
			color:#60b5f7;
			font-weight:bold;
			z-index:1000;}
		.lb-itinerary .itinerary a.prev {
			top:13px;
			left:15px;
			padding-left:13px;
			background:url(/images2/arrow-9.png) left center no-repeat;}
		.lb-itinerary .itinerary a.next {
			top:13px;
			right:15px;
			padding-right:13px;
			background:url(/images2/arrow-10.png) right center no-repeat;}
	.lb-itinerary .days {
		width:533px;
		height:364px;
		overflow:hidden;}
	.lb-itinerary .day {
		width:533px;
		height:364px;}
		.lb-itinerary .day h4 {
			font-weight:bold;
			text-align:center;
			color:#303030;
			line-height:41px;}
		.lb-itinerary .day ul.tab-menu {
			display:block;
			background:url(/images2/lb-itinerary-days-tabs-menu-bg.gif) repeat-x;
			height:40px;
			text-align:center;}
			.lb-itinerary .day ul.tab-menu li {
				display:inline-block;
				overflow:hidden;}
				.lb-itinerary .day ul.tab-menu li a {
					float:left;
					padding:2px 24px 5px;
					line-height:33px;
					color:#303030;
					font-size:12px;}
				.lb-itinerary .day ul.tab-menu li a:hover {
					color:#898989;
					text-decoration:none;}
				.lb-itinerary .day ul.tab-menu li.ui-tabs-selected a {
					color:#898989;
					background:url(/images2/lb-itinerary-days-tabs-menu-active.gif) bottom center no-repeat;}
		.lb-itinerary .day .tab {
			height:283px;
			overflow-y:auto;}
		.lb-itinerary .day .tab.ui-tabs-hide {
			display:none;}
			.lb-itinerary .day .tab .row {
				padding:12px 18px;
				border-top:1px solid #e8e8e8;
				overflow:hidden;}
			.lb-itinerary .day .tab .row:first-child {
				border-top:0 none;}
				.lb-itinerary .day .tab .row img {
					float:left;
					margin-right:12px;}
				.lb-itinerary .day .tab .row p {
					float:left;
					margin-top:6px;
					font-size:12px;
					line-height:16px;}
				.lb-itinerary .day .tab .row a {
					float:right;
					padding-left:20px;
					line-height:12px;
					font-size:12px;
					background:url(/images2/eye.png) bottom left no-repeat;
					color:#60b5f7;
					margin-top:17px;}
		.lb-itinerary .lb-foot {
			background:url(/images2/lb-itinerary-footer.gif) repeat-x;
			height:55px;}
			.lb-itinerary .lb-foot a {
				float:right;
				margin:16px;}
	#fancybox-bg-n,
	#fancybox-bg-ne,
	#fancybox-bg-e,
	#fancybox-bg-se,
	#fancybox-bg-s,
	#fancybox-bg-sw,
	#fancybox-bg-w,
	#fancybox-bg-nw {
		background:none;}
	#fancybox-content {
		box-shadow:0 0 10px 5px #CCC;}
	.select_listing ul { margin:0;}
	.select_listing ul li input[type="button"],
	.select_listing ul li input[type="submit"] {
		height:30px;}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-backend">
            <?= $this->partial('partials/vendormainmenu.phtml', array('notifications'=> $this->pendingSettings,'active'=>'Offers','parentActive'=>'Offers')); ?>
            <?php if(count($this->listings) > 0): ?>
            <?php if(count($this->offers) > 0): ?>
            <div class="description-offer">
                <h2><?= count($this->offers) ?> people will travel near of your listing location</h2>
                <ul>
                    <li><a href="#selectListing" class="btn-1">Make a multiple Offer</a></li>
                    <li><a href="" class="btn-13"><span>Remove Selected</span></a></li>
                </ul>
            </div><!--DESCRIPTION-OFFER-->
            <div class="vendor-offers">
                <table width="958" border="1">
                    <tr>
                        <th align="left" width="37"><input type="checkbox" value="" /></th>
                        <th align="left" width="200">Traveler Name</th>
                        <th align="left" width="117">Trip Starting Date</th>
                        <th align="left" width="117">Trip Ending Date</th>
                        <th align="left" width="69">Travelers</th>
                        <th align="left" colspan="1" width="140">Destination</th>
                    </tr>
                    <?php foreach($this->offers as $i => $offer): ?>
                    <tr class="<?= ($i == 0) ? 'first' : '' ?>">
                        <td><input type="checkbox" value="" /></td>
                        <?php $image = (!empty($offer->image)) ? $offer->image : '/images/default-profile.gif' ?>
                        <td><p><?= $this->thumbnail(32, $image, '', '1:1') ?> <span><?= $offer->name ?></span></p></td>
                        <td><?= (!is_null($offer->start)) ? date('M jS, Y', strtotime($offer->start)) : 'Not Defined' ?></td>
                        <td><?= (!is_null($offer->end)) ? date('M jS, Y', strtotime($offer->end)) : 'Not Defined' ?></td>
                        <td><?= $offer->adults ?></td>
                        <td>San Jose, Costa Rica</td>
                        <td class="explore"><a href="/ajax/loaditinerary/<?= $offer->id ?>">Explore Itineray</a></td>
                        <td><a href="#selectListing" class="btn-1">Make an Offer</a></td>
                    </tr>
                    <?php endforeach ?>
                </table>
            </div><!--VENDOR-OFFERS-->
            <?php else: ?>
            <div class="empty-container">
                <img src="/images/empty-10.png" alt="" /><br />
                There is no people traveling to your city at the momment
            </div><!-- closes empty -->            
            <?php endif ?>
            <?php else: ?>
            <div class="empty-container">
                <img src="/images/empty-10.png" alt="" /><br />
                You don't have any active listing to offer
            </div><!-- closes empty -->
            <?php endif ?>
        </div><!-- closes user-backend -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div class="hidden">
	<div id="selectListing">
    	<div class="select_listing">
            <h2>Choose the listing you would like to offer</h2>
            <form action="/en-US/provider/offers/new" method="post">
                <select name="listing">
                	<?php foreach($this->listings as $listing): ?>
                    <option value="<?= $listing->id ?>"><?= $listing->title ?></option>
                    <?php endforeach ?>
                </select>
                <ul>
                    <li><input class="btn-1" type="submit" value="Select Listing" /></li>
                    <li><input class="btn-13" onclick="$.fancybox.close(); return false;" type="button" value="Cancel" /></li>
                </ul>
            </form>
        </div><!--SELECT_LISTING-->
    </div>
</div>
</body>
</html>