<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> - Reservations History | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages">
            <?= $this->partial('partials/vendormainmenu.phtml', array('active'=>'History','parentActive'=>'Reservations')); ?>
            <div class="subttl">
                <a href="/provider/reservations" class="link-4">Back to Reservations</a>
            	<p>History Reservations</p>
            </div>
            <?php if(count($this->reservations) > 0): ?>
            <div class="reservations past">
                <table cellpadding="0" cellspacing="0" border="0">
                    <tbody>
                        <tr>
                            <th>Reservation Code</th>
                            <th>Client Name</th>
                            <th>Method</th>
                            <th>Amount</th>
                            <th>Date</th>
                            <th>&nbsp;</th>
                        </tr>
                        <?php foreach($this->reservations as $reserve): ?>
                        <tr>
                            <td><?= $reserve->code ?></td>
                            <td><?= $reserve->user_name ?></td>
                            <td><img class="card-3" src="https://static.tripfab.com/images/cleardot.gif" alt=""/><?= $reserve->method ?></td>
                            <td>$<?= $reserve->ammount ?></td>
                            <td><?= date('d/m/Y', strtotime($reserve->checkin)) ?></td>
                            <td><a href="/cart/invoice/<?= $reserve->id ?>">See details</a></td>
                        </tr>
                        <?php endforeach ?>					
                    </tbody>
                </table>
            </div><!-- closes reservations -->
            <?php else: ?>
            <div class="empty-container">
                <img src="https://static.tripfab.com/images/empty-7.png" alt="" /><br />
                There are no incoming reservations :(
            </div><!-- closes empty -->            
            <?php endif ?>
        </div><!-- closes user-messages -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
    $(document).ready(function() {
		
		$('.reservation .top h2').click(function(){
			$parent = $(this).parents('.reservation');
			$('.bottom', $parent).slideToggle();
		});
    });
</script>
<style type="text/css">
.reservations.past {
	background-color: #FFFFFF;
	border: 1px solid #E7E7E7;
	border-radius: 4px 4px 4px 4px;
}
</style>
</body>
</html>
