<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>vendor reservations 4</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->

</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages">
            <?= $this->partial('partials/vendormainmenu.phtml', array('active'=>'Transactions','parentActive'=>'Reservations')); ?>
            <div class="transactions">
                <div class="left">
                    <table border="0" cellpadding="0" cellspacing="0">
                        <tbody>
                            <tr>
                                <th>code</th>
                                <th>name</th>
                                <th>method</th>
                                <th>amount</th>
                                <th>date</th>
                                <th>&nbsp;</th>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                            <tr>
                                <td>8478979846541414</td>
                                <td>Nelson Riccardi</td>
                                <td>Mastercard</td>
                                <td>$49</td>
                                <td>14/02/2011</td>
                                <td><a href="">View Details</a></td>
                            </tr>
                        </tbody>
                    </table>
                </div><!-- closes left -->
                <div class="right">
                    <div class="widget">
                        <div class="ttl">
                            My Total Earnings
                        </div><!-- closes ttl -->
                        <div class="content">
                            <strong>$2,584</strong>
                            <a href="" class="btn-1">Withdraw</a>
                        </div><!-- closes content -->
                    </div><!-- closes widget -->
                </div><!-- closes right -->
            </div><!-- closes transactions -->
        </div><!-- closes user-messages -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="/js2/jquery.js"></script>
</body>
</html>