<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> - Reviews | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
	<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
	<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages">
        	<?php $icons = array(
				2 => 'ico-11.png',
				4 => 'ico-10.png',
				5 => 'ico-12.png',
				6 => 'ico-8.png',
				7 => 'ico-9.png',
			) ?>
            <?= $this->partial('partials/vendormainmenu.phtml', array('active'=>'Reviews','parentActive'=>'Reviews \&amp; Questions')); ?>
            <div class="reviews-questions">
            	<?php foreach($this->listings as $listing): ?>
                <div class="s-question">
                    <div class="right">
                        <div><a href="/provider/reviews/view/<?= $listing->id ?>" class="btn-4">See Reviews</a></div>
                        <?php if($this->new[$listing->id] > 0): ?>
                        <div><span><?= $this->new[$listing->id] ?></span> New Reviews</div>
                        <?php endif ?>
                    </div><!-- closes right -->
                    <?= $this->thumbnail(97, $listing->image, '','1:1') ?>
                    <h2><img src="https://static.tripfab.com/images2/<?= $icons[$listing->main_type] ?>" alt="" /><?= $listing->title ?></h2>
                </div><!-- closes s-question -->
                <?php endforeach ?>
            </div><!-- closes reviews-questions -->
        </div><!-- closes user-messages -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('textarea').elastic();				
        $('input').ToggleInputValue();
        $('form select').jqTransSelect();
    });
</script>
</body>
</html>