<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Welcome to Tripfab for providers | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
	<script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('input:not(.noclean)').ToggleInputValue();
            $('form input').focus(function() {
            	$(this).prev('label').addClass('hide');
            });
            $('form input').focusout(function() {
            	if (!$(this).val()) {
            		$(this).prev('label').removeClass('hide');
            	}
            });
			
			$('.sign-box form').validate({
				rules: {
					name:"required",
					email:"required email",
					password:"required",
					password2:{
						required:true,
						equalTo:'#password'},
					phone:"required",
					website:"required url",
					country_id:'required',
				},
				
			}); 
			
			$('input[name=email]').blur(function(){$(this).val($.trim($(this).val()));});
			$('input[name=website]').blur(function(){$(this).val($.trim($(this).val()));});
        });
		
		function isEmpty(element){
			return (element.value == element.title) ? false : (element.value == "") ? false : true;
		}
    </script>
    <style type="text/css">
	.error { border:1px solid #F00; padding:5px; margin-bottom:10px; color:#F00; font-style:italic;}
	.hidden { display:none;}
	label.error { 
		right:0px !important;
		bottom:0px !important;
		line-height:14px !important;
		font-size:12px !important;
		top:auto !important;
		left:auto !important;
		height:auto !important;
		padding:2px 4px !important;
		margin-bottom:0px !important;
		background:#F00 !important;
		color:#fff !important;
		font-weight:bold !important;
		border:0 none !important;
	    z-index: 100;}
	.sign-box .content input.in-1 {
		background-image:url(/images2/ico-200.png);}
	.sign-box .content input.in-6 {
		background-image:url(/images2/ico-201.png);}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>    
    <div class="w2">
        <div class="small-wrapper">
            <div class="sign-box vendor">
                <h2>Sign Up for Tripfab</h2>
                <p>Making your trip fabulous!</p>
                <div class="content su">
                	<?php if($this->errors): ?>
                    <div class="error">
                    	<?php foreach($this->errors as $err): ?>
	                    	<?= $err ?><br />
                        <?php endforeach ?>
                    </div>
                    <?php endif ?>
                    <form method="post" action="">
                        <fieldset>
                            <span>
                        	<?php if(isset($_POST['name'])): ?>
                            <input type="text" name="name" value="<?= $_POST['name'] ?>" class="in-1 noclean" />
                            <?php else: ?>
                        		<label for="name">Company Name</label>
                            	<input type="text" name="name" class="in-1" />                            
                            <?php endif ?>
                            </span>
                        	<span>
                        	<?php if(isset($_POST['contact'])): ?>
                            <input type="text" name="contact" value="<?= $_POST['contact'] ?>" class="in-1 noclean" />
                            <?php else: ?>
                        		<label for="contact">Contact Name</label>
                            	<input type="text" name="contact" class="in-6" />                            
                            <?php endif ?>
                            </span>
                            <span>
                        	<?php if(isset($_POST['email'])): ?>
                            <input type="text" name="email" value="<?= $_POST['email'] ?>" class="in-2 noclean" />
                            <?php else: ?>
                        		<label for="email">E-Mail</label>
	                            <input type="text" name="email" class="in-2" />
                            <?php endif ?>
                            </span>
                            <span>
                            	<label for="password">Password</label>
                            	<input id="password" type="password" name="password" class="in-3" />
                            </span>    
                            <span>
                            	<label for="password2">Confirm Password</label>
                            	<input type="password" name="password2" class="in-4" />
                            </span>
                            <span>
                        	<?php if(isset($_POST['phone'])): ?>
                            <input type="text" name="phone" value="<?= $_POST['phone'] ?>" class="in-5 noclean" />
                            <?php else: ?>  
                            	<label for="phone">Phone</label>                            
                            	<input type="text" name="phone" class="in-5" />
                            <?php endif ?>
                            </span>
                            <span>
                        	<?php if(isset($_POST['website'])): ?>
                            <input type="text" name="website" value="<?= $_POST['website'] ?>" class="in-6 noclean" />
                            <?php else: ?>
	                        <input type="text" name="website" value="http://" class="in-6 noclean" />
                            <?php endif ?>
                            </span>
                            <span>
                        	<?php if(isset($_POST['country_id'])): ?>
                            <select name="country_id">
                                <option value="">Select Country</option>
                                <?php foreach($this->countries as $c): ?>
                                <?php if($_POST['country_id'] == $c->id): ?>
                                <option selected="selected" value="<?= $c->id ?>"><?= $c->title ?></option>
                                <?php else: ?>
                                <option value="<?= $c->id ?>"><?= $c->title ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                            <?php else: ?>
                            <select name="country_id">
                                <option value="">Select Country</option>
                                <?php foreach($this->countries as $c): ?>
                                <option value="<?= $c->id ?>"><?= $c->title ?></option>
                                <?php endforeach ?>
                            </select>
                            <?php endif ?>
                            </span>
                        </fieldset>
                        <fieldset>
                            <input type="checkbox" />
                            <label>Remember me next time</label>
                            <input type="submit" value="Activate Account" class="noclean btn-1" />
                        </fieldset>
                    </form>
                </div><!-- closes content -->
                <div class="foot">
                    By clicking "Activate Account" you confirm that you accept the <a href="">Terms of Service</a>.
                </div><!-- closes foot -->
            </div><!-- closes sign-box -->
        </div><!-- closes small-wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->	
</body>
</html>