<style type="text/css">
.item { position:relative;}
.item .help {
	position:absolute;
	top:13px;
	left:-35px;}
.item .help a.eye {
	display:block;
	background:url(/images2/eye.png) no-repeat top left;
	width:18px;
	height:12px;
	text-indent:-9999px;
	cursor:pointer;}
	.item .help:hover a.eye {
		background-position:left -12px;}
.item.first .help {
	top:0px;}
	.item .help a.tooltip3 {
		background:url(/images2/help-tooltip-bg.png) top left no-repeat;
		left: 17px;
		padding:11px 12px;
		position:absolute;
		top:-102px;
		z-index:1000;
		display:none;}
	.item .help:hover a.tooltip3 {
		display:block;}

.profile-items {
	overflow:visible;}
.lstng-detail .help {
	position:absolute;
	top:20px;
	left:280px;}
.lstng-detail .help a.eye {
	display:block;
	background:url(/images2/eye.png) no-repeat top left;
	width:18px;
	height:12px;
	text-indent:-9999px;
	cursor:pointer;}
	.lstng-detail .help:hover a.eye {
		background-position:left -12px;}
.lstng-detail.first .help {
	top:0px;}
	.lstng-detail .help a.tooltip3 {
		background:url(/images2/help-tooltip-bg.png) top left no-repeat;
		left: 17px;
		padding:11px 12px;
		position:absolute;
		top:-102px;
		z-index:1000;
		display:none;}
	.lstng-detail .help:hover a.tooltip3 {
		display:block;}

.lstng-detail {
	overflow:visible;}
.listing-content { overflow:visible;}
</style>
<?php if($_POST): ?>
<form action="" method="post">
    <div class="profile-items">
    	<?php if(count($this->errors) > 0): ?>
        <?php foreach($this->errors as $err): ?>
        <div class="error">
        	<p><?= $err ?></p>
        </div>
		<?php endforeach ?>
        <?php endif ?>
        <div class="main-ttl">
            <a href="/provider/listings/types/<?= $this->listing->id ?>" class="link-4">Activity Types</a>
            <p><strong><?= $_POST['name'] ?></strong></p>        	
        </div><!-- closes main-ttl -->
        <div class="item-wrppr">
            <div class="item-ttl">
                Basic Information
            </div><!-- closes item ttl -->
            <div class="item first">
                <input tabindex="1" name="name" class="noclean" placeholder="Enter the name here" type="text" value="<?= $_POST['name'] ?>" />
                <h4>Activity Type Name</h4>
                <span>Write the name for this activity type</span>
                <div class="help">
                    <a href="/images2/help/big-act-types-name.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-name.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-name.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="item last">
                <textarea tabindex="2" class="noclean" name="description" placeholder="Write a short description here" cols="30" rows="1"><?= $_POST['description'] ?></textarea>
                <h4>Description</h4>
                <span>Write the description for this activity type</span>
                <div class="help">
                    <a href="/images2/help/big-act-types-description.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-description.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-description.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="clear"></div>									
        </div><!-- closes item-wrppr -->
        <div class="item-wrppr">
            <div class="item-ttl">
                Capacity
            </div><!-- closes item ttl -->
            <div class="item first">
                <div class="selects">
                    <select tabindex="3" name="min">
                        <option value="1">1 person</option>
                    	<?php for($i=2;$i<=50;$i++): ?>
                        <?php $selected = ($i == $_POST['min']) ? 'selected="selected"' : '' ?>
                        <option <?= $selected ?> value="<?= $i ?>"><?= $i ?> people</option>
                        <?php endfor ?>
                    </select>
                </div><!-- closes selects -->
                <h4>Minimum Capacity</h4>
                <span>Select the Minimum people</span>
                <div class="help">
                    <a href="/images2/help/big-act-types-capacity.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-capacity.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-capacity.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="item last">
                <div class="selects">
                    <select tabindex="4" name="max">
                        <option value="1">1 person</option>
                    	<?php for($i=2;$i<=50;$i++): ?>
                        <?php $selected = ($i == $_POST['max']) ? 'selected="selected"' : '' ?>
                        <option <?= $selected ?> value="<?= $i ?>"><?= $i ?> people</option>
                        <?php endfor ?>
                    </select>
                </div><!-- closes selects -->
                <h4>Maximum Capacity</h4>
                <span>Select the maximum people</span>
            </div><!-- closes item -->
            <div class="clear"></div>									
        </div><!-- closes item-wrppr -->
        <div class="item-wrppr">
            <div class="item-ttl">
                Children Options
            </div><!-- closes item ttl -->
            <div class="item first">
				<?php $checked = (isset($_POST['kids'])) ? 'checked="checked"' : '' ?>
                <input tabindex="5" <?= $checked ?> type="checkbox" name="kids" value="1" />
                <label>This activity type accepts children</label>
                <div class="help">
                    <a href="/images2/help/big-act-types-children.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-children.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-children.png" /></a>
                </div>
            </div><!-- closes item -->
            <?php $class = (isset($_POST['kids'])) ? '' : 'hidden' ?>
            <?php $disabled = (!empty($class)) ? 'disabled="disabled"' : '' ?>
            <div class="accept-kids <?= $class ?>">
                <div class="item last">
                    <div class="selects">
                        <select tabindex="6" <?= $disabled ?> name="kid_age_max">
                        	<?php for($i=1;$i<=12;$i++): ?>
                            <?php $selected = ($i == $_POST['kid_age_max']) ? 'selected="selected"' : '' ?>
                            <option <?= $selected ?> value="<?= $i ?>">Under <?= $i ?> years</option>
                            <?php endfor ?>
                        </select>
                    </div><!-- closes selects -->
                    <h4>Child Age</h4>
                    <span>What age do you consider as a child?</span>
                </div><!-- closes item -->
            </div><!-- accept-kids -->
            <div class="clear"></div>
        </div><!-- closes item-wrppr -->
         <div class="lstng-details">
            <div class="lstng-detail faq">
                <strong>Activity Type Requirements</strong>
                <span>Write the requeriments for this activity type</span>
                <br />
				<?php $tab = 8; ?>
                <?php if(count($_POST['tips']) > 0): ?>
                <?php foreach($_POST['tips'] as $i => $tip): ?>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tips[<?= $i ?>][text]" value="<?= $tip['text'] ?>" />
                    <div class="clear"></div>
                </div>
                <?php $tab++ ?>
                <?php endforeach ?>
                <?php endif ?>
                
                <?php if(count($_POST['tip']) > 0): ?>
                <?php foreach($_POST['tip'] as $i => $tip): ?>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tip[<?= $i ?>][text]" value="<?= $tip['text'] ?>" />
                    <div class="clear"></div>
                </div>
                <?php $tab++ ?>
                <?php endforeach ?>
                <?php endif ?>
                <?php if(count($_POST['tips']) == 0 and count($_POST['tip']) == 0): ?>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tip[0]" />
                    <div class="clear"></div>
                </div>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab++ ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tip[1]" />
                    <div class="clear"></div>
                </div>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab++ ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tip[2]" />
                    <div class="clear"></div>
                </div>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab++ ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tip[3]" />
                    <div class="clear"></div>
                </div>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab++ ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tip[4]" />
                    <div class="clear"></div>
                </div>
                <?php endif ?>
                <div class="itemm newitem hidden">
                    <a href="" class="remove">remove</a>
                    <input class="noclean" placeholder="Enter the requirement text here" type="text" name="text" value="" />
                    <div class="clear"></div>
                </div>
                <a href="" id="addNewTip" class="link-5">Add another requirement</a>
                <div class="clear"></div>
                <div class="help">
                    <a href="/images2/help/big-act-types-requeriments.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-requeriments.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-requeriments.png" /></a>
                </div>
            </div><!-- closes lstng-detail -->
         </div><!-- closes lstng-details -->
    </div><!-- closes profile-items -->
    <div class="foot">
        <input type="submit" class="noclean btn-1" value="Save Changes" />
        <a href="">Deactivate Listing</a>
    </div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'add-type') ?>" />
    <input type="hidden" name="_task" value="<?= md5('add_type') ?>" />
    <?php if(isset($_POST['typeid'])): ?>
    <input type="hidden" name="typeid" value="<?= $_POST['typeid'] ?>" />
    <?php endif ?>
</form>
<?php else: ?>
<?php if($this->data): ?>
<?php $type = $this->data['type'] ?>
<?php $tips = $this->data['tips'] ?>
<form action="" method="post">
    <div class="profile-items">
        <div class="main-ttl">
            <a href="/provider/listings/types/<?= $this->listing->id ?>" class="link-4">Activity Types</a>
            <p><strong><?= $type->name ?></strong></p>        	
        </div><!-- closes main-ttl -->
        <div class="item-wrppr">
            <div class="item-ttl">
                Basic Information
            </div><!-- closes item ttl -->
            <div class="item first">
                <input tabindex="1" class="noclean" name="name" placeholder="Enter the name here" type="text" value="<?= $type->name ?>" />
                <h4>Activity Type Name</h4>
                <span>Write the name for this activity type</span>
                <div class="help">
                    <a href="/images2/help/big-act-types-name.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-name.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-name.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="item last">
                <textarea tabindex="2" class="noclean" name="description" placeholder="Write a short description here" 
                cols="30" rows="1"><?= $type->description ?></textarea>
                <h4>Description</h4>
                <span>Write the description for this activity type</span>
                <div class="help">
                    <a href="/images2/help/big-act-types-description.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-description.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-description.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="clear"></div>									
        </div><!-- closes item-wrppr -->
        <div class="item-wrppr">
            <div class="item-ttl">
                Capacity
            </div><!-- closes item ttl -->
            <div class="item first">
                <div class="selects">
                    <select tabindex="3" name="min">
                        <option value="1">1 person</option>
                    	<?php for($i=2;$i<=50;$i++): ?>
                        <?php $selected = ($i == $type->min) ? 'selected="selected"' : '' ?>
                        <option <?= $selected ?> value="<?= $i ?>"><?= $i ?> people</option>
                        <?php endfor ?>
                    </select>
                </div><!-- closes selects -->
                <h4>Minimum Capacity</h4>
                <span>Select the Minimum people</span>
                <div class="help">
                    <a href="/images2/help/big-act-types-capacity.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-capacity.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-capacity.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="item last">
                <div class="selects">
                    <select tabindex="4" name="max">
                        <option value="1">1 person</option>
                    	<?php for($i=2;$i<=50;$i++): ?>
                        <?php $selected = ($i == $type->max) ? 'selected="selected"' : '' ?>
                        <option <?= $selected ?> value="<?= $i ?>"><?= $i ?> people</option>
                        <?php endfor ?>
                    </select>
                </div><!-- closes selects -->
                <h4>Maximum Capacity</h4>
                <span>Select the maximum people</span>
            </div><!-- closes item -->
            <div class="clear"></div>									
        </div><!-- closes item-wrppr -->
        <div class="item-wrppr">
            <div class="item-ttl">
                Children Options
            </div><!-- closes item ttl -->
            <div class="item first">
				<?php $checked = ($type->kids == 1) ? 'checked="checked"' : '' ?>
                <input tabindex="5" <?= $checked ?> type="checkbox" name="kids" value="1" />
                <label>This activity type accepts children</label>
                <div class="help">
                    <a href="/images2/help/big-act-types-children.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-children.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-children.png" /></a>
                </div>
            </div><!-- closes item -->
            <?php $class = ($type->kids == 1) ? '' : 'hidden' ?>
            <?php $disabled = (!empty($class)) ? 'disabled="disabled"' : '' ?>
            <div class="accept-kids <?= $class ?>">
                <div class="item last">
                    <div class="selects">
                        <select tabindex="6" <?= $disabled ?> name="kid_age_max">
                        	<?php for($i=1;$i<=12;$i++): ?>
                            <?php $selected = ($i == $type->kid_age_max) ? 'selected="selected"' : '' ?>
                            <option <?= $selected ?> value="<?= $i ?>">Under <?= $i ?> years</option>
                            <?php endfor ?>
                        </select>
                    </div><!-- closes selects -->
                    <h4>Child Age</h4>
                    <span>What age do you consider as a child?</span>
                </div><!-- closes item -->
            </div><!-- accept-kids -->
            <div class="clear"></div>
        </div><!-- closes item-wrppr -->
         <div class="lstng-details">
            <div class="lstng-detail faq">
                <strong>Activity Type Requeriments</strong>
                <span>Write the requeriments for this activity type</span>
                <br />
                <?php $tab = 8 ?>
                <?php if(count($tips) > 0): ?>
                <?php foreach($tips as $tip): ?>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tips[<?= $tip->id ?>][text]" value="<?= $tip->text ?>" />
                    <div class="clear"></div>
                </div>
                <?php $tab++ ?>
                <?php endforeach ?>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tip[0][text]" value="" />
                    <div class="clear"></div>
                </div>
                <?php else: ?>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tip[0]" />
                    <div class="clear"></div>
                </div>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab++ ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tip[1]" />
                    <div class="clear"></div>
                </div>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab++ ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tip[2]" />
                    <div class="clear"></div>
                </div>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab++ ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tip[3]" />
                    <div class="clear"></div>
                </div>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="<?= $tab++ ?>" class="noclean" placeholder="Enter the requirement text here" type="text" name="tip[4]" />
                    <div class="clear"></div>
                </div>
                <?php endif ?>
                <div class="itemm newitem hidden">
                    <a href="" class="remove">remove</a>
                    <input class="noclean" placeholder="Enter the requirement text here" type="text" name="text" value="" />
                    <div class="clear"></div>
                </div>
                <a href="" id="addNewTip" class="link-5">Add another requirement</a>
                <div class="clear"></div>
                <div class="help">
                    <a href="/images2/help/big-act-types-requeriments.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-requeriments.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-requeriments.png" /></a>
                </div>
            </div><!-- closes lstng-detail -->
         </div><!-- closes lstng-details -->
    </div><!-- closes profile-items -->
    <div class="foot">
        <input type="submit" class="noclean btn-1" value="Save Changes" />
        <a href="">Deactivate Listing</a>
    </div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="typeid" value="<?= $type->id ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'edit-type') ?>" />
    <input type="hidden" name="_task" value="<?= md5('edit_type') ?>" />
</form>
<?php else: ?>
<form action="" method="post">
    <div class="profile-items">
        <div class="main-ttl">
            <a href="/provider/listings/types/<?= $this->listing->id ?>" class="link-4">Activity Types</a>
            <p><strong>New Activity Type</strong></p>        	
        </div><!-- closes main-ttl -->
        <div class="item-wrppr">
            <div class="item-ttl">
                Basic Information
            </div><!-- closes item ttl -->
            <div class="item first">
                <input tabindex="1" class="noclean" placeholder="Enter the name here" name="name" type="text" value="" />
                <h4>Activity Type Name</h4>
                <span>Write the name for this activity type</span>
                <div class="help">
                    <a href="/images2/help/big-act-types-name.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-name.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-name.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="item last">
                <textarea tabindex="2" placeholder="Write a short description here" name="description" cols="30" rows="1"></textarea>
                <h4>Description</h4>
                <span>Write the description for this activity type</span>
                <div class="help">
                    <a href="/images2/help/big-act-types-description.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-description.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-description.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="clear"></div>									
        </div><!-- closes item-wrppr -->
        <div class="item-wrppr">
            <div class="item-ttl">
                Capacity
            </div><!-- closes item ttl -->
            <div class="item first">
                <div class="selects">
                    <select tabindex="3" name="min">
                        <option value="1">1 person</option>
                    	<?php for($i=2;$i<=50;$i++): ?>
                        <option value="<?= $i ?>"><?= $i ?> people</option>
                        <?php endfor ?>
                    </select>
                </div><!-- closes selects -->
                <h4>Minimum Capacity</h4>
                <span>Select the Minimum people</span>
                <div class="help">
                    <a href="/images2/help/big-act-types-capacity.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-capacity.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-capacity.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="item last">
                <div class="selects">
                    <select tabindex="4" name="max">
                        <option value="1">1 person</option>
                    	<?php for($i=2;$i<=50;$i++): ?>
                        <option value="<?= $i ?>"><?= $i ?> people</option>
                        <?php endfor ?>
                    </select>
                </div><!-- closes selects -->
                <h4>Maximum Capacity</h4>
                <span>Select the maximum people</span>
            </div><!-- closes item -->
            <div class="clear"></div>									
        </div><!-- closes item-wrppr -->
        <div class="item-wrppr">
            <div class="item-ttl">
                Children Options
            </div><!-- closes item ttl -->
            <div class="item first">
                <input tabindex="5" type="checkbox" name="kids" value="1" />
                <label>This activity type accepts children</label>
                <div class="help">
                    <a href="/images2/help/big-act-types-children.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-children.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-children.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="accept-kids hidden">
                <div class="item last">
                    <div class="selects">
                        <select tabindex="6" disabled="disabled" name="kid_age_max">
                        	<?php for($i=1;$i<=12;$i++): ?>
                            <option value="<?= $i ?>">Under <?= $i ?> years</option>
                            <?php endfor ?>
                        </select>
                    </div><!-- closes selects -->
                    <h4>Child Age</h4>
                    <span>What age do you consider as a child?</span>
                </div><!-- closes item -->
            </div><!-- accept-kids -->
            <div class="clear"></div>
        </div><!-- closes item-wrppr -->
         <div class="lstng-details">
            <div class="lstng-detail faq">
                <strong>Activity Type Requeriments</strong>
                <span>Write the requeriments for this activity type</span>
                <br />
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="8" placeholder="Enter the requirement text here" type="text" name="tip[0][text]" value="" />
                    <div class="clear"></div>
                </div>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="9" placeholder="Enter the requirement text here" type="text" name="tip[1][text]" value="" />
                    <div class="clear"></div>
                </div>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="10" placeholder="Enter the requirement text here" type="text" name="tip[2][text]" value="" />
                    <div class="clear"></div>
                </div>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="11" placeholder="Enter the requirement text here" type="text" name="tip[3][text]" value="" />
                    <div class="clear"></div>
                </div>
                <div class="itemm">
                    <a href="" class="remove">remove</a>
                    <input tabindex="12" placeholder="Enter the requirement text here" type="text" name="tip[4][text]" value="" />
                    <div class="clear"></div>
                </div> 
                <div class="itemm newitem hidden">
                    <a href="" class="remove">remove</a>
                    <input tabindex="13" placeholder="Enter the requirement text here" type="text" name="text" value="" />
                    <div class="clear"></div>
                </div>
                <a href="" id="addNewTip" class="link-5">Add another requirement</a>
                <div class="clear"></div>
                <div class="help">
                    <a href="/images2/help/big-act-types-requeriments.png" class="eye">help</a>
                    <a href="/images2/help/big-act-types-requeriments.png" class="tooltip3">
                    <img src="/images2/help/small-act-types-requeriments.png" /></a>
                </div>
            </div><!-- closes lstng-detail -->
         </div><!-- closes lstng-details -->
    </div><!-- closes profile-items -->
    <div class="foot">
        <input type="submit" class="noclean btn-1" value="Save Changes" />
    </div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'add-type') ?>" />
    <input type="hidden" name="_task" value="<?= md5('add_type') ?>" />
</form>
<?php endif ?>
<?php endif ?>