<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->trip->title ?>, <?= $this->trip->country ?> | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
	<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
	<link type="text/css" rel="stylesheet" href="/css2/jquery-ui-1.8.16.custom.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js2/jquery.cycle.all.js"></script>
    <script type="text/javascript" src="/js2/jquery.input.value.js"></script>
    <script type="text/javascript" src="/js2/jquery.jcarousel.min.js"></script>
    <script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
    <script type="text/javascript" src="/js2/common.js"></script>
    <script type="text/javascript" src="/js2/trips/view.js"></script>
    <style type="text/css">
	.desc-wrapper #pager a { width:<?= (100 / count($this->images)) . '%'; ?>;} .hidden { display:none;}
	.datepicker a.ui-state-active { background-color: #60B5F7; color: #FFFFFF;}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>    
    <div class="w2">
        <div class="wrapper box">
            <div class="desc-wrapper">
                <ul class="trip-gallery">
                	<?php foreach($this->images as $image): ?>
                    <li>
                        <?= $this->thumbnail(array('width'=>960,'height'=>389), $image, '','960:389'); ?>
                    </li>
                    <?php endforeach ?>
                </ul>
                <div class="time-stamp">
                    <span><?= $this->trip->days ?><?= ($this->trip->days > 1) ? ' Days' : ' Days'; ?> Trip</span>
                </div><!-- closes time-stamp -->
                <div id="pager"></div>
                <div class="trip-description">
                    <div class="left">
                        <img src="/images2/img-4.png" alt="" />
                    </div><!-- closes left -->
                    <div class="right">
                        <div class="top">
                            <span><?= $this->trip->price ?> <em>/ per person</em></span>
                            <h1><?= $this->trip->title ?></h1>
                            <strong><?= $this->trip->country ?></strong>
                        </div><!-- closes top -->
                        <div class="bottom">
                            <p><?= $this->trip->description ?></p>
	                        <a href="#dates_lb" class="lb btn-2">Buy Trip</a>
                        </div><!-- closes bottom -->
                    </div><!-- closes right -->
                </div><!-- closes description -->
            </div><!-- closes desc-wrapper -->					
        </div><!-- closes wrapper -->
        
        <div class="tabs-wrapper wrapper">
            <ul>
                <li><a href="#tabs-1">Overview</a></li>
                <li><a href="#tabs-2">Itinerary</a></li>
            </ul>
            <div id="tabs-1" class="tab">
                <div class="section">
                    <h3>Hightlights</h3>
                    <div class="hl">
                        <h4>Things you'll love</h4>
                        <ul>
                            <li>6 luncheons</li>
                            <li>Wine tasting dinner at Astrid y Gaston in Santiago</li>
                            <li>Dinner at Veta Bistro with former French Laundry chef Roberto Leira</li>
                            <li>Dinner at Mallman 1884 in Mendoza</li>
                            <li>Tango Show with VIP seating in Buenos Aires</li>
                        </ul>
                    </div><!-- closes hl -->
                    <div class="hl">
                        <h4>Things you'll learn</h4>
                        <ul>
                            <li>Santa Cruz Museum Entrance</li>
                            <li>Gratuities for porters in airports and hotels</li>
                            <li>Bottled mineral waters on buses</li>
                            <li>All ground transportation in clean air conditioned and comfortable vehicle</li>
                            <li>Professional bilingual guide</li>
                        </ul>
                    </div><!-- closes hl -->
                    <div class="hl last">
                        <h4>Things need to know</h4>
                        <ul>
                            <li>Two nights lodging in Santiago with breakfast</li>
                            <li>Three nights lodging in Santa Cruz with breakfast</li>
                            <li>Three nights lodging in Mendoza with breakfast</li>
                            <li>Two nights lodging in Buenos Aires with breakfast</li>
                            <li>15 winery visits with tastings</li>
                        </ul>
                    </div><!-- closes hl -->
                </div><!-- closes section -->
                
                <div class="section">
                    <h3>Things to Do</h3>
                    <?php $used = array(); ?>
                    <?php foreach($this->listings as $listing): ?>
                    <?php if($listing->main_type != 2 && $listing->main_type != 5): ?>
                    <?php if(!in_array($listing->id, $used)): ?>
                    <?php $used[] = $listing->id ?>
                    <div class="item">
                    	<?php $class = ($dr = !$dr) ? 'left' : 'right' ?>
                    	<?= $this->thumbnail(array('width'=>316,'height'=>209), $listing->image, $class, '316:209') ?>
                        <h4><?= $listing->title ?></h4>
                        <p><?= $listing->description ?></p>
                    </div><!-- closes item -->
                    <?php endif ?>
                    <?php endif ?>
                    <?php endforeach ?>
                </div><!-- closes section -->
                <div class="section">
                    <h3>Dining</h3>
                    <?php $used = array(); ?>
                    <?php foreach($this->listings as $listing): ?>
                    <?php if($listing->main_type == 2): ?>
                    <?php if(!in_array($listing->id, $used)): ?>
                    <?php $used[] = $listing->id ?>
                    <div class="item">
                    	<?php $class = ($dr = !$dr) ? 'left' : 'right' ?>
                    	<?= $this->thumbnail(array('width'=>316,'height'=>209), $listing->image, $class, '316:209') ?>
                        <h4><?= $listing->title ?></h4>
                        <p><?= $listing->description ?></p>
                    </div><!-- closes item -->
                    <?php endif ?>
                    <?php endif ?>
                    <?php endforeach ?>
                </div><!-- closes section -->
                <div class="section">
                    <h3>Stay</h3>
                    <?php $used = array(); ?>
                    <?php foreach($this->listings as $listing): ?>
                    <?php if($listing->main_type == 5): ?>
                    <?php if(!in_array($listing->id, $used)): ?>
                    <?php $used[] = $listing->id ?>
                    <div class="item">
                    	<?php $class = ($dr = !$dr) ? 'left' : 'right' ?>
                    	<?= $this->thumbnail(array('width'=>316,'height'=>209), $listing->image, $class, '316:209') ?>
                        <h4><?= $listing->title ?></h4>
                        <p><?= $listing->description ?></p>
                    </div><!-- closes item -->
                    <?php endif ?>
                    <?php endif ?>
                    <?php endforeach ?>
                </div><!-- closes section -->
                
                <div class="section details"> 
                    <h3>Details</h3>
                    <div class="hl">
                        <h4>Includes</h4>
                        <ul>
                            <li>6 luncheons</li>
                            <li>Wine tasting dinner at Astrid y Gaston in Santiago</li>
                            <li>Dinner at Veta Bistro with former French Laundry chef Roberto Leira</li>
                            <li>Dinner at Mallman 1884 in Mendoza</li>
                            <li>Tango Show with VIP seating in Buenos Aires</li>
                        </ul>
                    </div>
                    <!-- closes hl -->
                    <div class="hl">
                        <h4>Not includes</h4>
                        <ul>
                            <li>Santa Cruz Museum Entrance</li>
                            <li>Gratuities for porters in airports and hotels</li>
                            <li>Bottled mineral waters on buses</li>
                            <li>All ground transportation in clean air conditioned and comfortable vehicle</li>
                            <li>Professional bilingual guide</li>
                        </ul>
                    </div>
                    <!-- closes hl -->
                    <div class="hl last">
                        <h4>Trip Tips</h4>
                        <ul>
                            <li>Two nights lodging in Santiago with breakfast</li>
                            <li>Three nights lodging in Santa Cruz with breakfast</li>
                            <li>Three nights lodging in Mendoza with breakfast</li>
                            <li>Two nights lodging in Buenos Aires with breakfast</li>
                            <li>15 winery visits with tastings</li>
                        </ul>
                    </div>
                    <!-- closes hl -->
                </div>
                <!-- closes section -->
                <div class="info-bottom">
                    <a href="" class="btn-2">Buy trip</a>
                    Questions about this trip?
                    <a href="">Contact us!</a>
                </div>
                <!-- closes info-bottom -->
            </div>
            <!-- closes tab -->
            <div id="tabs-2" class="tab">
                <ul class="days">
                	<?php for($i=1;$i<=count($this->listingsbyday);$i++): ?>
                    <li>
                        <div class="section title">Day <?= $i ?></div>
                        <?php foreach($this->listingsbyday[$i] as $time => $listings): ?>
                        <div class="section">
                            <div class="left"><?= $time ?></div>
                            <?php foreach($listings as $listing): ?>
                            <div class="right">
                                <?= $this->thumbnail(array('width'=>176,'height'=>117), $listing->image, '','176:117'); ?>
                                <div class="text">
                                    <span><?= $listing->city ?></span>
                                    <strong><?= date('g:i A', strtotime($listing->start)) ?> - <?= date('g:i A', strtotime($listing->end)) ?></strong>
                                    <strong><?= $listing->title ?></strong>
                                    <ul>
                                        <li>Vivamus luctus tellus tristique purus iaculis non ornare erat ultrices. Morbi eros quam, imperdiet nec laoreet eget.</li>
                                        <li>Aliquam non mi sapien, pharetra viverra orci.</li>
                                        <li>Vivamus luctus tellus tristique purus iaculis non ornare erat ultrices. Morbi eros quam, imperdiet nec laoreet eget, condimentum id sapien. Aliquam non mi sapien, pharetra viverra orci.</li>
                                    </ul>
                                </div><!-- closes text -->
                            </div><!-- closes right -->
                            <?php endforeach ?>
                        </div><!-- closes section -->
                        <?php endforeach ?>
                    </li>
                    <?php endfor ?>
                </ul>
                <div class="info-bottom"></div><!-- closes info-bottom -->
            </div><!-- closes tab -->
        </div><!-- closes tabs-wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->	
<div class="hidden">
	<div id="dates_lb">
    	<div class="lb-dates">
			<div class="left">
				<h2>First, select the dates you want to go on your vacation.</h2>
				<ul>
					<li>Your trip is going to be <?= $this->trip->days ?> days long.</li>
					<li>This trip is available for children.</li>
					<li>Maximum occupation is <?= $this->trip->max ?> people.</li>
                    <?php if($this->trip->min > 1): ?>
                    <li>Minimum occupation is <?= $this->trip->min ?> people.</li>
                    <?php else: ?>
					<li>No minimum  required.</li>
                    <?php endif ?>
                    <li><em>The price listed is an estimation, you will get a final price depending on your dates and ocupation requirements</em></li>
				</ul>
			</div><!-- closes left -->
			<div class="right">
				<div id="datepicker" class="datepicker"></div>
                <form action="/trips/checkprice/<?= $this->trip->id ?>" method="post">
                    <div class="occ">
                        <label>Adults</label>
                        <select name="adults">
                        	<option value="0">None</option>
						<?php for($i=$this->trip->min; $i<=$this->trip->max; $i++): ?>
                            <?php if($i==$this->trip->min): ?>
                            <option value="<?= $i ?>">min <?= $i ?></option>
                            <?php elseif($i==$this->trip->max): ?>
                            <option value="<?= $i ?>">max <?= $i ?></option>
                            <?php else: ?>
                            <option value="<?= $i ?>"><?= $i ?></option>
                            <?php endif ?>
                        <?php endfor ?>
                        </select>
                        <label>Children</label>
                        <select name="kids">
                        	<option value="0">None</option>
                        <?php for($i=$this->trip->min; $i<=$this->trip->max; $i++): ?>
                            <?php if($i==$this->trip->min): ?>
                            <option value="<?= $i ?>">min <?= $i ?></option>
                            <?php elseif($i==$this->trip->max): ?>
                            <option value="<?= $i ?>">max <?= $i ?></option>
                            <?php else: ?>
                            <option value="<?= $i ?>"><?= $i ?></option>
                            <?php endif ?>
                        <?php endfor ?>
                        </select>
                    </div><!-- closes occ -->
                    <div class="occ">
                        <input type="submit" class="btn-1" value="Check Availability" />
                        <span onclick="$.fancybox.close()" class="btn-4">Cancel</span>
                    </div><!-- closes occ -->
                    <input type="hidden" name="date" value="" />
                    <input type="hidden" name="ids" value="<?= $this->trip->id ?>" />
                    <input type="hidden" name="token" value="<?= $this->trip->token ?>" />
                </form>
			</div><!-- closes right -->
		</div><!-- closes dates -->
    </div>
</div>
</body>
</html>