<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Cancellation Policies | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
    <script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#header .header-login a.user').click(function(){
                $(this).next().toggleClass('show');
                return false;
            });
            $('.tabs').tabs();
        });
    </script>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper cw">
            <h2>Cancellation Policies for Hotels</h2>
            <div class="cancellation">						
                <div class="intro">
                    <p>Tripfab allows hosts to choose among three standardized cancellation policies (Low, Medium, and High Restrictions) that we will enforce to protect both guest and host alike. T Each listing and reservation on our site will clearly state the cancellation policy. Guests may cancel and review any penalties by viewing their travel plans and then clicking 'Cancel' on the appropriate reservation.</p>
                </div><!-- closes intro -->
                <div class="tabs">
                    <ul>
                        <li><a href="#tabs-1">Low Restictions</a></li>
                        <li><a href="#tabs-2">Medium Restrictions</a></li>
                        <li><a href="#tabs-3">High Restrictions</a></li>
                    </ul>
                    <div id="tabs-1" class="tab">
                        <h3>Full refund 1 day prior to arrival, except fees</h3>
                        <ul>
                            <li>Cleaning fees are always refunded if the guest did not check in.
                            <li>The Tripfab service fee is refundable.</li>
                            <li>If there is a complaint from either party, notice must be given to Tripfab Resolution 
                            Center within 24 hours of check-in.</li>
                            <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                            <li>A reservation is not officially canceled until the guest receives a cancellation 
                            confirmation e-mail from Tripfab Resolution Center.</li>
                        </ul>
                        <div class="inner">
                            <div class="top">
                                <img src="/images2/img-65-hotel.png" alt="" />
                            </div><!-- closes top -->
                            <div class="bottom">
                                <div>
                                   Must be made a full 24 hours prior to listing's local check in time (or 2:00 PM if not specified) on the day of check in. For example, if check-in is on Friday, cancel by Thursday of that week before check in time.
                                </div>
                                <div>
                                    If the guest cancels less than 24 hours before check-in, the first night is non-refundable.
                                </div>
                                <div>
                                    If the guest arrives and decides to leave early, the nights not spent 24 hours after the official cancellation are 100% refunded.
                                </div>
                            </div><!-- closes bottom -->
                        </div><!-- closes inner -->
                    </div><!-- closes tab -->
                    <div id="tabs-2" class="tab">
                        <h3>Full refund 3 days prior to arrival, except fees</h3>
                        <ul>
                            <li>Cleaning fees are always refunded if the guest did not check in.</li>
                            <li>The Tripfab service fee is refundable.</li>
                            <li>If there is a complaint from either party, notice must be given to Tripfab Resolution Center within 
                            24 hours of check-in.</li>
                            <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                            <li>A reservation is not officially canceled until the guest receives a cancellation 
                            confirmation e-mail from Tripfab Resolution Center.</li>
                        </ul>
                        <div class="inner">
                            <div class="top">
                                <img src="/images2/img-66-hotel.png" alt="" />
                            </div><!-- closes top -->
                            <div class="bottom">
                                <div>
                                   Must be made three full days prior to listing's local check in time (or 2:00 PM if not specified) on the day of check in. For example, if check-in is on Friday, cancel by the previous Tuesday before check in time.
                                </div>
                                <div>
                                    If the guest cancels less than 3 days in advance, the first night is non-refundable but the remaining nights will be 50% refunded.
                                </div>
                                <div>
                                   If the guest arrives and decides to leave early, the nights not spent 24 hours after the cancellation occurs are 50% refunded.
                                </div>
                            </div><!-- closes bottom -->
                        </div><!-- closes inner -->
                    </div><!-- closes tab -->
                    <div id="tabs-3" class="tab">
                        <h3>50% refund up until 1 week prior to arrival, except fees</h3>
                        <ul>
                            <li>Cleaning fees are always refunded if the guest did not check in.</li>
                            <li>The Tripfab service fee is non-refundable.</li>
                            <li>If there is a complaint from either party, notice must be given to Tripfab Resolution 
                            Center within 24 hours of check-in.</li>
                            <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                            <li>A reservation is not officially canceled until the guest receives a cancellation confirmation e-mail 
                            from Tripfab Resolution Center.</li>
                        </ul>
                        <div class="inner">
                            <div class="top">
                                <img src="/images2/img-67-hotel.png" alt="" />
                            </div><!-- closes top -->
                            <div class="bottom">
                                <div>
                                    Must be made seven full days prior to listing's local check in time (or 2:00 PM if not specified) on the day of check in, otherwise no refund. For example, if check-in is on Friday, cancel by Friday of the previous 
                                </div>
                                <div>
                                    If the guest cancels less than 7 days in advance, the nights not spent are not refunded.
                                </div>
                                <div>
                                    If the guest arrives and decides to leave early, the nights not spent are not refunded.
                                </div>
                            </div><!-- closes bottom -->
                        </div><!-- closes inner -->
                    </div><!-- closes tab -->
                </div><!-- closes tabs -->
            </div><!-- closes cancellation -->
        </div><!-- closes wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
</body>
</html>