<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
	<title>vendor messages</title>
		<link type="text/css" rel="stylesheet" href="css5/reset.css" />
		<link type="text/css" rel="stylesheet" href="css5/all.css" />
		<link type="text/css" rel="stylesheet" href="html/jqtransform/jqtransform.css" />
	</head>

	<body>
		<div class="w1">
			<div id="header">
				<div class="wrapper">
					<h1 class="logo_icon"><a href="">Tripfab</a></h1>
					<ul class="menu_admin">
						<li><a href="" class="active">Listings<img alt="" src="../images/cleardot.gif"></a>
							<ul>

								<li><a href="">All Listings</a></li>
								<li><a href="">Restaurants</a></li>
								<li><a href="">Entertainment</a></li>
								<li><a href="">Tourist Sights</a></li>
							</ul>
						</li>
						<li class="single"><a href="">Trips</a></li>

						<li><a href="">Places<img alt="" src="../images/cleardot.gif"></a></li>
						<li><a href="">Users<img alt="" src="../images/cleardot.gif"></a></li>
						<li><a href="">Payments<img alt="" src="../images/cleardot.gif"></a></li>
						<li class="single"><a href="">Reservations</a></li>
						<li class="single"><a href="" class="reports">Reports</a></li>
					</ul>

					<a href="" class="sign_log">Logout</a>
				</div>
				<!-- closes wrapper -->			
			</div>
			<!-- closes header -->
			
			<div class="w3_admin">
				<div class="sub_menu">
					<h2>Create. <span>New Trip.</span></h2>

					<a href="#" class="back">Back to Trips</a>
				</div><!--SUB_MENU-->
            </div><!--W3-->
				
				<div id="trips" class="listing-wrapper wrapper">
					<div class="listing-content">
						<div class="left">
							<ul>
								<li><a href="">General Information</a></li>

								<li><a href="">Trip Facts</a></li>
								<li><a href="">Photos</a></li>
								<li><a href="">Trip Details</a></li>
								<li class="current"><a href="">Itinerary</a></li>
							</ul>
						</div>
						<!-- closes left -->

						<div class="right">
							<div class="lstng-details">
								<h3 class="title">Edit Itinerary</h3>
								<div class="block">
									<div class="item-ttl">Schedule</div>
									<div class="item">
										<p class="descrip name">
											<strong>Listing Name</strong>

											Write the name of the listing
										</p>
										<input type="text" name="" value="Monkey Quest" class="name-in" />
									</div><!---ITEM-->
									
									<div class="item">
										<p class="descrip">
											<strong>Listing Type</strong>
											Select the type of listing 
										</p>

										<select>
											<option>Activity</option>
										</select>
									</div><!---ITEM-->
									
									<div class="item">
										<p class="descrip">
											<strong>Itinerary Day</strong>
											Select the day of the activity 
										</p>

										<select>
											<option>Day 2</option>
										</select>
									</div><!---ITEM-->
									
									<div class="item">
										<p class="descrip">
											<strong>Duration</strong>
											Select how many days long
										</p>

										<select>
											<option>Concludes Same Day</option>
										</select>
									</div><!---ITEM-->
									
									<div class="item">
										<p class="descrip">
											<strong>Starting Hour</strong>
											Select the hour activity starts
										</p>

										<select class="time">
											<option>AM</option>
										</select>
										<select class="hour">
											<option>08:00</option>
										</select>
									</div><!---ITEM-->
									
									<div class="item">

										<p class="descrip">
											<strong>Ending Hour</strong>
											Select the hour activity ends
										</p>
										<select class="time">
											<option>AM</option>
										</select>
										<select class="hour">

											<option>10:00</option>
										</select>
									</div><!---ITEM-->
									
									<div class="item last">
										<p class="descrip"><input type="checkbox" value="" />Show this activity in the main page of the trip</p>
										
									</div><!---ITEM-->
									
								</div><!--BLOCK-->
								
								<div class="block">

									<h3 class="item-ttl">Description</h3>
									<div class="item">
										<div class="description_l">
											<textarea rows="" cols=""></textarea>
										</div>
									</div><!--ITEM-->
								</div><!--BLOCK-->
								
								<div class="block">

									<h3 class="item-ttl">Picture</h3>
									<div class="item">
										<table width="470" border="0">
											<tr>
												
												<td width="270">
													<h4>Picture Requeriments</h4>
													<dl class="photo-limit">
														<dt>Upload limit</dt>

														<dd>10 photos per listing</dd>
														<dt>Photo Dimention</dt>
														<dd>640x425 pixels</dd>
														<dt>File size</dt>
														<dd>2MB or less</dd>
													</dl>

												</td>
												<td width="180" class="picture">
													<img src="images2/img-31.png" width="68" height="68" alt="" />
													<input type="file" />
												</td>
											</tr>
										</table>
									</div><!--ITEM-->
								</div><!--BLOCK-->

								<div class="block">
									<div class="single last">
										<p class="item-ttl">Map</p>
										<input type="button" class="btn-10" value="Set Location" />
										<input type="text" class="location" value="" />
										<div class="map">
											<div class="map_holder">
												<img src="images2/map-result.gif" width="500" height="265" alt="" />

											</div>
										</div><!--MAP-->
									</div><!--single-->
								</div><!--BLOCK-->
								
								
							</div>
							<!-- closes lstng-details -->
							<div class="foot">
								<input type="submit" class="btn-1" value="Save Changes" />
							</div>

							<!-- closes foot -->
						</div>
						<!-- closes right -->
					</div>
					<!-- closes listing-content -->
				</div>
					
			<div class="footer black">
				<div class="wrapper">
					<a href="" class="logo">Tripfab</a>

				</div><!--WRAPPER-->
			</div>
			<!-- closes footer -->
		</div>
		<!-- closes w1 -->
	</body>
</html>