<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
	<title>vendor messages</title>
        <link type="text/css" rel="stylesheet" href="/css5/reset.css" />
        <link type="text/css" rel="stylesheet" href="/css5/all.css" />
		<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
  		<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />
  		<!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
  		<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
  		<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
    	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
		<script type="text/javascript" src="/js2/jquery.js"></script>
    	<script type="text/javascript" src="/js2/admin/place-edit.js"></script>
		<style type="text/css">
        #mapcanvas { width:500px; height:300px; margin-top:10px; margin-bottom:10px;}
        </style>
		<script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.js"></script>
		<script>
        $(document).ready(function() {
            $('a.lbc').fancybox({
                padding: 0,
                overlayColor: '#FFF',
                overlayOpacity: '0.7',
                showCloseButton: 'false',
            });
            $("#report_tabs").tabs();
        });
		</script>
	</head>
	<body>
		<div class="w1">
    	<?php echo $this->partial('admin_partials/header.phtml', array()); ?>
						
			<div class="w3_admin">
				<div class="sub_menu">
					<?php if($this->titleMessage ):?>
                     	<h2><?php echo $this->titleMessage?></h2>
                    <?php else: ?>
                    	<h2>Edit. <span><?php echo $this->place->title?></span></h2>
                     <?php endif;?> 
					<a href="/admin/places/cities" class="back">Back to Cities</a>
				</div><!--SUB_MENU-->
            </div><!--W3-->
			<div class="all_listing">
				<div class="create_city">
				<?php if($this->successMessage): ?>
				<script type="text/javascript">
					showAlert("Your changes have been saved");
                </script>
                <?php endif ?>	

                <?php if(count($this->errors)) : ?>
                <center>
                <div style="border:1px solid red; margin-left:22px; margin-right:22px; margin-bottom:10px;">
                	<?php foreach($this->errors as $error):?>
                    	<p><?php echo $error;?></p>
                    <?php endforeach;?>
                </div>
                </center>
                <?php endif;?>
					<form method="post" name="f1" id="f1">
					<div class="block">
						<div class="sub_titl">Basic Information</div><!--SUB_TITL-->
						<div class="cont">
							<div class="single">
								<select name="country">
                                	<?php foreach($this->countries as $c): ?>
                                    <?php $selected = ($c->id == $this->place->parent_id) ? 'selected="selected"' : ''; ?>
                                    <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                                    <?php endforeach ?>
								</select>
								<p class="descrip"><strong>Country</strong> Select country</p>
							</div><!--single-->
							<div class="single">
								<input type="text" value="<?php echo $this->place->title?>" name="title" />
								<p class="descrip"><strong>Name</strong></p>
							</div><!--single-->
							<div class="single">
								<input type="text" value="<?php echo $this->place->identifier?>" name="identifier" />
								<p class="descrip"><strong>Identifier</strong></p>
							</div><!--single-->
							<div class="single last">
								<textarea cols="" rows="" name="description"><?php echo $this->place->description?></textarea>
								<p class="descrip"><strong>Short Description</strong> Write a nice description for the city
							(200 characters max)</p>
							</div><!--single-->
						</div><!--CONT-->
					</div><!--BLOCK-->
					
					<div class="block">
						<div class="sub_titl">Location</div><!--SUB_TITL-->
						<div class="cont">
							<div class="single last">
								<p class="descrip"><strong>Map</strong>Set the location of the city in the map</p>
								<input type="button" class="btn-10" value="Set Location"  id="setLocation" /><input type="text" class="location" value="" name="address" />
								<div class="map">
                                    <div class="w-m">
                                        <h5>Location Results</h5>
                                        <ul id="maplocations">
                                        </ul>
                                    </div>
                                    <!-- closes w-m -->
                                    <div id="mapcanvas"></div>
                                    <input type="hidden" name="lat" value="<? echo $this->place->lat?>" />
                                    <input type="hidden" name="lng" value="<? echo $this->place->lng ?>" />                
								</div><!--MAP-->
							</div><!--single-->
						</div><!--CONT-->
					</div><!--BLOCK-->
					
					<div class="block">
						<div class="sub_titl">Landscapes</div><!--SUB_TITL-->
						<div class="cont">
							<div class="single last">
								<p class="descrip"><strong>Landscape</strong> Select Landscapes</p>
                                <div class="landscapes">
								<table><tr>
                                <?php foreach($this->landscapes as $key => $landscape):?>
                                	<?php $checked = (in_array($landscape->id, $this->p_lands)) ? 'checked="checked"' : ''; ?>
									<td width="180" height="24"><input <?php echo $checked ?> type="checkbox" value="<?php echo $landscape->id?>" name="landscapes[]" /><?php echo $landscape->name?></td>	
									<?php if(($key+1) % 3 == 0):?>
                                    	</tr><tr>
                                    <?php endif; ?>
                                <?php endforeach;?>
                                </tr></table>
                                
								</div><!--LANDSCAPES-->
							</div><!--SINGLE-->
						</div><!--CONT-->
					</div><!--BLOCK-->
					<div class="block last">
						<a href="" class="delete">Delete this Listing</a>
						<a href="javascript://" class="btn-1" onclick="f1.submit();">Save Changes</a>
					</div><!--BLOCK-->
				</form>	
				</div><!--CREATE-CITY-->
				
			</div><!--ALL_LISTING-->
					
			<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
			<!-- closes footer -->
		</div>
		<!-- closes w1 -->
		<?php echo $this->partial('admin_partials/report.phtml', array()); ?>
	</body>
</html>