<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> : Photos | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css2/lightboxes.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
	<script type="text/javascript" src="/js2/jquery.js"></script>
	<script type="text/javascript" src="/js2/admin/listing-actions.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
			$('a.lb').fancybox({
				padding:0,
				overlayColor:'#fff',
				centerOnScroll:1,
				overlayOpacity:0.7,
				showCloseButton:0,
			});
			$('.lbox .btn-2, .lbox .btn-11').click(function(){
				$(this).parents('form').submit();
			});
			
			var uploader = new qq.FileUploader({
                element: document.getElementById('file_upload3'),
                action: '/phpscripts/uploadListingPhotos.php',
				multiple:true,
				fileTemplate: '<li>' +
								  '<span class="qq-upload-file"></span>' +
								  '<span class="qq-upload-progress"><span class="qq-upload-progress-range"></span></span>' +
								  '<span class="qq-upload-size"></span>' +
								  '<span class="qq-upload-spinner"></span>' +
								  '<a class="qq-upload-cancel" href="#">Cancel</a>' +
								  '<span class="qq-upload-failed-text">Failed</span>' +
							  '</li>',    
				params:{
					'userids':<?= $this->user->id ?>,
					'vendorid':<?= $this->vendor->id ?>,
					'listings':<?= $this->listing->id ?>,
					'listtoken':'<?= $this->listing->token ?>',
					'formtoken':'<?= $this->user->token ?>',
					'usertoken':'<?= md5($this->user->token.'upload_listing_pictures') ?>'					
				},
				allowedExtensions:['jpg', 'jpeg', 'png', 'gif'],
				sizeLimit:2097152,
				listElement:document.getElementById('qqPhotoQueueUL'),
				onProgress: function(id, fileName, loaded, total){
					var _w = loaded * 100 / total; _w = _w + "%";
					$('#qqPhotoQueueUL li:eq('+id+') .qq-upload-progress-range').css({
						width:_w
					});
				},
				showMessage:function(err) {
					showError(err);
				}
            }); 
			
			$('.uploadTrigger').click(function(){
				$('#file_upload3 input').click();
				return false;
			});
			$('a.deny').click(function(){
				showError('You have upload 10 images already');
				return false;
			});
        });
    </script>
    <style type="text/css">
	.hidden { display:none; }
	.photo.empty object { float:none;}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('admin_partials/header.phtml', array()); ?>
    <div class="w3_admin">
        <div class="sub_menu">
            <h2>
            	<?php if($this->listing->status == 1): ?>
            	<span class="lstngActv">Active</span>
                <?php else: ?>
            	<span class="lstngInct">Inactive</span>
                <?php endif ?>
            	Editing. <span><?php echo $this->listing->title ?></span>
            <em class="ed">by </em> <a href="/admin/users/view/partner/<?= $this->vendor->id ?>" class="partner"><?= $this->vendor->name ?></a></h2>
            <?= $this->partial('admin_partials/listing_actions.phtml', array('active'=> $this->listing)); ?>
        </div><!--SUB_MENU-->
    </div><!--W3-->
    <div class="w2">
        <div class="listing-wrapper wrapper">
            <div class="listing-content show">
                <div class="left">
                    <?= $this->partial('admin_partials/vendorlistingsmenu.phtml', array('active'=>'Photos', 'id' => $this->listing->id, 
									   'type'=>$this->listing->main_type)) ?>
                </div><!-- closes left -->                
                <div class="right">
					<?= $this->partial('admin_listing/common/photos.phtml', array(
							'pictures' => $this->pictures,
							'listing'  => $this->listing,
							'help' => $this->help,
					)) ?>
                </div><!-- closes right -->
                <div class="clear"></div>
            </div><!-- closes listing-content -->
        </div><!-- closes listing-wrapper -->
    </div><!-- closes w2 -->
	<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
</div><!-- closes w1 -->
<div class="hidden">
	<?php foreach($this->pictures as $img): ?>
    <div id="img_delete_<?= $img->id ?>" class="lb-forgot">
        <form action="" method="post" id="form_picture_delete_<?= $img->id ?>">
            <div class="ttl">Delete Picture</div>
            <div class="content">
                <p>Are you sure you want to delete this picture?</p>
            </div><!-- closes content -->
            <div class="bottom">
                <input type="submit" class="btn-1 noclean" value="Delete" />
                <span class="btn-4" onclick="$.fancybox.close()">Cancel</span>				
            </div><!-- closes bottom -->
            <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
            <input type="hidden" name="img_id" value="<?= $img->id ?>" />
            <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
            <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'form_picture_delete_'.$img->id) ?>" />
            <input type="hidden" name="_task" value="<?= md5('delete_picture') ?>" />
        </form>
    </div><!-- closes lb-forgot -->
    <?php endforeach ?>
</div>
<?php echo $this->partial('admin_partials/listing_actions_lbs.phtml', array('listing'=>$this->listing, 'main_category' => $this->main_category)) ?>
</body>
</html>