<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
	<meta content="noindex,nofollow" name="robots" />
	<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> - Admin | Tripfab.com</title>
	<link type="text/css" rel="stylesheet" href="/css6/reset.css" />
	<link type="text/css" rel="stylesheet" href="/css6/common.css" />
	<link type="text/css" rel="stylesheet" href="/css6/section1.css" />
	<link type="text/css" rel="stylesheet" href="/css6/calendar.css" />	
	<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
</head>
<body class="bg_hl">
<div id="wp_all">
    <div id="wp_header">
        <?= $this->partial('partials/header-v2.phtml', array('user'=>$this->user,'full'=>true)); ?>
        <div class="sub_header" id="lstng_header">
        	<div class="cntrl">
        	    <ul class="breadcrump">
        	        <li class="first"><a href="/" class="home"></a></li>
        	        <li><a href="/<?= $this->country->identifier ?>"><?= $this->country->title ?></a></li>
        	        <li><a href="/<?= $this->country->identifier ?>/<?= $this->city->identifier ?>"><?= $this->city->title ?></a></li>
        	        <li class="last"><a href="/<?= $this->country->identifier ?>/<?= $this->city->identifier ?>/#/hotels" class="active">Hotels</a></li>
        	    </ul>
        	    <a href="/costa_rica/alajuela/#/hotels" 
        	    class="link1">&larr; Back to Results</a>
        	    <div class="clear"></div>
        	</div><!--CNTRL-->
            <div class="cont">
                <?= $this->partial('admin_partials/headerVendorInfo.phtml', array('vendor'=>$this->vendor, 'user'=> $this->user)) ?>
            </div><!--CONT-->
        </div><!--SUB_HEADER-->
    </div><!--WP_HEADER-->
    <div id="wp_content">
        <div id="cont_bl">
            <div id="lstng_htl">
                <div class="img_bg">
                	<?php if(strpos($this->listing->image, 'ico-') === false): ?>
                    <div class="photo"><?= $this->blur($this->listing->image) ?></div><!--PHOTO-->
                    <?php else: ?>
                    <div class="photo"></div><!--PHOTO-->                    
                    <?php endif ?>
                    <div class="wrap">
                        <div class="dscript">
                            <div class="inner">
                                <?php if(!is_null($this->city) or !is_null($this->country)): ?>
                                <span class="location"><em></em>
                                <?php if(!is_null($this->city->title)): ?>
								<?= $this->city->title ?>, 
                                <?php endif; if(!is_null($this->country->title)): ?>
								<?= $this->country->title ?>
                                <a href="/admin/listings/location/<?= $this->listing->id ?>" class="link1">Edit location</a></span>
                                <?php endif ?>
                                <?php else: ?>
								<span class="location"><em></em>Unknown Location. 
                                <a href="/admin/listings/location/<?= $this->listing->id ?>" class="link1">Set location</a></span>
								<?php endif ?>
                                <?php if(!empty($this->listing->description)): ?>
                                <p><?= $this->listing->description ?>...</p>
                                <?php else: ?>
                                <p>No description yet.</p>
                                <?php endif ?>
                                <?php if($this->listing->price != 0): ?>
                                <div class="price">
                                    <em>From</em>
                                    <sup>$</sup>
                                    <span><?= $this->listing->price ?> <sub>per night</sub></span>
                                </div><!--PRICE-->
                                <?php else: ?>
                                <div class="price">
                                    <p class="notSet">
                                        No price set yet<br/>
                                        <a href="/admin/listings/pricing/<?= $this->listing->id ?>" class="link1">Set pricing now</a>
                                    </p>
                                </div><!--PRICE-->
                                <?php endif ?>
                                <!--
                                <div class="reviews">
                                    <ul class="rating">
                                        <li><a href="" class="slct"></a></li>
                                        <li><a href="" class="slct"></a></li>
                                        <li><a href="" class="slct"></a></li>
                                        <li><a href="" class="nrml"></a></li>
                                        <li><a href="" class="nrml"></a></li>
                                    </ul>
                                    <span>5 Reviews</span>
                                </div>--><!--REVIEWS-->
                            </div><!--INNER-->
                        </div><!--DSCRIPT-->
                        <div class="clear"></div>
                    </div><!--WRAP-->
                </div><!--IMAGE_BG-->
                <div class="wrap">
                    <div class="cont">
                        <div class="container">
                        	<?= $this->partial('partials/addtomytrip.phtml', array(
									'user' => $this->user,
									'trips' => $this->trips,
									'listing' => $this->listing,
									'class'	=> 'btn-2',
									'class2' => 'one'
							)) ?>
							
                            <?php if(!isset($_COOKIE['tooltipHelpList'])): ?>
							<div class="firstime_tip">
								<img class="arrow" src="https://developer.tripfab.com/images6/arrow-24.png" alt="">
								<div class="cont">
									<img src="https://developer.tripfab.com/images6/stamp.png" width="75" height="75" alt="" />
									<p><strong>Planning a Trip?</strong>
										Ey! If you're planning a trip you can create you own customize trip, add things to do there and book it when you're ready to travel.
									</p>
								</div><!--CONT-->
								<div class="bot">
									<form action="post" id="tooltipHelpList">
										<fieldset>
											<label><input checked="checked" type="checkbox" name="" value="" />Don't show again</label>
											<input type="submit" value="Okay" class="btn-1" />
										</fieldset>
									</form>
								</div><!--BOT-->
							</div><!--FIRSTIME_TIP-->
                            <?php endif ?>
							
                            <div class="carousel">
                                <p><span></span>Photos & Video</p>
                                <a href="" class="lf-arrow"></a>
                                <div class="imgs">
                                	<?php if(count($this->pictures) > 0): ?>
									<ul>
                                    <?php foreach($this->pictures as $j=>$pic): ?>
										<li>
											<a rel="group1" title="<?= $pic->location ?>" class="lbc" href="#grande<?= $j ?>" data-tip="#small<?= $j ?>">
											<?= $this->thumbnail(65,$pic->url,'','1:1') ?><span class="arrow"></span></a>
										</li>
	                                <?php endforeach ?>
									</ul>
                                    <?php else: ?>
                                    <ul><li></li><li></li><li></li><li></li><li></li><li></li></ul>
                                    <?php endif ?>
	                            </div><!--IMGS-->
								<div class="bigImages">
                                	<?php foreach($this->pictures as $j => $pic): ?>
                                	<div class="hover" id="small<?= $j ?>">
                                        <a href="#grande<?= $j ?>" class="lbc">
                                        <?= $this->thumbnail(array('width'=>391,'height'=>254),$pic->url,'','391:254') ?>
                                        <span><?= $pic->location ?></span></a>
                                    </div>
                                    <?php endforeach ?>
								</div><!--BIGIMAGES-->
                            </div><!--CAROUSEL-->
                            <div class="hidden">
                                <?php for($i=0;$i<count($this->pictures);$i++): ?>
                                <?= $this->image($this->pictures[$i]->url, 'lgbox_img','grande'.$i) ?>
                                <?php endfor ?>
                            </div>
                            <div class="tabs">
                                <ul>
                                    <li><a href="#description" class="ui-tabs-selected ui-state-active">Description</a></li>
                                    <li><a href="#room_types">Room Types</a></li>
                                    <li><a href="#directions">How to Get There</a></li>
                                </ul>
                                <div class="description" id="description">
                                    <div class="info">
                                        <ul>
                                			<?php if(!empty($this->listing->checkin) and $this->listing->checkin != '00:00:00'): ?>
                                            <li><span class="ck_in"></span><strong>Check In</strong> 
											<?= date('g:i a', strtotime($this->listing->checkin)) ?></li>
                                            <?php endif ?>
                                			<?php if(!empty($this->listing->checkout) and $this->listing->checkout != '00:00:00'): ?>
                                            <li><span class="ck_out"></span><strong>Check Out</strong> 
											<?= date('g:i a', strtotime($this->listing->checkout)) ?></li>
                                            <?php endif ?>
                                        </ul>
                                    </div><!--INFO-->
                                    <h4><span class="hotel"></span><?= $this->listing->title ?></h4>
                                    <?php $ok = true ?>
                                    <?php if(!empty($this->overview->about)): ?>
                                    <?php $ok = false; ?>
                                    <p><?= nl2br($this->overview->about) ?></p>
                                    <?php endif; if(!empty($this->overview->expect)): ?>
                                    <?php $ok = false; ?>
                                    <h5>What to Expect</h5>
                                    <p><?= nl2br($this->overview->expect) ?></p>
                                    <?php endif; if(!empty($this->overview->love)): ?>
                                    <?php $ok = false; ?>
                                    <h5>Things you'll love</h5>
                                    <p><?= nl2br($this->overview->love) ?></p>
                                    <?php endif ?>
                                    
                                    <?php if($ok): ?>
                                    <div class="empty">
                                        <p>There are no description yet. 
                                        <a href="/admin/listings/overview/<?= $this->listing->id ?>" class="link1">Edit now</a></p>
                                    </div><!--EMPTY-->
                                    <?php endif ?>
                                    
									<?php $ok = true; $i=0; $limit = count($this->details) ?>
                                    <?php $ok1 = true; $ok3 = true; ?>
                                    <?php while($i<$limit) { 
                                            if($this->details[$i]->type == 1) {$ok = false; $ok1 = false; }
                                            if($this->details[$i]->type == 3) {$ok = false; $ok3 = false; }
                                            $i++; } ?>
                                    <?php if(!$ok1 or (count($this->listing_amenities) > 0)): ?>
                                    <div class="amenities">
                                        <h4><span class="icon"></span>Amenities</h4>
                                        <ul>
                                            <?php foreach($this->listing_amenities  as $amm): ?>
                                            <li><?= $this->def_amenities[$amm]->name ?></li>
                                            <?php endforeach ?>
                                            <?php foreach($this->details as $detail): ?>
                                            <?php if($detail->type == 1): ?>
                                            <li><?= stripslashes($detail->text) ?></li>
                                            <?php endif ?>
                                            <?php endforeach ?>
                                        </ul>
                                    </div><!--AMENITIES-->
                                    <?php else: ?>
                                    <div class="act_details">
                                        <h4><span class="icon"></span>Amenities</h4>
                                        <div class="empty">
                                            <p>There are no amenities yet. 
                                        <a href="/admin/listings/details/<?= $this->listing->id ?>" class="link1">Edit now</a></p>
                                        </div><!--EMPTY-->
                                    </div><!--AMENITIES-->
                                    <?php endif ?>
                                    <?php if(!$ok3): ?>
                                    <div class="policies">
                                        <h5>Policies</h5>
                                        <ul>
											<?php foreach($this->details as $detail): ?>
                                            <?php if($detail->type == 3): ?>
                                            <li><?= stripslashes($detail->text) ?></li>
                                            <?php endif ?>
                                            <?php endforeach ?>
                                        </ul>
                                    </div><!--POLICIES-->
                                    <?php else: ?>
                                    <div class="policies">
                                        <h5>Policies</h5>
                                        <div class="empty ">
                                            <p>There are no policies yet. 
                                        	<a href="/admin/listings/details/<?= $this->listing->id ?>" class="link1">Edit now</a></p>
                                        </div><!--EMPTY-->
                                    </div><!--POLICIES-->
                                    <?php endif ?>
                                </div><!--DESCRIPTION-->
                                <div class="room_types" id="room_types">
                                	<?php if(count($this->rooms) > 0): ?>
                                	<?php foreach($this->rooms as $room): ?>
                                    <div class="single">
                                        <h4><?= $room->name ?></h4>
                                        <?php if(!empty($room->image)): ?>
                                        <?= $this->thumbnail(array('width'=>220,'height'=>136), $room->image, '','220:136'); ?>
                                        <?php endif ?>
                                        <ul>
											<?php if(!empty($room->description)): ?>
                                            <li><?= $room->description ?></li>
                                            <?php endif ?>
                                            <?php if($room->nights > 0):?>
                                            <li>Minimum Stay: <?= $room->nights ?> <?= (count($room->nights) > 1) ? "nights" : 'night' ?>   </li>
                                            <?php endif ?>
                                            <?php if($room->people > 0): ?>
                                            <li>Maximum Accommodation: <?= $room->people ?> <?= (count($room->people) > 1) ? "people" : 'person' ?></li>
                                            <?php endif ?>
                                            <?php if($room->bedrooms > 0): ?>
                                            <li>
                                                <?= $room->bedrooms ?> <?= (count($room->bedrooms) > 1) ? "Bedrooms" : 'Bedroom' ?>  
                                            </li>
                                            <?php endif ?>
                                            <?php foreach($this->beds[$room->id] as $bed): ?>
                                            <li><?= $bed->quantity ?> <?= $bed->type ?> <?= (count($room->quantity) > 1) ? "Beds" : 'Bed' ?></li>
                                            <?php endforeach ?>
                                            <?php if(count($this->room_amenities[$room->id]) > 0): ?>
                                            <li><b>Amenities</b>
                                            <?php foreach($this->room_amenities[$room->id] as $amm): ?>
                                            <br /><?= $this->amenities[$amm]->name ?>
                                            <?php endforeach ?></li>
                                            <?php endif ?>
                                        </ul>
                                        <div class="clear"></div>
                                    </div><!--SINGLE-->
                                    <?php endforeach ?>
                                    <?php else: ?>
                                    <div class="empty line">
                                        <p>There are no rooms yet. 
                                        <a href="/admin/listings/rooms/<?= $this->listing->id ?>" class="link1">Edit now</a></p>
                                    </div><!--EMPTY-->
                                    <?php endif ?>
                                </div><!--ROOM_TYPES-->
                                
                                <div id="directions">
                                	<?php $ok = true ?>
                                    <?php if(!empty($this->getthere->plane)): ?>
                                	<?php $ok = false ?>
                                    <div class="dflt">
                                        <h4><span class="plane"></span>By Plane</h4>
                                        <p><?= stripslashes(nl2br($this->getthere->plane)) ?></p>
                                    </div><!--DFLT-->
                                    <?php endif; if(!empty($this->getthere->car)): ?>
                                	<?php $ok = false ?>
                                    <div class="dflt">
                                        <h4><span class="car"></span>By Car</h4>
                                        <p><?= stripslashes(nl2br($this->getthere->car)) ?></p>
                                    </div><!--DFLT-->
                                    <?php endif; if(!empty($this->getthere->bus)): ?>
                                	<?php $ok = false ?>
                                    <div class="dflt">
                                        <h4><span class="bus"></span>By Bus</h4>
                                        <p><?= stripslashes(nl2br($this->getthere->bus)) ?></p>
                                    </div><!--DFLT-->
                                    <?php endif; if(!empty($this->getthere->train)): ?>
                                	<?php $ok = false ?>
                                    <div class="dflt">
                                        <h4><span class="train"></span>By Train</h4>
                                        <p><?= stripslashes(nl2br($this->getthere->train)) ?></p>
                                    </div><!--DFLT-->
                                    <?php endif; if(!empty($this->getthere->boat)): ?>
                                	<?php $ok = false ?>
                                    <div class="dflt">
                                        <h4><span class="boat"></span>By Boat</h4>
                                        <p><?= stripslashes(nl2br($this->getthere->boat)) ?></p>
                                    </div><!--DFLT-->
                                    <?php endif ?>
                                    
                                    <?php if($ok): ?>
                                    <div class="dflt">
                                        <div class="empty">
                                            <span class="car"></span>
                                            <p>There is not info about how to get there. 
                                        <a href="/admin/listings/location/<?= $this->listing->id ?>" class="link1">Edit now</a></p>
                                        </div><!--EMPTY-->
                                    </div><!--DFLT-->
                                    <?php endif ?>
                                    
                                    <?php if(!empty($this->listing->address)): ?>
                                    <div class="map">
                                        <h4><span></span>Location</h4>
                                        <p><strong><?= $this->listing->title ?></strong>
                                        <?= $this->listing->address ?></p>
                                        <div class="map_canvas">
                                            <div class="cont">
                                                <div id="mapcanvas"></div>
                                            </div><!--CONT-->
                                            <span class="sw"></span>
                                        </div><!--MAP_CANVAS-->
                                    </div><!--MAP-->
                                    <?php else: ?>
                                    <div class="dflt">
                                        <div class="empty">
                                            <span class="location"></span>
                                            <p>Unknown Location. 
                                       		<a href="/admin/listings/location/<?= $this->listing->id ?>" class="link1">Set location now</a></p>
                                        </div><!--EMPTY-->
                                    </div><!--DFLT-->
                                    <?php endif ?>
                                </div><!--DIRECTIONS-->
                            </div><!--TABS-->
                            
                            <?php if(count($this->reviews) > 0): ?>
                            <div class="reviews">
                                <div class="ttl"><span></span><?= count($this->reviews) ?> Reviews 
                                <!--<a href="#writeReview" class="btn-10 lbc">Write Review</a>--></div><!--TTL-->
                                <?php foreach($this->reviews as $rev): ?>
                                <div class="single">
	                                <?php if(!empty($rev->user_image)): ?>
                                	<?= $this->thumbnail(58,$review->user_image, '', '1:1') ?>
	                                <?php else: ?>
	                                <?= $this->thumbnail(58,'/images/default-profile.gif','', '1:1') ?>                                    
                                    <?php endif ?>
                                    <div class="message">
                                        <div class="subject"><?= $rev->title ?> <em>by</em> <span><?= $rev->user_name ?></span></div>                                        <div class="text">
                                            <p><?= stripslashes(nl2br($rev->text)) ?></p>
                                            <!--
                                            <div class="social">
                                                <a href="" class="not"></a>
                                                <a href="" class="like"></a>
                                                <span class="pos">+4</span>
                                                <span class="neg">-4</span>
                                                <p>Did you find this review helpful?</p>
                                                <span class="date">Apr 26, 2011</span>
                                                <div class="clear"></div>												
                                            </div>--> <!--SOCIAL-->
                                            <span class="help"><em></em>Helpful</span>
                                            <span class="n-help"><em></em>Not Helpful</span>
                                        </div><!--TEXT-->
                                    </div><!--MESSAGE-->
                                    <div class="clear"></div>
                                </div><!--SINGLE-->
                                <?php endforeach ?>
                                <!--
                                <div class="paging">
                                    <span class="total">20 - 25 of 126 Reviews</span>
                                    <ul>
                                        <li class="prev"><a href="" class="" class="prev">Previous</a></li>
                                        <li><a href="" class="">1</a></li>
                                        <li><a class="active" href="" class="">2</a></li>
                                        <li><a href="" class="">3</a></li>
                                        <li class="next"><a href="" class="" class="next">Next</a></li>
                                    </ul>
                                </div>--><!--PAGING-->
                            </div><!--REVIEWS-->
							<?php else: ?>
                            <div class="empty_reviews">
                                <div class="empty">
                                    <span class="reviews"></span>
                                    <p>This listing doesn't have reviews yet.</p>
                                </div><!--EMPTY-->
                            </div>		
                            <?php endif ?>
                        </div><!--CONTAINER-->
                        <div class="sidebar">
                            <div class="cont">
	                        	<form id="booking" method="post" action="/en-US/<?= $this->form_action ?>">
                                    <h5>Select the Dates <span class="i_date"></span></h5>
                                    <div class="dates">
                                    	<span class="line"></span>
                                        <div class="check">
                                            <label>Check In</label>
                                            <input id="checkIn" type="text" name="checkin" value="dd/mm/yyyy" />
                                        </div><!--CHECK-->
                                        <div class="check">
                                            <label>Check Out</label>
                                            <input id="checkOut" type="text" name="checkout" value="dd/mm/yyyy" />
                                        </div><!--CHECK-->
                                    </div><!--DATES-->
                                    <h5><span class="i_room"></span>Select the Room Details</h5>
                                    <div class="type">
                                    	<span class="line"></span>
                                        <?php foreach($this->options as $option): ?>
	                                        <div class="details">
	                                        
	                                        	<table width="262">
	                                        		<tr>
	                                        			<td width="32"><input type="radio" id="room<?= $option->id ?>" name="option" value="<?= $option->id ?>" /></td>
	                                        			<td width="175"><label for="room<?= $option->id ?>"><?= $option->name ?> (<?= $this->rooms2[$option->id]['people'] ?>/room)</label></td>
	                                        			<td width="55"><em>$<?= $this->prices[$option->id]['price'] ?> </em></td>
	                                        		</tr>
	                                        	</table>
                                        		<!--<label for="room<?= $option->id ?>">
													<input type="radio" id="room<?= $option->id ?>" name="option" value="<?= $option->id ?>" />
													<span><?= $option->name ?> (<?= $this->rooms2[$option->id]['people'] ?>/room)</span> 
													<em>$<?= $this->prices[$option->id]['price'] ?> </em>
												</label>-->

												<div class="room_tip">
													<span class="rw"></span>
													<h6><?= $option->name ?></h6>
													<div class="text">
														<p><?= $this->rooms2[$option->id]['description'] ?></p>
													</div><!--TEXT-->
													<ul>
                                                    	<?php if($this->rooms2[$option->id]['nights'] > 0): ?>
														<li><strong>Minimum Stay:</strong> 
                                                        <?= count($this->rooms2[$option->id]['nights'] > 1) ? 
														$this->rooms2[$option->id]['nights'] . ' nights' :
														$this->rooms2[$option->id]['nights'] . ' night' ?></li>
                                                        <?php endif ?>
                                                        <?php if($this->rooms2[$option->id]['people'] > 0): ?>
														<li><strong>Maximum Accommodation:</strong> 
                                                        <?= count($this->rooms2[$option->id]['people'] > 1) ? 
														$this->rooms2[$option->id]['people'] . ' people' :
														$this->rooms2[$option->id]['people'] . ' person' ?></li>
                                                        <?php endif ?>
													</ul>
												</div><!--ROOM_TIP-->												
                                        	</div><!--DETAILS-->
                                        <?php endforeach ?>
                                    </div><!--TYPE-->
                                    <div class="selects">
                                        <label class="rooms">
                                            Adults
                                            <select class="ocp adt"  name="adults">
                                                <?php for($i=1; $i<=12; $i++): ?>
                                                <option value="<?= $i ?>"><?= $i ?></option>
                                                <?php endfor ?>
                                            </select>
                                        </label>
                                        <label>
                                            Kids
                                            <select class="ocp kid" name="kids">
                                                <option value="0">0</option>
                                                <?php for($i=1; $i<=12; $i++): ?>
                                                <option value="<?= $i ?>"><?= $i ?></option>
                                                <?php endfor ?>
                                            </select>
                                        </label>
                                        <div class="clear"></div>
                                    </div><!--SELECTS-->
                                    <div class="price">
                                         <div>
                                         	<span><sup>$</sup>
                                         	<abbr id="sumaryPrice"><?= $this->listing->price ?></abbr> 
                                         	<sub>Subtotal</sub></span>
                                         </div>
                                    </div><!--PRICE-->
                                    <input type="submit" value="Book Now!" class="btn-1 noclean" />
                                    <?php foreach($this->form_fields as $name => $value): ?>
                                    <input type="hidden" name="<?= $name ?>" value="<?= $value ?>" />
                                    <?php endforeach ?>
                                </form>
                                <div class="add">
                                    <?= $this->partial('partials/addtomytrip.phtml', array(
                                            'user' => $this->user,
                                            'trips' => $this->trips,
                                            'listing' => $this->listing,
                                            'class'	=> 'btn-2',
                                            'class2' => 'two'
                                    )) ?>
                                    <em>or you can</em>
                                    <div class="clear"></div>
                                </div><!--ADD-->
                            </div><!--CONT-->
                        </div><!--SIDEBAR-->
                        <div class="clear"></div>
                    </div><!--CONT-->
                </div><!--WRAP-->
            </div><!--LSTNG_HTL-->
        </div><!--CONT_BL-->
    </div><!--WP_CONTENT-->
    <div id="wp_footer">
	    <?= $this->partial('partials/footer.phtml'); ?>  
    </div><!--WP_FOOTER-->
    <div class="hidden">
        <div id="send_message">
            <form action="" id="sendMessageForm">
                <div class="lb-forgot">
                    <div class="ttl">Send a message <em>to</em> <?= $this->vendor->name ?></div>
                    <div class="intro_m">
                        <p><strong>Questions or concerns about the activity?</strong>
                            Please write a message and you'll get an answer very soon.</p>
                    </div><!--INTRO-->
                    <div class="content">
                        <textarea cols="30" name="message" rows="1"></textarea>
                    </div><!-- closes content -->
                    <div class="bottom">
                        <input type="submit" class="btn-1" value="Send Message" />
                        <span onclick="$.fancybox.close()" class="btn-10">Cancel</span>	
                    </div><!-- closes bottom -->
                </div><!-- closes lb-forgot -->
                <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
            </form>
        </div>
        <div id="live_chat">
            <img src="/images2/chat.png" />
        </div>
        <div id="start_call">
            <div id="dialpad" class="lb">
                <div class="top">Dial your phone number</div><!--TOP-->
                <div class="middle">
                    <p>We'll connect you with the vendor in few minutes. Directly.</p>
                    <div class="number-display">
                        <a href="#" class="flag"><img src="/images2/flags/us.png" width="16" height="16" alt="" /></a>
                        <div class="all_flags">
                            <a href="#" class="up" onMouseover="move('container',10)" onMouseout="clearTimeout(move.to)"></a>
                            <a href="#" class="down" onMouseover="move('container',-10)" onMouseout="clearTimeout(move.to)"></a>
                            <div class="holder">
                                <div id="container" style="position:absolute;width:282px;left:0;top:0">
                                    <p>ALL COUNTRIES</p>
                                    <?php foreach($this->countries as $c): ?>
                                    <a href="#" data-code="<?= $c->phone ?>"><img src="/images2/flags/<?= strtolower($c->code) ?>.png" width="16" height="16" alt="" />
                                    <?= $c->title ?> <strong>(+<?= $c->phone ?>)</strong></a>
                                    <?php endforeach ?> 
                                </div><!--CONTAINER-->
                            </div><!--HOLDER-->
                        </div><!--ALL_FLAGS-->
                        <input type="text" name="number" value="" />
                        <input type="hidden" name="code" value="1" />
                        <a href="" class="close"></a>
                        <div class="clear"></div>
                    </div><!--NUMBER-DISPLAY-->
                    <div class="numbers">
                        <a data-num="1" href="">1</a>
                        <a data-num="2" href="">2<span>ABC</span></a>
                        <a data-num="3" href="">3<span>DEF</span></a>
                        <a data-num="4" href="">4<span>GHI</span></a>
                        <a data-num="5" href="">5<span>JKL</span></a>
                        <a data-num="6" href="">6<span>MNO</span></a>
                        <a data-num="7" href="">7<span>PQRS</span></a>
                        <a data-num="8" href="">8<span>TUV</span></a>
                        <a data-num="9" href="">9<span>WXYZ</span></a>
                        <a data-num="*" href="">*</a>
                        <a data-num="0" href="">0</a>
                        <a data-num="#" href="">#</a>
                    </div><!--NUMBERS-->
                    <div class="control">
                        <input type="button" name="start" class="btn-1" value="Start Call" />
                        <input type="button" name="Cancel"  class="cancel" value="Cancel" />
                    </div><!--CONTROL-->
                </div><!--MIDDLE-->
            </div><!--DIALPAD-->
        </div>
        <div id="newtrip">
            <div id="create_trip">
                <form action="">
                    <div class="top">
                        <h3>Create a New Trip</h3>
                        <p>Complete the information below to start your next trip</p>
                    </div><!--TOP-->
                    <div class="cont">
                        <fieldset>
                            <div class="item">
                                <label class="trip">Trip Name</label>
                                <input type="text" name="title" value="" />
                            </div><!--ITEM-->
                            <div class="item">
                                <label class="dates">Trip Dates</label>
                                <input class="start" type="text" name="start" value="Starting Date" />
                                <input class="end"type="text" name="end" value="Ending Date" />
                                <label class="check">
                                    <input type="checkbox" class="nodatesyet"/>
                                    I don't know the travel dates yet
                                </label>
                            </div><!--ITEM-->
                            <div class="item last">
                                    <input type="checkbox" checked="checked" />
                                    <p>I want to receive special offers from vendors near
                                        of the places I'll visit in this trip</p>
                            </div><!--ITEM-->
                        </fieldset>
                    </div><!--CONT-->
                    <div class="bottom">
                        <input type="submit" class="btn-1 noclean" value="Create Trip" />
                        <input type="button" onclick="$.fancybox.close(); return false;" class="btn-10 noclean" value="Cancel" />
                    </div><!--BOTTOM-->
                    <input type="hidden" name="trip" value="new" />
                    <input type="hidden" name="listing" value="" />
                </form>
            </div><!--CREATE_TRIP-->
        </div>
    </div>
</div><!--WRAPPER_ALL-->
<input type="hidden" value="<?= ($this->listing->lat) ? $this->listing->lat : 'none' ?>" name="listlat" />
<input type="hidden" value="<?= ($this->listing->lng) ? $this->listing->lng : 'none' ?>" name="listlng" />
<input type="hidden" value="<?= $this->listing->title ?>" name="listtitle" />
<input type="hidden" value="<?php foreach($this->disabledDates as $d): ?><?= $d ?>,<?php endforeach ?>" name="diableddates" />
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/jquery.popupWindow.js"></script>
<script type="text/javascript" src="/js2/index/listing-hotel.js"></script>
<style type="text/css">
#mapcanvas {
	width:638px;
	height:354px;}
</style>
</body>
</html>