<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> : General Info - Admin | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css2/lightboxes.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
    <style type="text/css">
    #maplocations ul {
        list-style:none;
        margin-top:10px;
        background:#FFC;
    }
    #maplocations ul li {
        margin-bottom:5px;
    }
    #mapcanvas {
        width:356px;
        height:207px;
        background:#09C;
        clear:both;
        margin-top:35px;
    }
    .listing-content .profile-items .item .inner-container > a {
        display:none;
    }
    .listing-content .profile-items .item:hover .inner-container > a {
        display:block;
    }
    .item .inner-form {
        clear:both;
        overflow:hidden;
        padding-top:5px;
    }
    .item .inner-form input.text {
        float:left;
        width:200px !important;
        vertical-align:middle;
    }
    .item .inner-form input.btn {
        float:left;
        vertical-align:middle;
    }
    .item .inner-form .selects {
        display:block;
        clear:both;
    }
    .hidden {
        display:none;
    }
    .errors {
        border:1px solid #F00;
        margin:20px 0 0;
        padding:5px;
    }
    .errors p {
        color:#F00;
        font-weight:normal;
        font-style:italic;
    }
    input.error {
        border:1px solid #F00 !important;
    }
    label.error {
        display:none !important;
    }
    </style>
</head>
<body>
<div class="w1">
    <?= $this->partial('admin_partials/header.phtml', array()); ?>
    <div class="w3_admin">
        <div class="sub_menu">
            <h2>
            	<?php if($this->listing->status == 1): ?>
            	<span class="lstngActv">Active</span>
                <?php else: ?>
            	<span class="lstngInct">Inactive</span>
                <?php endif ?>
            	Editing. <span>Editing. <span><?php echo $this->listing->title ?></span>
	            <em class="ed">by </em> 
	            <a href="/admin/users/view/partner/<?= $this->vendor->id ?>" class="partner"><?= $this->vendor->name ?></a>
	        </h2>           
            <?= $this->partial('admin_partials/listing_actions.phtml', array('active'=> $this->listing)); ?>
        </div><!--SUB_MENU-->
    </div><!--W3-->
    <div class="w2">
        <div class="listing-wrapper wrapper" id="edit_places">
            <div class="listing-content show">
                <div class="left">
                    <?= $this->partial('admin_partials/vendorlistingsmenu.phtml', array('active'=>'General Information', 'id' => $this->listing->id, 
									   'type'=>$this->listing->main_type)) ?>
                </div><!-- closes left -->
                <div class="right">
                	<?= $this->partial('admin_listing/restaurant/info.phtml', array(
							'errors' 	 => $this->errors,
							'listing'	 => $this->listing,
							'countries'	 => $this->countries,
							'cities'	 => $this->cities,
							'schedules'	 => $this->schedules,
							'place'		 => $this->place,
							'rest_categories' => $this->rest_categories,
							'ent_categories' => $this->ent_categories,
							'fq'		=> $this->fq,
							'listing_types' => $this->listing_types
						)); ?>
                </div><!-- closes right -->
                <div class="clear"></div>
            </div><!-- closes listing-content --> 
        </div><!-- closes listing-wrapper --> 
    </div><!-- closes w2 -->
	<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
</div><!-- closes w1 -->
<?php echo $this->partial('admin_partials/listing_actions_lbs.phtml', array('listing'=>$this->listing, 'main_category' => $this->main_category)) ?>
<script type="text/javascript" src="/js2/jquery.js"></script> 
<script type="text/javascript" src="/js2/provider/listing-edit.js"></script> 
<script type="text/javascript" src="/js2/admin/listing-actions.js"></script>
<script type="text/javascript">
var $appid = '191328617648352';
//var $appid = '370449162976552';

var $token;

$(function(){
	$('textarea').elastic();
	
	$('input, select:not(.hidden), textarea').attr('disabled','disabled');
	
	$('select[name=main_type]').change(function(){
		$cat = parseInt($(this).val());
		switch($cat) {
			case 2: 
				$('select[name=types].rest').removeClass('hidden');
				$('select[name=types].rest').removeAttr('disabled');
				$('select[name=types].ent').addClass('hidden');
				$('select[name=types].ent').attr('disabled');
				break;
			case 7: 
				$('select[name=types].ent').removeClass('hidden');
				$('select[name=types].ent').removeAttr('disabled');
				$('select[name=types].rest').addClass('hidden');
				$('select[name=types].rest').attr('disabled');
				break;
		}
	});
	
	$('input[name=reloadinfo]').click(function(){
		$('input, select:not(.hidden), textarea').attr('disabled','disabled');
		
		$url = $('input[name=url]').val();
		$listing = $('input[name=ids]').val();
        if($url == "") {
            $('input, select:not(.hidden), textarea').removeAttr('disabled');
            return false;
        }
        
        $id = $('input[name=fqid]').val();
        if(typeof $id == "undefined") {
            $('input, select:not(.hidden), textarea').removeAttr('disabled');
            return false;                
        } if($id == "") {
            $('input, select:not(.hidden), textarea').removeAttr('disabled');
            return false;
        } if($token == null){
            alert('Missing Facebook Token');
            $('input, select:not(.hidden), textarea').removeAttr('disabled');
            return false;
        }
        
        $.ajax({
            url:'/ajax/updateplace',
            data:{
                id:$id,
                url:$url,
                token:$token,
				listing:$listing
            },
            dataType:'json',
            success:function(res) {
                if(res.status == "success"){
                    window.location.reload();
                } else {
                    alert(res.error);
                    $('input, select:not(.hidden)').removeAttr('disabled');
                }
            },
            error:function(res){
                alert('Something went wrong');
                $('input, select:not(.hidden)').removeAttr('disabled');
            }
        });
        
        return false;
	});
});

(function(d){
    var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
    if (d.getElementById(id)) {
        return;
    }
    js = d.createElement('script');
    js.id = id;
    js.async = true;
    js.src = "//connect.facebook.net/en_US/all.js";
    ref.parentNode.insertBefore(js, ref);
}(document));

window.fbAsyncInit = function() {
    FB.init({
        appId      : $appid, // App ID
        channelUrl : '//tripfab.com/places/channel.html', // Channel File
        status     : true, // check login status
        cookie     : true, // enable cookies to allow the server to access the session
        xfbml      : true  // parse XFBML
    });
	
	FB.getLoginStatus(function(response) {
		console.log(response);
		if (response.status === 'connected') {
			$token = response.authResponse.accessToken;
			$('select:not(.hidden), input, textarea').removeAttr('disabled');
		} else {
			FB.login(function(response) {
				if (!response.authResponse) {
					alert('You need to enable this application on facebook in order to used');
					$token = null;
				} else {
					$token = response.authResponse.accessToken;
					$('select:not(.hidden), input').removeAttr('disabled');
				}
			});
		}
	});
};
</script>
</body>
</html>