<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> : Tips | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
	<script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
			$tip = 10;
			$('#addTip').click(function(){
				$item = $('.hidden.tip.detail').html();
				$item = $('<div class="item">'+$item+'</div>');
				$('input',$item).attr('name','tips['+$tip+'][text]');
				$('.hidden.tip.detail').before($item);
				$tip++;
				return false;
			});
        });
    </script>
</head>
<body>
<div class="w1">
    <?= $this->partial('admin_partials/header.phtml', array()); ?>
    <div class="w3_admin">
        <div class="sub_menu">
            <h2>Editing. <span><?php echo $this->listing->title ?></span></h2>
            <a href="#new_listing" class="btn-1 lbc">Create New</a>
        </div><!--SUB_MENU-->
    </div><!--W3-->
    <div class="w2">
        <div class="listing-wrapper wrapper">
            <?= $this->partial('partials/vendorlistingstop.phtml', array('listing'=>$this->listing)); ?>
            <div class="listing-content">
                <div class="left">
                    <?= $this->partial('admin_partials/vendorlistingsmenu.phtml', array('active'=>'Tips', 'id' => $this->listing->id, 
									   'type'=>$this->listing->main_type)) ?>
                </div><!-- closes left -->
                <div class="right">
				<?php 	switch($this->listing->main_type):
							case 2:
								echo $this->partial('admin_listing/restaurant/tips.phtml', array(
										'help' => $this->help,
								));
								break;
							case 4:
								echo $this->partial('admin_listing/sight/tips.phtml', array(
										'help' => $this->help,
								));
								break;
							case 5:
								echo $this->partial('admin_listing/hotel/tips.phtml', array(
										'help' => $this->help,
								));
								break;
							case 6:
								echo $this->partial('admin_listing/activity/tips.phtml', array(
										'listing' => $this->listing,
										'tips'	  => $this->tips,
										'help' => $this->help,
								));
								break;
							case 7:
								echo $this->partial('admin_listing/entertaiment/tips.phtml', array(
										'help' => $this->help,
								));
								break;
						endswitch ?>
                </div><!-- closes right -->
                <div class="clear"></div>
            </div><!-- closes listing-content -->
        </div><!-- closes listing-wrapper -->
    </div><!-- closes w2 -->
	<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
</div><!-- closes w1 -->
</body>
</html>