<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> : Type | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
    <script type="text/javascript" src="/js2/jquery.js"></script>
	<script type="text/javascript" src="/js2/admin/listing-actions.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
			
			$('input[name=kids]').change(function(){
				if($(this).attr('checked') == undefined){
					$('.accept-kids').addClass('hidden');
					$('.accept-kids select').attr('disabled','disabled');
				} else {
					$('.accept-kids').removeClass('hidden');
					$('.accept-kids select').removeAttr('disabled');
				}
			});
			
			$i = <?= (count($_POST['tip']) > 0) ? count($_POST['tip']) : 5 ?>;
			$('#addNewTip').click(function(){
				$item = $('.newitem.hidden').html();
				$item = $('<div class="itemm">'+$item+'</div>');
				$('input[name=text]', $item).attr('name','tip['+$i+'][text]');
				$('.itemm:last').before($item);
				$i++;
				return false;
			});
			
			$('.itemm a.remove').live('click', function(){
				$(this).parent('.itemm').fadeOut('fast', function(){
					$(this).remove();
				});
				return false;
			});
        });
    </script>
    <style type="text/css">
	.hidden { display:none }
	.error  {
		padding:5px; 
		border:1px solid #F00;
		margin:20px 0 0;
		color:#F00;
		font-style:italic;}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('admin_partials/header.phtml', array()); ?>
    <div class="w3_admin">
        <div class="sub_menu">
            <h2>
            	<?php if($this->listing->status == 1): ?>
            	<span class="lstngActv">Active</span>
                <?php else: ?>
            	<span class="lstngInct">Inactive</span>
                <?php endif ?>
            	Editing. <span><?php echo $this->listing->title ?></span>
            <em class="ed">by </em> <a href="/admin/users/view/partner/<?= $this->vendor->id ?>" class="partner"><?= $this->vendor->name ?></a></h2>
            <?= $this->partial('admin_partials/listing_actions.phtml', array('active'=> $this->listing)); ?>
        </div><!--SUB_MENU-->
    </div><!--W3-->
    <div class="w2">
        <div class="listing-wrapper wrapper">
            <div class="listing-content">
                <div class="left">
                    <?= $this->partial('admin_partials/vendorlistingsmenu.phtml', array('active'=>'Activity Types', 'id' => $this->listing->id, 
									   'type'=>$this->listing->main_type)) ?>
                </div><!-- closes left -->
                <div class="right">
                    <?= $this->partial('admin_listing/activity/type.phtml', array(
							'listing' => $this->listing,
							'data'	  => $this->data,
					)); ?>
                </div><!-- closes right -->
                <div class="clear"></div>
            </div><!-- closes listing-content -->
        </div><!-- closes listing-wrapper -->
    </div><!-- closes w2 -->
	<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
</div><!-- closes w1 -->
<?php echo $this->partial('admin_partials/listing_actions_lbs.phtml', array('listing'=>$this->listing, 'main_category' => $this->main_category)) ?>
</body>
</html>