<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> : Overview | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
	<script type="text/javascript" src="/js2/jquery.js"></script>
	<script type="text/javascript" src="/js2/admin/listing-actions.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
			$restrict = 10; 
			$('#addRestriction').click(function(){
				$item = $('.hidden.restriction.detail').html();
				$item = $('<div class="item">'+$item+'</div>');
				$('input',$item).attr('name','details[3]['+$restrict+'][text]');
				$('.hidden.restriction.detail').before($item);
				$restrict++;
				return false;
			});
			$('.lstng-detail a.remove').live('click', function(){
				$detail = $(this).parent('.item');
				$detail.fadeOut('fast', function(){
					$('input', $detail).attr('disabled','disabled');
				});
				return false;
			});
			$('textarea').elastic();
        });
    </script>
    <style type="text/css">
	.listing-content { overflow:visible;}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('admin_partials/header.phtml', array()); ?>
    <div class="w3_admin">
        <div class="sub_menu">
            <h2>Editing. <span><?php echo $this->listing->title ?></span>
            <em class="ed">by </em> <a href="/admin/users/view/partner/<?= $this->vendor->id ?>" class="partner"><?= $this->vendor->name ?></a></h2>
            <?= $this->partial('admin_partials/listing_actions.phtml', array('active'=> $this->listing)); ?>
        </div><!--SUB_MENU-->
    </div><!--W3-->
    <div class="w2">
        <div class="listing-wrapper wrapper">
            <div class="listing-content">
                <div class="left">
                    <?= $this->partial('admin_partials/vendorlistingsmenu.phtml', array('active'=>'Overview', 'id' => $this->listing->id, 
									   'type'=>$this->listing->main_type)) ?>
                </div><!-- closes left -->
                <div class="right">
				<?php 	switch($this->listing->main_type):
							case 2:
								echo $this->partial('admin_listing/restaurant/overview.phtml', array(
										'listing' => $this->listing,
										'overview' => $this->overview,
										'help' => $this->help,
										'details' => $this->details,
								));
								break;
							case 4:
								echo $this->partial('admin_listing/sight/overview.phtml', array(
										'listing' => $this->listing,
										'help' => $this->help,
										'overview' => $this->overview
								));
								break;
							case 5:
								echo $this->partial('admin_listing/hotel/overview.phtml', array(
										'listing' => $this->listing,
										'help' => $this->help,
										'overview' => $this->overview
								));
								break;
							case 6:
								echo $this->partial('admin_listing/activity/overview.phtml', array(
										'listing' => $this->listing,
										'help' => $this->help,
										'overview' => $this->overview
								));
								break;
							case 7:
								echo $this->partial('admin_listing/entertaiment/overview.phtml', array(
										'listing' => $this->listing,
										'help' => $this->help,
										'overview' => $this->overview,
										'details' => $this->details,
								));
								break;
						endswitch ?>
                </div><!-- closes right -->
                <div class="clear"></div>
            </div><!-- closes listing-content -->
        </div><!-- closes listing-wrapper -->
    </div><!-- closes w2 -->
	<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
</div><!-- closes w1 -->
<?php echo $this->partial('admin_partials/listing_actions_lbs.phtml', array('listing'=>$this->listing, 'main_category' => $this->main_category)) ?>
</body>
</html>