<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> : Missing Information - Admin | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css?v=<?= $this->cssVC ?>" />
    <link rel="stylesheet" href="guiders/guiders.css?v=<?= $this->cssVC ?>" type="text/css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
	<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
	<script type="text/javascript" src="/js2/admin/listing-actions.js?v=<?= $this->cssVC ?>"></script>	
    <?php if($this->ready): ?>
    <script type="text/javascript">
	$(function(){
		$.fancybox({
			href:'#finish_listing',
			padding:0,
			overlayColor:'#fff',
			showCloseButton:0,
			modal:1,
			centerOnScroll:1
		});
	});
	</script>
    <style type="text/css">
	#fancybox-content { background:#fff;}
	</style>
    <?php endif ?>
</head>
<body>
<div class="w1">
    <?= $this->partial('admin_partials/header.phtml', array()); ?>
    <div class="w3_admin">
        <div class="sub_menu">
            <h2>
            	<?php if($this->listing->status == 1): ?>
            	<span class="lstngActv">Active</span>
                <?php else: ?>
            	<span class="lstngInct">Inactive</span>
                <?php endif ?>
            	Editing. <span><?php echo $this->listing->title ?></span>
            <em class="ed">by </em> <a href="/admin/users/view/partner/<?= $this->vendor->id ?>" class="partner"><?= $this->vendor->name ?></a></h2>
            <?= $this->partial('admin_partials/listing_actions.phtml', array('active'=> $this->listing)); ?>
        </div><!--SUB_MENU-->
    </div><!--W3-->
    <div class="w2">
        <div class="listing-wrapper wrapper">
            <div class="listing-content">
                <div class="left">
                    <?= $this->partial('admin_partials/vendorlistingsmenu.phtml', array('active'=>'', 'id' => $this->listing->id, 
									   'type'=>$this->listing->main_type)) ?>
                </div><!-- closes left -->
                <div class="right">
                    <div class="pending-steps">
                        <div class="ttl">
                            <h2>This listing can't be active yet! </h2>
                            <h3>There are <span> steps remaining</span> before activate your listing</h3>
                        </div><!-- closes ttl -->
                        <ul>
                        	<?php foreach($this->validate as $key => $val): ?>
                            <?php if($val['done']): ?>
                            <li class="done">
                                <img src="/images2/cleardot.gif" alt="" />
                                <span><?= $val['label'] ?></span>
                                <?= $val['desription'] ?>
                            </li>
                            <?php else: ?>
                            <li>
                                <img src="/images2/cleardot.gif" alt="" />
                                <?php if($key == "profile"): ?>
                                <a href="<?= $val['url'] ?>"><?= $val['label'] ?></a>
                                <?php else: ?>
                                <a href="<?= $val['url'] . $this->listing->id ?>"><?= $val['label'] ?></a>
                                <?php endif ?>
                                <?= $val['desription'] ?>
                            </li>
                            <?php endif ?>
                            <?php endforeach ?>
                        </ul>
                    </div><!-- closes pending-steps -->
                </div><!-- closes right -->
            </div><!-- closes listing-content -->
        </div><!-- closes listing-wrapper -->
    </div><!-- closes w2 -->
	<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
</div><!-- closes w1 -->
<?php echo $this->partial('admin_partials/listing_actions_lbs.phtml', array('listing'=>$this->listing, 'main_category' => $this->main_category)) ?>
</body>
</html>