<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
		<title><?= $this->user->name ?> : Partners - Admin | Tripfab.com</title>
        <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
        <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
		<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
	    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css?v=<?= $this->cssVC ?>" />
		<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
  		<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css?v=<?= $this->cssVC ?>" />
  		<!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
  		<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
  		<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
	    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
		<script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.js?v=<?= $this->cssVC ?>"></script>
    	<script type="text/javascript" src="/js2/admin/traveller-view.js?v=<?= $this->cssVC ?>"></script>
			<script>
				$(document).ready(function() {
					$('a.lbc').fancybox({
						padding: 0,
						overlayColor: '#FFF',
						overlayOpacity: '0.7',
						showCloseButton: 'false'
					});
            		$("#report_tabs").tabs();
					panel(<?php echo $this->user->id?>, 1, 'partner');
				});
			</script>
		</head>
		<body>
			<div class="w1">
    		<?php echo $this->partial('admin_partials/header.phtml', array()); ?>
			
			<div class="w3_admin">
				<div class="sub_menu">
					<h2><?php echo $this->user->name?>. <span>Personal Information.</span></h2>
					<a href="#password-reset" class="btn-10 lbc">Reset Password</a>
                    <a href="#activate" class="btn-10 act lbc" id="act-btn-342"<?php echo $this->user->active==1 ? 'style="display:none"' : '';?> >Activate Partner</a>
            		<a href="#deactivate" class="btn-10 deact lbc" id="deact-btn-342" <?php echo $this->user->active==0 ? 'style="display:none"' : '';?>>Deactivate Partner</a>
				</div><!--SUB_MENU-->
            </div><!--W3-->
			<div class="all_listing">
				<div id="user_view" class="listing-wrapper wrapper">
					<div class="listing-content">
						<div class="left">
							<ul>
								<li id="nav1" class="current"><a href="javascript://" onclick="panel(<?php echo $this->user->id?>, 1, 'partner')">General Information</a></li>
								<li id="nav2"><a href="javascript://" onclick="panel(<?php echo $this->user->id?>, 2,'partner')">Listings</a></li>
								<li id="nav3"><a href="javascript://" onclick="panel(<?php echo $this->user->id?>, 3,'partner')">Reservations</a></li>
								<li id="nav4"><a href="javascript://" onclick="panel(<?php echo $this->user->id?>, 4,'partner')">Offers</a></li>
								<li id="nav5"><a href="javascript://" onclick="panel(<?php echo $this->user->id?>, 5,'partner')">Bank Accounts</a></li>
							</ul>
						</div><!-- closes left -->
						<div class="right">
                        
                        
							<?php if($this->successMessage): ?>
							<script type="text/javascript">
                                showAlert("Your changes have been saved");
                            </script>
                            <?php endif ?>	
                        
							<div class="lstng-details" id="content">

							</div>
							<!-- closes lstng-details -->
						</div>
						<!-- closes right -->
					</div>
					<!-- closes listing-content -->
				</div><!--USER_VIEW-->

			</div><!--ALL_LISTING-->
					
			<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
            
            
            <div class="hidden">
            
                <div class="lb activation" id="activate">
                <div class="top">Activate Listing </div><!--TOP-->
                <form method="post" action="">
                    <fieldset>
                        <div class="cont">
                            <p>Are you sure activate <?php echo $this->user->name?>?</p>
                        </div><!--CONT-->
                        <div class="bottom">
                            <a href="javascript://" class="btn-1" id="btn-activate-326">Activate</a>
                            <a href="javascript://" class="btn-10" id="btn-cancel-326">Cancel</a>
                        </div><!--BOTTOM-->
                    </fieldset>
                </form>
            </div><!--ACTIVATE-->
            
            <div class="lb activation" id="deactivate">
                <div class="top">Desactivate Listing </div><!--TOP-->
                <form method="post" action="">
                    <fieldset>
                        <div class="cont">
                            <p>Are you sure deactivate the <?php echo $this->user->name?>?</p>
                        </div><!--CONT-->
                        <div class="bottom">
                            <a href="javascript://" class="btn-1" id="btn-deactivate-327">Deactivate</a>
                            <a href="javascript://" class="btn-10" id="btn-cancel-327">Cancel</a>
                        </div><!--BOTTOM-->
                    </fieldset>
                </form>
            </div><!--ACTIVATE-->
        
            
            </div><!--HIDDEN-->
            
            
            
		</div>
		<!-- closes w1 -->
		<?php echo $this->partial('admin_partials/report.phtml', array()); ?>
		
<div class="hidden">
	<div class="lightbox-2" id="password-reset">
		<h2>Reset Password</h2>
		<h3>Do you want to reset the password to Karina Romaine</h3>
		<div class="buttons">
			<ul>
				<li><a href="" class="btn-1">Reset</a></li>
				<li><a href="" class="btn-10">Cancel</a></li>
			</ul>
		</div><!--BUTTONS-->
	</div><!--PASSWORD-RESET-->
</div><!--HIDDEN--> 

<script type="text/javascript">
	var listingId = '<?php echo $this->user->user_id?>';
	
	$("#btn-cancel-327").click(function(){
		$.fancybox.close();
	});
	
	$("#btn-cancel-326").click(function(){
		$.fancybox.close();
	});
	$("#btn-activate-326").click(function(){
		changeListingStatus(listingId, 1);
	});
	
	$("#btn-deactivate-327").click(function(){
		changeListingStatus(listingId, 0);
	});
	
	function changeListingStatus(listingId, action){
		$.ajax({ 
		   type: "POST", 
		   url: "/ajax/usertatus/", 
		   data: 'id=' + listingId + '&act=' + action ,
		   success: function(json, status){
				$.fancybox.close();
				if(json=="success"){
					 showAlert("Listing has been updated successfully");
					 if(action==1){
						$("#act-btn-342").hide(); 
						$("#deact-btn-342").show(); 
					 }
					 else{
						$("#act-btn-342").show(); 
						$("#deact-btn-342").hide(); 
					 }
				}
		   }, 
		   error:function(jqXHR, textStatus, errorThrown){ 
				alert(textStatus);
		   }
		});
	}
</script>
	</body>
</html>