<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
		<title>Treveller</title>
        <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
        <link type="text/css" rel="stylesheet" href="/css2/all.css" />
		<script type="text/javascript" src="/js2/jquery.js"></script>
	    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
		<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
  		<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />
  		<!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
  		<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
  		<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
	    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
		<script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.js"></script>
    	<script type="text/javascript" src="/js2/admin/traveller-view.js"></script>
			<script>
				$(document).ready(function() {
					$('a.lbc').fancybox({
						padding: 0,
						overlayColor: '#FFF',
						overlayOpacity: '0.7',
						showCloseButton: 'false'
					});
            		$("#report_tabs").tabs();
					panel(<?php echo $this->user->id?>, 1, 'partner');
				});
			</script>
		</head>
		<body>
			<div class="w1">
    		<?php echo $this->partial('admin_partials/header.phtml', array()); ?>
			
			<div class="w3_admin">
				<div class="sub_menu">
					<h2><?php echo $this->user->name?>. <span>Personal Information.</span></h2>
					<a href="#password-reset" class="btn-10 lbc">Reset Password</a>
                    <a href="#activate" class="btn-10 act lbc" id="act-btn-342"<?php echo $this->user->active==1 ? 'style="display:none"' : '';?> >Activate Partner</a>
            		<a href="#deactivate" class="btn-10 deact lbc" id="deact-btn-342" <?php echo $this->user->active==0 ? 'style="display:none"' : '';?>>Deactivate Partner</a>
				</div><!--SUB_MENU-->
            </div><!--W3-->
			<div class="all_listing">
				<div id="user_view" class="listing-wrapper wrapper">
					<div class="listing-content">
						<div class="left">
							<ul>
								<li id="nav1" class="current"><a href="<?php echo $this->url(array('seq'=>1))?>">General Information</a></li>
								<li id="nav2"><a href="<?php echo $this->url(array('seq'=>2))?>">Listings</a></li>
								<li id="nav3"><a href="<?php echo $this->url(array('seq'=>3))?>">Reservations</a></li>
								<li id="nav4"><a href="<?php echo $this->url(array('seq'=>4))?>">Offers</a></li>
								<li id="nav5"><a href="<?php echo $this->url(array('seq'=>5))?>">Bank Accounts</a></li>
							</ul>
						</div><!-- closes left -->
						<div class="right">
                        
                        
							<?php if($this->successMessage): ?>
							<script type="text/javascript">
                                showAlert("Your changes have been saved");
                            </script>
                            <?php endif ?>	
                        
							<div class="lstng-details" id="content">
<h3 class="title">General Information <a href="" class="back">Back to Partners</a></h3>
<div class="block">

<form id="general" name="general" method="POST" action="/admin/users/view/partner/<?php echo $this->user->id ?>">
<div class="single_trip">
    <div class="image"><img src="<?php echo $this->user->image?>" width="134" height="134" alt="" /></div><!--IMAGE-->
    <table width="520" border="0" class="info">
        <tr>
            <td width="180">Company Name</td>
			<td width="340"><input type="text"  name="name" value="<?php echo $this->user->name?>" /></td>
        </tr>
        <tr>
            <td width="180">E-mail</td>
			<td width="340"><input type="text" name="email" value="<?php echo $this->user->email?>" /></td>
        </tr>
        <tr>
            <td width="180">Contact Name</td>
			<td width="340"><input type="text" name="contact_name" value="<?php echo $this->user->contact_name?>" /></td>
        </tr>
        <tr>
            <td width="180">Partner Since</td>
			<td width="340"><input type="text" name="created" value="<?php echo date('M d, Y', strtotime($this->user->created))?>" /></td>
        </tr>
        <tr>            
            <td width="180">Country</td>
			<td width="340">
             <select id="country"  name="country">
                    <?php foreach($this->countries as $country):?>
                    <option <?php echo $this->user->country_id == $country->id ? ' selected="selected"' : ''; ?> value="<?php echo @$country->id?>"><?php echo $country->title?></option>
                    <?php endforeach;?>
            </select>
            </td>
        </tr>
        <tr>
            <td width="180">City</td>
			<td width="340">           
                    <select  id="city"  name="city">
                        <option selected="selected">City</option>
                    </select>
			</td>
        </tr>
        <tr>
            <td width="180">Phone</td>
			<td width="340"><input type="text" name="phone" value="<?php echo $this->user->phone?>" /></td>
        </tr>
        <tr>
            <td width="180">Website</td>
			<td width="340"><input type="text" name="website" value="<?php echo $this->user->website?>" /></td>
        </tr>
    </table>
</div><!--SINGLE_TRIP-->
<input type="hidden" name="user_id" value="<?php echo $this->user->user_id ?>"/>
<input class="btn-1" type="submit" onclick="/admin/users/view/partner/<?php echo $this->user->id ?>" value="Upadate"/>
</form>
</div><!--BLOCK-->


							</div>
							<!-- closes lstng-details -->
						</div>
						<!-- closes right -->
					</div>
					<!-- closes listing-content -->
				</div><!--USER_VIEW-->

			</div><!--ALL_LISTING-->
					
			<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
			<?php echo $this->partial('admin_partials/partner.phtml', array('name'=>$this->user->name, 'userId'=>$this->user->user_id)); ?>
            
            
            
            
		</div>
		<!-- closes w1 -->
		<?php echo $this->partial('admin_partials/report.phtml', array()); ?>
		
<div class="hidden">
	<div class="lightbox-2" id="password-reset">
		<h2>Reset Password</h2>
		<h3>Do you want to reset the password to Karina Romaine</h3>
		<div class="buttons">
			<ul>
				<li><a href="" class="btn-1">Reset</a></li>
				<li><a href="" class="btn-10">Cancel</a></li>
			</ul>
		</div><!--BUTTONS-->
	</div><!--PASSWORD-RESET-->
</div><!--HIDDEN--> 


<script>
		var cityId = '<?php echo $this->city;?>';
		fillCityTrip($('#country').val());
		screenUpdate();
		$('select#country').change(function(){
			fillCityTrip($('#country').val());
		});
		
		$('select#type').change(function(){
			screenUpdate();
		});
		
		function screenUpdate(){
			if($('#type').val() == 5){
				$("#field-wrapper").hide();
			}
			else{
				$("#field-wrapper").show();
			}
		}
		
		function fillCityTrip(countryId){
			var url = "/ajax/places/?type=city&c=" + countryId;
			$("#city" ).children().remove();
			$("#city" ).append(new Option('Select City', 0, true, true));
			var selected = false;
			$.getJSON(url, function(fsdata) {
				$.each(fsdata.data, function(i,city){ 
					selected = cityId == city.id ? true : false ;
					$("#city" ).append(new Option(city.title, city.id, true, selected));
					
					
				});
			});	
		}
				
		</script>




	</body>
</html>