<?php foreach($this->reservations as $reservation) : ?>
<div class="single_trip">
    <table width="520" border="0" class="info">
        <tr>
            <td width="180"><?php echo $reservation->listing_type?></td>
            <td width="340"><?php echo $reservation->listing_name?></td>
        </tr>
        <tr>
            <td width="180">Reserve Code</td>
            <td width="340"><?php echo $reservation->code?></td>
        </tr>
        <tr>
            <td width="180">Traveler</td>
            <td width="340"><?php echo $reservation->user_name?></td>
        </tr>
        <tr>
            <td><?php echo $reservation->listing_type == 'Hotels' ? 'Check In' : 'Date'?> </td>
            <td><?php echo date('M d, Y', strtotime($reservation->checkin))?></td>
        </tr>

		<?php if($reservation->listing_type == 'Hotels'): ?>
        <tr>
            <td>Check Out</td>
            <td><?php echo date('M d, Y', strtotime($reservation->checkout))?></td>
        </tr>
        <?php endif;?>
        <tr>
            <td width="180">Total</td>
            <td width="340">$<?php echo $reservation->ammount?></td>
        </tr>
        <tr>
            <td width="180"></td>
            <td width="340"><a href="">Reservation Details</a></td>
        </tr>
    </table>
</div><!--SINGLE_TRIP-->
<?php endforeach;?>

