<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
<title>vendor messages</title>
<link type="text/css" rel="stylesheet" href="/css2/reset.css" />
<link type="text/css" rel="stylesheet" href="/css2/all.css" />
<script type="text/javascript" src="/js2/jquery.js"></script>
<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />
<!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->

</head>
<body>
<div class="w1">
<div class="big-message green">
	<div class="wrapper"><img src="/images2/cleardot.gif" alt=""> <span>Your changes have been saved!</span></div>
	<!-- closes wrapper --> 
</div>
<?php echo $this->partial('admin_partials/header.phtml', array()); ?>
<div class="w3_admin">
	<div class="sub_menu">
		<h2>Quandong Hideaway. <span> Reservation Details</span></h2>
		<a href="" class="btn-10">Mark as Paid</a>
		<span class="pending_amount">Pending Payment: $750</span>
	</div><!--SUB_MENU-->
</div>
<!--W3-->
<div class="all_listing">
	<div class="detailsPayments">
		<div class="ttl">
			<h4>There are <?php echo  ?> reservations pending to pay</h4>
			<a href="/admin/payments/"> &larr; Back to Payments</a>
		</div><!--TTL-->
		<?php foreach($this->reservation as $reservations):?>
		<div class="pending_reservation">
			<div class="left">
				Surfing Lessons
			</div><!--LEFT-->
			<div class="details">
				<table cellpadding="0" width="300" border="0">
					<tr>
						<td>Type</td>
						<td class="res"><?php echo $reservations->listing_type ?></td>
					</tr>
					<tr>
						<td>Reserve Code</td>
						<td class="res"><?php echo $reservations->code ?></td>
					</tr>
					<tr>
						<td>Traveler</td>
						<td class="res"><?php echo $reservations->vendor_name ?></td>
					</tr>

					<tr>
						<td>Check in</td>
						<td class="res"><?php echo $reservations->checkin ?></td>
					</tr>
					<tr>
						<td>Check out</td>
						<td class="res"><?php echo $reservations->checkout ?></td>
					</tr>
					<tr>
						<td>Total</td>
						<td class="res"><?php echo $reservations->code ?></td>
					</tr>
				</table>
			</div><!--DETAILS-->
			<div class="clear"></div>
		</div><!--PENDING_RESERVATION-->
       <?php endforeach;?>
<div class="footer black">
	<div class="wrapper"> <a href="" class="logo">Tripfab</a> </div>
	<!--WRAPPER--> 
</div>
<!-- closes footer -->

</body>
</html>