<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
		<title>Regions</title>
        <link type="text/css" rel="stylesheet" href="/css5/reset.css" />
        <link type="text/css" rel="stylesheet" href="/css5/all.css" />
		<script type="text/javascript" src="/js2/jquery.js"></script>
		<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
  		<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />   
		<script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.js"></script>
    	<script type="text/javascript" src="/js2/admin/traveller-view.js"></script>
			<script>
				$(document).ready(function() {
					$('a.lbc').fancybox({
						padding: 0,
						overlayColor: '#FFF',
						overlayOpacity: '0.7',
						showCloseButton: 'false',
					});
					
            		$("#report_tabs").tabs();
					panel(<?php echo $this->user->id?>, 1, 'partner');
				});
			</script>
	</head>
		<body>
			<div class="w1">
    		<?php echo $this->partial('admin_partials/header.phtml', array()); ?>
			<div class="w3_admin">
				<div class="sub_menu">
					<h2>Reservation by Date </h2>
				</div><!--SUB_MENU-->
            </div><!--W3-->
			<div class="all_listing">
				<div class="search_list">
					<ul class="get-report">
						<li><a href="<?php echo $this->url(array('page' => 'pdf')); ?>" class="btn-10"><span class="pdf">Download .pdf</span></a></li>
						<li><a href="" class="btn-10"><span class="excel">Download .xls</span></a></li>
					</ul>
					<?php echo $this->paginationControl($this->paginator, 'Sliding', 'admin_partials/paginator.phtml', array('sort'=>$this->paramSort, 'seq'=>$this->paramSequence, 'q'=>$this->paramQuery)); ?>
				</div><!--SEARCH_LIST-->
				<div class="list_content">
					<table width="100%" border="0">
						<tr>
							<th width="112"><a href="<?php echo $this->url(array('sort'=>0, 'seq'=>$this->paramSort == 0 && $this->paramSequence !='desc' ? 'desc':'default'));?>">Date</a></th>
							<th width="174"><a href="<?php echo $this->url(array('sort'=>1, 'seq'=>$this->paramSort == 1 && $this->paramSequence !='desc' ? 'desc':'default'));?>">Reservation ID</a></th>
							<th width="155"><a href="<?php echo $this->url(array('sort'=>2, 'seq'=>$this->paramSort == 2 && $this->paramSequence !='desc' ? 'desc':'default'));?>">Traveler ID</a></th>
							<th width="155"><a href="<?php echo $this->url(array('sort'=>3, 'seq'=>$this->paramSort == 3 && $this->paramSequence !='desc' ? 'desc':'default'));?>">Status</a></th>
							<th width="155"><a href="<?php echo $this->url(array('sort'=>4, 'seq'=>$this->paramSort == 4 && $this->paramSequence !='desc' ? 'desc':'default'));?>">Gross Amount</a></th>
							<th width="125"><a href="<?php echo $this->url(array('sort'=>5, 'seq'=>$this->paramSort == 5 && $this->paramSequence !='desc' ? 'desc':'default'));?>">Fee</a></th>
							<th width="110"><a href="<?php echo $this->url(array('sort'=>6, 'seq'=>$this->paramSort == 6 && $this->paramSequence !='desc' ? 'desc':'default'));?>">Net Amount</a></th>
							<th width="110" class="last"><a href="<?php echo $this->url(array('sort'=>7, 'seq'=>$this->paramSort == 7 && $this->paramSequence !='desc' ? 'desc':'default'));?>">Partner ID</a></th>
						</tr>
						<?php foreach($this->paginator as $key=>$listing):?>
                        <tr <?php echo $key==0 ? 'class="first"' : ''?>>
							<td><?php echo date('M d, Y', strtotime($listing->date))?></td>
							<td><?php echo $listing->code?></td>
							<td><?php echo $listing->user_id?></td>
							<td><?php echo $listing->status ==1 ? 'Complete' : 'In Progress...';?></td>
							<td>$<?php echo round($listing->ammount, 2)?></td>
							<td>$<?php echo round($listing->fee, 2)?></td>
							<td>$<?php echo round($listing->net, 2)?></td>
							<td><?php echo $listing->vendor_id?></td>
						</tr>
                        <?php endforeach;?>
					</table>
				</div><!--LIST-CONTENT-->
				<div class="paging_bottom">
					<?php echo $this->paginationControl($this->paginator, 'Sliding', 'admin_partials/paginator.phtml', array('sort'=>$this->paramSort, 'seq'=>$this->paramSequence, 'q'=>$this->paramQuery)); ?>
				</div><!--PAGING_BOTTOM-->
			</div><!--ALL_LISTING-->
					
			<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
		</div>
		<!-- closes w1 -->
		<?php echo $this->partial('admin_partials/report.phtml', array()); ?>
        <script>
			function searchSubmit(){
				location.href="<?php echo $this->baseUrl?>/" + $("#q").val();
			}
		</script>


	</body>
</html>