<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
		<title>Reservation Details - Admin | Tripfab.com</title>
        <link type="text/css" rel="stylesheet" href="/css5/reset.css?v=<?= $this->cssVC ?>" />
        <link type="text/css" rel="stylesheet" href="/css5/all.css?v=<?= $this->cssVC ?>" />
		<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
		<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
  		<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css?v=<?= $this->cssVC ?>" />
  		<!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
  		<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
  		<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
		<script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.js?v=<?= $this->cssVC ?>"></script>
    	<script type="text/javascript" src="/js2/admin/traveller-view.js?v=<?= $this->cssVC ?>"></script>
			<script>
				$(document).ready(function() {
					$('a.lbc').fancybox({
						padding: 0,
						overlayColor: '#FFF',
						overlayOpacity: '0.7',
						showCloseButton: 'false',
					});
            		$("#report_tabs").tabs();
					
				});
			</script>
		</head>
		<body>
			<div class="w1">
    		<?php echo $this->partial('admin_partials/header.phtml', array()); ?>
			
			<div class="w3_admin">
				<div class="sub_menu">
					<h2></span></h2>
				</div><!--SUB_MENU-->
            </div><!--W3-->
			<div class="all_listing">
				<div id="user_view" class="listing-wrapper wrapper">
					<div class="listing-content">
						<div class="left">
							<ul>
								<li id="nav1" class="current">General Information</li>
							</ul>
						</div><!-- closes left -->
						<div class="right">
							<div class="lstng-details">
								<h3 class="title">General Information <a href="/admin/reservations" class="back">Back to Reservations</a></h3>
								<div class="block" id="content">
									
                                <div class="single_trip">
                                <div class="image"><img src="images2/img-76.jpg" width="134" height="134" alt="" /></div><!--IMAGE-->
                                <table width="520" border="0" class="info">
                                    <tr>
                                        <td width="180">Code</td>
                                        <td width="340"><?php echo $this->reservation->code?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Adults#</td>
                                        <td width="340"><?php echo $this->reservation->adults?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Kids</td>
                                        <td width="340"><?php echo $this->reservation->kids?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Rooms</td>
                                        <td width="340"><?php echo $this->reservation->rooms?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Nights</td>
                                        <td width="340"><?php echo $this->reservation->nights?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Rate Description</td>
                                        <td width="340"><?php echo $this->reservation->rate_description?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Additional</td>
                                        <td width="340"><?php echo $this->reservation->additional?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Additional Description</td>
                                        <td width="340"><?php echo $this->reservation->additional_description?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Rate</td>
                                        <td width="340"><?php echo $this->reservation->rate?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Sub Total</td>
                                        <td width="340"><?php echo $this->reservation->subtotal?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Taxes</td>
                                        <td width="340"><?php echo $this->reservation->taxes?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Amount</td>
                                        <td width="340"><?php echo $this->reservation->ammount?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Checkin</td>
                                        <td width="340"><?php echo date('M d, Y', strtotime($this->reservation->checkin))?></td>
                                    </tr>
                                    <tr>
                                        <td width="180">Checkout</td>
                                        <td width="340"><?php echo date('M d, Y', strtotime($this->reservation->checkout))?></td>
                                    </tr>
                                     <tr>
                                        <td width="180">Title</td>
                                        <td width="340"><?php echo $this->reservation->listing_name?></td>
                                    </tr>

                                </table>
                            </div><!--SINGLE_TRIP-->
						
									
									
								</div><!--BLOCK-->
							</div>
							<!-- closes lstng-details -->
						</div>
						<!-- closes right -->
					</div>
					<!-- closes listing-content -->
				</div><!--USER_VIEW-->

			</div><!--ALL_LISTING-->
					
			<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
		</div>
		<!-- closes w1 -->
		<?php echo $this->partial('admin_partials/report.phtml', array()); ?>
		
<div class="hidden">
	<div class="lightbox-2" id="password-reset">
		<h2>Reset Password</h2>
		<h3>Do you want to reset the password to Karina Romaine</h3>
		<div class="buttons">
			<ul>
				<li><a href="" class="btn-1">Reset</a></li>
				<li><a href="" class="btn-10">Cancel</a></li>
			</ul>
		</div><!--BUTTONS-->
	</div><!--PASSWORD-RESET-->
</div><!--HIDDEN-->
	</body>
</html>