<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
		<title>Travelers</title>
        <link type="text/css" rel="stylesheet" href="/css5/reset.css" />
        <link type="text/css" rel="stylesheet" href="/css5/all.css" />
		<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
  		<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />
  		<!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
  		<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
  		<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
		<script type="text/javascript" src="/js2/jquery.js"></script>
		<script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.js"></script>
    	<script type="text/javascript" src="/js2/admin/traveller-view.js"></script>
			<script>
				$(document).ready(function() {
					$('a.lbc').fancybox({
						padding: 0,
						overlayColor: '#FFF',
						overlayOpacity: '0.7',
						showCloseButton: 'false',
					});
            		$("#report_tabs").tabs();
					
					panel(<?php echo $this->user->id?>, 1, 'partner');
				});
			</script>
		</head>
		<body>
			<div class="w1">
    		<?php echo $this->partial('admin_partials/header.phtml', array()); ?>
			<div class="w3_admin">
				<div class="sub_menu">
					<h2>Traverlers. <span>There are <?php echo $this->numCount?>.</span></h2>
					<a href="#new_partner" class="btn-1 lbc">Create a Partner</a>
					<ul class="sub_links">
						<li class="select"><a href="/admin/users/travellers">Travelers</a></li>
						<li><a href="/admin/users/partners">Partners</a></li>
					</ul>
				</div><!--SUB_MENU-->
            </div><!--W3-->
			<div class="all_listing">
				<div class="search_list">
					<form action="" onsubmit="return false">
						<input type="text" placeholder="Search Users by email" name="q" id="q" value="<?php echo $this->searchText?>" />
						<input type="button" class="btn-1" value="Search" onclick="searchSubmit()" />
					</form>
					<?php echo $this->paginationControl($this->paginator, 'Sliding', 'admin_partials/paginator.phtml', array('sort'=>$this->paramSort, 'seq'=>$this->paramSequence, 'q'=>$this->paramQuery)); ?>
				</div><!--SEARCH_LIST-->
				<div class="list_content">
					<table width="100%" border="0">
						<tr>
							<th width="160"><a href="<?php echo $this->url(array('sort'=>0, 'seq'=>$this->paramSort == 0 && $this->paramSequence !='desc' ? 'desc':'default'));?>">User Name</a></th>
							<th width="160"><a href="<?php echo $this->url(array('sort'=>1, 'seq'=>$this->paramSort == 1 && $this->paramSequence !='desc' ? 'desc':'default'));?>">E-mail</a></th>
							<th width="135"><a href="<?php echo $this->url(array('sort'=>2, 'seq'=>$this->paramSort == 2 && $this->paramSequence !='desc' ? 'desc':'default'));?>">Country</a></th>
							<th width="180"><a href="<?php echo $this->url(array('sort'=>3, 'seq'=>$this->paramSort == 3 && $this->paramSequence !='desc' ? 'desc':'default'));?>">City</a></th>
							<th width="70"><a href="<?php echo $this->url(array('sort'=>4, 'seq'=>$this->paramSort == 4 && $this->paramSequence !='desc' ? 'desc':'default'));?>">Age</a></th>
							<th width="105"><a href="<?php echo $this->url(array('sort'=>5, 'seq'=>$this->paramSort == 5 && $this->paramSequence !='desc' ? 'desc':'default'));?>">Reservations</a></th>
							<th width="65" class="last">&nbsp;</th>
						</tr>
						<?php foreach($this->paginator as $key=>$listing):?>
						<tr  <?php echo $key==0 ? 'class="first"' : ''?>>
							<td><?php echo $listing->name?></td>
							<td><?php echo $listing->email?></td>
							<td><?php echo $listing->countryName?></td>
							<td><?php echo $listing->cityName?></td>
							<td><?php echo $listing->age?></td>
							<td><?php echo $listing->reservationTotal?></td>
							<td><a href="/admin/users/view/traveller/<?php echo $listing->id?>" class="view">View</a></td>
						</tr>
                        <?php endforeach;?>
						
					</table>
				</div><!--LIST-CONTENT-->
				<div class="paging_bottom">
					<?php echo $this->paginationControl($this->paginator, 'Sliding', 'admin_partials/paginator.phtml', array('sort'=>$this->paramSort, 'seq'=>$this->paramSequence, 'q'=>$this->paramQuery)); ?>
				</div><!--PAGING_BOTTOM-->
			</div><!--ALL_LISTING-->
					
			<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
		</div>
		<!-- closes w1 -->
		<?php echo $this->partial('admin_partials/report.phtml', array()); ?>
		<div class="hidden">
			<div id="new_partner" class="lb">
            	<form name="partner-form" id="partner-form">
				<div class="top"><h3>Create Partner Account</h3></div><!--TOP-->
				<div class="cont">
					<ul>
						<li>
                        	<label>Company Name</label>
                            <input type="text" name="c_name" value="" />
                        </li>
                        <li> <div id="_c_name" class="errdiv" style="float:right; margin-right:30px; background: none repeat scroll 0 0 #FF0000; color: #FFFFFF;font-size: 10px;font-weight: bold; display:none"></div></li>
						<li><label>Company E-mail</label><input type="text" value="" name="c_email" /></li>
                        <li> <div class="errdiv" id="_c_email" style="float:right; margin-right:30px; background: none repeat scroll 0 0 #FF0000; color: #FFFFFF;font-size: 10px;font-weight: bold; display:none"></div></li>
						<li><label>Contact Name</label><input type="text" value="" name="cnt_name"/></li>
                        <li> <div class="errdiv" id="_cnt_name" style="float:right; margin-right:30px; background: none repeat scroll 0 0 #FF0000; color: #FFFFFF;font-size: 10px;font-weight: bold; display:none"></div></li>
						<li><label>Phone</label><input type="text" value="" class="code" name="phone"/><input type="text" value="" class="phone" /></li>
                        <li> <div class="errdiv" id="_phone" style="float:right; margin-right:30px; background: none repeat scroll 0 0 #FF0000; color: #FFFFFF;font-size: 10px;font-weight: bold; display:none"></div></li>
						<li><label>Website</label><input type="text" value="" name="website" /></li>
                        <li> <div class="errdiv" id="_website" style="float:right; margin-right:30px; background: none repeat scroll 0 0 #FF0000; color: #FFFFFF;font-size: 10px;font-weight: bold; display:none"></div></li>
						<li>
							<label>Country</label>
							<select name="country">
                            <option value="">Select Country</option>
							<?php foreach($this->countries as $country): ?>
                                <option value="<?php echo $country->id?>"><?php echo $country->title?></option>
							 <?php endforeach; ?>
							</select>
						</li>
                         <li> <div class="errdiv" id="_country" style="float:right; margin-right:30px; background: none repeat scroll 0 0 #FF0000; color: #FFFFFF;font-size: 10px;font-weight: bold; display:none"></div></li>

					</ul>
				</div><!--CONT-->
				<div class="bottom">
					<input type="button" id="c-vendor" class="btn-1" value="Create Account" onclick="/admin/users/venders/" />
					<a class="btn-10" onclick="$.fancybox.close()">Cancel</a>
				</div><!--BOTTOM-->
				</form>
            </div><!--NEW_PARTNER-->
			
		</div><!--HIDDEN-->
            
         <script>
		$('#c-vendor').click(function(){
			$('.errdiv').hide();
			$.ajax({ 
			   type: "POST", 
			   url: "/admin/vendors/add", 
			   data: $("#partner-form").serialize() ,
			   success: function(json, status){
				   if(json.attempt=='success'){
						$.fancybox.close();
						showAlert("Partner added successfully");
					   return;
				   }
				   
				   if(json.error_code == "validation_error"){
						$.each(json.data, function(i,validationError){ 
							$("#_" + validationError.field).show();
							$("#_" + validationError.field).text(validationError.message);
						});
				   }
			   }, 
			   error:function(jqXHR, textStatus, errorThrown){ 
					alert(textStatus);
			   }
			});
		});
			function searchSubmit(){
				location.href="<?php echo $this->baseUrl?>/" + $("#q").val();
			}
			$("#q").keypress(function(e) {
				var keycode;
				if (window.event) keycode = window.event.keyCode;
				else if (e) keycode = e.which;
				else return true;
				if (keycode == 13) {
				   location.href="<?php echo $this->baseUrl?>/" + $("#q").val();
				   return false;
				}
				else
				   return true;
			});
		</script>


	</body>
</html>