<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
		<title><?= $this->trip->title ?> - Admin | Tripfab.com</title>
        <link type="text/css" rel="stylesheet" href="/css5/reset.css" />
        <link type="text/css" rel="stylesheet" href="/css2/all.css" />
		<script type="text/javascript" src="/js2/jquery.js"></script>
		<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
  		<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />
  		<!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
  		<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
  		<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
		<script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.js"></script>
    	<script type="text/javascript" src="/js2/admin/traveller-view.js"></script>
			<script>
				$(document).ready(function() {
					$('a.lbc').fancybox({
						padding: 0,
						overlayColor: '#FFF',
						overlayOpacity: '0.7',
						showCloseButton: 'false',
					});
            		$("#report_tabs").tabs();
					
					panel(<?php echo $this->user->id?>, 1, 'partner');
				});
			</script>
		</head>
		<body>
			<div class="w1">
    		<?php echo $this->partial('admin_partials/header.phtml', array()); ?>
			<div class="w3_admin">
				<div class="sub_menu">
					<h2>Create. <span>New Trip.</span></h2>
					<a class="btn-10" href="" target="_blank">Trip Preview</a>		
				</div><!--SUB_MENU-->
            </div><!--W3-->
				
				<div id="trips" class="listing-wrapper wrapper">
					<div class="listing-content">
						<div class="left">
							<ul>
								<li class="current"><a href="<?php echo $this->url(array('page'=>1))?>">General Information</a></li>
								<li><a href="<?php echo $this->url(array('page'=>2))?>">Trip Facts</a></li>
								<li><a href="<?php echo $this->url(array('page'=>4))?>">Trip Details</a></li>
								<li><a href="<?php echo $this->url(array('page'=>5))?>">Itinerary</a></li>
							</ul>
						</div>
						<!-- closes left -->
						<div class="right">
							<?php if($this->successMessage): ?>
							<script type="text/javascript">
                                showAlert("Your changes have been saved");
                            </script>
                            <?php endif ?>	
            
                            <?php if(count($this->errors)) : ?>
                            <center>
                            <div style="border:1px solid red; margin-left:22px; margin-right:22px; margin-bottom:10px;">
                                <?php foreach($this->errors as $error):?>
                                    <p><?php echo $error;?></p>
                                <?php endforeach;?>
                            </div>
                            </center>
                            <?php endif;?>

                            
                            
                            <form name="f1" method="post" enctype="multipart/form-data">
							<div class="profile-items">
								<div class="item-wrppr">
									<h3>General Information <a href="/admin/trips" class="back">Back to Trips</a></h3>								
								</div>
								<!-- closes item-wrppr -->
								<div class="item-wrppr">
									<div class="item-ttl">
										Basic Information
									</div>
									<!-- closes item ttl -->
									<div class="item first">
										<input type="text" class="noclean" name="title" value="<?php echo $this->trip->title?>" />
										<h4>Trip Title</h4>
										<span>Your trip name</span>
									</div>
									<!-- closes item -->
									<div class="item">
										<textarea class="noclean" cols="30" rows="1" name="description"><?php echo $this->trip->description?></textarea>
										<h4>Trip Description</h4>
										<span>Write a nice description for your trip</span>
									</div>
									<!-- closes item -->
                                    <div class="item last">
										<input type="text" class="noclean" name="price" value="<?php echo $this->trip->price?>" />
										<h4>Price</h4>
										<span>Price for trip</span>
									</div>
									<!-- closes item -->

									<div class="clear"></div>									
								</div>
								<!-- closes item-wrppr -->
								<div class="item-wrppr">
									<div class="item-ttl">
										Trip Picture
									</div>
									<!-- closes item ttl -->
									<div class="item first last">
										<div class="picture">
											<img src="<?php echo $this->trip->image?>" alt="" />
											<input type="file" name="image" />
										</div>
										<h4>Picture Requirements</h4>
										<dl class="photo-limit">
											<dt>Photo Dimention</dt>
											<dd>640x425 pixels</dd>
											<dt>File size</dt>
											<dd>2MB or less</dd>
										</dl>
									</div>
									<!-- closes item -->
									<div class="clear"></div>
								</div>
								<!-- closes item-wrppr -->
								<div class="item-wrppr">
									<div class="item-ttl">
										Trip Information
									</div>
									<!-- closes item ttl -->
									<div class="item first">
										<div class="selects">
                                        	<!--<input type="text" class="noclean" name="days" value="<?php echo $this->trip->days?>"/>-->
                                        	<select class="days">
                                        		<option>7 Days</option>
                                        	</select>
                                        	<select class="days"> 
                                        		<option>6 Nights</option>
                                        	</select>
										</div>
										<!-- closes selects -->
										<h4>Duration (No. of days)</h4>
										<span>Description goes here</span>
									</div>
									<!-- closes item -->
									<div class="item">
										<div class="selects big">
											<select id="trip_country"  name="trip_country">
												<?php foreach($this->countries as $country):?>
                                                <option <?php echo $this->trip->country_id == $country->id ? ' selected' : ''; ?> value="<?php echo $country->id?>"><?php echo $country->title?></option>
                                                <?php endforeach;?>
											</select>
										</div>
										<!-- closes selects -->
										<h4>Country</h4>
										<span>Description goes here</span>
									</div>
									<!-- closes item -->
									<div class="item last">
										<div class="selects big">
											<select  id="trip_city1"  name="trip_city1">
												<option>Select City</option>
											</select>
											<select  id="trip_city2"  name="trip_city2">
												<option>Select City</option>
											</select>
											<select  id="trip_city3"  name="trip_city3">
												<option>Select City</option>
											</select>
											<select  id="trip_city4"  name="trip_city4">
												<option>Select City</option>
											</select>
											<select  id="trip_city5"  name="trip_city5">
												<option>Select City</option>
											</select>
										</div>
										<!-- closes selects -->
										<h4>Main Cities</h4>
										<span>Description goes here</span>
									</div>
									<!-- closes item -->
									<div class="clear"></div>									
								</div>
								<!-- closes item-wrppr -->
								<div class="item-wrppr">
									<div class="item-ttl">
										Highlights
									</div>
									<!-- closes item ttl -->
									<div class="item first">
										<input type="text" class="noclean" class="noclean" name="highlight[]" value="<?php echo @$this->highlights[0]->title?>"/>
										<textarea class="noclean" cols="30" rows="1" name="hDescription[]"><?php echo @$this->highlights[0]->text?></textarea>
										<h4>Highlight #1</h4>
										<span>Write the first highlight about the trip </span>
									</div>
									<!-- closes item -->
									<div class="item">
										<input type="text" class="noclean" name="highlight[]"  value="<?php echo @$this->highlights[1]->title?>"/>
										<textarea cols="30" class="noclean" rows="1" name="hDescription[]"><?php echo @$this->highlights[1]->text?></textarea>
										<h4>Highlight #2</h4>
										<span>Write the second highlight about the trip </span>
									</div>
									<!-- closes item -->
									<div class="item last">
										<input type="text" class="noclean" name="highlight[]" value="<?php echo @$this->highlights[2]->title?>"/>
										<textarea cols="30" class="noclean" rows="1" name="hDescription[]"><?php echo @$this->highlights[2]->text?></textarea>
										<h4>Highlight #3</h4>
										<span>Write the third highlight about the trip </span>
									</div>
									<!-- closes item -->
									<div class="clear"></div>									
								</div>
								<!-- closes item-wrppr -->
								<div class="foot">
								<input type="submit" class="btn-1" value="Save Changes" />
								<a href="">Delete Trip</a>
							</div>
							<!-- closes foot -->
							</div>
							<!-- closes profile-items -->
							</form>
                        </div>
						<!-- closes right -->
					</div>
					<!-- closes listing-content -->
				</div>
					
			<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
		</div>
		<!-- closes w1 -->
		<?php echo $this->partial('admin_partials/report.phtml', array()); ?>
        <script>
			var selectedCities = <?php echo $this->cities ?>;
			fillCityTrip($('#trip_country').val());
			$('select#trip_country').change(function(){
				fillCityTrip($('#trip_country').val());
			});
			
			
			function fillCityTrip(countryId){
				var url = "/ajax/places/?type=city&c=" + countryId;
				$("#trip_city1" ).children().remove();
				$("#trip_city2" ).children().remove();
				$("#trip_city3" ).children().remove();
				$("#trip_city4" ).children().remove();
				$("#trip_city5" ).children().remove();
				$("#trip_city1" ).append(new Option('Select City', 0, true, true));
				$("#trip_city2" ).append(new Option('Select City', 0, true, true));
				$("#trip_city3" ).append(new Option('Select City', 0, true, true));
				$("#trip_city4" ).append(new Option('Select City', 0, true, true));
				$("#trip_city5" ).append(new Option('Select City', 0, true, true));
				var selected = false;
				$.getJSON(url, function(fsdata) {
					$.each(fsdata.data, function(i,city){ 
						
						selected = false;
						if(typeof selectedCities[0] != "undefined"){ selected = selectedCities[0].city_id == city.id ? true : false ;}
						$("#trip_city1" ).append(new Option(city.title, city.id, true, selected));
						
						selected = false;
						if(typeof selectedCities[1] != "undefined"){ selected = selectedCities[1].city_id == city.id ? true : false ;}
						$("#trip_city2" ).append(new Option(city.title, city.id, true, selected));
						
						selected = false;
						if(typeof selectedCities[2] != "undefined"){ selected = selectedCities[2].city_id == city.id ? true : false ;}
						$("#trip_city3" ).append(new Option(city.title, city.id, true, selected));
						
						selected = false;
						if(typeof selectedCities[3] != "undefined"){ selected = selectedCities[3].city_id == city.id ? true : false ;}
						$("#trip_city4" ).append(new Option(city.title, city.id, true, selected));
						
						selected = false;
						if(typeof selectedCities[4] != "undefined"){ selected = selectedCities[4].city_id == city.id ? true : false ;}
						$("#trip_city5" ).append(new Option(city.title, city.id, true, selected));
						
					});
				});	
			}
				
		
		</script>
	</body>
</html>