<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
		<title><?= $this->trip->title ?> - Admin | Tripfab.com</title>
        <link type="text/css" rel="stylesheet" href="/css5/reset.css" />
        <link type="text/css" rel="stylesheet" href="/css2/all.css" />
		<script type="text/javascript" src="/js2/jquery.js"></script>
		<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
  		<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />
  		<!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
  		<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
  		<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]--> 
    	<script type="text/javascript" src="/js2/admin/traveller-view.js"></script>
			<script type="text/javascript">
				$(document).ready(function() {
					$('a.lbc').fancybox({
						padding: 0,
						overlayColor: '#FFF',
						overlayOpacity: '0.7',
						showCloseButton: 'false',
					});
            		$("#report_tabs").tabs();
					
					panel(<?php echo $this->user->id?>, 1, 'partner');
				});
			</script>
		</head>
		<body>
			<div class="w1">
    		<?php echo $this->partial('admin_partials/header.phtml', array()); ?>
			
			<div class="w3_admin">
				<div class="sub_menu">
					<h2>Create. <span>New Trip.</span></h2>
					<a class="btn-10" href="" target="_blank">Trip Preview</a>						
				</div><!--SUB_MENU-->
            </div><!--W3-->
				
				<div id="trips" class="listing-wrapper wrapper">
					<div class="listing-content">
						<div class="left">
							<ul>
								<li><a href="<?php echo $this->url(array('page'=>1))?>">General Information</a></li>
								<li><a href="<?php echo $this->url(array('page'=>2))?>">Trip Facts</a></li>
								<li class="current"><a href="<?php echo $this->url(array('page'=>3))?>">Photos</a></li>
								<li><a href="<?php echo $this->url(array('page'=>4))?>">Trip Details</a></li>
								<li><a href="<?php echo $this->url(array('page'=>5))?>">Itinerary</a></li>
							</ul>
						</div>
						<!-- closes left -->
						<div class="right">
							<?php if($this->successMessage): ?>
							<script type="text/javascript">
                                showAlert("Your changes have been saved");
                            </script>
                            <?php endif ?>	
            
                            <?php if(count($this->errors)) : ?>
                            <center>
                            <div style="border:1px solid red; margin-left:22px; margin-right:22px; margin-bottom:10px;">
                                <?php foreach($this->errors as $error):?>
                                    <p><?php echo $error;?></p>
                                <?php endforeach;?>
                            </div>
                            </center>
                            <?php endif;?>

                            
                            
                            <form name="f1" method="post" enctype="multipart/form-data">
                                <div class="profile-items">
                                    <div class="item-wrppr">
                                        <h3>Photos <a href="/admin/trips" class="back">Back to Trips</a></h3>								
                                    </div>
                                    <!-- closes item-wrppr -->
                                    <div class="item-wrppr">
                                        <h4 class="photo_tittle">Picture Requirements</h4>
                                        <dl class="photo-limit two">
                                            <dt>Photo Dimention</dt>
                                            <dd>640x425 pixels</dd>
                                            <dt>File size</dt>
                                            <dd>2MB or less</dd>
                                        </dl>
                                        <a href="" class="btn-1">Upload Photos</a>
                                    </div>
                                    <!-- closes item -->
                                    
                                    <div class="item-wrppr">
                                        <div class="pht">
                                            <div class="image">
                                                <img width="132" height="98" src="https://developer.tripfab.com/images6/home_pic1.jpg" alt="" />
                                            </div><!--IMAGE-->
                                            
                                            <div class="info">
                                                <strong>Photo Description</strong>
                                                <input type="text" name="" value="" />
                                                <a href="" class="remove">Remove Picture</a>
                                            </div><!--INFO-->
                                            
                                        </div><!--PHOTO-->
                                    </div><!-- closes item-wrppr -->
                                    
                                    <div class="item-wrppr">
                                        <div class="pht">
                                            <div class="image">
                                                <img width="132" height="98" src="https://developer.tripfab.com/images6/home_pic1.jpg" alt="" />
                                            </div><!--IMAGE-->
                                            
                                            <div class="info">
                                                <strong>Photo Description</strong>
                                                <input type="text" name="" value="" />
                                                <a href="" class="remove">Remove Picture</a>
                                            </div><!--INFO-->
                                            
                                        </div><!--PHOTO-->
                                    </div><!-- closes item-wrppr -->
                                                                
                                    
                                    
                                    
                
                                    <div class="foot">
                                        <input type="submit" class="btn-1" value="Save Changes" />
                                        <a href="">Delete Trip</a>
                                    </div>
                                    <!-- closes foot -->
                                </div>
                                <!-- closes profile-items -->
							</form>
						</div>
						<!-- closes right -->
					</div>
					<!-- closes listing-content -->
				</div>
					
			<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
		</div>
		<!-- closes w1 -->
		<?php echo $this->partial('admin_partials/report.phtml', array()); ?>
        
        <script>
		function removeElement(elm, divName){
			var d = document.getElementById(divName);
  			d.removeChild(elm.parentNode);
		}
		
		function addElement(divName, inclusion){
			var d = document.getElementById(divName);
			var html = '<div>';
			html += '<a href="javascript://" class="remove" name="delete" onclick="removeElement(this, \'' + divName + '\')">remove</a>';
			if(inclusion){
				html += '<textarea cols="" rows="" name="inclusion[]"  class="noclean"></textarea>';
				html += '<input type="hidden" name="iid[]" value="0"/>';
			}
			else{
				html += '<textarea cols="" rows="" name="exclusion[]"  class="noclean"></textarea>';
				html += '<input type="hidden" name="eid[]" value="0"/>';
			}
			html += '<div class="clear"></div>';
			html += '</div>';
			
			$('#'+ divName).append(html);
		}
		</script>
	</body>
</html>