<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
		<title><?= $this->trip->title ?> - Admin | Tripfab.com</title>
        <link type="text/css" rel="stylesheet" href="/css5/reset.css" />
        <link type="text/css" rel="stylesheet" href="/css2/all.css" />
		<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
  		<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />
  		<!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
  		<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
  		<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
		<script type="text/javascript" src="/js2/jquery.js"></script>
       	<script>
			$(document).ready(function() {
				$('a.lbc').fancybox({
					padding: 0,
					overlayColor: '#FFF',
					overlayOpacity: '0.7',
					showCloseButton: 'false',
				});
				$("#report_tabs").tabs();
				$('.carrousel').accordion({
					autoHeight: false 
				});
				
				$('#activate .btn-1').click(function(){
					$id = $(this).parents('form').find('input[name=tripid]').val();
					$action = 1;
					$.ajax({
						url:'/ajax/tripstatus',
						type:'post',
						data: {
							id:$id,
							act:$action,
						},
						success:function(res){
							if(res == 'success') {
								$.cookie('alert','Changes saved');
								window.location.reload();
							} else {
								showError('Something went wrong');
							}
						},
						error:function(){
							showError('Something went wrong');
						}
					});
				});
				
				$('#deactivate .btn-1').click(function(){
					$id = $(this).parents('form').find('input[name=tripid]').val();
					$action = 0;
					$.ajax({
						url:'/ajax/tripstatus',
						type:'post',
						data: {
							id:$id,
							act:$action,
						},
						success:function(res){
							if(res == 'success') {
								$.cookie('alert','Changes saved');
								window.location.reload();
							} else {
								showError('Something went wrong');
							}
						},
						error:function(){
							showError('Something went wrong');
						}
					});
				});
			});
		</script>

	</head>
	<body>
		<div class="w1">
    		<?php echo $this->partial('admin_partials/header.phtml', array()); ?>
			<div class="w3_admin">
				<div class="sub_menu">
					<h2>
					<?php if($this->trip->active == 1): ?>
                    <span class="lstngActv">Active</span>
                    <?php else: ?>
                    <span class="lstngInct">Inactive</span>
                    <?php endif ?>
                    Create. <span>New Trip.</span></h2>
					<a class="btn-10" href="/admin/trips/preview/<?php echo $this->trip->id?>" target="_blank">Trip Preview</a>		
                    <a href="#activate" class="btn-10 act lbc" id="act-btn-342"<?php echo $this->trip->active ? 'style="display:none"' : '';?> >Activate Trip</a>
            		<a href="#deactivate" class="btn-10 deact lbc" id="deact-btn-342" <?php echo !$this->trip->active ? 'style="display:none"' : '';?>>Deactivate Trip</a>
					
				</div><!--SUB_MENU-->
            </div><!--W3-->
				
				<div id="trips" class="listing-wrapper wrapper">
					<div class="listing-content">
						<div class="left">
							<ul>
								<li><a href="<?php echo $this->url(array('page'=>1))?>">General Information</a></li>
								<li class="current"><a href="<?php echo $this->url(array('page'=>2))?>">Trip Facts</a></li>
								<li><a href="<?php echo $this->url(array('page'=>3))?>">Photos</a></li>
								<li><a href="<?php echo $this->url(array('page'=>4))?>">Trip Details</a></li>
								<li><a href="<?php echo $this->url(array('page'=>5))?>">Itinerary</a></li>
							</ul>
						</div>
						<!-- closes left -->
						<div class="right">

							<?php if($this->successMessage): ?>
							<script type="text/javascript">
                                showAlert("Your changes have been saved");
                            </script>
                            <?php endif ?>	
            
                            <form name="f1" method="post">
							<div class="profile-items">
								<div class="item-wrppr">
									<h3>Trip Facts <a href="https://developer.tripfab.com/admin/trips" class="back">Back to Trips</a></h3>								
								</div>
								<!-- closes item-wrppr -->
								
                                <?php foreach($this->facts as $fact): ?>
                                  <?php if($fact['multi']):?>
                                    <div class="item-wrppr">
                                        <div class="item-ttl">
                                            <h4><?php echo $fact['title']?><span>Write the first paragraph</span></h4>
                                        </div><!-- closes item ttl -->									
                                        <div class="facts-item" id="d<?php echo $fact['id']?>">
                                            <?php $totalItems = count($fact['facts']); $ctr = 1;?>
                                            <?php foreach($fact['facts'] as $item):?>
                                                <?php  if($ctr++ > 3):?>
                                            		<div class="rmv"><input type="text" name="fact[<?php echo $fact['id']?>][]" value="<?php echo $item->text?>"/><a href="javascript://" class="remove"></a></div>
                                                <?php else:?>
                                                    <input type="text" name="fact[<?php echo $fact['id']?>][]" value="<?php echo $item->text?>"/>
												<?php endif;?>
                                            <?php endforeach;?>
                                            <?php for(; $ctr<5; $ctr++):?> 
                                                <?php  if($ctr > 3):?>
                                            		<div class="rmv"><input type="text" name="fact[<?php echo $fact['id']?>][]" placeholder="Write an item"/><a href="javascript://" class="remove"></a></div>
                                                <?php else:?>
                                                    <input type="text" name="fact[<?php echo $fact['id']?>][]" placeholder="Write an item"/>
												<?php endif;?>
                                           <?php endfor;?>
                                        </div><!--FACTS-ITEM-->
                                        <div class="add-p">
                                        <a class="add-para-l" identifier="<?php echo $fact['id']?>" href="javascript://">Write New item</a>
                                        </div>
                                        <div class="clear"></div>
                                    </div>
                                    <!-- closes item-wrppr -->
                                    
                                  <?php else :?>
                                    <div class="item-wrppr">
                                        <div class="item-ttl">
                                            <h4><?php echo $fact['title']?> <span>Write the first paragraph</span></h4>
                                        </div><!-- closes item ttl -->									
                                        <div class="facts-item">
                                            <textarea cols="" rows="" name="fact[<?php echo $fact['id']?>][]"><?php echo @$fact['facts'][0]->text?></textarea>
                                        </div><!--FACTS-ITEM-->
    
                                        <div class="clear"></div>									
                                    </div>
                                    <!-- closes item-wrppr -->
                                    
                                   <?php endif;?>
								<?php endforeach;?>
								
                                <div class="foot">
								<input type="submit" class="btn-1" value="Save Changes">
								<a href="">Delete Trip</a>
                                </div>
                                <!-- closes foot -->

                                
                                
                                
							</div>
                            <!-- close profile-items -->
							</form>

                        </div>
						<!-- closes right -->
					</div>
					<!-- closes listing-content -->
				</div>
				<!-- closes listing-wrapper -->
					
			<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
			<?php echo $this->partial('admin_partials/trip.phtml', array('title'=>$this->trip->title, 'tripId'=>$this->trip->id)); ?>
		</div>
		<!-- closes w1 -->
		<?php echo $this->partial('admin_partials/report.phtml', array()); ?>
        
        <script type="text/javascript">
        	$('.remove').live('click',function(){
				$(this).parent("div:first").remove();
			});
			
        	$('.add-para-l').live('click',function(){
				var identifier = $(this).attr("identifier");
		      	html ='  <div class="rmv"><input type="text" name="fact[' + identifier + '][]" placeholder="Write an item"/><a href="javascript://" class="remove"></a></div>';
				$("#d" + identifier).append(html);
			});
        </script>
	</body>
</html>