<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
		<title>Trips</title>
        <link type="text/css" rel="stylesheet" href="/css5/reset.css" />
        <link type="text/css" rel="stylesheet" href="/css5/all.css" />
		<script type="text/javascript" src="/js2/jquery.js"></script>
		<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
  		<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />
  		<!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
  		<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
  		<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]--> 
		<script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.js"></script>
    	<script type="text/javascript" src="/js2/admin/place-edit.js"></script>
			<script>
				$(document).ready(function() {
					$('a.lbc').fancybox({
						padding: 0,
						overlayColor: '#FFF',
						overlayOpacity: '0.7',
						showCloseButton: 'false',
					});
            		$("#report_tabs").tabs();
					
				});
			</script>
	</head>
	<body>
		<div class="w1">
    		<?php echo $this->partial('admin_partials/header.phtml', array()); ?>
			
			<div class="w3_admin">
				<div class="sub_menu">
					<h2>Create. <span>New Trip.</span></h2>
					<a href="#" class="back">Back to Trips</a>
				</div><!--SUB_MENU-->
            </div><!--W3-->
			<form id="tripEdit" name="tripEdit" method="POST" action="/admin/trip4edit/"/>
				<div id="trips" class="listing-wrapper wrapper">
					<div class="listing-content">
						<div class="left">
							<ul>
							<ul>
								<li><a href="<?php echo $this->url(array('page'=>1))?>">General Information</a></li>
								<li><a href="<?php echo $this->url(array('page'=>2))?>">Trip Facts</a></li>
								<li><a href="<?php echo $this->url(array('page'=>4))?>">Trip Details</a></li>
								<li class="current"><a href="<?php echo $this->url(array('page'=>5))?>">Itinerary</a></li>
							</ul>
							</ul>
						</div>
						<!-- closes left -->
						<div class="right">
							<?php if($this->successMessage): ?>
							<script type="text/javascript">
                                showAlert("Your changes have been saved");
                            </script>
                            <?php endif ?>	
            
                            <?php if(count($this->errors)) : ?>
                            <center>
                            <div style="border:1px solid red; margin-left:22px; margin-right:22px; margin-bottom:10px;">
                                <?php foreach($this->errors as $error):?>
                                    <p><?php echo $error;?></p>
                                <?php endforeach;?>
                            </div>
                            </center>
                            <?php endif;?>
							<div class="lstng-details">
								<h3 class="title">Edit Itinerary</h3>
								<div class="block">
									<div class="item-ttl">Schedule</div>
									<div class="item">
										<p class="descrip name">
										
											<strong>Listing Name</strong>
											Write the name of the listing
										</p>
										<input name="title" value="<?php echo @$itineraries->title ?>" class="name-in" type="text">
									</div><!---ITEM-->
									<div class="item">
										<p class="descrip">
											<strong>Listing Type</strong>
											Select the type of listing 
										</p>
										<select name="activity">
											<option selected="selected">Activity</option>
										</select>
									</div><!---ITEM-->
									
									<div class="item">
										<p class="descrip">
											<strong>select country</strong>
											 
										</p>
										<select id="trip_country"  name="trip_country">
												<?php foreach($this->countries as $country):?>
                                                <option <?php echo @$itineraries->country_id == $country->id ? ' selected' : ''; ?> value="<?php echo @$country->id?>"><?php echo $country->title?></option>
                                                <?php endforeach;?>
										</select>
									</div><!---ITEM-->
									
									<div class="item">
										<p class="descrip">
											<strong>select city</strong>
											 
										</p>
										<select  id="trip_city1"  name="trip_city1">
											<option selected="selected">City</option>
										</select>
									</div><!---ITEM-->

									<div class="item">
										<p class="descrip">
											<strong>Itinerary Day</strong>
											Select the day of the activity 
										</p>
										<select name="days">
                                       		<option><?php echo @$itineraries->day?></option>
										</select>
									</div><!---ITEM-->
									
									<div class="item">
										<p class="descrip">
											<strong>Duration</strong>
											Select how many days long
										</p>
										<select value="duration">
											<option selected="selected" value="<?php echo @$itineraries->duration?>" ><?php echo @$itineraries->duration?></option>
										</select>
										
									</div><!---ITEM-->
									
									<div class="item">
										<p class="descrip">
											<strong>Starting Hour</strong>
											Select the hour activity starts
										</p>
										<select class="time" name="">
											<option selected="selected">AM</option>
										</select>
										<select class="hour" name="start">
											<option selected="selected"><?php echo @$itineraries->start?></option>
										</select>
									</div><!---ITEM-->
									
									<div class="item">
										<p class="descrip">
											<strong>Ending Hour</strong>
											Select the hour activity ends
										</p>
										<select class="time">
											<option selected="selected">AM</option>
										</select>
										<select class="hour" name="end">
											<option selected="selected" ><?php echo @$itineraries->end ?></option>
										</select>
									</div><!---ITEM-->
									
									<div class="item last">
										<p class="descrip"><input value="" type="checkbox">Show this activity in the main page of the trip</p>
										
									</div><!---ITEM-->
									
								</div><!--BLOCK-->
								
								<div class="block">
									<h3 class="item-ttl">Description</h3>
									<div class="item">
										<div class="description_l">
											<textarea rows="" cols="" name="description"><?php echo @$itineraries->description ?></textarea>
										</div>
									</div><!--ITEM-->
								</div><!--BLOCK-->
								
								<div class="block">
									<h3 class="item-ttl">Picture</h3>
									<div class="item">
										<table width="470" border="0">
											<tbody><tr>
												
												<td width="270">
													<h4>Picture Requeriments</h4>
													<dl class="photo-limit">
														<dt>Upload limit</dt>
														<dd>10 photos per listing</dd>
														<dt>Photo Dimention</dt>
														<dd>640x425 pixels</dd>
														<dt>File size</dt>
														<dd>2MB or less</dd>
													</dl>
												</td>
												<td class="picture" width="180">
													<img src="<?php echo @$itineraries->image?>"  alt="" width="68" height="68">
													<input type="file" name="image">
												</td>
											</tr>
										</tbody></table>
									</div><!--ITEM-->
								</div><!--BLOCK-->
								<div class="block">
									<div class="single last">
										<p class="item-ttl">Map</p>
										<input type="button" class="btn-10" value="Set Location" />
										<input type="text" class="location" value="" />
										<div class="map">
											<div class="map_holder">
												<img src="/images2/map-result.gif" width="500" height="265" alt="" />

											</div>
										</div><!--MAP-->
									</div><!--single-->								</div><!--BLOCK-->
								
							</div>
							<!-- closes lstng-details -->
							<div class="foot">
								<input class="btn-1" value="Save Changes" type="submit">
							</div>
							<!-- closes foot -->
						</div>
						<!-- closes right -->
					</div>
					<!-- closes listing-content -->
				</div>
					
			<div class="footer black">
				<div class="wrapper">
					<a href="" class="logo">Tripfab</a>
				</div><!--WRAPPER-->
			</div>
			<!-- closes footer -->
		</div>
		<!-- closes w1 -->

        <script>
			var selectedCities = <?php echo $this->cities ?>;
			fillCityTrip($('#trip_country').val());
			$('select#trip_country').change(function(){
				fillCityTrip($('#trip_country').val());
			});
			
			
			function fillCityTrip(countryId){
				var url = "/ajax/places/?type=city&c=" + countryId;
				$("#trip_city1" ).children().remove();
				$("#trip_city1" ).append(new Option('Select City', 0, true, true));
				var selected = false;
				$.getJSON(url, function(fsdata) {
					$.each(fsdata.data, function(i,city){ 
						
						selected = false;
						if(typeof selectedCities[0] != "undefined"){ selected = selectedCities[0].city_id == city.id ? true : false ;}
						$("#trip_city1" ).append(new Option(city.title, city.id, true, selected));
						
						
					});
				});	
			}
				
		
		</script>

</body></html>