<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
	<head>
		<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
		<title><?= $this->trip->title ?> - Admin | Tripfab.com</title>
        <link type="text/css" rel="stylesheet" href="/css5/reset.css" />
        <link type="text/css" rel="stylesheet" href="/css2/all.css" />
		<script type="text/javascript" src="/js2/jquery.js"></script>
		<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
  		<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />
  		<!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
  		<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
  		<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]--> 
    	<script type="text/javascript" src="/js2/admin/traveller-view.js"></script>
			<script type="text/javascript">
				$(document).ready(function() {
					$('a.lbc').fancybox({
						padding: 0,
						overlayColor: '#FFF',
						overlayOpacity: '0.7',
						showCloseButton: 'false',
					});
            		$("#report_tabs").tabs();
					
					panel(<?php echo $this->user->id?>, 1, 'partner');
				});
			</script>
		</head>
		<body>
			<div class="w1">
    		<?php echo $this->partial('admin_partials/header.phtml', array()); ?>
			
			<div class="w3_admin">
				<div class="sub_menu">
					<h2>Create. <span>New Trip.</span></h2>
					<a class="btn-10" href="/admin/trips/preview/<?php echo $this->trip->id?>" target="_blank">Trip Preview</a>					
				</div><!--SUB_MENU-->
            </div><!--W3-->
				
				<div id="trips" class="listing-wrapper wrapper">
					<div class="listing-content">
						<div class="left">
							<ul>
								<li><a href="<?php echo $this->url(array('page'=>1))?>">General Information</a></li>
								<li><a href="<?php echo $this->url(array('page'=>2))?>">Trip Facts</a></li>
								<li><a href="<?php echo $this->url(array('page'=>3))?>">Photos</a></li>
								<li class="current"><a href="<?php echo $this->url(array('page'=>4))?>">Trip Details</a></li>
								<li><a href="<?php echo $this->url(array('page'=>5))?>">Itinerary</a></li>
							</ul>
						</div>
						<!-- closes left -->
						<div class="right">
							<?php if($this->successMessage): ?>
							<script type="text/javascript">
                                showAlert("Your changes have been saved");
                            </script>
                            <?php endif ?>	
            
                            <?php if(count($this->errors)) : ?>
                            <center>
                            <div style="border:1px solid red; margin-left:22px; margin-right:22px; margin-bottom:10px;">
                                <?php foreach($this->errors as $error):?>
                                    <p><?php echo $error;?></p>
                                <?php endforeach;?>
                            </div>
                            </center>
                            <?php endif;?>

                            
                            
                            <form name="f1" method="post" enctype="multipart/form-data">
							<div class="profile-items">
								<div class="item-wrppr">
									<h3>Inclusions <a href="/admin/trips" class="back">Back to Trips</a></h3>									
								</div>
								<div class="lstng-detail faq">
									<table width="100%" border="0">
										<tr>
											<td width="150">
												<strong>Inclusions</strong>
												<span>Write the inclusions<br /> around the whole trip</span>
											</td>
											<td width="590">
											<div id="inclusion">
											<?php foreach($this->includes as $key=>$include):?>
                                            	<div>
                                                <?php if($key != 0):?>
                                                	<a href="javascript://" class="remove" onclick="removeElement(this, 'inclusion')">remove</a>
                                                <?php endif; ?>
                                                <textarea cols="" rows="" name="inclusion[]" class="noclean"><?php echo $include->text ?></textarea>
                                                <input type="hidden" name="iid[]" value="<?php echo @$include->id ?>"/>
                                                <div class="clear"></div>
                                                </div>
											<?php endforeach; ?>
                                            </div>
											<a href="javascript://" class="link-5" onclick="addElement('inclusion', true);">Add a new inclusion</a>
											</td>
										</tr>
									</table>
								</div>
								<!-- closes lstng-detail -->
								<div class="lstng-detail faq last">								
									<table width="100%" border="0">
										<tr>
											<td width="150">
												<strong>Exclusions</strong>
												<span>Write the exclusions<br /> around the whole trip</span>
											</td>
											<td width="590">
											<div id="exclusion">
											<?php foreach($this->excludes as $key=>$exclude):?>
                                                <div>
												<?php if($key != 0):?>
                                                	<a href="javascript://" class="remove" name="delete" onclick="removeElement(this, 'exclusion')">remove</a>
                                                <?php endif; ?>
												<textarea cols="" rows="" name="exclusion[]" class="noclean"><?php echo $exclude->text ?></textarea>
                                                <input type="hidden" name="eid[]" value="<?php echo $exclude->id ?>"/>
												<div class="clear"></div>
                                                </div>
											<?php endforeach; ?>
                                            </div>
											<a href="javascript://" onclick="addElement('exclusion', false);" class="link-5">Add a new exclusion</a>
											</td>
										</tr>
									</table>
								</div>
								<!-- closes lstng-detail -->
							</div>
							<!-- closes lstng-details -->
							<div class="foot">
								<input type="submit" class="btn-1" value="Save Changes" />
								<a href="">Deactivate Listing</a>
							</div>
							<!-- closes foot -->
							</form>
						</div>
						<!-- closes right -->
					</div>
					<!-- closes listing-content -->
				</div>
					
			<?php echo $this->partial('admin_partials/footer.phtml', array()); ?>
		</div>
		<!-- closes w1 -->
		<?php echo $this->partial('admin_partials/report.phtml', array()); ?>
        
        <script>
		function removeElement(elm, divName){
			var d = document.getElementById(divName);
  			d.removeChild(elm.parentNode);
		}
		
		function addElement(divName, inclusion){
			var d = document.getElementById(divName);
			var html = '<div>';
			html += '<a href="javascript://" class="remove" name="delete" onclick="removeElement(this, \'' + divName + '\')">remove</a>';
			if(inclusion){
				html += '<textarea cols="" rows="" name="inclusion[]"  class="noclean"></textarea>';
				html += '<input type="hidden" name="iid[]" value="0"/>';
			}
			else{
				html += '<textarea cols="" rows="" name="exclusion[]"  class="noclean"></textarea>';
				html += '<input type="hidden" name="eid[]" value="0"/>';
			}
			html += '<div class="clear"></div>';
			html += '</div>';
			
			$('#'+ divName).append(html);
		}
		</script>
	</body>
</html>