<h3 class="title">Listings <a href="" class="back">Back to Partners</a></h3>
<div class="block">
<?php if(count($this->listings)): ?>
	<?php foreach($this->listings as $listing) : ?>
    <div class="single_trip">
        <table width="520" border="0" class="info">
            <tr>
                <td width="180"><?php echo $listing->type_name?></td>
                <td width="340"><?php echo $listing->title?></td>
            </tr>
            <tr>
                <td width="180">Activity Code</td>
                <td width="340"><?php echo $listing->id?></td>
            </tr>
            <tr>
                <td width="180">Locations</td>
                <td width="340"><?php echo $listing->address?> <?php echo $listing->address ? ', ' : '' ?><?php echo $listing->country_name?></td>
            </tr>
            <tr>
                <td width="180">Status</td>
                <td width="340"><?php echo $listing->status==1 ? 'Active' : 'Inactive'?></td>
            </tr>
            <tr>
                <td width="180">Reservations</td>
                <td width="340"><?php echo $listing->reservationTotal?></td>
            </tr>
            <tr>
                <td width="180"></td>
                <td width="340"><a href="/admin/listings/edit/<?php echo $listing->id?>">Edit Listing</a></td>
            </tr>
        </table>
    </div><!--SINGLE_TRIP-->
    
    <?php endforeach;?>
<?php else: ?>
	<center><h1>There is no listing in this account.</h1></center>
<?php endif;?>
</div><!--BLOCK-->
