<h3 class="title">Offers <a href="" class="back">Back to Partners</a></h3>
<div class="block">
<?php if(count($this->offers)): ?>
	<?php foreach($this->offers as $offer) : ?>
    <div class="single_trip">
        <table width="360" border="0" class="info">
            <tr>
                <td width="180"><?php echo $offer->type_name?></td>
                <td width="180"><?php echo $offer->type_name?></td>
            </tr>
            <tr>
                <td width="180">Listing Code</td>
                <td width="180"><?php echo $offer->listing_id?></td>
            </tr>
            <tr>
                <td width="180">Traveler Name</td>
                <td width="180">????</td>
            </tr>
            <tr>
                <td width="180">Offers Starts</td>
                <td width="180"><?php echo date('M d, Y', strtotime($offer->start))?></td>
            </tr>
            <tr>
                <td width="180">Offers Ends</td>
                <td width="180"><?php echo date('M d, Y', strtotime($offer->end))?></td>
            </tr>
            <tr>
                <td width="180">People Requeriments</td>
                <td width="180"><?php echo $offer->people_ammount?> <?php echo $offer->people?></td>
            </tr>
        </table>
        <table width="360" border="0" class="info">
            <tr>
                <td width="180">Discount Percent</td>
                <td width="180"><?php echo ($offer->regular / 100)* $offer->price; ?></td>
            </tr>
            <tr>
                <td width="180">Regular Pricing</td>
                <td width="180"><?php echo $offer->regular?></td>
            </tr>
            <tr>
                <td width="180">Special Rate</td>
                <td width="180">$<?php echo $offer->price?></td>
            </tr>
        </table>
    </div><!--SINGLE_TRIP-->
    <?php endforeach;?>
<?php else: ?>
	<center><h1>There is no offer in this account.</h1></center>
<?php endif;?>
</div><!--BLOCK-->
