<form id="general" name="general" method="POST" action="/admin/users/view/partner/<?php echo $this->user->id ?>">
<div class="single_trip">
    <div class="image"><img src="<?php echo $this->user->image?>" width="134" height="134" alt="" /></div><!--IMAGE-->
    <table width="520" border="0" class="info">
        <tr>
            <td width="180">Company Name</td>
			<td width="340"><input type="text"  name="name" value="<?php echo $this->user->name?>" /></td>
        </tr>
        <tr>
            <td width="180">E-mail</td>
			<td width="340"><input type="text" name="email" value="<?php echo $this->user->email?>" /></td>
        </tr>
        <tr>
            <td width="180">Contact Name</td>
			<td width="340"><input type="text" name="contact_name" value="<?php echo $this->user->contact_name?>" /></td>
        </tr>
        <tr>
            <td width="180">Partner Since</td>
			<td width="340"><input type="text" name="created" value="<?php echo date('M d, Y', strtotime($this->user->created))?>" /></td>
        </tr>
        <tr>            
            <td width="180">Country</td>
			<td width="340">
             <select id="country"  name="country">
                    <?php foreach($this->countries as $country):?>
                    <option <?php echo $this->user->country_id == $country->id ? ' selected="selected"' : ''; ?> value="<?php echo @$country->id?>"><?php echo $country->title?></option>
                    <?php endforeach;?>
            </select>
            </td>
        </tr>
        <tr>
            <td width="180">City</td>
			<td width="340">           
                    <select  id="city"  name="city">
                        <option selected="selected">City</option>
                    </select>
			</td>
        </tr>
        <tr>
            <td width="180">Phone</td>
			<td width="340"><input type="text" name="phone" value="<?php echo $this->user->phone?>" /></td>
        </tr>
        <tr>
            <td width="180">Website</td>
			<td width="340"><input type="text" name="website" value="<?php echo $this->user->website?>" /></td>
        </tr>
    </table>
</div><!--SINGLE_TRIP-->
<input type="hidden" name="user_id" value="<?php echo $this->user->user_id ?>"/>
<input class="btn-1" type="submit" onclick="/admin/users/view/partner/<?php echo $this->user->id ?>" value="Upadate"/>
</form>
<script>
		var cityId = '<?php echo $this->city;?>';
		fillCityTrip($('#country').val());
		screenUpdate();
		$('select#country').change(function(){
			fillCityTrip($('#country').val());
		});
		
		$('select#type').change(function(){
			screenUpdate();
		});
		
		function screenUpdate(){
			if($('#type').val() == 5){
				$("#field-wrapper").hide();
			}
			else{
				$("#field-wrapper").show();
			}
		}
		
		function fillCityTrip(countryId){
			var url = "/ajax/places/?type=city&c=" + countryId;
			$("#city" ).children().remove();
			$("#city" ).append(new Option('Select City', 0, true, true));
			var selected = false;
			$.getJSON(url, function(fsdata) {
				$.each(fsdata.data, function(i,city){ 
					selected = cityId == city.id ? true : false ;
					$("#city" ).append(new Option(city.title, city.id, true, selected));
					
					
				});
			});	
		}
				
		</script>
