<h3 class="title">Reviews <a href="/admin/users/travellers" class="back">Back to Travelers</a></h3>
<div class="block">
<?php if(count($this->reviewes)): ?>
	<?php foreach($this->reviewes as $review) : ?>
    
    <div class="single_trip">
        <table width="520" border="0" class="info">
            <tr>
                <td width="180">Listing</td>
                <td width="340"><?php echo $review->listing_name?></td>
            </tr>
            <tr>
                <td>Review</td>
                <td>
                    <p>
                   <?php echo $review->text?>
                    </p>
                </td>
            </tr>
            <tr>
                <td>Date</td>
                <td><?php echo date('M d, Y', strtotime($review->created))?></td>
            </tr>
        </table>
    </div><!--SINGLE_TRIP-->
    <?php endforeach;?>
<?php else: ?>
	<center><h1>User haven't made any review yet.</h1></center>
<?php endif;?>
</div><!--BLOCK-->
