<style type="text/css">
.hidden { display:none;}
.lstng-detail { position:relative;}
.lstng-detail .help {
	position:absolute;
	top:20px;
	left:240px;}
.lstng-detail .help a.eye {
	display:block;
	background:url(/images2/eye.png) no-repeat top left;
	width:18px;
	height:12px;
	text-indent:-9999px;
	cursor:pointer;}
	.lstng-detail .help:hover a.eye {
		background-position:left -12px;}
.lstng-detail.first .help {
	top:0px;}
	.lstng-detail .help a.tooltip3 {
		background:url(/images2/help-tooltip-bg.png) top left no-repeat;
		left: 17px;
		padding:11px 12px;
		position:absolute;
		top:-102px;
		z-index:1000;
		display:none;}
	.lstng-detail .help:hover a.tooltip3 {
		display:block;}

.lstng-detail {
	overflow:visible;}
</style>
<script type="text/javascript">
$('textarea').elastic();
</script>
<form action="" method="post">
    <div class="lstng-details pricing overview">		
    	<?php if($this->help->ent_overview == 0): ?>						
    	<div class="desc">
    		<h3>What is the Overview Section?</h3>
    		<p>Let people know about your entertainment, how is the experience, what to expect, things they'll love.</p>
    		<a href="" rel="ent_overview" class="remove">Remove</a>
    	</div><!-- closes desc -->
        <?php endif ?>
    	<div class="main-ttl">
    		<p><strong>Entertainment Overview</strong></p>    		
    	</div><!-- closes main-ttl -->
        <div class="lstng-detail">
            <textarea placeholder="Write a nice description about the entertaiment" class="noclean limitcc" rel="1000" name="about" cols="30" rows="1"><?= stripslashes($this->overview->about) ?></textarea>
            <strong>About the entertainment</strong>
            <span>Write a detailed description</span>
            <!--<span class="counter">500</span>-->
            <div class="help">
                <a href="/images2/help/big-ent-overview-about.png" class="eye">help</a>
                <a href="/images2/help/big-ent-overview-about.png" class="tooltip3">
                <img src="https://static.tripfab.com/images2/help/small-ent-overview-about.png" /></a>
            </div>
            <div class="clear"></div>
        </div><!-- closes lstng-detail -->
        <div class="lstng-detail">
            <textarea placeholder="Write a nice description about what to expect" class="noclean limitcc" rel="1000" name="expect" cols="30" rows="1"><?= stripslashes($this->overview->expect) ?></textarea>
            <strong>Kind of entertaimment you will get</strong>
            <span>Tell us what the traveler can expect</span>
            <!--<span class="counter">500</span>-->
            <div class="help">
                <a href="/images2/help/big-ent-overview-kind.png" class="eye">help</a>
                <a href="/images2/help/big-ent-overview-kind.png" class="tooltip3">
                <img src="https://static.tripfab.com/images2/help/small-ent-overview-kind.png" /></a>
            </div>
            <div class="clear"></div>
        </div><!-- closes lstng-detail -->
        
       <div class="lstng-detail faq last">								
            <strong>Restrictions</strong>
            <span>Write a detailed description</span><br />
            
            <div class="clear"></div>
            <?php $exists = false; ?>
            <?php foreach($this->details as $detail): ?>
            <?php if($detail->type == 3): ?>
            <?php $exists = true; ?>
            <div class="item">
                <a href="#delete_detail_<?= $detail->id ?>" class="remove">remove</a>
                <input placeholder="Enter your restriction text here" type="text" class="noclean" name="detail[<?= $detail->id ?>][text]" value="<?= $detail->text ?>" />
                <div class="clear"></div>
            </div>
            <?php endif ?>
            <?php endforeach ?>
            
            
            <?php if($exists): ?>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="details[3][0][text]" value="" />
                <div class="clear"></div>
            </div>
            <?php else: ?>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="details[3][0][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="details[3][1][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="details[3][2][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="details[3][3][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="details[3][4][text]" value="" />
                <div class="clear"></div>
            </div>
            <?php endif ?>
            
            <div class="hidden restriction detail">
            	<a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="text" value="" />
                <div class="clear"></div>
            </div>
            <a href="" id="addRestriction" class="link-5">Add another item</a>
            <div class="help">
                <a href="/images2/help/big-ent-overview-policies.png" class="eye">help</a>
                <a href="/images2/help/big-ent-overview-policies.png" class="tooltip3">
                <img src="https://static.tripfab.com/images2/help/small-ent-overview-policies.png" /></a>
            </div>
            <div class="clear"></div>
        </div><!-- closes lstng-detail -->
    </div><!-- closes lstng-details -->
    <div class="foot">
        <input type="submit" class="btn-1 noclean" value="Save Changes" />
    </div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'edit-overview') ?>" />
    <input type="hidden" name="_task" value="<?= md5('edit_overview') ?>" />
</form>