<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <!-- Google Website Optimizer Tracking Script -->
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['gwo._setAccount', 'UA-24981182-2']);
      _gaq.push(['gwo._trackPageview', '/3967799894/test']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
    <!-- End of Google Website Optimizer Tracking Script -->
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Tripfab.com</title>
    <link type="text/css"  rel="stylesheet" href="/css6/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css"  rel="stylesheet" href="/css6/trips.css?v=<?= $this->cssVC ?>" />
    <link type="text/css"  rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css"  rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
    <link href="/css6/calendar.css?v=<?= $this->cssVC ?>" rel="stylesheet" type="text/css">
</head>
<body>
<div id="wp_all">
    <div id="wp_header">
        <div class="header">
            <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>
        </div><!--HEADER-->
    </div><!--WP_HEADER-->
    <div id="wp_content">
        <div id="trips1">
            <div class="cntrl">
                <ul class="breadcrump">
                    <li class="first"><a class="home" href="/"></a></li>
                    <li><a href="/trips/costa_rica">Preplanned Packages</a></li>
                    <li><a href="/trips/costa_rica">Costa Rica</a></li>
                    <li class="last"><a class="active" href="/l1/trips/costa_rica/#/adventure">Adventure</a></li>
                </ul>
                <a class="link1" href="/trips/costa_rica">← Back to Results</a>
                <div class="clear"></div>
            </div><!--CNTRL-->
            
            <div class="head">
                <span></span>
                <h2>Adventure Packages in Costa Rica</h2>
                <a href="">Select a Category <em></em></a>
                <div class="categories">
                    <em></em>
                    <ul>
                        <li><a href="#/all">All Categories<span><?= $this->trips_count['all'] ?></span></a></li>
                    	<?php foreach($this->categories as $cat): ?>
                        <li><a href="#/<?= strtolower(str_replace(' ','_', $cat->name)) ?>"><?= $cat->name ?> <span class="num">(<?= $this->trips_count[$cat->id] ?>)</span></a></li>
                        <?php endforeach ?>
                    </ul>
                </div><!--CATEGORIES-->
            </div><!--HEAD-->
            <div class="content">
                <div class="side">
                    <h3>Best Price 100% Guaranteed</h3>
                    <h4>Why Book with Tripfab?</h4>
                    <ul>
                        <li>Customer Care</li>
                        <li>Lowest prices guaranteed</li>
                        <li>No extra fees</li>
                        <li>Save 20% - 40%</li>
                    </ul>
                    <h4>Questions?</h4>
                    <p>Our <strong>Costa Rica travel experts</strong> are on the phone waiting to answer all the questions you have.</p>
                    <strong class="phone">+1-866-401-0382</strong>
                    <span class="line"><em>or</em></span>
                    <a href="#" onclick="return SnapABug.startLink();" class="btn-10"><em></em>Live Chat Now</a>
                </div><!--SIDE-->
                
                <div class="main">
                    <div class="filters">
                        <span class="ttl">FILTER OPTIONS</span>
                        <div class="price">
                            <span>Price</span>
                            <select id="js-price">
                                <option value="500">$500 or less</option>
                                <option value="1000">$1,000 or less</option>
                                <option value="2000">$2,000 or less</option>
                                <option value="3000">$3,000 or less</option>
                                <option value="4000">$4,000 or less</option>
                                <option value="5000">$5,000 or less</option>
                                <option value="6000" selected="selected">$6,000 or less</option>
                            </select>
                        </div><!--PRICE-->
                        
                        <div class="travelers">
                            <span>Travelers</span>
                            <select id="js-people">
                                <option value="0" selected="selected">Any</option>
                                <option value="1">1 person</option>
                                <option value="2">2 people</option>
                                <option value="3">3 people</option>
                                <option value="4">4 people</option>
                                <option value="5">5 people</option>
                                <option value="6">6 people</option>
                                <option value="7">7 people</option>
                                <option value="8">8 people</option>
                                <option value="9">9 people</option>
                                <option value="10">10 people</option>
                            </select>
                        </div><!--TRAVELERS-->
                        
                        <div class="duration">
                            <span>Duration</span>
                            <select id="js-days">
                                <option value="1">1 or more</option>
                                <option value="2">2 or more</option>
                                <option value="3">3 or more</option>
                                <option value="4">4 or more</option>
                                <option value="5">5 or more</option>
                                <option value="6">6 or more</option>
                                <option value="7">7 or more</option>
                                <option value="15">15 or more</option>
                                <option value="30">30 or more</option>
                            </select>
                        </div><!--TRAVELERS-->
                    </div><!--FILTERS-->
                    
                    <div class="js-search-results">
						<div class="loading js-loading"><div class="load">Loading...</div></div>
                    </div>
                </div><!--MAIN-->
                <div class="clear"></div>
            </div><!--CONTENT-->
        </div><!--TRIPS1-->		
    </div><!--WP_CONTENT-->
    <?= $this->partial('partials/footer.phtml'); ?>
    <?php if(!isset($_COOKIE['nohelp2'])): ?>
    <div class="js-footer-fixed">
        <div id="support" class="fixed">
            <div class="wrap">
            	<a href="" class="js-close close"></a>
            	<div class="rg">
            		<p>Need help? Want a custom package? Is something not clear? Contact our <strong>Costa Rica travel experts</strong> and let us help.</p>
            	</div><!--RG-->
            	<div class="number"><h6>Toll Free <span>1-866-401-0382</span></h6></div><!--NUMBER-->
            </div><!--WRAP-->
        </div><!--SUPPORT-->
    </div>
    <?php endif ?>
</div><!--WRAPPER_ALL-->
<input type="hidden" id="hddCountryId" name="hddCountryId" value="<?= $this->country->id ?>" />
<div id="tripsAutocompleteContainerTop"></div>
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript" src="/js2/trips/country2.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
$(function(){
	$('.js-close').click(function(){
		$('.js-footer-fixed').hide();
		$.cookie('nohelp2','please',{expires:365});	
		return false;
	});
	
	$(".head > a").click(function() {
		$(".head .categories").toggleClass('show');
		return false;
	});
});
</script>
<script type="text/javascript">
$(function(){
	setTimeout('SnapABug.openProactiveChat();', 2000);
});
</script>
</body>
</html>