<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Tripfab Signups</title>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript">
$(function(){
	$('.latest ul li:odd').addClass('odd');
});
</script>
<style type="text/css">
* {
	margin:0;
	padding:0;}
body { 
	background:#000;
	color:#FFF;
	font-weight:bold;
	font-family:Georgia, "Times New Roman", Times, serif;
	text-align:center;}
#counter {
	width:500px;
	margin:50px auto;}
	#counter h3 {
		font-size:30px;}
	#counter h1 {
		font-size:72px;}
		
	#counter .other {
		margin-top:50px;
		overflow:hidden;}
		#counter .other .item {
			float:left;
			width:33%;}
		#counter .other .item h5 {
			font-size:24px;}
		#counter .other .item p {
			font-size:36px;}
	
	#counter .latest {
		width:300px;
		margin:20px auto;
		border:1px solid #FFF;
		height:200px;}
		#counter .latest ul {
			height:180px;
			overflow-y:scroll;
			list-style:none;
			margin:0 0 0 0;
			padding:0 0 0 0;}
		#counter .latest ul li {
			margin:0 0 0 0;
			padding:0 0 0 5px;
			font-family:Arial, Helvetica, sans-serif;
			font-size:12px;
			line-height:20px;
			text-align:left;}
		#counter .latest ul li.odd {
			background:#333;}
		#counter .latest p {
			text-align:right;
			font-size:10px;
			font-style:italic;
			line-height:20px;}
</style>
</head>

<body>
<div id="counter">
	<h3>Tripfab Signups</h3>
    <h1><?= $this->total ?></h1>
    <div class="other">
    	<div class="item">
        	<h5>Today</h5>
            <p><?= $this->day ?></p>
        </div>
    	<div class="item">
        	<h5>This week</h5>
            <p><?= $this->week ?></p>
        </div>
    	<div class="item">
        	<h5>This month</h5>
            <p><?= $this->month ?></p>
        </div>
    </div>
    <div class="latest">
    	<ul>
        	<?php foreach($this->emails as $email): ?>
        	<li><?= $email[email] ?></li>
            <?php endforeach ?>
        </ul>
        <p>Showing the last <?= count($this->emails) ?> emails</p>
    </div>
</div>
</body>
</html>
