<div class="rstl"><span> <?= count($this->places) ?> Results</span></div><!--RSTL-->
<div class="cont">
	<?php for($i=0;$i<count($this->places);$i=$i+48): ?>
    <div class="single">
    	<?php for($j=$i;($j<count($this->places)) and ($j<($i+48));$j=$j+16): ?>
        <ul>
        	<?php for($k=$j;($k<count($this->places)) and ($k<($j+16));$k++): ?>
            <?php $place = $this->places[$k]; ?>
            <?php if($place->done): ?>
            <li><a class="done" href="<?= $place->id ?>">
			<?= $place->name ?> <span>(<?= $place->stats->checkinsCount ?>)</span><em></em></a></li>
            <?php else: ?>
            <li><a href="<?= $place->id ?>" data-google="" data-facebook="">
			<?= $place->name ?> <span>(<?= $place->stats->checkinsCount ?>)</span><em></em></a></li>
            <?php endif ?>
            <?php endfor ?>
        </ul>
        <?php endfor ?>
    </div><!--SINGLE-->
    <?php endfor ?>
</div><!--CONT-->