<h3>There are <strong><?= $this->listing_count ?> <?= $this->categ ?> in <?= $this->city->title ?>, <?= $this->country->title ?></strong></h3>
<div class="results-wrapper">
<?php $url = $this->baseUrl() .'/'. $this->country->identifier .'/'. $this->city->identifier .'/filter';
$cat = $this->cat; $subcat = $this->subcat; $sort = $this->sort; $stars  = $this->stars; ?>
<div class="loading"><div class="load">Loading...</div></div>
<?php if(count($this->listings) > 0): ?>
<?php foreach($this->listings as $i => $list): ?>	
<?php $class = ((($i+1) % 3) == 0) ? 'last' : '' ?>
<div class="result <?= $class ?>">
	<div class="holder">
		<div class="img-wrapper">
			<?php if(!is_null($this->user) && $this->user->role_id == 2): ?>
			<a href="#" class="been">Been there</a>
			<?php endif ?>
			<a href="<?= str_replace('filter', $list->identifier, $url) ?>">
			<?= $this->thumbnail(array('width'=>'225', 'height'=>'167'), $list->image, '','225:167') ?>
			<h4><?= $list->title ?></h4>
			</a>
			<?php if(!is_null($this->user) && $this->user->role_id == 2): ?>
			<?= $this->partial('partials/trips.phtml', array('trips'=> $this->trips, 'id'=>$list->id)); ?>
			<?php endif ?>
		</div><!-- closes img-wrapper -->
		<div class="meta">
			<span class="location"><strong>Tamarindo</strong>, CR</span> 
			<span class="cat"><img src="/images2/cleardot.gif" alt="" /></span>
		</div><!-- closes meta -->
		<p class="listing_description"><?= $list->description ?></p>
		<?php if($list->price > 0): ?>
		<strong class="price">$<?= $list->price ?><em> / person</em></strong>
		<?php endif ?>
		<a href="<?= str_replace('filter', $list->identifier, $url) ?>" class="btn-1">View activity</a>
	</div>
</div><!-- closes result -->
<?php endforeach ?>
<div class="clear"></div>
<?php else: ?>
<p>No Listings Found</p>
<div class="clear"></div>
<?php endif ?>
</div><!-- closes results-wrapper -->