<?php $_classes = array(
		2 => 'restaurant',
		4 => 'sights',
		5 => 'hotel',
		6 => 'activity',
		7 => 'entertaiment'
) ;

$css_name = array(
		2 => 'gen',
		4 => 'gen',
		5 => 'hotel',
		6 => 'activity',
		7 => 'gen'
) ;

$cat_name = array(
		2 => 'Restaurant',
		4 => 'Tourist Sight',
		5 => 'Hotel',
		6 => 'Activity',
		7 => 'Entertainment'
); 
$per_night = array(
		2 => 'per person',
		4 => 'per person',
		5 => 'per night',
		6 => 'per person',
		7 => 'per person'
); 


?>
<?php if(count($this->listings) > 0): ?>
<?php foreach($this->listings as $i => $list): ?>	
    <div class="single <?=$css_name[$list->main_type] ?>-1">
        <div class="image">
        
        <?php if($list->main_type == 2 || $list->main_type == 4 || $list->main_type == 7):?>
			<?php if(!is_null($this->user) && $this->user->role_id == 2): ?>
                <a href="#" class="add been"></a>
            <?php else: ?>
                <a href="/login" class="add been not"></a>
			<?php endif ?>
            <?= $this->lazylisting(array('width'=>'241', 'height'=>'124'), $list->image, '','241:124') ?>
            <ul class="rating">
                <li><a href="" class="slct"></a></li>
                <li><a href="" class="slct"></a></li>
                <li><a href="" class="slct"></a></li>
                <li><a href="" class="nrml"></a></li>
                <li><a href="" class="nrml"></a></li>
            </ul>
            <div class="hvr">
                <a class="restaurant" href="/<?= $list->countryidf ?>/<?= $list->cityidf ?>/<?= $list->identifier ?>">
                View <?=$cat_name[$list->main_type] ?>
                <span> </span>
                </a>
            </div><!--HVR-->
        </div><!--IMAGE-->
        <h4><a href="/<?= $list->countryidf ?>/<?= $list->cityidf ?>/<?= $list->identifier ?>"><?= $list->title ?></a></h4>

        <div class="info">
            <span class="location"><span></span>Location <strong><?= $list->city ?>, <?= $list->country ?></strong></span>
            <div class="price"><sup>$</sup><?= $list->price ?> <sub><?=$per_night[$list->main_type] ?></sub></div>
            <div class="clear"></div>
        </div><!--INFO-->
 
         <?php else:?>
            <?= $this->lazylisting(array('width'=>'241', 'height'=>'124'), $list->image, '','241:124') ?>
            <a class="add" href=""></a>
            <ul class="rating">
                <li><a href="" class="slct"></a></li>
                <li><a href="" class="slct"></a></li>
                <li><a href="" class="slct"></a></li>
                <li><a href="" class="nrml"></a></li>
                <li><a href="" class="nrml"></a></li>
            </ul>
            <div class="hvr">
                <a class="restaurant" href="/<?= $list->countryidf ?>/<?= $list->cityidf ?>/<?= $list->identifier ?>">
                View <?=$cat_name[$list->main_type] ?>
                <span> </span>
                </a>
            </div><!--HVR-->
        </div><!--IMAGE-->
        <h4><a href="/<?= $list->countryidf ?>/<?= $list->cityidf ?>/<?= $list->identifier ?>"><?= $list->title ?></a></h4>
   		<?php if($list->main_type == 6):?>
            <span>by <?= $list->vendor_name?></span>
        <?php endif;?>
        <p><?= substr($list->description, 0, 100) ?>...</p>      
        <div class="info">
            <span class="location"><span></span>Location <strong><?= $list->city ?>, <?= $list->country ?></strong></span>
            <div class="price"><sup>$</sup><?= $list->price ?> <sub><?=$per_night[$list->main_type] ?></sub></div>
            <div class="clear"></div>
        </div><!--INFO-->
       
        <?php endif;?>
        
    </div><!--SINGLE-->


<?php endforeach ?>
<div class="clear"></div>
<?php endif ?>