<?php $_classes = array(
		2 => 'restaurant',
		4 => 'sights',
		5 => 'hotel',
		6 => 'activity',
		7 => 'entertaiment'
) ?>
<?php if(!is_null($this->city)): ?>
<?php $url = $this->baseUrl() .'/'. $this->country->identifier .'/'. $this->city->identifier .'/filter';
$cat = $this->cat; $subcat = $this->subcat; $sort = $this->sort; $stars  = $this->stars; ?>

<div style="top: 0pt;" class="sort">
    <h3>There are <strong><?= $this->listing_count ?> <?= $this->categ ?> in <?= $this->city->title ?>, <?= $this->country->title ?></strong></h3>
    <div class="filter">
        <form action="">
            <fieldset>
                <select>
                    <?php foreach($this->sortOptions as $opt):?>
                    <option ><?php echo $opt?></option>
                    <?php endforeach;?>
                </select>
                <label>Sort by:</label>
                <div class="clear"></div>
            </fieldset>
        </form>
    </div><!--FILTER-->
    <span class="shw"></span>
</div><!--SORT-->
                

<?php else: ?>
<?php $url = $this->baseUrl() .'/'. $this->country->identifier .'/filter';
$cat = $this->cat; $subcat = $this->subcat; $sort = $this->sort; $stars  = $this->stars; ?>
<h3>There are <strong><?= $this->listing_count ?> <?= $this->categ ?> in <?= $this->country->title ?></strong></h3>
<?php endif ?>
<div class="results-wrapper">
<?php if(count($this->listings) > 0): ?>
<?php if(!isset($_COOKIE['tooltipHelpSearch'])): ?>
<div class="firstime_tip">
	<img class="arrow" src="https://developer.tripfab.com/images6/arrow-24.png" alt="">
	<div class="cont">
		<img src="https://developer.tripfab.com/images6/stamp.png" width="75" height="75" alt="" />
		<p><strong>Planning a Trip?</strong>
            Hey! If you're planning a trip, you can create your own customized trip, add things to do there and book it when you're ready to travel.
        </p>
	</div><!--CONT-->
	<div class="bot">
		<form action="post" id="tooltipHelpSearch">
			<fieldset>
				<label><input checked="checked" type="checkbox" name="" value="" />Don’t show again</label>
				<input type="submit" value="Okay" class="btn-1" />
			</fieldset>
		</form>
	</div><!--BOT-->
</div><!--FIRSTIME_TIP-->
<?php endif ?>
<?php endif ?>

<div class="loading"><div class="load">Loading...</div></div>
<?php if(count($this->listings) > 0): ?>
<?php foreach($this->listings as $i => $list): ?>	
<?php $class = ((($i+1) % 3) == 0) ? 'last' : '' ?>



    <div class="single">
        <div class="image">
            <?= $this->lazylisting(array('width'=>'241', 'height'=>'124'), $list->image, '','241:124') ?>
            <ul class="rating">
                <li><a href="" class="slct"></a></li>
                <li><a href="" class="slct"></a></li>
                <li><a href="" class="slct"></a></li>
                <li><a href="" class="nrml"></a></li>
                <li><a href="" class="nrml"></a></li>
            </ul>
            <div class="hvr">
                <span class="cat"><em></em>Category <strong><?= ucfirst($_classes[$list->main_type]) ?></strong></span>
                <span class="time"><em></em>Duration <strong>8 hours</strong></span>
                <a href="" class="add"></a>
                <div class="tooltip hidden">Add to My Trips<span></span></div>
            </div><!--HVR-->
        </div><!--IMAGE-->
        
        <h4><a href="/<?= $list->countryidf ?>/<?= $list->cityidf ?>/<?= $list->identifier ?>"><?= $list->title ?></a></h4>
        <span>by <a href="" class="link1"><?= $list->vendor_name?></a></span>
        <p><?= substr($list->description, 0, 100) ?>...</p>
        
        <div class="info">
            <span class="location"><span></span>Location <strong><?= $list->city ?>, <?= $list->country ?></strong></span>
            <div class="price"><sup>$</sup><?= $list->price ?> <sub>per person</sub></div>
            <div class="clear"></div>
        </div><!--INFO-->
        
    </div><!--SINGLE-->



<?php endforeach ?>
<div class="clear"></div>
<?php else: ?>
<p>No Listings Found</p>
<div class="clear"></div>
<?php endif ?>
</div><!-- closes results-wrapper -->
<div class="loading2"></div>