<?php $_classes = array(
		2 => 'restaurant',
		4 => 'sights',
		5 => 'hotel',
		6 => 'activity',
		7 => 'entertaiment'
) ?>
<?php if(count($this->listings) > 0): ?>
<?php foreach($this->listings as $i => $list): ?>	
    <div class="single">
        <div class="image">
            <?= $this->lazylisting(array('width'=>'241', 'height'=>'124'), $list->image, '','241:124') ?>
            <ul class="rating">
                <li><a href="" class="slct"></a></li>
                <li><a href="" class="slct"></a></li>
                <li><a href="" class="slct"></a></li>
                <li><a href="" class="nrml"></a></li>
                <li><a href="" class="nrml"></a></li>
            </ul>
            <div class="hvr">
                <span class="cat"><em></em>Category <strong><?= ucfirst($_classes[$list->main_type]) ?></strong></span>
                <span class="time"><em></em>Duration <strong>8 hours</strong></span>
                <a href="" class="add"></a>
                <div class="tooltip hidden">Add to My Trips<span></span></div>
            </div><!--HVR-->
        </div><!--IMAGE-->
        
        <h4><a href="/<?= $list->countryidf ?>/<?= $list->cityidf ?>/<?= $list->identifier ?>"><?= $list->title ?></a></h4>
        <span>by <a href="" class="link1"><?= $list->vendor_name?></a></span>
        <p><?= substr($list->description, 0, 100) ?>...</p>
        
        <div class="info">
            <span class="location"><span></span>Location <strong><?= $list->city ?>, <?= $list->country ?></strong></span>
            <div class="price"><sup>$</sup><?= $list->price ?> <sub>per person</sub></div>
            <div class="clear"></div>
        </div><!--INFO-->
        
    </div><!--SINGLE-->
<?php endforeach ?>
<div class="clear"></div>
<?php endif ?>