
   	<script type="text/javascript">
   		$(document).ready(function() {
   			$('a.lbc').fancybox({
   				padding: 0,
   				overlayColor: '#000',
   				overlayOpacity: '0.7'
   			});
   			$('.cont').cycle({ 
   			    fx:     'fade', 
   			    prev:   '.larrow', 
   			    next:   '.rarrow', 
   			    timeout: 0 
   			});
   		});
   		</script>

	<div id="recomendation_listing" class="lb">
		<div class="top">Our Recommendations </div><!--TOP-->
		<div class="mid">
			<div class="slider">
				<a href="#" class="larrow"></a>
				<a href="#" class="rarrow"></a>
				<div class="cont">
					<div class="slide">
						<img src="images2/img-16.png" width="329" height="232" alt="" />
						<div class="info">
							<h4>Tropical Bungee</h4>
							<h5><img src="images2/ico_136.png" width="10" height="15" alt="" /><strong>Tamarindo,</strong> Costa Rica</h5>
							<p>You can never keep a good thing under wraps for long and though Costa Rica is no longer a well-kept secret hidden from the attentions of mass toutrism, it has nonetheless survived You can never. You can never keep a good thing under wraps for long and though Costa Rica is no longer a well-kept secret hidden from the attentions of mass toutrism.</p>
							<div class="bot">
								<span><sup>$</sup>79 <em>/ person</em></span>
								<input type="submit" class="btn-1" value="Replace" />
								<input type="submit" class="btn-10" value="Read More" />
							</div><!--BOTTOM-->
						</div><!--INFO-->
					</div><!--SLIDE-->
					<div class="slide">
						<img src="images2/img-16.png" width="329" height="232" alt="" />
						<div class="info"> 
							<h4>Tropical Bungee</h4>
							<h5><img src="images2/ico_136.png" width="10" height="15" alt="" /><strong>Tamarindo,</strong> Costa Rica</h5>
							<p>You can never. You can never keep a good thing under wraps for long and though Costa Rica is no longer a well-kept secret hidden from the attentions of mass toutrism. You can never keep a good thing under wraps for long and though Costa Rica is no longer a well-kept secret hidden from the attentions of mass toutrism, it has nonetheless survived .</p>
							<div class="bot">
								<span><sup>$</sup>179 <em>/ person</em></span>
								<input type="submit" class="btn-1" value="Replace" />
								<input type="submit" class="btn-10" value="Read More" />
							</div><!--BOTTOM-->
						</div><!--INFO-->
					</div><!--SLIDE-->
				</div><!--CONT-->
			</div><!--SLIDER-->
		</div><!--MID-->
	</div><!--RECOMMENDATION_LISTING-->
