<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->trip->title ?> : Check Availability and Price | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
	<link type="text/css" rel="stylesheet" href="/css2/calendar/jquery-ui-1.8.16.custom.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->

</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', 
	array('user'=>$this->user,'full'=>true)); ?>
    <div class="w2">
        <div class="main wrapper">
            <div class="checkout-header">
                <?= $this->thumbnail(array('width'=>960,'height'=>353), $this->trip->image, '','960:353') ?>
                <div>
                    <span>Trip Availability</span>
                    <h2><?= $this->trip->title ?></h2>
                    <div class="timestamp">
                        <span><?= $this->trip->days ?> days trip</span>
                    </div><!-- closes timestamp -->	
                </div>
            </div><!-- closes checkout-header -->
            <div class="checkout-wrapper">
                <div class="trip-settings">
                    <form action="/en-US/trips/checkprice/<?= $this->trip->id ?>" method="post">
                        <fieldset>
                            <label>Start Date</label>
                            <input type="text" value="<?= $_POST['date'] ?>" class="calendar_start" name="date" />
                        </fieldset>
                        <fieldset>
                            <label>Adults</label>
                            <select name="adults">
                            	<?php for($i=$this->trip->min; $i<=$this->trip->max; $i++): ?>
                            	<?php $selected = ($_POST['adults'] == $i) ? 'selected=selected' : ''; ?>
                                <?php if($i==$this->trip->min): ?>
                                <option <?= $selected ?> value="<?= $i ?>">min <?= $i ?></option>
                                <?php elseif($i==$this->trip->max): ?>
                                <option <?= $selected ?> value="<?= $i ?>">max <?= $i ?></option>
                                <?php else: ?>
                                <option <?= $selected ?> value="<?= $i ?>"><?= $i ?></option>
                                <?php endif ?>
                            	<?php endfor ?>																
                            </select>
                        </fieldset>
                        <fieldset>
                            <label>Children</label>
                            <?php if(isset($_POST['adults'])): ?>
                            <select name="kids">
                            	<option value="0">None</option>
                                <?php $limit = $this->trip->max - $_POST['adults'] ?>
                                <?php for($i=1; $i<=$limit; $i++): ?>
                                <?php $selected = ($_POST['kids'] == $i) ? 'selected=selected' : ''; ?>
                                <option <?= $selected ?> value="<?= $i ?>"><?= $i ?></option>
                                <?php endfor ?>
                            </select>
                            <?php else: ?>
                            <select name="kids">
                                <option value="0">None</option>
                            	<?php for($i=$this->trip->min; $i<=$this->trip->max; $i++): ?>
                                <?php if($i==$this->trip->min): ?>
                                <option value="<?= $i ?>">min <?= $i ?></option>
                                <?php elseif($i==$this->trip->max): ?>
                                <option value="<?= $i ?>">max <?= $i ?></option>
                                <?php else: ?>
                                <option value="<?= $i ?>"><?= $i ?></option>
                                <?php endif ?>
                            	<?php endfor ?>																
                            </select>
                            <?php endif ?>
                        </fieldset>
                        <fieldset class="last">
                            <input type="submit" class="btn-1" value="Check Availability" />
                        </fieldset>
                        <input type="hidden" name="ids" value="<?= $this->trip->id ?>" />
                        <input type="hidden" name="token" value="<?= $this->trip->token ?>" />
                    </form>
                </div><!-- closes trip-settings -->
                <div class="trip-items">
                	<?php if($this->items > 0 or $this->items2 > 0): ?>
                    <div class="left">
                    	<?php foreach($this->items as $key => $cart): ?>
                        <div class="trip-item" id="item-<?= $key ?>">
                            <div class="top">
                                <?= $this->thumbnail(35, $cart->listing_image, '','1:1'); ?>
                                <p><strong><?= $cart->listing_title ?></strong>
                                <?php if($cart->available): ?>
                                </p><span class="green">Green</span>
                                <?php else: ?>
                                <span>(Not Available)</span> Don't worry! 
                                <a class="lb" href="#lb-recommendations">We have some recommendations for you.</a></p>
                                <span class="red">Red</span>
                                <?php endif ?>
                            </div><!-- closes top -->
                            <?php if($cart->available): ?>
                            <div class="bottom">
                                <ul>
                                	<li><strong>Ocupation</strong>
                                    <span>Adults: <?= $cart->adults ?>, Kids: <?= $cart->kids ?>, 
                                    <?php if(isset($cart->rooms)): ?>
                                    Rooms: <?= $cart->rooms ?>, Nights: <?= $cart->nights ?></span>
                                    <?php else: ?>
                                    </span>
                                    <?php endif ?>
                                    <li><strong>Dates</strong>
                                    <span>Day # <?= $cart->day ?> | Checkin: <?= $cart->checkin ?>, 
                                    <?php if(isset($cart->checkout)): ?>
                                    Checkout: <?= $cart->checkout ?></span>
                                    <?php else: ?>
                                    </span>
                                    <?php endif ?>
                                    </li>
                                    <li>
                                        <strong>$<?= $cart->rate ?></strong>
                                        <span><?= $cart->rate_description ?></span>
                                    </li>
                                    <?php if(isset($cart->additional) && $cart->additional > 0): ?>
                                    <li>
                                        <strong>$<?= $cart->additional ?></strong>
                                        <span><?= $cart->additional_description ?></span>
                                    </li>
                                    <?php endif ?>
                                    <li>
                                    	<strong>$<?= $cart->subtotal ?></strong>
                                        <span>Subtotal</span>
                                    </li>
                                    <li>
                                    	<strong>$<?= $cart->taxes ?></strong>
                                        <span>Taxes and Fees</span>
                                    </li>
                                    <li>
                                    	<strong>$<?= $cart->total ?></strong>
                                        <span>Total</span>
                                    </li>
                                </ul>
                            </div><!-- closes bottom -->
                            <?php else: ?>
                            <div class="bottom">
                                <ul>
                                	<li><strong>Ocupation</strong>
                                    <span>Adults: <?= $cart->adults ?>, Kids: <?= $cart->kids ?>, Date: <?= $cart->checkin ?></span></li>
                                    <li>
                                        <strong>Error</strong>
                                        <span><?= $cart->error ?></span>
                                    </li>
                                </ul>
                            </div><!-- closes bottom -->
                            <?php endif ?>
                        </div><!-- closes trip-item -->
                        <?php endforeach ?>
                        <?php foreach($this->items2 as $key => $cart): ?>
                        <div class="trip-item" id="item2-<?= $key ?>">
                            <div class="top">
                                <?= $this->thumbnail(35, $cart->listing_image, '','1:1'); ?>
                                <p><strong><?= $cart->listing_title ?></strong></p><span class="green">Green</span>
                            </div><!-- closes top -->
                            <div class="bottom">
                                <ul>
                                    <li>
                                        <strong>Price not charged</strong>
                                        <span>Check the prices when you get there</span>
                                    </li>
                                </ul>
                            </div><!-- closes bottom -->
                        </div><!-- closes trip-item -->
                        <?php endforeach ?>
                    </div><!-- closes left -->
                    <div class="right">
                        <div class="widget summary">
                            <div class="ttl">
                                Trip Summary
                            </div><!-- closes ttl -->
                            <ul>
                            	<?php foreach($this->items as $key => $cart): ?>
                                <?php $class = ($cart->available) ? '' : 'error' ?>
                                <li class="<?= $class ?>">
                                    <a href="#item-<?= $key ?>"><span>&larr;</span> <?= $cart->listing_title ?>
                                    <?php if($cart->available): ?><strong>$<?= $cart->total ?></trong><?php endif ?></a>
                                </li>
                                <?php endforeach ?>
                                <?php foreach($this->items2 as $key => $cart): ?>
                                <li>
                                    <a href="#item2-<?= $key ?>"><span>&larr;</span> <?= $cart->listing_title ?></a>
                                </li>
                                <?php endforeach ?>
                            </ul>
                            <div class="total">
                            <form action="/en-US/cart/purchasetrip" method="post">
                                <input type="submit" class="btn-2" value="Process to Checkout" />
                                <span>Trip Total <strong>$<?= $this->bigtotal ?></strong></span>
                                <input type="hidden" name="checkin" value="<?= $_POST['date'] ?>" />
                                <input type="hidden" name="kids" value="<?= $_POST['kids'] ?>" />
                                <input type="hidden" name="adults" value="<?= $_POST['adults'] ?>" />
                                <input type="hidden" name="trip" value="<?= $this->trip->id ?>" />
                                <input type="hidden" name="triptoken" value="<?= $this->trip->token ?>" />
                            </form>
                            </div>
                        </div><!-- closes widget -->
                    </div><!-- closes right -->
                    <?php endif ?>
                </div><!-- closes trip-items -->
            </div><!-- closes checkout-wrapper -->
        </div><!-- closes main -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js2/jquery.scrollTo.js"></script>
<script type="text/javascript" src="/js2/jquery.input.value.js"></script>
<script type="text/javascript" src="/js2/jquery.elastic.js"></script>
<script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<script type="text/javascript" src="/js/scrollElement.jQuery.js"></script>
<script type="text/javascript" src="/js2/common.js"></script>
<script type="text/javascript" src="/js2/trips/checkprices.js"></script>
</body>
</html>