<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Trips to <?= $this->country->title ?> | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css2/trips/country.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
    
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', 
	array('user'=>$this->user,'full'=>true)); ?>
    
    <div class="w2">
        <div class="wrapper filters">
            <div class="top">
                We have <span><?= count($this->trips) ?></span> preplaned itineraries to <span>Costa Rica</span>
            </div><!-- closes top -->
            <div class="bottom">
                <div class="slider-wrapper">
                    Cost per person: <span id="value-1"></span>
                    <div id="slider-1"></div>
                </div><!-- closes slider-wrapper -->
                <div class="slider-wrapper">
                    Duration: <span id="value-2"></span>
                    <div id="slider-2"></div>
                </div><!-- closes slider-wrapper -->
                <div class="slider-wrapper last">
                    People: <span id="value-3"></span>
                    <div id="slider-3"></div>
                </div><!-- closes slider-wrapper -->
            </div><!-- closes bottom -->
        </div><!-- closes filters -->
        <div class="wrapper box results">
            <div class="content" id="browse_search">
            	<div class="loading"><div class="load">Loading...</div></div>
            </div><!-- closes content -->
            <div class="sidebar">
            	<div class="scrollContainer">
                    <div class="widget menu">
                        <h2>Categories</h2>
                        <ul class="cats-menu">
	                        <li><a data-category="all" href="#/all">Show all</a></li>
                            <?php foreach($this->categories as $cat): ?>
                            <li><a data-category="<?= $cat->id ?>" href="#/<?= strtolower(str_replace(' ','_', $cat->name)) ?>"><?= $cat->name ?></a></li>
                            <?php endforeach ?>
                        </ul>
                    </div><!-- closes widget -->
                </div>
            </div><!-- closes sidebar -->
        </div><!-- closes wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->	
<input type="hidden" id="hddCountryId" name="hddCountryId" value="<?= $this->country->id ?>" />
<div id="tripsAutocompleteContainerTop"></div>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/trips.country.js"></script>
<script type="text/javascript" src="/js2/trips/country.js"></script>
</body>
</html>