<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Trips to <?= $this->country->title ?> | Tripfab.com</title>
    <link rel="icon" type="image/png" href="/images3/favicon.png" />
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/section1.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/trips/country.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
	<link type="text/css" rel="stylesheet" href="/css6/calendar.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <style type="text/css">
	.search-item .slide .photos { background:#333;}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', 
	array('user'=>$this->user,'full'=>true)); ?>
    
    <div class="sub_header" id="src_map">
        <div class="cont">
            <div class="title">
            	<h2>Buy Pre-planned Trips</h2>
            	<h3>Book activities and hotels, or add things to do to your custom trip</h3>
            </div>
            <div class="links">
            	<a class="active" href="#">Pre-Planned Packages <span>(25)</span></a>
            	<a href="/costa_rica#/all">Build Your Trip <span>(1,258)</span></a>
            </div><!--LINKS-->
            <div class="clear"></div>
        </div><!--CONT-->
    </div><!--SUB_HEADER-->
    
    <div class="w2">
        <div class="wrapper filters">
            <div class="bottom">
                <div class="slider-wrapper">
                    Price Range: <span id="value-1"></span>
                    <div id="slider-1" data-max="<?= $this->max ?>"></div>
                </div><!-- closes slider-wrapper -->
                <div class="slider-wrapper">
                    Duration: <span id="value-2"></span>
                    <div id="slider-2"></div>
                </div><!-- closes slider-wrapper -->
                <div class="slider-wrapper last">
                    People: <span id="value-3"></span>
                    <div id="slider-3"></div>
                </div><!-- closes slider-wrapper -->
            </div><!-- closes bottom -->
        </div><!-- closes filters -->
        <div class="wrapper box results">
            <div class="content" id="browse_search">
            	<div class="loading"><div class="load">Loading...</div></div>
            </div><!-- closes content -->
            <div class="sidebar">
            	<div class="scrollContainer">
                    <div class="widget menu">
                        <h2 class="cat">Categories</h2>
                        <ul class="cats-menu">
	                        <li><a data-category="all" href="#/all">Show All <span class="num">(<?= $this->trips_count['all'] ?>)</span></a></li>
                            <?php foreach($this->categories as $cat): ?>
                            <li><a data-category="<?= $cat->id ?>" href="#/<?= strtolower(str_replace(' ','_', $cat->name)) ?>"><?= $cat->name ?> <span class="num">(<?= $this->trips_count[$cat->id] ?>)</span></a></li>
                            <?php endforeach ?>
                        </ul>
                    </div><!-- closes widget -->
                </div>
            </div><!-- closes sidebar -->
        </div><!-- closes wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->	
<input type="hidden" id="hddCountryId" name="hddCountryId" value="<?= $this->country->id ?>" />
<div id="tripsAutocompleteContainerTop"></div>
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript" src="/js2/trips.country.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript" src="/js2/trips/country.js?v=<?= $this->cssVC ?>"></script>
</body>
</html>