<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->trip->title ?>, <?= $this->trip->country ?> | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
	<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
	<link type="text/css" rel="stylesheet" href="/css2/jquery-ui-1.8.16.custom.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
</head>
<body>
<div class="w1 profile"> 
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>    
    <div class="w2">
    	 <div class="w3 itinerary">
        	<div class="wrapper">
        	    <a href="#dates_lb" class="lb btn-1">Buy Itinerary</a>
        	    <h2><?= $this->trip->title ?></h2>
        	</div><!-- closes ttl -->
        </div>
        <div class="wrapper trip-itinerary">
            <div class="overview">
                <ul class="menu">
                    <li class="active"><a href="/trips/view/<?= $this->trip->id ?>">Overview</a></li>
                    <li><a href="/trips/itinerary/<?= $this->trip->id ?>">Itinerary</a></li>
                </ul>
                <div class="image">
                	<?= $this->thumbnail(array('width'=>930, 'height'=>476), $this->trip->image,'','930:746') ?>
                    <div class="info">
                        <h3><?= $this->trip->title ?></h3>
                        <span class="place"><?= $this->trip->country ?></span>
                        <span class="duration"><?= $this->trip->days ?> days</span>
                        <h4><sup>$</sup><?= $this->trip->price ?><span>per person</span></h4>
                    </div><!--INFO-->
                </div><!--IMAGE-->
            </div><!--OVERVIEW-->
            
            <div class="facts">
                <div class="cities">
                    <h3>Some cities you'll explore</h3>
                    <img src="/images2/itinerary-map.png" width="" height="" alt="" />
                    <ul>
                        <?php $used_cities = array(); ?>
                    	<?php foreach($this->listings as $list): ?>
                        <?php if(!in_array($list->city, $used_cities)): ?>
                        <li><?= $list->city ?></li>
                        <?php $used_cities[] = $list->city ?>
                        <?php endif ?>
                        <?php endforeach ?>
                    </ul>
                </div><!--CITIES-->
                <h3>Trip Overview</h3>
                <p><?= $this->trip->description ?></p>
            </div><!--FACTS-->
            
            <?php if(count($this->highlights) > 0): ?>
            <div class="hight-lights">
                <h4>Trip Highlights</h4>
                <?php foreach($this->highlights as $high): ?>
                <div>
                    <h5><?= $high->title ?></h5>
                    <p><?= nl2br($high->text) ?></p>
                </div>
                <?php endforeach ?>
            </div><!-- closes high-lights -->
            <?php endif ?>
            <div class="tabs-wrapper">
				<?php $show = array(); ?>
                <?php foreach($this->listings as $listing): ?>
                    <?php if($listing->main_type == 6 or $listing->main_type == 7): ?>
                    <?php $show[1] = true; ?>
                    <?php elseif($listing->main_type == 4): ?>
                    <?php $show[2] = true; ?>
                    <?php elseif($listing->main_type == 5): ?>
                    <?php $show[3] = true; ?>
                    <?php elseif($listing->main_type == 2): ?>
                    <?php $show[4] = true; ?>
                    <?php endif ?>
                <?php endforeach ?>
                <ul>
                    <?php if(isset($show[1]) and $show[1] == true): ?><li><a href="#tabs-1">Things to do</a></li><?php endif ?>
                    <?php if(isset($show[2]) and $show[2] == true): ?><li><a href="#tabs-2">Attractions</a></li><?php endif ?>
                    <?php if(isset($show[3]) and $show[3] == true): ?><li><a href="#tabs-3">Places to Stay</a></li><?php endif ?>
                    <?php if(isset($show[4]) and $show[4] == true): ?><li><a href="#tabs-4">Dining Places</a></li><?php endif ?>
                </ul>
                <?php if(isset($show[1]) and $show[1] == true): ?>
                <div class="tab" id="tabs-1">
                    <div id="slider-1">
                        <?php $used = array() ?>
                        <?php foreach($this->listings as $listing): ?>
                        <?php if($listing->main_type == 6 or $listing->main_type == 7): ?>
                        <?php if(!in_array($listing->id, $used)): $used[] = $listing->id ?>
                        <div class="slide">
                            <?= $this->thumbnail(array('width'=>855,'height'=>342), $listing->image, '', '855:342') ?>
                            <div class="content">
                                <div class="left">
                                    <?= $listing->title ?>
                                </div><!-- closes left -->
                                <div class="right">
                                    <p><?= $listing->description ?></p>
                                </div><!-- closes right -->
                            </div><!-- closes content -->
                        </div><!-- closes slide -->
                        <?php endif ?>
                        <?php endif ?>
                        <?php endforeach ?>
                    </div><!-- closes slider -->
                    <a href="" id="next-1" class="next">Next</a>
                    <a href="" id="prev-1" class="prev">Prev</a>
                    <div id="cycle-pager-1" class="cycle-pager"></div>
                </div><!-- closes tab -->
                <?php endif ?>
                <?php if(isset($show[2]) and $show[2] == true): ?>
                <div class="tab" id="tabs-2">
                    <div id="slider-2" style="height: 525px;">
                        <?php $used = array() ?>
                        <?php foreach($this->listings as $listing): ?>
                        <?php if($listing->main_type == 4): ?>
                        <?php if(!in_array($listing->id, $used)): $used[] = $listing->id ?>
                        <div class="slide">
                            <?= $this->thumbnail(array('width'=>855,'height'=>342), $listing->image, '', '855:342') ?>
                            <div class="content">
                                <div class="left">
                                    <?= $listing->title ?>
                                </div><!-- closes left -->
                                <div class="right">
                                    <p><?= $listing->description ?></p>
                                </div><!-- closes right -->
                            </div><!-- closes content -->
                        </div><!-- closes slide -->
                        <?php endif ?>
                        <?php endif ?>
                        <?php endforeach ?>
                    </div><!-- closes slider -->
                    <a href="" id="next-2" class="next">Next</a>
                    <a href="" id="prev-2" class="prev">Prev</a>
                    <div id="cycle-pager-2" class="cycle-pager"></div>
                </div><!-- closes tab -->
                <?php endif ?>
                <?php if(isset($show[3]) and $show[3] == true): ?>
                <div class="tab" id="tabs-3">
                    <div id="slider-3" style="height:525px">
                        <?php $used = array() ?>
                        <?php foreach($this->listings as $listing): ?>
                        <?php if($listing->main_type == 5): ?>
                        <?php if(!in_array($listing->id, $used)): $used[] = $listing->id ?>
                        <div class="slide">
                            <?= $this->thumbnail(array('width'=>855,'height'=>342), $listing->image, '', '855:342') ?>
                            <div class="content">
                                <div class="left">
                                    <?= $listing->title ?>
                                </div><!-- closes left -->
                                <div class="right">
                                    <p><?= $listing->description ?></p>
                                </div><!-- closes right -->
                            </div><!-- closes content -->
                        </div><!-- closes slide -->
                        <?php endif ?>
                        <?php endif ?>
                        <?php endforeach ?>
                    </div><!-- closes slider -->
                    <a href="" id="next-3" class="next">Next</a>
                    <a href="" id="prev-3" class="prev">Prev</a>
                    <div id="cycle-pager-3" class="cycle-pager"></div>
                </div><!-- closes tab -->
                <?php endif ?>
                <?php if(isset($show[4]) and $show[4] == true): ?>
                <div class="tab" id="tabs-4">
                    <div id="slider-4" style="height:525px">
                        <?php $used = array() ?>
                        <?php foreach($this->listings as $listing): ?>
                        <?php if($listing->main_type == 2): ?>
                        <?php if(!in_array($listing->id, $used)): $used[] = $listing->id ?>
                        <div class="slide">
                           <?= $this->thumbnail(array('width'=>855,'height'=>342), $listing->image, '', '855:342') ?>
                            <div class="content">
                                <div class="left">
                                    <?= $listing->title ?>
                                </div><!-- closes left -->
                                <div class="right">
                                    <p><?= $listing->description ?></p>
                                </div><!-- closes right -->
                            </div><!-- closes content -->
                        </div>
                        <?php endif ?>
                        <?php endif ?>
                        <?php endforeach ?>
                    </div><!-- closes slider -->
                    <a href="" id="next-4" class="next">Next</a>
                    <a href="" id="prev-4" class="prev">Prev</a>
                    <div id="cycle-pager-4" class="cycle-pager"></div>
                </div><!-- closes tab -->
            	<?php endif ?>
            </div>
            <div class="box tabs-bottom">
                <?php $show = array(); ?>
            	<?php foreach($this->facts as $fact): ?>
                	<?php if($fact->type == 1) $show[1] = true; ?>
                    <?php if($fact->type == 2) $show[2] = true; ?>
                    <?php if($fact->type == 3) $show[3] = true; ?>
                    <?php if($fact->type == 4) $show[4] = true; ?>
                    <?php if($fact->type == 5) $show[5] = true; ?>
                    <?php if($fact->type == 6) $show[6] = true; ?>
                <?php endforeach ?>
                <?php if(count($show) > 0): ?>
                <ul>
                	<?php if($show[1] === true): ?>
                    <li class="item-1">
                        <a href="#tabs-1"><img src="/images2/cleardot.gif" alt="" /><strong>The Culture</strong> Vivamus luctust tellus</a>
                    </li>
                    <?php endif; if($show[2] === true): ?>
                    <li class="item-2">
                        <a href="#tabs-2"><img src="/images2/cleardot.gif" alt="" /><strong>The Environment</strong> Vivamus luctust tellus</a>
                    </li>
                    <?php endif; if($show[3] === true): ?>
                    <li class="item-3">
                        <a href="#tabs-3"><img src="/images2/cleardot.gif" alt="" /><strong>Knowledge</strong> Vivamus luctust tellus</a>
                    </li>
                    <?php endif; if($show[4] === true): ?>
                    <li class="item-4">
                        <a href="#tabs-4"><img src="/images2/cleardot.gif" alt="" /><strong>Things you'll love</strong> Vivamus luctust tellus</a>
                    </li>
                    <?php endif; if($show[5] === true): ?>
                    <li class="item-5">
                        <a href="#tabs-5"><img src="/images2/cleardot.gif" alt="" /><strong>When to take this trip</strong> Vivamus luctust tellus</a>
                    </li>
                    <?php endif; if($show[6] === true): ?>
                    <li class="item-6">
                        <a href="#tabs-6"><img src="/images2/cleardot.gif" alt="" /><strong>Tips &amp; Recommendations</strong> Vivamus luctust tellus</a>
                    </li>
                    <?php endif ?>
                </ul>
				<?php if($show[1] === true): ?>
                <div id="tabs-1" class="tab">
                    <h4>About the Culture</h4>
                    <?php $right = false; ?>
                    <?php foreach($this->facts as $fact): ?>
                    <?php if($fact->type == 1): ?>
                    <?php $class = ($right) ? 'right' : 'left' ?> <?php $right = !$right ?>
                    <?= $this->thumbnail(array('width'=>193,'height'=>123), $fact->image, $class, '193:123') ?>
                    <p><?= nl2br($fact->text) ?></p>
                    <div class="clear"></div>
                    <?php endif ?>
                    <?php endforeach ?>
                </div>
                <?php endif; if($show[2] === true): ?>
                <div id="tabs-2" class="tab">
                    <h4>About the Environment</h4>
                    <?php $right = false; ?>
                    <?php foreach($this->facts as $fact): ?>
                    <?php if($fact->type == 2): ?>
                    <?php $class = ($right) ? 'right' : 'left' ?> <?php $right = !$right ?>
                    <?= $this->thumbnail(array('width'=>193,'height'=>123), $fact->image, $class, '193:123') ?>
                    <p><?= nl2br($fact->text) ?></p>
                    <div class="clear"></div>
                    <?php endif ?>
                    <?php endforeach ?>
                </div>
                <?php endif; if($show[3] === true): ?>
                <div id="tabs-3" class="tab">
                    <h4>About the knowledge</h4>
                    <?php $right = false; ?>
                    <?php foreach($this->facts as $fact): ?>
                    <?php if($fact->type == 3): ?>
                    <?php $class = ($right) ? 'right' : 'left' ?> <?php $right = !$right ?>
                    <?= $this->thumbnail(array('width'=>193,'height'=>123), $fact->image, $class, '193:123') ?>
                    <p><?= nl2br($fact->text) ?></p>
                    <div class="clear"></div>
                    <?php endif ?>
                    <?php endforeach ?>
                </div>
                <?php endif; if($show[4] === true): ?>
                <div id="tabs-4" class="tab">
                    <h4>About the things you'll love</h4>
                    <?php $right = false; ?>
                    <?php foreach($this->facts as $fact): ?>
                    <?php if($fact->type == 4): ?>
                    <?php $class = ($right) ? 'right' : 'left' ?> <?php $right = !$right ?>
                    <?= $this->thumbnail(array('width'=>193,'height'=>123), $fact->image, $class, '193:123') ?>
                    <p><?= nl2br($fact->text) ?></p>
                    <div class="clear"></div>
                    <?php endif ?>
                    <?php endforeach ?>
                </div>
                <?php endif; if($show[5] === true): ?>
                <div id="tabs-5" class="tab">
                    <h4>About when to take the trip</h4>
                    <?php $right = false; ?>
                    <?php foreach($this->facts as $fact): ?>
                    <?php if($fact->type == 5): ?>
                    <?php $class = ($right) ? 'right' : 'left' ?> <?php $right = !$right ?>
                    <?= $this->thumbnail(array('width'=>193,'height'=>123), $fact->image, $class, '193:123') ?>
                    <p><?= nl2br($fact->text) ?></p>
                    <div class="clear"></div>
                    <?php endif ?>
                    <?php endforeach ?>
                </div>
                <?php endif; if($show[6] === true): ?>
                <div id="tabs-6" class="tab">
                    <h4>About tips &amp; recommendations</h4>
                    <?php $right = false; ?>
                    <?php foreach($this->facts as $fact): ?>
                    <?php if($fact->type == 6): ?>
                    <?php $class = ($right) ? 'right' : 'left' ?> <?php $right = !$right ?>
                    <?= $this->thumbnail(array('width'=>193,'height'=>123), $fact->image, $class, '193:123') ?>
                    <p><?= nl2br($fact->text) ?></p>
                    <div class="clear"></div>
                    <?php endif ?>
                    <?php endforeach ?>
                </div>
	            <?php endif ?>
                <?php endif ?>
            </div>

            <div class="compare">
                <div class="inner">
                	<div class="left">
                        <ul>
                            <?php foreach($this->includes as $inc): ?>
							<?php if($inc->included == 1): ?>
                            <li><?= nl2br($inc->text) ?></li>
                            <?php endif ?>
                            <?php endforeach ?>
                        </ul>
                    </div><!-- closes left -->
                    <div class="right">
                        <ul>
                            <?php foreach($this->includes as $inc): ?>
							<?php if($inc->included == 0): ?>
                            <li><?= nl2br($inc->text) ?></li>
                            <?php endif ?>
                            <?php endforeach ?>
                        </ul>
                    </div><!-- closes right --> 
                </div>
            </div>
            <div class="result">
                <a href="#dates_lb" class="lb btn-1">Buy Itinerary</a>
                <span><sup>$</sup><?= $this->trip->price ?> <em>per person</em></span>
            </div><!--RESULT-->
        </div><!-- closes BROWSE_TRIPS --> 
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div class="hidden">
	<div id="dates_lb">
    	<div class="lb-dates">
			<div class="left">
				<h2>First, select the dates you want to go on your vacation.</h2>
				<ul>
					<li>Your trip is going to be <?= $this->trip->days ?> days long.</li>
                    <?php if($this->trip->kids): ?>
					<li>This trip is available for children.</li>
                    <?php else: ?>
					<li>This trip is not available for children.</li>                    
                    <?php endif ?>
					<li>Maximum occupation is <?= $this->trip->max ?> people.</li>
                    <?php if($this->trip->min > 1): ?>
                    <li>Minimum occupation is <?= $this->trip->min ?> people.</li>
                    <?php else: ?>
					<li>No minimum  required.</li>
                    <?php endif ?>
				</ul>
			</div><!-- closes left -->
			<div class="right">
				<div id="datepicker" class="datepicker"></div>
                <form action="/en-US/cart/purchasetrip" method="post">
                    <div class="occ">
                        <label>Adults</label>
                        <select name="adults">
							<?php for($i=$this->trip->min; $i<=$this->trip->max; $i++): ?>
                            <?php if($i==$this->trip->min): ?>
                            <option value="<?= $i ?>">min <?= $i ?></option>
                            <?php elseif($i==$this->trip->max): ?>
                            <option value="<?= $i ?>">max <?= $i ?></option>
                            <?php else: ?>
                            <option value="<?= $i ?>"><?= $i ?></option>
                            <?php endif ?>
                        	<?php endfor ?>
                        </select>
                        <?php if($this->trip->kids): ?>
                        <label>Children</label>
                        <select name="kids">
                        	<option value="0">None</option>
                        	<?php for($i=$this->trip->min; $i<=$this->trip->max; $i++): ?>
                            <?php if($i==$this->trip->min): ?>
                            <option value="<?= $i ?>">min <?= $i ?></option>
                            <?php elseif($i==$this->trip->max): ?>
                            <option value="<?= $i ?>">max <?= $i ?></option>
                            <?php else: ?>
                            <option value="<?= $i ?>"><?= $i ?></option>
                            <?php endif ?>
                        	<?php endfor ?>
                        </select>
                        <?php endif ?>
                    </div><!-- closes occ -->
                    <div class="occ">
                        <input type="submit" class="btn-1 noclean" value="Check Availability" />
                        <span onclick="$.fancybox.close()" class="btn-4">Cancel</span>
                    </div><!-- closes occ -->
                    <input type="hidden" name="checkin" value="" />
                    <input type="hidden" name="token" value="<?= $this->trip->token ?>" />
                    <input type="hidden" name="trip" value="<?= $this->trip->id ?>" />
                    <input type="hidden" name="triptoken" value="<?= $this->trip->token ?>" />
                </form>
			</div><!-- closes right -->
		</div><!-- closes dates -->
    </div>
</div>

<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/trips/view.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#slider-1').cycle({
            next: 	'#next-1',
            prev: 	'#prev-1',
            pager:	'#cycle-pager-1',
			timeout:0
        });
        $('#slider-2').cycle({
            next: 	'#next-2',
            prev: 	'#prev-2',
            pager:	'#cycle-pager-2',
			timeout:0
        });
        $('#slider-3').cycle({
            next: 	'#next-3',
            prev: 	'#prev-3',
            pager:	'#cycle-pager-3',
			timeout:0
        });
        $('#slider-4').cycle({
            next: 	'#next-4',
            prev: 	'#prev-4',
            pager:	'#cycle-pager-4',
			timeout:0
        });
        $('.tabs-wrapper, .tabs-bottom').tabs();
    });
</script>
<style type="text/css">
.desc-wrapper #pager a { width:<?= (100 / count($this->images)) . '%'; ?>;} 
.hidden { display:none;}
.datepicker a.ui-state-active { background-color: #60B5F7; color: #FFFFFF;}
</style>

</body>
</html>