<style type="text/css">
#mapcanvas { width:500px; height:300px; margin-top:10px; margin-bottom:10px;}
.errors { border:1px solid #F00; padding:5px; margin-bottom:10px;}
.errors p { font-size:12px; font-weight:normal; font-style:italic; color:#F00;}
.w-m { display:none;}
.lstng-detail { position:relative;}
.lstng-detail .help {
	position:absolute;
	top:20px;
	left:240px;}
.lstng-detail .help a.eye {
	display:block;
	background:url(/images2/eye.png) no-repeat top left;
	width:18px;
	height:12px;
	text-indent:-9999px;
	cursor:pointer;}
	.lstng-detail .help:hover a.eye {
		background-position:left -12px;}
.lstng-detail.first .help {
	top:0px;}
	.lstng-detail .help a.tooltip3 {
		background:url(/images2/help-tooltip-bg.png) top left no-repeat;
		left: 17px;
		padding:11px 12px;
		position:absolute;
		top:-102px;
		z-index:1000;
		display:none;}
	.lstng-detail .help:hover a.tooltip3 {
		display:block;}

.lstng-detail {
	overflow:visible;}
.listing-content { overflow:visible;}
</style>
<?php if($_POST): ?>
<form action="" method="post">
    <div class="lstng-details pricing overview">
    	<?php if($this->help->com_getthere == 0): ?>
    	<div class="desc">
        	<h3>What is the Listing Location Section?</h3>
        	<p>Provide people with a very descriptive address, ways to get there, the easiest transportation choices and make sure you choose the correct location of your venue in the map. You can drag and drop the pin over the exact location of your listing.</p>
        	<a href="" rel="com_getthere" class="remove">Remove</a>
        </div>
        <!-- closes desc -->	
        <?php endif ?>
    	<?php if($this->errors): ?>
        <div class="errors">
            <?php foreach($this->errors as $err): ?>
            <p><?= $err ?></p>
            <?php endforeach ?>
        </div><!-- closes item -->
        <?php endif ?>
        <div class="main-ttl">
        	<p><strong>How to Get There</strong> <a href="/admin/listings" class="back_btn">&larr; Back to Listings</a></p>        	
        </div><!-- closes main-ttl -->
        <!-- closes main-ttl -->    
    	<div class="lstng-detail">
        	<div class="selects">
                <select id="country2" name="country_id">
                    <option value="">Select Country</option>
                    <?php foreach($this->countries as $c): ?>
                    <?php $selected = ($c->id == $_POST['country_id']) ? 'selected="selected"' : ''; ?>
                    <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                    <?php endforeach ?>
                </select>
                <select name="city_id" id="cities2">
                    <?php if(count($this->cities) > 0): ?>
                    <option value="">Select the city</option>
                    <?php foreach($this->cities as $c): ?>
                    <?php $selected = ($c->id == $_POST['city_id']) ? 'selected="selected"' : ''; ?>
                    <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                    <?php endforeach ?>                                    
                    <?php else: ?>
                    <option value="">Country first</option>
                    <?php endif ?>
                </select>
            </div><!-- closes selects -->
            <strong>Location</strong>
			<span>Select country and city</span>	
            <div class="help">
                <a href="/images2/help/big-act-howto-map.png" class="eye">help</a>
                <a href="/images2/help/big-act-howto-map.png" class="tooltip3">
                <img src="/images2/help/small-act-howto-map.png" /></a>
            </div>
            <div class="clear"></div>					
        </div><!-- closes item-wrppr -->
    
        <div class="lstng-detail">
            <div class="map">
                <input placeholder="Search for your place in the map" type="text" class="noclean short" name="address" value="<?= $_POST['address'] ?>" />
                <input type="submit" class="btn-10" id="setLocation" value="Set Location" />
                <div class="clear"></div>
				<div class="w-m">
					<h5>Location Results</h5>
                	<ul id="maplocations">
                	</ul>
                </div>
                <!-- closes w-m -->
                <div id="mapcanvas"></div>
                <input type="hidden" name="lat" value="<?= $_POST['lat'] ?>" />
                <input type="hidden" name="lng" value="<?= $_POST['lng'] ?>" />                
            </div><!-- closes map -->
            <strong>Map</strong>
            <span>This is how your address appears <br /> on the public listing</span>
            <div class="clear"></div>
        </div><!-- closes lstng-detail -->
        
        <div class="lstng-detail">
        	<?php if(empty($_POST['plane']) and
					 empty($_POST['car']) and
					 empty($_POST['train']) and
					 empty($_POST['boat'])): ?>
			<div class="direction">
                <div class="cont">
                    <p>There is no any direction yet</p>
                </div><!--CONT-->
                <a href="#new_direction" class="add_direc">Add a New Direction</a>
            </div><!--DIRECTION-->
			<?php else: ?>
            <div class="direction">
				<div class="cont">
                    <?php if(!empty($_POST['plane'])): ?>
                    <div class="top">
                        <strong>By Plane</strong>
                        <a href="" class="delete">Remove</a>
                    </div><!--TOP-->
                    <textarea placeholder="Nice description about to how to get to your place by plane" cols="" class="noclean limitcc" rel="1000" name="plane" rows="1"><?= stripslashes($_POST['plane']) ?></textarea>
                    <?php endif; if(!empty($_POST['car'])): ?>
                    <div class="top">
                        <strong>By Car</strong>
                        <a href="" class="delete">Remove</a>
                    </div><!--TOP-->
                    <textarea placeholder="Nice description about to how to get to your place by car" cols="" class="noclean limitcc" rel="1000" name="car" rows="1"><?= stripslashes($_POST['car']) ?></textarea>
                    <?php endif; if(!empty($_POST['train'])): ?>
                    <div class="top">
                        <strong>By Train</strong>
                        <a href="" class="delete">Remove</a>
                    </div><!--TOP-->
                    <textarea placeholder="Nice description about to how to get to your place by train" cols="" class="noclean limitcc" rel="1000" name="train" rows="1"><?= stripslashes($_POST['train']) ?></textarea>
                    <?php endif; if(!empty($_POST['boat'])): ?>
                    <div class="top">
                        <strong>By Boat</strong>
                        <a href="" class="delete">Remove</a>
                    </div><!--TOP-->
                    <textarea placeholder="Nice description about to how to get to your place by boat" cols="" class="noclean limitcc" rel="1000" name="boat" rows="1"><?= stripslashes($_POST['boat']) ?></textarea>
                    <?php endif; if(!empty($_POST['bus'])): ?>
                    <div class="top">
                        <strong>By Boat</strong>
                        <a href="" class="delete">Remove</a>
                    </div><!--TOP-->
                    <textarea placeholder="Nice description about to how to get to your place by bus" cols="" class="noclean limitcc" rel="1000" name="boat" rows="1"><?= stripslashes($_POST['bus']) ?></textarea>
                    <?php endif; ?>
                </div><!--CONT-->
                <a href="#new_direction" class="add_direc">Add a New Direction</a>
            </div><!--DIRECTION-->
            <?php endif ?>
            <strong>Directions</strong> 
            <span>Define the way to get there</span>
            <div class="help">
                <a href="/images2/help/big-act-howto-info.png" class="eye">help</a>
                <a href="/images2/help/big-act-howto-info.png" class="tooltip3">
                <img src="/images2/help/small-act-howto-info.png" /></a>
            </div>
            <div class="clear"></div>
		</div><!-- closes lstng-detail -->
    </div>
    
	<div class="foot">
		<input type="submit" class="btn-1 noclean" value="Save Changes" />
	</div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'edit-location') ?>" />
    <input type="hidden" name="_task" value="<?= md5('edit_location') ?>" />
</form>
<?php else: ?>
<form action="" method="post">
    <div class="lstng-details pricing overview">
    	<?php if($this->errors): ?>
        <div class="errors">
            <?php foreach($this->errors as $err): ?>
            <p><?= $err ?></p>
            <?php endforeach ?>
        </div><!-- closes item -->
        <?php endif ?>
    	<?php if($this->help->com_getthere == 0): ?>
        <div class="desc">
        	<h3>What is the Listing Location Section?</h3>
        	<p>Provide people with a very descriptive address, ways to get there, the easiest transportation choices and make sure you choose the correct location of your venue in the map. You can drag and drop the pin over the exact location of your listing.</p>
        	<a href="" rel="com_getthere" class="remove">Remove</a>
        </div><!-- closes desc -->	
        <?php endif ?>						
        <div class="main-ttl">
        	<p><strong>How to Get There</strong></p>        	
        </div><!-- closes main-ttl -->
        <div class="lstng-detail">
        	<div class="selects">
                <select id="country2" name="country_id">
                    <option value="">Select Country</option>
                    <?php foreach($this->countries as $c): ?>
                    <?php $selected = ($c->id == $this->listing->country_id) ? 'selected="selected"' : ''; ?>
                    <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                    <?php endforeach ?>
                </select>
                <select name="city_id" id="cities2">
                    <?php if(count($this->cities) > 0): ?>
                    <option value="">Select the city</option>
                    <?php foreach($this->cities as $c): ?>
                    <?php $selected = ($c->id == $this->listing->city_id) ? 'selected="selected"' : ''; ?>
                    <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                    <?php endforeach ?>                                    
                    <?php else: ?>
                    <option value="">Country first</option>
                    <?php endif ?>
                </select>
            </div><!-- closes selects -->
            <strong>Location</strong>
			<span>Select country and city</span>	
            <div class="help">
                <a href="/images2/help/big-act-howto-map.png" class="eye">help</a>
                <a href="/images2/help/big-act-howto-map.png" class="tooltip3">
                <img src="/images2/help/small-act-howto-map.png" /></a>
            </div>
            <div class="clear"></div>					
        </div><!-- closes item-wrppr -->
    
        <div class="lstng-detail">
            <div class="map">
                <input placeholder="Search for your place in the map" type="text" class="noclean short" name="address" value="<?= $this->listing->address ?>" />
                <input type="submit" class="btn-10" id="setLocation" value="Set Location" />
                <div class="clear"></div>
                <div class="w-m">
                	<h5>Location Results</h5>
                	<ul id="maplocations">
                	</ul>
                </div>
                <!-- closes w-m -->
                <div id="mapcanvas"></div>
                <input type="hidden" name="lat" value="<?= $this->listing->lat ?>" />
                <input type="hidden" name="lng" value="<?= $this->listing->lng ?>" />
            </div><!-- closes map -->
            <strong>Map</strong>
            <span>This is how your address appears <br /> on the public listing</span>
            <div class="clear"></div>
        </div><!-- closes lstng-detail -->
		<div class="lstng-detail">
        	<?php if(empty($this->location->plane) and
					 empty($this->location->car) and
					 empty($this->location->train) and
					 empty($this->location->boat) and
					 empty($this->location->bus)): ?>
			<div class="direction">
                <div class="cont">
                    <p>There is no any direction yet</p>
                </div><!--CONT-->
                <a href="#new_direction" class="add_direc">Add a New Direction</a>
            </div><!--DIRECTION-->
			<?php else: ?>
            <div class="direction">
				<div class="cont">
                    <?php if(!empty($this->location->plane)): ?>
                    <div class="top">
                        <strong>By Plane</strong>
                        <a href="" class="delete">Remove</a>
                    </div><!--TOP-->
                    <textarea placeholder="Nice description about to how to get to your place by plane" cols="" class="noclean limitcc" rel="1000" name="plane" rows="1"><?= stripslashes($this->location->plane) ?></textarea>
                    <?php endif; if(!empty($this->location->car)): ?>
                    <div class="top">
                        <strong>By Car</strong>
                        <a href="" class="delete">Remove</a>
                    </div><!--TOP-->
                    <textarea placeholder="Nice description about to how to get to your place by car" cols="" class="noclean limitcc" rel="1000" name="car" rows="1"><?= stripslashes($this->location->car) ?></textarea>
                    <?php endif; if(!empty($this->location->train)): ?>
                    <div class="top">
                        <strong>By Train</strong>
                        <a href="" class="delete">Remove</a>
                    </div><!--TOP-->
                    <textarea placeholder="Nice description about to how to get to your place by train" cols="" class="noclean limitcc" rel="1000" name="train" rows="1"><?= stripslashes($this->location->train) ?></textarea>
                    <?php endif; if(!empty($this->location->boat)): ?>
                    <div class="top">
                        <strong>By Boat</strong>
                        <a href="" class="delete">Remove</a>
                    </div><!--TOP-->
                    <textarea placeholder="Nice description about to how to get to your place by boat" cols="" class="noclean limitcc" rel="1000" name="boat" rows="1"><?= stripslashes($this->location->boat) ?></textarea>
                    <?php endif; if(!empty($this->location->bus)): ?>
                    <div class="top">
                        <strong>By Bus</strong>
                        <a href="" class="delete">Remove</a>
                    </div><!--TOP-->
                    <textarea placeholder="Nice description about to how to get to your place by bus" cols="" class="noclean limitcc" rel="1000" name="boat" rows="1"><?= stripslashes($this->location->bus) ?></textarea>
                    <?php endif; ?>
                </div><!--CONT-->
                <a href="#new_direction" class="add_direc">Add a New Direction</a>
            </div><!--DIRECTION-->
            <?php endif ?>
            <strong>Directions</strong> 
            <span>Define the way to get there</span>
            <div class="help">
                <a href="/images2/help/big-act-howto-info.png" class="eye">help</a>
                <a href="/images2/help/big-act-howto-info.png" class="tooltip3">
                <img src="/images2/help/small-act-howto-info.png" /></a>
            </div>
            <div class="clear"></div>
		</div><!-- closes lstng-detail -->    
    </div>
	<div class="foot">
		<input type="submit" class="btn-1 noclean" value="Save Changes" />
	</div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'edit-location') ?>" />
    <input type="hidden" name="_task" value="<?= md5('edit_location') ?>" />
</form>
<?php endif ?>