<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Untitled Document</title>
</head>

<body bgcolor="#e6e6e6" topmargin="0" rightmargin="0" bottommargin="0" leftmargin="0">
	<table width="100%" bgcolor="#e6e6e6" topmargin="0" rightmargin="0" bottommargin="0" leftmargin="0">
		<table  width="600" cellspacing="0" cellpadding="0" border="0" bgcolor="#e6e6e6" align="center">
			<tr>
				<td width="600">
					<table width="600" border="0" cellspacing="0" cellpadding="0" >
						<tr>
							<td><img src="http://tripfab.com/images/email/et_spacerBlue.png" width="600" height="51" border="0" alt="" style="display:block;" /></td>
						</tr>
						<tr>
							<td>
								<table width="600" cellspacing="0" cellpadding="0" border="0">
									<tr>
										<td ><img src="http://tripfab.com/images/email/e-logo.png" width="600" height="51" border="0" alt="TripFab | Making your Trip Fabulous" style="display:block;" /></td>
									</tr>
									<tr>
										<td bgcolor="#FFFFFF">
											<table width="600" border="0">
												<tr>
													<td width="25">&nbsp;</td>
													<td width="550">
														<table width="550" border="0" cellspacing="0" cellpadding="0">
															<tr>
																<td><img width="391" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
															</tr>
															<tr>
																<td><font face="Helvetica, Arial, sans-serif" color="#303030" style="font-size:14px; "><b>
                                                                Listing Approved</b></font></td>
															</tr>
															<tr>
																<td><img width="391" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
															</tr>
														</table>
													</td>
													<td width="25">&nbsp;</td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td bgcolor="#FFFFFF">
											<img src="http://tripfab.com/images/email/g-2.gif" width="600" height="16" alt="" style="display:block;" border="0" />
											<table width="600" border="0" cellpadding="0" cellspacing="0 ">
												<tr>
													<td width="25">&nbsp;</td>
													<td width="550"><font face="Helvetica, Arial, sans-serif" color="#303030" style="font-size:12px; ">
                                                    Hey <?= $this->user->name ?>!</font></td>
													<td width="25">&nbsp;</td>
												</tr>
												<tr>
													<td width="25"><img width="25" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
													<td><img width="550" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
													<td width="25"><img width="25" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
												</tr>
												<tr>
													<td width="25">&nbsp;</td>
													<td width="550"><font face="Helvetica, Arial, sans-serif" color="#303030" 
                                                    style="font-size:12px; line-height:16px">
                                                    We've just reviewed your listing "<?= $this->listing->title ?>", and thought it was awesome. It won't be long now before the clients start rolling in...</font>
													</td>
													<td width="25">&nbsp;</td>
												</tr>
												<tr>
													<td width="25"><img width="25" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
													<td><img width="550" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
													<td width="25"><img width="25" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
												</tr>
												<tr>
													<td width="25">&nbsp;</td>
													<td width="550"><font face="Helvetica, Arial, sans-serif" color="#303030" style="font-size:12px; line-height:16px ">You will be getting new reservations notifications to this email<br /><br />
                                                    Please any question or comment give us a call at<bt><bt>
                                                    (+1) 800-TRIPFAB (+1 800 8747322)</font>
													</td>
													<td width="25">&nbsp;</td>
												</tr>
												<tr>
													<td width="25">&nbsp;</td>
													<td><img width="550" height="20" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
													<td width="25">&nbsp;</td>
												</tr>
												<tr>
													<td width="25"><img width="25" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
													<td style="border-top:1px solid #e6e6e6;"><img width="550" height="20" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
													<td width="25"><img width="25" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
												</tr>
												<tr>
													<td width="25">&nbsp;</td>
													<td width="550"><font face="Helvetica, Arial, sans-serif" color="#303030" style="font-size:12px; line-height:16px; ">With love<br />
													The Tripfab Team</font>
													</td>
													<td width="25">&nbsp;</td>
												</tr>
												<tr>
													<td width="25"><img width="25" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
													<td><img width="550" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
													<td width="25"><img width="25" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td>
												</tr>
											</table>
										</td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td><img src="http://tripfab.com/images/email/bot.png" width="600" height="7" alt="" style="display:block;" border="0" /></td>
						</tr>
						<tr>
							<td>
								<table width="600" border="0" cellpadding="0" cellspacing="0 ">
									<tr><td width="25"><img width="25" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td></tr>
									<tr>
										<td width="50"><img src="http://tripfab.com/images/email/footer-logo.png" width="29" height="27" alt="" style="display:block;" border="0" /></td>
										<td><font face="Helvetica, Arial, sans-serif" color="#303030" style="font-size:11px; line-height:16px ">Sent from a tropical paradise<br />
											Tripfab Inc &copy; 2012 All Rights Reserved</font>
										</td>
									</tr>
									<tr><td width="25"><img width="25" height="10" border="0" style="display:block;" alt="" src="http://tripfab.com/images/email/et_spacerBlue.png" /></td></tr>
								</table>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</table>
</body>
</html>
