<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Profile | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('input:file').uploadify({
                'uploader' 	: '/uploadify/uploadify.swf',
				'script' 	: '/phpscripts/uploadUserPicture.php',
				'cancelImg' : '/uploadify/cancel.png',
				'folder' 	: '/uploads',
				'buttonImg' : '/images2/file-1.png',
				'height' 	: 27,
				'width' 	: 92,
				'auto' 		: true,
				'fileExt'	: '*.jpg;*.gif;*.png',
				'onError':function(e,a,c,d){
					console.log('ERROR');
					console.log(e);
					console.log(a);
					console.log(c);
					console.log(d);
				},
				'onComplete':function(a,b,c,image){
					console.log('COMPLETE');
					console.log(a);
					console.log(b);
					console.log(c);
					console.log(image);
					if(image != 'error'){
						$('.picture img').attr('width',68);
						$('.picture img').attr('height',68);
						$('.picture img').attr('src',image);
					}
				},
				'scriptData':{
					'userids':<?= $this->user->id ?>,
					'formtoken':'<?= $this->user->token ?>',
					'usertoken':'<?= md5($this->user->token.'change_picture') ?>',
				},
            });
			
			$('#provider_form').validate({
				//errorLabelContainer:$('#provider_form .errors'),
				success:function(error){
					error.parents('.item').removeClass('error');
				},
				errorPlacement:function(error, element){
					if(error.html() == "")
						return;
					element.parents('.item').addClass('error');
					element.after(error);
				},
			});
        });
    </script>
    <style type="text/css">
	.item label.error { display:none !important; }
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-backend">
        	<?= $this->partial('partials/vendormainmenu.phtml', array('notifications'=> $this->pendingSettings,'active'=>'Profile','parentActive'=>'Account')); ?>
            <div class="listings-main">
            	<div class="sub-ttl">
	                Account - Profile
            	</div><!-- closes sub-ttl -->
            </div>
            <div class="vendor-profile">
                <form action="" id="provider_form" method="post">
                    <div class="profile-items">
                    	<?php if($this->errormessage): ?>
						<script type="text/javascript">
                        showError("<?= $this->errormessage ?>");
                        </script>
                        <?php endif ?>
                        <?php if($this->successmessage): ?>
                        <script type="text/javascript">
                        showAlert("Your changes have been saved");
                        </script>
                        <?php endif ?>	
                        <div class="item-wrppr">
                            <div class="item-ttl">
                                Company Information
                            </div><!-- closes item ttl -->
                            <div class="item first">
                                <input type="text" name="name" class="required noclean" value="<?= $this->vendor->name ?>" />
                                <h4>Name</h4>
                                <span>Your company name</span>
                            </div><!-- closes item -->
                            <div class="item">
                                <input type="text" name="email" class="required email noclean" value="<?= $this->vendor->email ?>" />
                                <h4>Email</h4>
                                <span>Set your email contact information</span>
                            </div><!-- closes item -->
                            <div class="item">
                                <input type="text" name="phone" class="required noclean" value="<?= $this->vendor->phone ?>" />
                                <h4>Phone</h4>
                                <span>Your contact phone</span>
                            </div><!-- closes item -->
                            <div class="item">
                                <select name="place_id" class="required">
	                                <option value="">Select your country</option>
                                	<?php foreach($this->countries as $c): ?>
                                    <?php $selected = ($c->id == $this->vendor->place_id) ? 'selected="selected"' : ''; ?>
                                    <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                                    <?php endforeach ?>
                                </select>
                                <h4>Country</h4>
                                <span>The country where you are based</span>
                            </div><!-- closes item -->
                            <div class="item">
                                <input type="text" name="address" class="noclean" value="<?= $this->vendor->address ?>" />
                                <h4>Location</h4>
                                <span>Your Office Location</span>
                            </div><!-- closes item -->
                            <div class="item last">
                                <input type="text" name="website" class="noclean" value="<?= $this->vendor->website ?>" />
                                <h4>Website</h4>
                                <span>Your company's website</span>
                            </div><!-- closes item -->
                            <div class="clear"></div>									
                        </div><!-- closes item-wrppr -->
                        <div class="item-wrppr">
                            <div class="item-ttl">
                                Profile Picture
                            </div><!-- closes item ttl -->
                            <div class="item last first">
                                <div class="picture">
                                	<?php $image = (!empty($this->user->image)) ? $this->user->image : '/images/default-profile.gif' ?>
                                	<?= $this->thumbnail(68,$image,'','1:1'); ?>
                                    <input type="file" name="file_upload" id="file_upload" />
                                </div>
                                <h4>Picture Requirements</h4>
                                <span>Should be square, preferably 100x100 pixels, <br />and in JPEG, GIF, or PNG format.</span>
                            </div><!-- closes item -->
                            <div class="clear"></div>
                        </div><!-- closes item-wrppr -->
                        <div class="item-wrppr">
                            <div class="item-ttl">
                                Company Members
                            </div><!-- closes item ttl -->
                            <div class="item first">
                                <ul class="controls">
                                    <li><a href="#finish_listing" class="edit f_b">Edit</a></li>
                                    <li><a href="" class="remove">Remove</a></li>
                                </ul>
                                <h4>Karina Romaine</h4>
                            </div><!-- closes item -->
                            <div class="item">
                                <ul class="controls">
                                    <li><a href="" class="edit">Edit</a></li>
                                    <li><a href="" class="remove">Remove</a></li>
                                </ul>
                                <h4>Karina Romaine</h4>
                            </div><!-- closes item -->
                            <div class="item">
                                <ul class="controls">
                                    <li><a href="" class="edit">Edit</a></li>
                                    <li><a href="" class="remove">Remove</a></li>
                                </ul>
                                <h4>Karina Romaine</h4>
                            </div><!-- closes item -->
                            <div class="item last">
                                <a href="#new_member" class="add-btn f_b">Add another Company Member</a>
                            </div><!-- closes item -->
                            <div class="clear"></div>									
                        </div><!-- closes item-wrppr -->
							
							
                        <div class="item-wrppr">
                            <div class="item-ttl">Live Chat</div>
                            <div class="item_descr">
                                <p>
                                    <strong>Connect your favorite IM Service</strong>
                                    Select the IM Service you prefer<br />
                                    to talk with your clients
                                </p>
                                <ul>
                                    <li><a class="btn-13 f_b" href="#lb_yahoo"><span class="yahoo">Connect with your Yahoo Account</span></a></li>
                                    <li><a class="btn-13 f_b" href="#lb_msn"><span class="msn">Connect with your MSN Account</span></a></li>
                                    <li><a class="btn-13 f_b" href="#lb_gtalk"><span class="gtalk">Connect with your GTalk Account</span></a></li>
                                </ul>
                            </div><!--ITEM_DESCR-->
                        </div><!-- closes item-wrppr -->
                        <div class="item-wrppr">
                            <div class="item-ttl">Language</div>
                            <div class="item_descr">
                                <p>
                                    <strong>Choose Language</strong>
                                    What language would you like to use?
                                </p>
                                <select class="language">
                                    <option>English</option>
                                    <option>Spanish</option>
                                </select>
                            </div><!--ITEM_DESCR-->
                        </div><!-- closes item-wrppr -->
                    </div><!-- closes profile-items -->
                    <div class="foot">
                        <input type="submit" class="btn-1 noclean" value="Save Changes" />
                        <a href="">Deactivate Account</a>
                    </div><!-- closes foot -->
                    <input type="hidden" name="ids" value="<?= $this->user->id ?>" />
                    <input type="hidden" name="vids" value="<?= $this->vendor->id ?>" />
                    <input type="hidden" name="user_token" value="<?= $this->user->token ?>" />
                    <input type="hidden" name="form_id" value="<?= md5($this->user->token.'provider_form') ?>" />
                </form>
            </div><!-- closes vendor-profile -->
        </div><!-- closes user-backend -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div class="hidden">
    <div class="lb_connect" id="lb_yahoo">
        <h2>Connect your Yahoo Account</h2>
        <form action="">
            <label>e-Mail</label>
            <input class="yahoo" type="text" value="" />
            <label>Password</label>
            <input type="password" value="" />
            <ul>
                <li><input type="button" class="btn-1" value="Connect" /></li>
                <li><input type="button" class="btn-13" value="Cancel" /></li>
            </ul>
        </form>
    </div><!--L_CONNECT-->
    <div class="lb_connect" id="lb_msn">
        <h2>Connect your Yahoo Account</h2>
        <form action="">
            <label>e-Mail</label>
            <input class="msn" type="text" value="" />
            <label>Password</label>
            <input type="password" value="" />
            <ul>
                <li><input type="button" class="btn-1" value="Connect" /></li>
                <li><input type="button" class="btn-13" value="Cancel" /></li>
            </ul>
        </form>
    </div><!--L_CONNECT-->
    <div class="lb_connect" id="lb_gtalk">
        <h2>Connect your Yahoo Account</h2>
        <form action="">
            <label>e-Mail</label>
            <input class="gtalk" type="text" value="" />
            <label>Password</label>
            <input type="password" value="" />
            <ul>
                <li><input type="button" class="btn-1" value="Connect" /></li>
                <li><input type="button" class="btn-13" value="Cancel" /></li>
            </ul>
        </form>
    </div><!--L_CONNECT-->
    
    <div class="lb_connect" id="new_member">
        <h2>Add a New Company Member</h2>
        <form action="">
            <label>First Name</label>
            <input type="text" value="" />
            <label>Last Name</label>
            <input type="text" value="" />
            <label>Position</label>
            <input type="text" value="" />
            <label>Contact e-mail</label>
            <input type="text" value="name@example.com" />
            <label>Phone</label>
            <input type="text" class="code" value="Code" />
            <input type="text" class="number" value="Number" />
            <input type="text" class="ext" value="Ext" />
            <ul>
                <li><input type="button" class="btn-1" value="Add Member" /></li>
                <li><input type="button" class="btn-13" value="Cancel" /></li>
            </ul>
        </form>
    </div><!--NEW-MEMBER-->
    <div id="finish_listing">
        <h3>Your listing has been sent!</h3>
        <p>Tripfab had received your listing.  We must to check everything is ok with your listing.  We'll notify you when is ready to be watched by the entire world. Thanks!</p>
        <div class="bottom">
            <a href="" class="btn-1">Okay</a>
        </div><!--BUTTONS-->
    </div><!--FINISH_LISTING-->
</div><!--HIDDEN-->
</body>
</html>