<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Profile | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/js/jwysiwyg/jquery.wysiwyg.css" />
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js2/jquery.input.value.js"></script>
    <script type="text/javascript" src="/js/jquery.jqtransform.js"></script>
    <script type="text/javascript" src="/js2/jquery.elastic.js"></script>
    <script type="text/javascript" src="/js2/common.js"></script>
	<script type="text/javascript" src="/js/jwysiwyg/jquery.wysiwyg.js"></script>
    <script type="text/javascript" src="/js/jwysiwyg/controls/wysiwyg.link.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('select').jqTransSelect();
			
			$('textarea.wysiwyg').wysiwyg({
				initialContent:'',
				rmUnusedControls:true,
				controls:{
					bold:{ visible:true },
					italic:{ visible:true },
					underline:{ visible:true },
					justifyLeft:{ visible:true },
					justifyCenter:{ visible:true },
					justifyRight:{ visible:true },
					insertOrderedList:{ visible:true },
					insertUnorderedList:{ visible:true },
					createLink:{ visible:true },
					h3:{ visible:true },
					paragraph:{ visible:true },
				}
			});
        });
    </script>
    <style type="text/css">
	textarea.wysiwyg { width:730px; height:500px;}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="listing-wrapper wrapper">
			<?= $this->partial('partials/vendormainmenu.phtml', array('notifications'=> $this->pendingSettings,'active'=>'All Listings','parentActive'=>'Listings')); ?>   
            <?= $this->partial('partials/vendorlistingstop.phtml', array('listing'=>$this->listing)); ?>
            <div class="listing-content show">
                <div class="left">
                    <?= $this->partial('partials/vendorlistingsmenu.phtml', array('active'=>'Details', 'id' => $this->listing->id, 
									   'type'=>$this->listing->main_type)) ?>
                </div><!-- closes left -->
                <form action="" method="post" id="form_tab_<?= $tab->id ?>">
                    <div class="right">
                        <div class="lstng-details">
                            <div class="lstng-detail">
                                <strong><?= $this->tab->title ?></strong>
                            </div><!-- closes lstng-detail -->
                            <div class="lstng-detail">
                                <textarea class="wysiwyg noclean" name="text"><?= $this->tab->text ?></textarea>
                            </div><!-- closes lstng-detail -->
                        </div><!-- closes lstng-details -->
                        <div class="foot">
                            <input type="submit" class="btn-1" value="Save Changes" />
                            <a href="">Deactivate Listing</a>
                        </div><!-- closes foot -->
                    </div><!-- closes right -->
                    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
                    <input type="hidden" name="tab_id" value="<?= $this->tab->id ?>" />
                    <input type="hidden" name="tab_token" value="<?= $this->tab->token ?>" />
                    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
                    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'form_tab_'.$this->tab->id) ?>" />
                    <input type="hidden" name="_task" value="<?= md5('edit_tab') ?>" />
                </form>
                <div class="clear"></div>
            </div><!-- closes listing-content -->
        </div><!-- closes listing-wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
</body>
</html>