<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> : Set Pricing | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />    
	<script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {			
			$('a.lb').fancybox({
				padding:0,
				overlayColor:'#000',
				centerOnScroll:1,
				overlayOpacity:0.3,
				showCloseButton:0,
			});
			$('input[name=starting]').each(function(){
				$val = $(this).val();
				$(this).datepicker({
					dateFormat:'M dd, yy',
					defaultDate:$val,
					onSelect:function(date){
						$('input[name=ending]').datepicker('option','minDate', date);
					},
				});
			});
			$('input[name=ending]').each(function(){
				$val = $(this).val();
				$(this).datepicker({
					dateFormat:'M dd, yy',
					defaultDate:$(this).val(),
				});
			})
			
			$('.carrousel').accordion();
			$('.pricing-tabs').tabs();
			
			$('#ui-datepicker-div').wrap('<div id="calendarContainer"></div>');
			
			$('input.sameprice').change(function(){
				if($(this).attr('checked') == undefined){
					$item = $(this).parents('.pricing-itm');
					$('input.kids', $item).removeAttr('disabled');
				} else {
					$item = $(this).parents('.pricing-itm');
					$('input.kids', $item).attr('disabled','disabled');
				}
			});
        });
    </script>
    <style type="text/css">
	.hidden { display:none;}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="listing-wrapper wrapper">
			<?= $this->partial('partials/vendormainmenu.phtml', array('notifications'=> $this->pendingSettings,'active'=>'All Listings','parentActive'=>'Listings')); ?>
            <?= $this->partial('partials/vendorlistingstop.phtml', array('listing'=>$this->listing)); ?>
            <div class="listing-content show">
                <div class="left">
                    <?= $this->partial('partials/vendorlistingsmenu.phtml', array('active'=>'Pricing', 'id' => $this->listing->id, 
									   'type'=>$this->listing->main_type)) ?>
                </div><!-- closes left -->
                <div class="right">
                    <?php 	switch($this->listing->main_type):
							case 2:
								echo $this->partial('listing/restaurant/pricing.phtml', array(
										'listing' 		=> $this->listing,
										'schedules'		=> $this->schedules,
										'sch'			=> $this->sch,
										'seasons'		=> $this->seasons,
										'season'		=> $this->season,
										'basic_price'	=> $this->basic_price,
										'persons'		=> $this->persons,
										'help'			=> $this->help,
								));
								break;
							case 4:
								echo $this->partial('listing/sight/pricing.phtml', array(
										'listing' 		=> $this->listing,
										'schedules'		=> $this->schedules,
										'sch'			=> $this->sch,
										'seasons'		=> $this->seasons,
										'season'		=> $this->season,
										'basic_price'	=> $this->basic_price,
										'persons'		=> $this->persons,
										'help'			=> $this->help,
								));
								break;
							case 5:
								echo $this->partial('listing/hotel/pricing.phtml', array(
										'listing' 		=> $this->listing,
										'schedules'		=> $this->schedules,
										'sch'			=> $this->sch,
										'seasons'		=> $this->seasons,
										'season'		=> $this->season,
										'basic_price'	=> $this->basic_price,
										'persons'		=> $this->persons,
										'help' 			=> $this->help,
								));
								break;
							case 6:
								echo $this->partial('listing/activity/pricing.phtml', array(
										'listing' 		=> $this->listing,
										'schedules'		=> $this->schedules,
										'sch'			=> $this->sch,
										'seasons'		=> $this->seasons,
										'season'		=> $this->season,
										'basic_price'	=> $this->basic_price,
										'persons'		=> $this->persons,
										'help' 			=> $this->help,
										'types'			=> $this->types,
								));
								break;
							case 7:
								echo $this->partial('listing/entertaiment/pricing.phtml', array(
										'listing' 		=> $this->listing,
										'schedules'		=> $this->schedules,
										'sch'			=> $this->sch,
										'seasons'		=> $this->seasons,
										'season'		=> $this->season,
										'basic_price'	=> $this->basic_price,
										'persons'		=> $this->persons,
										'help' 			=> $this->help,
								));
								break;
						endswitch ?>
                </div><!-- closes right -->
                <div class="clear"></div>
            </div><!-- closes listing-content -->
        </div><!-- closes listing-wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
</body>
</html>