<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> - <?= $this->city->title ?>, <?= $this->country->title ?> | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/jquery-ui-1.8.16.custom.css" />
    <link type="text/css" rel="stylesheet" href="/css2/index/listing-activity.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <style type="text/css">
	.noprice {
		float:right;
		font-size:12px;
		color:#898989;
		line-height:15px;
		text-align:center;
		margin-top:10px;}
		.noprice p {
			font-size:12px;
			line-height:15px;
			display:inline;
			float:none;}
		.noprice a {
			color:#60b5f7;
			font-size:12px;
			line-height:15px;
			display:inline;
			float:none;}
	</style>
</head>
<body>
<div class="w1">
	<?= $this->partial('partials/header.phtml', 
	array('user'=>$this->user,'full'=>true)); ?>
    <div class="w2">
        <div class="main wrapper">
        	<?= $this->partial('partials/vendormainmenu.phtml', array('notifications'=> $this->pendingSettings,'active'=>'All Listings','parentActive'=>'Listings')); ?>
            <div class="content-2">
                <div class="box">
                    <?= $this->partial('partials/gallery.phtml', 
					array('user'=>$this->user, 'listing' => $this->listing, 'city' => $this->city, 
						  'country' => $this->country,'pictures' => $this->pictures,'trips'=>$this->trips)); ?>
                    <?php // $this->partial('partials/tabs.phtml',  array('listing' => $this->listing, 'tabs' => $this->tabs, 'faqs' => $this->faqs, 'map' => true)); ?>
                </div><!-- closes box -->
                <div class="tabs-wrapper-2">
                    <ul>
                        <li><a href="#tabs-1">Overview</a></li>
                        <li><a href="#tabs-2">Amenities</a></li>
                        <li><a href="#tabs-3">Rooms</a></li>
                        <li><a href="#tabs-4">FAQ's</a></li>
                        <li><a href="#tabs-5">How to Get There</a></li>
                    </ul>
                    <div class="tab" id="tabs-1">
                    	<?php if(!empty($this->overview->about) or
									!empty($this->overview->about) or
									!empty($this->overview->about)): ?>
                        <div class="tab-ttl">About your stay</div>
                        <div class="tab-content">
                        	<?php if(!empty($this->overview->about)): ?>
                        	<p><?= stripslashes(nl2br($this->overview->about)) ?></p>
                            <?php endif; if(!empty($this->overview->expect)): ?>
                            <h2>What to expect</h2>
                            <p><?= stripslashes(nl2br($this->overview->expect)) ?></p>
                            <?php endif; if(!empty($this->overview->love)): ?>
                            <h2>Things you'll love</h2>
                            <p><?= stripslashes(nl2br($this->overview->love)) ?></p>
                            <?php endif ?>
                        </div><!-- closes tab-content -->
                        <?php else: ?>
                        <div class="tab-content">
	                        <a href="/provider/listings/overview/<?= $this->listing->id ?>"><img src="/images2/empty-overview.gif" /></a>
                        </div>
                        <?php endif ?>
                        <div class="message">
                            <div>
                                <p><strong>Check in</strong></p>
                                <?php if(!empty($this->listing->checkin) and $this->listing->checkin != '00:00:00'): ?>
                                <p><?= date('g:i A', strtotime($this->listing->checkin)) ?></p>
                                <?php else: ?>
                                <p><a style="color:#60B5F7" href="/provider/listings/edit/<?= $this->listing->id ?>">Add now</a></p>
                                <?php endif ?>
                            </div>
                            <div>
                                <p><strong>Check out</strong></p>
                                <?php if(!empty($this->listing->checkout) and $this->listing->checkout != '00:00:00'): ?>
                                <p><?= date('g:i A', strtotime($this->listing->checkout)) ?></p>
                                <?php else: ?>
                                <p><a style="color:#60B5F7" href="/provider/listings/edit/<?= $this->listing->id ?>">Add now</a></p>
                                <?php endif ?>
                            </div>
                            <div>
                                <p><strong>Room Types</strong></p>
                                <?php if($this->rooms): ?>
                                <p><?= count($this->rooms) ?></p>
                                <?php else: ?>
                                <p><a style="color:#60B5F7" href="/provider/listings/edit/<?= $this->listing->id ?>">Add now</a></p>
                                <?php endif ?>
                            </div>
                        </div><!-- closes message -->
                    </div><!-- closes tab -->
                    <div class="tab" id="tabs-2">
                    	<?php $ok = true; $i=0; $limit = count($this->details) ?>
                        <?php $ok1 = true; $ok3 = true; ?>
                        <?php while($i<$limit) { 
								if($this->details[$i]->type == 1) {$ok = false; $ok1 = false; }
								if($this->details[$i]->type == 3) {$ok = false; $ok3 = false; }
								$i++; } ?>
						<?php if(!$ok or (count($this->listing_amenities) > 0)): ?>
                        <div class="tab-ttl">
                            Some details about the hotel
                        </div><!-- closes tab-ttl -->
                        <div class="tab-content">
                        	<?PHP if(!$ok1 or (count($this->listing_amenities) > 0)): ?>
                            <h2>Hotel Amenities</h2>
                            <ul>
                            	<?php foreach($this->listing_amenities  as $amm): ?>
                                <li><?= $this->def_amenities[$amm]->name ?></li>
                                <?php endforeach ?>
                                <?php foreach($this->details as $detail): ?>
                                <?php if($detail->type == 1): ?>
                                <li><?= stripslashes($detail->text) ?></li>
                                <?php endif ?>
                                <?php endforeach ?>
                            </ul>
                            <?php endif; if(!$ok3): ?>
                            <h2>Policies</h2>
                            <ul>
                                <?php foreach($this->details as $detail): ?>
                                <?php if($detail->type == 3): ?>
                                <li><?= stripslashes($detail->text) ?></li>
                                <?php endif ?>
                                <?php endforeach ?>
                            </ul>
                            <?php endif ?>
                        </div><!-- closes tab-content -->
                        <?php else: ?>
                        <div class="tab-content">
                            <a href="/provider/listings/details/<?= $this->listing->id ?>"><img src="/images2/empty-amanities.gif" /></a>
                        </div>
                        <?php endif ?>
                    </div><!-- closes tab -->
                    <div class="tab" id="tabs-3">
                    	<?php if(count($this->rooms) > 0): ?>
                        <div class="tab-ttl">
                            Our Room Types
                        </div><!-- closes tab-ttl -->
                        <div class="tab-content">
                        	<?php foreach($this->rooms as $room): ?>
                            <h2><?= $room->name ?></h2>
                            <ul>
                            	<?php if(!empty($room->description)): ?>
                                <li><?= $room->description ?></li>
                                <?php endif ?>
                                <li>Minimum Stay: <?= $room->nights ?> <?= (count($room->nights) > 1) ? "nights" : 'night' ?>   </li>
                                <li>Maximum Accomodation: <?= $room->people ?> <?= (count($room->people) > 1) ? "people" : 'person' ?></li>
                                <li>
                                	<?= $room->bedrooms ?> <?= (count($room->bedrooms) > 1) ? "Bedrooms" : 'Bedroom' ?>  
                                </li>
                                <?php foreach($this->beds[$room->id] as $bed): ?>
                                <li><?= $bed->quantity ?> <?= $bed->type ?> <?= (count($room->quantity) > 1) ? "Beds" : 'Bed' ?></li>
                                <?php endforeach ?>
                                <li><b>Amenities</b>
                                <ul>
                                <?php foreach($this->room_amenities[$room->id] as $amm): ?>
                                <li><?= $this->amenities[$amm]->name ?></li>
                                <?php endforeach ?>
                                </ul></li>
                            </ul>
                            <?php endforeach ?>
                        </div><!-- closes tab-content -->
                        <?php else: ?>
                        <div class="tab-content">
                        	<a href="/provider/listings/rooms/<?= $this->listing->id ?>"><img src="/images2/empty-rooms.gif" /></a>
                        </div>                        
                        <?php endif ?>
                    </div><!-- closes tab -->
                    <div class="tab" id="tabs-4">
                        <?php if(count($this->faqs) > 0): ?>
                        <div class="tab-ttl">
                            Frequently Asked Questions
                        </div><!-- closes tab-ttl -->
                        <div class="tab-content faqs">
                            <ul>
                            	<?php foreach($this->faqs as $faq): ?>
                                <li>
                                    <strong><?= stripslashes(nl2br($faq->question)) ?></strong><br />
                                    <?= stripslashes(nl2br($faq->answer)) ?>
                                </li>
                                <?php endforeach ?>
                            </ul>
                        </div><!-- closes tab-content -->
                        <?php else: ?>
                        <div class="tab-content">
                        	<a href="/provider/listings/faqs/<?= $this->listing->id ?>"><img src="/images2/empty-faqs.gif" /></a>
                        </div>
                        <?php endif ?>
                    </div><!-- closes tab -->
                    <div class="tab" id="tabs-5">
                        <?php if(!empty($this->getthere->plane) or
									!empty($this->getthere->car) or
									!empty($this->getthere->train) or
									!is_null($this->listing->lat)): ?>
                        <div class="tab-ttl">
                            How to get there
                        </div><!-- closes tab-ttl -->
                        <div class="tab-content there">	
                        	<?php if(!empty($this->getthere->plane)): ?>
                            <h2>By plane</h2>
                            <p><?= stripslashes(nl2br($this->getthere->plane)) ?></p>
                            <?php endif; if(!empty($this->getthere->car)): ?>
                            <h2>By car</h2>
                            <p><?= stripslashes(nl2br($this->getthere->car)) ?></p>
                            <?php endif; if(!empty($this->getthere->train)): ?>
                            <h2>By train</h2>
                            <p><?= stripslashes(nl2br($this->getthere->train)) ?></p>
                            <?php endif; ?>
                            <div id="mapcanvas"></div>
                        </div><!-- closes tab-content -->
                        <div class="message">
                            <address>
                                <p><strong>Detailed Address</strong></p>
                                <p><?= $this->listing->address ?></p>
                            </address>
                        </div><!-- closes message -->
                        <?php else: ?>
                        <div class="tab-content">
                        	<a href="/provider/listings/location/<?= $this->listing->id ?>"><img src="/images2/empty-getthere.gif" /></a>
                        </div>
                        <?php endif ?>
                    </div><!-- closes tab -->
                </div><!-- closes tabs-wrapper -->	                
                <div class="reviews-wrapper">
                    <?= $this->partial('partials/reviews.phtml', 
					array('reviews' => $this->reviews, 'questions' => $this->questions, 'answer_allow' => false,
						  'user'=>$this->user, 'listing' => $this->listing->id)); ?>
                </div><!-- closes reviews-wrapper -->
            </div><!-- closes content-2 -->
            
            <div class="right-sidebar">               
                <form id="booking" method="post" action="">
                    <div class="widget book">
                        <div class="ttl">
                            <span>From only</span>
                            <?php if($this->listing->price > 0): ?>
                            <strong>$<?= $this->listing->price ?> <span>/ person</span></strong>
                            <?php else: ?>
                            <div class="noprice">
                            	<p>There isn't pricing info yet<br />
                                <a href="/provider/listings/pricing/<?= $this->listing->id ?>">Set Pricing now</a></p>
                            </div>
                            <?php endif ?>
                        </div><!-- closes ttl -->
                        <ul>
                            <li id="acordion">                            
                                <a href=""><span>Select the date</span><img src="/images/arrow-46.png" alt="" class="arrow" />
                                <strong id="checkinlabel"></strong></a>
                                <div id="datepicker" class="datepicker"></div>
                                <a href=""><span>Checkout</span><img src="/images/arrow-46.png" alt="" class="arrow" />
                                <strong id="checkoutlabel"></strong></a>
	                            <div id="datepicker-2" class="datepicker"></div>
                                <a href=""><span>Occupation</span><img src="/images/arrow-46.png" alt="" class="arrow" /></a>
                                <div class="occupation">
                                	<div class="room-types">
                                        <strong>Choose a room type</strong>
                                        <ul>
											<?php foreach($this->options as $option): ?>
                                            <li>
                                                <input id="sch<?= $option->id ?>" name="option" value="<?= $option->id ?>" type="radio" />
                                                <label for="sch<?= $option->id ?>"><?= $option->name ?></label>
                                                <span><strong>$<?= $this->prices[$option->id]['price'] ?></strong> / night
                                                <strong>Max <?= $this->prices[$option->id]['max'] ?> people</strong> per room</span>
                                            </li>
                                            <?php endforeach ?>
                                        </ul>
                                    </div><!-- closes room-types -->
                                    <p>
                                        <label>Adults</label>
                                        <select class="ocp adt"  name="adults">
                                            <?php for($i=1; $i<=12; $i++): ?>
                                            <option value="<?= $i ?>"><?= $i ?></option>
                                            <?php endfor ?>
                                        </select>
                                    </p>
                                    <p>
                                        <label>Kids</label>
                                        <select class="ocp kid" name="kids">
                                            <option value="0">0</option>
                                            <?php for($i=1; $i<=12; $i++): ?>
                                            <option value="<?= $i ?>"><?= $i ?></option>
                                            <?php endfor ?>
                                        </select>
                                    </p>
                                    <div class="clear"></div>
                                </div><!-- closes ocupation -->
                            </li>
                        </ul>
                        <div class="summary">
                            <span>Subtotal <strong id="Subtotal">$<?= $this->listing->price ?></strong></span>
                            <input type="submit" value="Book Now!" class="btn-1" />
                        </div><!-- closes summary -->
                	</div><!-- closes widget -->
                	<?php foreach($this->form_fields as $name => $value): ?>
                    <input type="hidden" name="<?= $name ?>" value="<?= $value ?>" />
                    <?php endforeach ?>
                    <input type="hidden" name="checkin" id="inputCheckin" value="" />
                    <input type="hidden" name="checkout" id="inputCheckout" value="" />
                </form>
                <div class="widget talk">
                    <?= $this->partial('partials/talk.phtml', array('vendor'=>$this->vendor,'user' => $this->user)); ?>
                </div><!-- closes widget -->
            </div><!-- closes right-sidebar -->
        </div><!-- closes main -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div id="citiesAutocompleteContainer"></div>
<input type="hidden" value="<?= ($this->listing->lat) ? $this->listing->lat : 'none' ?>" name="listlat" />
<input type="hidden" value="<?= ($this->listing->lng) ? $this->listing->lng : 'none' ?>" name="listlng" />
<input type="hidden" value="<?= $this->listing->title ?>" name="listtitle" />
<input type="hidden" value="<?php foreach($this->disabledDates as $d): ?><?= $d ?>,<?php endforeach ?>" name="diableddates" />

<div class="hidden">
	<div id="send_message">
        <form action="" id="sendMessageForm">
            <div class="lb-forgot">
                <div class="ttl">Send a message to <?= $this->vendor->name ?></div>
                <div class="content">
                    <textarea cols="30" name="message" rows="1"></textarea>
                </div><!-- closes content -->
                <div class="bottom">
                    <input type="submit" class="btn-1" value="Send Message" />
                    <span onclick="$.fancybox.close()" class="btn-4">Cancel</span>				
                </div><!-- closes bottom -->
            </div><!-- closes lb-forgot -->
            <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
        </form>
    </div>
    <div id="live_chat">
    	<img src="/images2/chat.png" />
    </div>
    <div id="start_call">
    	<img src="/images2/phone.png" />
    </div>
</div>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/index/listing-hotel.js"></script>
</body>
</html>