<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Unreplied Messages | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/messages.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
	<script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript" src="/js2/user/messages.js"></script>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages">
            <?= $this->partial('partials/vendormainmenu.phtml', array('notifications'=> $this->pendingSettings,'active'=>'Never Responded','parentActive'=>'Messages')); ?>
            <div id="features">
                <div class="top centered">
                    <h2>Messages</h2>
                    <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lorem risus, malesuada et elementum sit amet.</h3>
                    <img src="/images2/img-59.png" alt="" />
                    <img src="/images2/img-49.png" alt="" class="corner" />
                </div>
                <!-- closes top -->
                <div class="bottom">
                    <img src="/images2/img-46.png" alt="" class="izq" />
                    <h4>Lorem ipsum dolor sit amet</h4>
                    <p>Consectetur adipiscing elit. In lorem risus, malesuada et elementum sit amet, varius quis tellus. Vivamus elementum ipsum sit amet purus venenatis sed lacinia arcu euismod. Consectetur adipiscing elit. In lorem risus, malesuada et elementum sit amet, varius quis tellus. Vivamus elementum ipsum sit amet purus venenatis sed.</p>
                    <div class="clear"></div>
                    <img src="/images2/img-47.png" alt="" class="izq" />
                    <h4>Lorem ipsum dolor sit amet</h4>
                    <p>Consectetur adipiscing elit. In lorem risus, malesuada et elementum sit amet, varius quis tellus. Vivamus elementum ipsum sit amet purus venenatis sed lacinia arcu euismod. Consectetur adipiscing elit. In lorem risus, malesuada et elementum sit amet, varius quis tellus. Vivamus elementum ipsum sit amet purus venenatis sed.</p>
                    <div class="clear"></div>
                    <img src="/images2/img-48.png" alt="" class="izq" />
                    <h4>Lorem ipsum dolor sit amet</h4>
                    <p>Consectetur adipiscing elit. In lorem risus, malesuada et elementum sit amet, varius quis tellus. Vivamus elementum ipsum sit amet purus venenatis sed lacinia arcu euismod. Consectetur adipiscing elit. In lorem risus, malesuada et elementum sit amet, varius quis tellus. Vivamus elementum ipsum sit amet purus venenatis sed.</p>
                </div>
                <!-- closes bottom -->
            </div>
            <!-- closes features -->
        </div>
        <!-- closes user-messages -->
    </div>
    <!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div>
<!-- closes w1 -->
</body>
</html>