<h3 class="title">General Information <a href="/admin/users/travellers" class="back">Back to Travelers</a></h3>
<div class="block">

<div class="image"><img src="images2/img-75.gif" width="134" height="134" alt="" /></div><!--IMAGE-->
<table width="590" border="0" class="info">
    <tr>
        <th width="180">First Name</th>
        <td><?php echo $this->user->name?></td>
    </tr>
    <tr>
        <th>Last Name</th>
        <td><?php echo $this->user->lname?></td>
    </tr>
    <tr>
        <th>E-mail</th>
        <td><?php echo $this->user->email?></td>
    </tr>
    <tr>
        <th>Age</th>
        <td><?php echo $this->user->age?></td>
    </tr>
    <tr>
        <th>Birthday</th>
        <td><?php echo date('M d, Y', strtotime($this->user->birthdate))?></td>
    </tr>
    <tr>
        <th>Country</th>
        <td><?php echo $this->user->countryName?></td>
    </tr>
    <tr>
        <th>City</th>
        <td><?php echo $this->user->cityName?></td>
    </tr>
</table>
</div><!--BLOCK-->
