<div class="tabs-wrapper-2">
    <ul>
        <?php foreach($this->tabs as $k => $tab): ?>
        <li><a href="#tab<?= $k ?>"><?= $tab->label ?></a></li>
        <?php endforeach ?>
        <li><a href="#faqs_tab">FAQ's</a></li>
        <?php if($this->map): ?>
        <li><a href="#map_tab">Map</a></li>
        <?php endif ?>
    </ul>
    <?php foreach($this->tabs as $k=>$tab): ?>
    <div id="tab<?= $k ?>" class="tab">
        <h5><?= $tab->label ?></h5>
        <?= stripslashes($tab->text) ?>
    </div><!-- closes tab -->
    <?php endforeach ?>
    <div id="faqs_tab" class="tab">
        <?php foreach($this->faqs as $faq): ?>
        <p><strong><?= $faq->question ?></strong><br />
        <?= $this->escape($faq->answer) ?></p>
        <?php endforeach ?>
    </div><!-- closes tab -->
    <?php if($this->map): ?>
    <div id="map_tab" class="tab">
        <div id="mapcanvas"></div>
        <p><strong>Detailed Address</strong><br />
        <?= $this->listing->address ?></p>
    </div><!-- closes tab -->
    <?php endif ?>
</div><!-- closes tabs-wrapper -->