<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Let us bring you thousands of travelers for free | Tripfab</title>
    <link type="text/css" rel="stylesheet" href="/css4/all.css" />
    <script type="text/javascript" src="http://tripfab.com/js2/jquery.js"></script>
    <script type="text/javascript" src="/js4/scroll-startstop.events.jqueary.js"></script>
    <script type="text/javascript">
	$(function(){
		$('.language a.current').click(function(){
			$(this).toggleClass('active');
			$('.language .select').toggleClass('show');
			return false;
		});
		jQuery('#other-features ul').jcarousel();
	});
	</script>
</head>
<body class="landing">
<div id="header-shadow">
    <div id="header">
        <div class="wrapper">
            <h1 class="logo"><a href="/<?= $this->lang ?>">TripFab</a></h1>
            <div class="right">
                <div class="language">
                    <a class="current" href="#"><?= $this->translate('language') ?></a>
                    <div class="select">
                        <ul>
                            <?php $class = ($this->lang == 'en-US') ? 'active' : '' ?>
                            <li class="en <?= $class ?>"><a href="/en-US/about">English</a></li>
                            <?php $class = ($this->lang == 'es-ES') ? 'active' : '' ?>
                            <li class="es <?= $class ?>"><a href="/es-ES/about">Español</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="right">
                <a href="/<?= $this->lang ?>/login" class="btn-1"><?= $this->translate('signin') ?></a>
                <?= $this->translate('Have an account') ?>
            </div><!-- closes right -->
        </div><!-- closes wrapper -->				
    </div><!-- closes header -->
</div><!-- closes header-shadow -->

<div id="top">			
    <div class="content wrapper">
        <div class="video-wrapper">
            <img src="/images4/img-1.png" alt="" />
        </div><!-- closes video-wrapper -->
        <h2>Let us bring you thousands of travelers <em>for free</em></h2>
        <p>Hotels, Tour Operators, Transportation Services, and <br />everything in between contact us now to sign up and be <br />a part of the Tripfab platform.</p>
        <a href="/<?= $this->lang ?>/signup" class="btn-2">Get an Invitation</a>
        <img src="/images4/img-2.png" alt="" />
        <div class="clear"></div>
        <h3>Why should you get on TripFab?</h3>
        <h4>We make it <em>effortless!</em></h4>
        <div id="main-features">
            <div class="centered">
                <div>
                    <h2><span>1</span>Control your Business</h2>
                    <p><strong>You get to have total control of your offers</strong></p>
                    <p>With TripFab you get total control of the services you offer, who your offer them to and the ability to make changes, promos and more at any time.</p>
                </div>
                <div>
                    <h2><span>2</span>Exposure to Millions</h2>
                    <p><strong>You will be seen by millions of TripFab users</strong></p>
                    <p>TripFab platform puts your business in front of the eyes of millions of people interested in your services right when they need them.</p>
                </div>
                <div>
                    <h2><span>3</span>Payments</h2>
                    <p><strong>Organize, receive and control all payments</strong></p>
                    <p>You get instant access to all your received and pending payments in one single place, making payment management easy and efficient.</p>
                </div>
            </div><!-- closes centered -->
        </div><!-- closes main features -->				
    </div><!-- closes content -->
</div><!-- closes top -->
<div id="main">
    <div class="wrapper">
        <div id="menu">
            <ul>
                <li class="item-1"><a id="to-scroll1"><img src="/images4/cleardot.gif" alt="" /><br />How Tripfab <br />Works</a></li>
                <li class="item-2"><a id="to-scroll2"><img src="/images4/cleardot.gif" alt="" /><br />Customer <br />Management</a></li>
                <li class="item-3"><a id="to-scroll3"><img src="/images4/cleardot.gif" alt="" /><br />Payments <br />&amp; Sales</a></li>
            </ul>
        </div><!-- closes menu -->
        <div class="container">
            <div class="ttl" id="scroll-1">
                <span>Learn everything about</span>
                <h2>How Tripfab Works</h2>
                <strong>TripFab connects businesses directly with travelers - no middle men involved.</strong>
            </div><!-- closes ttl -->
            <div class="section">
                <img src="/images4/img-3.png" alt="" class="right" />
                <h3>No More Travel Agents</h3>
                <p>TripFab is allowing travelers for the first time to be their own travel agent. They can discover travel businesses and book travel tours, activities, hotels, transportation and everything in between, directly from you - the businesses from the TripFab platform.</p>
            </div><!-- closes section -->
            <div class="section">
                <div class="video right">
                    <img src="/images4/img-4.png" alt="" />							
                </div><!-- closes video -->
                <h3>A Travel Search Engine</h3>
                <p>We are basically a travel search engine, that gives travelers the ability to find and discover where they want to go, and then book their entire trip all in one place with one transaction directly from businesses. We are just a marketplace connecting travelers with you.</p>						
            </div><!-- closes section -->
            <div class="section">
                <div class="sub-section sub-1">
                    <h4><img src="/images4/cleardot.gif" alt="" />We Help You Sell Better</h4>
                    <p>Businesses get a profile and the ability to list their services and make them available for purchase via listings. We provide businesses with listings pages that help you sell your services in an easy, accurate way.</p>
                </div><!-- closes sub-section -->
                <div class="sub-section sub-2">
                    <h4><img src="/images4/cleardot.gif" alt="" />Talk Directly With Clients</h4>
                    <p>Potential customers can communicate directly with you on your custom listings page via our messaging system, live chat, or they can call you completely free no matter where they are located.</p>
                </div><!-- closes sub-section -->
                <div class="sub-section sub-3 last">
                    <h4><img src="/images4/cleardot.gif" alt="" />Promote Your Business</h4>
                    <p>You will be able to promote your business in a more personalized and efficient way to others: providing single users with special discounts, instant assistance, and customer service that will make you stand out.</p>
                </div><!-- closes sub-section -->
                <div class="clear"></div>
                <a class="back">Back to Top</a>
            </div><!-- closes section -->
            <div class="ttl" id="scroll-2">
                <span>Customer</span>
                <h2>Management</h2>
                <strong>Our platform makes reservations, payments, and bookings insanely simple yet powerful.</strong>
            </div><!-- closes ttl -->
            <div class="section">
                <img src="/images4/img-5.png" alt="" class="left" />
                <h3>Control Reservations</h3>
                <p>We give you the ability to approve or decline reservations. Maybe someone just booked and paid for a reservation, and you guys are completely full that day? Before the customers card is charged, you can accept or decline that reservation. No worries.</p>
            </div><!-- closes section -->
            <div class="section">
                <div class="video left">
                    <img src="/images4/img-9.png" alt="" />
                </div><!-- closes video -->
                <h3>Manage all TripFab sales in one place.</h3>
                <p>You can view and manage all the sales you made all from our account center in our application. It makes accounting a breeze and gives you quick access to check on that reservation. We also send you email reminders to let you know when that clients is coming. Just so you remember! :)</p>											
            </div><!-- closes section -->
            <div class="section">
                <div class="sub-section sub-4">
                    <h4><img src="/images4/cleardot.gif" alt="" />Custom Cancellation Policies</h4>
                    <p>We give you complete control over your listings and reservations. You can select your own custom cancellation policy that fills  your requirements. This is your company. </p>
                </div><!-- closes sub-section -->
                <div class="sub-section sub-5">
                    <h4><img src="/images4/cleardot.gif" alt="" />Seasonal Pricing</h4>
                    <p>You have complete control over your pricing. Maybe you have a high season and a low season with different pricing requirements? You have complete control of what you charge and when. </p>
                </div><!-- closes sub-section -->
                <div class="sub-section sub-6 last">
                    <h4><img src="/images4/cleardot.gif" alt="" />Control Your Calendar</h4>
                    <p>We give you the ability to share your schedule publicly and block out days you are closed, full or just plain unavailable letting potential customers know you can't take reservations that day. </p>
                </div><!-- closes sub-section -->	
            </div><!-- closes section -->
            <div class="section s-w">
                <div class="squares">
                    <div id="first-square">
                        <div class="square-1">
                            <h4>All your different services managed in one place</h4>
                            <p>It does not matter if you offer one or multiple services, packages or even one simple tour or accomodations, you will have total control of every single offer, the simplest way possible. Tripfab is amazingly organized and user friendly.</p>
                        </div>
                        <div class="square-2">
                            <h4>Update your pricing according to your needs</h4>
                            <p>You can manage all types of pricing on your services according to your needs: have seasonal pricing, special offers, last minute discounts? Update, change or review your prices one single platform.</p>
                        </div>
                        <div class="clear"></div>
                        <div class="square-3">
                            <h4>Bookings Management and Calendar</h4>
                            <p>Update your calendar when you need or want to, accomodate schedules by hourly, daily or even monthly availability. Provide real time schedules and choices to your customers with a few simple steps.</p>
                        </div>
                        <div class="square-4">
                            <h4>High Quality Content and Pictures</h4>
                            <p>Use your TripFab profile to provide potential clients with high quality images, video and detailed information about each and every one of your services: updates, changes and additions can be made easily and your customers can see what you have to offer knowing they are getting TripFab high quality information displayed.</p>
                        </div>
                    </div><!-- closes first-square -->							
                </div><!-- closes squares -->
                <div class="clear"></div>
                <a class="back">Back to Top</a>
            </div><!-- closes section -->
            <div class="ttl" id="scroll-3">
                <span>About the</span>
                <h2>Payments &amp; Sales</h2>
                <strong>After we told you about thousands more reservations, wondering how you get paid?</strong>
            </div><!-- closes ttl -->
            <div class="section">
                <img src="/images4/img-6.png" alt="" class="right" />
                <h3>We Give You Lots Of Options</h3>
                <p>After someone books a reservation with you, we go ahead and process that payment and as soon as your guests arrive we go ahead and release that payment over to your account. You can either choose to withdraw that right away, or maybe you have lots of reservations coming in that same week, and you prefer to wait a few days and batch together the payments into one large withdrawal. Whatever you want. </p>
            </div><!-- closes section -->
            <div class="section n-m">
                <div class="sub-section sub-7">
                    <h4><img src="/images4/cleardot.gif" alt="" />TripFab Debit Card</h4>
                    <p>Every business gets issued an official TripFab card, which gives you access to your money instantly. You can go to the ATM, purchase things, or anything you want. It's absolutely free.</p>
                </div><!-- closes sub-section -->
                <div class="sub-section sub-8">
                    <h4><img src="/images4/cleardot.gif" alt="" />Bank Transfer</h4>
                    <p>We can send you a wire transfer from our bank over to the valid bank account you have on file. Usually this takes a few days depending on your bank.</p>
                </div><!-- closes sub-section -->
                <div class="sub-section sub-9 last">
                    <h4><img src="/images4/cleardot.gif" alt="" />PayPal</h4>
                    <p>If you have a PayPal account, we can go ahead and debit over your paypal account with the funds available in your account.</p>
                </div><!-- closes sub-section -->						
            </div><!-- closes section -->
            <div class="section s-w">
                <div class="squares">
                    <div id="second-square">
                        <div class="square-1">
                            <h4>Don't wait to be found, get right in front</h4>
                            <p>You will have access to actually search and find people who are going to be needing your services and contact them with special, unique offers. Also you can create massive promotions open to the public to be seen by millions of travelers who are actually visiting your location.</p>
                        </div>
                        <div class="square-2">
                            <h4>Looking To Atract More Clients?</h4>
                            <p>Just go ahead and create impressive massive promotions that will appeal to actual visitors and increase your business even during low season. People always appreciate the value of a good deal. </p>
                        </div>
                        <div class="clear"></div>
                        <div class="square-3">
                            <h4>Manage Every Detail Of Your Offer</h4>
                            <p>You get to control who you make an special offer to, when and for how long. With TripFab people can take advantage of your deals and you can take advantage of endless business opportunities. </p>
                        </div>
                        <div class="square-4">
                            <h4>Make Unique Offers To Single Users</h4>
                            <p>You get the chance to actually find single potential clients that will need your services and make them special offers personally. A perfect feature for low booking seasons or to attract special clients to your business.</p>
                        </div>
                    </div><!-- closes second-square -->							
                </div><!-- closes squares -->
                <div class="clear"></div>
                <a class="back">Back to Top</a>
            </div><!-- closes section -->
        </div><!-- closes container -->
        <div id="other-features">
            <ul>
                <li>
                    <img src="/images4/ico-17.png" alt="" />
                    <h5>Free Calls</h5>
                    <p>Travelers can call you from all around the world free of charge</p>
                </li>
                <li>
                    <img src="/images4/ico-18.png" alt="" />
                    <h5>Real Reviews</h5>
                    <p>You will only get reviews from people who visited you, no fake reviews from angry competitors</p>
                </li>
                <li>
                    <img src="/images4/ico-19.png" alt="" />
                    <h5>Easy To Post</h5>
                    <p>Create your listing in three simple steps</p>
                </li>
                <li>
                    <img src="/images4/ico-20.png" alt="" />
                    <h5>Keep Your Prices Updated</h5>
                    <p>Change your pricing information easily and whenever you want</p>
                </li>
                <li>
                    <img src="/images4/ico-13.png" alt="" />
                    <h5>Video</h5>
                    <p>We are able to produce a small video enhancing your wonderful business</p>
                </li>
                <li>
                    <img src="/images4/ico-14.png" alt="" />
                    <h5>Tripfab Support</h5>
                    <p>You will get to have a dedicated Tripfab staff member assisting you whenever you need</p>
                </li>
                <li>
                    <img src="/images4/ico-15.png" alt="" />
                    <h5>No Contracts</h5>
                    <p>You can cancel your membership at any time and at no cost</p>
                </li>
                <li>
                    <img src="/images4/ico-16.png" alt="" />
                    <h5>Languages</h5>
                    <p>Tribfab comes available in many different languages for everybody.</p>
                </li>
            </ul>
        </div><!-- closes other features -->
        <div class="container bottom">
            <div class="section">
                <div class="sub-ttl">
                    Testimonials
                </div><!-- closes sub-ttl -->
                <div class="sub-ttl">
                    &nbsp;
                </div><!-- closes sub-ttl -->
                <div class="sub-ttl last">
                    FAQ's
                </div><!-- closes sub-ttl -->
                <div class="sub-section">
                    <p>"After dealing with travel agencies, I decided to give Tripfab a try and it was the best decission ever. Super user-friendly backend, low pricing and great support makes this my favourite platform."</p>
                    <strong>Chelsey Las Name</strong>
                    <span>Company Name</span>
                </div><!-- closes sub-section -->
                <div class="sub-section">
                    <p>"I was impressed when the idea was presented to me when the guys visited my hotel some weeks ago. This is definitely something that will bring much more clients to my place. Cheers!"</p>
                    <strong>Chelsey Las Name</strong>
                    <span>Company Name</span>
                </div><!-- closes sub-section -->
                <div class="sub-section last">
                    <ul>
                        <li><a href="/<?= $this->lang ?>/faqs">How do I get paid?</a></li>
                        <li><a href="/<?= $this->lang ?>/faqs">Who will be staying at my place?</a></li>
                        <li><a href="/<?= $this->lang ?>/faqs">How do I get paid?</a></li>
                        <li><a href="/<?= $this->lang ?>/faqs">Who will be staying at my place?</a></li>
                    </ul>
                    <a href="/<?= $this->lang ?>/faqs">See all FAQ's</a>
                </div><!-- closes sub-section -->						
            </div><!-- closes section -->
        </div><!-- closes container -->
    </div><!-- closes wrapper -->
</div><!-- closes main -->
<div id="footer">
    <div id="footer-gradient">
        <div class="wrapper">
            <img src="/images4/logo-2.png" alt="" class="logo" />
            <strong><?= $this->translate('footer') ?></strong>
            <span>Copyright &copy; 2011 Tripfab</span>
            <img src="/images4/img-8.png" alt="" class="mobile" />
        </div><!-- closes wrapper -->	
    </div><!-- closes footer-gradient -->					
</div><!-- footer -->
</body>
</html>