<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Déjanos llevarte miles de viajeros | Tripfab</title>
    <link type="text/css" rel="stylesheet" href="/css4/all.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
    
</head>
<body class="landing">
<div id="header-shadow">
    <div id="header">
        <div class="wrapper">
            <h1 class="logo"><a href="/<?= $this->lang ?>">TripFab</a></h1>
            <div class="right">
                <div class="language">
                    <a class="current" href="#"><?= $this->translate('language') ?></a>
                    <div class="select">
                        <ul>
                            <?php $class = ($this->lang == 'en-US') ? 'active' : '' ?>
                            <li class="en <?= $class ?>"><a href="/en-US/about">English</a></li>
                            <?php $class = ($this->lang == 'es-ES') ? 'active' : '' ?>
                            <li class="es <?= $class ?>"><a href="/es-ES/about">Español</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="right">
                <a href="/<?= $this->lang ?>/login" class="btn-1"><?= $this->translate('signin') ?></a>
                <?= $this->translate('Have an account') ?>
            </div><!-- closes right -->
        </div><!-- closes wrapper -->				
    </div><!-- closes header -->
</div><!-- closes header-shadow -->

<div id="top">			
    <div class="content wrapper">
        <div class="video-wrapper">
            <img src="/images4/img-1.png" alt="" />
        </div><!-- closes video-wrapper -->
        <h2>Déjanos llevarte miles de<br /> viajeros <em>totalmente gratis</em></h2>
        <p>Hoteles, operadores de tours, servicios de transporte y todo lo relacionado. Obtén una invitación para ser parte de la nuestra increíble plataforma llamada Tripfab.</p>
        <a href="/<?= $this->lang ?>/signup" class="btn-2">Solicitar invitación</a>
        <?php ############################### ?>
        <img src="/images4/img-2.png" alt="" />
        <?php ############################### ?>
        <div class="clear"></div>
        <h3>¿Por qué deberias unirte a Tripfab?</h3>
        <h4>¡Lo hacemos extremadamente <em>sencillo!</em></h4>
        <div id="main-features">
            <div class="centered">
                <div>
                    <h2><span>1</span>Controla tu negocio</h2>
                    <p><strong>Obtendrás control total de tus ofertas</strong></p>
                    <p>Con Tripfab, tendrás control total sobre los servicios que ofreces, a quién se los ofreces y también la habilidad de hacer cambios, promociones y más en cualquier momento.</p>
                </div>
                <div>
                    <h2><span>2</span>Exposición hacia millones</h2>
                    <p><strong>Serás visto por millones de usuarios de Tripfab</strong></p>
                    <p>Tripfab pone tu negocio frente a los ojos de millones de personas interesadas en tus servicios siempre que los necesiten.</p>
                </div>
                <div>
                    <h2><span>3</span>Facilidad de Pagos</h2>
                    <p><strong>Organiza, recibe y controla todos los pagos</strong></p>
                    <p>Tendrás acceso instantáneo a todos tus pagos pendientes y recibidos en un mismo lugar, haciendo tu administración de ingresos fácil y sencilla.</p>
                </div>
            </div><!-- closes centered -->
        </div><!-- closes main features -->				
    </div><!-- closes content -->
</div><!-- closes top -->
<div id="main">
    <div class="wrapper">
        <div id="menu">
            <ul>
                <li class="item-1"><a id="to-scroll1"><img src="/images4/cleardot.gif" alt="" /><br />Cómo Funciona <br />Tripfab</a></li>
                <li class="item-2"><a id="to-scroll2"><img src="/images4/cleardot.gif" alt="" /><br />Administración <br />de Clientes</a></li>
                <li class="item-3"><a id="to-scroll3"><img src="/images4/cleardot.gif" alt="" /><br />Pagos y <br />Ventas</a></li>
            </ul>
        </div><!-- closes menu -->
        <div class="container">
            <div class="ttl" id="scroll-1">
                <span>Conoce todo sobre</span>
                <h2>Cómo funciona Tripfab</h2>
                <strong>Tripfab conecta los negocios con los viajeros directamente - sin terceras personas.</strong>
            </div><!-- closes ttl -->
            <div class="section">
                <img src="/images4/img-3.png" alt="" class="right" />
                <h3>No más agentes de viajes</h3>
                <p>Por primera vez, Tripfab está permitiendo a los viajeros ser sus propios agentes de viaje. Ellos podrán descubrir negocios de viaje y reservar toures, actividades, hoteles, transporte y todo lo relacionado, directamente de ustedes - los negocios de la plataforma Tripfab.</p>
            </div><!-- closes section -->
            <div class="section">
                <div class="video right">
                    <img src="/images4/img-4.png" alt="" />							
                </div><!-- closes video -->
                <h3>Un motor de búsqueda de viajes</h3>
                <p>Básicamente, somos un buscador de viajes que le brinda a los viajeros el poder de encontrar y descubrir donde ellos quieren ir y luego reservar la totalidad de su viaje en una sola transacción directamente de los negocios. Simplemente, somos un mercado que conecta a los viajeros con tu empresa.</p>						
            </div><!-- closes section -->
            <div class="section">
                <div class="sub-section sub-1">
                    <h4><img src="/images4/cleardot.gif" alt="" />Te ayudamos a vender mejor</h4>
                    <p>Tendrás un perfil propio y la habilidad de publicar tus servicios y hacerlos disponibles para ser adquiridos. Nosotros te proveemos  páginas individuales que te ayudarán a vender tus servicios de forma fácil y eficaz.</p>
                </div><!-- closes sub-section -->
                <div class="sub-section sub-2">
                    <h4><img src="/images4/cleardot.gif" alt="" />Comunicate con tus clientes</h4>
                    <p>Los clientes potenciales pueden comunicarse directamente con tu empresa a través de tus páginas individuales, a través de nuestro sistema de contacto, chat o también por teléfono completamente gratis sin importar en qué lugar del mundo estén localizados.</p>
                </div><!-- closes sub-section -->
                <div class="sub-section sub-3 last">
                    <h4><img src="/images4/cleardot.gif" alt="" />Promociona tu compañía</h4>
                    <p>Con Tripfab, podrás promover tu negocio de una manera más personalizada y eficiente para tus clientes, como por ejemplo: brindar descuentos especiales a usuarios específicos, asistencia inicial y un servicio al cliente que pondrá a tu empresa en alto.</p>
                </div><!-- closes sub-section -->
                <div class="clear"></div>
                <a class="back">Volver Arriba</a>
            </div><!-- closes section -->
            <div class="ttl" id="scroll-2">
                <span>Administración</span>
                <h2>de clientes</h2>
                <strong>Nuestra plataforma hace reservaciones y recibe pagos de forma simple pero poderosa.</strong>
            </div><!-- closes ttl -->
            <div class="section">
                <img src="/images4/img-5.png" alt="" class="left" />
                <h3>Controla tus reservaciones</h3>
                <p>Te damos la opción de aprobar o rechazar reservaciones. Quizás alguien reservó y pagó una reservación cuando tu ocupación estaba completamente llena ese día. Antes que la tarjeta de crédito de los clientes sea debitada, usted puede aceptar o rechazar la petición de reservación. Sin problema alguno.</p>
            </div><!-- closes section -->
            <div class="section">
                <div class="video left">
                    <img src="/images4/img-9.png" alt="" />
                </div><!-- closes video -->
                <h3>Administra todas las ventas de TripFab en un solo lugar</h3>
                <p>Podrás ver y administrar todas las ventas que haz hecho a través de nuestro centro financiero en nuestra aplicación.  Esto hace que la contabilidad sea fácil y de rápido acceso. También, te estaremos enviando mensajes por correo electrónico para recordarte que un cliente estará llegando pronto. Como un recordatorio :-)</p>											
            </div><!-- closes section -->
            <div class="section">
                <div class="sub-section sub-4">
                    <h4><img src="/images4/cleardot.gif" alt="" />Políticas de cancelación</h4>
                    <p>Nosotros te damos un control completo sobre tus listados y reservaciones. Puedes seleccionar tu propia política de cancelación personalizada que mejor se ajuste a tus requisitos. Esta es tu compañía.</p>
                </div><!-- closes sub-section -->
                <div class="sub-section sub-5">
                    <h4><img src="/images4/cleardot.gif" alt="" />Precios de temporada</h4>
                    <p>Tendrás control total sobre tus tarifas. Quizá tus tarifas sean distintas en temporada baja y en temporada alta. Con Tripfab, podrás cambiar esos precios cuando lo requieras. Inclusive crear tus propias temporadas.</p>
                </div><!-- closes sub-section -->
                <div class="sub-section sub-6 last">
                    <h4><img src="/images4/cleardot.gif" alt="" />Controla tu calendario</h4>
                    <p>Los usuarios podrán ver tu calendario. Podrás bloquear los días que esté cerrado, lleno o simplemente no disponible, dejando así saber a tus clientes el estatus de tu ocupación durante los días consultados.</p>
                </div><!-- closes sub-section -->	
            </div><!-- closes section -->
            <div class="section s-w">
                <div class="squares">
                    <div id="first-square">
                        <div class="square-1">
                            <h4>Todos tus diferentes servicios en un mismo lugar</h4>
                            <p>No importa si ofreces uno o múltiples servicios, paquetes, incluso un simple tour o bien hospedaje. Vas a tener control sobre cada una de tus ofertas, de la manera más simple posible. Tripfab es sorprendentemente organizado y fácil de usar.</p>
                        </div>
                        <div class="square-2">
                            <h4>Actualiza tu precio según tus necesidades</h4>
                            <p>Podrás administrar el precio de tus servicios de acuerdo a tus necesidades: precios por temporadas, ofertas especiales, descuentos de último momento. Actualiza, cambia o revisa tus precios en una sola plataforma.</p>
                        </div>
                        <div class="clear"></div>
                        <div class="square-3">
                            <h4>Reservas, Administración y Calendario</h4>
                            <p>Actualiza tu calendario cuando quiera o necesite, acomódalo por horas, días o meses. Pondrás a disposición de tus clientes un calendario actualizado a través de unos pasos bastante simples.</p>
                        </div>
                        <div class="square-4">
                            <h4>Contenido e imágenes de alta calidad</h4>
                            <p>Utiliza tu perfil de Tripfab para mostrarle a tus clientes potenciales imágenes de alta calidad, video e información detallada sobra cada uno de tus servicios. Podrás hacer actualizaciones, cambios y agregar nuevo contenido fácilmente para que tus clientes vean que la información que están obteniendo de Tribfab es de calidad.</p>
                        </div>
                    </div><!-- closes first-square -->							
                </div><!-- closes squares -->
                <div class="clear"></div>
                <a class="back">Volver Arriba</a>
            </div><!-- closes section -->
            <div class="ttl" id="scroll-3">
                <span>Acerca de los</span>
                <h2>pagos y ventas</h2>
                <strong>Sabemos que una vez que te hablamos de reservaciones, te preguntarás ¿Cómo serán pagadas?</strong>
            </div><!-- closes ttl -->
            <div class="section">
                <img src="/images4/img-6.png" alt="" class="right" />
                <h3>Brindamos varias opciones</h3>
                <p>Una vez que alguien haya hecho una reservación con alguno de tus servicios, nosotros procesamos el pago y tan pronto como tu cliente llegue a su destino, nosotros procederemos a transferir el dinero a tu cuenta. Este pago lo puedes solicitar inmediatamente, o quizá tengas muchas reservaciones en la misma semana y prefieras esperar unos cuantos días y solicitar todos los fondos juntos en una misma transacción. Puedes hacerlo como gustes.</p>
            </div><!-- closes section -->
            <div class="section n-m">
                <div class="sub-section sub-7">
                    <h4><img src="/images4/cleardot.gif" alt="" />Tarjeta de débito de Tripfab</h4>
                    <p>Tu compañía obtendrá una tarjeta oficial de Tripfab, que le dará acceso a tu dinero instantáneamente. Con esta tarjeta puedes ir al cajero automático, comprar cosas, lo que desea. Es totalmente gratis.</p>
                </div><!-- closes sub-section -->
                <div class="sub-section sub-8">
                    <h4><img src="/images4/cleardot.gif" alt="" />Transferencia bancaria</h4>
                    <p>Podemos hacerte una transferencia interbancaria desde nuestro banco a su cuenta personal. Usualmente este método toma unos cuantos días dependiendo del banco con quien tengas la cuenta.</p>
                </div><!-- closes sub-section -->
                <div class="sub-section sub-9 last">
                    <h4><img src="/images4/cleardot.gif" alt="" />PayPal</h4>
                    <p>Si tienes una cuenta de Paypal, podemos hacerte el débito a tu cuenta de Paypal sin problema alguno.</p>
                </div><!-- closes sub-section -->						
            </div><!-- closes section -->
            <div class="section s-w">
                <div class="squares">
                    <div id="second-square">
                        <div class="square-1">
                            <h4>No espere que le encuentren</h4>
                            <p>Tendrás acceso a buscar e identificar viajeros que necesiten de tus servicios y engancharlos con ofertas especiales y únicas. También, puedes crear promociones masivas abiertas al público para que sean vistas por los viajeros que estarán visitando tu localidad.</p>
                        </div>
                        <div class="square-2">
                            <h4>¿Buscando atraer más clientes?</h4>
                            <p>Simplemente tienes que crear promocines masivas que seducirán a los visitantes, alimentando así tu negocio aún en temporada baja. La gente siempre agradece el valor de los buenos tratos y ofertas.</p>
                        </div>
                        <div class="clear"></div>
                        <div class="square-3">
                            <h4>Administra cada detalle de tu oferta</h4>
                            <p>Tendrás control sobre a quien quieras hacerle una oferta especial, cuando hacerla y por cuanto tiempo. Con Tripfab, las personas pueden beneficiarse de tus ofertas y tu podrás beneficiarte de infinitas oportunidades para tu negocio.</p>
                        </div>
                        <div class="square-4">
                            <h4>Haz ofertas únicas para usuarios individuales</h4>
                            <p>Podrás encontrar clientes potenciales que necesitarán tus servicios y ofercerles ofertas personales. Una característica perfecta para temporadas bajas o para atraer clientes especiales a su empresa.</p>
                        </div>
                    </div><!-- closes second-square -->							
                </div><!-- closes squares -->
                <div class="clear"></div>
                <a class="back">Volver Arriba</a>
            </div><!-- closes section -->
        </div><!-- closes container -->
        <div id="other-features">
            <ul>
                <li>
                    <img src="/images4/ico-17.png" alt="" />
                    <h5>Llamadas Gratuitas</h5>
                    <p>Los viajeros podrán llamarlo de cualquier parte del mundo sin ningún costo</p>
                </li>
                <li>
                    <img src="/images4/ico-18.png" alt="" />
                    <h5>Revisiones Reales</h5>
                    <p>Obtendrá revisiones de gente que lo visitó, No de competidores enojados</p>
                </li>
                <li>
                    <img src="/images4/ico-19.png" alt="" />
                    <h5>Facil de Publicar</h5>
                    <p>Cree sus listados en 3 simples pasos</p>
                </li>
                <li>
                    <img src="/images4/ico-20.png" alt="" />
                    <h5>Precios actualizados</h5>
                    <p>Ajuste sus precios facilmente y en el momento que lo desee</p>
                </li>
                <li>
                    <img src="/images4/ico-13.png" alt="" />
                    <h5>Video</h5>
                    <p>Podemos producir un pequeño video para resaltar su compañía</p>
                </li>
                <li>
                    <img src="/images4/ico-14.png" alt="" />
                    <h5>Soporte de Tripfab</h5>
                    <p>Tendrá un miembro de Tripfab dedicado a asistirle cuando lo necesite.</p>
                </li>
                <li>
                    <img src="/images4/ico-15.png" alt="" />
                    <h5>Sin contratos</h5>
                    <p>Puede cancelar su membresía en cualquier momento sin costo alguno</p>
                </li>
                <li>
                    <img src="/images4/ico-16.png" alt="" />
                    <h5>Idiomas</h5>
                    <p>Tripfab está disponible en diferentes idiomas para todos.</p>
                </li>
            </ul>
        </div><!-- closes other features -->
        <div class="container bottom">
            <div class="section">
                <div class="sub-ttl">
                    Testimonios
                </div><!-- closes sub-ttl -->
                <div class="sub-ttl">
                    &nbsp;
                </div><!-- closes sub-ttl -->
                <div class="sub-ttl last">
                    FAQ's
                </div><!-- closes sub-ttl -->
                <div class="sub-section">
                    <p>"Después de trabajar con agencias de viajes, decidí darle una oportunidad a Tripfab y fue la mejor decisión. La administración de mi cuenta es muy fácil de usar, la comisión baja y el gran soporte la convirtió en mi plataforma favorita."</p>
                    <strong>Chelsey Las Name</strong>
                    <span>Company Name</span>
                </div><!-- closes sub-section -->
                <div class="sub-section">
                    <p>"Me impresionó cuando estos jóvenes me visitaron y me presentaron la idea en mi hotel hace unas semanas. Definitivamente esto es algo que me va a traer muchos clientes más. ¡Saludos!"</p>
                    <strong>Chelsey Las Name</strong>
                    <span>Company Name</span>
                </div><!-- closes sub-section -->
                <div class="sub-section last">
                    <ul>
                        <li><a href="/<?= $this->lang ?>/faqs">How do I get paid?</a></li>
                        <li><a href="/<?= $this->lang ?>/faqs">Who will be staying at my place?</a></li>
                        <li><a href="/<?= $this->lang ?>/faqs">How do I get paid?</a></li>
                        <li><a href="/<?= $this->lang ?>/faqs">Who will be staying at my place?</a></li>
                    </ul>
                    <a href="/<?= $this->lang ?>/faqs">See all FAQ's</a>
                </div><!-- closes sub-section -->						
            </div><!-- closes section -->
        </div><!-- closes container -->
    </div><!-- closes wrapper -->
</div><!-- closes main -->
<div id="footer">
    <div id="footer-gradient">
        <div class="wrapper">
            <img src="/images4/logo-2.png" alt="" class="logo" />
            <strong><?= $this->translate('footer') ?></strong>
            <span>Copyright &copy; 2011 Tripfab</span>
            <img src="/images4/img-8.png" alt="" class="mobile" />
        </div><!-- closes wrapper -->	
    </div><!-- closes footer-gradient -->					
</div><!-- footer -->
<script type="text/javascript" src="http://tripfab.com/js2/jquery.js"></script>
<script type="text/javascript" src="/js4/scroll-startstop.events.jqueary.js"></script>
<script type="text/javascript">
$(function(){
	$('.language a.current').click(function(){
		$(this).toggleClass('active');
		$('.language .select').toggleClass('show');
		return false;
	});
	jQuery('#other-features ul').jcarousel();
});
</script>
</body>
</html>