<?php $url = $this->baseUrl() .'/'. $this->country->identifier .'/'. $this->city->identifier .'/filter';
$cat = $this->cat; $subcat = $this->subcat; $sort = $this->sort; $stars  = $this->stars; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->city->title ?>, <?= $this->country->title ?> | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css2/index/city.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <link type="text/css" rel="stylesheet" href="/css2/calendar/jquery-ui-1.8.16.custom.css" />
    <script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript" src="/js2/index.city.js"></script>
    <script type="text/javascript" src="/js/scrollElement.jQuery.js"></script>
    <style type="text/css">
		.hidden { display:none;}
		.img-wrapper a { display:block;}
		.result .img-wrapper h4 { bottom:3px;}
		.big-message { z-index:100000}
		#search_result .widget.cats { display:none;}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>
    <div class="w2">
        <div class="main-search wrapper">
            <span><a href="" class="link-2">View Trip Plans in your country</a></span>
            <form action="">
                <fieldset>
                    <input id="citiesSearch2" type="text" value="<?= $this->country->title ?>, <?= $this->city->title ?>" />
                    <input type="submit" value="Search" class="btn-1"/>
                </fieldset>
            </form>
        </div><!-- closes main-search -->
        
        <div class="main wrapper" id="search_result">
            <div class="left-sidebar">
            	<div class="scrollcontainer">
                <ul class="cat-menu">
                	<?php $ii = 1 ?>
                	<?php foreach($this->categories as $i => $category): ?>
					<?php $_cat = strtolower(str_replace(' ','-',$category['name'])) ?>
                    <?php $class = ($cat == $_cat) ? 'active ' : ''; ?>
                    <?php $class.= ($i == (count($this->categories) - 1)) ? 'last' : ''; ?>
                    <li class="item-<?= $ii ?> <?= $class ?>">
                    <a data-cat="<?= $_cat ?>" href="#/<?= $_cat ?>">
                    <img src="/images2/cleardot.gif" alt="" />
                    <?= $category['name'] ?></a></li>
                    <?php $ii++ ?>
                    <?php endforeach ?>
                </ul>
                <h3 class="filter"><span>FILTER OPTIONS</span></h3>
                <div class="travelers">
                    <label>TRAVELERS </label>
                    <select>
                        <option>1</option>
                        <option>1</option>
                    </select>
                </div><!--TRAVELERS-->
                <div class="widget slider">
                    <h4><img src="/images2/cleardot.gif" alt="" />Price Per Person</h4>
                    <span id="value-4">Free - $1000</span>
                    <div class="bg">
	                    <div id="slider-4"></div>
                    </div>
                </div><!-- closes widget -->
                <div class="widget destinations listing-2">
                	<h4 class="location"><img src="/images2/cleardot.gif" alt="" />CITIES</h4>
                </div>
                <?php foreach($this->subcats as $_cat => $c): ?>
                <div rel="#/<?= $_cat ?>" class="widget cats destinations listing-2">
                    <h4 class="categories"><img src="/images2/cleardot.gif" alt="" />Categories</h4>
                    <?php foreach($c as $sc): ?>
                    <p><input type="checkbox" class="noclean" name="cat[<?= $sc->id ?>]" value="<?= $sc->id ?>" /><label><?= $sc->name ?></label></p>
                    <?php endforeach ?>
                </div>
                <?php endforeach ?>
                </div>
            </div><!-- closes left-sidebar -->
            <div class="content">
            	<h3>There are <strong><?= $this->listing_count ?> things to do in Costa Rica</strong></h3>
                <div class="results-wrapper">
                	<div class="loading"><div class="load">Loading...</div></div>
		            <div class="clear"></div>
                </div><!-- closes results-wrapper -->
            </div><!-- closes content -->
            <div class="clear"></div>
        </div><!-- closes main -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div id="citiesAutocompleteContainer2"></div>
<input type="hidden" id="hddCityId" name="hddCityId" value="<?= $this->city->identifier ?>" />
<input type="hidden" id="hddCountryId" name="hddCountryId" value="<?= $this->country->identifier ?>" />
<div style="display:none">
	<div id="newtrip">
    	<div id="create_trip">
			<form action="">
                <div class="top">
                    <h3>Create a New Trip</h3>
                    <p>Complete the information below to start your next trip</p>
                </div><!--TOP-->
                <div class="cont">
                    <fieldset>
                        <div class="item">
                            <label class="trip">Trip Name</label>
                            <input type="text" name="title" value="" />
                        </div><!--ITEM-->
                        <div class="item">
                            <label class="dates">Trip Dates</label>
                            <input class="start" type="text" name="start" value="Starting Date" />
                            <input class="end"type="text" name="end" value="Ending Date" />
                            <label class="check">
                                <input type="checkbox" class="nodatesyet"/>
                                I don't know the travel dates yet
                            </label>
                        </div><!--ITEM-->
                        <div class="item last">
                                <input type="checkbox" checked="checked" />
                                <p>I want to receive special offers from vendors near
                                    of the places I'll visit in this trip</p>
                        </div><!--ITEM-->
                    </fieldset>
                </div><!--CONT-->
                <div class="bottom">
                    <input type="submit" class="btn-1 noclean" value="Create Trip" />
                    <input type="button" onclick="$.fancybox.close(); return false;" class="btn-10 noclean" value="Cancel" />
                </div><!--BOTTOM-->
                <input type="hidden" name="trip" value="new" />
                <input type="hidden" name="listing" value="" />
            </form>
		</div><!--CREATE_TRIP-->
    </div>
</div>
</body>
</html>