<?php $url = $this->baseUrl() .'/'. $this->country->identifier .'/'. $this->city->identifier .'/filter';
$cat = $this->cat; $subcat = $this->subcat; $sort = $this->sort; $stars  = $this->stars; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->city->title ?>, <?= $this->country->title ?> | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css2/index/city.css" />
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js2/jquery.input.value.js"></script>
    <script type="text/javascript" src="/js2/common.js"></script>
    <script type="text/javascript" src="/js2/index.city.js"></script>
    <script type="text/javascript" src="/js/scrollElement.jQuery.js"></script>
    <style type="text/css">
		.hidden { display:none;}
		.img-wrapper a { display:block;}
		.result .img-wrapper h4 { bottom:3px;}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', 
	array('user'=>$this->user,'full'=>true)); ?>
    <div class="w2">
        <div class="main-search wrapper">
            <span><a href="" class="link-2">View Trip Plans in your country</a></span>
            <form action="">
                <fieldset>
                    <input id="citiesSearch2" type="text" value="<?= $this->country->title ?>, <?= $this->city->title ?>" />
                    <input type="submit" value="Search" class="btn-1"/>
                </fieldset>
            </form>
        </div><!-- closes main-search -->
        
        <div class="main wrapper">
            <div class="left-sidebar">
            	<div class="scrollcontainer">
                <ul class="cat-menu">
                	<?php $ii = 1 ?>
                	<?php foreach($this->categories as $i => $category): ?>
					<?php $_cat = strtolower(str_replace(' ','-',$category['name'])) ?>
                    <?php $class = ($cat == $_cat) ? 'active ' : ''; ?>
                    <?php $class.= ($i == (count($this->categories) - 1)) ? 'last' : ''; ?>
                    <li class="item-<?= $ii ?> <?= $class ?>">
                    <a data-cat="<?= $_cat ?>" href="#<?= $_cat ?>">
                    <img src="/images2/cleardot.gif" alt="" />
                    <?= $category['name'] ?></a></li>
                    <?php $ii++ ?>
                    <?php endforeach ?>
                </ul>
                <div class="widget slider">
                    <h4><img src="/images2/cleardot.gif" alt="" />Price Per Person</h4>
                    <span id="value-4">Free - $1000</span>
                    <div id="slider-4"></div>
                </div><!-- closes widget -->
                <?php foreach($this->subcats as $_cat => $c): ?>
                <div rel="#<?= $_cat ?>" class="widget destinations listing-2">
                    <h4><img src="/images2/cleardot.gif" alt="" />Categories</h4>
                    <?php foreach($c as $sc): ?>
                    <p><input type="checkbox" /><label><?= $sc->name ?></label></p>
                    <?php endforeach ?>
                </div>
                <?php endforeach ?>
                </div>
            </div><!-- closes left-sidebar -->
            <div class="content">
                <div class="results-wrapper">
                	<div class="loading"><div class="load">Loading...</div></div>
                	<?php foreach($this->listings as $i => $list): ?>
                    <?php $class = ((($i+1) % 3) == 0) ? 'last' : '' ?>
                    <div class="result <?= $class ?>">
                        <div class="img-wrapper">
                        	<?php if($this->user->role_id == 2): ?>
                            <a href="#" class="been">Been there</a>
                            <?php endif ?>
                            <a href="<?= str_replace('filter', $list->identifier, $url) ?>">
                            <?php // $this->thumbnail(array('width'=>'225', 'height'=>'167'), $list->image, '','225:167') ?>
                            <img width="225" height="167" src="/images/lph/th/All-Activities-0<?= $i + 1 ?>.jpg" />
                            <h4><?= $list->title ?></h4>
                            </a>
                            <?php if($this->user->role_id == 2): ?>
                            <?= $this->partial('partials/trips.phtml', array('trips'=> $this->trips, 'id'=>$list->id)); ?>
                            <?php endif ?>
                        </div><!-- closes img-wrapper -->
                        <div class="meta">
                            <span class="cat-1"><img src="/images2/cleardot.gif" alt="" /><?= $this->categories[$list->main_type]['name'] ?></span>
                            <?php if($list->price > 0): ?>
                            <strong>$<?= $list->price ?><em> / person</em></strong>
                            <?php endif ?>
                        </div><!-- closes meta -->
                        <p class="listing_description"><?= $list->description ?></p>
                        <a href="<?= str_replace('filter', $list->identifier, $url) ?>" class="btn-1">View activity</a>
                    </div><!-- closes result -->
                    <?php endforeach ?>
                </div><!-- closes results-wrapper -->
            </div><!-- closes content -->
        </div><!-- closes main -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div id="citiesAutocompleteContainer2"></div>
<input type="hidden" id="hddCityId" name="hddCityId" value="<?= $this->city->identifier ?>" />
<input type="hidden" id="hddCountryId" name="hddCountryId" value="<?= $this->country->identifier ?>" />
</body>
</html>