<?php if(!is_null($this->city)): ?>
<?php $url = $this->baseUrl() .'/'. $this->country->identifier .'/'. $this->city->identifier .'/filter';
$cat = $this->cat; $subcat = $this->subcat; $sort = $this->sort; $stars  = $this->stars; ?>
<?php else: ?>
<?php $url = $this->baseUrl() .'/'. $this->country->identifier .'/filter';
$cat = $this->cat; $subcat = $this->subcat; $sort = $this->sort; $stars  = $this->stars; ?>
<?php endif ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <?php if(!is_null($this->city)): ?>
    <title><?= $this->city->title ?>, <?= $this->country->title ?> | Tripfab.com </title>
    <?php else: ?>
    <title><?= $this->country->title ?> | Tripfab.com</title>
    <?php endif ?>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css" />
    <link type="text/css" rel="stylesheet" href="/css6/section1.css" />
    <link type="text/css" rel="stylesheet" href="/css2/index/city.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <link href="/css6/calendar.css" rel="stylesheet" type="text/css">
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>
    <div class="w2">
    
				<div class="sub_header" id="src_map">
					<div class="cont">
						<div class="top">
							<div class="ttl">
								<img class="country" alt="" src="https://static.tripfab.com/images6/map_cr.png" width="45" height="43">
								<h2><?php if(!is_null($this->city)): ?>
                                <strong><?= $this->city->title ?>,</strong>
                                <?php endif; ?> <?= $this->country->title ?> 
                                <img alt="" src="https://static.tripfab.com/images6/flagCR.png" width="" height=""></h2>
								<!--<a href="" class="link1 maplink">Show Map &rarr;</a>
								<a href="" class="link1 near">View Nearby Cities &rarr;</a>-->
								<div class="near_cities hidden">
									<span class="arrow"></span>
									<ul>
										<li class="active"><a href="">Tamarindo<span>→</span></a></li>
										<li><a href="">Drake Bay<span>→</span></a></li>
										<li><a href="">Jacó<span>→</span></a></li>
										<li><a href="">Santa Teresa<span>→</span></a></li>
										<li><a href="">Tamarindo<span>→</span></a></li>
									</ul>
									<ul>
										<li><a href="">Tamarindo<span>→</span></a></li>
										<li><a href="">Drake Bay<span>→</span></a></li>
										<li><a href="">Jacó<span>→</span></a></li>
										<li><a href="">Santa Teresa<span>→</span></a></li>
										<li><a href="">Tamarindo<span>→</span></a></li>
									</ul>
								</div><!--NEAR_CITIES-->
							</div><!--TTL-->
							
							<div class="src_bar">
								<form action="">
									<fieldset>
										<input name="" value="Search" class="btn-1" type="submit">
										<input id="citiesSearch2" placeholder="Search places" type="text">
										<div class="clear"></div>
									</fieldset>
								</form>
							</div><!--SRC_BAR-->
							<div class="clear"></div>
							
						</div><!--TOP-->
						
						<div class="map less">
							<div class="mapcanvas"><img src="search-result-hybrid_files/src_result-img2.png" alt="" width="" height=""></div>						
						</div><!--MAP-->
						
					</div><!--CONT-->
				</div><!--SUB_HEADER-->




        <div class="main wrapper" id="search_result">
            <div class="left-sidebar">
            	<div class="scrollcontainer">
                <ul class="cat-menu">
                	<?php $ii = 1 ?>
                	<?php foreach($this->categories as $i => $category): ?>
					<?php $_cat = strtolower(str_replace(' ','-',$category['name'])) ?>
                    <?php $class = ($cat == $_cat) ? 'active ' : ''; ?>
                    <?php $class.= ($i == (count($this->categories) - 1)) ? 'last' : ''; ?>
                    <li class="item-<?= $ii ?> <?= $class ?>">
                    <a data-cat="<?= $_cat ?>" href="#/<?= $_cat ?>">
                    <em><img src="https://static.tripfab.com/images2/cleardot.gif" alt="" />
                    <?= $category['name'] ?></em><span><?= $this->ls_count[$category['id']] ?></span></a>
                    </li>
                    <?php $ii++ ?>
                    <?php endforeach ?>
                </ul>
                <div class="widget slider">
                    <h4><img src="https://static.tripfab.com/images2/cleardot.gif" alt="" />Price Per Person</h4>
                    <span id="value-4">Free - $1000</span>
                    <div class="bg">
	                    <div id="slider-4"></div>
                    </div>
                </div><!-- closes widget -->
                <div class="widget destinations listing-2">
                	<h4 class="location"><img src="https://static.tripfab.com/images2/cleardot.gif" alt="" />CITIES</h4>
                </div>
                <?php foreach($this->subcats as $_cat => $c): ?>
                <div rel="#/<?= $_cat ?>" class="widget cats destinations listing-2">
                    <h4 class="categories"><img src="https://static.tripfab.com/images2/cleardot.gif" alt="" />Categories</h4>
                    <?php foreach($c as $sc): ?>
                    <p><input type="checkbox" class="noclean" name="cat[<?= $sc->id ?>]" value="<?= $sc->id ?>" /><label><?= $sc->name ?></label></p>
                    <?php endforeach ?>
                </div>
                <?php endforeach ?>
                </div>
            </div><!-- closes left-sidebar -->
           
            <div class="content">
                <div class="results-wrapper">
                	<div class="loading"><div class="load">Loading...</div></div>
		            <div class="clear"></div>
                </div><!-- closes results-wrapper -->
                <div class="loading2"></div>
            </div><!-- closes content -->
            <div class="clear"></div>
        </div><!-- closes main -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div id="citiesAutocompleteContainer2"></div>
<?php if(!is_null($this->city)): ?>
<input type="hidden" id="hddCityId" name="hddCityId" value="<?= $this->city->identifier ?>" />
<?php else: ?>
<input type="hidden" id="hddCityId" name="hddCityId" value="default" />
<?php endif ?>
<input type="hidden" id="hddCountryId" name="hddCountryId" value="<?= $this->country->identifier ?>" />
<div style="display:none">
	<div id="newtrip">
    	<div id="create_trip">
			<form action="">
                <div class="top">
                    <h3>Create a New Trip</h3>
                    <p>Complete the information below to start your next trip</p>
                </div><!--TOP-->
                <div class="cont">
                    <fieldset>
                        <div class="item">
                            <label class="trip">Trip Name</label>
                            <input type="text" name="title" value="" />
                        </div><!--ITEM-->
                        <div class="item">
                            <label class="dates">Trip Dates</label>
                            <input class="start" type="text" name="start" value="Starting Date" />
                            <input class="end"type="text" name="end" value="Ending Date" />
                            <label class="check">
                                <input type="checkbox" class="nodatesyet"/>
                                I don't know the travel dates yet
                            </label>
                        </div><!--ITEM-->
                        <div class="item temp">
                        	<label class="travelers">Travelers</label>
                        	<select name="adults">
                        		<option value="1">1 Adult</option>
                                <?php for($i=2;$i<=20;$i++): ?>
                                <option value="<?= $i ?>"><?= $i ?> Adults</option>
                                <?php endfor ?>
                        	</select>
                        	<select name="kids">
                        		<option value="">None</option>
                        		<option value="1">1 Kid</option>
                                <?php for($i=2;$i<=20;$i++): ?>
                                <option value="<?= $i ?>"><?= $i ?> Kids</option>
                                <?php endfor ?>
                        	</select>
                        </div><!--ITEM-->
                    </fieldset>
                </div><!--CONT-->
                <div class="bottom">
                    <input type="submit" class="btn-1 noclean" value="Create Trip" />
                    <input type="button" onclick="$.fancybox.close(); return false;" class="btn-10 noclean" value="Cancel" />
                </div><!--BOTTOM-->
                <input type="hidden" name="trip" value="new" />
                <input type="hidden" name="listing" value="" />
            </form>
		</div><!--CREATE_TRIP-->
    </div>
</div>
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript" src="/js2/index.city.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript" src="/js/scrollElement.jQuery.js?v=<?= $this->cssVC ?>"></script>
<style type="text/css">
	.hidden { display:none;}
	.img-wrapper a { display:block;}
	.result .img-wrapper h4 { bottom:3px;}
	.big-message { z-index:100000}
	#search_result .widget.cats { display:none;}
</style>
</body>
</html>