<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
  	<meta content="noindex,nofollow" name="robots" />
  	<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
  	<title>Tripfab.com</title>
  	<link type="text/css" rel="stylesheet" href="/css6/reset.css?v=<?= $this->cssVC ?>" />
  	<link type="text/css" rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
  	<link type="text/css" rel="stylesheet" href="/css6/section1.css?v=<?= $this->cssVC ?>" />
</head>
<body>
<div id="wp_all">
    <div id="wp_header">
        <?= $this->partial('partials/header-v2.phtml', array('user'=>$this->user,'full'=>true)); ?>
    </div><!--WP_HEADER-->
    <div id="wp_content">
        <div id="contactUs">
            <div class="left">
                <h2>Contact TripFab <span>Have a question or a problem?</span></h2>
                <div class="inner">
                    <h3>Complete the following form to get in contact with us</h3>
                    <form action="" id="js-contact-form" method="post">
                    	<?php if(is_null($this->user)): ?>
                        <div class="single">
                            <h4>I am a...</h4>
                            <div class="option">
                                <label><input class="js-type noclean" type="radio" checked="checked" name="type" value="Traveler" /> Traveler</label>
                                <label><input class="js-type noclean" type="radio" name="type" value="Partner" /> Partner</label>
                            </div><!--OPTION-->
                            <div class="clear"></div>
                        </div><!--SINGLE-->
                        <div class="single">
                            <h4>My name is</h4>
                            <div class="option">
                                <input type="text" name="name" placeholder="Name" value="" />
                            </div><!--OPTION-->
                            <div class="clear"></div>
                        </div><!--SINGLE-->
                        <div class="single hidden js-comapny-field">
                            <h4>I work in</h4>
                            <div class="option">
                                <input type="text" name="company" placeholder="Company Name" value="" />
                            </div><!--OPTION-->
                            <div class="clear"></div>
                        </div><!--SINGLE-->
                        <div class="single">
                            <h4>My e-mail is</h4>
                            <div class="option">
                                <input type="text" name="email" placeholder="E-mail" value="" />
                            </div><!--OPTION-->
                            <div class="clear"></div>
                        </div><!--SINGLE-->
                        <?php endif ?>
                        <div class="single">
                            <h4>My issue relates to...</h4>
                            <div class="option js-partner-subjects hidden">
                                <select name="subject" disabled="disabled">
                                	<option value="">-- Select one --</option>
                                    <option>Deposits or Payments</option>
                                    <option>Reservation Cancellation</option>
                                    <option>My Reservations</option>
                                    <option>Payments and Refunds</option>
                                    <option>Messaging and Booking</option>
                                    <option>Sublets</option>
                                    <option>How/Where do I find?</option>
                                    <option>Something Else</option>
                                </select>
                            </div><!--OPTION-->
                            <div class="option js-traveler-subjects">
                                <select name="subject">
                                	<option value="">-- Select one --</option>
                                    <option>Multiple Rooms & Availability</option>
                                    <option>Listing My Space</option>
                                    <option>A Reservation</option>
                                    <option>Host Payouts</option>
                                    <option>Security Deposit</option>
                                    <option>Managing My Listing</option>
                                    <option>Sublets</option>
                                    <option>Something Else</option>
                                    <option>Taxes</option>
                                    <option>How/Where do I find?</option>
                                </select>
                            </div><!--OPTION-->
                            <div class="clear"></div>
                        </div><!--SINGLE-->
                        <div class="single last">
                            <h4>This is my issue...</h4>
                            <div class="option">
                                <textarea name="message" placeholder="Describe the issue you're having"></textarea>
                            </div><!--OPTION-->
                            <div class="clear"></div>
                        </div><!--SINGLE-->
                        <input class="btn-1 noclean" type="submit" value="Send Message" />
                        <div class="clear"></div>
                        <?php if($this->user->role_id == 2): ?>
                        <input type="hidden" name="type" value="Traveler" />
                        <input type="hidden" name="name" value="<?= $this->user->name ?>" />
                        <input type="hidden" name="email" value="<?= $this->user->email ?>" />
                        <input type="hidden" name="user" value="1" />
                        <?php elseif($this->user->role_id == 3): ?>
                        <input type="hidden" name="type" value="Traveler" />
                        <input type="hidden" name="name" value="<?= $this->user->name ?>" />
                        <input type="hidden" name="company" value="<?= $this->user->name ?>" />
                        <input type="hidden" name="email" value="<?= $this->user->email ?>" />
                        <input type="hidden" name="user" value="1" />
                        <?php else: ?>
                        <input type="hidden" name="user" value="0" />
                        <?php endif ?>
                    </form>
                    <div class="sent js-message-sent">
                        <h6>Message sent!</h6>
                        <p>We’ll email you a reply as soon as possible</p>
                        <a href="" class="link1 js-ask">Have another question or problem?</a>
                    </div><!--SENT HIDDEN-->
                </div><!--INNER-->
            </div><!--LEFT-->
            
            <div class="right">
                <div class="top">
                    <h5><em></em>Are you a travel company? <span>Learn how to be our partner</span></h5>
                    <a href="http://partners.tripfab.com" class="btn-1">Join TripFab</a>
                </div><!--TOP-->
                <div class="inner">
                    <div class="single">
                        <h6>Phone Support</h6>
                        <p>Phone support is great for immediate action and emergency situations</p>
                        <span class="number">+1 917 725 4048</span>
                    </div><!--SINGLE-->
                    <div class="single chat">
                        <a href="" class="btn-10">Chat Now</a>
                        <h6>Live Chat</h6>
                        <p>Live chat is the fastest way to reach us</p>			
                    </div><!--SINGLE-->                    
                    <div class="single office">
                        <h6>Office</h6>
                        <dl>
                            <dt>Phone:</dt>
                            <dd>+506 2289 5064</dd>
                            <dt>Email:</dt>
                            <dd><a href="mailto:hello@tripfab.com" class="link1">hello@tripfab.com</a></dd>
                        </dl>
                    </div><!--SINGLE-->
                    <div class="single">
                        <ul>
                            <li><a href="https://twitter.com/tripfab"><span class="tw"></span>Follow Us on Twitter</a></li>
                            <li><a href="https://facebook.com/tripfab"><span class="fb"></span>Become our Fan on Facebook</a></li>
                            <li><a href="http://blog.tripfab.com/"><span class="bl"></span>Read our ideas</a></li>
                        </ul>
                    </div><!--SINGLE-->
                </div><!--INNER-->
            </div><!--RIGHT-->
            <div class="clear"></div>
        </div><!--CONT_BL CONTACTUS-->
    </div><!--WP_CONTENT-->
    <div id="wp_footer">
        <?= $this->partial('partials/footer.phtml', array('user'=>$this->user,'full'=>true)); ?>
    </div><!--WP_FOOTER-->
</div><!--WRAPPER_ALL-->
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
    $(document).ready(function() {
        function sentFx() {
            $('.left .sent').animate({
                opacity: 1,
            },500);
            $('.left .sent').fadeIn('slow');
        }
        $('input.btn-2').click(function() {
            
        });
        $('.sent .link1').click(function() {
            $('.left .sent').fadeOut('slow');
            $(".left .inner form, .inner h3").fadeIn();
            $(".left .inner").animate({
                height: "480px",  						
            }, 500 );
            return false
        });
		
		$('#js-contact-form').submit(function(){
			$isValid = $(this).validate({
				rules:{
					name:'required',
					email:'required email',
					subject:'required',
					message:'required'
				}
			});
			
			$form = $(this);
			
			if($isValid.form()) {
				$data = $form.serialize();
				$('input, select, textarea', $form).attr('disabled','disabled');
				$.ajax({
					url:'/ajax/contact',
					data:$data,
					type:'POST',
					dataType:'json',
					success:function(){
						$('input, select, textarea', $form).removeAttr('disabled');
						$('input:not([type=submit]), select, textarea', $form).val('');
						$(".left .inner form, .inner h3").fadeOut();
						$(".left .inner").animate({
							height: "252px",
							opacity: 1,       
						}, 500 );
						sentFx();
					},
					error:function(){
						showError('Something went wrong.');
						$('input, select', $form).removeAttr('disabled');
					}
				});
				return false;
			}
			return false;
		});
		
		$('.js-type').change(function(){
			if($(this).val() == 'Partner') {
				$('.js-comapny-field').removeClass('hidden');
				$('.js-partner-subjects').removeClass('hidden');
				$('.js-partner-subjects select').removeAttr('disabled');
				$('.js-traveler-subjects').addClass('hidden');
				$('.js-traveler-subjects select').attr('disabled','disabled');
			} else {
				$('.js-comapny-field').addClass('hidden');
				$('.js-traveler-subjects').removeClass('hidden');
				$('.js-traveler-subjects select').removeAttr('disabled');
				$('.js-partner-subjects').addClass('hidden');
				$('.js-partner-subjects select').attr('disabled','disabled');
			}
		});
    });
</script>
</body>
</html>
