<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <script type="text/javascript">var NREUMQ=NREUMQ||[];NREUMQ.push(["mark","firstbyte",new Date().getTime()]);</script>
    <title>Plan the perfect trip, in one place | Tripfab.com</title>
    <link type="text/css"  rel="stylesheet" href="/css6/reset.css" />
    <link type="text/css"  rel="stylesheet" href="/css6/home2.css" />
    <link type="text/css"  rel="stylesheet" href="/css6/common.css" />
    <link type="text/css"  rel="stylesheet" href="/css2/index/index.css" />
    <link type="text/css"  rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <link type="image/png" rel="icon" href="/images2/favicon3.ico" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
</head>
<body id="home2">
<div id="wp_all">
	<div id="wp_header"><?= $this->partial('partials/header-v2.phtml', array('user'=>$this->user,'full'=>true)); ?></div>
	<div id="wp_content">
	<div id="wrapper-top">
		<div class="pattern"></div>
		<div class="top">
			<?php $rand = mt_rand(1,5) ?>
			<img class="high background" src="/images6/home_top<?= $rand ?>.jpg"  style="display:none;" />
		</div><!--TOP-->
			
		<div class="wrap">
			<div class="main">
				<h2>Plan the perfect trip, in one place.</h2>
				<h3>From things to do to everything in between - directly from business.</h3>
				<div id="search-box">
					<div class="search">
						<input id="tags" type="text" name="" value="Where do you want to go?" />
						<input type="submit" name="" value="Search" class="btn-1 noclean" />
						<div class="clear"></div>
					</div><!--SEARCH--> 
				</div><!--SEARCH-BOX-->
				
			</div><!--MAIN--> 
		</div><!--WRAP-->
		
		<div class="bottom">
			<div class="wrap">
				<div class="each">
					<span class="things"></span>
					<h4>Discover <em>things to do</em></h4>
					<p>With Tripfab you'll discover amazing hotels, restaurants, places to see and things to do.</p>
				</div><!--EACH-->
				
				<div class="each">
					<span class="book"></span>
					<h4>book <em>what you love</em></h4>
					<p>Effortlessly book preplanned trips with the click of a button. </p>
				</div><!--EACH-->
				
				<div class="each">
					<span class="create"></span>
					<h4><em>or</em> create custom trips</h4>
					<p>Custom create your dream vacation à la carte – whatever you want, whenever you want.</p>
				</div><!--EACH-->
				
				<div class="each last">
					<span class="save"></span>
					<h4><em>and</em> save money</h4>
					<p>With Tripfab, you'll discover the most amazing deals on hotels, tours and activities.</p>
				</div><!--EACH-->
				<div class="clear"></div>
			</div><!--WRAP--> 
		</div><!--BOTTOM--> 
		
	</div><!--WRAP-TOP-->
	
	<div id="home_trips">
		<div class="wrap">
			<div class="featured">
				<div class="tabs">
					<ul>
						<li><a href="#hotels"><span class="hotel"></span>Featured Hotels</a></li>
						<li><a href="#activity"><span class="activity"></span>Featured Activities</a></li>
						<li><a href="#itinerary"><span class="itinerary"></span>Featured Itineraries</a></li>
					</ul>
					<div id="hotels">
						<div class="slideshow">
							<a href="" class="rgarrow"></a>
							<a href="" class="lfarrow"></a>
							<div class="cont">
								<div class="one">
									<img src="https://developer.tripfab.com/images6/home_pic1.jpg" width="563" height="260" alt="" />
									<h5>Hotel Punta Islita</h5>
									<span class="meta"><strong><em></em>Nicoya Peninsula,</strong> Costa Rica</span>
									<div class="price">
										<div>
											<span>75</span>
											<sup>$</sup>
											<div class="clear"></div>
										</div>
										<sub>Per Night</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
								</div><!--ONE-->
								
								<div class="one">
									<img src="https://developer.tripfab.com/images6/home_pic1.jpg" width="563" height="260" alt="" />
									<h5>Hotel Punta Islita</h5>
									<span class="meta"><strong><em></em>Nicoya Peninsula,</strong> Costa Rica</span>
									<div class="price">
										<div>
											<sup>$</sup>
											<span>75</span>
											<div class="clear"></div>
										</div>
										<sub>Per Night</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
								</div><!--ONE-->
								
							</div><!--CONT-->
						</div><!--SLIDESHOW-->
					</div><!--HOTELS-->
					
					<div id="activity">
						<div class="slideshow">
							<a href="" class="rgarrow"></a>
							<a href="" class="lfarrow"></a>
							<div class="cont">
								<div class="one">
									<img src="https://developer.tripfab.com/images6/home_pic1.jpg" width="563" height="260" alt="" />
									<h5>Hotel Punta Islita</h5>
									<span class="meta"><strong><em></em>Nicoya Peninsula,</strong> Costa Rica</span>
									<div class="price">
										<sup>$</sup>
										<span>75</span>
										<sub>Per Night</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
								</div><!--ONE-->
								
								<div class="one">
									<img src="https://developer.tripfab.com/images6/home_pic1.jpg" width="563" height="260" alt="" />
									<h5>Hotel Punta Islita</h5>
									<span class="meta"><strong><em></em>Nicoya Peninsula,</strong> Costa Rica</span>
									<div class="price">
										<sup>$</sup>
										<span>75</span>
										<sub>Per Night</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
								</div><!--ONE-->
								
							</div><!--CONT-->
						</div><!--SLIDESHOW-->
					</div><!--ACTIVTIY-->
					
					<div id="itinerary">
						<div class="slideshow">
							<a href="" class="rgarrow"></a>
							<a href="" class="lfarrow"></a>
							<div class="cont">
								<div class="one">
									<img src="https://developer.tripfab.com/images6/home_pic1.jpg" width="563" height="260" alt="" />
									<h5>Hotel Punta Islita</h5>
									<span class="meta"><strong><em></em>Nicoya Peninsula,</strong> Costa Rica</span>
									<div class="price">
										<sup>$</sup>
										<span>75</span>
										<sub>Per Night</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
								</div><!--ONE-->
								
								<div class="one">
									<img src="https://developer.tripfab.com/images6/home_pic1.jpg" width="563" height="260" alt="" />
									<h5>Hotel Punta Islita</h5>
									<span class="meta"><strong><em></em>Nicoya Peninsula,</strong> Costa Rica</span>
									<div class="price">
										<sup>$</sup>
										<span>75</span>
										<sub>Per Night</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
								</div><!--ONE-->
								
							</div><!--CONT-->
						</div><!--SLIDESHOW-->
					</div><!--ITINERARY-->
					
				</div><!--TABS-->
			</div><!--FEATURED-->
			<div class="side">
				<h5><span></span>Your Trips</h5>
				<div class="paging">
					<p>1 of 3 <span>of 5</span></p>
					<div><a href="" class="prev"></a></div>
					<a href="" class="next"></a>
				
				</div><!--PAGING-->
				<div class="cont">
					<div class="slides">
					
						<div class="single">
							<img width="109" height="88" alt="" src="https://developer.tripfab.com/images6/home_pic1.jpg" />
							<div class="info">
								<h6>Honeymoon</h6>
								<span class="meta"><em></em>7 Days Trip</span>
								<div class="prices">
									<sup>$</sup>
									<span>225</span>
									<sub>per person</sub>
								</div><!--PRICE-->
								<a href="" class="edit">Edit Trip</a>
							</div><!--INFO-->
						</div><!--SINGLE-->
						
						<div class="single">
							<img width="109" height="88" alt="" src="https://developer.tripfab.com/images6/home_pic1.jpg" />
							<div class="info">
								<h6>Weekend with my family</h6>
								<span class="meta"><em></em>7 Days Trip</span>
								<div class="prices">
									<sup>$</sup>
									<span>225</span>
									<sub>per person</sub>
								</div><!--PRICE-->
								<a href="" class="edit">Edit Trip</a>
							</div><!--INFO-->
						</div><!--SINGLE-->
						
						<div class="single last">
							<img width="109" height="88" alt="" src="https://developer.tripfab.com/images6/home_pic1.jpg" />
							<div class="info">
								<h6>Vacations!!!!</h6>
								<span class="meta"><em></em>7 Days Trip</span>
								<div class="prices">
									<sup>$</sup>
									<span>225</span>
									<sub>per person</sub>
								</div><!--PRICE-->
								<a href="" class="edit">Edit Trip</a>
							</div><!--INFO-->
						</div><!--SINGLE-->
						
					</div><!--SLIDES-->
					
					
					<div class="slides">
					
						<div class="single">
							<img width="109" height="88" alt="" src="https://developer.tripfab.com/images6/home_pic1.jpg" />
							<div class="info">
								<h6>Honeymoon</h6>
								<span class="meta"><em></em>7 Days Trip</span>
								<div class="prices">
									<sup>$</sup>
									<span>225</span>
									<sub>per person</sub>
								</div><!--PRICE-->
								<a href="" class="edit">Edit Trip</a>
							</div><!--INFO-->
						</div><!--SINGLE-->
						
						<div class="single">
							<img width="109" height="88" alt="" src="https://developer.tripfab.com/images6/home_pic1.jpg" />
							<div class="info">
								<h6>Honeymoon</h6>
								<span class="meta"><em></em>7 Days Trip</span>
								<div class="prices">
									<sup>$</sup>
									<span>225</span>
									<sub>per person</sub>
								</div><!--PRICE-->
								<a href="" class="edit">Edit Trip</a>
							</div><!--INFO-->
						</div><!--SINGLE-->
						
						<div class="single last">
							<img width="109" height="88" alt="" src="https://developer.tripfab.com/images6/home_pic1.jpg" />
							<div class="info">
								<h6>Honeymoon</h6>
								<span class="meta"><em></em>7 Days Trip</span>
								<div class="prices">
									<sup>$</sup>
									<span>225</span>
									<sub>per person</sub>
								</div><!--PRICE-->
								<a href="" class="edit">Edit Trip</a>
							</div><!--INFO-->
						</div><!--SINGLE-->
						
					</div><!--SLIDES-->
					
					
				</div><!--CONT-->
				
				
			</div><!--SIDE-->
			<div class="clear"></div>
		</div><!--WRAP-->
	</div><!--HOME_TRIPS-->
	
	<div id="popular-cities">
		<div class="wrap">
			<h5>Hot Cities in Costa Rica</h5>
			<div class="all">
				<?= $this->partial('partials/indexcities.phtml', array('cities'=>$this->cities, 'country'=>$this->country)) ?>
			</div><!--ALL--> 
		</div><!--WRAP--> 
	</div><!--POPULAR-CITIES-->
	
	<div class="more_info">
		<div id="newsletter">
			<div class="video">
				<a class="lbc" href="#video_player"></a>
				<p><strong>Watch our video</strong>30 second intro to <br />how TripFab works</p>
			</div><!--VIDEO-->
			
			<div class="cont">
				<?php if(!isset($_COOKIE['newsletter'])): ?>
				<p><strong>Sign up for our newsletter:</strong> Find out when we will launch in your city.</p>
				<form method="post" action="" class="section">
					<fieldset>
						<input type="text" name="email" value="Enter your e-mail here" />
						<input type="submit" value="Subscribe" class="btn-1 noclean" />
						<div class="clear"></div>
					</fieldset>
				</form>
				<div class="clear"></div>
			</div><!--CONT-->
			<div class="sent"><p><strong>Thanks, we'll keep you posted.</strong> In the meantime, you can start creating your next trip around Costa Rica.</p></div><!--SENT-->
			<?php else: ?>
			<div class="sent"><p><strong>Thanks, we'll keep you posted.</strong> In the meantime, you can start creating your next trip around Costa Rica.</p></div><!--SENT-->
			<?php endif ?>
		</div><!--NEWSLETTER-->
	</div><!--MORE_INFO-->

</div><!--WP_CONTENT-->
	<div id="wp_footer">
		<?= $this->partial('partials/footer.phtml'); ?>  
	</div><!--WP_FOOTER-->
</div><!--WP_ALL-->

<div class="hidden">
    <div id="video_player">
        <iframe src="https://player.vimeo.com/video/31072654?title=0&amp;byline=0&amp;portrait=0" width="640" height="360" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
    </div><!--VIDEO-PLAYER-->
</div><!--HIDDEN-->
<div id="citiesAutocompleteContainer"></div>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/index/index.js"></script>
<script type="text/javascript">
$(document).ready(function() {    
    $(".slideshow .cont").cycle({
    	timeout: 0,
		fx: 'scrollHorz',
		prev: '.lfarrow',
		next: '.rgarrow'
    	
    });
    $(".side .cont").cycle({
    	timeout: 0,
    	fx: 'scrollHorz',
    	prev: '.prev',
    	next: '.next'
    	
    });
    $(".featured .tabs").tabs();
    
    $('a.lbc').fancybox({
        padding: 0,
        overlayColor: '#FFF',
        overlayOpacity: '0.7',
        centerOnScroll:1
    });
	$('#newsletter form').submit(function(){
		$email = $(this).find('input[name=email]').val();
		if($email == "" || $email == "Enter your e-mail here") {
			$email.focus();
			return false;
		}

		$.ajax({
			type: 'POST',
			url: '/ajax/newssignup',
			data: {email:$email},
			success: function() {
				$('#newsletter .cont').fadeOut('fast', function(){
					$('#newsletter .sent').fadeIn('fast');
				});
				$.cookie('newsletter','1',{ expires: 365 })
			}
		});
		
		return false;
	});
});
</script> 
<script type="text/javascript">
$(document).ready(function(){
    img_ready($('img.background.high'));
});

function img_ready($obj){
    resizeImg($obj);
	$(window).resize(function() {
	   resizeImg($obj);
	});
	$obj.fadeIn();
}
function resizeImg($bgImg) { 
	var imgwidth = 1244;
	var imgheight = 490	;
	
	var winwidth = $(window).width();
	var winheight = $(window).height();
	
	var winCenter = winwidth / 2;
	var imgCenter = imgwidth / 2;
	
	var left = (winwidth > imgwidth) ? 0 : (winCenter - imgCenter);
	
	var width = (winwidth > imgwidth) ? winwidth : imgwidth;
	
	var height = (winwidth > imgwidth) ? ((imgheight * winwidth) / imgwidth) : height;
	
	var winCenter2 = imgheight / 2;
	var imgCenter2 = height / 2;
	
	var top = (winwidth > imgwidth) ? (winCenter2 - imgCenter2) : 0;
	
	$bgImg.css('left',left);
	$bgImg.css('width',width);
	$bgImg.css('height',height);
	$bgImg.css('top',top);
}
</script>
</body>
</html>