<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Plan the perfect trip, in one place. | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css2/index/index.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
	<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
	<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>    
    <div class="w2">
        <div class="home-search">
            <div class="wrapper">
                <div class="search-wrapper">
                    <h2>Plan the perfect trip, in one place.</h2>
                    <p>From things to do to everything in between - directly from business.</p>
                    <form action="">
                        <fieldset>
                            <input id="tags" type="text" value="Where do you want to go?" />
                        </fieldset>
                    </form>
                </div><!-- closes search-wrapper -->
                <div class="video-wrapper">
                    <img src="/images2/img-17.png" alt="" />
                </div><!-- closes video -->
            </div><!-- closes wrapper -->
        </div><!-- closes home-search -->
        
        <?php if(!$this->user): ?>
        <div class="bar">
            <div class="wrapper">
                <a href="/signup" class="btn-2">Sign Up Now</a>
                Tripfab helps you to create and book fabolous trips, removing middle layers that makes you save money!
            </div><!-- closes wrapper -->
        </div><!-- closes bar -->
        <?php endif ?>
        
        <div class="home-boxes wrapper">
            <div class="box">
                <a href=""><img src="/images2/img-18.png" alt="" /></a>
            </div><!-- closes box -->
            <div class="box">
                <a href=""><img src="/images2/img-19.png" alt="" /></a>					
            </div><!-- closes box -->
            <div class="box">
                <a href=""><img src="/images2/img-20.png" alt="" /></a>					
            </div><!-- closes box -->
            <div class="box last">
                <a href="/vendor-signup"><img src="/images2/img-21.png" alt="" /></a>					
            </div><!-- closes box -->
        </div><!-- closes home-boxes -->
        <div class="home-cities wrapper">
            <div class="ttl">
                <form action="">
                    <fieldset>
                        <label>Country</label>
                        <select name="countries">
						<?php foreach($this->countries as $c): ?>
							<?php if($c->id == $this->country->id): ?>
                            <option selected="selected" value="<?= $c->id ?>"><?= $c->title ?></option>
                            <?php else: ?>
                            <option value="<?= $c->id ?>"><?= $c->title ?></option>
                            <?php endif ?>
                        <?php endforeach ?>
                        </select>
                    </fieldset>
                </form>
                See what's new in the most popular cities in the world!
                <div class="clear"></div>
            </div><!-- closes ttl -->
            <div class="cities">
            	<?= $this->partial('partials/indexcities.phtml', array('cities'=>$this->cities, 'country'=>$this->country)) ?>
            </div><!-- closes cities -->
        </div><!-- closes home-cities -->
        <div class="press wrapper">
            As seen on <img src="/images2/img-22.png" alt="" />
        </div><!-- closes press -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js2/jquery.input.value.js"></script>
<script type="text/javascript" src="/js2/common.js"></script>
<script type="text/javascript" src="/js2/index/index.js"></script>
</body>
</html>