<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
	<title>Tripfab - Making your trip fabulous!</title>
    <link type="image/png" rel="icon" href="/images2/favicon3.ico" />
    <link type="text/css"  rel="stylesheet" href="/css6/reset.css?v=000000000000068" />
    <link type="text/css"  rel="stylesheet" href="/css6/home2.css?v=000000000000068" />
    <link type="text/css"  rel="stylesheet" href="/css6/common.css?v=000000000000068" />
    <link type="text/css"  rel="stylesheet" href="/css2/index/index.css?v=000000000000068" />
    <link type="text/css"  rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=000000000000068" />
    <link type="text/css"  rel="stylesheet" href="/css6/calendar.css?v=000000000000068">
	<!--[if IE 7]><link type="text/css" rel="stylesheet" href="css2/ie.css" /><![endif]-->
	<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
	<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
	<script type="text/javascript" src="/js2/jquery.js?v=000000000000068"></script>
	<script type="text/javascript" src="/js2/index/index.js?v=000000000000068"></script>
	<script type="text/javascript">
		$(document).ready(function() {
			$(".tabs").tabs();
		});
	</script>
</head>
<body id="home">
	<div id="wp_all">
		<div id="wp_header">
			<div id="header">
			    <div class="wrapper">
			        <h1 class="logo"><a href="/">Tripfab</a></h1>
			        <div class="top_search">
			            <form method="post" action="/costa_rica">
			                <fieldset>
			                    <input id="citiesSearch" type="text" value="Search for a city..."/>
			                    <a href="/costa_rica" class="srcBtn">Search</a>
			                    <div id="note3" class="note"><em></em>
			                       	<p class="flag">We have listings only in <strong>Costa Rica</strong>, other countries coming soon.</p>
			                    	</div><!--NOTE1-->
			                    <div id="note4" class="note"><em></em>
			                    	<p><strong>0 Results. </strong>You know we work just in Costa Rica. Right?</p>
			                    </div><!--NOTE2-->
			                </fieldset>
			            </form>
			        </div><!--TOP_SEARCH-->
			        <div class="rg">
			                        <a href="#" id="cart" class="js-cart js-get-cart js-new-trip">
			            <span class="num"></span></a>
			            <div class="js-cart-placeholder"></div>
			            <div class="user-menu js-header-user-menu">
			                <span class="arrow"></span>
							                <div class="main">
			        			        			<img  class="" src="/cache/423a3645f4b41708e91e83abd57ac828_w72_h72_cp." width="72" height="72" />                    <ul>
			                        <!--<li><a href="/user/trips">My Trips</a></li>-->
			                        <li><a href="/user/account" class="account">Account</a></li>
			                        <li><a href="/user/messages">Messages</a></li>
			                        <li><a href="/user/reservations">Reservations</a></li>
			                    </ul>
			                </div><!--MAIN-->
			                <div class="bot">
			                    <a href="/logout" class="sign_out">Sign Out</a>
			                </div><!--BOT-->
							            </div><!--USER-MENU-->
			                                    <div id="logged_in"><a class="js-header-account" href="/login">My Account<span class="aw"></span></a></div><!--LOGGED_IN-->
			                        <div class="overlay js-menu-overlay-login"></div>
			            <div class="phone">
			                <span>Customer Service</span> <strong>1-866-401-0382</strong>
			            </div><!--PHONE-->
			        </div><!--RG-->
			    </div><!--WRAPPER-->
			</div><!--HEADER-->
		</div><!--WP_HEADER-->
		<div id="wp_content">
			<div id="main">
			
				<div class="wrap">
					<h2>Be Your Own Travel Agent</h2>
					<div class="steps">
						<div class="first">
							<h3>Tell us where<br /> you want to go</h3>
						</div><!--FIRST-->
						<div class="mid">
							<h3>Create a trip and start adding listings of hotels, tours, and everything else.</h3>
						</div><!--MID-->
						<div class="last">
							<h3>Book it directly from<br /> business owners.</h3> 
						</div><!--LAST-->
						<div class="clear"></div>
					</div><!--STEPS-->
					
					<div id="search">
						<form method="post" action="">
							<fieldset>
								<div class="box"><input type="text" value="Search for cities" /></div>
							</fieldset>
						</form>
					</div><!--SEARCH-->
					<div class="btn">
						<span class="label">What do we do?</span>
						<a href="">Learn More <em></em></a>
					</div><!--BTN-->
				</div><!--WRAP-->
			</div><!--MAIN-->
			<div class="expand">
				
			</div><!--EXPAND-->
			<div id="featured">
				<div class="tabs">
					<ul>
						<li><a href="#hotels"><em class="i1"></em>Featured Hotels</a></li>
						<li><a href="#activities"><em class="i2"></em>Featured Activities</a></li>
						<li><a href="#trips"><em class="i3"></em>Featured Trips</a></li>
					</ul>
					
					<div id="hotels" class="cycle">
						<div class="inner">
							<div class="single">
								<img src="http://static.tripfab.com/images6/HomeDefault.png" width="" height="" alt="" />
								<h5>La Reserva Vacation Villas</h5>
								<span class="meta"><em></em>Tamarindo, CR</span>
								<div class="info">
									<div class="price">
										<sup>$</sup>
										<span>229</span>
										<sub>per person</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
									
									<a href="">Visit Listing</a>
									<div class="clear"></div>
								</div><!--INFO-->
							</div><!--SINGLE-->
							
							<div class="single">
								<img src="http://static.tripfab.com/images6/HomeDefault.png" width="" height="" alt="" />
								<h5>La Reserva Vacation Villas</h5>
								<span class="meta"><em></em>Tamarindo, CR</span>
								<div class="info">
									<div class="price">
										<sup>$</sup>
										<span>229</span>
										<sub>per person</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
									
									<a href="">Visit Listing</a>
									<div class="clear"></div>
								</div><!--INFO-->
							</div><!--SINGLE-->
							
							<div class="single">
								<img src="http://static.tripfab.com/images6/HomeDefault.png" width="" height="" alt="" />
								<h5>La Reserva Vacation Villas</h5>
								<span class="meta"><em></em>Tamarindo, CR</span>
								<div class="info">
									<div class="price">
										<sup>$</sup>
										<span>229</span>
										<sub>per person</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
									
									<a href="">Visit Listing</a>
									<div class="clear"></div>
								</div><!--INFO-->
							</div><!--SINGLE-->
							
							<div class="single last">
								<img src="http://static.tripfab.com/images6/HomeDefault.png" width="" height="" alt="" />
								<h5>La Reserva Vacation Villas</h5>
								<span class="meta"><em></em>Tamarindo, CR</span>
								<div class="info">
									<div class="price">
										<sup>$</sup>
										<span>229</span>
										<sub>per person</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
									
									<a href="">Visit Listing</a>
									<div class="clear"></div>
								</div><!--INFO-->
							</div><!--SINGLE-->
							
							<div class="clear"></div>
							
						</div><!--INNER-->					
					</div><!--HOTELS-->
					
					<div id="activities" class="cycle">
						<div class="inner">
							<div class="single">
								<img src="http://static.tripfab.com/images6/HomeDefault.png" width="" height="" alt="" />
								<h5>La Reserva Vacation Villas</h5>
								<span class="meta"><em></em>Tamarindo, CR</span>
								<div class="info">
									<div class="price">
										<sup>$</sup>
										<span>229</span>
										<sub>per person</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
									
									<a href="">Visit Listing</a>
									<div class="clear"></div>
								</div><!--INFO-->
							</div><!--SINGLE-->
							
							<div class="single">
								<img src="http://static.tripfab.com/images6/HomeDefault.png" width="" height="" alt="" />
								<h5>La Reserva Vacation Villas</h5>
								<span class="meta"><em></em>Tamarindo, CR</span>
								<div class="info">
									<div class="price">
										<sup>$</sup>
										<span>229</span>
										<sub>per person</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
									
									<a href="">Visit Listing</a>
									<div class="clear"></div>
								</div><!--INFO-->
							</div><!--SINGLE-->
							
							<div class="single">
								<img src="http://static.tripfab.com/images6/HomeDefault.png" width="" height="" alt="" />
								<h5>La Reserva Vacation Villas</h5>
								<span class="meta"><em></em>Tamarindo, CR</span>
								<div class="info">
									<div class="price">
										<sup>$</sup>
										<span>229</span>
										<sub>per person</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
									
									<a href="">Visit Listing</a>
									<div class="clear"></div>
								</div><!--INFO-->
							</div><!--SINGLE-->
							
							<div class="single last">
								<img src="http://static.tripfab.com/images6/HomeDefault.png" width="" height="" alt="" />
								<h5>La Reserva Vacation Villas</h5>
								<span class="meta"><em></em>Tamarindo, CR</span>
								<div class="info">
									<div class="price">
										<sup>$</sup>
										<span>229</span>
										<sub>per person</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
									
									<a href="">Visit Listing</a>
									<div class="clear"></div>
								</div><!--INFO-->
							</div><!--SINGLE-->
							
							<div class="clear"></div>
							
						</div><!--INNER-->	
					</div><!--ACTIVITIES-->
					
					<div id="trips">
						<div class="inner">
							<div class="single">
								<img src="http://static.tripfab.com/images6/HomeDefault.png" width="" height="" alt="" />
								<h5>La Reserva Vacation Villas</h5>
								<span class="meta"><em></em>Tamarindo, CR</span>
								<div class="info">
									<div class="price">
										<sup>$</sup>
										<span>229</span>
										<sub>per person</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
									
									<a href="">Visit Listing</a>
									<div class="clear"></div>
								</div><!--INFO-->
							</div><!--SINGLE-->
							
							<div class="single">
								<img src="http://static.tripfab.com/images6/HomeDefault.png" width="" height="" alt="" />
								<h5>La Reserva Vacation Villas</h5>
								<span class="meta"><em></em>Tamarindo, CR</span>
								<div class="info">
									<div class="price">
										<sup>$</sup>
										<span>229</span>
										<sub>per person</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
									
									<a href="">Visit Listing</a>
									<div class="clear"></div>
								</div><!--INFO-->
							</div><!--SINGLE-->
							
							<div class="single">
								<img src="http://static.tripfab.com/images6/HomeDefault.png" width="" height="" alt="" />
								<h5>La Reserva Vacation Villas</h5>
								<span class="meta"><em></em>Tamarindo, CR</span>
								<div class="info">
									<div class="price">
										<sup>$</sup>
										<span>229</span>
										<sub>per person</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
									
									<a href="">Visit Listing</a>
									<div class="clear"></div>
								</div><!--INFO-->
							</div><!--SINGLE-->
							
							<div class="single last">
								<img src="http://static.tripfab.com/images6/HomeDefault.png" width="" height="" alt="" />
								<h5>La Reserva Vacation Villas</h5>
								<span class="meta"><em></em>Tamarindo, CR</span>
								<div class="info">
									<div class="price">
										<sup>$</sup>
										<span>229</span>
										<sub>per person</sub>
										<div class="clear"></div>
									</div><!--PRICE-->
									
									<a href="">Visit Listing</a>
									<div class="clear"></div>
								</div><!--INFO-->
							</div><!--SINGLE-->
							
							<div class="clear"></div>
							
						</div><!--INNER-->	
					</div><!--TRIPS-->
					
					
					
				</div><!--TABS-->
				
			</div><!--FEATURED-->
			
			<div id="recommend">
				<div class="ttl"><span><em></em>Recommend Cities in Costa Rica</span></div><!--TTL-->
				<ul>
					<li><a href="">Tamarindo</a></li>
					<li><a href="">Drake Bay</a></li>
					<li><a href="">Jacó</a></li>
					<li><a href="">La Fortuna</a></li>
					<li><a href="">Monteverde</a></li>
					<li><a href="">San Jose</a></li>
					<li><a href="">Puerto Viejo</a></li>
				</ul>
				<ul>
					<li><a href="">Tamarindo</a></li>
					<li><a href="">Drake Bay</a></li>
					<li><a href="">Jacó</a></li>
					<li><a href="">La Fortuna</a></li>
					<li><a href="">Monteverde</a></li>
					<li><a href="">San Jose</a></li>
					<li><a href="">Puerto Viejo</a></li>
				</ul>
				<ul>
					<li><a href="">Tamarindo</a></li>
					<li><a href="">Drake Bay</a></li>
					<li><a href="">Jacó</a></li>
					<li><a href="">La Fortuna</a></li>
					<li><a href="">Monteverde</a></li>
					<li><a href="">San Jose</a></li>
					<li><a href="">Puerto Viejo</a></li>
				</ul>
				<ul>
					<li><a href="">Tamarindo</a></li>
					<li><a href="">Drake Bay</a></li>
					<li><a href="">Jacó</a></li>
					<li><a href="">La Fortuna</a></li>
					<li><a href="">Monteverde</a></li>
					<li><a href="">San Jose</a></li>
					<li><a href="">Puerto Viejo</a></li>
				</ul>
				<ul>
					<li><a href="">Tamarindo</a></li>
					<li><a href="">Drake Bay</a></li>
					<li><a href="">Jacó</a></li>
					<li><a href="">La Fortuna</a></li>
					<li><a href="">Monteverde</a></li>
					<li><a href="">San Jose</a></li>
					<li><a href="">Puerto Viejo</a></li>
				</ul>
				
				<ul class="last">
					<li><a href="">Tamarindo</a></li>
					<li><a href="">Drake Bay</a></li>
					<li><a href="">Jacó</a></li>
					<li><a href="">La Fortuna</a></li>
					<li><a href="">Monteverde</a></li>
					<li><a href="">San Jose</a></li>
					<li><a href="">Puerto Viejo</a></li>
				</ul>                   
				<div class="clear"></div>
			</div><!--RECOMMEND-->
		</div><!--WP_CONTENT-->
		<div id="wp_footer">
			<div id="footer">
				<div class="wrap">
					<span class="flag"></span>
					<div class="left">
						<div class="number"><span></span>Toll Free: +1-866-401-0382</div>
						<span>&copy; Copyright  2012 Tripfab. All rights reserved.</span>
					</div><!--LEFT-->
					
					<div class="right">
						<ul>
							<li>Connect with TripFab</li>
							<li><a target="_blank" href="https://twitter.com/tripfab"><em class="tw"></em>Twitter</a></li>
							<li><a target="_blank" href="https://facebook.com/tripfab"><em class="fb"></em>Facebook</a></li>
							<li><a target="_blank" href="https://plus.google.com/108576021199856132768/"><em class="gl"></em>Google+</a></li>
						</ul>
						<ul>
							<li>Boring Stuff</li>
							<li><a href="/terms">Terms of Use</a></li>
							<li><a href="/policies">Privacy</a></li>
						</ul>
						<ul>
							<li>Company</li>
							<li><a href="/contact">Contact Us</a></li>
							<li><a target="_blank" href="http://blog.tripfab.com">Blog</a></li>
						</ul>
					</div><!--RIGHT-->
					<div class="bot"><p><em></em>Tripfab is lovingly designed in a tropical paradise</p></div>
				</div><!--WRAP-->
			</div><!--FOOTER-->
		</div><!--WP_FOOTER-->
	</div><!--WRAPPER_ALL-->
</body>
</html>