<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> - <?= $this->city->title ?>, <?= $this->country->title ?> | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/jquery-ui-1.8.16.custom.css" />
    <link type="text/css" rel="stylesheet" href="/css2/index/listing-activity.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
    
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', 
	array('user'=>$this->user,'full'=>true)); ?>
    <div class="w2">
        <div class="main wrapper">
            <div class="content-2">
                <div class="box">
                    <?= $this->partial('partials/gallery.phtml', 
					array('user'=>$this->user, 'listing' => $this->listing, 'city' => $this->city, 
						  'country' => $this->country,'pictures' => $this->pictures,'trips'=>$this->trips, 'edit'=>false)); ?>
                </div><!-- closes box -->
                <div class="tabs-wrapper-2">
                    <ul>
                        <li><a href="#tabs-1">Overview</a></li>
                        <li><a href="#tabs-2">FAQ's</a></li>
                    </ul>
                    <div class="tab" id="tabs-1">
                    	<?php if(!empty($this->overview->about) or
									!empty($this->overview->about) or
									!empty($this->overview->about)): ?>
                        <div class="tab-ttl">About <?= $this->listing->title ?></div>
                        <div class="tab-content">
                        	<?php if(!empty($this->overview->about)): ?>
                        	<h2>About the spot</h2>
                        	<p><?= stripslashes(nl2br($this->overview->about)) ?></p>
                            <?php endif ?>
                            <?php if(!empty($this->overview->expect)): ?>
                            <h2>What to expect</h2>
                            <p><?= stripslashes(nl2br($this->overview->expect)) ?></p>
                            <?php endif ?>
                            <?php if(!empty($this->overview->love)): ?>
                            <h2>Things you'll love</h2>
                            <p><?= stripslashes(nl2br($this->overview->love)) ?></p>
                            <?php endif ?>
                            <?php if(count($this->details) > 0): ?>
                            <h2>Polices</h2>
                            <ul>
                            	<?php foreach($this->details as $detail): ?>
                                <?php if($detail->type == 3): ?>
                                <li><?= stripslashes($detail->text) ?></li>
                                <?php endif ?>
                                <?php endforeach ?>
                            </ul>
                            <?php endif ?>
                        </div><!-- closes tab-content -->
                        <?php else: ?>
                        <div class="tab-content">
                        	<p>No overview added</p>
                        </div>
                        <?php endif ?>
                    </div><!-- closes tab -->
                    <div class="tab" id="tabs-2">
                        <?php if(count($this->faqs) > 0): ?>
                        <div class="tab-ttl">
                            Frequently Asked Questions
                        </div><!-- closes tab-ttl -->
                        <div class="tab-content faqs">
                            <ul>
                            	<?php foreach($this->faqs as $faq): ?>
                                <li>
                                    <strong><?= stripslashes(nl2br($faq->question)) ?></strong><br />
                                    <?= stripslashes(nl2br($faq->answer)) ?>
                                </li>
                                <?php endforeach ?>
                            </ul>
                        </div><!-- closes tab-content -->
                        <?php else: ?>
                        <div class="tab-content">
                        	<p>No FAQS added</p>
                        </div>
                        <?php endif ?>
                    </div><!-- closes tab -->								
                </div><!-- closes tabs-wrapper -->                
                <div class="reviews-wrapper">
                    <?= $this->partial('partials/reviews.phtml', 
					array('reviews' => $this->reviews, 'questions' => $this->questions, 'answer_allow' => false,
						  'user'=>$this->user, 'listing' => $this->listing->id)); ?>
                </div><!-- closes reviews-wrapper -->
            </div><!-- closes content-2 -->
            
            <div class="right-sidebar">
                <div class="widget book">
                    <div class="ttl">
                        <span>Entertainment</span>
                    </div><!-- closes ttl -->
                    <div class="map-wrapper">
                        <h4>Location</h4>
                        <?php if(!is_null($this->listing->lat)): ?>
                        <div id="mapcanvas"></div>
                        <div class="mapshadow"></div><!--SHADOW-->
                        <address>
                            <p><strong><?= $this->listing->title ?></strong></p>
                            <p><?= $this->listing->address ?></p>
                        </address>
                        <?php else: ?>
                        <div id="mapcanvas"></div>
                        <div class="mapshadow"></div><!--SHADOW-->
                        <address>
                            <p><strong><?= $this->listing->title ?></strong></p>
                            <p>Not address added</p>
                        </address>
                        <?php endif ?>
                    </div><!-- closes map-wrapper -->
                </div><!-- closes widget -->
                <div class="widget talk">
                    <?= $this->partial('partials/talk.phtml',array('vendor'=>$this->vendor,'user' => $this->user)); ?>
                </div><!-- closes widget -->
            </div><!-- closes right-sidebar -->
        </div><!-- closes main -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->	
<div id="citiesAutocompleteContainer"></div>
<input type="hidden" value="<?= ($this->listing->lat) ? $this->listing->lat : 'none' ?>" name="listlat" />
<input type="hidden" value="<?= ($this->listing->lng) ? $this->listing->lng : 'none' ?>" name="listlng" />
<input type="hidden" value="<?= $this->listing->title ?>" name="listtitle" />
<input type="hidden" value="<?= $this->listing->id ?>" name="listingids" />

<div class="hidden">
	<div id="send_message">
	    <form action="" id="sendMessageForm">
	        <div class="lb-forgot">
	            <div class="ttl">Send a message <em>to</em> <?= $this->vendor->name ?></div>
	            <div class="intro_m">
	            	<p><strong>Questions or concerns about the activity?</strong>
	            		Please write a message and you’ll get an answer very soon.</p>
	            </div><!--INTRO-->
	            <div class="content">
	                <textarea cols="30" name="message" rows="1"></textarea>
	            </div><!-- closes content -->
	            <div class="bottom">
	                <input type="submit" class="btn-1" value="Send Message" />
	                <span onclick="$.fancybox.close()" class="btn-10">Cancel</span>	
	            </div><!-- closes bottom -->
	        </div><!-- closes lb-forgot -->
	        <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
	    </form>
	</div><!--SEND_MESSAGE-->
    <div id="live_chat">
    	<img src="/images2/chat.png" />
    </div>
    <div id="start_call">
    	<div id="dialpad" class="lb">
            <div class="top">Dial your phone number</div><!--TOP-->
            <div class="middle">
                <p>We'll connect you with the vendor in few minutes. Directly.</p>
                <div class="number-display">
                    <a href="#" class="flag"><img src="/images2/flags/us.png" width="16" height="16" alt="" /></a>
                    <div class="all_flags">
                        <a href="#" class="up" onMouseover="move('container',10)" onMouseout="clearTimeout(move.to)"></a>
                        <a href="#" class="down" onMouseover="move('container',-10)" onMouseout="clearTimeout(move.to)"></a>
                        <div class="holder">
                            <div id="container" style="position:absolute;width:282px;left:0;top:0">
                                <p>ALL COUNTRIES</p>
                                <?php foreach($this->countries as $c): ?>
                                <a href="#" data-code="<?= $c->phone ?>"><img src="/images2/flags/<?= strtolower($c->code) ?>.png" width="16" height="16" alt="" />
                                <?= $c->title ?> <strong>(+<?= $c->phone ?>)</strong></a>
                                <?php endforeach ?> 
                            </div><!--CONTAINER-->
                        </div><!--HOLDER-->
                    </div><!--ALL_FLAGS-->
                    <input type="text" name="number" value="" />
                    <input type="hidden" name="code" value="1" />
                    <a href="" class="close"></a>
                    <div class="clear"></div>
                </div><!--NUMBER-DISPLAY-->
                <div class="numbers">
                    <a data-num="1" href="">1</a>
                    <a data-num="2" href="">2<span>ABC</span></a>
                    <a data-num="3" href="">3<span>DEF</span></a>
                    <a data-num="4" href="">4<span>GHI</span></a>
                    <a data-num="5" href="">5<span>JKL</span></a>
                    <a data-num="6" href="">6<span>MNO</span></a>
                    <a data-num="7" href="">7<span>PQRS</span></a>
                    <a data-num="8" href="">8<span>TUV</span></a>
                    <a data-num="9" href="">9<span>WXYZ</span></a>
                    <a data-num="*" href="">*</a>
                    <a data-num="0" href="">0</a>
                    <a data-num="#" href="">#</a>
                </div><!--NUMBERS-->
                <div class="control">
                    <input type="button" name="start" class="btn-1" value="Start Call" />
                    <input type="button" name="Cancel"  class="cancel" value="Cancel" />
                </div><!--CONTROL-->
            </div><!--MIDDLE-->
        </div><!--DIALPAD-->
    </div>
    <div id="newtrip">
    	<div id="create_trip">
			<form action="">
                <div class="top">
                    <h3>Create a New Trip</h3>
                    <p>Complete the information below to start your next trip</p>
                </div><!--TOP-->
                <div class="cont">
                    <fieldset>
                        <div class="item">
                            <label class="trip">Trip Name</label>
                            <input type="text" name="title" value="" />
                        </div><!--ITEM-->
                        <div class="item">
                            <label class="dates">Trip Dates</label>
                            <input class="start" type="text" name="start" value="Starting Date" />
                            <input class="end"type="text" name="end" value="Ending Date" />
                            <label class="check">
                                <input type="checkbox" class="nodatesyet"/>
                                I don't know the travel dates yet
                            </label>
                        </div><!--ITEM-->
                        <div class="item last">
                                <input type="checkbox" checked="checked" />
                                <p>I want to receive special offers from vendors near
                                    of the places I'll visit in this trip</p>
                        </div><!--ITEM-->
                    </fieldset>
                </div><!--CONT-->
                <div class="bottom">
                    <input type="submit" class="btn-1 noclean" value="Create Trip" />
                    <input type="button" onclick="$.fancybox.close(); return false;" class="btn-10 noclean" value="Cancel" />
                </div><!--BOTTOM-->
                <input type="hidden" name="trip" value="new" />
                <input type="hidden" name="listing" value="" />
            </form>
		</div><!--CREATE_TRIP-->
    </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/jquery.popupWindow.js"></script>
<script type="text/javascript" src="/js2/index/listing-entertaiment.js"></script>
<style type="text/css">#mapcanvas { width:246px;  height:175px; }</style>
</body>
</html>