<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css6/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css" />
    <link type="text/css" rel="stylesheet" href="/css6/section1.css" />
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript" src="/js2/index/listing-restaurant.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('.imgs').cycle({
                timeout: 0,
                fx: 'scrollHorz',
                prev: '.lf-arrow',
                next: '.rg-arrow'
            });
            $( ".single a" ).click(function() {
                $id = $(this).attr('href');
                $(".single a").removeClass('active');
                $(this).addClass('active');
                $(".slideshow img" ).removeClass('show');
                $($id).addClass('show');
                return false
            });
        });
    </script>
    <style type="text/css">
	#mapcanvas { width:285px;  height:171px; }
	</style>   
</head>
<body class="bg_ts">
<div id="wp_all">
    <div id="wp_header">
		<?= $this->partial('partials/header-v2.phtml', array('user'=>$this->user,'full'=>true)); ?>
    </div><!--WP_HEADER-->
    <div id="wp_content">
        <div id="cont_bl">
            <div class="lstng_dflt" id="sight">
                <div class="top">
                    <div class="cntrl">
                        <ul class="breadcrump">
                            <li class="first"><a href="/" class="home"></a></li>
                            <li><a href="/<?= $this->country->identifier ?>"><?= $this->country->title ?></a></li>
                            <li><a href="/<?= $this->country->identifier ?>/<?= $this->city->identifier ?>"><?= $this->city->title ?></a></li>
                            <li class="last"><a href="/<?= $this->country->identifier ?>/<?= $this->city->identifier ?>/#/tourist-sights"
                            class="active">Tourist Sights</a></li>
                        </ul>
                        <a href="/<?= $this->country->identifier ?>/<?= $this->city->identifier ?>/#/tourist-sights" 
                        class="link1">&larr; Back to Results</a>
                        <div class="clear"></div>
                    </div><!--CNTRL-->
                    
                    <div class="description">
                        <div class="slideshow">
                        	<?php foreach($this->pictures as $i=>$pic): ?>
                            <?php $class = ($i == 0) ? 'show' : '' ?>
                            <?= $this->thumbnail(array('width'=>298,'height'=>212), $pic->url, $class, '298:212', 'img'.$i) ?>
                            <?php endforeach ?>
                        </div><!--SLIDESHOW-->
                        <div class="info">
                            <h2><?= $this->listing->title ?></h2>
                            <span class="location"><em></em><strong><?= $this->city->title ?>,</strong> <?= $this->country->title ?>
                            <img src="/images6/flag<?= strtoupper($this->country->code) ?>.png" width="" height="" alt="" /></span>
                            <a href="" class="btn-1"><span></span>Add to My Trips</a>
                            <div class="text">
                                <ul class="rating">
                                    <li><a href="" class="slct"></a></li>
                                    <li><a href="" class="slct"></a></li>
                                    <li><a href="" class="slct"></a></li>
                                    <li><a href="" class="nrml"></a></li>
                                    <li><a href="" class="nrml"></a></li>
                                </ul>
                                <div class="clear"></div>
                            </div><!--TEXT-->
                            <div class="photos">
                                <a href="" class="lf-arrow"></a>
                                <div class="imgs">
                                	<?php for($i=0; $i<count($this->pictures); $i=$i+10): ?>
                                    <div class="single">
                                    	<?php for($j=$i;$j<($i+10); $j++):?>
                                        <?php if(isset($this->pictures[$j])): ?>
                                        <?php $pic = $this->pictures[$j] ?>
                                        <?php $class = ($j == 0) ? 'active' : '' ?>
                                        <a class="<?= $class ?>" href="#img<?= $j ?>"><?= $this->thumbnail(65, $pic->url, '', '1:1') ?></a>
                                        <?php else: ?>
                                        <img src="/images2/empty-small-photo.png" width="65" height="65" />
                                        <?php endif ?>
                                        <?php endfor ?>
                                    </div>
                                    <?php endfor ?>
                                </div><!--IMGS-->
                                <a href="" class="rg-arrow"></a>
                            </div><!--PHOTOS-->
                        </div><!--INFO-->
                        <div class="clear"></div>
                    </div><!--DESCRIPTION-->
                </div><!--TOP-->
                <div class="container">
                    <div class="sidebar">
                        <div class="map">
                            <div class="cont">
                                <div class="map_canvas">
                                	<div id="mapcanvas"></div>                                
                                </div><!--MAP_CANVAS-->
                            </div><!--CONT-->
                        </div><!--MAP-->
                        <?php if(!empty($this->listing->address)): ?>
                        <div class="location">
                            <img src="/images6/map_<?= strtolower($this->country->code) ?>.png" class="country" width="45" height="43" alt="" />
                            <p><strong>Location</strong> <?= $this->listing->address ?></p>
                            <div class="clear"></div>
                        </div><!--LOCATION-->
                        <?php endif ?>
                    </div><!--SIDEBAR-->
                    
                    <div class="content">
                        <div class="descrip">
                            <h3>Description</h3>
							<?php if(!empty($this->overview->about)): ?>
                            <p>About the spot</p>
                            <p><?= stripslashes(nl2br($this->overview->about)) ?></p>
                            <?php endif; if(!empty($this->overview->expect)): ?>
                            <p>What to expect</p>
                            <p><?= stripslashes(nl2br($this->overview->expect)) ?></p>
                            <?php endif; if(!empty($this->overview->love)): ?>
                            <p>Things you'll love</p>
                            <p><?= stripslashes(nl2br($this->overview->love)) ?></p>
                            <?php endif ?>
                        </div><!--DESCRIP-->
                        
                        <div class="direcctions">
                            <h3>How to get there</h3>
							<?php if(!empty($this->getthere->plane)): ?>
                            <div class="single">
                                <h4><span class="plane"></span>By Plane</h4>
                                <p><?= stripslashes(nl2br($this->getthere->plane)) ?></p>
                            </div><!--DFLT-->
                            <?php endif; if(!empty($this->getthere->car)): ?>
                            <div class="single">
                                <h4><span class="car"></span>By Car</h4>
                                <p><?= stripslashes(nl2br($this->getthere->car)) ?></p>
                            </div><!--DFLT-->
                            <?php endif; if(!empty($this->getthere->bus)): ?>
                            <div class="single">
                                <h4><span class="bus"></span>By Bus</h4>
                                <p><?= stripslashes(nl2br($this->getthere->bus)) ?></p>
                            </div><!--DFLT-->
                            <?php endif; if(!empty($this->getthere->train)): ?>
                            <div class="single">
                                <h4><span class="train"></span>By Train</h4>
                                <p><?= stripslashes(nl2br($this->getthere->train)) ?></p>
                            </div><!--DFLT-->
                            <?php endif; if(!empty($this->getthere->boat)): ?>
                            <div class="single">
                                <h4><span class="boat"></span>By Boat</h4>
                                <p><?= stripslashes(nl2br($this->getthere->boat)) ?></p>
                            </div><!--DFLT-->
                            <?php endif ?>
                        </div><!--DIRECCTIONS-->
                        <div class="clear"></div>
                    </div><!--CONTENT-->
                    <div class="clear"></div>
                </div><!--CONTAINER-->
            </div><!--LSTNG_DFLT-->
        </div><!--CONT_BL-->
    </div><!--WP_CONTENT-->
    <div id="wp_footer">
		<?= $this->partial('partials/footer.phtml'); ?>
    </div><!--WP_FOOTER-->
</div><!--WRAPPER_ALL-->
<input type="hidden" value="<?= ($this->listing->lat) ? $this->listing->lat : 'none' ?>" name="listlat" />
<input type="hidden" value="<?= ($this->listing->lng) ? $this->listing->lng : 'none' ?>" name="listlng" />
<input type="hidden" value="<?= $this->listing->title ?>" name="listtitle" />
<input type="hidden" value="<?= $this->listing->id ?>" name="listingids" />
</body>
</html>

<?php /*<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
<meta content="noindex,nofollow" name="robots" />
<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
<title><?= $this->listing->title ?> - <?= $this->city->title ?>, <?= $this->country->title ?> | Tripfab.com</title>
<link type="text/css" rel="stylesheet" href="/css2/reset.css" />
<link type="text/css" rel="stylesheet" href="/css2/all.css" />
<link type="text/css" rel="stylesheet" href="/css2/jquery-ui-1.8.16.custom.css" />
<link type="text/css" rel="stylesheet" href="/css2/index/listing-activity.css" />
<link type="text/css" rel="stylesheet" href="/css2/common.css" />
<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
<link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />
<!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
<!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
<!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
<style type="text/css">#mapcanvas { width:246px;  height:175px; }</style>
</head>
<body>
<div class="w1">
<?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>    
<div class="w2">
    <div class="main wrapper">
        <div class="content-2">
            <div class="box">
                <?= $this->partial('partials/gallery.phtml', 
                array('user'=>$this->user,'listing'	=> $this->listing, 'city' => $this->city, 
                      'country' => $this->country,'pictures' => $this->pictures,'trips'=>$this->trips, 'edit'=>false)); ?>
            </div><!-- closes box -->                    
            <div class="tabs-wrapper-2">
                <ul>
                    <li><a href="#tabs-1">Overview</a></li>
                    <li><a href="#tabs-2">FAQ's</a></li>
                </ul>
                <div class="tab" id="tabs-1">
                    <?php if(!empty($this->overview->about) or
                                !empty($this->overview->about) or
                                !empty($this->overview->about)): ?>
                    <div class="tab-ttl">About <?= $this->listing->title ?></div>
                    <div class="tab-content">
                        <?php if(!empty($this->overview->about)): ?>
                        <h2>About the spot</h2>
                        <p><?= stripslashes(nl2br($this->overview->about)) ?></p>
                        <?php endif; if(!empty($this->overview->expect)): ?>
                        <h2>What to expect</h2>
                        <p><?= stripslashes(nl2br($this->overview->expect)) ?></p>
                        <?php endif; if(!empty($this->overview->love)): ?>
                        <h2>Things you'll love</h2>
                        <p><?= stripslashes(nl2br($this->overview->love)) ?></p>
                        <?php endif ?>
                    </div><!-- closes tab-content -->
                    <?php else: ?>
                    <div class="tab-content">
                        <p>No overview added</p>
                    </div>
                    <?php endif ?>
                </div><!-- closes tab -->
                <div class="tab" id="tabs-2">
                    <?php if(count($this->faqs) > 0): ?>
                    <div class="tab-ttl">
                        Frequently Asked Questions
                    </div><!-- closes tab-ttl -->
                    <div class="tab-content faqs">
                        <ul>
                            <?php foreach($this->faqs as $faq): ?>
                            <li>
                                <strong><?= stripslashes(nl2br($faq->question)) ?></strong><br />
                                <?= stripslashes(nl2br($faq->answer)) ?>
                            </li>
                            <?php endforeach ?>
                        </ul>
                    </div><!-- closes tab-content -->
                    <?php else: ?>
                    <div class="tab-content">
                        <p>No FAQS added</p>
                    </div>
                    <?php endif ?>
                </div><!-- closes tab -->								
            </div><!-- closes tabs-wrapper -->
            <div class="reviews-wrapper">
                <?= $this->partial('partials/reviews.phtml', 
                array('reviews' => $this->reviews, 'questions' => $this->questions, 'answer_allow' => false,
                      'user'=>$this->user, 'listing' => $this->listing->id)); ?>
            </div><!-- closes reviews-wrapper -->
        </div><!-- closes content-2 -->
        
        <div class="right-sidebar">
            <div class="widget book">
                <div class="map-wrapper">
                    <h4>Location</h4>
                    <?php if(!is_null($this->listing->lat)): ?>
                    <div id="mapcanvas"></div>
                    <div class="mapshadow"></div><!--SHADOW-->
                    <address>
                        <p><strong><?= $this->listing->title ?></strong></p>
                        <p><?= $this->listing->address ?></p>
                    </address>
                    <?php else: ?>
                    <div id="mapcanvas"></div>
                    <div class="mapshadow"></div><!--SHADOW-->
                    <address>
                        <p><strong><?= $this->listing->title ?></strong></p>
                        <p>No address added</p>
                    </address>
                    <?php endif ?>
                </div><!-- closes map-wrapper -->
            </div><!-- closes widget -->
            <div class="widget near">
                <div>
                    <h6>Nearest Hotels</h6>
                    <ul>
                        <li>
                            <a href="">
                                <img src="/images2/img-29.png" alt="" />
                                <strong>Hotel Silencio</strong>
                                <span>2.5 Km</span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="/images2/img-29.png" alt="" />
                                <strong>Hotel Silencio</strong>
                                <span>2.5 Km</span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="/images2/img-29.png" alt="" />
                                <strong>Hotel Silencio</strong>
                                <span>2.5 Km</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div>
                    <h6>Nearest Activities</h6>
                    <ul>
                        <li>
                            <a href="">
                                <img src="/images2/img-29.png" alt="" />
                                <strong>Surfing</strong>
                                <span>2.5 Km</span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="/images2/img-29.png" alt="" />
                                <strong>Surfing</strong>
                                <span>2.5 Km</span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="/images2/img-29.png" alt="" />
                                <strong>Surfing</strong>
                                <span>2.5 Km</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div>
                    <h6>Nearest Restaurants</h6>
                    <ul>
                        <li>
                            <a href="">
                                <img src="/images2/img-29.png" alt="" />
                                <strong>Restaurant 1420</strong>
                                <span>2.5 Km</span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="/images2/img-29.png" alt="" />
                                <strong>Restaurant 1420</strong>
                                <span>2.5 Km</span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="/images2/img-29.png" alt="" />
                                <strong>Restaurant 1420</strong>
                                <span>2.5 Km</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div>
                    <h6>Nearest Entertainments</h6>
                    <ul>
                        <li>
                            <a href="">
                                <img src="/images2/img-29.png" alt="" />
                                <strong>Teatro Oscar Fessler</strong>
                                <span>2.5 Km</span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="/images2/img-29.png" alt="" />
                                <strong>Teatro Oscar Fessler</strong>
                                <span>2.5 Km</span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="/images2/img-29.png" alt="" />
                                <strong>Teatro Oscar Fessler</strong>
                                <span>2.5 Km</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div><!-- closes widget -->
        </div><!-- closes right-sidebar -->
    </div><!-- closes main -->
</div><!-- closes w2 -->
<?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->	
<div id="citiesAutocompleteContainer"></div>
<input type="hidden" value="<?= ($this->listing->lat) ? $this->listing->lat : 'none' ?>" name="listlat" />
<input type="hidden" value="<?= ($this->listing->lng) ? $this->listing->lng : 'none' ?>" name="listlng" />
<input type="hidden" value="<?= $this->listing->title ?>" name="listtitle" />
<div style="display:none">
<div id="newtrip">
    <div id="create_trip">
        <form action="">
            <div class="top">
                <h3>Create a New Trip</h3>
                <p>Complete the information below to start your next trip</p>
            </div><!--TOP-->
            <div class="cont">
                <fieldset>
                    <div class="item">
                        <label class="trip">Trip Name</label>
                        <input type="text" name="title" value="" />
                    </div><!--ITEM-->
                    <div class="item">
                        <label class="dates">Trip Dates</label>
                        <input class="start" type="text" name="start" value="Starting Date" />
                        <input class="end"type="text" name="end" value="Ending Date" />
                        <label class="check">
                            <input type="checkbox" class="nodatesyet"/>
                            I don't know the travel dates yet
                        </label>
                    </div><!--ITEM-->
                    <div class="item last">
                            <input type="checkbox" checked="checked" />
                            <p>I want to receive special offers from vendors near
                                of the places I'll visit in this trip</p>
                    </div><!--ITEM-->
                </fieldset>
            </div><!--CONT-->
            <div class="bottom">
                <input type="submit" class="btn-1 noclean" value="Create Trip" />
                <input type="button" onclick="$.fancybox.close(); return false;" class="btn-10 noclean" value="Cancel" />
            </div><!--BOTTOM-->
            <input type="hidden" name="trip" value="new" />
            <input type="hidden" name="listing" value="" />
        </form>
    </div><!--CREATE_TRIP-->
</div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/index/listing-touristsight.js"></script>
</body>
</html>
*/ ?>