<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <meta name="robots" content="noindex, nofollow" />
    <title><?= strip_tags($this->translate('Index Title')) ?> | Tripfab.com</title>
    <meta http-equiv="description" name="description" content="<?= $this->translate('Index Description') ?>" />
    <link type="text/css" rel="stylesheet" href="/css4/all.css" />
	<link rel="icon" type="image/png" href="/images3/favicon.png" />
    <script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
	$(function(){
		$('.language a.current').click(function(){
			$(this).toggleClass('active');
			$('.language .select').toggleClass('show');
			return false;
		});
		
		$('#signupForm').validate({
			rules: {
				name:'required',
				company:'required',
				email:'required email',
				code:'required',
				phone:'required',
				website:'required url',
				business:'required',
				country:'required',
			}
		});
	});
	</script>
    <style type="text/css">
		#signupForm fieldset div { position:relative;}
		input.error { border:1px solid #F00;}
		label.error {     
			background: none repeat scroll 0 0 #FF0000;
			bottom: 10px;
			color: #FFFFFF !important;
			padding: 2px 4px;
			position: absolute;
			right: 24px;}
	</style>
</head>
<body class="home v4">
<div id="header-shadow">
    <div id="header">
        <div class="wrapper">
            <h1 class="logo"><a href="/en-US">TripFab</a></h1>
            <div class="right">
                <div class="language">
                    <a class="current" href="#">English</a>
                    <div class="select">
                        <ul>
                            <li class="en active"><a href="/en-US">English</a></li>
                            <li class="es"><a href="/es-ES">Español</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="right">
                <a href="/en-US/login" class="btn-1">Sign In</a>
                Have an account?
            </div><!-- closes right -->
        </div><!-- closes wrapper -->				
    </div><!-- closes header -->
</div><!-- closes header-shadow -->
<div id="top">			
    <div class="content wrapper">
        <h2>Multiply <em>your reservations</em> with us</h2>
        <h3>Double and triple your current reservations by joining the TripFab platform.</h3>
        
        <div class="all_content">
            <div class="left">
                <div class="player">
                    <iframe src=" http://player.vimeo.com/video/31072654?title=0&byline=0&portrait=0" width="580" height="326" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
                </div><!--PLAYER-->
                <h4>A few reasons you'll love Tripfab</h4>
                <p>Tripfab is the best platform to manage your business, completely free.</p>
                <ul class="list">
                    <li>
                        <h5><img src="/images4/icon_1.gif" width="39" height="39" alt="" />Manage Everything</h5>
                        <p>Your business will get its own profile and you will have the option to list all the activities that you offer.</p>
                        <a href="/en-US/about">Read more</a>
                    </li>
                    <li>
                        <h5><img src="/images4/icon_6.gif" width="38" height="41" alt="" />Millions of Users</h5>
                        <p>You will be seen by thousands of TripFab users as it puts your business in front of the eyes of travelers interested  on your services.</p>
                        <a href="/en-US/about">Read more</a>
                    </li>
                    <li>
                        <h5><img src="/images4/icon_2.gif" width="48" height="39" alt="" />Payments</h5>
                        <p>Get full control and instant access to all your payments in one single place, making payment management a piece of cake.</p>
                        <a href="/en-US/about">Read more</a>
                    </li>
                    <li>
                        <h5><img src="/images4/icon_3.gif" width="38" height="39" alt="" />Control your Business</h5>
                        <p>For the first time, Tripfab allows travelers to be their own travel agents so they can discover travel businesses just like you.</p>
                        <a href="/en-US/about">Read more</a>
                    </li>
                </ul>
            </div><!--LEFT-->
            <div class="right">
                <div class="request">
                    <h3><span>Get an Invitation to join Tripfab</span></h3>
                    <div class="cont_form">
                        <form id="signupForm" action="/en-US/signup" method="post">
                            <fieldset>
                            	<div>
                                <label>Company Name</label>
                                <input value="" name="name" type="text" placeholder="Enter your company name" />
                                </div>
                            	<div>
                                <label>Company E-mail</label>
                                <input value="" name="email" type="text" placeholder="Enter your company e-mail" />
                                </div>
                            	<div>
                                <label>Contact Name</label>
                                <input value="" name="contact" type="text" placeholder="The person in charge of this account" />
                                </div>
                            	<div>
                                <label>Company Phone</label>
                                <input value="" name="code" class="code" type="text" placeholder="Code" />
                                <input value="" name="phone" class="phone" type="text" placeholder="Phone Number" />
                                </div>
                            	<div>
                                <label>Website</label>
                                <input value="" name="website" type="text" placeholder="Enter your website domain" />
                                </div>
                            	<div>
                                <label>Business Type</label>
                                <select name="business">
                                    <option value="">Select your business type</option>
                                    <option value="Hotel">Hotels & Resorts</option>
                                    <option value="Activity">Tours & Activities</option>
                                    <option value="Restaurant">Restaurants & Cafe</option>
                                    <option value="Entertainment">Entertainment & Events</option>
                                </select>	
                                </div>
                            	<div>
                                <label>Country</label>
                                <select name="country">
                                    <option value="">Select your Country</option>
                                	<?php foreach($this->countries as $c): ?>
                                    <option value="<?= $c->title ?> - <?= $c->id ?>"><?= $c->title ?></option>
                                    <?php endforeach ?>
                                </select>
                                </div>
                                <div class="button">
                                    <input type="submit" class="noclean" value="Send Request" />
                                </div><!--BUTTON-->
                            </fieldset>
                        </form>
                    </div><!--CONT_FORM-->
                </div><!--REQUEST-->
                <div class="separator"><span></span></div>
                <div class="subscribe">
                    <form action="">
                        <fieldset>
                            <label><span>Are you a traveler?</span></label>
                            <input type="text" value="Get News and Updates" />
                            <input type="button" value="Subscribe" />
                        </fieldset>
                    </form>
                </div><!--SUBSCRIBE-->
            </div><!--RIGHT-->
        </div><!--ALL_CONTENT-->
    </div><!-- closes content -->
</div><!-- closes top -->

<div class="sticky">
        <div class="texture">
            <div id="bottom">
                <div class="wrapper">
                    <div class="center">
                        <div class="items-wrapper">
                            <div class="item">
                                <img src="/images4/img-13-en-US.png" width="179" height="31" alt="" />
                            </div><!-- closes item -->
                            <div class="item item-2">
                                <a href="/en-US/signup" class="en-US"><img src="images4/cleardot.gif" alt="" /></a>
                            </div><!-- closes item -->
                            <div class="item">
                                <img src="/images4/img-15-en-US.png" width="35" height="162" alt="" />
                            </div><!-- closes item -->
                            <div class="item item-4">
                                <a href="/en-US/about" class="en-US"><img src="/images4/cleardot.gif" alt="" /></a>
                            </div><!-- closes item -->
                            <div class="item">
                                <img src="/images4/img-17-en-US.png" width="179" height="23" alt="" />
                            </div><!-- closes item -->
                        </div><!-- closes items-wrapper -->
                    </div><!-- closes center -->
                </div><!-- closes wrapper -->
            </div><!-- closes bottom -->
        </div><!-- closes texture -->			
        <div id="footer">
            <div id="footer-gradient">
                <div class="wrapper">
                	<ul>
                        <li><a href="https://www.facebook.com/TripFab">Facebook</a></li>
                        <li><a href="https://twitter.com/#!/TripFab">Twitter</a></li>
                        <li><a href="https://plus.google.com/108576021199856132768">Google+</a></li>
                        <li><a href="mailto:hello@tripfab.com">eMail</a></li>
                        <li><a href="http://blog.tripfab.com/">Blog</a></li>
                    </ul>
                    <img src="/images4/logo-2.png" width="36" height="32" alt="" class="logo" />
                    <strong>Tripfab is beautifully designed in a tropical paradise</strong>
                    <span>Copyright &copy; 2011 Tripfab</span>
                </div><!-- closes wrapper -->	
            </div><!-- closes footer-gradient -->					
        </div><!-- footer -->
    </div><!-- closes sticky -->
</div><!-- closes container -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24981182-1']);
  _gaq.push(['_trackPageview']);

  (function() {
	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
</body>
</html>