<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <meta name="robots" content="noindex, nofollow" />
    <title><?= strip_tags($this->translate('Index Title')) ?> | Tripfab.com</title>
    <meta http-equiv="description" name="description" content="<?= $this->translate('Index Description') ?>" />
    <link type="text/css" rel="stylesheet" href="/css4/all.css" />
	<link rel="icon" type="image/png" href="/images3/favicon.png" />
    <script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
	$(function(){
		$('.language a.current').click(function(){
			$(this).toggleClass('active');
			$('.language .select').toggleClass('show');
			return false;
		});
		
		$('#signupForm').validate({
			rules: {
				name:'required',
				company:'required',
				email:'required email',
				code:'required',
				phone:'required',
				website:'required url',
				business:'required',
				country:'required',
			}
		});
	});
	</script>
    <style type="text/css">
		#signupForm fieldset div { position:relative;}
		input.error { border:1px solid #F00;}
		label.error {     
			background: none repeat scroll 0 0 #FF0000;
			bottom: 10px;
			color: #FFFFFF !important;
			padding: 2px 4px;
			position: absolute;
			right: 24px;}
	</style>
</head>
<body class="home v4">
<div id="header-shadow">
    <div id="header">
        <div class="wrapper">
            <h1 class="logo"><a href="/es-ES">TripFab</a></h1>
            <div class="right">
                <div class="language">
                    <a class="current" href="#">Español</a>
                    <div class="select">
                        <ul>
                            <li class="en"><a href="/en-US">English</a></li>
                            <li class="es active"><a href="/es-ES">Español</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="right">
                <a href="/es-ES/login" class="btn-1">Ingresar</a>
                ¿Tiene una cuenta?
            </div><!-- closes right -->
        </div><!-- closes wrapper -->				
    </div><!-- closes header -->
</div><!-- closes header-shadow -->
<div id="top">			
    <div class="content wrapper">
        <h2>Multiplica <em>tus reservaciones</em> con nosotros.</h2>
        <h3>Duplica y triplica tus reservaciones actuales uni&eacute;ndote a la plataforma TripFab.</h3>
        <div class="all_content">
            <div class="left">
                <div class="player">
                    <iframe src="http://player.vimeo.com/video/34488150?title=0&byline=0&portrait=0" width="580" height="326" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
                </div><!--PLAYER-->
                <h4>Algunas razones por las cuales amar&aacute;s TripFab</h4>
                <p>TripFab es la mejor plataforma para administrar tu negocio, y es gratis.</p>
                <ul class="list">
                    <li>
                        <h5><img src="images4/icon_1.gif" width="39" height="39" alt="" />Administra todo</h5>
                        <p>Tu negocio contar&aacute; con su propio perfil y tendr&aacute;s la opci&oacute;n de listar todas las actividades que ofreces.</p>
                        <a href="/es-ES/about">Leer m&aacute;s</a>
                    </li>
                    <li>
                        <h5><img src="images4/icon_6.gif" width="38" height="41" alt="" />Millones de usuarios</h5>
                        <p>Ser&aacute;s visto por los miles de usuarios de TripFab al poner tu negocio frente a los ojos de viajeros interesados en tus servicios.</p>
                        <a href="/es-ES/about">Leer m&aacute;s</a>
                    </li>
                    <li>
                        <h5><img src="images4/icon_2.gif" width="48" height="39" alt="" />Pagos</h5>
                        <p>Obt&eacute;n control total y acceso instant&aacute;neo a todos tus pagos en un mismo lugar, haci&eacute;ndolo muy sencillo.</p>
                        <a href="/es-ES/about">Leer m&aacute;s</a>
                    </li>
                    <li>
                        <h5><img src="images4/icon_3.gif" width="38" height="39" alt="" />Controla tu negocio</h5>
                        <p>Por primera vez, TripFab permite a los viajeros ser sus propios agentes de viaje para que puedan descubrir negocios como el tuyo.</p>
                        <a href="/es-ES/about">Leer m&aacute;s</a>
                    </li>
                </ul>
            </div><!--LEFT-->
            <div class="right">
                <div class="request">
                    <h3><span>Obt&eacute;n una invitaci&oacute;n gratuita</span></h3>
                    <div class="cont_form">
                    	<form id="signupForm" action="/es-ES/signup" method="post">
                            <fieldset>
                            	<div>
                                <label>Nombre de la compa&ntilde;&iacute;a</label>
                                <input value="" name="name" type="text" placeholder="Ingresa el nombre de tu compa&ntilde;&iacute;a" />
                                </div>
                            	<div>
                                <label>Correo electr&oacute;nico</label>
                                <input value="" name="email" type="text" placeholder="Ingresa el correo electr&oacute;nico de tu compa&ntilde;&iacute;a" />
                                </div>
                            	<div><label>Nombre de contacto</label>
                            	  <input value="" name="contact" type="text" placeholder="Nombre del encargado de la cuenta" />
                              </div>
                            	<div><label>Tel&eacute;fono de la compa&ntilde;&iacute;a</label>
                            	  <input value="" name="code" class="code" type="text" placeholder="C&ocute;digo" />
                                <input value="" name="phone" class="phone" type="text" placeholder="N&uacute;mero de tel&eacute;fono" />
                              </div>
                            	<div>
                                <label>Sitio Web</label>
                                <input value="" name="website" type="text" placeholder="Ingresa la direcci&oacute;n de tu sitio web" />
                                </div>
                            	<div>
                                <label>Tipo de compañ&iacute;a</label>
                                <select name="business">
                                    <option value="">Selecciona el tipo de tu compa&ntilde;&iacute;a</option>
                                    <option value="Hotel">Hoteles y Resorts</option>
                                    <option value="Activity">Tours y Actividades</option>
                                    <option value="Restaurant">Restaurantes y Cafes</option>
                                    <option value="Entertainment">Entretenimiento y Eventos</option>
                                </select>	
                                </div>
                            	<div>
                                <label>Pa&iacute;s</label>
                                <select name="country">
                                    <option value="">Selecciona tu pa&iacute;s</option>
                                	<?php foreach($this->countries as $c): ?>
                                    <option value="<?= $c->title ?> - <?= $c->id ?>"><?= $c->title ?></option>
                                    <?php endforeach ?>
                                </select>
                                </div>
                                <div class="button">
                                    <input type="submit" class="noclean" value="Enviar Petici&oacute;n" />
                                </div><!--BUTTON-->
                            </fieldset>
                        </form>
                    </div><!--CONT_FORM-->
                </div><!--REQUEST-->
                
                <div class="separator"><span></span></div>
                <div class="subscribe">
                    <form action="">
                        <fieldset>
                            <label><span>¿Eres un viajero?</span></label>
                            <input type="text" value="Obt&eacute;n noticias y actualizaciones" />
                            <input type="button" value="Suscr&iacute;bete" />
                        </fieldset>
                    </form>
                </div><!--SUBSCRIBE-->
            </div><!--RIGHT-->
        </div><!--ALL_CONTENT-->
    </div><!-- closes content -->
</div><!-- closes top -->

<div class="sticky">
        <div class="texture">
            <div id="bottom">
                <div class="wrapper">
                    <div class="center">
                        <div class="items-wrapper">
                            <div class="item">
                                <img src="images4/img-13-es-ES.png" width="136" height="31" alt="" />
                            </div><!-- closes item -->
                            <div class="item item-2">
                                <a href="/es-ES/signup" class="es-ES"><img src="images4/cleardot.gif" alt="" /></a>
                            </div><!-- closes item -->
                            <div class="item">
                                <img src="images4/img-15-en-US.png" width="35" height="162" alt="" />
                            </div><!-- closes item -->
                            <div class="item item-4">
                                <a href="/es-ES/about" class="es-ES"><img src="images4/cleardot.gif" alt="" /></a>
                            </div><!-- closes item -->
                            <div class="item">
                                <img src="images4/img-17-es-ES.png" width="179" height="23" alt="" />
                            </div><!-- closes item -->
                        </div><!-- closes items-wrapper -->
                    </div><!-- closes center -->
                </div><!-- closes wrapper -->
            </div><!-- closes bottom -->
        </div><!-- closes texture -->			
        <div id="footer">
            <div id="footer-gradient">
                <div class="wrapper">
                	<ul>
                        <li><a href="https://www.facebook.com/TripFab">Facebook</a></li>
                        <li><a href="https://twitter.com/#!/TripFab">Twitter</a></li>
                        <li><a href="https://plus.google.com/108576021199856132768">Google+</a></li>
                        <li><a href="mailto:hello@tripfab.com">eMail</a></li>
                        <li><a href="http://blog.tripfab.com/">Blog</a></li>
                    </ul>
                    <img src="/images4/logo-2.png" width="36" height="32" alt="" class="logo" />
                    <strong>TripFab es hermosamente diseñado en un para&iacute;so tropical.</strong>
                    <span>Derechos Reservados &copy; 2011 Tripfab</span>
                </div><!-- closes wrapper -->	
            </div><!-- closes footer-gradient -->					
        </div><!-- footer -->
    </div><!-- closes sticky -->
</div><!-- closes container -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24981182-1']);
  _gaq.push(['_trackPageview']);

  (function() {
	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
</body>
</html>