<?php $url = $this->baseUrl() .'/'. $this->country->identifier .'/'. $this->city->identifier .'/filter';
$cat = $this->cat; $subcat = $this->subcat; $sort = $this->sort; $stars  = $this->stars; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $_GET['q'] ?>, Search Results | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js2/jquery.input.value.js"></script>
    <script type="text/javascript" src="/js2/index.city.js"></script>
    <script type="text/javascript" src="/js/scrollElement.jQuery.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('input').ToggleInputValue();
        });
		
		$(function(){
			var $search = <?= $this->tags ?>;
	    	$( "#citiesSearch" ).autocomplete({
	    		source: $search,
	    		select:function(e, ui){
	    			window.location = ui.item.url
	    		},
				appendTo:'#citiesAutocompleteContainer'
			}).data( "autocomplete" )._renderItem = function( ul, item ) {
				return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( '<a href="'+item.url+'">' + item.label + "</a>" )
				.appendTo( ul ); 
			};
			$( "#citiesSearch2" ).autocomplete({
	    		source: $search,
	    		select:function(e, ui){
	    			window.location = ui.item.url
	    		},
				appendTo:'#citiesAutocompleteContainer2'
			}).data( "autocomplete" )._renderItem = function( ul, item ) {
				return $( "<li></li>" )
				.data( "item.autocomplete", item )
				.append( '<a href="'+item.url+'">' + item.label + "</a>" )
				.appendTo( ul );
			};
		});
    </script>
    <style type="text/css">
	.ui-autocomplete { 
		background:#fff; 
		border:1px solid #D8D8D8; 
		border-top:none; 
		width:220px !important; 
		list-style:none; 
		max-height:200px; 
		overflow-y:auto; 
		z-index:100 !important;
		height:auto !important;}
	.ui-autocomplete li a {
		display:block;
		line-height:20px;
		color:#000;}
	.ui-autocomplete li a.ui-state-hover {
		background:#8DC63F;
		color:#fff;
		text-decoration:none;}
	#citiesAutocompleteContainer2 .ui-autocomplete { min-height:210px; width:546px !important; background:#fff; border-color:#E8E7E7;}
	#citiesAutocompleteContainer2 .ui-autocomplete li a { line-height:35px; color:#616161; padding:0 20px; font-size:16px; font-weight:bold;}
	#citiesAutocompleteContainer2 .ui-autocomplete li a.ui-state-hover { 
		color:#fff;
		text-shadow:1px 1px #030;
	}
	
	.result { height:340px; }
	
	.results-wrapper { position:relative;}
	.results-wrapper .loading { 
		position:absolute; 
		width:100%; 
		height:100%; 
		background:url('/images2/loading-bg.png');
		top:0; 
		left:0px; 
		z-index:10;
		display:none;}
	.results-wrapper .loading .load {
		width:200px;
		margin:0 0 0 283px;
		background:#303030;
		line-height:50px;
		font-size:26px;
		color:#fff;
		font-weight:bold;
		text-align:center;
		position:fixed;
		top:250px;
		left:1;}
	ul.cat-menu { margin-top:0px; padding-top:14px; }
	ul.cat-menu li a { 
		position:relative;
		z-index:11;}
	.main.wrapper .left-sidebar { min-height:1px; }
	</style>
</head>
<body>
<div class="w1">
    <?php if(!$this->user): ?>
    <div id="sign-up">
        <div class="wrapper">
            <a href="/signup" class="btn-2">Sign Up</a>
            Tripfab helps you to create, share and book fabolous trips, removing middle layers that saves you money!
        </div><!-- closes wrapper -->
    </div><!-- closes sign-up -->
    <?php endif ?>
    <div id="header">
        <div class="wrapper">
            <h1 class="logo"><a href="/">Tripfab</a></h1>
            <ul>
                <li><a href="/top-spots">Top Spots</a></li>
                <li><a href="/trips">Browse Trips</a></li>
                <li><a href="/comunity">Community</a></li>
                <li class="imp"><a href="/trip/plan">Plan Trip</a></li>
            </ul>
            <div class="header-search">
                <form method="post" action="">
                    <fieldset>
                        <input id="citiesSearch" type="text" value="Search Places"/>
                    </fieldset>
                </form>
            </div><!-- closes header-search -->
            <div class="header-login">
            	<?php if(!$this->user): ?>
                <a href="/login" class="btn-1">Login</a>
    			<?php else: ?>
                <a href="/user/account" class="user"><?= $this->user->name ?></a>
	            <?php endif ?>
            </div><!-- closes header-login -->
        </div><!-- closes wrapper -->			
    </div><!-- closes header -->
    <div class="w2">
        <div class="main-search wrapper">
            <span><a href="" class="link-2">View Trip Plans in your country</a></span>
            <form action="">
                <fieldset>
                    <input id="citiesSearch2" type="text" value="<?= $_GET['q'] ?>" />
                    <input type="submit" value="Search" class="btn-1"/>
                </fieldset>
            </form>
        </div><!-- closes main-search -->
        
        <div class="main wrapper">
            <div class="left-sidebar">
            	<div class="scrollcontainer">
                <ul class="cat-menu">
                	<?php $ii = 1 ?>
                	<?php foreach($this->categories as $i => $category): ?>
					<?php $_cat = strtolower(str_replace(' ','-',$category['name'])) ?>
                    <?php $class = ($cat == $_cat) ? 'active ' : ''; ?>
                    <?php $class.= ($i == (count($this->categories) - 1)) ? 'last' : ''; ?>
                    <li class="item-<?= $ii ?> <?= $class ?>">
                    <a data-cat="<?= $_cat ?>" href="#<?= $_cat ?>">
                    <img src="/images2/cleardot.gif" alt="" />
                    <?= $category['name'] ?></a></li>
                    <?php $ii++ ?>
                    <?php endforeach ?>
                </ul>
                <div class="widget slider">
                    <h4><img src="/images2/cleardot.gif" alt="" />Price Per Person</h4>
                    <span id="value-4">Free - $1000</span>
                    <div id="slider-4"></div>
                </div><!-- closes widget -->
                <div class="widget destinations">
                    <h4><img src="/images2/cleardot.gif" alt="" />Destinations</h4>
                    <form action="">
                        <fieldset>
                            <p><input type="checkbox" /><label>All Destinations</label></p>
                            <p><input type="checkbox" /><label>Tamarindo</label></p>
                            <p><input type="checkbox" /><label>Manuel Antonio</label></p>
                            <p><input type="checkbox" /><label>Jac&oacute;</label></p>
                            <p><input type="checkbox" /><label>Uvita</label></p>
                            <p><input type="checkbox" /><label>San Jos&eacute;</label></p>
                            <p><input type="checkbox" /><label>Cartago</label></p>
                        </fieldset>
                    </form>
                    <a href="">See More &darr;</a>
                </div><!-- closes widget -->
                </div>
            </div><!-- closes left-sidebar -->
            <div class="content">
                <div class="results-wrapper">
                	<div class="loading"><div class="load">Loading...</div></div>
                	<?php foreach($this->listings as $i => $list): ?>
                    <?php $class = ((($i+1) % 3) == 0) ? 'last' : '' ?>
                    <div class="result <?= $class ?>">
                        <div class="img-wrapper">
                            <a href="<?= str_replace('filter', $list->identifier, $url) ?>" class="been">Been there</a>
                            <?= $this->thumbnail(array('width'=>'225', 'height'=>'167'), $list->image, '','225:167') ?>
                            <h4><?= $list->title ?></h4>
                        </div><!-- closes img-wrapper -->
                        <div class="meta">
                            <span class="cat-1"><img src="/images2/cleardot.gif" alt="" /><?= $this->categories[$list->main_type]['name'] ?></span>
                            <?php if($list->price > 0): ?>
                            <strong>$<?= $list->price ?><em> / person</em></strong>
                            <?php endif ?>
                        </div><!-- closes meta -->
                        <p class="listing_description"><?= $list->description ?></p>
                        <a href="<?= str_replace('filter', $list->identifier, $url) ?>" class="btn-1">View activity</a>
                    </div><!-- closes result -->
                    <?php endforeach ?>
                </div><!-- closes results-wrapper -->
            </div><!-- closes content -->
        </div><!-- closes main -->
    </div><!-- closes w2 -->
    <div class="footer">
        <div class="wrapper">
            <p><img src="/images2/logo-2.png" alt="" /><strong>Tripfab</strong> is lovely designed in a <strong>tropical paradise</strong></p>
            <ul>
                <li><a href="">Contact</a></li>
                <li><a href="">Blog</a></li>
                <li><a href="">Twitter</a></li>
                <li><a href="">Facebook</a></li>
                <li><a href="">Terms</a></li>
                <li><a href="">Privacy</a></li>
            </ul>
        </div><!-- closes wrapper -->
    </div><!-- closes footer -->
</div><!-- closes w1 -->
<div id="citiesAutocompleteContainer"></div>
<div id="citiesAutocompleteContainer2"></div>
<input type="hidden" id="hddCityId" name="hddCityId" value="<?= $this->city->identifier ?>" />
<input type="hidden" id="hddCountryId" name="hddCountryId" value="<?= $this->country->identifier ?>" />
</body>
</html>