<?php if(!is_null($this->user) and $this->user->role_id = 2): ?>
<?php if(count($this->trips) > 0): ?>
<a href="" class="addToTripBtn <?= $this->class ?>" data-listing="<?= $this->listing->id ?>"><span></span>Add to My Trips</a>
<?php else: ?>
<a href="" class="addToTripBtn not js-new-trip <?= $this->class ?>" data-listing="<?= $this->listing->id ?>"><span></span>Add to My Trips</a>
<?php endif ?>
<?php else: ?>
<a href="#" class="<?= $this->class ?> js-signup"><span></span>Add to My Trips</a>
<?php endif ?>