<div id="footer">
	<div class="wrap">
		<span class="flag"></span>
		<p><strong>Tripfab is lovingly designed in a tropical paradise</strong>Copyright &copy; 2011 Tripfab</p>
		<ul>
			<li><a href="https://facebook.com/tripfab">Facebook</a></li>
			<li><a href="https://twitter.com/tripfab">Twitter</a></li>
			<li><a href="https://plus.google.com/108576021199856132768/">Google+</a></li>
			<li><a href="mailto:hello@tripfab.com">eMail</a></li>
			<li><a href="http://blog.tripfab.com">Blog</a></li>
		</ul>
	</div><!--WRAP-->
</div><!--FOOTER-->
<div id="citiesAutocompleteContainer"></div>

<div class="hidden">
	<div id="signUp" class="signLog">
		<div class="top">
			<h2>Sign up for TripFab. <span>It’s Free!</span></h2>
			<p>You need to create an account to continue</p>
		</div><!--TOP-->
		<div class="cont">
			<a href="" class="fb"></a>		
			<div class="contForm">
				<em>Or</em>
				<form method="post" action="https://developer.tripfab.com/en-US/login">
					<input class="name" type="text" name="" value="Name" />
					<input class="lastName" type="text" name="" value="Last Name" />
					<input class="email" type="text" name="" value="E-mail" />
					<input class="password" type="text" name="" value="Password" />
					<input class="confirm" type="text" name="" value="Confirm Password" />
					<div class="cntrl">
						<label><input type="checkbox" name="remenber" value="" /> Remember me next time</label>
						<input type="submit" class="btn-1 noclean" value="Create Account" />
					</div><!--CNTRL-->
				</form>
			</div><!--CONTFORM-->
			<div class="note">
				<p>By clicking "Create Account" or "Sign up with Facebook,"<br />
					you confirm that you accept the <a href="/terms" class="link1">Terms of Service.</a> </p>
			</div>
		</div><!--CONT-->
		<div class="bottom">
			<h6>Already an TripFab member? <a href="#signIn" class="link1 lbc">Sign In Now</a></h6>
		</div><!--BOTTOM-->
	</div><!--SIGNUP-->
	
	
	<div id="signIn" class="signLog">
		<div class="top">
			<h2>Sign into your TripFab account</h2>
			<p>Welcome back, we love you :)</p>
		</div><!--TOP-->
		<div class="cont">
			<a href="" class="fb"></a>		
			<div class="contForm">
				<em>Or</em>
				<form method="post" action="https://developer.tripfab.com/en-US/login">
					<input class="email" type="text" name="" value="E-mail" />
					<input class="password" type="text" name="" value="Password" />
					<div class="cntrl">
						<label><input type="checkbox" name="remenber" value="" /> Remember me next time</label>
						<input type="submit" class="btn-1 noclean" value="Create Account" />
					</div><!--CNTRL-->
				</form>
			</div><!--CONTFORM-->
			<div class="note">
				<p><a href="" class="link1">Forgot password?</a> </p>
			</div>
		</div><!--CONT-->
		<div class="bottom">
			<h6>New on TripFab?<a href="#signUp" class="link1 lbc"> Sign Up Now</a></h6>
		</div><!--BOTTOM-->
	</div><!--SIGNIn-->
</div><!--HIDDEN-->