<div class="footer">
    <div class="wrapper">
        <p><img src="/images2/logo-2.png" alt="" /><strong>Tripfab</strong> is lovely designed in a <strong>tropical paradise</strong></p>
        <ul>
            <li><a href="mailto:hello@tripfab.com">Contact</a></li>
            <li><a href="http://blog.tripfab.com">Blog</a></li>
            <li><a href="http://twitter.com/tripfab">Twitter</a></li>
            <li><a href="http://facebook.com/tripfab">Facebook</a></li>
            <li><a href="/terms">Terms</a></li>
        </ul>
    </div><!-- closes wrapper -->
</div><!-- closes footer -->
<div id="citiesAutocompleteContainer"></div>