<div class="img_logo">
    <?php if(!empty($this->vendor->image)): ?>
    <?= $this->logo($this->vendor->image, '109:89') ?>
    <?php else: ?>
    <?= $this->logo('/images/default-profile.gif', '109:89') ?>
    <?php endif ?>
</div><!--LOGOS-->	
<div class="ttl">
    <h2 id="title"><?= $this->vendor->name ?></h2>
    <!--<span class="act"><em></em>Activity</span>-->
    <span class="htl"><em></em>Hotel</span>
    <span class="reviews"><em></em>0 Reviews</span>
</div><!--TTL-->
<p class="qz">
    <strong>Questions about this listing?</strong>
    Talk directly with <?= $this->vendor->name ?>
</p>
<?php if($this->user): ?>
<ul>
    <li><span>FREE</span><a href="#start_call" class="phone lbc">Phone Call</a></li>
    <li><a href="https://<?= $_SERVER['HTTP_HOST'] ?>/chat?provider=<?= $this->vendor->user_id ?>" class="chat livechat">Live Chat</a></li>
    <li><a href="#send_message" class="msj lbc phonecall">Message</a></li>
</ul>
<?php else: ?>
<ul>
    <li><span>FREE</span><a href="/login" class="phone">Phone Call</a></li>
    <li><a href="/login" class="chat">Live Chat</a></li>
    <li><a href="/login" class="msj">Message</a></li>
</ul>
<?php endif ?>
<div class="clear"></div>