<?php $path = @explode('/',$_SERVER[REQUEST_URI]) ?>
<?php if(isset($path[2]) and $path[2] == 'trips') $class1 ='active'; ?>
<?php if(isset($path[2]) and $path[2] == 'user' and isset($path[3]) and $path[3] == 'trips') $class2 ='active'; ?>
<?php if(count($path) == 2) $class3 ='active'; ?>
<?php if(isset($path[2]) and $path[2] == 'mytrips') $class2 = 'active'; ?>
<div class="big-message green">
    <div class="wrapper"><img src="https://static.tripfab.com/images2/cleardot.gif" alt=""> 
    <span>Your changes have been saved!</span></div><!-- closes wrapper -->
</div>
<?php if(!is_null($this->user) and ($this->user->active == 0)): ?>
<div class="checkEmail">
	<div class="wrapper">
		<h2><?= $this->user->name ?>, please go to <?= $this->user->email ?> to complete your sign-up process</h2>
		<a href="" class="btn-10 js-resend-verification">Resend E-mail</a>
	</div><!--WRAPPER-->
</div><!--CHECKEMAIL-->
<?php endif ?>
<div id="header">
    <div class="wrapper">
        <h1 class="logo"><a href="/">Tripfab</a></h1>
        <div class="top_search">
            <form method="post" action="/costa_rica">
                <fieldset>
                    <input id="citiesSearch" type="text" value="Search Places"/>
                    <a href="/costa_rica" class="srcBtn">Search</a>
                    <div id="note3" class="note"><em></em>
                       	<p class="flag">We have listings only in <strong>Costa Rica</strong>, other countries coming soon.</p>
                    	</div><!--NOTE1-->
                    <div id="note4" class="note"><em></em>
                    	<p><strong>0 Results. </strong>You know we work just in Costa Rica. Right?</p>
                    </div><!--NOTE2-->
                </fieldset>
            </form>
        </div><!--TOP_SEARCH-->
        <div class="rg">
            <?php if(!$this->user): ?>
            <a href="/mytrips" id="cart" class="js-cart js-signup"><span class="num">0</span></a>
            <div class="cart-B js-cart-B">
            	<a href="" class="icon js-signup"><span>0</span></a>
            	<div class="info">
            		<h3>$0</h3>
            		<span>0 listings in your trip</span>
            		<a href="/mytrips" class="organize js-signup"><span>Organize Trip</span></a>
            	</div><!--INFO-->
            </div><!--CART-B-->
            <div class="login js-header-login js-div-signin js-form-container">
                <span class="arrow"></span>
                <form method="post" action="https://<?= $_SERVER['HTTP_HOST'] ?>/en-US/login">
                    <div class="">
                    <input class="email js-input-email" type="text" name="email" placeholder="E-Mail" />
                    </div>
                    <div class="">
                    <input class="pass js-input-password" type="password" name="password" placeholder="Password" />
                    </div>
                    <div class="bttns">
                        <label for="remenber"><input class="js-input-remember" 
                        type="checkbox" id="remenber" name="remenber" value="1" />Remember me</label>
                        <input type="submit" class="btn-1 noclean" value="Sign In" />
                    </div><!--BTTNS-->
                    <div class="actions">
                        <a href="#" class="link1 js-forgot">Forgot Password?</a>
                        <a href="/signup" class="link1 create js-signup">Create a TripFab Account</a>
                        <div class="clear"></div>
                    </div><!--ACTIONS-->
                    <div class="fb">
                        <a href="/signup/facebook" class="js-fb-sigup">Sign In with Facebook</a>
                    </div><!--FB-->
                </form>
            </div><!--LOGIN-->
            <?php else: ?>
            <a href="/user/trips/itinerary/" id="cart" class="js-cart js-get-cart">
            <span class="num"><?= $this->userTrip->listings ?></span></a>
            <div class="js-cart-placeholder"></div>
            <div class="user-menu js-header-user-menu">
                <span class="arrow"></span>
				<?php switch($this->user->role_id): case 2: ?>
                <div class="main">
        			<?php $image = (!empty($this->user->image)) ? $this->user->image : '/images/default-profile.gif' ?>
        			<?= $this->thumbnail(72,$image,'','1:1'); ?>
                    <ul>
                        <li><a href="/user/trips">My Trips</a></li>
                        <li><a href="/user/messages">Messages</a></li>
                        <li><a href="/user/reservations">Reservations</a></li>
                    </ul>
                </div><!--MAIN-->
                <div class="bot">
                    <a href="/user/account" class="account">Account</a>
                    <a href="/logout" class="sign_out">Sign Out</a>
                </div><!--BOT-->
				<?php break; case 3: ?>
                <div class="main">
        			<?php $image = (!empty($this->user->image)) ? $this->user->image : '/images/default-profile.gif' ?>
        			<?= $this->thumbnail(72,$image,'','1:1'); ?>
                    <ul>
                        <li><a href="/provider/listings">Listings</a></li>
                        <li><a href="/provider/messages">Messages</a></li>
                        <li><a href="/provider/reservations">Reservations</a></li>
                        <li><a href="/provider/reviews">Reviews</a></li>	   
                        <li><a href="/provider/offers">Offers</a></li>
                    </ul>
                </div><!--MAIN-->
                <div class="bot">
                    <a href="/provider/account" class="account">Account</a>
                    <a href="/logout" class="sign_out">Sign Out</a>
                </div><!--BOT-->
				<?php break; case 4: ?>
                <div class="main">
        			<?php $image = (!empty($this->user->image)) ? $this->user->image : '/images/default-profile.gif' ?>
        			<?= $this->thumbnail(72,$image,'','1:1'); ?>
                    <ul>
                        <li><a href="/admin/listings">Listings</a></li>
                        <li><a href="/admin/trips">Trips</a></li>
                        <li><a href="/admin/places">Places</a></li>
                        <li><a href="/admin/users">Users</a></li>	   
                        <li><a href="/admin/payments">Payments</a></li>  
                        <li><a href="/admin/reservations">Reservations</a></li>
                    </ul>    
                </div><!--MAIN-->
                <div class="bot">
                    <a href="admin" class="account">Account</a>
                    <a href="/logout" class="sign_out">Sign Out</a>
                </div><!--BOT-->
				<?php break; endswitch ?>
            </div><!--USER-MENU-->
            <?php endif ?>
            <?php if(!$this->user): ?>
            <div class="sign_in"><a class="js-header-signin" href="/login">Sign In<span class="aw"></span></a></div>
            <?php else: ?>
            <div id="logged_in"><a class="js-header-account" href="/login">My Account<span class="aw"></span></a></div><!--LOGGED_IN-->
            <?php endif ?>
            <div class="overlay js-menu-overlay-login"></div>
            <div class="phone">
                <span>Customer Service</span> <strong>1-866-401-0382</strong>
            </div><!--PHONE-->
        </div><!--RG-->
    </div><!--WRAPPER-->
</div><!--HEADER-->


