<div class="js-header-container">
<?php $path = @explode('/',$_SERVER[REQUEST_URI]) ?>
<?php if(isset($path[2]) and $path[2] == 'trips') $class1 ='active'; ?>
<?php if(isset($path[2]) and $path[2] == 'user' and isset($path[3]) and $path[3] == 'trips') $class2 ='active'; ?>
<?php if(count($path) == 2) $class3 ='active'; ?>
<?php if(isset($path[2]) and $path[2] == 'mytrips') $class2 = 'active'; ?>
<div class="big-message green">
    <div class="wrapper"><img src="https://static.tripfab.com/images2/cleardot.gif" alt=""> 
    <span>Your changes have been saved!</span></div><!-- closes wrapper -->
</div>
<?php if(!is_null($this->user) and ($this->user->active == 0)): ?>
<div class="checkEmail">
	<div class="wrapper">
		<h2><?= $this->user->name ?>, please go to <?= $this->user->email ?> to complete your sign-up process</h2>
		<a href="" class="btn-10 js-resend-verification">Resend E-mail</a>
	</div><!--WRAPPER-->
</div><!--CHECKEMAIL-->
<?php endif ?>
<div id="header">
    <div class="wrapper">
        <h1 class="logo"><a href="/">Tripfab</a></h1>
        <ul>
            <li><a class="<?= $class3 ?>" href="/"><span>Home</span></a></li>
            <li><a class="<?= $class1 ?>" href="/trips/costa_rica"><span>Preplanned trips</span></a></li>
            <?php if(!$this->user): ?>
            <li><a class="<?= $class2 ?>" href="/mytrips"><span>Create Trip</span></a></li>
            <?php else: ?>
            <li><a class="<?= $class2 ?>" href="/user/trips"><span>My Trips</span></a></li>
            <?php endif ?>
        </ul>
        
        <div class="rg">
        	<div class="log">
        				
        		<?php if(!$this->user): ?>
        		<div class="btn"><a href="/signup" class="btn-1 js-signup">Sign Up</a></div>
        		<div class="sign_in">
        			Have an Account? <a href="" id="sign-in">Sign In<span class="aw"></span></a>
        		</div><!--SIGN_IN-->
        		
        		<div class="login js-div-signin js-form-container">
        			<span class="arrow"></span>
        			<form method="post" action="https://<?= $_SERVER['HTTP_HOST'] ?>/en-US/login">
                    	<div class="">
        				<input class="email js-input-email" type="text" name="email" value="eMail" />
                        </div>
                        <div class="">
        				<input class="pass js-input-password" type="password" name="password" value="******" />
                        </div>
        				<div class="bttns">
        					<label for="remenber"><input class="js-input-remember" 
                            type="checkbox" id="remenber" name="remenber" value="1" />Remember me</label>
        					<input type="submit" class="btn-1 noclean" value="Sign In" />
        				</div><!--BTTNS-->
        				<div class="actions">
        					<a href="#" class="link1 js-forgot">Forgot Password?</a>
        					<a href="#" class="link1 create js-sigup">Create a TripFab Account</a>
        					<div class="clear"></div>
        				</div><!--ACTIONS-->
        				<div class="fb">
        					<a href="/signup/facebook" class="js-fb-signup">Sign In with Facebook</a>
        				</div><!--FB-->
        			</form>
        		</div><!--LOGIN-->
        		
        		<?php else: ?>
        		<?php if($this->user->role_id == 2): ?>
        		<div class="sign_in">
        			<?php $image = (!empty($this->user->image)) ? $this->user->image : '/images/default-profile.gif' ?>
        			<?= $this->thumbnail(25,$image,'','1:1'); ?>
        			<a href="/user/account" id="logged_in"><?= $this->user->name . " " . $this->user->lname ?><span class="aw"></span></a>
        		</div><!--SIGN_IN-->
        		<div class="user-menu">
        			<span class="arrow"></span>
        			<div class="main">
        				<?php $image = (!empty($this->user->image)) ? $this->user->image : '/images/default-profile.gif' ?>
        				<?= $this->thumbnail(68,$image,'','1:1'); ?>
        				<ul>
        					<li><a href="/user/trips">My Trips</a></li>
        					<li><a href="/user/messages">Messages</a></li>
        					<li><a href="/user/reservations">Reservations</a></li>
        				</ul>
        				<div class="clear"></div>
        			</div><!--MAIN-->
        			<div class="bot">
        				<a href="/user" class="account">Account</a>
        				<a href="/logout" class="sign_out">Sign Out</a>
        			</div><!--BOT-->
        		</div><!--USER-MENU-->
        		
        		<?php elseif($this->user->role_id == 3): ?>
        		
        		
        		<div class="sign_in">
        			<?php $image = (!empty($this->user->image)) ? $this->user->image : '/images/default-profile.gif' ?>
        			<?= $this->thumbnail(25,$image,'','1:1'); ?>
        			<a href="/provider/account" id="logged_in"><?= $this->user->name ?><span class="aw"></span></a>
        		</div><!--SIGN_IN-->
        		
        		<div class="user-menu">
        			<span class="arrow"></span>
        			<div class="main">
        				<?php $image = (!empty($this->user->image)) ? $this->user->image : '/images/default-profile.gif' ?>
        				<?= $this->thumbnail(68,$image,'','1:1'); ?>
        				<ul>
        					<li><a href="/provider/listings">Listings</a></li>
        					<li><a href="/provider/messages">Messages</a></li>
        					<li><a href="/provider/reservations">Reservations</a></li>
        					<li><a href="/provider/reviews">Reviews</a></li>	   
        					<li><a href="/provider/offers">Offers</a></li>
        				</ul>
        				<div class="clear"></div>
        			</div><!--MAIN-->
        			<div class="bot">
        				<a href="/user" class="account">Account</a>
        				<a href="/logout" class="sign_out">Sign Out</a>
        			</div><!--BOT-->
        		</div><!--USER-MENU-->
        	
        		<?php else: ?>
            	<div class="sign_in">
        			<?php $image = (!empty($this->user->image)) ? $this->user->image : '/images/default-profile.gif' ?>
        			<?= $this->thumbnail(25,$image,'','1:1'); ?>
        			<a href="/admin" id="logged_in"><?= $this->user->name ?><span class="aw"></span></a>
        		</div><!--SIGN_IN-->
        		<div class="user-menu">
        			<span class="arrow"></span>
        			<div class="main">
        				<?php $image = (!empty($this->user->image)) ? $this->user->image : '/images/default-profile.gif' ?>
        				<?= $this->thumbnail(68,$image,'','1:1'); ?>
        				<ul>
        					<li><a href="/admin/listings">Listings</a></li>
        					<li><a href="/admin/trips">Trips</a></li>
        					<li><a href="/admin/places">Places</a></li>
        					<li><a href="/admin/users">Users</a></li>	   
        					<li><a href="/admin/payments">Payments</a></li>  
        					<li><a href="/admin/reservations">Reservations</a></li>
        				</ul>
        				<div class="clear"></div>
        			</div><!--MAIN-->
        			<div class="bot">
        				<a href="/admin" class="account">Admin</a>
        				<a href="/logout" class="sign_out">Sign Out</a>
        			</div><!--BOT-->
        		</div><!--USER-MENU-->
        		<?php endif ?>
        	<?php endif ?>
        	</div><!--LOG-->
        	<div class="top_search">
        		<form method="post" action="">
        			<fieldset>
        				<input id="citiesSearch" type="text" value="Search Places"/>
        				<div id="note3" class="note"><em></em>
        					<p class="flag">We have listings only in <strong>Costa Rica</strong>, other countries coming soon.</p>
        				</div><!--NOTE1-->
        				<div id="note4" class="note"><em></em>
        					<p><strong>0 Results. </strong>You know we work just in Costa Rica. Right?</p>
        				</div><!--NOTE2-->
        			</fieldset>
        		</form>
        	</div><!--TOP_SEARCH-->
        </div><!--RG-->
        <div class="clear"></div>
    </div><!-- WRAPPER -->
    <div class="overlay"></div>	
</div><!-- closes header -->
</div>