<div class="ttl">Talk with the vendor</div>
<div class="widget-content">
    <?php if(!empty($this->user->image)): ?>
    <?= $this->thumbnail(67, $this->user->image, '', '1:1') ?>
    <?php else: ?>
    <a href="/provider/account"><img src="/images2/empty-profile-pic.png" /></a>
    <?php endif ?>
    <h2><?= $this->vendor->name ?></h2>
    <a href="" class="online"><img src="/images2/cleardot.gif" alt="" />Online</a>
</div><!-- closes widget-content -->
<?php if($this->user): ?>
<ul>
    <li class="item-1"><a class="lb" href="#send_message"><img src="/images2/cleardot.gif" alt="" /><br />Send Message</a></li>
    <li class="item-2"><a class="lb" href="#live_chat"><img src="/images2/cleardot.gif" alt="" /><br />Live Chat</a></li>
    <li class="item-3"><a class="lb" href="#start_call"><img src="/images2/cleardot.gif" alt="" /><br />Start Call</a></li>
</ul>
<?php else: ?>
<ul>
    <li class="item-1"><a href="/login"><img src="/images2/cleardot.gif" alt="" /><br />Send Message</a></li>
    <li class="item-2"><a href="/login"><img src="/images2/cleardot.gif" alt="" /><br />Live Chat</a></li>
    <li class="item-3"><a href="/login"><img src="/images2/cleardot.gif" alt="" /><br />Start Call</a></li>
</ul>
<?php endif ?>