<?php $items = array(
	array(
		'label' => 'Listings',
		'url'	=> '/provider/listings/',
		'submenu' => array(
			array(
				'label' => 'All Listings',
				'url'	=> '/provider/listings/#/all',
			),
			array(
				'label' => 'Active',
				'url'	=> '/provider/listings/#/active',
			),
			array(
				'label' => 'Inactive',
				'url'	=> '/provider/listings/#/inactive',
			),
		),
	),
	array(
		'label' => 'Messages',
		'url'	=> '/provider/messages/',
	),
	array(
		'label' => 'Reservations',
		'url'	=> '/provider/reservations/',
		'submenu' => array(
			array(
				'label' => 'Incoming',
				'url'	=> '/provider/reservations/',
			),
			array(
				'label' => 'Waiting Approval',
				'url'	=> '/provider/reservations/pending',
			),
			array(
				'label' => 'History',
				'url'	=> '/provider/reservations/history',
			),
		),
	),
	array(
		'label' => 'Reviews',
		'url'	=> '/provider/reviews/',
	),
	array(
		'label' => 'Offers',
		'url'	=> '/provider/offers/',
	),
	array(
		'label' => 'Account',
		'url'	=> '/provider/account/',
		'submenu' => array(
			array(
				'label' => 'Profile',
				'url'	=> '/provider/account/',
			),
			array(
				'label' => 'Password',
				'url'	=> '/provider/account/password',
			),
			array(
				'label'	=> 'Payments',
				'url'	=> '/provider/account/payments',
			),
			array(
				'label'	=> 'Notifications',
				'url'	=> '/provider/account/notifications',
			),		
		),
	),
) ?>
<div class="main-menu">
    <ul>
    	<?php foreach($items as $i => $item): ?>
        <?php $class = (isset($item['label']) && $item['label'] == $this->parentActive) ? 'active' : '' ; ?>
        <?php $class.= (isset($item['submenu']) && $item['submenu']) ? ' sub-menu' : ''; ?>
        <li class="<?= $class ?>">
            <a href="<?= $item['url'] ?>"><?= $item['label'] ?></a>
            <?php if(isset($item['submenu'])): ?>
            <ul>
            	<?php foreach($item['submenu'] as $subitem): ?>
                <?php $class = ($subitem['label'] == $this->active) ? 'active' : '' ; ?>
                <li class="<?= $class ?>"><a href="<?= $subitem['url'] ?>"><?= $subitem['label'] ?></a></li>
                <?php endforeach ?>
            </ul>
            <img src="/images2/g-27.png" alt="" class="g-right" />
            <?php if($i != 0): ?><img src="/images2/g-28.png" alt="" class="g-left" /><?php endif ?>
            <?php endif ?>
        </li>
        <?php endforeach ?>
        <li class="avaible-balance">
            <p>Available Balance: <span class="total">$0.00</span></p>
            <a href="/provider/withdraw" class="btn-1">Withdraw</a>
        </li>
    </ul>
    <div class="clear"></div>
</div><!-- closes menu -->
<?php if($this->notifications): ?>
<!--<div class="subttl">
    <h4><a href="/provider/account/notifications">Set up your notifications</a></h4>
</div>-->
<?php endif ?>