<?php 
switch($this->type){
	case 2:
		$items = array(
			array(
				'label'	=> 'General Information',
				'url'	=> '/provider/listings/edit/'.$this->id,
			),
			array(
				'label'	=> 'Overview',
				'url'	=> '/provider/listings/overview/'.$this->id,
			),
			array(
				'label'	=> 'Photos',
				'url'	=> '/provider/listings/photos/'.$this->id,
			),
			array(
				'label' => 'How To Get There',
				'url'	=> '/provider/listings/location/'.$this->id,
			),
			array(
				'label' => 'Specialities',
				'url'	=> '/provider/listings/specialities/'.$this->id,
			),
		);
		break;
	case 4:
		$items = array(
			array(
				'label'	=> 'General Information',
				'url'	=> '/provider/listings/edit/'.$this->id,
			),
			array(
				'label'	=> 'Overview',
				'url'	=> '/provider/listings/overview/'.$this->id,
			),
			array(
				'label'	=> 'Photos',
				'url'	=> '/provider/listings/photos/'.$this->id,
			),
			array(
				'label' => 'How To Get There',
				'url'	=> '/provider/listings/location/'.$this->id,
			),
		);
		break;
	case 5:
		$items = array(
			array(
				'label'	=> 'General Information',
				'url'	=> '/provider/listings/edit/'.$this->id,
			),
			array(
				'label'	=> 'Overview',
				'url'	=> '/provider/listings/overview/'.$this->id,
			),
			array(
				'label'	=> 'Photos',
				'url'	=> '/provider/listings/photos/'.$this->id,
			),
			array(
				'label' => 'How To Get There',
				'url'	=> '/provider/listings/location/'.$this->id,
			),
			array(
				'label' => 'General Amenities',
				'url'	=> '/provider/listings/details/'.$this->id,
			),
			array(
				'label' => 'Rooms',
				'url'	=> '/provider/listings/rooms/'.$this->id,
			),
			array(
				'label' => 'Calendar',
				'url'	=> '/provider/listings/calendar/'.$this->id,
			),
			array(
				'label'	=> 'Pricing',
				'url'	=> '/provider/listings/pricing/'.$this->id,
			),
		);
		break;
	case 6:
		$items = array(
			array(
				'label'	=> 'General Information',
				'url'	=> '/provider/listings/edit/'.$this->id,
			),
			array(
				'label'	=> 'Overview',
				'url'	=> '/provider/listings/overview/'.$this->id,
			),
			array(
				'label'	=> 'Photos',
				'url'	=> '/provider/listings/photos/'.$this->id,
			),
			array(
				'label' => 'How To Get There',
				'url'	=> '/provider/listings/location/'.$this->id,
			),
			array(
				'label' => 'Details',
				'url'	=> '/provider/listings/details/'.$this->id,
			),
			array(
				'label' => 'Tips',
				'url'	=> '/provider/listings/tips/'.$this->id,
			),
			array(
				'label' => 'Activity Types',
				'url'	=> '/provider/listings/types/'.$this->id,
			),
			array(
				'label' => 'Calendar',
				'url'	=> '/provider/listings/calendar/'.$this->id,
			),
			array(
				'label'	=> 'Pricing',
				'url'	=> '/provider/listings/pricing/'.$this->id,
			),
		);
		break;
	case 7:
		$items = array(
			array(
				'label'	=> 'General Information',
				'url'	=> '/provider/listings/edit/'.$this->id,
			),
			array(
				'label'	=> 'Overview',
				'url'	=> '/provider/listings/overview/'.$this->id,
			),
			array(
				'label'	=> 'Photos',
				'url'	=> '/provider/listings/photos/'.$this->id,
			),
			array(
				'label' => 'How To Get There',
				'url'	=> '/provider/listings/location/'.$this->id,
			),
		);
		break;
}
?>
<ul>
	<?php foreach($items as $item): ?>
    <?php $class = ($item['label'] == $this->active) ? 'current' : ''; ?>
    <li class="<?= $class ?>"><a href="<?= $item['url'] ?>"><?= $item['label'] ?></a></li>
    <?php endforeach ?>
</ul>