<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Change Password | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('input').ToggleInputValue();
            $('form select').jqTransSelect();
            $('#header .header-login a.user').click(function(){
                $(this).next().toggleClass('show');
                return false;
            });
        });
    </script>
</head>
<body>
<div class="w1 profile">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-backend">
            <?= $this->partial('partials/usermainmenu.phtml', array('active'=>'Notifications','parentActive'=>'Account')); ?>
            <h2 class="title">Notifications</h2>
            <div class="vendor-profile">
            	<form action="" id="user_form_notifications" method="post">
                    <div class="profile-items">
                        <div class="item-wrppr">
                            <div class="item-ttl">Send me emails when:</div>
                            <div class="item">							
                                <span>We promise not to spam, and you can disable these at any time</span>
                            </div><!-- closes item -->
                            <?php foreach($this->notifications[1] as $ntf): ?>
                            <?php if(in_array($ntf->id, $this->usersettings)): ?>
                            <div class="item notification"><input checked="checked" name="ntf[<?= $ntf->id ?>]" value="<?= $ntf->id ?>" type="checkbox" />
                            <label><?= $ntf->label ?></label></div>
                            <?php else: ?>
                            <div class="item notification"><input name="ntf[<?= $ntf->id ?>]" value="<?= $ntf->id ?>" type="checkbox" />
                            <label><?= $ntf->label ?></label></div>
                            <?php endif ?>
                            <?php endforeach ?>
                            <div class="clear"></div>									
                        </div><!-- closes item-wrppr -->
                        <div class="item-wrppr">
                            <div class="item-ttl">Remind me when:</div>
                            <div class="item">							
                                <span>Enabling these emails ensures the best possible experience for both hosts and guests</span>
                            </div><!-- closes item -->
                            <?php foreach($this->notifications[3] as $ntf): ?>
                            <?php if(in_array($ntf->id, $this->usersettings)): ?>
                            <div class="item notification"><input checked="checked" name="ntf[<?= $ntf->id ?>]" value="<?= $ntf->id ?>" type="checkbox" />
                            <label><?= $ntf->label ?></label></div>
                            <?php else: ?>
                            <div class="item notification"><input name="ntf[<?= $ntf->id ?>]" value="<?= $ntf->id ?>" type="checkbox" />
                            <label><?= $ntf->label ?></label></div>
                            <?php endif ?>
                            <?php endforeach ?>	
                            <div class="clear"></div>									
                        </div><!-- closes item-wrppr -->
                    </div><!-- closes profile-items -->
                    <div class="foot">
                        <input type="submit" class="btn-1" value="Save Changes" />
                    </div><!-- closes foot -->
                    <input type="hidden" name="userids" value="<?= $this->user->id ?>" />
                    <input type="hidden" name="usertokens" value="<?= $this->user->token ?>" />
                    <input type="hidden" name="formid" value="<?= md5($this->user->token.'user_form_notifications') ?>" />
                    <input type="hidden" name="_task" value="<?= md5('update_user_notifications') ?>" />
                </form>
            </div><!-- closes  -->
        </div><!-- closes user-backend -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
</body>
</html>