<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> - Payment Methods | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css?v=<?= $this->cssVC ?>" />
	<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
</head>
<body>
<div class="w1 profile">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-backend">
        	<?= $this->partial('partials/usermainmenu.phtml', array('active'=>'Account','parentActive'=>'Payments')); ?>
            <h2 class="title">Edit Credit Card <a href="/user/account/payments" class="back">&larr; Back to Payments</a></h2>
            <div class="vendor-profile" id="u-payments">
                <form id="user_account" method="post" action="">
                    <div class="profile-items">
                        <div class="item-wrppr">
                            <div class="item-ttl"> 
                            	Credit Card Information <p>Please enter your credit or debit card information below.</p>
                            </div><!-- closes item ttl -->
                            <div class="item">
                                <ul class="cards"></ul>
                            </div><!-- closes item -->
                            <div class="item">
                                <input type="text" class="cnum" autocomplete="off" />
                                <h4>Credit Card Number</h4>
                                <span>No dashes or spaces</span> 
                            </div><!-- closes item -->
                            <div class="item">
                                <input type="text" name="cname" autocomplete="off" />
                                <h4>Cardholder Name</h4>
                                <span>As it appears on the credit card</span> 
                            </div><!-- closes item -->
                            <div class="item">
                                <select class="cmonth">
                                    <option value="">--</option>
                                    <option value="01">Jan (01)</option>
                                    <option value="02">Feb (02)</option>
                                    <option value="03">Mar (03)</option>
                                    <option value="04">Avr (04)</option>
                                    <option value="05">May (05)</option>
                                    <option value="06">Jun (06)</option>
                                    <option value="07">Jul (07)</option>
                                    <option value="08">Aug (08)</option>
                                    <option value="09">Sep (09)</option>
                                    <option value="10">Oct (10)</option>
                                    <option value="11">Nov (11)</option>
                                    <option value="12">Dec (12)</option>
                                </select>
                                <select class="cyear">
                                    <option value="">----</option>
                                    <option value="2011">2011</option>
                                    <option value="2012">2012</option>
                                    <option value="2013">2013</option>
                                    <option value="2014">2014</option>
                                    <option value="2015">2015</option>
                                    <option value="2016">2016</option>
                                    <option value="2017">2017</option>
                                    <option value="2018">2018</option>
                                    <option value="2019">2019</option>
                                    <option value="2020">2020</option>
                                    <option value="2021">2021</option>
                                </select>
                                <h4>Expiration Date</h4>
                                <span>Only month and year required</span> 
                            </div><!-- closes item -->
                            <div class="item security">
                                <input type="text" class="ccode" autocomplete="off" />
                                <h4>Security Code</h4>
                                <a href="#" class="helptip">What's this?</a>
                                <p class="tip hidden"><span></span>The 3 or 4 digit value printed on the card or signature strip</p>
                            </div><!-- closes item -->
                            <div class="clear"></div>
                        </div><!-- closes item-wrppr -->
                    </div><!-- closes profile-items -->
                    <div class="foot">
                        <input type="submit" class="btn-1" value="Save Credit Card" />
                        <a href="">Deactivate Account</a> 
                    </div><!-- closes foot -->
                    <input type="hidden" name="userids" value="<?= $this->user->id ?>" />
                    <input type="hidden" name="usertokens" value="<?= $this->user->token ?>" />
                    <input type="hidden" name="formid" value="<?= md5('update_card_form') ?>" />
                    <input type="hidden" name="_task" value="<?= md5('update_card') ?>" />
                    <input type="hidden" name="card" value="<?= $this->account->id ?>" />
                </form>
            </div><!-- closes vendor-profile --> 
        </div><!-- closes user-backend -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript">PUBLIC_KEY = "<?= $this->pkey ?>"; </script>
<script type="text/javascript" src="https://js.stripe.com/v1/"></script>
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript" src="/js2/cardcheck.min.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('a.lbc').fancybox({
        	padding: 0,
        	overlayColor: '#FFF',
        	overlayOpacity: '0.7',
			centerOnScroll:true
        });
		
		$('a.delete_btn').click(function(){
			$form = $(this).parents('form');
			$form.submit();
			return false;
		});
		
		$('#user_account').submit(function(){
			if($('.cnum', this).val() == '') {
				showError('Credit Card cannot be empty');
				return false;
			} else if($('.ccode', this).val() == '') {
				showError('Security Code cannot be empty');
				return false;
			} else if($('.cmonth', this).val() == '') {
				showError('Please select the expiration month');
				return false;
			} else if($('.cyear', this).val() == '') {
				showError('Please select the expiration year');
				return false;
			} else {
				Stripe.setPublishableKey(PUBLIC_KEY);
				$data = {
					number:    $('.cnum', this).val(),
					cvc: 	   $('.ccode', this).val(),
					exp_month: $('.cmonth', this).val(),
					exp_year:  $('.cyear', this).val()
				};
				$('input, select', this).attr('disabled', 'disabled');
				var amount = 200; //amount you want to charge in cents
				Stripe.createToken($data, amount, stripeResponseHandler);
				// prevent the form from submitting with the default action
				return false;
			}
		});
		
		var creditCard = $('#user_account .cnum');
		creditCard.cardcheck({
			iconLocation: 'ul.cards',
			iconDir:'/images/'
		});
    });
	
	function stripeResponseHandler(status, response) {
		var $form = $("#user_account");
		if (response.error) {
			//show the errors on the form
			$('input, select', $form).removeAttr('disabled');
			showError(response.error.message);
		} else {
			// token contains id, last4, and card type
			var token = response['id'];
			
			$('input, select', $form).removeAttr('disabled');
			// insert the token into the form so it gets submitted to the server
			$form.append("<input type='hidden' name='stripeToken' value='" + token + "'/>");
			// and submit
			$form.get(0).submit();
		}
	}
</script>
</body>
</html>