<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> - Payment Methods | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css?v=<?= $this->cssVC ?>" />
	<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
</head>
<body>
<div class="w1 profile">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-backend">
        	<?= $this->partial('partials/usermainmenu.phtml', array('active'=>'Account','parentActive'=>'Payments')); ?>
            <h2 class="title">Payments <a href="/user/account/payments/new" class="add">Add a New Account</a></h2><!-- closes subttl -->
            <?php if(count($this->accounts) > 0): ?>
            <div id="u-payments">
	            <?php foreach($this->accounts as $a): ?>
                <div class="each">
                    <span class="type"><img src="<?= $this->cards[$a->type] ?>" alt="" /> <?= $a->type ?></span>
                    <span class="number">Card Number <strong>************<?= $a->last4 ?></strong></span>
                    <span class="expiration">Added <strong><?= date('F jS, Y', strtotime($a->created)) ?></strong></span>
                    <a class="delete lbc" href="#delete_card_<?= $a->id ?>">Delete Card</a>
                    <a class="edit" href="/user/account/payments/<?= $a->id ?>">Edit</a>						
                </div><!--EACH-->
                <?php endforeach ?>
            </div><!-- closes u-payments --> 
            <?php else: ?>
            <div id="u-payments">
                <div class="no-payment">
                    <h3>You don't have any credit card yet</h3>
                    <a href="/user/account/payments/new">Add a credit card now</a>
                </div><!--NO-PAYMENT-->
            </div><!-- closes u-payments -->
            <?php endif ?>
        </div><!-- closes user-backend -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div class="hidden">
	<?php foreach($this->accounts as $a): ?>
    <div id="delete_card_<?= $a->id ?>" class="lb delete_card_lb">
    	<form action="" method="post">
            <div class="mid">
                <h3>Are you sure you want to remove this card from your account?</h3>
                <p>You will loose all the information for this credit card</p>
            </div>
            <div class="bottom">
                <a href="#" class="btn-1 delete_btn">Delete</a>
                <a href="#" onclick="$.fancybox.close(); return false;" class="btn-10">Cancel</a>
            </div><!--BOTTOM-->
            <input type="hidden" name="card" value="<?= $a->id ?>" />
            <input type="hidden" name="user" value="<?= $this->user->id ?>" />
            <input type="hidden" name="usertoken" value="<?= $this->user->token ?>" />
            <input type="hidden" name="_task" value="<?= md5('delete_card') ?>" />
        </form>
    </div><!--DELETE_CARD-->
    <?php endforeach ?>
</div><!--HIDDEN-->
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('a.lbc').fancybox({
        	padding: 0,
        	overlayColor: '#FFF',
        	overlayOpacity: '0.7',
			centerOnScroll:true
        });
		
		$('a.delete_btn').click(function(){
			$form = $(this).parents('form');
			$form.submit();
			return false;
		});
    });
</script>
</body>
</html>