<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Reservations Waiting Approval | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('textarea').elastic();				
            $('input').ToggleInputValue();
            $('form select').jqTransSelect();
			
			$('.reservation .top h2').click(function(){
				$parent = $(this).parents('.reservation');
				$('.bottom', $parent).slideToggle();
			});
        });
    </script>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages">
        	<?= $this->partial('partials/usermainmenu.phtml', array('active'=>'Reservations','parentActive'=>'Waiting Approval')); ?>
        	<div class="subttl">
        		<h4>You have <?= count($this->reservations) ?> reservations pending approval</h4>
        	</div>
        	<!-- closes subttl -->
            <?php if(count($this->reservations) > 0): ?>
            <div class="reservations">
            	<?php foreach($this->reservations as $reserve): ?>
                <div class="reservation">							
                    <div class="top">
                        <?= $this->thumbnail(70, $reserve->listing_image, '', '1:1') ?>
                        <div class="meta">
                            <h2><?= $reserve->listing_name ?></h2>
                            <span><?= $reserve->listing_type ?></span>
                        </div><!-- closes meta -->								
                        <a href="">Send Message to Vendor</a>
                        <a href="" class="cncl">Cancel Reservation</a>
                    </div><!-- closes top -->
                    <div class="bottom">
                        <div class="ttl">
                            <strong>Reserve Code: <?= $reserve->code ?></strong>
                            Reservation Details
                        </div><!-- closes  -->
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td>Booking Date</td>
                                    <td><strong><?= date('F jS, Y', strtotime($reserve->created)) ?></strong></td>
                                </tr>
                                <tr>
                                    <td>Provider</td>
                                    <td><strong><?= $reserve->vendor_name ?></strong></td>
                                </tr>										
                            </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td>Checkin</td>
                                    <td><strong><?= date('F jS, Y', strtotime($reserve->checkin)) ?></strong></td>
                                </tr>
                                <?php if(!is_null($reserve->checkout)): ?>
                                <tr>
                                    <td>Checkput</td>
                                    <td><strong><?= date('F jS, Y', strtotime($reserve->checkout)) ?></strong></td>
                                </tr>
                                <?php endif ?>
                                <tr>
                                    <td>Occupation</td>
                                    <td><strong><?= $reserve->adults ?> adults
                                    <?php if($reserve->kids > 0): ?>
                                    and <?= $reserve->kids ?> kids 
                                    <?php endif ?>
                                    </strong></td>
                                </tr>
                            </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td>Payment Method</td>
                                    <td><strong><?= $reserve->method ?></strong></td>
                                </tr>
                                <tr>
                                    <td>Total Paid</td>
                                    <td><strong>$<?= $reserve->ammount ?></strong></td>
                                </tr>
                            </tbody>
                        </table>
                    </div><!-- closes bottom -->
                </div><!-- closes reservation -->
                <?php endforeach ?>
            </div><!-- closes reservations -->
            <?php else: ?>
            <div class="empty-container">
                <img src="/images/empty-9.png" alt="" /><br />
                You don't have waiting approval reservations
            </div><!-- closes empty -->
            <?php endif ?>
        </div><!-- closes user-messages -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
</body>
</html>