<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> - Reservations Waiting Approval | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages">
        	<?= $this->partial('partials/usermainmenu.phtml', array('active'=>'Reservations','parentActive'=>'Waiting Approval')); ?>
            <?php if(count($this->reservations) > 0): ?>
        	<div class="subttl">
        		<h4>You have <?= count($this->reservations) ?> reservations pending approval</h4>
        	</div><!-- closes subttl -->
            <div class="reservations">
            	<?php foreach($this->reservations as $reserve): ?>
                <div class="reservation">							
                    <div class="top">
                        <?= $this->thumbnail(70, $reserve->listing_image, '', '1:1') ?>
                        <div class="meta">
                            <h2><?= $reserve->listing_name ?></h2>
                            <span><?= $reserve->listing_type ?></span>
                        </div><!-- closes meta -->
                        <a href="" class="btn-10 edit"><span>Edit</span></a>
                        <div class="control"> <span class="arrow"></span>
                            <ul>
                            	<?php $link = '/'.$reserve->listing_country.'/'.$reserve->listing_city.'/'.$reserve->listing_idf; ?>
                                <li><a href="<?= $link ?>">View Actitvity</a></li>
                                <li><a href="#send_message_<?= $reserve->vendor_id ?>" class="sendMessage">Contatct Partner</a></li>
                                <li><a href="/user/reservations/view/<?= $reserve->id ?>">Reservation Details</a></li>
                            </ul>
                        </div><!--CONTROL-CONT-->
                        <a href="" class="btn-10">Cancel Reservation</a>
                        <input type="hidden" value="<?= $reserve->id ?>" name="reservation" class="reservation" />
                    </div><!-- closes top -->
                    <div class="clear"></div>
                    <div class="bottom">
                        <div class="ttl">
                            <strong>Reserve Code: <?= $reserve->code ?></strong>
                            Reservation Details
                        </div><!-- closes  -->
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td>Booking Date</td>
                                    <td><strong><?= date('F jS, Y', strtotime($reserve->created)) ?></strong></td>
                                </tr>
                                <tr>
                                    <td>Provider</td>
                                    <td><strong><?= $reserve->vendor_name ?></strong></td>
                                </tr>										
                            </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td>Checkin</td>
                                    <td><strong><?= date('F jS, Y', strtotime($reserve->checkin)) ?></strong></td>
                                </tr>
                                <?php if(!is_null($reserve->checkout)): ?>
                                <tr>
                                    <td>Checkput</td>
                                    <td><strong><?= date('F jS, Y', strtotime($reserve->checkout)) ?></strong></td>
                                </tr>
                                <?php endif ?>
                                <tr>
                                    <td>Occupation</td>
                                    <td><strong><?= $reserve->adults ?> adults
                                    <?php if($reserve->kids > 0): ?>
                                    and <?= $reserve->kids ?> kids 
                                    <?php endif ?>
                                    </strong></td>
                                </tr>
                            </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td>Payment Method</td>
                                    <td><strong><?= $reserve->method ?></strong></td>
                                </tr>
                                <tr>
                                    <td>Total Paid</td>
                                    <td><strong>$<?= $reserve->ammount ?></strong></td>
                                </tr>
                            </tbody>
                        </table>
                    </div><!-- closes bottom -->
                    <div class="clear"></div>
                </div><!-- closes reservation -->
                <?php endforeach ?>
            </div><!-- closes reservations -->
            <?php else: ?>
            <div id="reservations">
                <div class="no-reserv">
                    <h3>You don't have reservations wairing approval</h3>
                </div><!--NO-PAYMENT-->
            </div><!-- closes u-payments --> 
            <?php endif ?>
        </div><!-- closes user-messages -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<?php if(count($this->reservations) > 0): ?>
<?php $users = array(); ?>
<div class="hidden">
	<?php foreach($this->reservations as $reserve): ?>
    <?php if(!in_array($reserve->vendor_id, $users)): $users[] = $reserve->vendor_id ?>
	<div id="send_message_<?= $reserve->vendor_id ?>">
        <form action="" class="sendMessageForm">
            <div class="lb-forgot">
                <div class="ttl">Send a message to <?= $reserve->vendor_name ?></div>
                <div class="content">
                    <textarea cols="30" name="message" rows="1"></textarea>
                </div><!-- closes content -->
                <div class="bottom">
                    <input type="submit" class="btn-1" value="Send Message" />
                    <span onclick="$.fancybox.close()" class="btn-4">Cancel</span>				
                </div><!-- closes bottom -->
            </div><!-- closes lb-forgot -->
            <input type="hidden" name="user" value="<?= $reserve->vendor_id ?>" />
        </form>
    </div>
    <?php endif ?>
    <?php endforeach ?>
</div>
<?php endif ?>
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
    $(document).ready(function() {
		$('.reservation .top h2').click(function(){
			$parent = $(this).parents('.reservation');
			$('.bottom', $parent).slideToggle();
		});
		$('.reservation .top a.btn-10:not(.edit)').click(function(){
			$parent  = $(this).parents('.reservation');
			$reserve = $(this).siblings('input.reservation').val();
			$.ajax({
				url:'/ajax/cancelreservation',	
				type:'post',
				data:{id:$reserve},
				success:function(){
					$parent.fadeOut('slow');
					showAlert('The Reservation has been cancelled');
				},
				error:function(){
					showError('Something went wrong, Please try again later');
				}
			});
			return false;
		});		
		$( ".reservation .top a.edit" ).click(function() {
			$(this).siblings("div.control").toggleClass('show');
			return false;
		});
		$('.reservation .top a.sendMessage').fancybox({
			padding:0,
			showCloseButton:0,
			overlayColor:'#fff',
			modal:1
		});
		$('.sendMessageForm').submit(function(){
			$form = $(this);
			$data = {
				message:$('textarea[name=message]', $form).val(),
				vendor:$('input[name=user]', $form).val()
			};
			if($data.message == ''){
				showError('Enter a message');
				return false;
			}
			
			$.ajax({
				url:'/ajax/sendmsgvendor',
				data:$data,
				type:'post',
				success:function(response){
					$.fancybox.close();
					if(response.type == 'success'){
						showAlert(response.message);
						$('textarea[name=message]', $form).val('');
					} else {
						showError(response.message);
						$('textarea[name=message]', $form).val('');
					}
				},
				error:function(){
					$.fancybox.close();
					showError('Something went wrong, Please try again later');
					$('textarea[name=message]', $form).val('');
				}
			});
			return false;
		});
    });
</script>
</body>
</html>