<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Reservations Waiting Approval | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages">
        	<?= $this->partial('partials/usermainmenu.phtml', array('active'=>'Reservations','parentActive'=>'Waiting Approval')); ?>
            <?php if(count($this->reservations) > 0): ?>
        	<div class="subttl">
        		<h4>You have <?= count($this->reservations) ?> reservations pending approval</h4>
        	</div><!-- closes subttl -->
            <div class="reservations">
            	<?php foreach($this->reservations as $reserve): ?>
                <div class="reservation">							
                    <div class="top">
                        <?= $this->thumbnail(70, $reserve->listing_image, '', '1:1') ?>
                        <div class="meta">
                            <h2><?= $reserve->listing_name ?></h2>
                            <span><?= $reserve->listing_type ?></span>
                        </div><!-- closes meta -->
                        <a href="" class="btn-10 edit"><span>Edit</span></a>
                        <div class="control"> <span class="arrow"></span>
                            <ul>
                            	<?php $link = '/'.$reserve->listing_country.'/'.$reserve->listing_city.'/'.$reserve->listing_idf; ?>
                                <li><a href="<?= $link ?>">View Actitvity</a></li>
                                <li><a href="">Contatct Partner</a></li>
                                <li><a href="/user/reservations/view/<?= $reserve->id ?>">Reservation Details</a></li>
                            </ul>
                        </div><!--CONTROL-CONT-->
                        <a href="" class="btn-10">Cancel Reservation</a>
                    </div><!-- closes top -->
                    <div class="clear"></div>
                    <div class="bottom">
                        <div class="ttl">
                            <strong>Reserve Code: <?= $reserve->code ?></strong>
                            Reservation Details
                        </div><!-- closes  -->
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td>Booking Date</td>
                                    <td><strong><?= date('F jS, Y', strtotime($reserve->created)) ?></strong></td>
                                </tr>
                                <tr>
                                    <td>Provider</td>
                                    <td><strong><?= $reserve->vendor_name ?></strong></td>
                                </tr>										
                            </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td>Checkin</td>
                                    <td><strong><?= date('F jS, Y', strtotime($reserve->checkin)) ?></strong></td>
                                </tr>
                                <?php if(!is_null($reserve->checkout)): ?>
                                <tr>
                                    <td>Checkput</td>
                                    <td><strong><?= date('F jS, Y', strtotime($reserve->checkout)) ?></strong></td>
                                </tr>
                                <?php endif ?>
                                <tr>
                                    <td>Occupation</td>
                                    <td><strong><?= $reserve->adults ?> adults
                                    <?php if($reserve->kids > 0): ?>
                                    and <?= $reserve->kids ?> kids 
                                    <?php endif ?>
                                    </strong></td>
                                </tr>
                            </tbody>
                        </table>
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td>Payment Method</td>
                                    <td><strong><?= $reserve->method ?></strong></td>
                                </tr>
                                <tr>
                                    <td>Total Paid</td>
                                    <td><strong>$<?= $reserve->ammount ?></strong></td>
                                </tr>
                            </tbody>
                        </table>
                    </div><!-- closes bottom -->
                    <div class="clear"></div>
                </div><!-- closes reservation -->
                <?php endforeach ?>
            </div><!-- closes reservations -->
            <?php else: ?>
            <div id="reservations">
                <div class="no-reserv">
                    <h3>You don't have reservations wairing approval</h3>
                </div><!--NO-PAYMENT-->
            </div><!-- closes u-payments --> 
            <?php endif ?>
        </div><!-- closes user-messages -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
		$('.reservation .top h2').click(function(){
			$parent = $(this).parents('.reservation');
			$('.bottom', $parent).slideToggle();
		});
		
		$( ".reservation .top a.edit" ).click(function() {
			$(this).siblings("div.control").toggleClass('show');
			return false;
		});
    });
</script>
</body>
</html>