<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Reservations History | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="reserv_history">
        	<?= $this->partial('partials/usermainmenu.phtml', array('active'=>'Reservations','parentActive'=>'History')); ?>
            <?php if(count($this->reservations) > 0): ?>
        	<div class="subttl">
        		<h4>You have <?= count($this->reservations) ?> hostoric reservations</h4>
        	</div><!-- closes subttl -->
            <div class="list_content">
                <table width="100%" border="0">
                    <tr>
                        <th width="145"><a href="">Reservation Code</a></th>
                        <th width="170"><a href="">Activity</a></th>
                        <th width="80"><a href="">Kind</a></th>
                        <th width="130"><a href="">Partner</a></th>
                        <th width="130"><a href="">Reservation Date</a></th>
                        <th width="145"><a href="">Method</a></th>
                        <th width="80"><a href="">Amount</a></th>
                        <th width="65" class="last">&nbsp;</th>
                    </tr>
					<?php foreach($this->reservations as $i => $reserve): ?>
                    <?php $class = ($i == 0) ? 'first' : '' ?>
                    <tr class="<?= $class ?>">
                        <td><?= $reserve->code ?></td>
                        <td><?= $reserve->listing_name ?></td>
                        <td><?= $reserve->listing_type ?></td>
                        <td><?= $reserve->vendor_name ?></td>
                        <td><?= date('d/m/Y', strtotime($reserve->created)) ?></td>
                        <td><?= $reserve->method ?></td>
                        <td>$<?= $reserve->ammount ?></td>
                        <td><a href="/user/reservations/view/<?= $reserve->id ?>">Details</a></td>
                    </tr>
                    <?php endforeach ?>
                </table>
            </div>
            <?php else: ?>
            <div id="reservations">
                <div class="no-reserv">
                    <h3>You don't have reservations history</h3>
                </div><!--NO-PAYMENT-->
            </div><!-- closes u-payments --> 
            <?php endif ?>
        </div><!-- closes user-messages -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('textarea').elastic();				
        $('input').ToggleInputValue();
        $('form select').jqTransSelect();
    });
</script>
</body>
</html>