<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Trips | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css2/lightboxes.css" />
    <link type="text/css" rel="stylesheet" href="/css2/calendar/jquery-ui-1.8.16.custom.css" />
	<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('textarea').elastic();				
            $('input').ToggleInputValue();
            $('form select').jqTransSelect();
			$('a.lb').fancybox({
				padding:0,
				overlayColor:'#fff',
				centerOnScroll:1,
				showCloseButton:0,
			});
			
			$('a.delete_btn').click(function(){
				$form = $(this).parents('form');
				$form.submit();
				return false;
			});
			$('.lbox .btn-2, .lbox .btn-11').click(function(){
				$(this).parents('form').submit();
			});
			
			$('input.calendar1').datepicker({
				minDate:new Date(),
				onSelect:function(date){
					$end = $(this).parents('.content').find('input.calendar2');
					$end.datepicker('option','minDate', date);
				},
				dateFormat:'D M d yy',
			});
			
			$('input.calendar2').datepicker({
				minDate:new Date(),
				dateFormat:'D M d yy',
			});
			
			<?php if($this->alert): ?>
			showAlert("<?= $this->alert ?>");
			<?php endif ?>
			
			<?php if($this->error): ?>
			showError("<?= $this->error ?>");
			<?php endif ?>
        });
    </script>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages">
            <?php if(count($this->trips) > 0): ?>
            <div class="subttl">
            	<a href="/user/trips/create" class="btn-1">Plan a New Trip</a>
            	<h4>You are planning <?= count($this->trips) ?> trips</h4>
            </div>
            <div class="past-trips">
                <div class="left">
                    <?php foreach($this->trips as $trip): ?>
                    <div class="past-trip">
                        <div class="top">
                            <?= $this->thumbnail(102, $trip->image, '','1:1'); ?>
                            <div class="right">
                                <h2><?= $trip->title ?></h2>
                                <?php if($trip->start != '0000-00-00' && $trip->end != '0000-00-00'): ?>
                                <span>Travel Planning: 
								<?= date('F j, Y', strtotime($trip->start)) ?> - 
                                <?= date('F j, Y', strtotime($trip->end)) ?></span>
                                <?php else: ?>
                                <span>Travel Planning: Undefined</span>
                                <?php endif ?>
                                <ol>
                                    <li><img src="/images2/ico-70.png" alt="" /><?= $this->listingCounter[$trip->id][6] ?>
                                    <span>Activities</span></li>
                                    <li><img src="/images2/ico-71.png" alt="" /><?= $this->listingCounter[$trip->id][5] ?>
                                    <span>Hotels</span></li>
                                    <li><img src="/images2/ico-72.png" alt="" /><?= $this->listingCounter[$trip->id][2] ?>
                                    <span>Restaurants</span></li>
                                    <li><img src="/images2/ico-73.png" alt="" /><?= $this->listingCounter[$trip->id][7] ?>
                                    <span>Entertainments</span></li>
                                    <li><img src="/images2/ico-74.png" alt="" /><?= $this->listingCounter[$trip->id][4] ?>
                                    <span>Tourist Sights</span></li>
                                </ol>
                            </div><!-- closes right -->
                        </div><!-- closes top -->
                        <div class="meta">
                            <span>Trips Estimate</span>
                            <strong>$<?= $trip->price ?></strong>
                            <?php if($trip->start != '0000-00-00' && $trip->end != '0000-00-00'): ?>
                            <a href="/user/trips/itinerary/<?= $trip->id ?>" class="btn-1">Manage Trip</a>
                            <?php else: ?>
                            <a href="#set_dates_<?= $trip->id ?>" class="lb btn-1">Manage Trip</a>
                            <?php endif ?>
                            <a href="#delete_trip_<?= $trip->id ?>" class="lb delete">Delete Trip</a>	
                            <div class="clear"></div>
                        </div><!-- closes meta -->
                        <div class="time">
                            <span><?= $trip->days ?> DAYS TRIP</span>								
                        </div><!-- closes time -->
                    </div><!-- closes past-trip -->
                    <?php endforeach ?>
                </div><!-- closes left -->
                <div class="right">
                    <?= $this->partial('partials/usertriprightmenu.phtml', array('future'=>$this->trips, 'past'=>$this->pastTrips)); ?>
                </div><!-- closes right -->
            </div><!-- closes past-trips -->
            <?php else: ?>
            <div class="empty-container">
                <img src="/images/empty-4.png" alt="" /><br />
                You don't have future trips :( <br /><br />
                <a href="" class="btn-1">Create a New Trip Now</a>
            </div><!-- closes empty -->
            <?php endif ?>
        </div><!-- closes user-messages -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div class="hidden">
	<?php foreach($this->trips as $trip): ?>
    <div id="delete_trip_<?= $trip->id ?>" class="lb delete_card_lb">
    	<form action="" method="post" id="form_delete_trip_<?= $trip->id ?>">
            <div class="mid">
                <h3>Are you sure you want to delete this trip?<br />
                You will loose all the information</h3>
            </div>
            <div class="bottom">
                <a href="#" class="btn-1 delete_btn">Delete</a>
                <a href="#" onclick="$.fancybox.close(); return false;" class="btn-10">Cancel</a>
            </div><!--BOTTOM-->
            <input type="hidden" name="ids" value="<?= $trip->id ?>" />
            <input type="hidden" name="token" value="<?= $trip->token ?>" />
            <input type="hidden" name="_task" value="<?= md5('delete_trip') ?>" />
        </form>
    </div>
    <?php endforeach ?>
    <?php foreach($this->trips as $trip): ?>
    <?php if($trip->start == '0000-00-00' or $trip->end == '0000-00-00'): ?>
    <div id="set_dates_<?= $trip->id ?>">
    	<form method="post" action="">
            <div class="lb-forgot trip-dates">
                <div class="ttl">
                    Ready to travel?
                    <span>We need some information about your trip to make it fabuluos!</span>
                </div><!-- closes ttl -->
                <div class="content">
                    <div class="left">
                        <span>Set the starting date</span>
                        <input name="start" class="calendar1" type="text" />
                    </div><!-- closes left -->
                    <div class="right">
                        <span>Set the ending date</span>
                        <input type="text" name="end" class="calendar2" />
                    </div><!-- closes right -->				
                    <input type="checkbox" />
                    <label>Receive special offers from vendors near the places I'll visit</label>
                </div><!-- closes content -->
                <div class="bottom">
                    <input type="submit" class="btn-1" value="Manage Itinerary" />
                    <span class="btn-4" onclick="$.fancybox.close()">Cancel</span>
                </div><!-- closes bottom -->
            </div><!-- closes lb-forgot -->
            <input type="hidden" name="ids" value="<?= $trip->id ?>" />
            <input type="hidden" name="token" value="<?= $trip->token ?>" />
            <input type="hidden" name="_task" value="<?= md5('assign_dates') ?>" />
        </form>
    </div>
    <?php endif ?>
    <?php endforeach ?>
</div>
</body>
</html>