<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
	<meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>index search results</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css2/calendar/jquery-ui-1.8.16.custom.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>    
    <div class="w2">
        <div class="wrapper plan-trip">
            <div class="box">
                <div class="ttl">
                    <h2>Going on a trip? Have businesses compete for you.</h2>
                    <p>Tell us where you're next trip is, and have businesses compete and offer you these best deals ever.</p>
                </div><!-- closes ttl -->
                <form action="" method="post">
                    <fieldset>
                        <input type="text" name="title" class="large" value="A name for your trip" />
                        <input type="text" name="start" class="calendar1" value="Starting Date" />
                        <input type="text" name="end" class="calendar2" value="Ending Date" />
                        <input type="submit" class="btn-1" value="Get Started" />
                    </fieldset>
                </form>
                <div class="bottom">
                    <h3>How can you plan your next trip with us? It's easy.</h3>
                    <ul>
                        <li>
                            <span>1.</span>
                            <div>
                                <h4>Choose your Dreamed Destination</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur amet tincidunt vitae adipiscing elit.</p>
                            </div>
                        </li>
                        <li>
                            <span>2.</span>
                            <div>
                                <h4>Organize your trip easily day-by-day</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur amet tincidunt vitae adipiscing elit.</p>
                            </div>
                        </li>
                        <li>
                            <span>3.</span>
                            <div>
                                <h4>Receive Special Deals from our vendors</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur amet tincidunt vitae adipiscing elit.</p>
                            </div>
                        </li>
                        <li class="last">
                            <span>4.</span>
                            <div>
                                <h4>Book and enjoy your next fabulous trip</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur amet tincidunt vitae adipiscing elit.</p>
                            </div>
                        </li>
                    </ul>
                </div><!-- closes bottom -->
            </div><!-- closes box -->
            <div class="home-cities">
                <div class="ttl">
                    <form action="">
                        <fieldset>
                            <label>Country</label>
                            <select name="countries">
                            <?php foreach($this->countries as $c): ?>
                                <?php if($c->id == $this->country->id): ?>
                                <option selected="selected" value="<?= $c->id ?>"><?= $c->title ?></option>
                                <?php else: ?>
                                <option value="<?= $c->id ?>"><?= $c->title ?></option>
                                <?php endif ?>
                            <?php endforeach ?>
                            </select>
                        </fieldset>
                    </form>
                    See what's new in the most popular cities in the world!
                    <div class="clear"></div>
                </div><!-- closes ttl -->
                <div class="cities">
                    <?= $this->partial('partials/indexcities.phtml', array('cities'=>$this->cities, 'country'=>$this->country)) ?>
                </div><!-- closes cities -->
            </div><!-- closes home-cities -->
        </div><!-- closes wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/index/index.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('input').ToggleInputValue();
					
		$('input.calendar1').datepicker({
			minDate:new Date(),
			onSelect:function(date){
				$end = $('input.calendar2');
				$end.datepicker('option','minDate', date);
			},
			dateFormat:'D M d yy'
		});
		
		$('input.calendar2').datepicker({
			minDate:new Date(),
			dateFormat:'D M d yy'
		});
		
		<?php if($this->error): ?>
		showError("<?= $this->error ?>");
		<?php endif ?>
    });
</script>
</body>
</html>