<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> - Trips | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css2/lightboxes.css" />
    <link type="text/css" rel="stylesheet" href="/css6/calendar.css" />
	<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w3_admin">
        <div class="sub_menu">
            <h2><span>You are planning <?= count($this->trips) ?> Trips</span></h2>
            <ul class="sub_links">
                <li class="select"><a href="/user/trips">Future Trips</a></li>
                <li><a href="/user/trips/past">Past Trips</a></li>
            </ul>
        </div><!--SUB_MENU-->
    </div><!--W3-->
    
    <?php if(count($this->trips) > 0): ?>
    <div id="all_trips">
    	<?php foreach($this->trips as $trip): ?>
    	
    	<div class="notification end-1">
			<span class="end"></span>
			<div class="text">
				<h2>Karina, You have a missed trip</h2>
				<p>'Weekend with my family in Costa Rica' was never reserved according to date's you established previously, however, you can always change the dates</p>
			</div><!--TEXT-->
			<a href="" class="btn-10">Okay!</a>
		</div><!--NOTIFICATION-->
		
		<div class="notification soon-1">
			<span class="soon"></span>
			<div class="text">
				<h2>Karina, one of your trip is around the corner</h2>
				<p>'Weekend with my Family in Costa Rica' starts in <strong>5 days</strong>, we suggest you rush to book to guarantee availability</p>
			</div><!--TEXT-->
			<a href="" class="btn-10">Okay!</a>
		</div><!--NOTIFICATION-->
		
        <div class="single">
            <div class="image">
                <div class="slideshow">
                	<?= $this->thumbnail(134, $trip->image, '','1:1'); ?>
                </div><!--SLIDESHOW-->
            </div><!--image-->
            <div class="info">
                <div class="title">
                    <h3><a href=""><span class="icon"></span><?= $trip->title ?></a></h3>
                    <span class="days_left"> <?= $trip->days ?> Days Trip</span>
                </div><!--TITLE-->
                <div class="description">
                    <div class="data">
                        <dl>
                            <dt>Travel Starts</dt>
                            <?php if(!is_null($trip->start) && $trip->start != '0000-00-00'): ?>
                            <dd><?= date('M j, Y', strtotime($trip->start)) ?></dd>
                            <?php else: ?><dd>--</dd><?php endif; ?>
                            <dt>Travel Ends</dt>
                            <?php if(!is_null($trip->start) && $trip->end != '0000-00-00'): ?> 
                            <dd><?= date('M j, Y', strtotime($trip->end)) ?></dd>
                            <?php else: ?><dd>--</dd><?php endif ?>
                        </dl>
                    </div><!--DATA-->
                    <div class="data last">
                        <dl>
                        </dl>
                    </div><!--DATA-->
                    <div class="listings">
                        <ul>
                        	
                        	<?php $class = ($this->listingCounter[$trip->id][6] == 0) ? 'not-active' : '' ?>
                            <li class="<?= $class ?>"><span><img src="/images2/ico_128.png" alt="" /></span>
							<?= $this->listingCounter[$trip->id][6] ?>
                            <em><span>activities</span></em></li>
                            <?php $class = ($this->listingCounter[$trip->id][5] == 0) ? 'not-active' : '' ?>
                            <li class="<?= $class ?>"><span><img src="/images2/ico_129.png" alt="" /></span>
                            <?= $this->listingCounter[$trip->id][5] ?>
                            <em class="hotels"><span>Hotels</span></em></li>
                            <?php $class = ($this->listingCounter[$trip->id][2] == 0) ? 'not-active' : '' ?>
                            <li class="<?= $class ?>"><span><img src="/images2/ico_130.png" alt="" /></span>
                            <?= $this->listingCounter[$trip->id][2] ?>
                            <em class="restaurants"><span>Restaurants</span></em></li>
                            <?php $class = ($this->listingCounter[$trip->id][7] == 0) ? 'not-active' : '' ?>
                            <li class="<?= $class ?>"><span><img src="/images2/ico_131.png" alt="" /></span>
                            <?= $this->listingCounter[$trip->id][7] ?>
                            <em class="entertaiment"><span>ENTERTAINMENT</span></em></li>
                            <?php $class = ($this->listingCounter[$trip->id][4] == 0) ? 'not-active' : '' ?>
                            <li class="<?= $class ?> last"><span><img src="/images2/ico_132.png" alt="" /></span>
                            <?= $this->listingCounter[$trip->id][4] ?>
                            <em><span>TOURIST SIGHTS</span></em></li>
                        </ul>
                        <div class="clear"></div>
                    </div><!--LISTINGS-->
                    <div class="clear"></div>
                </div><!--DESCRIPTION-->
                <div class="summary">
                    <div class="price">
                        <em>Aproximate / person</em><h4> $<?= $trip->price ?> </h4>
                    </div><!--PRICE-->
                    <div class="controls">
                    	<?php if($trip->start != '0000-00-00' && $trip->end != '0000-00-00'): ?>
                        <a href="/user/trips/itinerary/<?= $trip->id ?>" class="btn-1">Manage Trip</a>
                        <?php else: ?>
                        <a href="#set_dates_<?= $trip->id ?>" class="lb btn-1">Manage Trip</a>
                        <?php endif ?>
						<a href="#delete_trip_<?= $trip->id ?>" class="btn-10 lb">Delete Trip</a>
                    </div><!--CONTROLS-->
                </div><!--SUMMARY-->
            </div><!--INFO-->
        </div><!--single-->
        <?php endforeach ?>
        <div class="single">
        	<div class="image">
        		<div class="slideshow">
        			<img src="https://developer.tripfab.com/images2/img-79.jpg" width="134" height="134" alt="" />
        			<img src="https://developer.tripfab.com/images2/img-80.jpg" width="134" height="134" alt="" />
        			<img src="https://developer.tripfab.com/images2/img-81.jpg" width="134" height="134" alt="" />
        			<img src="https://developer.tripfab.com/images2/img-82.jpg" width="134" height="134" alt="" />
        		</div><!--SLIDESHOW-->
        		
        	</div><!--image-->
        	<div class="info">
        		<div class="title">
        			<h3><a href=""><span class="icon"></span>Trip ESTATICO DE PRUEBA PARA VER FECHAS</a></h3>
        			<span class="days_left"> 1000 Days Trip</span>
        		</div><!--TITLE-->
        		<div class="description">
        			<div class="data">
        				<dl>
        					<dt>Travel Start</dt>
        					<dd class="ended">Apr 26, 2011</dd>
        					<dt>Travel Ends</dt>
        					<dd class="ended">Apr 26, 2011</dd>
        				</dl>
        			</div><!--DATA-->
        			<div class="data last">
        				<dl>
        					<dt>Travelers</dt>
        					<dd>4 People</dd>
        					<dt>Travel Ends</dt>
        					<dd>1 Child</dd>
        				</dl>
        			</div><!--DATA-->
        			<div class="listings">
        				<ul>
        					<li><span><img src="https://developer.tripfab.com/images2/ico_128.png" width="18" height="30" alt="" /></span>0<em><span>activities</span></em></li>
        					<li><span><img src="https://developer.tripfab.com/images2/ico_129.png" width="18" height="30" alt="" /></span>20<em class="hotels"><span>Hotels</span></em></li>
        					<li><span><img src="https://developer.tripfab.com/images2/ico_130.png" width="18" height="30" alt="" /></span>20<em class="restaurants"><span>Restaurants</span></em></li>
        					<li class="not-active"><span><img src="https://developer.tripfab.com/images2/ico_131.png" width="18" height="30" alt="" /></span>0<em class="entertaiment"><span>ENTERTAINMENT</span></em></li>
        					<li class="last"><span><img src="https://developer.tripfab.com/images2/ico_132.png" width="18" height="30" alt="" /></span>20<em><span>TOURIST SIGHTS</span></em></li>
        				</ul>
        				<div class="clear"></div>
        			</div><!--LISTINGS-->
        			<div class="clear"></div>
        		</div><!--DESCRIPTION-->
        		<div class="summary">
        			<div class="price">
        				<em>Trip Estimate</em><h4> $2,725 / person</h4>
        			</div><!--PRICE-->
        			<div class="controls">
        				<a href="#redefineDates" class="btn-1 lbc">Redefine Dates</a>
        				<a href="" class="btn-10">Delete Trip</a>
        				<span><em>20</em>Pending Offers</span>
        			</div><!--CONTROLS-->
        		</div><!--SUMMARY-->
        	</div><!--INFO-->
        </div><!--single-->
    </div><!-- ALL_TRIPS -->
    <?php else: ?>
    	<div class="no_trips">
    		<div class="icon">You are not planning any trip yet</div>
    	</div><!--NO_TRIPS-->
    <?php endif ?>
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div class="hidden">
	<?php foreach($this->trips as $trip): ?>
    <div id="delete_trip_<?= $trip->id ?>" class="lb delete_card_lb">
    	<form action="" method="post" id="form_delete_trip_<?= $trip->id ?>">
            <div class="mid">
                <h3>Are you sure you want to delete this trip?<br />
                You will loose all the information</h3>
            </div>
            <div class="bottom">
                <a href="#" class="btn-1 delete_btn">Delete</a>
                <a href="#" onclick="$.fancybox.close(); return false;" class="btn-10">Cancel</a>
            </div><!--BOTTOM-->
            <input type="hidden" name="ids" value="<?= $trip->id ?>" />
            <input type="hidden" name="token" value="<?= $trip->token ?>" />
            <input type="hidden" name="_task" value="<?= md5('delete_trip') ?>" />
        </form>
    </div>
    <?php endforeach ?>
	<?php foreach($this->trips as $trip): ?>
    <?php if($trip->start == '0000-00-00' or $trip->end == '0000-00-00'): ?>
    <div id="set_dates_<?= $trip->id ?>">
    	<form method="post" action="">
            <div class="lb-forgot trip-dates">
                <div class="ttl">
                    Ready to travel?
                    <span>We need some information about your trip to make it fabuluos!</span>
                </div><!-- closes ttl -->
                <div class="content">
                    <div class="left">
                        <span>Set the starting date</span>
                        <input name="start" class="calendar1" type="text" />
                    </div><!-- closes left -->
                    <div class="right">
                        <span>Set the ending date</span>
                        <input type="text" name="end" class="calendar2" />
                    </div><!-- closes right -->				
                    <input type="checkbox" />
                    <label>Receive special offers from vendors near the places I'll visit</label>
                </div><!-- closes content -->
                <div class="bottom">
                    <input type="submit" class="btn-1" value="Manage Itinerary" />
                    <span class="btn-4" onclick="$.fancybox.close()">Cancel</span>
                </div><!-- closes bottom -->
            </div><!-- closes lb-forgot -->
            <input type="hidden" name="ids" value="<?= $trip->id ?>" />
            <input type="hidden" name="token" value="<?= $trip->token ?>" />
            <input type="hidden" name="_task" value="<?= md5('assign_dates') ?>" />
        </form>
    </div>
    <?php endif ?>
    <?php endforeach ?>        
    <div class="redefineDates lb" id="redefineDates">
		<div class="top">Redefine Travel Date</div>
		<div class="cont">
			<p>When do you want to start your trip?</p>
			<div id="calendar">
			
			</div><!--CALENDAR-->
			<div class="bottom">
				<input type="submit" class="btn-1" name="" value="Update Dates" />
				<a href="$.fancyboxClose" class="btn-10">Cancel</a>
			</div><!--BOTTOM-->
		</div><!--CONT-->	
	</div><!--REDEFINEDATES-->
</div>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
		$('a.lbc').fancybox({
			padding:0,
			overlayColor:'#fff',
			centerOnScroll:1,
			showCloseButton:0
		});
		
		$('.notification.end-1 .btn-10').click(function() {
			$('.notification.end-1').fadeOut('slow');
			return false
		})
		$('.notification.soon-1 .btn-10').click(function() {
			$('.notification.soon-1').fadeOut('slow');
			return false
		});
		
		$('#calendar').datepicker({
			dayNamesMin: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
			showOtherMonths: true
		});
		
		$('a.delete_btn').click(function(){
			$form = $(this).parents('form');
			$form.submit();
			return false;
		});
		$('.lbox .btn-2, .lbox .btn-11').click(function(){
			$(this).parents('form').submit();
		});
		
		$('input.calendar1').datepicker({
			minDate:new Date(),
			onSelect:function(date){
				$end = $(this).parents('.content').find('input.calendar2');
				$end.datepicker('option','minDate', date);
			},
			dateFormat:'D M d yy'
		});
		
		$('input.calendar2').datepicker({
			minDate:new Date(),
			dateFormat:'D M d yy'
		});
		
		$('#ui-datepicker-div').wrap('<div id="calendarContainer"></div>');
		
		<?php if($this->alert): ?>
		showAlert("<?= $this->alert ?>");
		<?php endif ?>
		
		<?php if($this->error): ?>
		showError("<?= $this->error ?>");
		<?php endif ?>
    });
</script>    
<script type="text/javascript">
    $(document).ready(function() {
		$('.slideshow').cycle({
            fx: 'fade'
        });
    });
</script>
</body>
</html>