<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> - <?= $this->trip->title ?>, Trip Itinerary | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css6/calendar.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <link type="text/css" rel="stylesheet" href="/css2/lightboxes.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
</head>
<body>
<div class="w1 itineraries">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w3_itinerary">
        <div class="wrapper">
            <h2><?= $this->trip->title ?> <a href="#rename-trip" class="lbc">Rename Itinerary</a></h2>
            <?php if($this->tocheckout): ?>
            <a href="/user/trips/checkprices/<?= $this->trip->id ?>" class="btn-1 tocheckout">Proceed to Checkout</a>
             <div class="warning hidden">
             	<h3>You can't checkout</h3>
             	<p>You must to add something to do to your itinerary before checkout</p>
             </div><!--WARNING-->
            <?php else: ?>
            <a href="/user/trips/checkprices/<?= $this->trip->id ?>" class="btn-1 deny tocheckout">Proceed to Checkout</a>
             <div class="warning hidden">
             	<h3>You can't checkout</h3>
             	<p>You must to add something to do to your itinerary before checkout</p>
             </div><!--WARNING-->
             <?php endif ?>
             <a href="#dates_lbx" class="btn-10 lb dates">Change Travel Dates</a>
        </div><!--WRAPPER-->
    </div><!--w3_itinerary-->
    <div class="title_itinerary">
        <h3>Itinerary Manager</h3>
        <a href="/user/trips">&larr; Back to My Future Trips</a>
    </div><!--title_itinerary-->
    <div class="w2">
        <div class="wrapper user-messages user-trips no-over">
            <div class="itinerary-wrapper">
                <div class="activities-tabs">
                    <ul>
                        <li class="activity"><a href="#tab-1">Activities <em></em></a></li>
                        <li class="entertaiment"><a href="#tab-2">Entertainment <em></em></a></li>
                        <li class="sights"><a href="#tab-3">Tourist Sights <em></em></a></li>
                        <li class="restaurants"><a href="#tab-4">Restaurants <em></em></a></li>
                        <li class="hotels"><a href="#tab-5">Hotels <em></em></a></li>
                    </ul>
                    <?php $class = array('','cat-activity','cat-entertainment','cat-sight','cat-restaurant','cat-hotel'); ?>
                    <?php for($i=1; $i<=5; $i++): ?>
                    <div class="tab" id="tab-<?= $i ?>">
                    	<?php if(!isset($_COOKIE['tooltipHelpItn'])): ?>
                    	<div class="firstime_tip">
                    		<img class="arrow" src="/images6/tooltiparrow.png" alt="">
                    		<div class="cont">
                    			<img src="https://developer.tripfab.com/images6/tooltipimg2.png" width="75" height="75" alt="" />
                    			<p><strong>Customize your Trip</strong>
                    				Drag and drop the activities, hotels, restaurants, tourist sights and entertainments you want to add to your trip.
                    			</p>
                    		</div><!--CONT-->
                    		<div class="bot">
                    			<form action="post" id="tooltipHelpItn">
                    				<fieldset>
                    					<label><input checked="checked" type="checkbox" name="" value="" />Don’t show again</label>
                    					<input type="submit" value="Okay" class="btn-1" />
                    				</fieldset>
                    			</form>
                    		</div><!--BOT-->
                    	</div><!--FIRSTIME_TIP-->
                    	<?php endif ?>
                        <ul id="mycarousel-<?= $i ?>">
                        	<?php if(isset($this->favorites[$i]) and count($this->favorites[$i]) > 0): ?>
                        	<?php foreach($this->favorites[$i] as $listing): ?>
                            <?php if(($listing->main_type != 5) or (is_null($listing->day) and is_null($listing->time))): ?>
                            <li data-id="<?= $listing->id ?>" data-city="<?= $listing->city_id ?>" data-class="<?= $class[$i] ?>"
                            data-country="<?= $listing->country_id ?>" data-type="<?= $i ?>" class="<?= $class[$i] ?>" data-trip="<?= $this->trip->id ?>">
                                <?= ($listing->image) ? 
										$this->thumbnail(65, $listing->image, '','1:1') :
										$this->thumbnail(65, '/images/img-70.png', '','1:1'); ?>
                                <h2><?= $listing->title ?></h2>
                                <?php if($listing->price > 0): ?>
                                <span>$<?= $this->formatnumber($listing->price) ?> <em>/person</em></span>
                                <?php else: ?>
								<span><h2>Price Not charged</h2></span>
                                <?php endif ?>
                            </li>
                            <?php endif ?>
                            <?php endforeach ?>
                            <?php endif ?>
                        </ul>
                    </div><!-- tab  -->
                    <?php endfor ?>
                </div><!-- closes activities-tab -->
                <div class="slider-controls">	
                    <a href="" class="next">Next Day &rarr;</a>
                    <a href="" class="prev">&larr; Previous Day</a>
                </div><!-- closes -->
                <div class="slider">
                	
                	<?php for($i=0; $i<$this->trip->days; $i++): ?>
                    <div class="slide">
                        <div class="hdr">
                        	<?php $time = strtotime($this->trip->start); ?>
                            <?php $daytime = $time + ($i * 86400) ?>
							<span>Day <?= $i+1 ?></span> <?= date('F jS, Y', $daytime) ?>
                        </div><!-- closes hdr -->
                        <div class="itinerary-items">
                        	<?php foreach($this->days[$i+1] as $time => $listings): ?>
                            <?php if(!empty($time) and $time != 'stay'): ?>
                            <div class="item" data-time="<?= $time ?>" data-day="<?= $i+1 ?>" data-date="<?= date('F jS, Y', $daytime) ?>">
                                <h4><?= $time ?></h4>
                                <ul class="morning">
                                    <?php if(count($listings) > 0): ?>
                                    <?php foreach($listings as $list): ?>
                                    <li data-id="<?= $list->id ?>" data-city="<?= $list->city_id ?>" data-class="<?= $class[$i] ?>"
		                            data-country="<?= $list->country_id ?>" data-type="<?= $list->main_type ?>" class="<?= $class[$i] ?>" 
                                    data-trip="<?= $this->trip->id ?>">
                                        <?= ($list->image) ? 
												$this->thumbnail(45, $list->image, '','1:1') :
												$this->thumbnail(45, '/images/img-70.png', '','1:1'); ?>
                                        <h2><?= substr($list->title, 0, 19) ?>...</h2>
										<?php if($list->price > 0): ?>
										<span class="location"><?= $list->city ?> ,CR</span>
                                        <span>$<?= $this->formatnumber($list->price) ?><em>/ person</em></span>
                                        <?php else: ?>
								<span><h2>Price Not charged</h2></span>                            
                                        <?php endif ?>
                                        <a href="" class="delete">Delete</a>
                                    </li>
                                    <?php endforeach ?>
                                    <?php else: ?>
                                    <li class="empty">
                                        <img src="/images2/arrow-17.png" alt="" />
                                        Drop here the things you want to do this Morning
                                    </li>
                                    <?php endif ?>
                                </ul>
                            </div><!-- closes item -->
                            <?php endif ?>
                            <?php endforeach ?>
                            <div class="item last stay" data-time="stay" data-day="<?= $i+1 ?>" data-date="<?= date('F jS, Y', $daytime) ?>">
                                <h4>Stay</h4>
								<?php if(count($this->days[$i+1]['stay']) > 0): ?>
                                <ul data-hashotel="1">
                                    <?php foreach($this->days[$i+1]['stay'] as $list): ?>
                                    <li data-id="<?= $list->id ?>" data-city="<?= $list->city_id ?>" data-class="<?= $class[5] ?>"
		                            data-country="<?= $list->country_id ?>" data-type="<?= $list->main_type ?>" class="<?= $class[5] ?>" 
                                    data-trip="<?= $this->trip->id ?>">
                                        <?= ($list->image) ? 
												$this->thumbnail(45, $list->image, '','1:1') :
												$this->thumbnail(45, '/images/img-70.png', '','1:1'); ?>
                                        <h2><?= substr($list->title, 0, 19) ?>...</h2>
                                        <span class="location"><?= $list->city ?>, CR</span>
										<?php if($list->price > 0): ?>
                                        <span>$<?= $this->formatnumber($list->price) ?><em>/ person</em></span>
                                        <?php else: ?>
										<span><h2>Price Not charged</h2></span>
                                        <?php endif ?>
                                        <a href="" class="delete">Delete</a>
                                    </li>
                                    <?php endforeach ?>
                                </ul>
								<?php else: ?>
                                <ul>
                                    <li class="empty">
                                        <img src="/images2/arrow-17.png" alt="" />
                                        Drop here the places you want to stay this day
                                    </li>
                                </ul>
								<?php endif ?>
                            </div><!-- closes item -->
                        </div><!-- closes itinerary-items -->
                    </div><!-- closes slide -->
                    <?php endfor ?>
                </div><!-- closes slider -->	
                <div class="bottom">
                    <span>Trip Estimate</span>
                    <strong id="tripprice">$<?= $this->formatnumber($this->trip->price) ?></strong>
                    <?php if($this->tocheckout): ?>
                    <a href="/user/trips/checkprices/<?= $this->trip->id ?>" class="btn-1 tocheckout">Proceed to Checkout</a>
                    <div class="warning hidden">
                    	<h3>You can't checkout</h3>
                    	<p>You must to add something to do to your itinerary before checkout</p>
                    </div><!--WARNING-->
                    <?php else: ?>
                    <a  href="/user/trips/checkprices/<?= $this->trip->id ?>" class="btn-1 deny tocheckout">Proceed to Checkout</a>
                    <div class="warning hidden">
                    	<h3>You can’t checkout</h3>
                    	<p>You must to add something to do to your itinerary before checkout</p>
                    </div><!--WARNING-->
                    <?php endif ?>
                </div><!-- closes bottom -->
            </div><!-- closes itinerary-wrapper -->
        </div><!-- closes user-messages -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<div class="hidden">
	<div id="delete_trip_<?= $this->trip->id ?>">
    	<form action="/user/trips" method="post" id="form_delete_trip_<?= $this->trip->id ?>">
            <div class="lbox lb-size-1">
                <div class="lb-wrapper">
                    <div class="inner-wrapper">
                        <div class="lb-ttl">
                            Are you sure you want to delete "<?= $this->trip->title ?>" ?
                        </div><!-- closes lb-ttl -->
                        <div class="lb-content">
                            <div class="btns">
                                <span class="btn-8" onclick="$.fancybox.close()">Cancel</span>
                                <span class="btn-11">Delete</span>
                            </div><!-- closes btns -->
                        </div><!-- closes content -->
                    </div><!-- closes inner-wrapper -->
                </div><!-- closes lb-wrapper -->
            </div><!-- closes lb-size-1 -->
            <input type="hidden" name="ids" value="<?= $this->trip->id ?>" />
            <input type="hidden" name="token" value="<?= $this->trip->token ?>" />
            <input type="hidden" name="_task" value="<?= md5('delete_trip') ?>" />
        </form>
    </div>
         
    <div class="dates_lbx lb" id="dates_lbx">
		<form method="post" action="">
			<div class="top">Change Trip Dates<span class="label"><?= $this->trip->days ?> Days</span></div><!--TOP-->
			<div class="cont">
				<label>Start</label>
                <input name="start" class="calendar1" type="text" />
				<label>End</label>
                <input name="end" class="calendar2" type="text" />
			</div><!--CONT-->
			<div class="bottom">
				<input class="btn-1" type="submit" value="Update dates" />
                <a href="#" onclick="$.fancybox.close(); return false;" class="btn-10">Cancel</a>
			</div><!--BOTTOM-->
            <input type="hidden" name="ids" value="<?= $this->trip->id ?>" />
            <input type="hidden" name="token" value="<?= $this->trip->token ?>" />
            <input type="hidden" name="_task" value="<?= md5('assign_dates') ?>" />
		</form>
	</div><!--DATES_LBX-->
	
	<div class="renameTrip lb" id="rename-trip">
		<div class="top">Rename Trip</div>
		<div class="cont">
			<form method="submit" action="">
				<label for="">Trip Name</label>
				<input type="text" name="" value="" />
			</form>
		</div><!--CONT-->
		<div class="bottom">
			<input class="btn-1" type="submit" name="" value="Rename" />
			<a class="btn-10" href="$.fancybox.close()">Cancel</a>
		</div><!--BOTTOM-->
	</div><!--RENAMETRIP-->
	
</div>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/user/trips.itinerary.js"></script>
<script type="text/javascript">
$(function(){
	$('input.calendar1').datepicker({
		minDate:new Date(),
		onSelect:function(date){
			$end = $(this).parents('.cont').find('input.calendar2');
			$end.datepicker('option','minDate', date);
		},
		dateFormat:'D M d yy'
	});
	
	$('input.calendar2').datepicker({
		minDate:new Date(),
		dateFormat:'D M d yy'
	});
	
	$('a.deny').live('click', function(){
		return false;
	});
});
</script>
<style type="text/css">
.jcarousel-clip.unhidden {
	position:static !important;
	overflow:visible !important;
}
.jcarousel-clip { min-height:100px;}
.ui-draggable-dragging {
	z-index:10000;
	padding:5px !important; }
.activities-tabs .tab ul li {
	background:#303030;}
.itinerary-items .item.ui-state-default {
	background:#e7e7e7;}
.itinerary-items .item.ui-state-hover {
	background:#fbfbfb;}
	.itinerary-items .item ul li img {
		height:auto;}
</style>
</body>
</html>