<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Past Trips | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css2/lightboxes.css" />
    <link type="text/css" rel="stylesheet" href="/css2/calendar2/jquery-ui-1.8.16.custom.css" />
	<link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('textarea').elastic();				
            $('input').ToggleInputValue();
            $('form select').jqTransSelect();
			$('a.lb').fancybox({
				padding:0,
				overlayColor:'#fff',
				centerOnScroll:1,
				showCloseButton:0,
			});
			
			$('a.delete_btn').click(function(){
				$form = $(this).parents('form');
				$form.submit();
				return false;
			});
			$('.lbox .btn-2, .lbox .btn-11').click(function(){
				$(this).parents('form').submit();
			});
			
			$('input.calendar1').datepicker({
				minDate:new Date(),
				onSelect:function(date){
					$end = $(this).parents('.content').find('input.calendar2');
					$end.datepicker('option','minDate', date);
				},
				dateFormat:'D M d yy',
			});
			
			$('input.calendar2').datepicker({
				minDate:new Date(),
				dateFormat:'D M d yy',
			});
			
			$('#ui-datepicker-div').wrap('<div id="calendarContainer"></div>');
			
			<?php if($this->alert): ?>
			showAlert("<?= $this->alert ?>");
			<?php endif ?>
			
			<?php if($this->error): ?>
			showError("<?= $this->error ?>");
			<?php endif ?>
        });
    </script>    
    <script type="text/javascript">
        $(document).ready(function() {
			$('.slideshow').cycle({
                fx: 'fade'
            });
        });
    </script>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w3_admin">
        <div class="sub_menu">
            <h2><span>You have purchased <?= count($this->trips) ?> Trips</span></h2>
            <ul class="sub_links">
                <li><a href="/user/trips">Future Trips</a></li>
                <li class="select"><a href="/user/trips/past">Past Trips</a></li>
            </ul>
        </div><!--SUB_MENU-->
    </div><!--W3-->
    
    <?php if(count($this->trips) > 0): ?>
    <div id="all_trips">
    	<?php foreach($this->trips as $trip): ?>
        <div class="single">
            <div class="image">
                <div class="slideshow">
                	<?= $this->thumbnail(134, $trip->image, '','1:1'); ?>
                </div><!--SLIDESHOW-->
            </div><!--image-->
            <div class="info">
                <div class="title">
                    <h3><a href=""><span class="icon"></span><?= $trip->title ?></a></h3>
                    <span class="days_left"> <?= $trip->days ?> Days Trip</span>
                </div><!--TITLE-->
                <div class="description">
                    <div class="data">
                        <dl>
                            <dt>Travel Started</dt>
                            <?php if(!is_null($trip->start) && $trip->start != '0000-00-00'): ?>
                            <dd><?= date('M j, Y', strtotime($trip->start)) ?></dd>
                            <?php else: ?><dd>--</dd><?php endif; ?>
                            <dt>Travel Ended</dt>
                            <?php if(!is_null($trip->start) && $trip->end != '0000-00-00'): ?> 
                            <dd><?= date('M j, Y', strtotime($trip->end)) ?></dd>
                            <?php else: ?><dd>--</dd><?php endif ?>
                        </dl>
                    </div><!--DATA-->
                    <div class="data last">
                        <dl>
                        </dl>
                    </div><!--DATA-->
                    <div class="listings">
                        <ul>
                        	
                        	<?php $class = ($this->listingCounter[$trip->id][6] == 0) ? 'not-active' : '' ?>
                            <li class="<?= $class ?>"><span><img src="/images2/ico_128.png" alt="" /></span>
							<?= $this->listingCounter[$trip->id][6] ?>
                            <em><span>activities</span></em></li>
                            <?php $class = ($this->listingCounter[$trip->id][5] == 0) ? 'not-active' : '' ?>
                            <li class="<?= $class ?>"><span><img src="/images2/ico_129.png" alt="" /></span>
                            <?= $this->listingCounter[$trip->id][5] ?>
                            <em class="hotels"><span>Hotels</span></em></li>
                            <?php $class = ($this->listingCounter[$trip->id][2] == 0) ? 'not-active' : '' ?>
                            <li class="<?= $class ?>"><span><img src="/images2/ico_130.png" alt="" /></span>
                            <?= $this->listingCounter[$trip->id][2] ?>
                            <em class="restaurants"><span>Restaurants</span></em></li>
                            <?php $class = ($this->listingCounter[$trip->id][7] == 0) ? 'not-active' : '' ?>
                            <li class="<?= $class ?>"><span><img src="/images2/ico_131.png" alt="" /></span>
                            <?= $this->listingCounter[$trip->id][7] ?>
                            <em class="entertaiment"><span>ENTERTAINMENT</span></em></li>
                            <?php $class = ($this->listingCounter[$trip->id][4] == 0) ? 'not-active' : '' ?>
                            <li class="<?= $class ?> last"><span><img src="/images2/ico_132.png" alt="" /></span>
                            <?= $this->listingCounter[$trip->id][4] ?>
                            <em><span>TOURIST SIGHTS</span></em></li>
                        </ul>
                        <div class="clear"></div>
                    </div><!--LISTINGS-->
                    <div class="clear"></div>
                </div><!--DESCRIPTION-->
                <div class="summary">
                    <div class="price">
                        <em>Total paid</em><h4> $<?= $trip->price ?> </h4>
                    </div><!--PRICE-->
                    <div class="controls">
                        <a href="/user/trips/view/<?= $trip->id ?>" class="btn-1">View Trip</a>
                    </div><!--CONTROLS-->
                </div><!--SUMMARY-->
            </div><!--INFO-->
        </div><!--single-->
        <?php endforeach ?>
    </div><!-- ALL_TRIPS -->
    <?php else: ?>
    
    <?php endif ?>
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
</body>
</html>