<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> :: <?= $this->trip->title ?>, Trip Offers | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages user-trips">
        	<div class="tripttl">
        		<div>
        			<a href="" class="btn-1">Proceed to Checkout</a>
        			<?= $this->thumbnail(50, $this->trip->image, '', '1:1'); ?>
        			<h2><?= $this->trip->title ?></h2>
        		</div>
        	</div>
        	<!-- closes tripttl -->
            <?= $this->partial('partials/usertripinfomenu.phtml', array('active'=>'Offers', 'id'=>$this->trip->id,'offers'=>1)); ?>
            <div class="offers-wrapper">
                <div class="offer">
                    <div class="content">
                        <h3>Horseback Riding</h3>
                        <img src="/images2/img-24.png" alt="" />
                        <span>Valid from Jan 1st to Apr 26th</span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget magna sit amet lectus lacinia dictum vitae pellentesque nulla. Nulla molestie, augue sit amet laoreet vehicula, nulla nunc elementum magna, eget ultricies metus dolor a enim.</p>
                        <a href="" class="btn-4">See Details</a>
                        <div class="meta">
                            <strong>$142</strong>
                            <span>Total Price</span>
                        </div>
                        <!-- closes meta -->
                    </div>
                    <!-- closes left -->
                    <div class="aside">
                        <div class="meta">
                            <span>Special Offer</span>
                            <strong>4x3</strong>									
                        </div>
                        <!-- closes meta -->
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td>Value</td>
                                    <td><strong>$264</strong></td>
                                </tr>
                                <tr>
                                    <td>Discount</td>
                                    <td><strong>25%</strong></td>
                                </tr>
                                <tr>
                                    <td>You Save</td>
                                    <td><strong>$122</strong></td>
                                </tr>
                            </tbody>
                        </table>
                        <a href="" class="btn-4">No, Thanks</a>
                        <a href="" class="btn-1">Accept</a>
                    </div>
                    <!-- closes right -->
                </div>
                <!-- closes offer -->
                <div class="offer">
                    <div class="content">
                        <h3>Horseback Riding</h3>
                        <img src="/images2/img-24.png" alt="" />
                        <span>Valid from Jan 1st to Apr 26th</span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget magna sit amet lectus lacinia dictum vitae pellentesque nulla. Nulla molestie, augue sit amet laoreet vehicula, nulla nunc elementum magna, eget ultricies metus dolor a enim.</p>
                        <a href="" class="btn-4">See Details</a>
                        <div class="meta">
                            <strong>$142</strong>
                            <span>Total Price</span>
                        </div>
                        <!-- closes meta -->
                    </div>
                    <!-- closes left -->
                    <div class="aside">
                        <div class="meta">
                            <span>Special Offer</span>
                            <strong>25%</strong>									
                        </div>
                        <!-- closes meta -->
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td>Value</td>
                                    <td><strong>$264</strong></td>
                                </tr>
                                <tr>
                                    <td>Discount</td>
                                    <td><strong>25%</strong></td>
                                </tr>
                                <tr>
                                    <td>You Save</td>
                                    <td><strong>$122</strong></td>
                                </tr>
                            </tbody>
                        </table>
                        <a href="" class="btn-4">No, Thanks</a>
                        <a href="" class="btn-1">Accept</a>
                    </div>
                    <!-- closes right -->
                </div>
                <!-- closes offer -->
                <div class="offer">
                    <div class="content">
                        <h3>Horseback Riding</h3>
                        <img src="/images2/img-24.png" alt="" />
                        <span>Valid from Jan 1st to Apr 26th</span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget magna sit amet lectus lacinia dictum vitae pellentesque nulla. Nulla molestie, augue sit amet laoreet vehicula, nulla nunc elementum magna, eget ultricies metus dolor a enim.</p>
                        <a href="" class="btn-4">See Details</a>
                        <div class="meta">
                            <strong>$142</strong>
                            <span>Total Price</span>
                        </div>
                        <!-- closes meta -->
                    </div>
                    <!-- closes left -->
                    <div class="aside">
                        <div class="meta">
                            <span>Special Offer</span>
                            <strong>50%</strong>									
                        </div>
                        <!-- closes meta -->
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td>Value</td>
                                    <td><strong>$264</strong></td>
                                </tr>
                                <tr>
                                    <td>Discount</td>
                                    <td><strong>25%</strong></td>
                                </tr>
                                <tr>
                                    <td>You Save</td>
                                    <td><strong>$122</strong></td>
                                </tr>
                            </tbody>
                        </table>
                        <a href="" class="btn-4">No, Thanks</a>
                        <a href="" class="btn-1">Accept</a>
                    </div>
                    <!-- closes right -->
                </div>
                <!-- closes offer -->
            </div>
            <!-- closes offers-wrapper -->
        </div>
        <!-- closes user-messages -->
    </div>
    <!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div>
<!-- closes w1 -->
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('textarea').elastic();				
        $('input').ToggleInputValue();
    });
</script>
</body>
</html>