<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->trip->title ?> - Check Availability and Price | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
    <link type="text/css" rel="stylesheet" href="/css2/calendar/jquery-ui-1.8.16.custom.css" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css" /><![endif]-->
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>
    <div class="w2">
        <div class="checkout_headerB">
            <h2><?= $this->trip->title ?></h2>
            <span class="place"><?= $this->country->title ?></span> 
            <span class="label"><em></em><?= $this->trip->days ?> <?= ($this->trip->days > 1) ? 'Days' : 'Day' ?> Trip</span> 
        </div><!--CHECKOUT_HEADERB-->
        <div class="wrapper" id="custom_checkout"> 
            <div class="left_block">
                <h3>Check the availability for your trip and the listing options before continue with the checkout</h3>
                <form method="post" action="" id="checkprices_form">
                    <div id="checkout_accordion">
                        <?php foreach($this->items as $item): ?>
                        <?php if($item->available || ($item->available === 0)): ?>
                        <div class="header active">
                            <span class="arrow"></span> 
                            <a href="#"></a>
                            <div class="descrip"> 
                                <?= $this->thumbnail(49, $item->listing_image, '', '1:1'); ?>
                                <h4><?= $item->listing_title ?></h4>
                                <span class="type"><?= $this->types[$item->listing_type]['name'] ?></span>
                                <p><?= $item->listing_city ?>, <?= $item->listing_country ?></p>
                            </div><!--DESCRIP-->
                            <?php if($item->available): ?>
                            <div class="info"> 
                                <span><em></em>Available</span>
                                <p>Ready to go! Just accept the terms</p>
                            </div><!--INFO--> 
                            <?php else: ?>
                            <div class="info"> 
                                <span><em></em>Available</span>
                                <p>But there are some problems</p>
                            </div><!--INFO--> 
                            <?php endif ?>
                        </div><!--HEADER-->
                        <div class="details">
                            <?php if(!$item->available): ?>
                            <div class="warning"><?= $item->error ?></div><!--WARNING-->
                            <?php endif ?>
                            <div class="item"> 
                                <strong>Occupation</strong>
                                <div class="edit">
                                    <label for="adults">Adults</label>
                                    <select name="bookings[<?= $item->id ?>][adults]" id="adults">
                                        <?php for($i=1; $i<=12; $i++): ?>
                                        <?php $selected = ($i == $item->adults) ? 'selected="selected"' : ''; ?>
                                        <option <?= $selected ?> value="<?= $i ?>"><?= $i ?></option>
                                        <?php endfor ?>
                                    </select>
                                    <label for="Children">Children</label>
                                    <select name="bookings[<?= $item->id ?>][kids]" id="Children">
                                        <?php for($i=0; $i<=12; $i++): ?>
                                        <?php $selected = ($i == $item->kids) ? 'selected="selected"' : ''; ?>
                                        <option <?= $selected ?> value="<?= $i ?>"><?= $i ?></option>
                                        <?php endfor ?>
                                    </select>
                                </div><!--EDIT--> 
                            </div><!--ITEM-->
                            <?php if($item->listing_type == 5): ?>
                            <div class="item"> 
                                <strong>Check In</strong>
                                <div class="edit"><?= date('L, F jS, Y', strtotime($item->checkin)) ?></div>
                            </div><!--ITEM-->
                            <div class="item"> 
                                <strong>Check Out</strong>
                                <div class="edit"><?= date('L, F jS, Y', strtotime($item->checkout)) ?></div><!--EDIT--> 
                            </div><!--ITEM-->
                            <div class="item"> 
                                <strong>Rooms</strong>
                                <div class="edit"><?= $item->rooms ?></div><!--EDIT--> 
                            </div><!--ITEM-->
                            <?php if(isset($this->options[$item->id]['options']) && 
                                    (count($this->options[$item->id]['options'] > 0))): ?>
                            <div class="item"> 
                                <strong>Room Type</strong>
                                <div class="room-type">
                                    <p>Select the room type you want to stay:</p>
                                    <?php foreach($this->options[$item->id]['options'] as $room): ?>
                                    <div class="single">
                                        <label for="Room1">
                                            <?php $checked = ($item->option_id == $room->schedule_id) ? 'checked="checked"' : ''; ?>
                                            <strong><input <?= $checked ?> type="radio" name="bookings[<?= $item->id ?>][option]" 
                                            id="Room1" value="<?= $room->schedule_id ?>" /><?= $room->name ?></strong> 
                                            <span><?= $room->description ?></span>
                                        </label>
                                        <span class="price">$<?= $this->options[$item->id]['prices'][$room->schedule_id]['price'] ?></span> 
                                    </div><!--SINGLE-->
                                    <?php endforeach ?>
                                </div><!--ROOM-TYPE--> 
                            </div><!--ITEM-->
                            <?php endif ?>
                            <?php else: ?>
                            <div class="item"> 
                                <strong>Activity Date</strong>
                                <div class="edit"><?= date('L, F jS, Y', strtotime($item->checkin)) ?></div><!--EDIT--> 
                            </div><!--ITEM-->
                            <div class="item"> 
                                <strong>Activity Type</strong>
                                <div class="room-type">
                                    <p>Select the capacity type that must fit your needs:</p>
                                    <?php if((is_null($item->listing_min) or is_null($item->listing_max)) &&
                                            (count($this->options[$item->id]['capacity']) > 0)): ?>
                                    <?php foreach($this->options[$item->id]['capacity'] as $option): ?>
                                    <div class="single">
                                        <?php $checked = (isset($item->option_id) && ($item->option_id == $option->id)) ? 'checked="checked"' : '' ?>
                                       <label for="activity1">
                                            <strong><input type="radio" name="bookings[<?= $item->id ?>][capacity]" 
                                            value="<?= $option->id ?>" <?= $checked ?> /><?= $option->name ?></strong>
                                            <span>Minimun: <?= (!is_null($option->min)) 
                                                                            ? ($option->min == 1) 
                                                                                ? '1 person' 
                                                                                : $option->min .' people'  
                                                                            : 'Not defined'  ?>
                                            Maximun: <?= (!is_null($option->max)) 
                                                                            ? ($option->max == 1) 
                                                                                ? '1 person' 
                                                                                : $option->max .' people'  
                                                                            : 'Not defined'  ?></span>
                                       </label>
                                       <span class="price">$<?= $this->options[$item->id]['prices'][$option->id]['price'] ?></span> 
                                    </div><!--SINGLE-->
                                    <?php endforeach ?>
                                    <?php else: ?>
                                    <div class="single">
                                       <label for="activity1"> 
                                       <strong><input checked="checked" type="radio" name="bookings[<?= $item->id ?>][capacity]" value="single" />
                                       Single Capacity</strong>
                                       <span>Minimun: <?= (!is_null($item->listing_min)) 
                                                                        ? ($item->listing_min == 1) 
                                                                            ? '1 person' 
                                                                            : $item->listing_min .' people'  
                                                                        : 'Not defined'  ?>
                                        Maximun: <?= (!is_null($item->listing_max)) 
                                                                        ? ($item->listing_max == 1) 
                                                                            ? '1 person' 
                                                                            : $item->listing_max .' people'  
                                                                        : 'Not defined'  ?></span>
                                       </label><span class="price">$<?= $item->listing_price ?></span>
                                    </div><!--SINGLE-->
                                    <?php endif ?>
                                </div><!--ROOM-TYPE--> 
                            </div><!--ITEM-->
                            <div class="item"> 
                                <strong>Schedule</strong>
                                <?php if(count($this->options[$item->id]['options']) > 0): ?>
                                <div class="edit">
                                    <select name="bookings[<?= $item->id ?>][option]">
                                        <?php foreach($this->options[$item->id]['options'] as $sch): ?>
                                        <?php $selected = ((isset($item->schedule_id)) && ($item->schedule_id == $sch->id)) ? 'selected="selected"' : '' ?>
                                        <option <?= $selected ?> value="<?= $sch->id ?>"><?= $sch->name ?> (<?= date('h:i a',strtotime($sch->starting)) ?> - 
                                        <?= date('h:i a',strtotime($sch->ending)) ?>)</option>
                                        <?php endforeach ?>
                                    </select>
                                </div><!--EDIT--> 
                                <?php else: ?>
                                <div class="edit">
                                    Flexible Schedule. You choose the hour
                                    <input type="hidden" name="bookings[<?= $item->id ?>][option]" value="flex" />
                                </div>
                                <?php endif ?>
                            </div><!--ITEM-->
                            <?php endif ?>
                            <?php if($item->available): ?>
                            <div class="item">
                                <strong>Rate</strong>
                                <div class="edit">
                                    $<?= $item->rate ?>, <?= $item->rate_description ?>
                                </div>
                            </div>
                            <?php if(isset($item->additional) and $item->additional > 0): ?>
                            <div class="item">
                                <strong>Additional</strong>
                                <div class="edit">
                                    $<?= $item->additional ?>, <?= $item->additional_description ?>
                                </div>
                            </div>                        
                            <?php endif ?>
                            <div class="item">
                            	<strong>Taxes</strong>
                                <div class="edit">
                                	$<?= $item->taxes ?>
                                </div>
                            </div>
                            <div class="item">
                            	<strong>Total</strong>
                                <div class="edit">
                                	$<?= $item->total ?>
                                </div>
                            </div>
                            <?php endif ?>
                            <div class="item"> 
                                <strong>Cancellation</strong> 
                                <a href="#" class="restriction">High Restrictions &rarr;</a> 
                            </div><!--ITEM-->
                            <div class="last"> 
                                <strong>Hotel Restrictions</strong> 
                                <a href="#" class="restriction">Read Hotel Restrictions &rarr;</a> 
                            </div><!--ITEM-->
                            	
                        </div><!--DETAILS-->
                        <?php else: ?>
                        <div class="header inactive"> 
                            <span class="arrow"></span> 
                            <a href="#"></a>
                            <div class="descrip"> 
                                <?= $this->thumbnail(49, $item->listing_image, '', '1:1'); ?>
                                <h4><?= $item->listing_title ?></h4>
                                <span class="type"><?= $this->types[$item->listing_type]['name'] ?></span>
                                <p><?= $item->listing_city ?>, <?= $item->listing_country ?></p>
                            </div><!--DESCRIP-->
                            <div class="info">
                                <span class="unavaible"><em></em>Not Available</span>
                                <p class="recommendation"><?= $item->error ?> 
                                <a href="/ajax/getrecomendations/<?= $item->id ?>?trip=<?= $this->trip->id ?>&listing=<?= $item->triplistingid ?>" class="link-10 lb">See our recommendations</a></p>
                            </div><!--INFO-->
                        </div><!--HEADER-->
                        <?php endif ?>
                        <?php endforeach ?>
                        <?php foreach($this->items2 as $item): ?>
                        <div class="header active"> <span class="arrow"></span> <a href="#"></a>
                            <div class="descrip"> 
                                <?= $this->thumbnail(49, $item->listing_image, '', '1:1'); ?>
                                <h4><?= $item->listing_title ?></h4>
                                <span class="type"><?= $this->types[$item->listing_type]['name'] ?></span>
                                <p><?= $item->listing_city ?>, <?= $item->listing_country ?></p>
                            </div><!--DESCRIP-->
                            <?php if($item->available): ?>
                            <div class="info"> 
                                <span><em></em>Available</span>
                                <p>Ready to go!</p>
                            </div><!--INFO--> 
                            <?php else: ?>
                            <div class="info"> 
                                <span><em></em>Unavailable</span>
                                <p>There is a problem</p>
                            </div><!--INFO--> 
                            <?php endif ?>
                        </div><!--HEADER-->
                        <div class="details">                        
                            <div class="item last">
                                <strong>Price not charged</strong>
                                <div class="edit">Check the prices when you get there</div>
                            </div><!--LAST-->
                        </div><!--DETAILS-->
                        <?php endforeach ?>
                    </div><!--CHECKOUT_ACCORDION-->
                    <div class="terms">
                    	<label><input type="checkbox" name="bookings[<?= $item->id ?>][terms]" value="1" class="termscheck" />
                    	I agree to the cancellation policy, hotel restrictions and <a target="_blank" href="/terms">terms of use.</a></label>
                    </div><!--TERMS-->
                    <input type="hidden" name="userid" value="<?= $this->user->id ?>" />
                    <input type="hidden" name="ids" value="<?= $this->trip->id ?>" />
                    <input type="hidden" name="token" value="<?= $this->trip->token ?>" />
                    <input type="hidden" name="_task" value="<?= md5('proceed') ?>" class="proceed" />
                    <input type="hidden" name="_task" value="<?= md5('recalculate') ?>" class="recalculate" disabled="disabled" />
                </form>
            </div><!--LEFT_BLOCK-->
            
            <div class="right_block">
                <h5>Trip Details</h5>
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                		<?php foreach($this->items as $item): ?>
                		<?php if($item->available): ?>
                		<tr>
                			<td width="200" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'"><a href="#"><em><?= $item->listing_title ?></em></a></td>
                			<td width="75" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'" valign="middle"><span>$<?= $item->total ?></span></td>
                		</tr>
                		<?php elseif($item->available === false): ?>
                		
                		<tr>
                			<td width="200" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'"><a href="#"><em><?= $item->listing_title ?></em></a></td>
                			<td width="75" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'" valign="middle"><span>Not available</span></td>
                		</tr>
                		<?php else: ?>
                		
                		<tr>
                			<td width="200" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'"><a href="#"><?= $item->listing_title ?></a></td>
                			<td width="75" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'" valign="middle"><span>Not ready</span></td>
                		</tr>
                		<?php endif ?> 
                		<?php endforeach ?>
                		<?php foreach($this->items2 as $item): ?>
                		
                		<tr>
                			<td width="200" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'"><a href=""><em><?= $item->listing_title ?></em></a></td>
                			<td width="75" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'" valign="middle"><span>Not charged</span></td>
                		</tr>
                		<?php endforeach ?>
                	</table>
                <div class="clear"></div>
                <div class="bottom"> <a href="" class="btn-1">Okay, continue</a>
                    <p>Grand Total<strong>$<?= $this->bigtotal ?></strong></p>
                </div><!--BOTTOM--> 
            </div><!--RIGHT_BLOCK--> 
        </div><!--CUSTOM_CHECKOUT--> 
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/trips/checkprices.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('a.helptip').click(function() {
			$('.tip').toggleClass('hidden');
			return false
		});
		$("#checkout_accordion").accordion({
			autoHeight: false,
			collapsible: true,
			header:'.active'
		});
	});
</script>
<style type="text/css">
#custom_checkout .details .item.last {
	border-bottom:0px none;}
</style>
</body>
</html>