<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->trip->title ?> - Check Availability and Price | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" media="screen" />
    <link type="text/css" rel="stylesheet" href="/css2/calendar/jquery-ui-1.8.16.custom.css?v=<?= $this->cssVC ?>" />
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 8]><link type="text/css" rel="stylesheet" href="/css2/ie8.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <!--[if IE 9]><link type="text/css" rel="stylesheet" href="/css2/ie9.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <style type="text/css">
	.checkout-item .restricction_tip {					
		right: -170px !important;
		top: -215px !important;
		z-index:20 !important;
	}
	#custom_checkout .details .item {
		overflow:visible !important;
	}
	#checkout_accordion {
		overflow:visible !important;}
	#custom_checkout .right_block table tr.hover td,
	#custom_checkout .right_block table tr.active td {
		background-color: #303030;
		color:#fff !important;
	}
	#custom_checkout .right_block table tr.hover a,
	#custom_checkout .right_block table tr.hover span,
	#custom_checkout .right_block table tr.active a,
	#custom_checkout .right_block table tr.active span {
		color: #FFF;
		text-decoration: none;
	}
	#custom_checkout .header.hover {
		background:url(https://static.tripfab.com/images2/g_67.png) repeat-x 0 -1px #f0f9ff;
	}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>
    <div class="w2">
        <div class="checkout_headerB">
            <h2><?= $this->trip->title ?></h2>
            <span class="place"><?= $this->country->title ?></span> 
            <span class="label"><em></em><?= $this->trip->days ?> <?= ($this->trip->days > 1) ? 'Days' : 'Day' ?> Trip</span> 
        </div><!--CHECKOUT_HEADERB-->
        <div class="wrapper" id="custom_checkout"> 
            <div class="left_block">
                <h3>Check the availability for your trip and the listing options before continue with the checkout</h3>
                <form method="post" action="" id="checkprices_form">
                    <div id="checkout_accordion">
                        <?php foreach($this->items as $kkk => $item): ?>
                        <?php if($item->available || ($item->available === 0)): ?>
                        <div rel="#itm<?=$kkk ?>" id="itmBig<?= $kkk ?>" class="header active">
                            <span class="arrow"></span> 
                            <a href="#"></a>
                            <div class="descrip"> 
                                <?= $this->thumbnail(49, $item->listing_image, '', '1:1'); ?>
                                <h4><?= $item->listing_title ?></h4>
                                <a href="/<?= $item->coidf ?>/<?= $item->ciidf ?>/<?= $item->idf ?>" 
                                class="type">View <?= $this->types[$item->listing_type]['name'] ?></a>
                                <p><?= $item->listing_city ?>, <?= $item->listing_country ?></p>
                            </div><!--DESCRIP-->
                            <?php if($item->available): ?>
                            <div class="info"> 
                                <span><em></em>Available</span>
                                <p>Ready to go</p>
                            </div><!--INFO--> 
                            <?php else: ?>
                            <div class="info"> 
                                <span><em></em>Available</span>
                                <p>Click to confirm details</p>
                            </div><!--INFO--> 
                            <?php endif ?>
                        </div><!--HEADER-->
                        <div class="details">
                            <?php if(!$item->available): ?>
                            <div class="warning"><?= $item->error ?></div><!--WARNING-->
                            <?php endif ?>
                            <div class="item"> 
                                <strong>Occupation</strong>
                                <div class="edit">
                                    <label for="adults">Adults</label>
                                    <select name="bookings[<?= $item->id ?>][adults]" id="adults">
                                        <?php for($i=1; $i<=12; $i++): ?>
                                        <?php $selected = ($i == $item->adults) ? 'selected="selected"' : ''; ?>
                                        <option <?= $selected ?> value="<?= $i ?>"><?= $i ?></option>
                                        <?php endfor ?>
                                    </select>
                                    <label for="Children">Children</label>
                                    <select name="bookings[<?= $item->id ?>][kids]" id="Children">
                                        <?php for($i=0; $i<=12; $i++): ?>
                                        <?php $selected = ($i == $item->kids) ? 'selected="selected"' : ''; ?>
                                        <option <?= $selected ?> value="<?= $i ?>"><?= $i ?></option>
                                        <?php endfor ?>
                                    </select>
                                </div><!--EDIT--> 
                                <div class="clear"></div>
                            </div><!--ITEM-->
                            <?php if($item->listing_type == 5): ?>
                            <div class="item"> 
                                <strong>Check In</strong>
                                <div class="edit"><?= date('L, F jS, Y', strtotime($item->checkin)) ?></div>
                                <div class="clear"></div>
                            </div><!--ITEM-->
                            <div class="item"> 
                                <strong>Check Out</strong>
                                <div class="edit"><?= date('L, F jS, Y', strtotime($item->checkout)) ?></div><!--EDIT--> 
                                <div class="clear"></div>
                            </div><!--ITEM-->
                            <div class="item"> 
                                <strong>Rooms</strong>
                                <div class="edit"><?= $item->rooms ?></div><!--EDIT--> 
                                <div class="clear"></div>
                            </div><!--ITEM-->
                            <?php if(isset($this->options[$item->id]['options']) && 
                                    (count($this->options[$item->id]['options'] > 0))): ?>
                            <div class="item"> 
                                <strong>Room Type</strong>
                                <div class="room-type">
                                    <p>Select the room type you want to stay:</p>
                                    <?php foreach($this->options[$item->id]['options'] as $room): ?>
                                    <div class="single">
                                        <label for="Room1">
                                            <?php $checked = ($item->option_id == $room->schedule_id) ? 'checked="checked"' : ''; ?>
                                            <strong><input <?= $checked ?> type="radio" name="bookings[<?= $item->id ?>][option]" 
                                            id="Room1" value="<?= $room->schedule_id ?>" /><?= $room->name ?></strong> 
                                            <span><?= $room->description ?></span>
                                        </label>
                                        <span class="price">$<?= $this->formatnumber($this->options[$item->id]['prices'][$room->schedule_id]['price']) ?></span> 
                                    </div><!--SINGLE-->
                                    <?php endforeach ?>
                                </div><!--ROOM-TYPE--> 
                                <div class="clear"></div>
                            </div><!--ITEM-->
                            <?php endif ?>
                            <?php else: ?>
                            <div class="item"> 
                                <strong>Activity Date</strong>
                                <div class="edit"><?= date('L, F jS, Y', strtotime($item->checkin)) ?></div><!--EDIT--> 
                                <div class="clear"></div>
                            </div><!--ITEM-->
                            <div class="item"> 
                                <strong>Activity Type</strong>
                                <div class="room-type">
                                    <p>Select the capacity type that must fit your needs:</p>
                                    <?php if((is_null($item->listing_min) or is_null($item->listing_max)) &&
                                            (count($this->options[$item->id]['capacity']) > 0)): ?>
                                    <?php foreach($this->options[$item->id]['capacity'] as $option): ?>
                                    <div class="single">
                                        <?php $checked = (isset($item->option_id) && ($item->option_id == $option->id)) ? 'checked="checked"' : '' ?>
                                       <label for="activity1">
                                            <strong><input type="radio" name="bookings[<?= $item->id ?>][capacity]" 
                                            value="<?= $option->id ?>" <?= $checked ?> /><?= $option->name ?></strong>
                                            <span>Minimun: <?= (!is_null($option->min)) 
                                                                            ? ($option->min == 1) 
                                                                                ? '1 person' 
                                                                                : $option->min .' people'  
                                                                            : 'Not defined'  ?>
                                            Maximun: <?= (!is_null($option->max)) 
                                                                            ? ($option->max == 1) 
                                                                                ? '1 person' 
                                                                                : $option->max .' people'  
                                                                            : 'Not defined'  ?></span>
                                       </label>
                                       <span class="price">$<?= $this->formatnumber($this->options[$item->id]['prices'][$option->id]['price']) ?></span> 
                                    </div><!--SINGLE-->
                                    <?php endforeach ?>
                                    <?php else: ?>
                                    <div class="single">
                                       <label for="activity1"> 
                                       <strong><input checked="checked" type="radio" name="bookings[<?= $item->id ?>][capacity]" value="single" />
                                       Single Capacity</strong>
                                       <span>Minimun: <?= (!is_null($item->listing_min)) 
                                                                        ? ($item->listing_min == 1) 
                                                                            ? '1 person' 
                                                                            : $item->listing_min .' people'  
                                                                        : 'Not defined'  ?>
                                        Maximun: <?= (!is_null($item->listing_max)) 
                                                                        ? ($item->listing_max == 1) 
                                                                            ? '1 person' 
                                                                            : $item->listing_max .' people'  
                                                                        : 'Not defined'  ?></span>
                                       </label><span class="price">$<?= $this->formatnumber($item->listing_price) ?></span>
                                    </div><!--SINGLE-->
                                    <?php endif ?>
                                </div><!--ROOM-TYPE--> 
                                <div class="clear"></div>
                            </div><!--ITEM-->
                            <div class="item"> 
                                <strong>Schedule</strong>
                                <?php if(count($this->options[$item->id]['options']) > 0): ?>
                                <div class="edit">
                                    <select name="bookings[<?= $item->id ?>][option]">
                                        <?php foreach($this->options[$item->id]['options'] as $sch): ?>
                                        <?php $selected = ((isset($item->schedule_id)) && ($item->schedule_id == $sch->id)) ? 'selected="selected"' : '' ?>
                                        <option <?= $selected ?> value="<?= $sch->id ?>"><?= $sch->name ?> (<?= date('h:i a',strtotime($sch->starting)) ?> - 
                                        <?= date('h:i a',strtotime($sch->ending)) ?>)</option>
                                        <?php endforeach ?>
                                    </select>
                                </div><!--EDIT--> 
                                <?php else: ?>
                                <div class="edit">
                                    Flexible Schedule. You choose the hour
                                    <input type="hidden" name="bookings[<?= $item->id ?>][option]" value="flex" />
                                </div>
                                <?php endif ?>
                                <div class="clear"></div>
                            </div><!--ITEM-->
                            <?php endif ?>
                            <?php if($item->available): ?>
                            <div class="item">
                                <strong>Rate</strong>
                                <div class="edit">
                                    $<?= $item->rate ?>, <?= $item->rate_description ?>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <?php if(isset($item->additional) and $item->additional > 0): ?>
                            <div class="item">
                                <strong>Additional</strong>
                                <div class="edit">
                                    $<?= $item->additional ?>, <?= $item->additional_description ?>
                                </div>
                                <div class="clear"></div>
                            </div>                        
                            <?php endif ?>
                            <div class="item">
                            	<strong>Taxes</strong>
                                <div class="edit">
                                	$<?= $item->taxes ?>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="item">
                            	<strong>Total</strong>
                                <div class="edit">
                                	$<?= $this->formatnumber($item->total) ?>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <?php endif ?>
                            
                            <?php switch($item->policy): case 1: ?>
                             <div class="checkout-item item"> 
                                <strong>Cancellation</strong> 
                                <a href="#cancel_policy_<?= $kkk ?>" class="high-r lb restriction">Low Restrictions &rarr;</a> 
								<?php if($item->listing_type == 5): ?>
                                <div id="restricction_tip_<?= $kkk ?>" class="restricction_tip hidden">
                                    <strong>Full refund 1 day prior to arrival, except fees</strong>
                                    <ul>
                                        <li>• Cleaning fees are always refunded if the guest did not check in</li>
                                        <li>• The Tripfab service fee is refundable.</li>
                                        <li>• If there is a complaint from either party, notice must be given to Tripfab 
                                        Resolution Center within 24 hours of check-in</li>
                                        <li>• Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                        <li>• A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                        e-mail from Tripfab Resolution Center.</li>
                                    </ul>
                                    <span></span>
                                </div><!--RESTRICCTION_TIP-->
                                <div class="hidden">
                                    <div id="cancel_policy_<?= $kkk ?>" class="cancel_policy lb">
                                        <div class="top">Low Restrictions Cancellation Policy</div>
                                        <div class="mid">
                                            <h3>Full refund 1 day prior to arrival, except fees</h3>
                                            <ul>
                                                <li>Cleaning fees are always refunded if the guest did not check in</li>
                                                <li>The Tripfab service fee is refundable.</li>
                                                <li>If there is a complaint from either party, notice must be given to Tripfab 
                                                Resolution Center within 24 hours of check-in</li>
                                                <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                                <li>A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                                e-mail from Tripfab Resolution Center.</li>
                                            </ul>
                                            <div class="inner">
                                                <img src="https://static.tripfab.com/images2/img-65-hotel.png" alt="" />
                                                <div class="specs">
                                                    <div class="column">
                                                        <p>Must be made a full 24 hours prior to listing's local check in time (or 2:00 PM 
                                                        if not specified) on the day of check in. For example, if check-in is on Friday, 
                                                        cancel by Thursday of that week before check in time.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="column">
                                                        <p>If the guest cancels less than 24 hours before check-in, the first night is non-refundable.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="column last">
                                                        <p>If the guest arrives and decides to leave early, the nights not spent 24 hours after 
                                                        the official cancellation are 100% refunded.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="clear"></div>
                                                </div><!--SPECS-->
                                            </div><!--INNER-->
                                        </div><!--MID-->
                                    </div><!--CANCEL_POLICY-->
                                </div>
                                <?php else: ?>
                                <div id="restricction_tip_<?= $kkk ?>" class="restricction_tip hidden">
                                    <strong>Full refund 1 day prior to arrival, except fees</strong>
                                    <ul>
                                        <li>• The Tripfab service fee is refundable.</li>
                                        <li>• If there is a complaint from either party, notice must be given to Tripfab 
                                        Resolution Center within 24 hours of the tour activity.</li>
                                        <li>• Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                        <li>• A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                        e-mail from Tripfab Resolution Center.</li>
                                    </ul>
                                    <span></span>
                                </div><!--RESTRICCTION_TIP-->
                                <div class="hidden">
                                    <div id="cancel_policy_<?= $kkk ?>" class="cancel_policy lb">
                                        <div class="top">Low Restrictions Cancellation Policy</div>
                                        <div class="mid">
                                            <h3>Full refund 1 day prior to arrival, except fees</h3>
                                            <ul>
                                                <li>The Tripfab service fee is refundable.</li>
                                                <li>If there is a complaint from either party, notice must be given to Tripfab 
                                                Resolution Center within 24 hours of the tour activity.</li>
                                                <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                                <li>A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                                e-mail from Tripfab Resolution Center.</li>
                                            </ul>
                                            <div class="inner">
                                                <img src="https://static.tripfab.com/images2/img-65.png" width="    " height="" alt="" />
                                                <div class="specs">
                                                    <div class="column">
                                                        <p>Must be made 24 hours prior to listing's local arriving time on the day when the tour begins,
                                                        otherwise no refund. For example, if the tour starts on Friday at 9:00 AM, the cancellation 
                                                        must be requested before 9:00 AM of the Thursday before.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="column">
                                                        <p>If the guest cancels less than 24 hours before the tour starts, the tour cost is not refunded.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="column last">
                                                        <p>If the visitor arrives and decides to leave early, or not take the tour, the cost of the 
                                                        tour is 100% refunded.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="clear"></div>
                                                </div><!--SPECS-->
                                            </div><!--INNER-->
                                        </div><!--MID-->
                                    </div><!--CANCEL_POLICY-->
                                </div>                            
                                <?php endif ?>
                                <div class="clear"></div>
                            </div><!--ITEM-->
							<?php break; case 2: ?>
                             <div class="checkout-item item"> 
                                <strong>Cancellation</strong> 
                                <a href="#cancel_policy_<?= $kkk ?>" class="high-r lb restriction">Medium Restrictions &rarr;</a> 
								<?php if($item->listing_type == 5): ?>
                                <div id="restricction_tip_<?= $kkk ?>" class="restricction_tip hidden">
                                    <strong>Full refund 3 days prior to arrival, except fees</strong>
                                    <ul>
                                        <li>• Cleaning fees are always refunded if the guest did not check in.
                                        <li>• The Tripfab service fee is refundable.</li></li>
                                        <li>• If there is a complaint from either party, notice must be given to 
                                        Tripfab Resolution Center within 24 hours of check-in.</li>
                                        <li>• Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                        <li>• A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                        e-mail from Tripfab Resolution Center.</li>
                                    </ul>
                                    <span></span>
                                </div><!--RESTRICCTION_TIP-->  
                                <div class="hidden">
                                    <div id="cancel_policy_<?= $kkk ?>" class="cancel_policy lb">
                                        <div class="top">Medium Restrictions Cancellation Policy</div>
                                        <div class="mid">
                                            <h3>Full refund 3 days prior to arrival, except fees</h3>
                                            <ul>
                                                <li>Cleaning fees are always refunded if the guest did not check in.
                                                <li>The Tripfab service fee is refundable.</li></li>
                                                <li>If there is a complaint from either party, notice must be given to 
                                                Tripfab Resolution Center within 24 hours of check-in.</li>
                                                <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                                <li>A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                                e-mail from Tripfab Resolution Center.</li>
                                            </ul>
                                            <div class="inner">
                                                <img src="https://static.tripfab.com/images2/img-66-hotel.png" width="    " height="" alt="" />
                                                <div class="specs">
                                                    <div class="column">
                                                        <p>Must be made three full days prior to listing's local check in time (or 2:00 PM if not specified) on the day of check in. For example, if check-in is on Friday, cancel by the previous Tuesday before check in time.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="column">
                                                        <p>If the guest cancels less than 3 days in advance, the first night is 
                                                        non-refundable but the remaining nights will be 50% refunded.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="column last">
                                                        <p>If the guest arrives and decides to leave early, the nights not spent 24 hours 
                                                        after the cancellation occurs are 50% refunded.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="clear"></div>
                                                </div><!--SPECS-->
                                            </div><!--INNER-->
                                        </div><!--MID-->
                                    </div><!--CANCEL_POLICY-->
                                </div>
                                <?php else: ?>
                                <div id="restricction_tip_<?= $kkk ?>" class="restricction_tip hidden">
                                    <strong>Full refund 3 days prior to arrival, except fees</strong>
                                    <ul>
                                        <li>• The Tripfab service fee is refundable.</li></li>
                                        <li>• If there is a complaint from either party, notice must be given to 
                                        Tripfab Resolution Center within 24 hours of the tour activity</li>
                                        <li>• Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                        <li>• A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                        e-mail from Tripfab Resolution Center.</li>
                                    </ul>
                                    <span></span>
                                </div><!--RESTRICCTION_TIP-->  
                                <div class="hidden">
                                    <div id="cancel_policy_<?= $kkk ?>" class="cancel_policy lb">
                                        <div class="top">Medium Restrictions Cancellation Policy</div>
                                        <div class="mid">
                                            <h3>Full refund 3 days prior to arrival, except fees</h3>
                                            <ul>
                                                <li>The Tripfab service fee is refundable.</li></li>
                                                <li>If there is a complaint from either party, notice must be given to 
                                                Tripfab Resolution Center within 24 hours of the tour activity</li>
                                                <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                                <li>A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                                e-mail from Tripfab Resolution Center.</li>
                                            </ul>
                                            <div class="inner">
                                                <img src="https://static.tripfab.com/images2/img-66.png" />
                                                <div class="specs">
                                                    <div class="column">
                                                        <p>Must be made three full days prior to listing's local arriving time on the day when the 
                                                        tour begins, otherwise no refund. For example, if the tour starts on Friday at 9:00 AM, the
                                                        cancellation must be requested before 9:00 AM of the previous Tuesday.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="column">
                                                        <p>If the visitor cancels less than 3 days in advance, 50% of the tour cost will be refunded.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="column last">
                                                        <p>If the visitor arrives and decides to leave early, or not take the tour, the cost of the 
                                                        tour is 50% refunded.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="clear"></div>
                                                </div><!--SPECS-->
                                            </div><!--INNER-->
                                        </div><!--MID-->
                                    </div><!--CANCEL_POLICY-->
                                </div>
                                <?php endif ?>
                                <div class="clear"></div>
                            </div><!--ITEM-->
                            <?php break; default: ?>
                             <div class="checkout-item item"> 
                                <strong>Cancellation</strong> 
                                <a href="#cancel_policy_<?= $kkk ?>" class="high-r lb restriction">High Restrictions &rarr;</a> 
								<?php if($item->listing_type == 5): ?>
                                <div id="restricction_tip_<?= $kkk ?>" class="restricction_tip hidden">
                                    <strong>50% refund up until 1 week prior to arrival, except fees</strong>
                                    <ul>
                                        <li>• Cleaning fees are always refunded if the guest did not check in.</li>
                                        <li>• The Tripfab service fee is non-refundable.</li>
                                        <li>• If there is a complaint from either party, notice must be given to Tripfab 
                                        Resolution Center within 24 hours of check-in.</li>
                                        <li>• Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                        <li>• A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                        e-mail from Tripfab Resolution Center.</li>
                                    </ul>
                                    <span></span>
                                </div><!--RESTRICCTION_TIP-->    
                                <div class="hidden">
                                    <div id="cancel_policy_<?= $kkk ?>" class="cancel_policy lb">
                                        <div class="top">High Restrictions Cancellation Policy</div>
                                        <div class="mid">
                                            <h3>50% refund up until 1 week prior to arrival, except fees</h3>
                                            <ul>
                                                <li>Cleaning fees are always refunded if the guest did not check in.</li>
                                                <li>The Tripfab service fee is non-refundable.</li>
                                                <li>If there is a complaint from either party, notice must be given to Tripfab 
                                                Resolution Center within 24 hours of check-in.</li>
                                                <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                                <li>A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                                e-mail from Tripfab Resolution Center.</li>
                                            </ul>
                                            <div class="inner">
                                                <img src="https://static.tripfab.com/images2/img-67-hotel.png" width="    " height="" alt="" />
                                                <div class="specs">
                                                    <div class="column">
                                                        <p>Must be made seven full days prior to listing's local check in time (or 2:00 PM 
                                                        if not specified) on the day of check in, otherwise no refund. For example, 
                                                        if check-in is on Friday, cancel by Friday of the previous</p>
                                                    </div><!--COLUMN-->
                                                    <div class="column">
                                                        <p>If the guest cancels less than 7 days in advance, the nights not spent are not refunded.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="column last">
                                                        <p>If the guest arrives and decides to leave early, the nights not spent are not refunded.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="clear"></div>
                                                </div><!--SPECS-->
                                            </div><!--INNER-->
                                        </div><!--MID-->
                                    </div><!--CANCEL_POLICY-->
                                </div>                    
                                <?php else: ?>
                                <div id="restricction_tip_<?= $kkk ?>" class="restricction_tip hidden">
                                    <strong>50% refund up until 1 week prior to arrival, except fees</strong>
                                    <ul>
                                        <li>• Cleaning fees are always refunded if the guest did not arrive to the meeting point.</li>
                                        <li>• The Tripfab service fee is non-refundable.</li>
                                        <li>• If there is a complaint from either party, notice must be given to Tripfab 
                                        Resolution Center within 24 hours of check-in.</li>
                                        <li>• Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                        <li>• A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                        e-mail from Tripfab Resolution Center.</li>
                                    </ul>
                                    <span></span>
                                </div><!--RESTRICCTION_TIP-->    
                                <div class="hidden">
                                    <div id="cancel_policy_<?= $kkk ?>" class="cancel_policy lb">
                                        <div class="top">High Restrictions Cancellation Policy</div>
                                        <div class="mid">
                                            <h3>50% refund up until 1 week prior to arrival, except fees</h3>
                                            <ul>
                                                <li>Cleaning fees are always refunded if the guest did not arrive to the meeting point.</li>
                                                <li>The Tripfab service fee is non-refundable.</li>
                                                <li>If there is a complaint from either party, notice must be given to Tripfab 
                                                Resolution Center within 24 hours of check-in.</li>
                                                <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                                <li>A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                                e-mail from Tripfab Resolution Center.</li>
                                            </ul>
                                            <div class="inner">
                                                <img src="https://static.tripfab.com/images2/img-67.png" width="    " height="" alt="" />
                                                <div class="specs">
                                                    <div class="column">
                                                        <p>Must be made seven full days prior to listing's local arriving time on the day when the 
                                                        tour begins, otherwise no refund. For example, if the tour starts on Friday at 9:00 AM, the 
                                                        ancellation must be requested before 9:00 AM of the previous Friday.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="column">
                                                        <p>If the visitor cancels less than 7 days in advance, the cost of the tour is not refunded.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="column last">
                                                        <p>If the visitor arrives and decides to leave early, or not take the tour, the cost of the 
                                                        tour is not refunded.</p>
                                                    </div><!--COLUMN-->
                                                    <div class="clear"></div>
                                                </div><!--SPECS-->
                                            </div><!--INNER-->
                                        </div><!--MID-->
                                    </div><!--CANCEL_POLICY-->
                                </div>           
                                <?php endif ?>  
                                <div class="clear"></div>  
                            </div><!--ITEM-->
                            <?php endswitch ?>
                            <?php if($item->listing_type == 5): ?>
                            <div class="last"> 
                                <strong>Hotel Restrictions</strong> 
                                <a href="/ajax/restrictions/<?= $item->id ?>" class="lb restriction">Read Hotel Restrictions &rarr;</a> 
                            </div><!--ITEM-->
                            <?php else: ?>
                            <div class="last"> 
                                <strong>Activity Restrictions</strong> 
                                <a href="/ajax/restrictions/<?= $item->id ?>" class="lb restriction">Read Activity Restrictions &rarr;</a> 
                            </div><!--ITEM-->
                            <?php endif ?>
                        </div><!--DETAILS-->
                        <?php else: ?>
                        <div rel="#itm<?=$kkk ?>" id="itmBig<?= $kkk ?>" class="header inactive"> 
                            <span class="arrow"></span> 
                            <a href="#"></a>
                            <div class="descrip"> 
                                <?= $this->thumbnail(49, $item->listing_image, '', '1:1'); ?>
                                <h4><?= $item->listing_title ?></h4>
                                <a href="/<?= $item->coidf ?>/<?= $item->ciidf ?>/<?= $item->idf ?>" 
                                class="type">View <?= $this->types[$item->listing_type]['name'] ?></a>
                                <p><?= $item->listing_city ?>, <?= $item->listing_country ?></p>
                            </div><!--DESCRIP-->
                            <div class="info">
                                <span class="unavaible"><em></em>Not Available</span>
                                <p class="recommendation">
                                <a href="/ajax/getrecomendations/<?= $item->id ?>?trip=<?= $this->trip->id ?>&listing=<?= $item->triplistingid ?>" class="link-10 lb">See Recommendations</a></p>
                            </div><!--INFO-->
                        </div><!--HEADER-->
                        <?php endif ?>
                        <?php endforeach ?>
                        <?php foreach($this->items2 as $kkk => $item): ?>
                        <div rel="#itm2<?=$kkk ?>" id="itmBig2<?= $kkk ?>" class="header active"> <span class="arrow"></span> <a href="#"></a>
                            <div class="descrip"> 
                                <?= $this->thumbnail(49, $item->listing_image, '', '1:1'); ?>
                                <h4><?= $item->listing_title ?></h4>
                                <a href="/<?= $item->coidf ?>/<?= $item->ciidf ?>/<?= $item->idf ?>" 
                                class="type">View <?= $this->types[$item->listing_type]['name'] ?></a>
                                <p><?= $item->listing_city ?>, <?= $item->listing_country ?></p>
                            </div><!--DESCRIP-->
                            <?php if($item->available): ?>
                            <div class="info"> 
                                <span><em></em>Available</span>
                                <p>Ready to go!</p>
                            </div><!--INFO--> 
                            <?php else: ?>
                            <div class="info"> 
                                <span><em></em>Unavailable</span>
                                <p>There is a problem</p>
                            </div><!--INFO--> 
                            <?php endif ?>
                        </div><!--HEADER-->
                        <div class="details">                        
                            <div class="item last">
                                <strong>Price not charged</strong>
                                <div class="edit">Check the prices when you get there</div>
                                <div class="clear"></div>
                            </div><!--LAST-->
                        </div><!--DETAILS-->
                        <?php endforeach ?>
                    </div><!--CHECKOUT_ACCORDION-->
                    <input type="hidden" name="userid" value="<?= $this->user->id ?>" />
                    <input type="hidden" name="ids" value="<?= $this->trip->id ?>" />
                    <input type="hidden" name="token" value="<?= $this->trip->token ?>" />
                    <input type="hidden" name="_task" value="<?= md5('proceed') ?>" class="proceed" />
                    <input type="hidden" name="_task" value="<?= md5('recalculate') ?>" class="recalculate" disabled="disabled" />
                </form>
            </div><!--LEFT_BLOCK-->
            
            <div class="right_block">
                <div class="inf">
                	<h5>Trip Details</h5>
                	<table width="100%" border="0" cellspacing="0" cellpadding="0">
                			<?php foreach($this->items as $kkk => $item): ?>
                			<?php if($item->available): ?>
                			<tr rel="#itmBig<?=$kkk ?>" id="itm<?= $kkk ?>">
                				<td width="200" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'"><a href="#"><em><?= $item->listing_title ?></em></a></td>
                				<td width="75" align="right" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'" valign="middle"><span>$<?= $this->formatnumber($item->total) ?></span></td>
                			</tr>
                			<?php elseif($item->available === false): ?>
                			
                			<tr rel="#itmBig<?=$kkk ?>" id="itm<?= $kkk ?>">
                				<td width="200" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'"><a href="#"><em><?= $item->listing_title ?></em></a></td>
                				<td width="75" align="right" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'" valign="middle"><span>Not available</span></td>
                			</tr>
                			<?php else: ?>
                			
                			<tr rel="#itmBig<?=$kkk ?>" id="itm<?= $kkk ?>">
                				<td width="200" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'"><a href="#"><?= $item->listing_title ?></a></td>
                				<td width="75" align="right" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'" valign="middle"><span>Not ready</span></td>
                			</tr>
                			<?php endif ?> 
                			<?php endforeach ?>
                			<?php foreach($this->items2 as $kkk => $item): ?>
                			
                			<tr rel="#itmBig2<?=$kkk ?>" id="itm2<?= $kkk ?>">
                				<td width="200" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'"><a href=""><em><?= $item->listing_title ?></em></a></td>
                				<td width="75" align="right" class="celdano" onmouseover="className='celdasi'" onmouseout="className='celdano'" valign="middle"><span>Not charged</span></td>
                			</tr>
                			<?php endforeach ?>
                		</table>
                	<div class="clear"></div>
                </div>
                
                <div class="terms">
                	<label><input type="checkbox" name="bookings[terms]" value="1" class="termscheck" />
                	<span>I agree to the cancellation policy, hotel restrictions and <a target="_blank" href="/terms">terms of use.</a></span></label>
                </div><!--TERMS-->	
                
                <div class="bottom"> <a href="" class="btn-1">Okay, continue</a>
                    <p>Grand Total<strong>$<?= $this->formatnumber($this->bigtotal) ?></strong></p>
                </div><!--BOTTOM--> 
                
            </div><!--RIGHT_BLOCK--> 
        </div><!--CUSTOM_CHECKOUT--> 
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript" src="/js2/trips/checkprices.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$('a.helptip').click(function() {
			$('.tip').toggleClass('hidden');
			return false
		});
		
		$('.header .descrip a.type').click(function(e){
			e.preventDefault();
			window.location.href = $(this).attr('href');
			return false;
		}); 
		$("#checkout_accordion").accordion({
			active:false,
			autoHeight:false,
			collapsible:true,
			header:'.active',
			changestart: function(event, ui) {
				$('.right_block table tr').removeClass('active');
				$(ui.newHeader.attr('rel')).addClass('active');
			}
		});
		$('a.high-r').hover(function() {
			$parent = $(this).parents('.details');
			$('.restricction_tip', $parent).toggleClass('hidden');
			return false;
		});
		
		$('#checkprices_form .header').hover(function(){
			$($(this).attr('rel')).toggleClass('hover');
		});
		
		$('.right_block table tr').hover(function(){
			$($(this).attr('rel')).toggleClass('hover');
		});
		
		$('.right_block table tr').click(function(){
			$($(this).attr('rel')).click();
			return false;
		});
	});
</script>
<style type="text/css">
#custom_checkout .details .item.last {
	border-bottom:0px none;}
#custom_checkout .header .type { display:inline;}
</style>
</body>
</html>