<div class="footer black">
	<div class="wrapper">
		<a href="" class="logo">Tripfab</a>
	</div><!--WRAPPER-->
</div><!-- closes footer -->
<div class="hidden">
	<div class="lb mark_paid" id="markPaid">
		<div class="top">Mark as Paid</div><!--TOP-->
		<form method="post" action="">
			<fieldset>
				<div class="cont">
					<p>Are you sure to mark Green Expeditions as paid?</p>
				</div><!--CONT-->
				<div class="bottom">
					<a href="" class="btn-1">Mark as Paid</a>
					<a href="" class="btn-10">Cancel</a>
				</div><!--BOTTOM-->
			</fieldset>
		</form>
	</div><!--ACTIVATE--> 
    
	<div id="new_partner" class="lb">
    	<form name="partner-form" id="partner-form">
		<div class="top"><h3>Create Partner Account</h3></div><!--TOP-->
		<div class="cont">
			<ul>
				<li>
                	<label>Company Name</label>
                    <input type="text" name="c_name" value="" />
                </li>
                <li> <div id="_c_name" class="errdiv" style="float:right; margin-right:30px; background: none repeat scroll 0 0 #FF0000; color: #FFFFFF;font-size: 10px;font-weight: bold; display:none"></div></li>
				<li><label>Company E-mail</label><input type="text" value="" name="c_email" /></li>
                <li> <div class="errdiv" id="_c_email" style="float:right; margin-right:30px; background: none repeat scroll 0 0 #FF0000; color: #FFFFFF;font-size: 10px;font-weight: bold; display:none"></div></li>
				<li><label>Contact Name</label><input type="text" value="" name="cnt_name"/></li>
                <li> <div class="errdiv" id="_cnt_name" style="float:right; margin-right:30px; background: none repeat scroll 0 0 #FF0000; color: #FFFFFF;font-size: 10px;font-weight: bold; display:none"></div></li>
				<li><label>Phone</label><input type="text" value="" class="code" name="phone"/><input type="text" value="" class="phone" /></li>
                <li> <div class="errdiv" id="_phone" style="float:right; margin-right:30px; background: none repeat scroll 0 0 #FF0000; color: #FFFFFF;font-size: 10px;font-weight: bold; display:none"></div></li>
				<li><label>Website</label><input type="text" value="" name="website" /></li>
                <li> <div class="errdiv" id="_website" style="float:right; margin-right:30px; background: none repeat scroll 0 0 #FF0000; color: #FFFFFF;font-size: 10px;font-weight: bold; display:none"></div></li>
				<li>
					<label>Country</label>
					<select name="country">
                    <option value="">Select Country</option>
					<?php foreach($this->countries as $country): ?>
                        <option value="<?php echo $country->id?>"><?php echo $country->title?></option>
					 <?php endforeach; ?>
					</select>
				</li>
                 <li> <div class="errdiv" id="_country" style="float:right; margin-right:30px; background: none repeat scroll 0 0 #FF0000; color: #FFFFFF;font-size: 10px;font-weight: bold; display:none"></div></li>

			</ul>
		</div><!--CONT-->
		<div class="bottom">
			<input type="button" id="c-vendor" class="btn-1" value="Create Account" onclick="/admin/users/venders/" />
			<a class="btn-10" onclick="$.fancybox.close()">Cancel</a>
		</div><!--BOTTOM-->
		</form>
    </div><!--NEW_PARTNER-->
    
    <div class="lightbox-2" id="password-reset">
    	<h2>Reset Password</h2>
    	<h3>Do you want to reset the password to Karina Romaine</h3>
    	<div class="buttons">
    		<ul>
    			<li><a href="" class="btn-1">Reset</a></li>
    			<li><a href="" class="btn-10">Cancel</a></li>
    		</ul>
    	</div><!--BUTTONS-->
    </div><!--PASSWORD-RESET-->
</div><!--HIDDEN-->