<div class="big-message green">
    <div class="wrapper"><img src="/images2/cleardot.gif" alt=""> 
    <span>Your changes have been saved!</span></div><!-- closes wrapper -->
</div>

			<div id="header">
				<div class="wrapper">
					<h1 class="logo_icon"><a href="">Tripfab</a></h1>
					<ul class="menu_admin">
						<li><a href="/admin/listings" <?php echo @$GLOBALS['menuContext'] == 1 ? 'class="active"' : '' ?>>Listings <img alt="" src="/images/cleardot.gif"></a>
							<ul>
								<li><a href="/admin/listings/all">All Listings</a></li>
								<li><a href="/admin/listings/activities">Activities</a></li>
								<li><a href="/admin/listings/hotels">Hotels</a></li>
								<li><a href="/admin/listings/restaurants">Restaurants</a></li>
								<li><a href="/admin/listings/entertainments">Entertainments</a></li>
								<li><a href="/admin/listings/tourist">Tourist Sights</a></li>
							</ul>
						</li>
						<li class="single"><a href="/admin/trips" <?php echo @$GLOBALS['menuContext'] == 2 ? 'class="active"' : '' ?>>Trips</a></li>
						<li><a href="/admin/places" <?php echo @$GLOBALS['menuContext'] == 3 ? 'class="active"' : '' ?>>Places<img alt="" src="/images/cleardot.gif"></a>
							<ul>
								<li><a href="/admin/places/regions">Regions</a></li>
								<li><a href="/admin/places/countries">Countries</a></li>
								<li><a href="/admin/places/cities">Cities</a></li>
							</ul>
                         </li>
						<li><a href="/admin/users" <?php echo @$GLOBALS['menuContext'] == 4 ? 'class="active"' : '' ?>>Users<img alt="" src="/images/cleardot.gif"></a>
							<ul>
								<li><a href="/admin/users/travellers">Travelers</a></li>
								<li><a href="/admin/users/partners">Partners</a></li>
							</ul>
                        </li>
						<li><a href="/admin/payments" <?php echo @$GLOBALS['menuContext'] == 5 ? 'class="active"' : '' ?>>Payments<img alt="" src="/images/cleardot.gif"></a>
							<ul>
								<li><a href="/admin/payments/pending">Pending to Pay</a></li>
								<li><a href="/admin/payments/history">History</a></li>
							</ul>
                        </li>
						<li class="single"><a href="/admin/reservations" <?php echo @$GLOBALS['menuContext'] == 6 ? 'class="active"' : '' ?>>Reservations<img alt="" src="/images/cleardot.gif"></a>
                        	<ul>
								<li><a href="/admin/reservations/all">All Reservations</a></li>
								<li><a href="/admin/reservations/hotels">Hotels</a></li>
								<li><a href="/admin/reservations/activities">Activities</a></li>
							</ul>

                        </li>
						<li class="single"><a id="rpt-link" href="#getReport" class="reports lbc <?php echo @$GLOBALS['menuContext'] == 7 ? 'active' : '' ?>">Reports</a></li>
					</ul>
					<a href="" class="sign_log">Logout</a>
				</div>
				<!-- closes wrapper -->			
			</div>
			<!-- closes header -->
			
