            <div class="hidden">
            
                <div class="lb activation" id="activate">
                <div class="top">Activate Listing </div><!--TOP-->
                <form method="post" action="">
                    <fieldset>
                        <div class="cont">
                            <p>Are you sure activate <?php echo $this->name?>?</p>
                        </div><!--CONT-->
                        <div class="bottom">
                            <a href="javascript://" class="btn-1" id="btn-activate-326">Activate</a>
                            <a href="javascript://" class="btn-10" id="btn-cancel-326">Cancel</a>
                        </div><!--BOTTOM-->
                    </fieldset>
                </form>
            </div><!--ACTIVATE-->
            
            <div class="lb activation" id="deactivate">
                <div class="top">Desactivate Listing </div><!--TOP-->
                <form method="post" action="">
                    <fieldset>
                        <div class="cont">
                            <p>Are you sure deactivate the <?php echo $this->name?>?</p>
                        </div><!--CONT-->
                        <div class="bottom">
                            <a href="javascript://" class="btn-1" id="btn-deactivate-327">Deactivate</a>
                            <a href="javascript://" class="btn-10" id="btn-cancel-327">Cancel</a>
                        </div><!--BOTTOM-->
                    </fieldset>
                </form>
            </div><!--ACTIVATE-->
        
            
            </div><!--HIDDEN-->
            
<script type="text/javascript">
	var listingId = '<?php echo $this->userId?>';
	
	$("#btn-cancel-327").click(function(){
		$.fancybox.close();
	});
	
	$("#btn-cancel-326").click(function(){
		$.fancybox.close();
	});
	$("#btn-activate-326").click(function(){
		changeListingStatus(listingId, 1);
	});
	
	$("#btn-deactivate-327").click(function(){
		changeListingStatus(listingId, 0);
	});
	
	function changeListingStatus(listingId, action){
		$.ajax({ 
		   type: "POST", 
		   url: "/ajax/usertatus/", 
		   data: 'id=' + listingId + '&act=' + action ,
		   success: function(json, status){
				$.fancybox.close();
				if(json=="success"){
					 showAlert("Listing has been updated successfully");
					 if(action==1){
						$("#act-btn-342").hide(); 
						$("#deact-btn-342").show(); 
					 }
					 else{
						$("#act-btn-342").show(); 
						$("#deact-btn-342").hide(); 
					 }
				}
		   }, 
		   error:function(jqXHR, textStatus, errorThrown){ 
				alert(textStatus);
		   }
		});
	}
</script>
