<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Oops, Page Not Found | Tripfab.com</title>
    <link rel="icon" type="image/png" href="/images3/favicon.png" />
    <link type="text/css" rel="stylesheet" href="/css2/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
    <link href="/css6/calendar.css?v=<?= $this->cssVC ?>" rel="stylesheet" type="text/css">
    <!--[if IE 7]><link type="text/css" rel="stylesheet" href="/css2/ie.css?v=<?= $this->cssVC ?>" /><![endif]-->
    <script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
    <script type="text/javascript">
	$(function(){
		$.ajax({
			url:'/ajax/getsearchtags',
			success:function(tags){
				$( "#tags" ).autocomplete({
					source:tags,
					select:function(e, ui){
						window.location = ui.item.url
					},
					appendTo:'#citiesAutocompleteContainerError'
				}).data( "autocomplete" )._renderItem = function( ul, item ) {
					return $( "<li></li>" )
					.data( "item.autocomplete", item )
					.append( '<a href="'+item.url+'">' + item.label + "</a>" )
					.appendTo( ul );
				};
			}
		});
    });	
    $(document).ready(function() {
    	
    	$('#tags').one('click', function() {
    		$('#note1').fadeIn('slow');
    		return false;
    	});
    	$('#tags').keypress(function() {
    		$('#citiesAutocompleteContainer2 ul').css('display', 'block');
    	});
    	$('#tags').keypress("autocompleteclose", function() {
    		$('#note1').fadeOut('fast');
    	});
    	$( "#tags" ).bind( "autocompleteclose", function() {
    		$('#note2').fadeIn('slow');
    	});
    	$( "#tags" ).bind( "autocompleteopen", function() {
    		$('#note2').fadeOut('slow');
    	});
    	$( "#tags" ).focusout(function() {
    		$('#note2').fadeOut('slow');
    		$('#note1').fadeOut('slow');
    	});
    	$( "#tags" ).bind( "autocompleteselect", function() {
    		$('#note2').hide();
    	});
    });
	</script>
</head>
<body>
<div class="w1" id="errorpage">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>
    <div class="w2">
        <div class="top">
            <div> </div>
        </div><!--TOP-->
        <div class="bottom">
            <div class="island"><img src="https://static.tripfab.com/images2/404-island.png"  alt="" /></div>
            <h2>You found a desert Island!</h2>
            <h3>Unfortunately Tripfab can't take you here.</h3>
            <div class="search">
                <form action="">
                    <fieldset>
                        <input type="text" id="tags" value="Where do you want to go?"  />
                        <input type="submit" class="btn-1 noclean" value="Go!" />
                        <div id="citiesAutocompleteContainerError"></div>
                        <div id="note1" class="note"><em></em>
                        	<p class="flag">We have listings only in <strong>Costa Rica</strong>, other countries coming soon.</p>
                        </div><!--NOTE1-->
                        <div id="note2" class="note"><em></em>
                        	<p><strong>0 Results. </strong>You know we work just in Costa Rica. Right?</p>
                        </div><!--NOTE2-->
                    </fieldset>
                </form>
            </div><!--SEARCH--> 
            <span class="previous-page"><a href="javascript:history.go(-1)">Go back</a> to the previous page</span> 
        </div><!--BOTTOM--> 
    </div><!-- closes w2 -->
    
	<?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
<!--
<h1>An error occurred</h1>
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)): ?>

<h3>Exception information:</h3>
<p>
<b>Message:</b> <?php echo $this->exception->getMessage() ?>
</p>

<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3>Request Parameters:</h3>
<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
</pre>

<?php endif ?>
-->


</body>
</html>