<style type="text/css">
.profile-items .item p.check { clear:both; margin-top:35px; }
.profile-items .item p.check label { float: none; }
.profile-items .item p.check input { vertical-align:baseline }
input.schname { float:none !important; width:90px !important; }
.item { position:relative;}
.item .help {
	position:absolute;
	top:13px;
	left:-35px;}
.item .help a.eye {
	display:block;
	background:url(/images2/eye.png) no-repeat top left;
	width:18px;
	height:12px;
	text-indent:-9999px;
	cursor:pointer;}
	.item .help:hover a.eye {
		background-position:left -12px;}
.item.first .help {
	top:0px;}
	.item .help a.tooltip3 {
		background:url(/images2/help-tooltip-bg.png) top left no-repeat;
		left: 17px;
		padding:11px 12px;
		position:absolute;
		top:-102px;
		z-index:1000;
		display:none;}
	.item .help:hover a.tooltip3 {
		display:block;}

.profile-items {
	overflow:visible;}
</style>
<?php $durations = array(1,2,3,4,5,6,7,8,9,10,15,30,45,); ?>
<?php $hours	 = array('1:00','2:00','3:00','4:00','5:00','6:00','7:00','8:00','9:00','10:00','11:00','12:00',); ?>
<?php if($_POST): ?>
<form action="" method="post">
    <div class="profile-items">
  		<?php if($this->help->hot_info == 0): ?>
    	<div class="desc">
        	<h3>What is the General Information?</h3>
        	<p>Some general details about the experience, listing name, contact information, categories and more.</p>
        	<a href="" rel="hot_info" class="remove">Remove</a>
        </div><!-- closes desc -->
        <?php endif ?>
    	<?php if($this->errors): ?>
        <div class="errors">
            <?php foreach($this->errors as $err): ?>
            <p><?= $err ?></p>
            <?php endforeach ?>
        </div><!-- closes item -->
        <?php endif ?>
        
        <div class="main-ttl">
        	<p><strong>General information about your hotel</strong> <a href="/admin/users/view/partner/<?= $this->vendor->id ?>/2" class="back_btn">&larr; Back to Listings</a></p>
        </div>
        <!-- closes main-ttl -->

		<div class="item-wrppr">
			<div class="item-ttl">
				Basic Information
			</div><!-- closes item ttl -->
			<div class="item first last">
				<input placeholder="Hotel's name" type="text" class="noclean limitcc" name="title" rel="60" value="<?= $_POST['title'] ?>" />
				<h4>Title</h4>
				<span>Hotel name<br />
                <span class="charsLeftInp"></span> Character Left</span>
                <div class="help">
                    <a href="/images2/help/big-hot-general-name.png" class="eye">help</a>
                    <a href="/images2/help/big-hot-general-name.png" class="tooltip3">
                    <img src="/images2/help/small-hot-general-name.png" /></a>
                </div>
			</div><!-- closes item -->
			<div class="clear"></div>									
		</div><!-- closes item-wrppr -->
        
        <div class="item-wrppr">
			<div class="item-ttl">
				Contact Information
			</div><!-- closes item ttl -->		
            <div class="item first">
                <?php $checked = (isset($_POST['contactEqual'])) ? 'checked="checked"' : '' ?>
                <input id="contactEqual" <?= $checked ?> type="checkbox" name="contactEqual" />
                <label for="contactEqual">The contact information is the same as my company profile</label>
            </div>	
            <?php $disabled = (!empty($checked)) ? 'disabled="disabled"' : '' ?> 
			<div class="item">
				<input placeholder="Your phone number" <?= $disabled ?> type="text" name="phone" value="<?= $_POST['phone'] ?>" />
				<h4>Phone</h4>
				<span>Contact Phone</span>
			</div><!-- closes item -->
			<div class="item">
				<input placeholder="Your email address" <?= $disabled ?> type="text" name="email" value="<?= $_POST['email'] ?>" />
				<h4>Email</h4>
				<span>Contact Email</span>
			</div><!-- closes item -->
			<div class="item last">
				<input placeholder="Your website url" <?= $disabled ?> type="text" name="website" value="<?= $_POST['website'] ?>" />
				<h4><a href="<?= $_POST['website'] ?>" target="_blank">Website</a></h4>
				<span>Company Website</span>
			</div><!-- closes item -->
			<div class="clear"></div>									
		</div><!-- closes item-wrppr -->
        
        <div class="item-wrppr">
            <div class="item-ttl">
                Details
            </div><!-- closes item ttl -->
            <div class="item first">
                <div class="selects">
                	<?php $checkin = $_POST['checkin_hour'] . ' ' . $_POST['checkin_time'] ?>
                    <?php $checkout = $_POST['checkout_hour'] . ' ' . $_POST['checkout_time'] ?>
                    <select name="checkin_hour">
                    	<?php foreach($hours as $h): ?>
                        <?php if($h == (date('g:i', strtotime($checkin)))): ?>
                        <option selected="selected" value="<?= $h ?>"><?= $h ?></option>
                        <?php else: ?>
                        <option value="<?= $h ?>"><?= $h ?></option>
                        <?php endif ?>
                        <?php endforeach ?>
                    </select>
                    <select name="checkin_time">
                    	<?php if('AM' == (date('A', strtotime($checkin)))): ?>
                        <option selected="selected" value="AM">AM</option>
                        <option value="PM">PM</option>
                        <?php elseif('PM' == (date('A', strtotime($checkin)))): ?>
                        <option value="AM">AM</option>
                        <option selected="selected" value="PM">PM</option>
                        <?php else: ?>
                        <option value="AM">AM</option>
                        <option value="PM">PM</option>                        
                        <?php endif ?>
                    </select>
                </div><!-- closes selects -->
                <h4>Check In</h4>
                <span>Select the checkin hour</span>
                <div class="help">
                    <a href="/images2/help/big-hot-general-checkin.png" class="eye">help</a>
                    <a href="/images2/help/big-hot-general-checkin.png" class="tooltip3">
                    <img src="/images2/help/small-hot-general-checkin.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="item">
                <div class="selects">                    
                    <select name="checkout_hour">
                    	<?php foreach($hours as $h): ?>
                        <?php if($h == (date('g:i', strtotime($checkout)))): ?>
                        <option selected="selected" value="<?= $h ?>"><?= $h ?></option>
                        <?php else: ?>
                        <option value="<?= $h ?>"><?= $h ?></option>
                        <?php endif ?>
                        <?php endforeach ?>
                    </select>
                    <select name="checkout_time">
                        <?php if('AM' == (date('A', strtotime($checkout)))): ?>
                        <option selected="selected" value="AM">AM</option>
                        <option value="PM">PM</option>
                        <?php elseif('PM' == (date('A', strtotime($checkout)))): ?>
                        <option value="AM">AM</option>
                        <option selected="selected" value="PM">PM</option>
                        <?php else: ?>
                        <option value="AM">AM</option>
                        <option value="PM">PM</option>                        
                        <?php endif ?>
                    </select>
                </div><!-- closes selects -->
                <h4>Check Out</h4>
                <span>Select the checkout hour</span>
                <div class="help">
                    <a href="/images2/help/big-hot-general-checkout.png" class="eye">help</a>
                    <a href="/images2/help/big-hot-general-checkout.png" class="tooltip3">
                    <img src="/images2/help/small-hot-general-checkout.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="item">
				<div class="inner-container">
                	<?php if(is_array($_POST['types'])): ?>
					<table>
						<tbody>
                        	<?php for($i=0; $i<count($this->categories); $i=$i+3): ?>
                            <tr>
                                <?php for($j=$i; ($j<count($this->categories)) && ($j<($i+3)); $j++): ?>
                                <td>
                                <?php $checked = (in_array($this->categories[$j]->id, $_POST['types'])) ? 'checked="checked"' : ''; ?>
                                <input <?= $checked ?> name="types[<?= $this->categories[$j]->id ?>]" 
                                value="<?= $this->categories[$j]->id ?>" type="checkbox"/>
                                <?= $this->categories[$j]->name ?>
                                </td>
                                <?php endfor ?>
                            </tr>
                            <?php endfor ?>
						</tbody>
					</table>
                    <?php else: ?>
                    <table>
						<tbody>
                        	<?php for($i=0; $i<count($this->categories); $i=$i+3): ?>
                            <tr>
                                <?php for($j=$i; ($j<count($this->categories)) && ($j<($i+3)); $j++): ?>
                                <td>
                                <input name="types[<?= $this->categories[$j]->id ?>]" 
                                value="<?= $this->categories[$j]->id ?>" type="checkbox"/>
                                <?= $this->categories[$j]->name ?>
                                </td>
                                <?php endfor ?>
                            </tr>
                            <?php endfor ?>
						</tbody>
					</table>
                    <?php endif ?>
				</div><!-- closes inner-container -->
				<h4>Category</h4>
				<span>Select categories</span>
                <div class="help">
                    <a href="/images2/help/big-hot-general-category.png" class="eye">help</a>
                    <a href="/images2/help/big-hot-general-category.png" class="tooltip3">
                    <img src="/images2/help/small-hot-general-category.png" /></a>
                </div>
			</div><!-- closes item -->
            <!--
			<div class="item last">
				<div class="inner-container">
                	<?php //if(is_array($_POST['tags'])): ?>
					<table>
						<tbody>
							<?php // for($i=0; $i<count($this->tags); $i=$i+2): ?>
                            <tr>
                                <?php  //for($j=$i; ($j<count($this->tags)) && ($j<($i+2)); $j++): ?>
                                <td>
                                <?php //$checked = (in_array($this->tags[$j]->id, $_POST['tags'])) ? 'checked="checked"' : ''; ?>
                                <input <? // $checked ?> name="tags[<? // $this->tags[$j]->id ?>]" 
                                value="<? // $this->tags[$j]->id ?>" type="checkbox"/>
                                <? //$this->tags[$j]->name ?>
                                </td>
                                <?php // endfor ?>
                            </tr>
                            <?php // endfor ?>
						</tbody>
					</table>
                    <?php // else: ?>
                    <table>
						<tbody>
							<?php //for($i=0; $i<count($this->tags); $i=$i+2): ?>
                            <tr>
                                <?php //for($j=$i; ($j<count($this->tags)) && ($j<($i+2)); $j++): ?>
                                <td>
                                <input name="tags[<? //$this->tags[$j]->id ?>]" 
                                value="<? //$this->tags[$j]->id ?>" type="checkbox"/>
                                <? //$this->tags[$j]->name ?>
                                </td>
                                <?php //endfor ?>
                            </tr>
                            <?php //endfor ?>
						</tbody>
					</table>
                    <?php //endif ?>
				</div>
				<h4>Tags</h4>
				<span>Select Tags</span>
			</div> -->
            <div class="item last">
				<div class="inner-container">
					<table>
						<tbody>
                            <?php for($i=0; $i<count($this->landscapes); $i=$i+3): ?>
                            <tr>
                                <?php for($j=$i; ($j<count($this->landscapes)) && ($j<($i+3)); $j++): ?>
                                <td>
                                <?php if(is_array($_POST['lands'])): ?>
                                <?php $checked = (in_array($this->landscapes[$j]->id, $_POST['lands'])) ? 'checked="checked"' : ''; ?>
                                <?php else: ?>
                                <?php $checked = '' ?>
                                <?php endif ?>
                                <input <?= $checked ?> name="lands[<?= $this->landscapes[$j]->id ?>]" 
                                value="<?= $this->landscapes[$j]->id ?>" type="checkbox"/>
                                <?= $this->landscapes[$j]->name ?>
                                </td>
                                <?php endfor ?>
                            </tr>
                            <?php endfor ?>
						</tbody>
					</table>
				</div><!-- closes inner-container -->
				<h4>Landscapes</h4>
				<span>Select Landscapes</span>
                <div class="help">
                    <a href="/images2/help/big-hot-general-landscape.png" class="eye">help</a>
                    <a href="/images2/help/big-hot-general-landscape.png" class="tooltip3">
                    <img src="/images2/help/small-hot-general-landscape.png" /></a>
                </div>
			</div><!-- closes item -->
			<div class="clear"></div>								
        </div><!-- closes item-wrppr -->
    </div><!-- closes profile-items -->
    <div class="foot">
        <input type="submit" class="btn-1 noclean" value="Save Changes" />
        <a class="confirmDeleteListing" href="/admin/listings/delete/<?= $this->listing->id ?>">Delete Listing</a>
    </div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'edit-listing') ?>" />
    <input type="hidden" name="_task" value="<?= md5('edit_listing') ?>" />
    <input type="hidden" name="partner" value="<?= $this->listing->vendor_id ?>" />
</form>
<?php else: ?>
<form action="" method="post">
    <div class="profile-items">
    	<?php if($this->help->hot_info == 0): ?>
    	<div class="desc">
        	<h3>What is the General Information?</h3>
        	<p>Some general details about the experience, listing name, contact information, categories and more.</p>
        	<a href="" rel="hot_info" class="remove">Remove</a>
        </div>
        <!-- closes desc -->
        <?php endif ?>
    	<?php if($this->errors): ?>
        <div class="errors">
            <?php foreach($this->errors as $err): ?>
            <p><?= $err ?></p>
            <?php endforeach ?>
        </div><!-- closes item -->
        <?php endif ?>
        <div class="main-ttl">
        	<p><strong>General information about your hotel</strong> <a href="/admin/users/view/partner/<?= $this->vendor->id ?>/2" class="back_btn">&larr; Back to Listings</a></p>
        </div>
        <!-- closes main-ttl -->
		<div class="item-wrppr">
			<div class="item-ttl">
				Basic Information
			</div><!-- closes item ttl -->
			<div class="item first last">
				<input placeholder="Hotel's name" type="text" class="noclean limitcc" name="title" rel="60" value="<?= $this->listing->title ?>" />
				<h4>Title</h4>
				<span>Hotel name<br />
                <span class="charsLeftInp"></span> Character Left</span>
                <div class="help">
                    <a href="/images2/help/big-hot-general-name.png" class="eye">help</a>
                    <a href="/images2/help/big-hot-general-name.png" class="tooltip3">
                    <img src="/images2/help/small-hot-general-name.png" /></a>
                </div>
			</div><!-- closes item --> 
			<div class="clear"></div>									
		</div><!-- closes item-wrppr -->
        
        <div class="item-wrppr">
			<div class="item-ttl">
				Contact Information
			</div><!-- closes item ttl -->
            <div class="item first">
            	<?php $checked = ($this->vendor->phone == $this->listing->phone &&
						 		  $this->vendor->email == $this->listing->email &&
								  $this->vendor->website == $this->listing->website) ? 'checked="checked"' : '' ?>
                <input id="contactEqual" <?= $checked ?> type="checkbox" name="contactEqual" />
                <label for="contactEqual">The contact information is the same as my company profile</label>
            </div>	
            <?php $disabled = ($checked != '') ? 'disabled="disabled"' : '' ?>
			<div class="item">
				<input placeholder="Your phone number" <?= $disabled ?> type="text" name="phone" value="<?= $this->listing->phone ?>" />
				<h4>Phone</h4>
				<span>Contact Phone</span>
			</div><!-- closes item -->
			<div class="item">
				<input placeholder="Your email address" <?= $disabled ?> type="text" name="email" value="<?= $this->listing->email ?>" />
				<h4>Email</h4>
				<span>Contact Email</span>
			</div><!-- closes item -->
			<div class="item last">
				<input placeholder="Your website url" <?= $disabled ?> type="text" name="website" value="<?= $this->listing->website ?>" />
				<h4><a href="<?= $this->listing->website ?>" target="_blank">Website</a></h4>
				<span>Company Website</span>
			</div><!-- closes item -->
			<div class="clear"></div>									
		</div><!-- closes item-wrppr -->
        
        <div class="item-wrppr">
            <div class="item-ttl">
                Details
            </div><!-- closes item ttl -->
            <div class="item first">
                <div class="selects">
                    <select name="checkin_hour">
                    	<?php foreach($hours as $h): ?>
                        <?php if(!is_null($this->listing->checkin) and $this->listing->checkin != '00:00:00' and 
									$h == (date('g:i', strtotime($this->listing->checkin)))): ?>
                        <option selected="selected" value="<?= $h ?>"><?= $h ?></option>
                        <?php elseif($h == '2:00'): ?>
                        <option selected="selected" value="<?= $h ?>"><?= $h ?></option>
                        <?php else: ?>
                        <option value="<?= $h ?>"><?= $h ?></option>
                        <?php endif ?>
                        <?php endforeach ?>
                    </select>
                    <select name="checkin_time">
                    	<?php if(!is_null($this->listing->checkin) and $this->listing->checkin != '00:00:00' and 
									'AM' == (date('A', strtotime($this->listing->checkin)))): ?>
                        <option selected="selected" value="AM">AM</option>
                        <option value="PM">PM</option>
                        <?php elseif(!is_null($this->listing->checkin) and $this->listing->checkin != '00:00:00' and 
										'PM' == (date('A', strtotime($this->listing->checkin)))): ?>
                        <option value="AM">AM</option>
                        <option selected="selected" value="PM">PM</option>
                        <?php else: ?>
                        <option value="AM">AM</option>
                        <option selected="selected" value="PM">PM</option>                        
                        <?php endif ?>
                    </select>
                </div><!-- closes selects -->
                <h4>Check In</h4>
                <span>Select the checkin hour</span>
                <div class="help">
                    <a href="/images2/help/big-hot-general-checkin.png" class="eye">help</a>
                    <a href="/images2/help/big-hot-general-checkin.png" class="tooltip3">
                    <img src="/images2/help/small-hot-general-checkin.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="item">
                <div class="selects">
                    <select name="checkout_hour">
                    	<?php foreach($hours as $h): ?>
                        <?php if(!is_null($this->listing->checkout) and $this->listing->checkout != '00:00:00' and 
									$h == (date('g:i', strtotime($this->listing->checkout)))): ?>
                        <option selected="selected" value="<?= $h ?>"><?= $h ?></option>
                        <?php elseif($h == '11:00'): ?>
                        <option selected="selected" value="<?= $h ?>"><?= $h ?></option>
                        <?php else: ?>
                        <option value="<?= $h ?>"><?= $h ?></option>
                        <?php endif ?>
                        <?php endforeach ?>
                    </select>
                    <select name="checkout_time">
                        <?php if(!is_null($this->listing->checkout) and $this->listing->checkout != '00:00:00' and 
									'AM' == (date('A', strtotime($this->listing->checkout)))): ?>
                        <option selected="selected" value="AM">AM</option>
                        <option value="PM">PM</option>
                        <?php elseif(!is_null($this->listing->checkout) and $this->listing->checkout != '00:00:00' and 
										'PM' == (date('A', strtotime($this->listing->checkout)))): ?>
                        <option value="AM">AM</option>
                        <option selected="selected" value="PM">PM</option>
                        <?php else: ?>
                        <option selected="selected" value="AM">AM</option>
                        <option value="PM">PM</option>                        
                        <?php endif ?>
                    </select>
                </div><!-- closes selects -->
                <h4>Check Out</h4>
                <span>Select the checkout hour</span>
                <div class="help">
                    <a href="/images2/help/big-hot-general-checkout.png" class="eye">help</a>
                    <a href="/images2/help/big-hot-general-checkout.png" class="tooltip3">
                    <img src="/images2/help/small-hot-general-checkout.png" /></a>
                </div>
            </div><!-- closes item -->
            <div class="item">
				<div class="inner-container">
					<table>
						<tbody>
                        	<?php for($i=0; $i<count($this->categories); $i=$i+3): ?>
                            <tr>
                                <?php for($j=$i; ($j<count($this->categories)) && ($j<($i+3)); $j++): ?>
                                <td>
                                <?php $checked = (in_array($this->categories[$j]->id, $this->listing_types)) ? 'checked="checked"' : ''; ?>
                                <input <?= $checked ?> name="types[<?= $this->categories[$j]->id ?>]" 
                                value="<?= $this->categories[$j]->id ?>" type="checkbox"/>
                                <?= $this->categories[$j]->name ?>
                                </td>
                                <?php endfor ?>
                            </tr>
                            <?php endfor ?>
						</tbody>
					</table>
				</div><!-- closes inner-container -->
				<h4>Category</h4>
				<span>Select categories</span>
                <div class="help">
                    <a href="/images2/help/big-hot-general-category.png" class="eye">help</a>
                    <a href="/images2/help/big-hot-general-category.png" class="tooltip3">
                    <img src="/images2/help/small-hot-general-category.png" /></a>
                </div>
			</div><!-- closes item -->
			<!--
			<div class="item last">
				<div class="inner-container">
					<table>
						<tbody>
							<?php //for($i=0; $i<count($this->tags); $i=$i+2): ?>
                            <tr>
                                <?php //for($j=$i; ($j<count($this->tags)) && ($j<($i+2)); $j++): ?>
                                <td>
                                <?php //$checked = (in_array($this->tags[$j]->id, $this->listing_tags)) ? 'checked="checked"' : ''; ?>
                                <input <? //$checked ?> name="tags[<? // $this->tags[$j]->id ?>]" 
                                value="<? //$this->tags[$j]->id ?>" type="checkbox"/>
                                <? //$this->tags[$j]->name ?>
                                </td>
                                <?php //endfor ?>
                            </tr>
                            <?php // endfor ?>
						</tbody>
					</table>
				</div>
				<h4>Tags</h4>
				<span>Select Tags</span>
			</div>-->
            <div class="item last">
				<div class="inner-container">
					<table>
						<tbody>
                        	<?php for($i=0;$i<count($this->landscapes);$i=$i+3): ?>
							<tr>
                            	<?php for($j=$i;($j<count($this->landscapes)) && ($j<($i+3));$j++): ?>
                                <?php $checked = (in_array($this->landscapes[$j]->id, $this->l_lands)) ? 'checked="checked"' : ''; ?>
								<td><input <?= $checked ?> name="lands[<?= $this->landscapes[$j]->id ?>]" value="<?= $this->landscapes[$j]->id ?>" 
                                			type="checkbox"/><?= $this->landscapes[$j]->name ?></td>
                                <?php endfor ?>
							</tr>
                            <?php endfor ?>
						</tbody>
					</table>
				</div><!-- closes inner-container -->
				<h4>Landscapes</h4>
				<span>Select Landscapes</span>
                <div class="help">
                    <a href="/images2/help/big-hot-general-landscape.png" class="eye">help</a>
                    <a href="/images2/help/big-hot-general-landscape.png" class="tooltip3">
                    <img src="/images2/help/small-hot-general-landscape.png" /></a>
                </div>
			</div><!-- closes item -->
			<div class="clear"></div>								
        </div><!-- closes item-wrppr -->
        <div id="contacts" class="item-wrppr">
	       <div class="item-ttl">
	           Staff Contacts
	       </div><!-- closes item ttl -->
	       <div class="item first">
	           <ul class="controls">
	               <li><a href="#edit_contact_339" class="edit f_b lb">Edit</a></li>
	               <li><a href="" class="remove">Remove</a></li>
	           </ul>
	           <h4>alksjhdljsakldj kasjdlkjaksl</h4>
	           <input type="hidden" name="contactid[339]" value="339" />
	       </div><!-- closes item -->
	                                                               <div class="item ">
	           <ul class="controls">
	               <li><a href="#edit_contact" class="edit f_b lb">Edit</a></li>
	               <li><a href="" class="remove">Remove</a></li>
	           </ul>
	           <h4>asdasd asd</h4>
	           <input type="hidden" name="contactid[340]" value="340" />
	       </div><!-- closes item -->
	                                   <div class="item last">
	           <a href="#new_contact" class="add-btn f_b lb">Add another Staff Contact</a>
	       </div><!-- closes item -->
	       <div class="clear"></div>									
	   </div><!-- closes item-wrppr -->
	   
	   <div class="item-wrppr">
			<div class="item-ttl">Live Chat</div>
			<div class="item_descr">
				<p>
					<strong>Connect your favorite IM Service</strong>
					Select the IM Service you prefer<br />
					to talk with your clients
				</p>
				<ul>
					<li><a class="btn-13 f_b" href="#lb_yahoo"><span class="yahoo lbc">Connect with your Yahoo Account</span></a></li>
					<li><a class="btn-13 f_b" href="#lb_gtalk"><span class="gtalk lbc">Update your Google Talk Account</span></a></li>
				</ul>
			</div><!--ITEM_DESCR-->
		</div><!-- closes item-wrppr -->
        
    </div><!-- closes profile-items -->
    <div class="foot">
        <input type="submit" class="btn-1 noclean" value="Save Changes" />
        <a class="confirmDeleteListing" href="/admin/listings/delete/<?= $this->listing->id ?>">Delete Listing</a>
    </div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'edit-listing') ?>" />
    <input type="hidden" name="_task" value="<?= md5('edit_listing') ?>" />
    <input type="hidden" name="partner" value="<?= $this->listing->vendor_id ?>" />
</form>
<div class="hidden">
	<div class="lb_connect" id="new_member">
       <h2>Edit Contact</h2>
       <form action="" method="post">
           <label>First Name</label>
           <input type="text" name="fname" class="noclean" value="alksjhdljsakldj" />
           <label>Last Name</label>
           <input type="text" name="lname" class="noclean" value="kasjdlkjaksl" />
           <label>Position</label>
           <input type="text" name="position" class="noclean" value="alsdjlkasjlkd" />
           <label>Contact e-mail</label>
           <input type="text" name="email" class="noclean" value="alksjdksa@sadjasio.com" />
           <label>Phone</label>
           <input type="text" class="code" class="noclean" value="4323" name="code" />
           <input type="text" class="number" class="noclean" value="23423423432" name="phone" />
           <input type="text" class="ext" class="noclean" value="1234" name="ext" />
           <ul>
               <li><input type="submit" class="btn-1 noclean" value="Add Member" /></li>
               <li><input type="button" class="btn-13 noclean" onclick="$.fancybox.close(); return false;" value="Cancel" /></li>
           </ul>
           <input type="hidden" name="_task" value="ca78a4e9621c8fb9a5d2b2539c07c41d" />
           <input type="hidden" name="id" value="339" />
       </form>
   </div><!--NEW-MEMBER-->
   
   <div class="lb_connect" id="lb_yahoo">
   		<h2>Connect your Yahoo Account</h2>
   		<form action="" method="post">
   			<label>e-Mail</label>
             			<input class="yahoo" type="text" value="" />            
             			<ul>
   				<li><input type="submit" class="btn-1" value="Connect" /></li>
   				<li><input type="button" class="btn-13" onclick="$.fancybox.close();" value="Cancel" /></li>
   			</ul>
             <input type="hidden" name="service" value="yahoo" />
             <input type="hidden" name="id" value="3" />
             <input type="hidden" name="_task" value="909790e70d5cc1f987e88b7b9d6c003a" />
   		</form>
   	</div><!--L_CONNECT-->
   	
   	<div class="lb_connect" id="lb_gtalk">
   		<h2>Connect your Google Talk Account</h2>
   		<form action="" method="post">
   			<label>e-Mail</label>
             			<input class="gtalk" name="email" type="text" value="cristian0789@gmail.com" />
             			<ul>
   				<li><input type="submit" class="btn-1" value="Connect" /></li>
   				<li><input type="button" class="btn-13" onclick="$.fancybox.close();" value="Cancel" /></li>
   			</ul>
             <input type="hidden" name="service" value="gmail" />
             <input type="hidden" name="id" value="3" />
             <input type="hidden" name="_task" value="909790e70d5cc1f987e88b7b9d6c003a" />
   		</form>
   	</div><!--L_CONNECT-->
   	
</div><!--HIDDEN-->
<?php endif ?>