<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> - <?= $this->city->title ?>, <?= $this->country->title ?> | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/jquery-ui-1.8.16.custom.css" />
    <link type="text/css" rel="stylesheet" href="/css2/index/listing-activity.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" />
    <style type="text/css">#mapcanvas { width:246px;  height:175px; }</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>true)); ?>    
    <div class="w2">
        <div class="main wrapper">
        	<?= $this->partial('partials/vendormainmenu.phtml', array('notifications'=> $this->pendingSettings,'active'=>'All Listings','parentActive'=>'Listings')); ?>
            <div class="content-2">
                <div class="box">
                    <?= $this->partial('partials/gallery.phtml', 
					array('user'=>$this->user, 'listing' => $this->listing, 'city' => $this->city, 
						  'country' => $this->country,'pictures' => $this->pictures,'trips'=>$this->trips)); ?>
                    <?php // $this->partial('partials/tabs.phtml', array('listing' => $this->listing, 'tabs' => $this->tabs, 'faqs' => $this->faqs, 'map' => false)); ?>
				</div><!-- closes box --> 
	            <div class="tabs-wrapper-2">
	                <ul>
	                    <li><a href="#tabs-1">Overview</a></li>
	                    <li><a href="#tabs-2">Details</a></li>
	                    <li><a href="#tabs-3">FAQ's</a></li>
	                </ul>
	                <div class="tab" id="tabs-1">
	                    <div class="tab-ttl">About <?= $this->listing->title ?></div>
                        <div class="tab-content">
                        	<h2>About the restaurant</h2>
                        	<p><?= stripslashes(nl2br($this->overview->about)) ?></p>
                            <h2>What to Expect</h2>
                            <p><?= stripslashes(nl2br($this->overview->expect)) ?></p>
                            <h2>Things you'll love</h2>
                            <p><?= stripslashes(nl2br($this->overview->love)) ?></p>
                        </div><!-- closes tab-content -->
	                </div><!-- closes tab -->
	                <div class="tab" id="tabs-2">
	                    <div class="tab-ttl">
	                        Some details you must to know
	                    </div><!-- closes tab-ttl -->
	                    <div class="tab-content">
	                        <h2>Amenities</h2>
	                        <ul>
	                            <li>Recommend for Families and Groups</li>
	                            <li>Takes Reservations</li>
	                            <li>Delivery Service Available</li>
	                            <li>Waiter Service</li>
	                            <li>Outdoor Seating</li>
	                            <li>Take-out</li>
	                            <li>Good for dinner and lunch</li>
	                            <li>Free WiFi</li>
	                            <li>Alcohol Beverages</li>
	                            <li>Wheelchair Accessible</li>
	                        </ul>
	                        <h2>Policies</h2>
	                        <ul>
	                            <li>Credit Cards Policy: We accept some credit cards.</li>
	                            <li>Attire Policy: Casual</li>
	                            <li>Parking Policy: Complimentary underground heated self-parking is available.</li>
	                            <li>Pet Policy: Pets are not permitted.</li>
	                            <li>Smoking Policy: Smoking is not permitted.</li>
	                        </ul>
	                    </div><!-- closes tab-content -->
	                </div><!-- closes tab -->
	                <div class="tab" id="tabs-3">
	                    <div class="tab-ttl">
	                        Frequently Asked Questions
	                    </div><!-- closes tab-ttl -->
	                    <div class="tab-content faqs">
	                        <ul>
	                            <?php foreach($this->faqs as $faq): ?>
                                <li>
                                    <strong><?= stripslashes(nl2br($faq->question)) ?></strong><br />
                                    <?= stripslashes(nl2br($faq->answer)) ?>
                                </li>
                                <?php endforeach ?>
	                        </ul>
	                    </div><!-- closes tab-content -->
	                </div><!-- closes tab -->
	            </div><!-- closes tabs-wrapper -->                
                <div class="reviews-wrapper">
                    <?= $this->partial('partials/reviews.phtml', 
					array('reviews' => $this->reviews, 'questions' => $this->questions, 'answer_allow' => false,
						  'user'=>$this->user, 'listing' => $this->listing->id)); ?>
                </div><!-- closes reviews-wrapper -->
            </div><!-- closes content-2 -->
            
            <div class="right-sidebar">
                <div class="widget book">
                    <div class="ttl">
                        <span>Restaurant</span>
                    </div><!-- closes ttl -->
                    <div class="map-wrapper">
                        <h4>Location</h4>
                        <div id="mapcanvas"></div>
                        <address>
                            <p><strong><?= $this->listing->title ?></strong></p>
                            <p><?= $this->listing->address ?></p>
                        </address>
                    </div><!-- closes map-wrapper -->
                    <div class="hours">
                        <h4>Hours</h4>
                        <table>
                            <tbody>
                                <tr>
                                    <td>Monday - Friday</td>
                                    <td>9 am - 5 pm</td>
                                </tr>
                                <tr>
                                    <td>Saturday</td>
                                    <td>10 am - 3 pm</td>
                                </tr>
                                <tr>
                                    <td>Sunday</td>
                                    <td>10 am - 3 pm</td>
                                </tr>
                            </tbody>
                        </table>
                    </div><!-- closes hours -->
                </div><!-- closes widget -->
                <div class="widget talk">
                    <?= $this->partial('partials/talk.phtml',array('vendor'=>$this->vendor,'user' => $this->user)); ?>
                </div><!-- closes widget -->
            </div><!-- closes right-sidebar -->
        </div><!-- closes main -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->	
<div id="citiesAutocompleteContainer"></div>
<input type="hidden" value="<?= ($this->listing->lat) ? $this->listing->lat : 'none' ?>" name="listlat" />
<input type="hidden" value="<?= ($this->listing->lng) ? $this->listing->lng : 'none' ?>" name="listlng" />
<input type="hidden" value="<?= $this->listing->title ?>" name="listtitle" />

<div class="hidden">
	<div id="send_message">
        <form action="" id="sendMessageForm">
            <div class="lb-forgot">
                <div class="ttl">Send a message to <?= $this->vendor->name ?></div>
                <div class="content">
                    <textarea cols="30" name="message" rows="1"></textarea>
                </div><!-- closes content -->
                <div class="bottom">
                    <input type="submit" class="btn-1" value="Send Message" />
                    <span onclick="$.fancybox.close()" class="btn-4">Cancel</span>				
                </div><!-- closes bottom -->
            </div><!-- closes lb-forgot -->
            <input type="hidden" name="vendor" value="<?= $this->vendor->id ?>" />
        </form>
    </div>
    
    <div id="live_chat">
    	<img src="/images2/chat.png" />
    </div>
    <div id="start_call">
    	<img src="/images2/phone.png" />
    </div>
</div>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="/js2/jquery.js"></script>
<script type="text/javascript" src="/js2/index/listing-restaurant.js"></script>
</body>
</html>