<H3>Bar Saprissa</H3>
<div class="explore">
    <h4><span></span>Explore some search results</h4>
    <a href="" class="fb"><span></span>Facebook Results</a>
    <a href="" class="gl"><span></span>Google Results</a>
    <div class="clear"></div>
</div><!--EXPLORE-->
<div class="fb_add">
    <label><span></span>Facebook URL</label>
    <input type="text" name="" value="" />
    <input type="submit" value="Create Selected" class="btn-1" />
</div><!--FB_ADD-->