
   	<script type="text/javascript">
   		$(document).ready(function() {
   			$('a.lbc').fancybox({
   				padding: 0,
   				overlayColor: '#000',
   				overlayOpacity: '0.7'
   			});
   			$('.cont').cycle({ 
   			    fx:     'fade', 
   			    prev:   '.larrow', 
   			    next:   '.rarrow', 
   			    timeout: 0 
   			});
   		});
   		</script>

	<div id="recomendation_listing" class="lb">
		<div class="top">Our Recommendations </div><!--TOP-->
		<div class="mid">
			<div class="slider">
				<a href="#" class="larrow"></a>
				<a href="#" class="rarrow"></a>
				<div class="cont">
                	<?php foreach($this->listings as $list): ?>
					<div class="slide">
                    	<?= $this->thumbnail(array('width'=>329,'height'=>232),$list->image,'','329:232'); ?>
						<div class="info">
                        <form action="" method="post">
							<h4><?= $list->title ?></h4>
							<h5><img src="https://static.tripfab.com/images2/ico_136.png" width="10" height="15" alt="" />
                            <strong><?= $list->city ?></strong> <?= $list->country ?></h5>
							<p><?= $list->description ?></p>
							<div class="bot">
                            	<?php if($list->main_type == 5): ?>
								<span><sup>$</sup><?= $this->formatnumber($list->price) ?> <em>/ night</em></span>
                                <?php else: ?>
								<span><sup>$</sup><?= $this->formatnumber($list->price) ?> <em>/ person</em></span>                                
                                <?php endif ?>
								<input type="submit" class="btn-1" value="Replace" />
								<a href="/<?= $list->country_idf ?>/<?= $list->city_idf ?>/<?= $list->identifier ?>" class="btn-10">Read More</a>
							</div><!--BOTTOM-->
                            <input type="hidden" name="ids" value="<?= $this->trip ?>" />
                            <input type="hidden" name="listing" value="<?= $list->listing_id ?>" />
                            <input type="hidden" name="triplisting" value="<?= $this->triplisting ?>" />
		                    <input type="hidden" name="_task" value="<?= md5('replace') ?>" class="replace" />
                        </form>
						</div><!--INFO-->
					</div><!--SLIDE-->
                    <?php endforeach ?>
				</div><!--CONT-->
			</div><!--SLIDER-->
		</div><!--MID-->
	</div><!--RECOMMENDATION_LISTING-->
