<style type="text/css">
.hidden { display:none;}
</style>
<form action="" method="post">
    <div class="lstng-details pricing overview">		
    	<?php if($this->help->ent_overview == 0): ?>						
    	<div class="desc">
    		<h3>What is the Overview Section?</h3>
    		<p>Let people know about your entertainment, how is the experience, what to expect, things they'll love.</p>
    		<a href="" rel="ent_overview" class="remove">Remove</a>
    	</div><!-- closes desc -->
        <?php endif ?>
    	<div class="main-ttl">
    		<p><strong>Entertainment Overview</strong></p>    		
    	</div><!-- closes main-ttl -->
        <div class="lstng-detail">
            <textarea placeholder="Write a nice description about the entertaiment" class="noclean" name="about" cols="30" rows="1"><?= stripslashes($this->overview->about) ?></textarea>
            <strong>About the entertainment</strong>
            <span>Write a detailed description</span><!--<span class="counter">500</span>-->
        </div><!-- closes lstng-detail -->
        <div class="lstng-detail">
            <textarea placeholder="Write a nice description about what to expect" class="noclean" name="expect" cols="30" rows="1"><?= stripslashes($this->overview->expect) ?></textarea>
            <strong>What to expect</strong>
            <span>Tell us what the traveler can expect</span>
            <!--<span class="counter">500</span>-->
        </div><!-- closes lstng-detail -->
        <div class="lstng-detail">
            <textarea placeholder="Write a nice description about what people will love" class="noclean" name="love" cols="30" rows="1"><?= stripslashes($this->overview->love) ?></textarea>
            <strong>Things you'll love</strong>
            <span>Write about things people will love about it</span>
            <!--<span class="counter">500</span>-->
        </div><!-- closes lstng-detail -->
        
       <div class="lstng-detail faq last">								
            <strong>Restrictions</strong>
            <span>Write a detailed description</span><br />
            
            <div class="clear"></div>
            <?php $exists = false; ?>
            <?php foreach($this->details as $detail): ?>
            <?php if($detail->type == 3): ?>
            <?php $exists = true; ?>
            <div class="item">
                <a href="#delete_detail_<?= $detail->id ?>" class="remove">remove</a>
                <input placeholder="Enter your restriction text here" type="text" class="noclean" name="detail[<?= $detail->id ?>][text]" value="<?= $detail->text ?>" />
                <div class="clear"></div>
            </div>
            <?php endif ?>
            <?php endforeach ?>
            
            
            <?php if($exists): ?>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="details[3][0][text]" value="" />
                <div class="clear"></div>
            </div>
            <?php else: ?>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="details[3][0][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="details[3][1][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="details[3][2][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="details[3][3][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="details[3][4][text]" value="" />
                <div class="clear"></div>
            </div>
            <?php endif ?>
            
            <div class="hidden restriction detail">
            	<a href="" class="remove"></a>
                <input placeholder="Enter your restriction text here" type="text" name="text" value="" />
                <div class="clear"></div>
            </div>
            <a href="" id="addRestriction" class="link-5">Add another item</a>
        </div><!-- closes lstng-detail -->
    </div><!-- closes lstng-details -->
    <div class="foot">
        <input type="submit" class="btn-1" value="Save Changes" />
    </div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'edit-overview') ?>" />
    <input type="hidden" name="_task" value="<?= md5('edit_overview') ?>" />
</form>