<style type="text/css">
.hidden { display:none;}
</style>
<form action="" method="post">
    <div class="lstng-details">
    	<?php if($this->help->act_details == 0): ?>
    	<div class="desc">
    		<h3>What is the Details Section?</h3>
    		<p>Let people know what the activity includes, what is not included and policies and restrictions people should keep in mind.</p>
    		<a href="" rel="act_details" class="remove">Remove</a>
    	</div>
    	<!-- closes desc -->
        <?php endif ?>
    	<div class="main-ttl">
    		<p><strong>Write some details about the activity</strong></p>    		
    	</div>
    	<!-- closes main-ttl -->
        <div class="lstng-detail faq">
            <strong>Includes</strong>
            <span>Write a detailed description</span><br />
            <?php $exist = false; ?>
            <?php foreach($this->details as $detail): ?>
            <?php if($detail->type == 1): ?>
            <?php $exist = true; ?>
            <div class="item">
                <a href="#delete_detail_<?= $detail->id ?>" class="remove">remove</a>
                <input type="text" class="noclean" name="detail[<?= $detail->id ?>][text]" value="<?= $detail->text ?>" />
                <div class="clear"></div>
            </div>
            <?php endif ?>
            <?php endforeach ?>
            
            <?php if($exist): ?>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter include text here" type="text" name="details[1][0][text]" value="" />
                <div class="clear"></div>
            </div>
            <?php else: ?>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter include text here" type="text" name="details[1][0][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter include text here" type="text" name="details[1][1][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter include text here" type="text" name="details[1][2][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter include text here" type="text" name="details[1][3][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input placeholder="Enter include text here" type="text" name="details[1][4][text]" value="" />
                <div class="clear"></div>
            </div>
            <?php endif ?>
            
            <div class="hidden include detail">
            	<a href="" class="remove"></a>
                <input placeholder="Enter include text here" type="text" name="text" value="" />
                <div class="clear"></div>
            </div>
            <a href="" id="addInclude" class="link-5">Add another item</a>
        </div><!-- closes lstng-detail -->
        <div class="lstng-detail faq">
            <strong>Non-Includes</strong>
            <span>Write a detailed description</span><br />
            
            <?php $exist = false; ?>
            <?php foreach($this->details as $detail): ?>
            <?php if($detail->type == 2): ?>
            <?php $exist = true; ?>
            <div class="item">
                <a href="#delete_detail_<?= $detail->id ?>" class="remove">remove</a>
                <input type="text" class="noclean" name="detail[<?= $detail->id ?>][text]" value="<?= $detail->text ?>" />
                <div class="clear"></div>
            </div>
            <?php endif ?>
            <?php endforeach ?>
            
            <?php if($exist): ?>
            <div class="item">
                <a href="" class="remove"></a>
                <input type="text" placeholder="Enter non-include text here" name="details[2][0][text]" value="" />
                <div class="clear"></div>
            </div>
            <?php else: ?>
            <div class="item">
                <a href="" class="remove"></a>
                <input type="text" placeholder="Enter non-include text here" name="details[2][0][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input type="text" placeholder="Enter non-include text here" name="details[2][1][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input type="text" placeholder="Enter non-include text here" name="details[2][2][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input type="text" placeholder="Enter non-include text here" name="details[2][3][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input type="text" placeholder="Enter non-include text here" name="details[2][4][text]" value="" />
                <div class="clear"></div>
            </div>
            <?php endif ?>
            
            <div class="hidden noninclude detail">
            	<a href="" class="remove"></a>
                <input type="text" placeholder="Enter non-include text here" name="text" value="" />
                <div class="clear"></div>
            </div>
            <a href="" id="addNonInclude" class="link-5">Add another item</a>
        </div><!-- closes lstng-detail -->
        <div class="lstng-detail faq last">								
            <strong>Restrictions</strong>
            <span>Write a detailed description</span><br />
            
            <?php $exist = false; ?>
            <?php foreach($this->details as $detail): ?>
            <?php if($detail->type == 3): ?>
            <?php $exist = true; ?>
            <div class="item">
                <a href="#delete_detail_<?= $detail->id ?>" class="remove">remove</a>
                <input type="text" class="noclean" name="detail[<?= $detail->id ?>][text]" value="<?= $detail->text ?>" />
                <div class="clear"></div>
            </div>
            <?php endif ?>
            <?php endforeach ?>
            
            <?php if($exist): ?>
            <div class="item">
                <a href="" class="remove"></a>
                <input type="text" placeholder="Enter the restriction text here" name="details[3][0][text]" value="" />
                <div class="clear"></div>
            </div>
            <?php else: ?>
            <div class="item">
                <a href="" class="remove"></a>
                <input type="text" placeholder="Enter the restriction text here" name="details[3][0][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input type="text" placeholder="Enter the restriction text here" name="details[3][1][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input type="text" placeholder="Enter the restriction text here" name="details[3][2][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input type="text" placeholder="Enter the restriction text here" name="details[3][3][text]" value="" />
                <div class="clear"></div>
            </div>
            <div class="item">
                <a href="" class="remove"></a>
                <input type="text" placeholder="Enter the restriction text here" name="details[3][4][text]" value="" />
                <div class="clear"></div>
            </div>
            <?php endif ?>
            
            <div class="hidden restriction detail">
            	<a href="" class="remove"></a>
                <input type="text" placeholder="Enter the restriction text here" name="text" value="" />
                <div class="clear"></div>
            </div>
            <a href="" id="addRestriction" class="link-5">Add another item</a>
        </div><!-- closes lstng-detail -->
    </div><!-- closes lstng-details -->
    <div class="foot">
        <input type="submit" class="btn-1" value="Save Changes" />
    </div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'edit-listing') ?>" />
    <input type="hidden" name="_task" value="<?= md5('edit_listing') ?>" />
</form>