<form action="" method="post">
    <div class="lstng-details pricing overview">
    	<?php if($this->help->act_overview == 0): ?>
    	<div class="desc">
    		<h3>What is the Overview Section?</h3>
    		<p>Let people know about your activity, how is the experience, what to expect, things they'll love.</p>
    		<a href="" rel="act_overview" class="remove">Remove</a>
    	</div>
    	<!-- closes desc -->
        <?php endif ?>
    	<div class="main-ttl">
    		<p><strong>Activity Overview</strong></p>    		
    	</div>
    	<!-- closes main-ttl -->
        <div class="lstng-detail">
            <textarea placeholder="Write a nice description about this activity" class="noclean" name="about" cols="30" rows="1"><?= stripslashes($this->overview->about) ?></textarea>
            <strong>About the activity</strong>
            <span>Write a detail description</span>
            <!--<span class="counter">500</span>-->
        </div><!-- closes lstng-detail -->
        <div class="lstng-detail">
            <textarea placeholder="Write a nice description about what to expect fron this activity" class="noclean" name="expect" cols="30" rows="1"><?= stripslashes($this->overview->expect) ?></textarea>
            <strong>What to expect</strong>
            <span>Tell us what the traveler can expect</span>
            <!--<span class="counter">500</span>-->
        </div><!-- closes lstng-detail -->
        <div class="lstng-detail">
            <textarea class="noclean" placeholder="Write a nice description about the things people will love of this activity" name="love" cols="30" rows="1"><?= stripslashes($this->overview->love) ?></textarea>
            <strong>Things you'll love</strong>
            <span>Write about things people will love about it</span>
            <!--<span class="counter">500</span>-->
        </div><!-- closes lstng-detail -->
    </div><!-- closes lstng-details -->
    <div class="foot">
        <input type="submit" class="btn-1" value="Save Changes" />
    </div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'edit-overview') ?>" />
    <input type="hidden" name="_task" value="<?= md5('edit_overview') ?>" />
</form>