<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Untitled Document</title>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script type="text/javascript" src="http://static.twilio.com/libs/twiliojs/1.0/twilio.min.js"></script>
<script type="text/javascript">
	// Set up with TOKEN, a string generated server-side
	Twilio.Device.setup("<?= $this->token ?>");
	Twilio.Device.ready(function() {
		// Could be called multiple times if network drops and comes back.
		// When the TOKEN allows incoming connections, this is called when
		// the incoming channel is open.
	});
	Twilio.Device.offline(function() {
		// Called on network connection lost.
	});
	Twilio.Device.incoming(function(conn) {
		console.log(conn.parameters.From); // who is calling
		conn.status // => "pending"
		conn.accept();
		conn.status // => "connecting"
	});
	Twilio.Device.cancel(function(conn) {
		console.log(conn.parameters.From); // who canceled the call
		conn.status // => "closed"
	});
	Twilio.Device.connect(function (conn) {
		// Called for all new connections
		console.log(conn.status);
	});
	Twilio.Device.disconnect(function (conn) {
		// Called for all disconnections
		console.log(conn.status);
	});
	Twilio.Device.presence(function (presenceEvent) {
		// Called for each available client when this device becomes ready
		// and every time another client's availability changes.
		presenceEvent.from // => name of client whose availablity changed
		presenceEvent.available // => true or false
	});
	Twilio.Device.error(function (e) {
		console.log(e.message + " for " + e.connection);
	});
	$(document).ready(function () {
		Twilio.Device.connect({
			agent: "Smith",
			phone_number: "4158675309"
		});
	});
	$("#hangup").click(function() {
		Twilio.Device.disconnectAll();
	});
</script>
</head>

<body>
</body>
</html>