<?php header('Content-type: text/xml');
echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<Response>
	<?php if ($_REQUEST['Digits'] == '1'): ?>
    <Dial callerId="client:sandbox">0050683200338</Dial>
    <Say>The call failed or the remote party hung up. Goodbye.</Say>
    <?php else: ?>
    <Say>Record your monkey howl after the tone.</Say>
	<Record maxLength="30" action="/phonetest/recordhandler" />
    <?php endif ?>
</Response>