<?php header('Content-type: text/xml');
echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<Response>
	<Say>Hello <?= $this->name ?></Say>
    <Play>http://demo.twilio.com/hellomonkey/monkey.mp3</Play>
    <Gather numDigits="1" action="/phonetest/keyhandler" method="POST">
	    <Say>To speak to a real monkey, press 1. 
        Press 2 to record your own monkey howl. 
        Press any other key to start over.</Say>
    </Gather>
</Response>
