<div id="footer">
	<div class="wrap">
		<span class="flag"></span>
		<p><strong>Tripfab is lovely designed in a tropical paradise</strong>Copyright &copy; 2011 Tripfab</p>
		<ul>
			<li><a href="http://facebook.com/tripfab">Facebook</a></li>
			<li><a href="http://twitter.com/tripfab">Twitter</a></li>
			<li><a href="https://plus.google.com/108576021199856132768/">Google+</a></li>
			<li><a href="mailto:hello@tripfab.com">eMail</a></li>
			<li><a href="http://blog.tripfab.com">Blog</a></li>
		</ul>
	</div><!--WRAP-->
</div><!--FOOTER-->
<div id="citiesAutocompleteContainer"></div>