<div class="tabs-wrapper-2">
    <ul>
        <li><a href="#tabs-1">Overview</a></li>
        <li><a href="#tabs-2">Details</a></li>
        <li><a href="#tabs-3">Tips</a></li>
        <li><a href="#tabs-4">FAQ's</a></li>    
	    <?php if($this->map): ?>
        <li><a href="#tabs-5">How to Get There</a></li>
        <?php endif ?>
    </ul>
    <div class="tab" id="tabs-1">
        <div class="tab-ttl">
            About the activity
        </div><!-- closes tab-ttl -->
        <div class="tab-content">
            <h2>What to Expect</h2>
            <p>Aenean auctor, leo congue vehicula dictum, purus orci eleifend lacus, sit amet eleifend neque ipsum eu magna. Sed a tellus nisl.</p>
            <p>Nam ut nibh id est condimentum imperdiet at non massa. Pellentesque ac congue ipsum. Sed porta lacus non libero hendrerit ultrices. Quisque ac nisi ac purus feugiat mollis sed ut diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam sit amet aliquam ligula. Integer ac dolor sed urna lacinia vulputate et sed nibh.</p>
            <h2>Things you'll love</h2>
            <p>bibendum elementum tincidunt commodo, feugiat quis quam. Duis feugiat, purus nec mollis pulvinar, felis diam imperdiet justo, id consequat massa libero ac velit. Nulla commodo, elit vitae consectetur viverra, ipsum neque volutpat eros, et faucibus arcu turpis eu quam. Fusce neque mauris, semper et aliquam et, ornare non tortor. Phasellus pellentesque viverra accumsan.</p>
            <p>bibendum elementum tincidunt commodo, feugiat quis quam. Duis feugiat, purus nec mollis pulvinar, felis diam imperdiet justo, id consequat massa libero ac velit. Nulla commodo, elit vitae consectetur viverra, ipsum neque volutpat eros, et faucibus arcu turpis eu quam. Fusce neque mauris, semper et aliquam et, ornare non tortor. Phasellus po, id consequat massa libero ac velit. Nulla commodo, elit vitae consectetur viverra, ipsum neque volutpat eros, et faucibus arcu turpis eu quam. Fusce neque mauris, semper et aliquam et, ornare non tortor. Phasellus p o, id consequat massa libero ac velit. </p>
            <p>Nulla commodo, elit vitae consectetur viverra, ipsum neque volutpat eros, et faucibus arcu turpis eu quam. Fusce neque mauris, semper et aliquam et, ornare non tortor. Phasellus pellentesque viverra accumsan. bibendum elementum tincidunt commodo, feugiat quis quam. Duis feugiat, purus nec mollis pulvinar, felis diam imperdiet justo, id consequat massa libero ac velit. Nulla commodo, elit vitae consectetur viverra, ipsum neque volutpat eros, et faucibus arcu turpis eu quam.</p>
        </div><!-- closes tab-content -->
        <div class="message">
            <div>
                <p><strong>Schedule Details</strong></p>
                <p>9:00 AM</p>
                <p>10:00 AM</p>
                <p>2:00 PM</p>
            </div>
            <div>
                <p><strong>Duration</strong></p>
                <p>1.5 - 2 hours</p>
            </div>
            <div>
                <p><strong>Departure Point</strong></p>
                <p>Tamarindo</p>
            </div>
            <div>
                <p><strong>Return Point</strong></p>
                <p>Tour concludes at the original point of departure</p>
            </div>
        </div><!-- closes message -->
    </div><!-- closes tab -->
    <div class="tab" id="tabs-2">
        <div class="tab-ttl">
            Some details you must to know
        </div><!-- closes tab-ttl -->
        <div class="tab-content">
            <h2>Inclusions</h2>
            <ul>
                <li>One or two-hour surf lesson with a qualified instructor</li>
                <li>Rash-guard shirt (rental)</li>
                <li>Surfboard equipment (rental)</li>
                <li>Rubberized fins (rental)</li>
                <li>Optional water shoes (rental)</li>
                <li>Hotel pickup and drop-off for private and semi-private lesson participants staying in Waikiki hotels.</li>
                <li>Stand up paddle lesson participants requesting hotel pickup and drop-off will be charged an 
                    additional $10 per person on the day of lesson.</li>
            </ul>
            <h2>Exclusions</h2>
            <ul>
                <li>One or two-hour surf lesson with a qualified instructor</li>
                <li>Rash-guard shirt (rental)</li>
                <li>Surfboard equipment (rental)</li>
                <li>Rubberized fins (rental)</li>
                <li>Optional water shoes (rental)</li>
                <li>Hotel pickup and drop-off for private and semi-private lesson participants staying in Waikiki hotels.</li>
                <li>Stand up paddle lesson participants requesting hotel pickup and drop-off will be charged an 
                    additional $10 per person on the day of lesson.</li>
            </ul>
            <h2>Policies</h2>
            <ul>
                <li>One or two-hour surf lesson with a qualified instructor</li>
                <li>Rash-guard shirt (rental)</li>
                <li>Surfboard equipment (rental)</li>
                <li>Rubberized fins (rental)</li>
                <li>Optional water shoes (rental)</li>
                <li>Hotel pickup and drop-off for private and semi-private lesson participants staying in Waikiki hotels.</li>
                <li>Stand up paddle lesson participants requesting hotel pickup and drop-off will be charged an 
                    additional $10 per person on the day of lesson.</li>
            </ul>
        </div><!-- closes tab-content -->
    </div><!-- closes tab -->
    <div class="tab" id="tabs-3">
        <div class="tab-ttl">
            Some recommendations before take the trip
        </div><!-- closes tab-ttl -->
        <div class="tab-content tips">
            <ul>
                <li>Make sure you are always on time for all pick ups.</li>
                <li>While in San Jose avoid going too far away from your hotel and ask hotel staff for directions of where to go.</li>
                <li>Do not go too far away from your your traveling group on your transfer stops.</li>
                <li>In Tortuguero and in Guanacaste always wear sun screen, the sun is quite hot there.</li>
                <li>Carry a little cash with you, some places give discounts is you pay cash.</li>
                <li>Do not leave your items unnatended in any of the locations, specially at the beach.</li>
                <li>If you need assistance at any time during your trip, ask your guide. </li>
                <li>Always be on time for pick ups.</li>
                <li>If you have any food allergies or specific food requirements make sure you inform the tour operator.</li>
                <li>Follow the instructions provided by your tour guide at all times.</li>
                <li>Do not leave your items unattended, specially at the beach.</li>
                <li>Make sure you always wear sun screen.</li>
                <li>If you have any food allergies or specific food requirements make sure you inform the tour operator.</li>
                <li>Follow the instructions provided by your tour guide at all times.</li>
                <li>Do not leave your items unattended, specially at the beach.</li>
            </ul>
        </div><!-- closes tab-content -->
    </div><!-- closes tab -->
    <div class="tab" id="tabs-4">
        <div class="tab-ttl">
            Frequently Asked Questions
        </div><!-- closes tab-ttl -->
        <div class="tab-content faqs">
            <ul>
                <li>
                    <strong>Can children take this tour?</strong>
                    Yes, people of all ages can take and enjoy this tour.
                </li>
                <li>
                    <strong>Can I be picked up in Liberia?</strong>
                    For different pick ups other than San Jose, please contact tour operator for details and/or possible arrangements.
                </li>
                <li>
                    <strong>When is the best time to take this tour?</strong>
                    This tour can be taken and enjoyed year round.
                </li>
                <li>
                    <strong>What is the temperature on these locations?</strong>
                    Tortuguero and Guanacaste are hot and sunny, although it rains more in Tortuguero. Arenal on the other hand might get a bit chilly.
                </li>
                <li>
                    <strong>Where is the pick up for this tour?</strong>
                    The pick up and drop off for this tour is at the Juan Santamaria Airport.
                </li>
                <li>
                    <strong>At what time can I do this tour?</strong>
                    Tropical Bungee offers this tour twice a day. Their departure times daily can be found on the Tour Details tab.
                </li>
                <li>
                    <strong>Do I have to own and/or bring my own equipment?</strong>
                    No, this tour includes all certified equipment necessary to jump and it is carefully verified for safety.
                </li>
                <li>
                    <strong>How old do I have to be to do this activity?</strong>
                    There is no age limit. Tropical Bungee has had jumpers as young as 4 years old and as old as 80 years old.
                </li>
                <li>
                    <strong>At what time can I do this tour?</strong>
                    Tropical Bungee offers this tour twice a day. Their departure times daily can be found on the Tour Details tab.
                </li>
            </ul>
        </div><!-- closes tab-content -->
    </div><!-- closes tab -->
    <?php if($this->map): ?>
    <div class="tab" id="tabs-5">
        <div class="tab-ttl">
            How to get there
        </div><!-- closes tab-ttl -->
        <div class="tab-content there">										
            <h2>By plane</h2>
            <p>Flights are available to John F. Kennedy International Airport (JFK) and LaGuardia Airport (LGA) from major U.S. cities on a variety of carriers</p>
            <h2>By car</h2>
            <p>Taxis to/from LGA, about 12 miles from the property, are approximately $40 per car, each way.</p>
            <h2>By train</h2>
            <p>Flights are available to John F. Kennedy International Airport (JFK) and LaGuardia Airport (LGA) from major U.S. cities on a variety of carriers</p>
            <div id="mapcanvas"></div>									
        </div><!-- closes tab-content -->
        <div class="message">
            <address>
                <p><strong>Detailed Address</strong></p>
                <p>9 Crosby Street</p>
                <p>New York, NY 10013</p>
                <p>United States</p>
            </address>
        </div><!-- closes message -->
    </div><!-- closes tab -->
    <?php endif ?>
</div><!-- closes tabs-wrapper -->