<form action="" method="post" id="form_faq">
    <div class="lstng-details">
        <div class="lstng-detail">
            <strong>FAQ's</strong>
            <span>Answers a some frequent asked questions</span>
        </div><!-- closes lstng-detail -->
        <?php foreach($this->faqs as $faq): ?>
        <div class="lstng-detail faq">
            <strong>Frequent question</strong>
            <textarea cols="30" class="noclean" rows="1" name="faq[<?= $faq->id ?>][question]"><?= stripslashes($faq->question) ?></textarea>
            <div class="clear"></div>
            <strong>Your Answer</strong>
            <textarea cols="30" class="noclean" name="faq[<?= $faq->id ?>][answer]" rows="1"><?= stripslashes($faq->answer) ?></textarea>
        </div><!-- closes lstng-detail -->
        <?php endforeach ?>
        <div id="addFAQ" class="lstng-detail faq hidden">
            <strong>Frequent question</strong>
            <textarea cols="30" class="noclean" name="question" rows="1"></textarea>
            <div class="clear"></div>
            <strong>Your Answer</strong>
            <textarea cols="30" class="noclean" name="answer" rows="1"></textarea>
        </div><!-- closes lstng-detail -->
        <div class="lstng-detail last">
            <a href="" id="addmewfaq" class="link-5">Add a New FAQ</a>
        </div><!-- closes lstng-detail -->
    </div><!-- closes lstng-details -->
    <div class="foot">
        <input type="submit" class="btn-1" value="Save Changes" />
        <a href="/provider/listings/desactivate/<?= $this->listing->id ?>">Deactivate Listing</a>
    </div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token.'form_faq') ?>" />
    <input type="hidden" name="_task" value="<?= md5('update_faq') ?>" />
</form>