<style type="text/css">
#mapcanvas { width:500px; height:300px; margin-top:10px; margin-bottom:10px;}
.errors { border:1px solid #F00; padding:5px; margin-bottom:10px;}
.errors p { font-size:12px; font-weight:normal; font-style:italic; color:#F00;}
.w-m { display:none;}
.lstng-detail { position:relative;}
.lstng-detail .help {
	position:absolute;
	top:20px;
	left:240px;}
.lstng-detail .help a.eye {
	display:block;
	background:url(/images2/eye.png) no-repeat top left;
	width:18px;
	height:12px;
	text-indent:-9999px;
	cursor:pointer;}
	.lstng-detail .help:hover a.eye {
		background-position:left -12px;}
.lstng-detail.first .help {
	top:0px;}
	.lstng-detail .help a.tooltip3 {
		background:url(/images2/help-tooltip-bg.png) top left no-repeat;
		left: 17px;
		padding:11px 12px;
		position:absolute;
		top:-102px;
		z-index:1000;
		display:none;}
	.lstng-detail .help:hover a.tooltip3 {
		display:block;}

.lstng-detail {
	overflow:visible;}
.listing-content { overflow:visible;}
</style>
<?php if($_POST): ?>
<form action="" method="post">
    <div class="lstng-details pricing overview">
    	<?php if($this->help->com_getthere == 0): ?>
    	<div class="desc">
        	<h3>What is the Listing Location Section?</h3>
        	<p>Provide people with a very descriptive address, ways to get there, the easiest transportation choices and make sure you choose the correct location of your venue in the map. You can drag and drop the pin over the exact location of your listing.</p>
        	<a href="" rel="com_getthere" class="remove">Remove</a>
        </div>
        <!-- closes desc -->	
        <?php endif ?>
    	<?php if($this->errors): ?>
        <div class="errors">
            <?php foreach($this->errors as $err): ?>
            <p><?= $err ?></p>
            <?php endforeach ?>
        </div><!-- closes item -->
        <?php endif ?>						
        <div class="main-ttl">
        	<p><strong>Listing Location</strong></p>        	
        </div>
        <!-- closes main-ttl -->
		<div class="lstng-detail">
			<textarea placeholder="Nice description about to how to get to your place by plane" cols="30" class="noclean limitcc" rel="1000" name="plane" rows="1"><?= $_POST['plane'] ?></textarea>
			<strong>By Plane</strong>
			<span>Write a detailed description</span>
            <div class="help">
                <a href="/images2/help/big-act-howto-info.png" class="eye">help</a>
                <a href="/images2/help/big-act-howto-info.png" class="tooltip3">
                <img src="/images2/help/small-act-howto-info.png" /></a>
            </div>
            <div class="clear"></div>
		</div><!-- closes lstng-detail -->
		<div class="lstng-detail">
			<textarea placeholder="Nice description about to how to get to your place by car" cols="30" class="noclean limitcc" rel="1000" name="car" rows="1"><?= $_POST['car'] ?></textarea>
			<strong>By Car</strong>
			<span>Write a detailed description</span>
            <div class="clear"></div>
		</div><!-- closes lstng-detail -->
		<div class="lstng-detail">
			<textarea placeholder="Nice description about to how to get to your place by train" cols="30" class="noclean limitcc" rel="1000" name="train" rows="1"><?= $_POST['train'] ?></textarea>
			<strong>By Train</strong>
			<span>Write a detailed description</span>
            <div class="clear"></div>
		</div><!-- closes lstng-detail -->
        <div class="lstng-detail">
			<textarea placeholder="Nice description about to how to get to your place by boat" cols="30" class="noclean limitcc" rel="1000" name="boat" rows="1"><?= $_POST['boat'] ?></textarea>
			<strong>By Boat</strong>
			<span>Write a detailed description</span>
            <div class="clear"></div>
		</div><!-- closes lstng-detail -->
    
    	<div class="lstng-detail">
        	<div class="selects">
                <select id="country2" name="country_id">
                    <option value="">Select Country</option>
                    <?php foreach($this->countries as $c): ?>
                    <?php $selected = ($c->id == $_POST['country_id']) ? 'selected="selected"' : ''; ?>
                    <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                    <?php endforeach ?>
                </select>
                <select name="city_id" id="cities2">
                    <?php if(count($this->cities) > 0): ?>
                    <option value="">Select the city</option>
                    <?php foreach($this->cities as $c): ?>
                    <?php $selected = ($c->id == $_POST['city_id']) ? 'selected="selected"' : ''; ?>
                    <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                    <?php endforeach ?>                                    
                    <?php else: ?>
                    <option value="">Country first</option>
                    <?php endif ?>
                </select>
            </div><!-- closes selects -->
            <strong>Location</strong>
			<span>Select country and city</span>	
            <div class="help">
                <a href="/images2/help/big-act-howto-map.png" class="eye">help</a>
                <a href="/images2/help/big-act-howto-map.png" class="tooltip3">
                <img src="/images2/help/small-act-howto-map.png" /></a>
            </div>
            <div class="clear"></div>					
        </div><!-- closes item-wrppr -->
    
        <div class="lstng-detail">
            <div class="map">
                <input placeholder="Search for your place in the map" type="text" class="noclean short" name="address" value="<?= $_POST['address'] ?>" />
                <input type="submit" class="btn-10" id="setLocation" value="Set Location" />
                <div class="clear"></div>
				<div class="w-m">
					<h5>Location Results</h5>
                	<ul id="maplocations">
                	</ul>
                </div>
                <!-- closes w-m -->
                <div id="mapcanvas"></div>
                <input type="hidden" name="lat" value="<?= $_POST['lat'] ?>" />
                <input type="hidden" name="lng" value="<?= $_POST['lng'] ?>" />                
            </div><!-- closes map -->
            <strong>Map</strong>
            <span>This is how your address appears <br /> on the public listing</span>
            <div class="clear"></div>
        </div><!-- closes lstng-detail -->
    </div>
    
	<div class="foot">
		<input type="submit" class="btn-1 noclean" value="Save Changes" />
	</div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'edit-location') ?>" />
    <input type="hidden" name="_task" value="<?= md5('edit_location') ?>" />
</form>
<?php else: ?>
<form action="" method="post">
    <div class="lstng-details pricing overview">
    	<?php if($this->errors): ?>
        <div class="errors">
            <?php foreach($this->errors as $err): ?>
            <p><?= $err ?></p>
            <?php endforeach ?>
        </div><!-- closes item -->
        <?php endif ?>
    	<?php if($this->help->com_getthere == 0): ?>
        <div class="desc">
        	<h3>What is the Listing Location Section?</h3>
        	<p>Provide people with a very descriptive address, ways to get there, the easiest transportation choices and make sure you choose the correct location of your venue in the map. You can drag and drop the pin over the exact location of your listing.</p>
        	<a href="" rel="com_getthere" class="remove">Remove</a>
        </div><!-- closes desc -->	
        <?php endif ?>						
        <div class="main-ttl">
        	<p><strong>Listing Location</strong></p>        	
        </div><!-- closes main-ttl -->
		<div class="lstng-detail">
			<textarea placeholder="Nice description about to how to get to your place by plane" cols="30" class="noclean limitcc" rel="1000" name="plane" rows="1"><?= stripslashes($this->location->plane) ?></textarea>
			<strong>By Plane</strong>
			<span>Write a detailed description</span>
            <div class="help">
                <a href="/images2/help/big-act-howto-info.png" class="eye">help</a>
                <a href="/images2/help/big-act-howto-info.png" class="tooltip3">
                <img src="/images2/help/small-act-howto-info.png" /></a>
            </div>
            <div class="clear"></div>
		</div><!-- closes lstng-detail -->
		<div class="lstng-detail">
			<textarea placeholder="Nice description about to how to get to your place by car" cols="30" class="noclean limitcc" rel="1000" name="car" rows="1"><?= stripslashes($this->location->car) ?></textarea>
			<strong>By Car</strong>
			<span>Write a detailed description</span>
            <div class="clear"></div>
		</div><!-- closes lstng-detail -->
		<div class="lstng-detail">
			<textarea placeholder="Nice description about to how to get to your place by train" cols="30" class="noclean limitcc" rel="1000" name="train" rows="1"><?= stripslashes($this->location->train) ?></textarea>
			<strong>By Train</strong>
			<span>Write a detailed description</span>
            <div class="clear"></div>
		</div><!-- closes lstng-detail -->
        <div class="lstng-detail">
			<textarea placeholder="Nice description about to how to get to your place by boat" cols="30" class="noclean limitcc" rel="1000" name="boat" rows="1"><?= stripslashes($this->location->boat) ?></textarea>
			<strong>By Boat</strong>
			<span>Write a detailed description</span>
            <div class="clear"></div>
		</div><!-- closes lstng-detail -->
    
    	<div class="lstng-detail">
        	<div class="selects">
                <select id="country2" name="country_id">
                    <option value="">Select Country</option>
                    <?php foreach($this->countries as $c): ?>
                    <?php $selected = ($c->id == $this->listing->country_id) ? 'selected="selected"' : ''; ?>
                    <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                    <?php endforeach ?>
                </select>
                <select name="city_id" id="cities2">
                    <?php if(count($this->cities) > 0): ?>
                    <option value="">Select the city</option>
                    <?php foreach($this->cities as $c): ?>
                    <?php $selected = ($c->id == $this->listing->city_id) ? 'selected="selected"' : ''; ?>
                    <option <?= $selected ?> value="<?= $c->id ?>"><?= $c->title ?></option>
                    <?php endforeach ?>                                    
                    <?php else: ?>
                    <option value="">Country first</option>
                    <?php endif ?>
                </select>
            </div><!-- closes selects -->
            <strong>Location</strong>
			<span>Select country and city</span>	
            <div class="help">
                <a href="/images2/help/big-act-howto-map.png" class="eye">help</a>
                <a href="/images2/help/big-act-howto-map.png" class="tooltip3">
                <img src="/images2/help/small-act-howto-map.png" /></a>
            </div>
            <div class="clear"></div>					
        </div><!-- closes item-wrppr -->
    
        <div class="lstng-detail">
            <div class="map">
                <input placeholder="Search for your place in the map" type="text" class="noclean short" name="address" value="<?= $this->listing->address ?>" />
                <input type="submit" class="btn-10" id="setLocation" value="Set Location" />
                <div class="clear"></div>
                <div class="w-m">
                	<h5>Location Results</h5>
                	<ul id="maplocations">
                	</ul>
                </div>
                <!-- closes w-m -->
                <div id="mapcanvas"></div>
                <input type="hidden" name="lat" value="<?= $this->listing->lat ?>" />
                <input type="hidden" name="lng" value="<?= $this->listing->lng ?>" />
            </div><!-- closes map -->
            <strong>Map</strong>
            <span>This is how your address appears <br /> on the public listing</span>
            <div class="clear"></div>
        </div><!-- closes lstng-detail -->
    </div>
    
	<div class="foot">
		<input type="submit" class="btn-1 noclean" value="Save Changes" />
	</div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token .'edit-location') ?>" />
    <input type="hidden" name="_task" value="<?= md5('edit_location') ?>" />
</form>
<?php endif ?>