<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?>: Notifications | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('input').ToggleInputValue();
			<?php if($this->successmessage): ?>
			showAlert("Your changes have been saved");
		    <?php endif ?>
        });
    </script>
    <style type="text/css">
	.profile-items .item input[type="password"] {
		border: 1px solid #D8D8D8;
		border-radius: 2px 2px 2px 2px;
		color: #303030;
		float: right;
		font-size: 12px;
		height: 27px;
		padding: 0 5px;
		width: 203px;
	}
	.profile-items .item input[type="password"]:focus {
		border-color: #ADDEFF;
		box-shadow: 0 0 5px #ADDEFF;
	}
	</style>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-backend">
        	<?= $this->partial('partials/vendormainmenu.phtml', array('notifications'=> $this->pendingSettings,'active'=>'Password','parentActive'=>'Account')); ?>
            <div class="listings-main">
            	<div class="sub-ttl">
	                Account - Notifications
            	</div><!-- closes sub-ttl -->
            </div>
            <div class="vendor-profile">
               <form action="" id="user_form_notifications" method="post">
                    <div class="profile-items">
                        <div class="item-wrppr">
                            <div class="item-ttl">Send me emails when:</div>
                            <div class="item first">
                                <span>We promise not to spam, and you can disable these at any time</span>
                            </div><!-- closes item -->
                            <?php foreach($this->notifications[1] as $ntf): ?>
                            <?php if(in_array($ntf->id, $this->usersettings)): ?>
                            <div class="item notification"><input checked="checked" name="ntf[<?= $ntf->id ?>]" value="<?= $ntf->id ?>" type="checkbox" />
                            <label><?= $ntf->label ?></label></div>
                            <?php else: ?>
                            <div class="item notification"><input name="ntf[<?= $ntf->id ?>]" value="<?= $ntf->id ?>" type="checkbox" />
                            <label><?= $ntf->label ?></label></div>
                            <?php endif ?>
                            <?php endforeach ?>
                            <div class="clear"></div>									
                        </div><!-- closes item-wrppr -->
                        <div class="item-wrppr">
                            <div class="item-ttl">Remind me when:</div>
                            <div class="item first">							
                                <span>Enabling these emails ensures the best possible experience for both hosts and guests</span>
                            </div><!-- closes item -->
                            <?php foreach($this->notifications[2] as $ntf): ?>
                            <?php if(in_array($ntf->id, $this->usersettings)): ?>
                            <div class="item notification"><input checked="checked" name="ntf[<?= $ntf->id ?>]" value="<?= $ntf->id ?>" type="checkbox" />
                            <label><?= $ntf->label ?></label></div>
                            <?php else: ?>
                            <div class="item notification"><input name="ntf[<?= $ntf->id ?>]" value="<?= $ntf->id ?>" type="checkbox" />
                            <label><?= $ntf->label ?></label></div>
                            <?php endif ?>
                            <?php endforeach ?>	
                            <div class="clear"></div>									
                        </div><!-- closes item-wrppr -->
                    </div><!-- closes profile-items -->
                    <div class="foot">
                        <input type="submit" class="btn-1" value="Save Changes" />
                    </div><!-- closes foot -->
                    <input type="hidden" name="userids" value="<?= $this->user->id ?>" />
                    <input type="hidden" name="usertokens" value="<?= $this->user->token ?>" />
                    <input type="hidden" name="formid" value="<?= md5($this->user->token.'user_form_notifications') ?>" />
                    <input type="hidden" name="_task" value="<?= md5('update_user_notifications') ?>" />
                </form>
            </div>
            <!-- closes vendor-profile -->
        </div>
        <!-- closes user-backend -->
    </div>
    <!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div>
<!-- closes w1 -->
</body>
</html>