<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->listing->title ?> : Location | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
	<script type="text/javascript" src="/js2/jquery.js"></script>
    <script type="text/javascript" src="/js2/provider/location.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('textarea').elastic();	
            $('#header .header-login a.user').click(function(){
                $(this).next().toggleClass('show');
                return false;
            });
        });
    </script>
</head>
<body>
<div class="w1">
     <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="listing-wrapper wrapper">
            <?= $this->partial('partials/vendormainmenu.phtml', array('notifications'=> $this->pendingSettings,'active'=>'All Listings','parentActive'=>'Listings')); ?>
            <?= $this->partial('partials/vendorlistingstop.phtml', array('listing'=>$this->listing)); ?>
            <div class="listing-content">
                <div class="left">
                    <?= $this->partial('partials/vendorlistingsmenu.phtml', array('active'=>'How To Get there', 'id' => $this->listing->id, 
									   'type'=>$this->listing->main_type)) ?>
                </div><!-- closes left -->
                <div class="right">
                    <?= $this->partial('listing/common/getthere.phtml', array(
							'listing' => $this->listing,
							'location' => $this->location,
							'countries' => $this->countries,
							'cities'	=> $this->cities,
							'errors'	=> $this->errors,
							'help' => $this->help,
					)) ?>
                </div><!-- closes right -->
            </div><!-- closes listing-content -->
        </div><!-- closes listing-wrapper -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
</body>
</html>