<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Change Password | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js2/jquery.input.value.js"></script>
    <script type="text/javascript" src="/js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
    <script type="text/javascript" src="/js2/common.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('input').ToggleInputValue();
            $("a.lb").fancybox({
                padding: 0,
                showCloseButton: false,
                overlayOpacity: 0.8,
                overlayColor: '#FFFFFF'
            });
        });
    </script>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-backend">
        	<?= $this->partial('partials/vendormainmenu.phtml', array('active'=>'Payments','parentActive'=>'Account')); ?>
            <div class="vendor-profile">
                <form action="">
                    <div class="profile-items">
                        <div class="item-wrppr payments">
                            <div class="item-ttl">
                                Accounts
                            </div>
                            <!-- closes item ttl -->
                            <div class="item">
                                <h4>Paypal</h4>
                                <span>5614484161561 (USD)</span>
                                <a href="" class="link-7">Delete</a>	
                                <a href="" class="link-6">Edit</a>
                            </div>
                            <!-- closes item -->
                            <div class="item">
                                <h4>Bac | Credomatic Bank</h4>
                                <span>5614484161561 (USD)</span>
                                <a href="" class="link-7">Delete</a>	
                                <a href="" class="link-6">Edit</a>
                            </div>
                            <!-- closes item -->
                            <div class="item last">
                                <a href="lb-add-payment.html" class="link-5 lb">Add a New Account</a>
                            </div>
                            <!-- closes item -->
                            <div class="clear"></div>									
                        </div>
                        <!-- closes item-wrppr -->
                    </div>
                    <!-- closes profile-items -->
                    <div class="foot">
                        <input type="submit" class="btn-1" value="Save Changes" />
                        <a href="">Deactivate Account</a>
                    </div>
                    <!-- closes foot -->
                </form>
            </div>
            <!-- closes vendor-profile -->
        </div>
        <!-- closes user-backend -->
    </div>
    <!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div>
<!-- closes w1 -->
</body>
</html>