<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Profile | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js2/jquery.input.value.js"></script>
    <script type="text/javascript" src="/js/jquery.jqtransform.js"></script>
    <script type="text/javascript" src="/js2/jquery.elastic.js"></script>
    <script type="text/javascript" src="/js2/common.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('textarea').elastic();				
            $('input').ToggleInputValue();
            $('form select').jqTransSelect();
        });
    </script>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages">
        	<?php $icons = array(
				2 => 'ico-11.png',
				4 => 'ico-10.png',
				5 => 'ico-12.png',
				6 => 'ico-8.png',
				7 => 'ico-9.png',
			) ?>
            <?= $this->partial('partials/vendormainmenu.phtml', array('active'=>'Questions','parentActive'=>'Reviews \&amp; Questions')); ?>
            <div class="reviews-questions">
            	<?php foreach($this->listings as $listing): ?>
                <div class="s-question">
                    <div class="right">
                        <div><a href="/provider/questions/view/<?= $listing->id ?>" class="btn-4">See Questions</a></div>
                        <?php if($this->new[$listing->id] > 0): ?>
                        <div><span><?= $this->new[$listing->id] ?></span> New Questions</div>
                        <?php endif ?>
                    </div><!-- closes right -->
                    <?= $this->thumbnail(97, $listing->image, '','1:1') ?>
                    <h2><img src="/images2/<?= $icons[$listing->main_type] ?>" alt="" /><?= $listing->title ?></h2>
                </div><!-- closes s-question -->
                <?php endforeach ?>
            </div><!-- closes reviews-questions -->
        </div><!-- closes user-messages -->
    </div><!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div><!-- closes w1 -->
</body>
</html>