<?php $l = strtotime('Next Sunday') - time();
$d1 = ($l - ($l % 86400)); $h1 = $l - $d1; $h2 = $h1 - ($h1 % 3600); $m1 = $h1 - $h2; $m2 = $m1 - ($m1 % 60);
$days = $d1 / 86400; $hours = $h2 / 3600; $minutes = $m2 / 60; $seconds = $m1 - $m2; 
$nights = array(3,4,5,7,10,15) ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
	<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
	<title>Triphut.com</title>
	<link type="text/css"  rel="stylesheet" href="/css6/reset.css?v=<?= $this->cssVC ?>" />
	<link type="text/css"  rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
	<link type="text/css"  rel="stylesheet" href="/css6/landing/landing5.css?v=<?= $this->cssVC ?>" />
</head>
<body id="trip5">
<div id="wp_all">
    <div id="wp_header">
        <div class="wrapper">
            <h1 class="logo"><a href="/">Triphut</a></h1>
            <h2 class="slogan">Let Us Plan Your Perfect Vacation!</h2>
            <div class="contact">
                <p>Call our Customer Service <strong>1-866-401-0382</strong></p>
                <a href="" class="btn-10 js-chat">Live Chat</a>
            </div><!--CONTACT-->
        </div><!--WRAPPER-->            
    </div><!--WP_HEADER-->
    
    <div id="wp_content">
        <div class="bg_image">
            <img class="background" src="https://static.tripfab.com/images6/land5-6.gif" alt="" />
            <div class="info">
                <div>
                    <h2>All-Inclusive Vacations <br />in Costa Rica</h2>
                    <p>The Ultimate All-Inclusive Vacations<br />
                    in Costa Rica, With The Best prices on <br />
                    the market.</p>
                </div>
            </div><!--INFO-->
        </div><!--BG_IMAGE-->
        <div id="content">
            <div class="main">
                <div class="left">
                    <div class="side">
                        <h2>Quick Inquiry</h2>
                        <div>
                            <p>Want one of our Travel Coordinator helping<br />
                            you out with your travel planning?<br />
                            Get a Quick Inquiry</p>
                            <form method="post" action="/ajax/subscribe" id="js-subscribe">
                                <label>Your Name</label>
                                <input type="text" name="name" value="" />
                                <label>Your E-mail</label>
                                <input type="text" name="email" value="" />
                                <label>Phone Number</label>
                                <input type="text" name="phone" value="" />
                                <div class="date">
                                	<div class="lf">
                                		<label>Arrival</label>
                                		<input class="js-checkin" type="text" name="checkin" value="" />
                                	</div>
                                	<div class="rg">
                                		<label>Departure</label>
                                		<input class="js-checkout" type="text" name="checkout" value="" />
                                	</div>
                                	<div class="clear"></div>
                                </div><!--DATE-->
                                <input type="submit" class="btn-1" value="Start your trip" />
                                <div class="clear"></div>
                            </form>
                        </div>
                    </div><!--SIDE-->
                    
                    <div class="widget">
                        <h4>What's different about Triphut?</h4>
                        <ul>
                            <li>
                                <span class="ico1"></span>
                                <p><strong>Satisfaction Insurance</strong> If you aren't 100% satisfied with any part of your trip, we'll give you a full refund for that portion – no questions asked</p>
                            </li>
                            <li>
                                <span class="ico3"></span><p><strong>Best Price Guarantee</strong> If you find any of our trips cheaper elsewhere, we'll not only match that price – we'll beat it. Even more, if you send us a trip not offered on our site, we'll build you a similar trip at a lower price</p>
                            </li>
                        </ul>
                    </div>
                </div><!--LEFT-->
                
                <div class="right">
                    <div class="shadows"></div>                    
                    <div class="sale">
                        <h2>Deal of the Week Hurry Up!</h2>
                        <div class="counter">
                            <div><span>Sale Finishes in</span></div>
                            <div class="jsd"><?= $days ?>d</div>
                            <div class="jsh"><?= $hours ?>h</div>
                            <div class="jsm"><?= $minutes ?>m</div>
                            <div class="jss"><?= $seconds ?>s</div>
                        </div><!--COUNTER-->
                        <div class="clear"></div>
                        <span class="stamp"></span>
                        <div class="trip">
                            <h3><a href="/landing/2/trip/<?= $this->trips[0]['id'] ?>"><?= $this->trips[0]['title'] ?></a></h3>
                            <div class="meta">
                                <ul class="reviews">
                                	<?php for($i=1;$i<=5;$i++): ?>
                                    <?php $class = ($i <= $this->trips[0]['rating']) ? 'fill' : ''; ?>
                                    <li><a href="" class="<?= $class ?>"></a></li>
                                    <?php endfor ?>
                                </ul>
                                <span><?= $this->trips[0]['reviews'] ?> reviews</span>
                                <span class="location"><strong>Location:</strong> <?= $this->trips[0]['location'] ?></span>
                                <div class="clear"></div>
                            </div><!--META-->
                            <a href="/landing/2/trip/<?= $this->trips[0]['id'] ?>"><span class="label"></span>
                            <img width="175" height="131" src="<?= $this->trips[0]['image'] ?>"></a>
                            <div class="inner">
                                <div class="descrip">
                                    <ul class="count">
                                        <li>Sale Finishes in</li>
                                        <li class="jsd"><?= $days ?>d</li>
                                        <li class="jsh"><?= $hours ?>h</li>
                                        <li class="jsm"><?= $minutes ?>m</li>
                                        <li class="jss"><?= $seconds ?>s</li>
                                    </ul>
                                    <p><?= $this->trips[0]['description'] ?>...</p>
                                    <div class="single">
                                        <strong>DURATION</strong>
                                        <p><?= $this->trips[0]['duration'] ?> Days</p>
                                    </div>
                                    <div class="single">
                                        <strong>TRAVELERS</strong>
                                        <p><?= $this->trips[0]['travelers'] ?> People</p>
                                    </div>
                                </div><!--DESCRIP-->
                                <div class="price">
                                    <sup>$<?= $this->formatnumber($this->trips[0]['price_before']) ?></sup>
                                    <span class="total">$<?= $this->formatnumber($this->trips[0]['price']) ?></span>
                                    <sub>per person</sub>
                                    <div class="save">Save $<?= $this->formatnumber($this->trips[0]['save']) ?></div>
                                </div><!--PRICE-->
                                <div class="clear"></div>
                            </div><!--INNER-->
                            <div class="clear"></div>
                        </div><!--TRIP-->
                    </div><!--SALE-->
                    
                    <div class="allTrips">
                    	<?php for($j=1;$j<4;$j++): ?>
                        <div class="trip">
                            <h3><a href="/landing/2/trip/<?= $this->trips[$j]['id'] ?>"><?= $this->trips[$j]['title'] ?></a></h3>
                            <div class="meta">
                                <ul class="reviews">
                                	<?php for($i=1;$i<=5;$i++): ?>
                                    <?php $class = ($i <= $this->trips[$j]['rating']) ? 'fill' : ''; ?>
                                    <li><a href="" class="<?= $class ?>"></a></li>
                                    <?php endfor ?>
                                </ul>
                                <span><?= $this->trips[$j]['reviews'] ?> reviews</span>
                                <span class="location"><strong>Location:</strong> <?= $this->trips[$j]['location'] ?></span>
                                <div class="clear"></div>
                            </div><!--META-->
                            <a href="/landing/2/trip/<?= $this->trips[$j]['id'] ?>"><span class="label"></span>
                            <img width="175" height="131" src="<?= $this->trips[$j]['image'] ?>"></a>
                            <div class="inner">
                                <div class="descrip">
                                    <ul class="count">
                                        <li>Sale Finishes in</li>
                                        <li class="jsd"><?= $days ?>d</li>
                                        <li class="jsh"><?= $hours ?>h</li>
                                        <li class="jsm"><?= $minutes ?>m</li>
                                        <li class="jss"><?= $seconds ?>s</li>
                                    </ul>
                                    <p><?= $this->trips[$j]['description'] ?>...</p>
                                    <div class="single">
                                        <strong>DURATION</strong>
                                        <p><?= $this->trips[$j]['duration'] ?> Days</p>
                                    </div>
                                    <div class="single">
                                        <strong>TRAVELERS</strong>
                                        <p><?= $this->trips[$j]['travelers'] ?> People</p>
                                    </div>
                                </div><!--DESCRIP-->
                                <div class="price">
                                    <sup>$<?= $this->formatnumber($this->trips[$j]['price_before']) ?></sup>
                                    <span class="total">$<?= $this->formatnumber($this->trips[$j]['price']) ?></span>
                                    <sub>per person</sub>
                                    <div class="save">Save $<?= $this->formatnumber($this->trips[$j]['save']) ?></div>
                                </div><!--PRICE-->
                                <div class="clear"></div>
                            </div><!--INNER-->
                            <div class="clear"></div>
                        </div><!--TRIP-->
                        <?php endfor ?>
                    </div><!--ALLTRIPS-->
                </div><!--RIGHT-->
                <div class="clear"></div>
            </div><!--MAIN-->
        </div><!--CONTENT-->
    </div><!--WP_CONTENT-->
    <div id="wp_footer">
        <div class="footer">
            <div class="left">
                <h6>Triphut is lovingly designed in a tropical paradise</h6>
                <span>Copyright &copy; 2011 Triphut</span>
            </div><!--LEFT-->
            <ul>
                <li><a target="_blank" href="mailto:hello@Triphut.com">eMail</a></li>
                <li><a target="_blank" href="https://plus.google.com/108576021199856132768/">Google+</a></li>
                <li><a target="_blank" href="https://twitter.com/Triphut">Twitter</a></li>
                <li><a target="_blank" href="https://facebook.com/Triphut">Facebook</a></li>
            </ul>
        </div><!--FOOTER-->
    </div><!--WP_FOOTER-->
</div><!--WRAPPER_ALL-->
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
$(document).ready(function() {
	$('a.lbc').fancybox({
		padding: 0,
		overlayColor: '#FFF',
		overlayOpacity: '0.7',
		showCloseButton: true,
		centerOnScroll: true,
		titlePosition: 'inside'
	});
	$(".tabs").tabs({
		selected: 2
	});
	$("#addons .accordion").accordion({
		autoHeight: false,
		collapsible: true
	});
	$('.js-checkin').datepicker({
		minDate:'+3',
        dateFormat:'M d, yy',
        onSelect:function(date){
            $date = $.datepicker.parseDate("M d, yy",date);
            $time = $date.getTime() + (86400 * 1000);
            $('.js-checkout').datepicker('option','minDate',$.datepicker.parseDate('@',$time));
        }
	});
    $('.js-checkout').datepicker({
        minDate:'+4',
        dateFormat:'M d, yy'
    });
	$('#js-subscribe').submit(function(){
		var $form = $(this);
		var $data = {
			name:$('input[name=name]', $form).val(),
			email:$('input[name=email]', $form).val(),
			phone:$('input[name=phone]', $form).val(),
			checkin:$('input[name=checkin]', $form).val(),
			checkout:$('input[name=checkout]', $form).val()
		};
		if($data.name == "") 
			alert('Please enter your name');
		else if($data.email == "") 
			alert('Please enter your email');
		else {
			$.ajax({
				url:'/ajax/subscribe',
				type:'post',
				data:$data,
				success:function(){
					$img = $('<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/956485843/?value=0&amp;label=5YoLCO29qwQQ06GLyAM&amp;guid=ON&amp;script=0"/>');
					$('body').append($img);
					$('input[type=text]', $form).val('');
					alert('Your information has been submited. We\'ll get in touch ASAP');
				},
				error:function(){
					$('input[type=text]', $form).val('');
					alert('Sorry, There was a problem. Try again later');
				}
			});
		}
		return false;
	});
	
	$expires = <?= strtotime('Next Sunday') ?>;
	$now	 = <?= time() ?>;
	
	setInterval(function(){
		$now += 1; $l = $expires - $now;
		$d1 = ($l - ($l % 86400)); $h1 = $l - $d1; $h2 = $h1 - ($h1 % 3600); $m1 = $h1 - $h2; $m2 = $m1 - ($m1 % 60);
		$days = $d1 / 86400; $hours = $h2 / 3600; $minutes = $m2 / 60; $seconds = $m1 - $m2;
		$('.jsd').text($days+'d:'); $('.jsh').text($hours+'h:'); $('.jsm').text($minutes+'m:'); $('.jss').text($seconds+'s');
	},1000);
	
	setTimeout(function(){
		console.log('called');
		SnapABug.openProactiveChat();
	}, 3000)
	
	$('.js-chat').click(function(){
		SnapABug.startLink(); return false;
	});
});
$(document).ready(function(){
	img_ready($('img.background'));
});
function img_ready($obj){
	resizeImg($obj);
	$(window).resize(function() {
		resizeImg($obj);
	});
	$obj.fadeIn();
}
function resizeImg($bgImg) { 
	var imgwidth = 1400;
	var imgheight = 382;

	var winwidth = $(window).width();
	var winheight = $(window).height();

	var winCenter = winwidth / 2;
	var imgCenter = imgwidth / 2;

	var left = (winwidth > imgwidth) ? 0 : (winCenter - imgCenter);

	var width = (winwidth > imgwidth) ? winwidth : imgwidth;

	var height = (winwidth > imgwidth) ? ((imgheight * winwidth) / imgwidth) : height;

	var winCenter2 = imgheight / 2;
	var imgCenter2 = height / 2;

	var top = (winwidth > imgwidth) ? (winCenter2 - imgCenter2) : 0;

	$bgImg.css('left',left);
	$bgImg.css('width',width);
	$bgImg.css('height',height);
	$bgImg.css('top',top);
}
</script>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24981182-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<script type="text/javascript">
document.write(unescape("%3Cscript src='" + ((document.location.protocol=="https:")?"https://snapabug.appspot.com":"http://www.snapengage.com") + "/snapabug.js' type='text/javascript'%3E%3C/script%3E"));</script>
<script type="text/javascript">
//SnapABug.setButton("https://static.tripfab.com/images/Live-Chat-Button.png");
//SnapABug.addButton("12926583-ebae-4874-8f3e-57cbe2114ebc","0","55%");
SnapABug.init("12926583-ebae-4874-8f3e-57cbe2114ebc");
SnapABug.setCallback('StartChat', function(email, msg, type) {
	var img = document.createElement('img');
	img.src = "http://www.googleadservices.com/pagead/conversion/956485843/?value=0&amp;label=8ghrCPW8qwQQ06GLyAM&amp;guid=ON&amp;script=0";
	img.width = 1; img.height = 1;
	document.body.appendChild(img);
});
</script>
</body>
</html>