<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
	<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
	<title>Tripfab.com</title>
	<link type="text/css"  rel="stylesheet" href="/css6/reset.css?v=<?= $this->cssVC ?>" />
	<link type="text/css"  rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
	<link type="text/css"  rel="stylesheet" href="/css6/landing/all2.css?v=<?= $this->cssVC ?>" />
</head>
<body id="trip_all2">
<div id="wp_all">
    <div id="wp_header">
        <div id="header" class="in2">
            <div class="wrapper">
                <h1 class="logo"><a href="">Tripfab</a></h1>
                <div class="contact">
                    <a href="#" class="btn-1">Live Chat Now</a>
                    <p>Questions?<strong>Call 1-866-401-0382</strong></p>
                </div><!--CONTACT-->
            </div><!--WRAPPER-->
        </div><!--HEADER-->
        
        <div class="subHeader">
            <div class="cntrl">
                <ul class="breadcrump">
                    <li class="first"><a class="home" href="/"></a></li>
                    <li><a href="">All Inclusive Trips</a></li>
                    <li class="last"><a href="">Allegro Papagayo's</a></li>
                </ul>
                <a class="link1" href="/costa_rica/san_jose/">&larr; Back to Results</a>
                <div class="clear"></div>
            </div>
        </div><!--SUBHEADER-->
    </div><!--WP_HEADER-->
    
    <div id="wp_content">
        <div id="checkout">
            <div class="left">
                <div class="offer">
                    <span class="hurry"></span>
                    <div class="text">
                        <h2>Sale of the week</h2>
                        <h3>Time Remaining to Book this Trip</h3>
                    </div>
                    <div class="counter">							
                        <div class="each first">
                            <strong>2</strong>
                            <span>Days</span>
                        </div><!--EACH-->
                        <div class="each">
                            <strong>2</strong>
                            <span>HOURS</span>
                        </div><!--EACH-->
                        <div class="each">
                            <strong>2</strong>
                            <span>MINUTES</span>
                        </div><!--EACH-->
                        <div class="each last">
                            <strong>2</strong>
                            <span>SECONDS</span>
                        </div><!--EACH-->
                    </div><!--COUNTER-->
                </div><!--OFFER-->
                
                <div class="resume">
                    <h3>All Inclusive</h3>
                    <img src="https://static.tripfab.com/images6/tripsView4ico3.png" width="95" height="95" alt="" />
                    <div class="text">
                        <h2>Allegro Papagayo's</h2>
                        <ul>
                            <li><em class="ico1"></em>Costa Rica</li>
                            <li><em class="ico2"></em>8 Days</li>
                            <li><em class="ico3"></em>7 Nights</li>
                        </ul>
                        <div class="specs">
                            <ul>
                                <li><strong class="ico4">Trip Starts</strong>Fri, September 23rd 2011</li>
                                <li><strong class="ico5">Trips Ends</strong>Sat, September 29th 2011</li>
                                <li><strong class="ico6">Travelers</strong>2 Adults, 1 Child</li>
                            </ul>
                            <div class="clear"></div>
                        </div><!--SPECS-->
                    </div><!--TEXT-->
                    <div class="clear"></div>
                </div><!--RESUME-->
            
                <div class="main">
                    <div class="errors">
                        <h6>The following information is missing or wrong</h6>
                        <ul>
                            <li>- The Credit Card Number required</li>
                            <li>- The Cardholder Name is wrong</li>
                            <li>- The Expiration Date is wrong</li>
                            <li>- The Security Code is wrong</li>
                            <li>- Please accept the terms and conditions</li>
                        </ul>
                    </div><!--ERRORS-->
                    <div class="top">
                        <h3>How it works</h3>
                        <p>Please provide your billing details now. <strong>You will not be charged unless we accept your request (within 48 hours).</strong> If we decline or do not accept, no charge is made and you can try booking another dates or search a different itinerary. </p>
                    </div><!--TOP-->
                    <form method="post" action="">
                        <div class="step">
                            <h4><span>1</span>Personal Information</h4>
                            <div class="fields">
                                <div class="single error">
                                    <label><strong>Full Name</strong>Write your full name</label>
                                    <input type="text" name="" value="" />
                                    <span class="icnError"></span>
                                    <div class="clear"></div>
                                </div><!--SINGLE-->
                                
                                <div class="single">
                                    <label><strong>E-Mail</strong>Give us a e-mail to contact you </label>
                                    <input type="text" name="" value="" />
                                    <span class="icnError"></span>
                                    <div class="clear"></div>
                                </div><!--SINGLE-->
                                
                                <div class="single">
                                    <label><strong>Phone</strong>Write a contact phone number</label>
                                    <input type="text" name="" value="" />
                                    <span class="icnError"></span>
                                    <div class="clear"></div>
                                </div><!--SINGLE-->
                                
                                <div class="single last">
                                    <label><strong>Country</strong>Write a contact phone number</label>
                                    <select>
                                        <option>Costa Rica</option>
                                    </select>
                                    <span class="icnError"></span>
                                    <div class="clear"></div>
                                </div><!--SINGLE-->
                            </div><!--FIELDS-->
                        </div><!--STEP-->
                        
                        <div class="step">
                            <h4><span>2</span>Payment Method</h4>
                            <div class="newCard2">
                                <div class="each">
                                    <label>
                                        <span>Enter a New Credit Card</span>
                                    </label>
                                    <ul class="cards">
                                        <li>
                                            <img id="card-visa1340318536530" src="https://static.tripfab.com/images/visa.png" class="card-icons1340318536530" />
                                        </li>
                                        <li>
                                            <img id="card-mastercard1340318536530" src="https://static.tripfab.com/images/mastercard.png" class="card-icons1340318536530">
                                        </li>
                                        <li>
                                            <img id="card-amex1340318536530" src="https://static.tripfab.com/images/amex.png" class="card-icons1340318536530">
                                        </li>
                                        <li>
                                            <img id="card-diners1340318536530" src="https://static.tripfab.com/images/diners.png" class="card-icons1340318536530">
                                        </li>
                                        <li>
                                            <img id="card-discover1340318536530" src="https://static.tripfab.com/images/discover.png" class="card-icons1340318536530">
                                        </li>
                                        <li>
                                            <img id="card-jcb1340318536530" src="https://static.tripfab.com/images/jcb.png" class="card-icons1340318536530">
                                        </li>
                                    </ul>
                                    <div class="clear"></div>
                                </div><!--EACH-->
                                
                                <div class="item error">
                                    <label>
                                        <strong>Credit Card Number</strong>
                                        No dashes or spaces
                                    </label>
                                    <input type="text" name="" value="" />
                                    <span class="icnError"></span>
                                    <div class="clear"></div>
                                </div><!--ITEM-->
                                <div class="item">
                                    <label>
                                        <strong>Cardholder Name</strong>
                                        As it appears on the credit card
                                    </label>
                                    <input type="text" name="" value="" />
                                    <span class="icnError"></span>
                                    <div class="clear"></div>
                                </div><!--ITEM-->
                                <div class="item">
                                    <label>
                                        <strong>Expiration Date</strong>
                                        No dashes or spaces
                                    </label>
                                    <select>
                                        <option>1</option>
                                    </select>
                                    <select>
                                        <option>1</option>
                                    </select>
                                    <span class="icnError"></span>
                                    <div class="clear"></div>
                                </div><!--ITEM-->
                                <div class="item">
                                    <label>
                                        <strong>Security Code</strong>
                                        <a class="link1 helptip" href="">What's this?</a>
                                        <p class="tip hidden"><span></span> The 3 or 4 digit value printed on the card or signature strip</p>
                                    </label>
                                    <input class="code" type="text" name="" value="" />
                                    <span class="icnError"></span>
                                    <div class="clear"></div>
                                </div><!--ITEM-->
                            </div><!--NEWCARD2-->
                            
                            <h5>Choose a Credit Card</h5>
                            <div class="each">
                                <label>
                                    <input type="radio" name="card" value="" />
                                    <img src="https://static.tripfab.com/images/visa.png" width="" height="" alt="" />
                                    <span>Visa</span>
                                </label>
                                <span class="saveNumber">************4036</span>
                                <div class="clear"></div>
                            </div><!--EACH-->
                            
                            <div class="each">
                                <label>
                                    <input type="radio" name="card" value="" />
                                    <img src="https://static.tripfab.com/images/mastercard.png" width="" height="" alt="" />
                                    <span>MasterCard</span>
                                </label>
                                <span class="saveNumber">************4036</span>
                                <div class="clear"></div>
                            </div><!--EACH-->
                            
                            <div class="newCard">
                                <div class="each">
                                    <label>
                                        <input type="radio" name="card" value="" />
                                        <span>Enter a New Credit Card</span>
                                    </label>
                                    <ul class="cards">
                                        <li>
                                            <img id="card-visa1340318536530" src="https://static.tripfab.com/images/visa.png" class="card-icons1340318536530" />
                                        </li>
                                        <li>
                                            <img id="card-mastercard1340318536530" src="https://static.tripfab.com/images/mastercard.png" class="card-icons1340318536530">
                                        </li>
                                        <li>
                                            <img id="card-amex1340318536530" src="https://static.tripfab.com/images/amex.png" class="card-icons1340318536530">
                                        </li>
                                        <li>
                                            <img id="card-diners1340318536530" src="https://static.tripfab.com/images/diners.png" class="card-icons1340318536530">
                                        </li>
                                        <li>
                                            <img id="card-discover1340318536530" src="https://static.tripfab.com/images/discover.png" class="card-icons1340318536530">
                                        </li>
                                        <li>
                                            <img id="card-jcb1340318536530" src="https://static.tripfab.com/images/jcb.png" class="card-icons1340318536530">
                                        </li>
                                    </ul>
                                    <div class="clear"></div>
                                </div><!--EACH-->
                                <div class="item error">
                                    <label>
                                        <strong>Credit Card Number</strong>
                                        No dashes or spaces
                                    </label>
                                    <input type="text" name="" value="" />
                                    <span class="icnError"></span>
                                    <div class="clear"></div>
                                </div><!--ITEM-->
                                <div class="item">
                                    <label>
                                        <strong>Cardholder Name</strong>
                                        As it appears on the credit card
                                    </label>
                                    <input type="text" name="" value="" />
                                    <span class="icnError"></span>
                                    <div class="clear"></div>
                                </div><!--ITEM-->
                                <div class="item">
                                    <label>
                                        <strong>Expiration Date</strong>
                                        No dashes or spaces
                                    </label>
                                    <select>
                                        <option>1</option>
                                    </select>
                                    <select>
                                        <option>1</option>
                                    </select>
                                    <span class="icnError"></span>
                                    <div class="clear"></div>
                                </div><!--ITEM-->
                                <div class="item">
                                    <label>
                                        <strong>Security Code</strong>
                                        <a class="link1 helptip" href="">What's this?</a>
                                        <p class="tip hidden"><span></span> The 3 or 4 digit value printed on the card or signature strip</p>
                                    </label>
                                    <input class="code" type="text" name="" value="" />
                                    <span class="icnError"></span>
                                    <div class="clear"></div>
                                </div><!--ITEM-->
                            </div><!--NEWCARD-->
                        </div><!--STEP-->
                                                    
                        <div class="step last">
                            <h4><span>3</span>Policies & Restriccions</h4>
                            <div class="all">
                                <div class="restriction">
                                    <strong>Cancellation</strong> 
                                    <a href="#cancel_policy" class="high-r lbc">High Restrictions &rarr;</a>
                                    <div class="clear"></div>
                                </div>
                                <div class="restriction">
                                    <strong>Activity Restrictions</strong> 
                                    <a href="#cancel_policy" class="lbc">Read Activity Restrictions &rarr;</a>
                                    <div class="clear"></div>
                                </div>
                                <div class="restricction_tip hidden">
                                    <strong>50% refund up until 1 week prior to arrival, except fees</strong>
                                    <ul>
                                        <li>• Cleaning fees are always refunded if the guest did not check in.</li>
                                        <li>• The Tripfab service fee is non-refundable.</li>
                                        <li>• If there is a complaint from either party, notice must be given to Tripfab 
                                        Resolution Center within 24 hours of check-in.</li>
                                        <li>• Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                                        <li>• A reservation is not officially canceled until the guest receives a cancellation confirmation 
                                        e-mail from Tripfab Resolution Center.</li>
                                    </ul>
                                    <span></span>
                                </div>
                                <div class="restriction last">
                                    <input type="checkbox" value="1" id="terms" name="terms">
                                    <label for="terms">I agree to the cancellation policy, activity restrictions and 
                                    <a href="/terms" class="link1" target="_blank">terms of use</a>.</label>
                                    <div class="clear"></div>
                                </div>
                            </div><!--ALL-->
                        </div><!--STEP-->
                        <div class="bottom"> 
                            <span>Grand Total<strong> $1,902</strong></span>
                            <input type="submit" value="Book Now " class="btn-1 noclean">
                        </div><!--BOTTOM-->
                    </form>			
                </div><!--MAIN-->
            </div><!--LEFT-->
            
            <div class="right">
                <div class="widget easyBooking">
                    <h6>One–Click–Book</h6>
                    <table width="265" cellspacing="0" cellpadding="0" border="0">
                        <tbody>
                            <tr class="before">
                                <td>Package Regular Price</td>
                                <td class="rg">$4510</td>
                            </tr>
                            <tr>
                                <td>Special Price</td>
                                <td class="rg"><strong>$4000</strong></td>
                            </tr>
                            <tr>
                                <td>Additional Experiences</td>
                                <td class="rg"><strong>$300</strong></td>
                            </tr>
                            <tr class="save">
                                <td>Total Save</td>
                                <td class="rg">$200</td>
                            </tr>
                            <tr class="total">
                                <td>Trip Total</td>
                                <td class="rg">$4300</td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="btn">
                        <input type="submit" class="btn-1" name="" value="Book Now" />
                    </div><!--BTN-->
                    <div class="bot">
                        <strong>Save $132</strong> per person
                    </div>
                </div><!--EASYBOOKING-->
                
                <div class="widget summary">
                    <h6>Trip Summary</h6>
                    <table width="265" cellspacing="0" cellpadding="0" border="0">
                        <tbody>
                            <tr>
                                <td>Allegro Papagayo</td>
                                <td><strong>$4510</strong></td>
                            </tr>
                            <tr>
                                <td>Tripfab Experience. <a class="lbc link1" href="#tripExperience">What is this?</a></td>
                                <td><strong class="fr">Free</strong></td>
                            </tr>
                            <tr>
                                <td>7 nights</td>
                                <td><strong>$300</strong></td>
                            </tr>
                            <tr>
                                <td>Scuba Diving Trip</td>
                                <td><strong>$200</strong></td>
                            </tr>
                            <tr>
                                <td>Night Scuba Diving</td>
                                <td><strong>$4300</strong></td>
                            </tr>
                        </tbody>
                    </table>
                </div><!--SUMMARY-->
                
                <div class="talk">
                    <strong>Questions about the trip?</strong>
                    <span>Call 1-866-401-0382</span>
                </div><!--TALK-->
            </div><!--RIGHT-->
            <div class="clear"></div>
        </div><!--CONTENT-->
    </div><!--WP_CONTENT-->
</div><!--WRAPPER_ALL-->
<div class="hidden">
    <div id="tripExperience" class="tripExperience">
        <span class="stamp"></span>
        <h2>Enjoy the Tripfab Experience®</h2>
        <h3>When you buy a trip with Tripfab you get a new travel experience</h3>
        <div class="single">
            <span class="icon1"></span>
            <h4>Best Price Guarantee</h4>
            <p>If you find any of our trips cheaper elsewhere, we'll not only match that price – we'll beat it. Even more, if you send us a trip not offered on our site, we'll build you a similar trip at a lower price</p>
        </div><!--SINGLE-->
        <div class="single">
            <span class="icon2"></span>
            <h4>Free Cell Phone</h4>
            <p>We send you off with a free iPhone phone to borrow. Make locals calls, take pictures and videos and upload them to our Facebook page for a chance to win cool prizes</p>
        </div><!--SINGLE-->
        <div class="single">
            <span class="icon3"></span>
            <h4>Satisfaction Insurance</h4>
            <p>If you aren't 100% satisfied with any part of your trip, we'll give you a full refund for that portion – no questions asked</p>
        </div><!--SINGLE-->
        <div class="clear"></div>
    </div><!--TRIPEXPERIENCE-->
    
    <img id="img1" src="https://static.tripfab.com/images6/tripsView4ico3.png" width="" height="" alt="" /> 

    <div id="cancel_policy" class="cancel_policy lb">
        <div class="top">High Restrictions Cancellation Policy</div>
        <div class="mid">
            <h3>50% refund up until 1 week prior to arrival, except fees</h3>
            <ul>
                <li>Cleaning fees are always refunded if the guest did not check in.</li>
                <li>The Tripfab service fee is non-refundable.</li>
                <li>If there is a complaint from either party, notice must be given to Tripfab 
                Resolution Center within 24 hours of check-in.</li>
                <li>Tripfab Resolution Center will mediate when necessary, and has the final say in all disputes.</li>
                <li>A reservation is not officially canceled until the guest receives a cancellation confirmation 
                e-mail from Tripfab Resolution Center.</li>
            </ul>
            <div class="inner">
                <img src="https://static.tripfab.com/images2/img-67-hotel.png" width="    " height="" alt="" />
                <div class="specs">
                    <div class="column">
                        <p>Must be made seven full days prior to listing's local check in time (or 2:00 PM 
                        if not specified) on the day of check in, otherwise no refund. For example, 
                        if check-in is on Friday, cancel by Friday of the previous</p>
                    </div><!--COLUMN-->
                    <div class="column">
                        <p>If the guest cancels less than 7 days in advance, the nights not spent are not refunded.</p>
                    </div><!--COLUMN-->
                    <div class="column last">
                        <p>If the guest arrives and decides to leave early, the nights not spent are not refunded.</p>
                    </div><!--COLUMN-->
                    <div class="clear"></div>
                </div><!--SPECS-->
            </div><!--INNER-->
        </div><!--MID-->
    </div><!--CANCEL_POLICY-->
</div><!--HIDDEN-->
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
$(document).ready(function() {
	$('a.lbc').fancybox({
		padding: 0,
		overlayColor: '#FFF',
		overlayOpacity: '0.7',
		showCloseButton:true
	});
	$('a.helptip').click(function() {
		$('.tip').toggleClass('hidden');
		return false;
	});
	$('a.high-r').hover(function() {
		$('.restricction_tip').toggleClass('hidden');
		return false;
	});
	$('.booknow').click(function(){
		$('#checkout').submit();
		return false;
	});        
});
</script>
</body>
</html>