<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
	<meta content="noindex,nofollow" name="robots" />
	<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
	<title>Tripfab.com</title>
	<link type="text/css"  rel="stylesheet" href="/css6/reset.css?v=<?= $this->cssVC ?>" />
	<link type="text/css"  rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
	<link type="text/css"  rel="stylesheet" href="/css6/landing/thankyou.css?v=<?= $this->cssVC ?>" />
</head>
<body id="confirm">
<div id="wp_all">
    <div id="wp_header">
        <div id="header" class="in2">
            <div class="wrapper">
                <h1 class="logo"><a href="">Tripfab</a></h1>
                <div class="contact">
                    <a href="#" class="btn-1">Live Chat Now</a>
                    <p>Questions?<strong>Call 1-866-401-0382</strong></p>
                </div><!--CONTACT-->
            </div><!--WRAPPER-->
        </div><!--HEADER-->
        
        <div class="subHeader">
            <div class="cntrl">
                <ul class="breadcrump">
                    <li class="first"><a class="home" href="/"></a></li>
                    <li><a href="">All Inclusive Trips</a></li>
                </ul>
                <a class="link1" href="/costa_rica/san_jose/">&larr; Back to Results</a>
                <div class="clear"></div>
            </div>
        </div><!--SUBHEADER-->
    </div><!--WP_HEADER-->
    
    <div id="wp_content">
        <div id="content">
            <h2>Confirmation</h2>
            <div class="top">
                <span class="icon"></span>
                <div class="inside">
                    <h2>Thank You Karina Romaine!</h2>
                    <h3>We wish you the best trip in your life!</h3>
                </div><!--INSIDE-->
            </div><!--TOP-->
            <div class="main">
                <div class="head">
                    <div class="text">
                        <h4>Your payment is done!</h4>
                        <p>You will receive a confirmation in your e-mail. If we decline your request, no charge is made. </p>
                    </div><!--TEXT-->
                    <a href="" class="btn-10"><em></em>Print Reservation</a>
                </div><!--HEAD-->
                <div class="cont">
                    <h5>
                        <strong>Reservation Details</strong>
                        <span class="code">Reservation Code: AS231541</span>
                    </h5>
                    <div class="title">
                        <img src="https://static.tripfab.com/images6/tripsView4ico3.png" width="55" height="55" alt="" />
                        <h6>Allegro Papagayo's All Inclusive</h6>
                        <span>Costa Rica</span>
                        <div class="clear"></div>
                    </div><!--TITLE-->
                    
                    <div class="single">
                        <h6>Payment</h6>
                        <ul>
                            <li>
                                <strong>Credit Card</strong>
                                <p>MasterCard | Last digits: 4028</p>
                            </li>
                            <li></li>
                        </ul>
                    </div><!--SINGLE-->
                    <div class="single">
                        <h6>Reservation Details</h6>
                        <ul>
                            <li>
                                <strong>Trip Starts</strong>
                                <p>Fri, September 23rd 2011</p>
                            </li>
                            <li>
                                <strong>Trips Ends</strong>
                                <p>Sat, September 29th 2011</p>
                            </li>
                            <li>
                                <strong>Trip Duration</strong>
                                <p>9 Days</p>
                            </li>
                            <li>
                                <strong>Travelers</strong>
                                <p>2 Adults, 2 Children</p>
                            </li>
                        </ul>
                    </div><!--SINGLE-->
                    <div class="single last">
                        <h6>Charges</h6>
                        <table width="280" cellspacing="0" cellpadding="0" border="0">
                            <tbody>
                                <tr class="before">
                                    <td>Package Regular Price</td>
                                    <td class="rg">$4510</td>
                                </tr>
                                <tr>
                                    <td>Special Price</td>
                                    <td class="rg"><strong>$4000</strong></td>
                                </tr>
                                <tr>
                                    <td>Tripfab Experience. <a href="#tripExperience" class="lbc link1">What is this?</a></td>
                                    <td class="fr">Free</td>
                                </tr>
                                <tr>
                                    <td>Additional Experiences</td>
                                    <td class="rg"><strong>$300</strong></td>
                                </tr>
                                <tr class="save">
                                    <td>Total Save</td>
                                    <td class="rg">$200</td>
                                </tr>
                                <tr class="total">
                                    <td>Total Paid</td>
                                    <td class="rg">$4300</td>
                                </tr>
                            </tbody>
                        </table>
                    </div><!--SINGLE-->
                </div><!--CONT-->
                <div class="contact">
                    <ul>
                        <li><strong>Questions?</strong></li>
                        <li><span class="ph"></span>1-866-401-0382</li>
                        <li><a href="mailto:hello@tripfab.com">service@tripfab.com </a></li>
                        <li><a href="" class="link1">Live Chat Now</a></li>
                    </ul>
                </div><!--CONTACT-->
            </div><!--MAIN-->
            <div class="bot">
                <h6>Do you want to explore Costa Rica and get the best deals?</h6>
                <p>We have tons of Hotels, exciting Activities, and amazing Pre-Planned Trips for your next vacation around Costa Rica</p>
                <a href="#" class="btn-1">Take a Look</a>
            </div><!--BOT-->
        </div><!--CONTENT-->
    </div><!--WP_CONTENT-->
</div><!--WRAPPER_ALL-->
<div class="hidden"></div>
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
$(document).ready(function() {
	$(".tabs").tabs({
		selected: 2
	});
	
	$('.date input').datepicker({ 
		showOtherMonths: true,
		dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S']
	});
	$('a.lbc').fancybox({
		padding: 10,
		overlayColor: '#FFF',
		overlayOpacity: '0.7',
		showCloseButton: true,
		centerOnScroll: true,
		titlePosition: 'inside'
	});
	$('#fancybox-title').addClass('tittle');
	$('#fancybox-left-ico').addClass('lfarrow');
	$('#fancybox-right-ico').addClass('rgarrow');
});
</script>
</body>
</html>