<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
	<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
	<title>Tripfab.com</title>
	<link type="text/css"  rel="stylesheet" href="/css6/reset.css?v=<?= $this->cssVC ?>" />
	<link type="text/css"  rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
	<link type="text/css"  rel="stylesheet" href="/css6/landing/thankyou.css?v=<?= $this->cssVC ?>" />
</head>
<body id="confirm">
<div id="wp_all">
    <div id="wp_header">
        <div id="header" class="in2">
            <div class="wrapper">
                <h1 class="logo"><a href="/">Tripfab</a></h1>
                <div class="contact">
                    <a href="#" onclick="SnapABug.startChat('How can I help you today?'); return false;" class="btn-1">Live Chat Now</a>
                    <p>Questions?<strong>Call 1-866-401-0382</strong></p>
                </div><!--CONTACT-->
            </div><!--WRAPPER-->
        </div><!--HEADER-->
        
        <div class="subHeader">
            <div class="cntrl">
                <ul class="breadcrump">
                    <li class="first"><a class="home" href="/"></a></li>
                    <li><a href="/landing/1/allinclusive">All Inclusive Trips</a></li>
                </ul>
                <a class="link1" href="/landing/1/allinclusive">&larr; Back to Results</a>
                <div class="clear"></div>
            </div>
        </div><!--SUBHEADER-->
    </div><!--WP_HEADER-->
    
    <div id="wp_content">
        <div id="content">
            <h2>Confirmation</h2>
            <div class="top">
                <span class="icon"></span>
                <div class="inside">
                    <h2>Thank you, <?= $this->info->name ?>!</h2>
                    <h3>We wish you the trip of a lifetime!</h3>
                </div><!--INSIDE-->
            </div><!--TOP-->
            <div class="main">
                <div class="head">
                    <div class="text">
                        <h4>Your payment is done!</h4>
                        <p>You will receive a confirmation e-mail. If we decline your request, no charge will be made. </p>
                    </div><!--TEXT-->
                    <a href="#" onclick="window.print(); return false;" class="btn-10"><em></em>Print Reservation</a>
                </div><!--HEAD-->
                <div class="cont">
                    <h5>
                        <strong>Reservation Details</strong>
                    </h5>
                    <div class="title">
                        <img src="https://static.tripfab.com/images6/tripsView4ico3.png" width="55" height="55" alt="" />
                        <h6><?= $this->hotel ?></h6>
                        <span>Costa Rica</span>
                        <div class="clear"></div>
                    </div><!--TITLE-->
                    
                    <div class="single">
                        <h6>Payment</h6>
                        <ul>
                            <li>
                                <strong>Credit Card</strong>
                                <p><?= $this->card->type ?> | Last digits: <?= $this->card->last4 ?></p>
                            </li>
                            <li></li>
                        </ul>
                    </div><!--SINGLE-->
                    <div class="single">
                        <h6>Reservation Details</h6>
                        <ul>
                            <li>
                                <strong>Arrival</strong>
                                <p><?= date('D, F jS, Y', strtotime($this->info->arrival)) ?></p>
                            </li>
                            <li>
                                <strong>Departure</strong>
                                <p><?= date('D, F jS, Y', strtotime($this->info->departure)) ?></p>
                            </li>
                            <li>
                                <strong>Trip Duration</strong>
                                <p><?= $this->info->nights ?> Nights</p>
                            </li>
                            <li>
                                <strong>Travelers</strong>
                                <p><?= $this->info->adults ?> Adults<?php if($this->info->childs > 0): ?>, 
								<?= $this->info->childs ?> Children<?php endif ?></p>
                            </li>
                        </ul>
                    </div><!--SINGLE-->
                    <div class="single last">
                        <h6>Charges</h6>
                        <table width="280" cellspacing="0" cellpadding="0" border="0">
                            <tbody>
                                <?php if($this->info->additional): ?>
                                <tr>
                                    <td>Special Price</td>
                                    <td class="rg"><strong>$<?= $this->info->price - $this->info->additional ?></strong></td>
                                </tr>
                                <?php else: ?>
                                <tr>
                                    <td>Special Price</td>
                                    <td class="rg"><strong>$<?= $this->info->price ?></strong></td>
                                </tr>                                
                                <?php endif ?>
                                <tr>
                                    <td>Tripfab Experience</td>
                                    <td class="fr">Free</td>
                                </tr>
                                <?php if($this->info->additional): ?>
                                <tr>
                                    <td>Additional Experiences</td>
                                    <td class="rg"><strong>$<?= $this->info->additional ?></strong></td>
                                </tr>
                                <?php endif ?>
                                <tr class="total">
                                    <td>Total Paid</td>
                                    <td class="rg">$<?= $this->info->price ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div><!--SINGLE-->
                </div><!--CONT-->
                <div class="contact">
                    <ul>
                        <li><strong>Questions?</strong></li>
                        <li><span class="ph"></span>1-866-401-0382</li>
                        <li><a href="mailto:service@tripfab.com">service@tripfab.com </a></li>
                        <li><a href="" onclick="SnapABug.startChat('How can I help you today?'); return false;" class="link1">Live Chat Now</a></li>
                    </ul>
                </div><!--CONTACT-->
            </div><!--MAIN-->
            <div class="bot">
                <h6>Do you want to explore Costa Rica and get the best deals?</h6>
                <p>We have tons of hotels, exciting activities, and amazing pre-planned trips for your next vacation to Costa Rica</p>
                <a href="/costa_rica" class="btn-1">Take a Look</a>
            </div><!--BOT-->
        </div><!--CONTENT-->
    </div><!--WP_CONTENT-->
</div><!--WRAPPER_ALL-->
<div class="hidden"></div>
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24981182-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<script type="text/javascript">
document.write(unescape("%3Cscript src='" + ((document.location.protocol=="https:")?"https://snapabug.appspot.com":"http://www.snapengage.com") + "/snapabug.js' type='text/javascript'%3E%3C/script%3E"));</script>
<script type="text/javascript">
//SnapABug.setButton("https://static.tripfab.com/images/Live-Chat-Button.png");
//SnapABug.addButton("12926583-ebae-4874-8f3e-57cbe2114ebc","0","55%");
SnapABug.init("12926583-ebae-4874-8f3e-57cbe2114ebc");
SnapABug.setCallback('StartChat', function(email, msg, type) {
	var img = document.createElement('img');
	img.src = "https://www.googleadservices.com/pagead/conversion/956485843/?value=0&amp;label=T64ECJWh8gMQ06GLyAM&amp;guid=ON&amp;script=0";
	img.width = 1; img.height = 1;
	document.body.appendChild(img);
});
</script>
</body>
</html>