<?php $l = strtotime('Next Sunday') - time();
$d1 = ($l - ($l % 86400)); $h1 = $l - $d1; $h2 = $h1 - ($h1 % 3600); $m1 = $h1 - $h2; $m2 = $m1 - ($m1 % 60);
$days = $d1 / 86400; $hours = $h2 / 3600; $minutes = $m2 / 60; $seconds = $m1 - $m2; 
$nights = array(3,4,5,7,10,15) ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title>Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css6/reset.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/common.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/css6/landing/all2.css?v=<?= $this->cssVC ?>" />
    <link type="text/css" rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css?v=<?= $this->cssVC ?>" />
    <link type="text/css"  rel="stylesheet" href="/css6/calendar.css?v=<?= $this->cssVC ?>" />
    <style type="text/css">
	.image { display:none;} .image.show { display:block;}
	</style>
</head>
<body id="trip_all2">
<div id="wp_all">
    <div id="wp_header">
        <div id="header" class="in2">
            <div class="wrapper">
                <h1 class="logo"><a href="">Tripfab</a></h1>
                <div class="contact">
                    <a href="#" onclick="SnapABug.startChat('How can I help you today?'); return false;" class="btn-1">Live Chat Now</a>
                    <p>Questions?<strong>Call 1-866-401-0382</strong></p>
                </div><!--CONTACT-->
            </div><!--WRAPPER-->
        </div><!--HEADER-->
        
        <div class="subHeader">
            <div class="cntrl">
                <ul class="breadcrump">
                    <li class="first"><a class="home" href="/"></a></li>
                    <li><a href="">All Inclusive Trips</a></li>
                </ul>
                <a class="link1" href="">&larr; Back to Results</a>
                <div class="clear"></div>
            </div>
        </div><!--SUBHEADER-->
    </div><!--WP_HEADER-->
    
    <div id="wp_content">
        <div id="content">
            <div class="left">
                <div class="offer">
                    <span class="hurry"></span>
                    <div class="text">
                        <h2>Offer of the week</h2>
                        <h3>Time Remaining to Book this Trip</h3>
                    </div>
                    <div class="counter">
                        <div class="each first">
                            <strong class="jsd"><?= $days ?></strong>
                            <span>Days</span>
                        </div><!--EACH-->
                        <div class="each">
                            <strong class="jsh"><?= $hours ?></strong>
                            <span>HOURS</span>
                        </div><!--EACH-->
                        <div class="each">
                            <strong class="jsm"><?= $minutes ?></strong>
                            <span>MINUTES</span>
                        </div><!--EACH-->
                        <div class="each last">
                            <strong class="jss"><?= $seconds ?></strong>
                            <span>SECONDS</span>
                        </div><!--EACH-->								
                    </div><!--COUNTER-->
                </div><!--OFFER-->
            
                <div class="picture">
                	<?php foreach($this->info['images'] as $id => $img): ?>
                    <div id="js-image<?= $id ?>" class="js-image image <?= ($id == 0) ? 'show' : '' ?>">
                        <img src="<?= $img['url'] ?>" width="650" height="285" alt="" />
                        <div class="title">
                            <h2><?= $this->info['title'] ?> – <?= $this->info['nights'] ?> Nights</h2>
                            <h3>All Inclusive</h3>
                        </div><!--TITLE-->
                        <div class="descrip"><?= $id ?> - <?= $img['desc'] ?> 
                        <a href="<?= $img['big'] ?>" rel="group1" class="js-fancybox"></a></div><!--DESCRIP-->
                    </div><!--IMAGES-->
                    <?php endforeach ?>
                    
                    <div class="carousel">
                        <div class="prev"></div>
                        <ul>
		                	<?php foreach($this->info['images'] as $id => $img): ?>
                            <li><a class="js-change-image" href="#js-image<?= $id ?>"><img src="<?= $img['thumb'] ?>" width="59" height="59" alt="" /></a></li>
                            <?php endforeach ?>
                        </ul>
                        <div href="" class="next"></div>	
                    </div><!--CAROUSEL-->
                </div><!--PICTURE-->
                                    
                <div class="features">
                    <h4>All Inclusive Features</h4>
                    <?php $count = count($this->info['features']); ?>
                    <?php $aux 	 = $count % 2; ?>
                    <?php $limit = ($aux > 0) ? ((($count - 1) / 2) + 1) : ($count / 2); ?>
                    <?php for($i=0;$i<=$count;$i=$i+$limit): ?>
                    <ul>
                    	<?php for($j=$i;($j<($i+$limit)) and ($j<$count); $j++): ?>
                        <li><?= $this->info['features'][$j] ?></li>
                        <?php endfor ?>
                    </ul>
                    <?php endfor ?>
                    <div class="clear"></div>
                </div><!--FEATURES-->
                
                <div class="other">
                    <div class="single">
                        <h5><?= $this->info['title'] ?></h5>
                        <p><?= $this->info['description'] ?></p>
                    </div><!--DESCRIPTION-->
                    
                    
                    <div class="single">
                        <h5>Dining:</h5>
                        <p><?= $this->info['dining'] ?></p>
                        <dl>
                        	<?php foreach($this->info['restaurants'] as $r): ?>
                            <dt><?= $r['title'] ?></dt>
                            <dd><?= $r['description'] ?></dd>
                            <?php endforeach ?>
                        </dl>
                    </div><!--FOOD-->
                    
                    <?php foreach($this->info['overview'] as $o): ?>
                    <div class="single">
                        <h5><?= $o['title'] ?></h5>
                        <ul>
                        	<?php foreach($o['points1'] as $p): ?>
                            <li><?= $p ?></li>
                            <?php endforeach ?>
                        </ul>
                        <ul>
                            <?php foreach($o['points2'] as $p): ?>
                            <li><?= $p ?></li>
                            <?php endforeach ?>
                        </ul>
                        <div class="clear"></div>
                    </div><!--ACTIVITIES-->
                    <?php endforeach ?>
                </div><!--OTHER-->
            </div><!--LEFT-->
            
            <div class="right">
                <div class="price">
                    <div class="left">
                        <span class="top">From</span>
                        <span class="mid"><sup>$</sup>
                        <?= str_replace('.','<sub>.',number_format($this->info['price'],2,'.',',')) ?></sub></span>
                        <span class="bot">Per person, per night</span>
                    </div><!--LEFT-->
                    <div class="right">
                        <sup>$</sup>
                        <span><?= str_replace('.','</span><sub>.',number_format($this->info['price_before'],2,'.',',')) ?></sub>
                    </div><!--RIGHT-->
                    <div class="bot">
                        <strong>Save $<?= $this->info['save'] ?></strong> per person per night
                    </div><!--BOTTOM-->
                </div><!--PRICE-->
                
                <div class="customize">
                    <h5>Customize Your Trip & Book</h5>
                    <form method="post" action="/en-US/landing/2/checkout">
                        <div class="fields">
                            <div class="block1">
                                <div class="date">
                                    <label>Travel Date</label>
                                    <input type="text" name="date" value="" class="js-calendar" />
                                    <span></span>
                                </div>
                                <div class="select">
                                    <label>Kids</label>
                                    <select name="kids" class="js-change js-kids">
                                    	<?php for($i=0;$i<=10;$i++): ?>
                                        <option value="<?= $i ?>"><?= $i ?></option>
                                        <?php endfor ?>
                                    </select>
                                </div><!--SELECT-->
                                <div class="select">
                                    <label>Adults</label>
                                    <select name="adults" class="js-adults js-change">
                                    	<?php for($i=2;$i<=20;$i++): ?>
                                        <option value="<?= $i ?>"><?= $i ?></option>
                                        <?php endfor ?>
                                    </select>
                                </div><!--SELECT-->
                                <div class="clear"></div>
                            </div><!--BLOCK1-->
                            
                            <div class="accordion">
                                <h6>Room Type</h6>
                                <div class="block2">
                                    <table width="272" border="0" cellspacing="0" cellpadding="0" class="js-room-table">
                                    	<?php foreach($this->rooms as $i => $room): ?>
                                        <?php $checked = (isset($room['selected'])) ? 'checked="checked"': '' ?>
                                        <tr>
                                            <td width="190"><label><input data-included="<?= isset($room['selected']) ?>" type="radio" name="room" 
                                            data-price="<?= $room['price'] ?>" value="<?= $room['id'] ?>" <?= $checked ?> class="js-room js-change" 
                                            data-label="<?= $room['name'] ?>" /> <?= $room['name'] ?></label></td>
                                            <td id="js-room-<?= $i ?>" class="rg">
                                            <?php if($room['selected'] != 1): ?>
                                            <?php $p = $room['price'] * 2 * $this->info['nights'] ?>
                                            <?= ($p > 0) ? '+ $'.$p : '- $'.abs($p) ?>
                                            <?php else: ?>
                                            Included
                                            <?php endif ?>
                                            </td>
                                        </tr>
                                        <?php endforeach ?>
                                    </table>
                                    <span class="line"></span>
                                </div><!--BLOCK2-->
                                
                                <h6>Extra Nights?</h6>
                                <div class="block2">
                                    <table width="272" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td width="190">
                                            <select name="nights" class="js-change js-nights">
                                                <option value="<?= $this->info['nights'] ?>"><?= $this->info['nights'] ?> Nights</option>
                                                <?php for($i=($this->info['nights'] + 1); $i<=15; $i++): ?>
                                                <option value="<?= $i ?>"><?= $i ?> Nights</option> 
                                                <?php endfor ?>
                                            </select>
                                            </td>
                                            <td class="rg js-nights-lb">Included</td>
                                        </tr>
                                    </table>
                                    <span class="line"></span>
                                </div><!--BLOCK2-->
                                
                                <?php if(count($this->activities) > 0): ?>
                                <h6>Additional Activities</h6>
                                <div class="block2">
                                    <table width="272" border="0" cellspacing="0" cellpadding="0" class="js-activity-table">
	                                    <?php foreach($this->activities as $i=>$a): ?>
                                        <tr>
                                            <td width="190"><label><input type="checkbox" class="js-activity js-change" value="<?= $a['id'] ?>" 
                                            data-price="<?= $a['price'] ?>" name="activities[]" data-label="<?= $a['name'] ?>" />
											<?= $a['name'] ?></label></td>
                                            <td id="js-activity-<?= $i ?>" class="rg">
                                            <?= '+ $'.($a['price'] * 2) ?>
                                            </td>
                                        </tr>
										<?php endforeach ?>
                                    </table>
                                </div><!--BLOCK2-->
                                <?php endif ?>
                            </div><!--ACCORDION-->
                            
                            <div class="total"> 
                                <div class="left">
                                    <span class="top">Trip Total </span>
                                    <span class="mid js-price-lb"><sup>$</sup>
                                    <?= str_replace('.','<sub>.',number_format($this->info['price']*2*$this->info['nights'],2,'.',',')) ?></sub></span>
                                </div><!--LEFT-->
                                <div class="right js-before-lb">
                                    <sup>$</sup><span><?= str_replace('.','</span><sub>.',
									number_format($this->info['price_before']*2*$this->info['nights'],2,'.',',')) ?></sub>
                                </div><!--RIGHT-->
                                <input class="btn-1" type="submit" name="" value="Book Now" />
                                <div class="bot js-save-lb">
                                    Total Saving $
									<?= ($this->info['price_before']*2*$this->info['nights']) - ($this->info['price']*2*$this->info['nights']) ?>
                                </div>
                            </div><!--TOTAL-->
                        </div><!--FIELDS-->
                        <input type="hidden" class="js-price" value="<?= $this->info['price'] ?>"/>
                        <input type="hidden" class="js-price-before" value="<?= $this->info['price_before'] ?>"/>
                        <input type="hidden" name="package" value="<?= md5($this->id) ?>" />
                    </form>
                </div><!--CUSTOMIZE-->
                <div class="talk">
                    <strong>Questions about the trip?</strong>
                    <span>Call 1-866-401-0382</span>
                </div><!--TALK-->
            </div><!--RIGHT-->
            <div class="clear"></div>
        </div><!--CONTENT-->
    </div><!--WP_CONTENT-->
</div><!--WRAPPER_ALL-->
<div class="hidden"></div>
<script type="text/javascript" src="/js2/jquery.js?v=<?= $this->cssVC ?>"></script>
<script type="text/javascript">
$(document).ready(function() {
	$(".tabs").tabs({
		selected: 2
	});
	$("#addons .accordion").accordion({
		autoHeight: false,
		collapsible: true
	});
	$('.js-change-image').click(function(){
		var href = $(this).attr('href');
		$('.js-image').removeClass('show');
		$(href).addClass('show');
		return false;
	});
	$('.js-fancybox').fancybox({
		overlayColor:'#fff',
		padding:5,
		centerOnScroll:1
	});
	
	$expires = <?= strtotime('Next Sunday') ?>;
	$now	 = <?= time() ?>;
	
	setInterval(function(){
		$now += 1; $l = $expires - $now;
		$d1 = ($l - ($l % 86400)); $h1 = $l - $d1; $h2 = $h1 - ($h1 % 3600); $m1 = $h1 - $h2; $m2 = $m1 - ($m1 % 60);
		$days = $d1 / 86400; $hours = $h2 / 3600; $minutes = $m2 / 60; $seconds = $m1 - $m2;
		$('.jsd').text($days); $('.jsh').text($hours); $('.jsm').text($minutes); $('.jss').text($seconds);
	},1000);
	
	$('.js-calendar').datepicker({
		minDate:new Date(),
		maxDate:new Date(2012,8,19),
		dateFormat:'MM d, yy'
	});
	
	$('.js-change').change(function(){
		calculate();
	});
	function calculate(){
		var price = parseFloat($('.js-price').val());
		var before = parseFloat($('.js-price-before').val());
		var _room  = $('.js-room:checked');
		var _activities = $('.js-activity:checked');
		var travelers  = parseInt($('.js-kids').val()) + parseInt($('.js-adults').val());
		var nights	   = parseInt($('.js-nights').val());
		
		
		if(_room.data('included') != 1) {
			var room = parseFloat(_room.data('price'));
			price = price + room;
		}
		
		$('.js-room-table tr').each(function(index){
			var p = parseFloat($('input', this).data('price')) * travelers * nights;
			if(p != 0) {
				if(p > 0){
					$('#js-room-'+index).text('+ $'+p);
				} else {
					$('#js-room-'+index).text('- $'+Math.abs(p));
				}
			} else {
				$('#js-room-'+index).text('Included');
			}
		});
		
		if(nights > <?= $this->info['nights'] ?>) {
			var n = (price * nights * travelers) - (price * <?= $this->info['nights'] ?> * travelers);
			$('.js-nights-lb').text('+ $'+n);
		} else {
			$('.js-nights-lb').text('Included');
		}
		
		$('.js-activity-table tr').each(function(index){
			var z = parseFloat($('input',this).data('price')) * travelers;
			$('#js-activity-'+index).text('+ $'+z);
		});
		
		var activities = 0;
		$('tr.js-activity-tr').remove();	
		
		if(_activities.length > 0) {
			$('.js-specsDiv').removeClass('hidden');
			_activities.each(function(){
				activities += ($(this).data('price') * travelers);
				$('.js-specsDiv table').append(
					'<tr class="js-activity-tr">'+
						'<td>'+$(this).data('label')+'</td>'+
						'<td class="rg">+ $'+($(this).data('price') * travelers)+'</td>'+
					'</tr>'
				);
			});
		} else {
			$('.js-specsDiv').addClass('hidden');
		}
		
		var total = (price * travelers * nights) + activities;
		var totalBefore = (before * travelers * nights) + activities;
		
		var save = totalBefore - total;
		
		$('.js-price-lb').html('<sup>$</sup> '+format(total.toFixed(2)).replace('.','<sub>.')+'</sub>');
		$('.js-before-lb').html('<sup>$</sup> <span>'+format(totalBefore.toFixed(2)).replace('.','</span><sub>.')+'</sub>');
		$('.js-save-lb').html('Total Saving $ '+save);
	}
	
	function format(nStr) {
		nStr += '';
		x = nStr.split('.');
		x1 = x[0];
		x2 = x.length > 1 ? '.' + x[1] : '';
		var rgx = /(\d+)(\d{3})/;
		while (rgx.test(x1)) {
			x1 = x1.replace(rgx, '$1' + ',' + '$2');
		}
		return x1 + x2;
	}
});
</script>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24981182-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<script type="text/javascript">
document.write(unescape("%3Cscript src='" + ((document.location.protocol=="https:")?"https://snapabug.appspot.com":"http://www.snapengage.com") + "/snapabug.js' type='text/javascript'%3E%3C/script%3E"));</script>
<script type="text/javascript">
//SnapABug.setButton("https://static.tripfab.com/images/Live-Chat-Button.png");
//SnapABug.addButton("12926583-ebae-4874-8f3e-57cbe2114ebc","0","55%");
SnapABug.init("12926583-ebae-4874-8f3e-57cbe2114ebc");
SnapABug.setCallback('StartChat', function(email, msg, type) {
	var img = document.createElement('img');
	img.src = "https://www.googleadservices.com/pagead/conversion/956485843/?value=0&amp;label=T64ECJWh8gMQ06GLyAM&amp;guid=ON&amp;script=0";
	img.width = 1; img.height = 1;
	document.body.appendChild(img);
});
</script>
</body>
</html>