<form action="" method="post" id="form_pricing">
    <div class="lstng-details pricing">
        <?php if($this->listing->main_type == 5): ?>
        <div class="lstng-detail">
            <strong>Regular Pricing</strong>
            <ul>
                <?php foreach($this->schedules as $sch): ?>
                <li>
                    <strong><?= $sch->name ?></strong>
                    <div>
                        <div class="row">
                            <label>Adults Rate</label>
                            <input type="text" name="sch[0][<?= $sch->id ?>][price]" 
                            value="<?= (isset($this->sch[0][$sch->id]['price'])) 
                            ? $this->sch[0][$sch->id]['price'] : "0.00" ?>"/>
                            <label>Kids Rate</label>
                            <input type="text" name="sch[0][<?= $sch->id ?>][kids]" 
                            value="<?= (isset($this->sch[0][$sch->id]['kids'])) 
                            ? $this->sch[0][$sch->id]['kids'] : "0.00" ?>"/>
                        </div>
                        <div class="row">
                            <label>Min</label>
                            <select name="sch[0][<?= $sch->id ?>][min]">
                                <?php foreach($this->persons as $i): ?>
                                <?php if($this->sch[0][$sch->id]['min'] == $i): ?>
                                <option selected="selected" value="<?= $i ?>"><?= $i ?></option>
                                <?php else: ?>
                                <option value="<?= $i ?>"><?= $i ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                            <label>Max</label>
                            <select name="sch[0][<?= $sch->id ?>][max]">
                                <?php foreach($this->persons as $i): ?>
                                <?php if($this->sch[0][$sch->id]['max'] == $i): ?>
                                <option selected="selected" value="<?= $i ?>"><?= $i ?></option>
                                <?php else: ?>
                                <option value="<?= $i ?>"><?= $i ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                        </div>
                        <div class="row">
                            <label>Additional</label>
                            <input type="text" name="sch[0][<?= $sch->id ?>][additional]" 
                            value="<?= (isset($this->sch[0][$sch->id]['additional'])) 
                            ? $this->sch[0][$sch->id]['additional'] : "0.00" ?>"/>
                            <label>Additional After</label>
                            <select name="sch[0][<?= $sch->id ?>][additional_after]">
                                <?php foreach($this->persons as $i): ?>
                                <?php if($this->sch[0][$sch->id]['additional_after'] == $i): ?>
                                <option selected="selected" value="<?= $i ?>"><?= $i ?></option>
                                <?php else: ?>
                                <option value="<?= $i ?>"><?= $i ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </li>
                <?php endforeach ?>
            </ul>
        </div><!-- closes lstng-detail -->
        <?php if(count($this->seasons) > 0): ?>
        <?php foreach($this->seasons as $season): ?>
        <div class="lstng-detail">
            <strong><?= $season->name ?></strong>
            <ul>
                <li>
                    <?= date('M j, Y', strtotime($season->starting)) ?> / <?= date('M j, Y', strtotime($season->ending)) ?>
                    <a href="" class="link-7">Delete</a>
                </li>
                <?php foreach($this->schedules as $sch): ?>
                <li>
                    <strong><?= $sch->name ?></strong>
                    <div>
                        <div class="row">
                            <label>Adults Rate</label>
                            <input type="text" name="sch[<?= $season->id ?>][<?= $sch->id ?>][price]" 
                            value="<?= (isset($this->season[$season->id][$sch->id]['price'])) 
                            ? $this->season[$season->id][$sch->id]['price'] : "0.00" ?>"/>
                            <label>Kids Rate</label>
                            <input type="text" name="sch[<?= $season->id ?>][<?= $sch->id ?>][kids]" 
                            value="<?= (isset($this->season[$season->id][$sch->id]['kids'])) 
                            ? $this->season[$season->id][$sch->id]['kids'] : "0.00" ?>"/>
                        </div>
                        <div class="row">
                            <label>Additional</label>
                            <input type="text" name="sch[<?= $season->id ?>][<?= $sch->id ?>][additional]" 
                            value="<?= (isset($this->season[$season->id][$sch->id]['additional'])) 
                            ? $this->season[$season->id][$sch->id]['additional'] : "0.00" ?>"/>
                        </div>
                    </div>
                </li>
                <?php endforeach ?>
            </ul>
        </div><!-- closes lstng-detail -->
        <?php endforeach ?>
        <?php endif ?>
        <div class="lstng-detail">
            <strong></strong>
            <ul>
                <li><a href="#" class="link-5">Add New Season</a></li>
            </ul>
        </div><!-- closes lstng-detail -->
        <?php else: ?>
        <div class="lstng-detail">
            <strong>Regular Pricing</strong>
            <ul>
                <li>
                    <strong></strong>
                    <div>
                        <div class="row">
                            <label>Adults Rate</label>
                            <input type="text" name="price" 
                            value="<?= (isset($this->basic_price->price)) ? $this->basic_price->price : "0.00" ?>"/>
                            <label>Kids Rate</label>
                            <input type="text" name="kids" 
                            value="<?= (isset($this->basic_price->kids)) ? $this->basic_price->kids : "0.00" ?>"/>
                        </div>
                        <div class="row">
                            <label>Min</label>
                            <select name="min">
                                <?php foreach($this->persons as $i): ?>
                                <?php if($this->basic_price->min == $i): ?>
                                <option selected="selected" value="<?= $i ?>"><?= $i ?></option>
                                <?php else: ?>
                                <option value="<?= $i ?>"><?= $i ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                            <label>Max</label>
                            <select name="max">
                                <?php foreach($this->persons as $i): ?>
                                <?php if($this->basic_price->max == $i): ?>
                                <option selected="selected" value="<?= $i ?>"><?= $i ?></option>
                                <?php else: ?>
                                <option value="<?= $i ?>"><?= $i ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                        </div>
                        <div class="row">
                            <label>Additional</label>
                            <input type="text" name="additional" 
                            value="<?= (isset($this->basic_price->additional)) ? $this->basic_price->additional : "0.00" ?>"/>
                            <label>Additional After</label>
                            <select name="additional_after">
                                <?php foreach($this->persons as $i): ?>
                                <?php if($this->basic_price->additional_after == $i): ?>
                                <option selected="selected" value="<?= $i ?>"><?= $i ?></option>
                                <?php else: ?>
                                <option value="<?= $i ?>"><?= $i ?></option>
                                <?php endif ?>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </li>
            </ul>
        </div><!-- closes lstng-detail -->
        <?php if(count($this->seasons) > 0): ?>
        <?php foreach($this->seasons as $season): ?>
        <div class="lstng-detail">
            <strong><?= $season->name ?></strong>
            <ul>
                <li>
                    <strong><?= $sch->name ?></strong>
                    <div>
                        <div class="row">
                            <label>Adults Rate</label>
                            <input type="text" name="price" 
                            value="<?= (isset($this->season[$season->id]['price'])) 
                            ? $this->season[$season->id]['price'] : "0.00" ?>"/>
                            <label>Kids Rate</label>
                            <input type="text" name="kids" 
                            value="<?= (isset($this->season[$season->id]['kids'])) 
                            ? $this->season[$season->id]['kids'] : "0.00" ?>"/>
                        </div>
                        <div class="row">
                            <label>Additional</label>
                            <input type="text" name="additional" 
                            value="<?= (isset($this->season[$season->id]['additional'])) 
                            ? $this->season[$season->id]['additional'] : "0.00" ?>"/>
                        </div>
                    </div>
                </li>
            </ul>
        </div><!-- closes lstng-detail -->
        <?php endforeach ?>
        <div class="lstng-detail">
            <strong></strong>
            <ul>
                <li><a href="#" class="link-5">Add New Season</a></li>
            </ul>
        </div><!-- closes lstng-detail -->
        <?php endif ?>
        <?php endif ?>
        <div class="lstng-detail">
            <strong>Cancellation Policy</strong>
            <select>
                <option>Flexible</option>
                <option>Flexible</option>
                <option>Flexible</option>
            </select>
            <a href="">Learn More</a>
        </div><!-- closes lstng-detail -->
        <div class="lstng-detail">
            <textarea cols="30" rows="1"></textarea>
            <strong>Restrictions</strong>
            <span>Write all the restrctions that people <br /> should know about this activity</span>
        </div><!-- closes lstng-detail -->
    </div><!-- closes lstng-details -->
    <div class="foot">
        <input type="submit" class="btn-1" value="Save Changes" />
        <a href="/provider/listings/desactivate/<?= $this->listing->id ?>">Deactivate Listing</a>
    </div><!-- closes foot -->
    <input type="hidden" name="ids" value="<?= $this->listing->id ?>" />
    <input type="hidden" name="listing_token" value="<?= $this->listing->token ?>" />
    <input type="hidden" name="form_id" value="<?= md5($this->listing->token.'form_pricing') ?>" />
    <input type="hidden" name="_task" value="<?= md5('update_pricing') ?>" />
</form>