<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Profile | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js2/jquery.input.value.js"></script>
    <script type="text/javascript" src="/js/jquery.jqtransform.js"></script>
    <script type="text/javascript" src="/js2/jquery.elastic.js"></script>
    <script type="text/javascript" src="/js2/common.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('textarea').elastic();				
            $('input, textarea').ToggleInputValue();
            $('form select').jqTransSelect();
        });
    </script>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages">
            <?= $this->partial('partials/vendormainmenu.phtml', array('active'=>'Reviews','parentActive'=>'Reviews \&amp; Questions')); ?>			
            <div class="bc">
                <a href="" class="link-4">Back to Reviews</a>
                You have 2 new reviews for 'Hotel Silencio'
            </div>
            <!-- closes bc -->
            <div class="reviews-questions rev">
                <div class="s-qa new">
                    <div class="q">
                        <div class="left">
                            <strong>Karina Romaine</strong>
                            <span>Asked on Apr 25, 2011</span>
                        </div>
                        <!-- closes left -->
                        <div class="right">
                            Consectetur adipiscing elit. Duis ullamcorper arcu id eros faucibus pulvinar. Duis pellentesque molestie enim, a tinci dunt lorem tristique ac duis ullamcorper arcu id eros faucibus pulvinar. Duis pellentesque molestie enim, a tinci dunt lorem tristique ac. Donec ac justo quis odio molestie tristique. Consectetur ullamcorper arcu id eros faucibus pulvinar adipiscing elit. Duis ullamcorper arcu id eros faucibus pulvinar.
                        </div>
                        <!-- closes right -->
                    </div>
                    <!-- closes q -->
                    <div class="bottom">
                        <div class="right">
                            <a href="">Report Abuse</a>
                            <a href="" class="btn-1">Mark as Read</a>
                            <a href="" class="btn-4">Contact Client</a>
                        </div>
                        <!-- closes right -->
                    </div>
                    <!-- closes bottom -->
                    <div class="timespan">
                        <span>New</span>
                    </div>
                    <!-- closes timespan -->
                </div>
                <!-- closes s-qa -->	
                <div class="s-qa new">
                    <div class="q">
                        <div class="left">
                            <strong>Karina Romaine</strong>
                            <span>Asked on Apr 25, 2011</span>
                        </div>
                        <!-- closes left -->
                        <div class="right">
                            Consectetur adipiscing elit. Duis ullamcorper arcu id eros faucibus pulvinar. Duis pellentesque molestie enim, a tinci dunt lorem tristique ac duis ullamcorper arcu id eros faucibus pulvinar. Duis pellentesque molestie enim, a tinci dunt lorem tristique ac. Donec ac justo quis odio molestie tristique. Consectetur ullamcorper arcu id eros faucibus pulvinar adipiscing elit. Duis ullamcorper arcu id eros faucibus pulvinar.
                        </div>
                        <!-- closes right -->
                    </div>
                    <!-- closes q -->
                    <div class="bottom">
                        <div class="right">
                            <a href="">Report Abuse</a>
                            <a href="" class="btn-1">Mark as Read</a>
                            <a href="" class="btn-4">Contact Client</a>
                        </div>
                        <!-- closes right -->
                    </div>
                    <!-- closes bottom -->
                    <div class="timespan">
                        <span>New</span>
                    </div>
                    <!-- closes timespan -->
                </div>
                <!-- closes s-qa -->
                <div class="s-qa">
                    <div class="q">
                        <div class="left">
                            <strong>Karina Romaine</strong>
                            <span>Asked on Apr 25, 2011</span>
                        </div>
                        <!-- closes left -->
                        <div class="right">
                            Consectetur adipiscing elit. Duis ullamcorper arcu id eros faucibus pulvinar. Duis pellentesque molestie enim, a tinci dunt lorem tristique ac duis ullamcorper arcu id eros faucibus pulvinar. Duis pellentesque molestie enim, a tinci dunt lorem tristique ac. Donec ac justo quis odio molestie tristique. Consectetur ullamcorper arcu id eros faucibus pulvinar adipiscing elit. Duis ullamcorper arcu id eros faucibus pulvinar.
                        </div>
                        <!-- closes right -->
                    </div>
                    <!-- closes q -->
                    <div class="bottom">
                        <div class="right">
                            <a href="">Report Abuse</a>
                            <a href="" class="btn-4">Contact Client</a>
                        </div>
                        <!-- closes right -->
                    </div>
                    <!-- closes bottom -->
                </div>
                <!-- closes s-qa -->				
                <div class="s-qa">
                    <div class="q">
                        <div class="left">
                            <strong>Karina Romaine</strong>
                            <span>Asked on Apr 25, 2011</span>
                        </div>
                        <!-- closes left -->
                        <div class="right">
                            Consectetur adipiscing elit. Duis ullamcorper arcu id eros faucibus pulvinar. Duis pellentesque molestie enim, a tinci dunt lorem tristique ac duis ullamcorper arcu id eros faucibus pulvinar. Duis pellentesque molestie enim, a tinci dunt lorem tristique ac. Donec ac justo quis odio molestie tristique. Consectetur ullamcorper arcu id eros faucibus pulvinar adipiscing elit. Duis ullamcorper arcu id eros faucibus pulvinar.
                        </div>
                        <!-- closes right -->
                    </div>
                    <!-- closes q -->
                    <div class="bottom">
                        <div class="right">
                            <a href="">Report Abuse</a>
                            <a href="" class="btn-4">Contact Client</a>
                        </div>
                        <!-- closes right -->
                    </div>
                    <!-- closes bottom -->
                </div>
                <!-- closes s-qa -->				
            </div>
            <!-- closes reviews-questions -->
        </div>
        <!-- closes user-messages -->
    </div>
    <!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div>
<!-- closes w1 -->
</body>
</html>