<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content="noindex,nofollow" name="robots" />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <title><?= $this->user->name ?> : Profile | Tripfab.com</title>
    <link type="text/css" rel="stylesheet" href="/css2/reset.css" />
    <link type="text/css" rel="stylesheet" href="/css2/all.css" />
    <link type="text/css" rel="stylesheet" href="/css2/common.css" />
    <link type="text/css" rel="stylesheet" href="/css/jqtransform.css" />
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js2/jquery.input.value.js"></script>
    <script type="text/javascript" src="/js/jquery.jqtransform.js"></script>
    <script type="text/javascript" src="/js2/jquery.elastic.js"></script>
    <script type="text/javascript" src="/js2/common.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('textarea').elastic();				
            $('input').ToggleInputValue();
            $('form select').jqTransSelect();
        });
    </script>
</head>
<body>
<div class="w1">
    <?= $this->partial('partials/header.phtml', array('user'=>$this->user,'full'=>false)); ?>
    <div class="w2">
        <div class="wrapper user-messages">
            <?= $this->partial('partials/vendormainmenu.phtml', array('active'=>'Reviews','parentActive'=>'Reviews \&amp; Questions')); ?>
            <div class="reviews-questions">
                <div class="s-question">
                    <div class="right">
                        <div>
                            <a href="/provider/reviews/view/" class="btn-4">See Reviews</a>
                        </div>
                        <div>
                            <span>3</span> New Reviews
                        </div>
                    </div>
                    <!-- closes right -->
                    <img src="/images2/img-30.png" alt="" />
                    <h2><img src="/images2/ico-12.png" alt="" />Hotel Silencio</h2>
                </div>
                <!-- closes s-question -->
                <div class="s-question">
                    <div class="right">
                        <div>
                            <a href="/provider/reviews/view/" class="btn-4">See Reviews</a>
                        </div>
                    </div>
                    <!-- closes right -->
                    <img src="/images2/img-30.png" alt="" />
                    <h2><img src="/images2/ico-13.png" alt="" />Turtle Watching</h2>
                </div>
                <!-- closes s-question -->
                <div class="s-question">
                    <div class="right">
                        <div>
                            <a href="/provider/reviews/view/" class="btn-4">See Reviews</a>
                        </div>
                    </div>
                    <!-- closes right -->
                    <img src="/images2/img-30.png" alt="" />
                    <h2><img src="/images2/ico-13.png" alt="" />Turtle Watching</h2>
                </div>
                <!-- closes s-question -->
                <div class="s-question">
                    <div class="right">
                        <div>
                            <a href="/provider/reviews/view/" class="btn-4">See Reviews</a>
                        </div>
                    </div>
                    <!-- closes right -->
                    <img src="/images2/img-30.png" alt="" />
                    <h2><img src="/images2/ico-13.png" alt="" />Turtle Watching</h2>
                </div>
                <!-- closes s-question -->
            </div>
            <!-- closes reviews-questions -->
        </div>
        <!-- closes user-messages -->
    </div>
    <!-- closes w2 -->
    <?= $this->partial('partials/footer.phtml'); ?>
</div>
<!-- closes w1 -->
</body>
</html>